local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "1")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "28744", "Head", "Uni-Mind Headdress", "BIS")
LoonBestInSlot:AddItem(spec, "23828", "Head", "Gnomish Power Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "29093", "Head", "Antlers of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28804", "Head", "Collar of Cho'gall", "Alt")

LoonBestInSlot:AddItem(spec, "29095", "Shoulders", "Pauldrons of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", "Spaulders of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "27738", "Shoulders", "Incanter's Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "31797", "Shoulders", "Elekk Hide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "Alt")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran", "Alt")

LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29091", "Chest", "Chestpiece of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "BIS")

LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "BIS")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28453", "Bracers", "Bracers of the White Stag", "Alt")

LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "BIS")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "29092", "Gloves", "Gloves of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "BIS")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "BIS")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "28654", "Belt", "Malefic Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "BIS")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling", "BIS")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers", "BIS")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice", "Alt")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "Alt")

LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "BIS")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "BIS")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt")

LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "BIS")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "BIS")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "Alt")

LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "BIS")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "BIS")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")

LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "BIS")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "Alt")

LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "BIS")

LoonBestInSlot:AddItem(spec, "29271", "OH", "Talisman of Kalecgos", "BIS")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "BIS")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane", "Alt")

LoonBestInSlot:AddItem(spec, "27518", "Idol", "Ivory Idol of the Moongoddess", "BIS")
