local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "1")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29086", "Head", "Crown of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "31376", "Head", "Gladiator's Kodohide Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28803", "Head", "Cowl of Nature's Breath", "Alt")
LoonBestInSlot:AddItem(spec, "32090", "Head", "Cowl of Naaru Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown", "Alt")
LoonBestInSlot:AddItem(spec, "28348", "Head", "Moonglade Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "29505", "Head", "Hood of Primal Life", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "29089", "Shoulders", "Shoulderguards of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28612", "Shoulders", "Pauldrons of the Solace-Giver", "Alt")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "28647", "Shoulders", "Forest Wind Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "31378", "Shoulders", "Gladiator's Kodohide Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance", "Alt")
LoonBestInSlot:AddItem(spec, "27737", "Shoulders", "Moonglade Shoulders", "Alt")

LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "BIS")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "Alt")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "22960", "Back", "Cloak of Suturing", "Alt")
LoonBestInSlot:AddItem(spec, "27946", "Back", "Avian Cloak of Feathers", "Alt")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Bishop's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape", "Alt")

LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29087", "Chest", "Chestguard of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "31379", "Chest", "Gladiator's Kodohide Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments", "Alt")
LoonBestInSlot:AddItem(spec, "28600", "Chest", "Stonebough Jerkin", "Alt")
LoonBestInSlot:AddItem(spec, "28202", "Chest", "Moonglade Robe", "Alt")
LoonBestInSlot:AddItem(spec, "27456", "Chest", "Raiments of Nature's Breath", "Alt")
LoonBestInSlot:AddItem(spec, "27506", "Chest", "Robe of Effervescent Light", "Alt")

LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "BIS")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent", "Alt")
LoonBestInSlot:AddItem(spec, "21604", "Bracers", "Bracelets of Royal Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "27827", "Bracers", "Lucid Dream Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "22495", "Bracers", "Dreamwalker Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "BIS")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "29090", "Gloves", "Handguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "Alt")
LoonBestInSlot:AddItem(spec, "31375", "Gloves", "Gladiator's Kodohide Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "24393", "Gloves", "Bloody Surgeon's Mitts", "Alt")
LoonBestInSlot:AddItem(spec, "25791", "Gloves", "Gloves of Preservation", "Alt")
LoonBestInSlot:AddItem(spec, "28268", "Gloves", "Natural Mender's Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "29327", "Gloves", "Cryo-mitts", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28655", "Belt", "Cord of Nature's Sustenance", "Alt")
LoonBestInSlot:AddItem(spec, "28652", "Belt", "Cincture of Will", "Alt")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification", "Alt")
LoonBestInSlot:AddItem(spec, "31594", "Belt", "General's Kodohide Belt", "Alt")
LoonBestInSlot:AddItem(spec, "27542", "Belt", "Cord of Belief", "Alt")
LoonBestInSlot:AddItem(spec, "28398", "Belt", "The Sleeper's Cord", "Alt")

LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "BIS")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "29088", "Legs", "Legguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31335", "Legs", "Pants of Living Growth", "Alt")
LoonBestInSlot:AddItem(spec, "28218", "Legs", "Pontiff's Pantaloons of Prophecy", "Alt")
LoonBestInSlot:AddItem(spec, "31377", "Legs", "Gladiator's Kodohide Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29345", "Legs", "Haramad's Leg Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers", "Alt")
LoonBestInSlot:AddItem(spec, "27875", "Legs", "Hallowed Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders", "BIS")
LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt", "Alt")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity", "Alt")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious", "Alt")
LoonBestInSlot:AddItem(spec, "25792", "Feet", "Curate's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "31595", "Feet", "General's Kodohide Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28251", "Feet", "Boots of the Glade-Keeper", "Alt")
LoonBestInSlot:AddItem(spec, "27525", "Feet", "Jeweled Boots of Sanctification", "Alt")

LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "28731", "Neck", "Shining Chain of the Afterworld", "Alt")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion", "Alt")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "Alt")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope", "Alt")
LoonBestInSlot:AddItem(spec, "23036", "Neck", "Necklace of Necropsy", "Alt")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope", "Alt")
LoonBestInSlot:AddItem(spec, "21712", "Neck", "Amulet of the Fallen God", "Alt")

LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "Alt")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "Alt")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos", "Alt")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void", "Alt")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29322", "Ring", "Keeper's Ring of Piety", "Alt")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "BIS")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "Alt")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "Alt")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "28727", "Trinket", "Pendant of the Violet Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "Alt")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler", "Alt")

LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "Alt")
LoonBestInSlot:AddItem(spec, "28257", "MH", "Hammer of the Penitent", "Alt")
LoonBestInSlot:AddItem(spec, "28216", "MH", "Dathrohan's Ceremonial Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "27538", "MH", "Lightsworn Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "31304", "MH", "The Essence Focuser", "Alt")

LoonBestInSlot:AddItem(spec, "30732", "2H", "Exodar Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "28782", "2H", "Crystalheart Pulse-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "28604", "2H", "Nightstaff of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "22632", "2H", "Atiesh, Greatstaff of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "27791", "2H", "Serpentcrest Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "29133", "2H", "Seer's Cane", "Alt")
LoonBestInSlot:AddItem(spec, "28033", "2H", "Epoch-Mender", "Alt")
LoonBestInSlot:AddItem(spec, "31289", "2H", "Staff of Divine Infusion", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28525", "OH", "Signet of Unshakable Faith", "Alt")
LoonBestInSlot:AddItem(spec, "23048", "OH", "Sapphiron's Right Eye", "Alt")
LoonBestInSlot:AddItem(spec, "23029", "OH", "Noth's Frigid Heart", "Alt")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing", "Alt")
LoonBestInSlot:AddItem(spec, "27714", "OH", "Swamplight Lantern", "Alt")
LoonBestInSlot:AddItem(spec, "28213", "OH", "Lordaeron Medical Guide", "Alt")
LoonBestInSlot:AddItem(spec, "31493", "OH", "Netherwing Spiritualist's Charm", "Alt")
LoonBestInSlot:AddItem(spec, "28387", "OH", "Lamp of Peaceful Repose", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
LoonBestInSlot:AddItem(spec, "25643", "Idol", "Harold's Rejuvenating Broach", "Alt")
