local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "1")
LoonBestInSlot:AddItem(spec, "24264", L["Head"], "Whitemend Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29086", L["Head"], "Crown of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28803", L["Head"], "Cowl of Nature's Breath", "Alt")

LoonBestInSlot:AddItem(spec, "21874", L["Shoulders"], "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "29089", L["Shoulders"], "Shoulderguards of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28612", L["Shoulders"], "Pauldrons of the Solace-Giver", "Alt")
LoonBestInSlot:AddItem(spec, "28647", L["Shoulders"], "Forest Wind Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "28765", L["Back"], "Stainless Cloak of the Pure Hearted", "BIS")
LoonBestInSlot:AddItem(spec, "31329", L["Back"], "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28582", L["Back"], "Red Riding Hood's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "22960", L["Back"], "Cloak of Suturing", "Alt")
LoonBestInSlot:AddItem(spec, "27946", L["Back"], "Avian Cloak of Feathers", "Alt")

LoonBestInSlot:AddItem(spec, "21875", L["Chest"], "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29087", L["Chest"], "Chestguard of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28600", L["Chest"], "Stonebough Jerkin", "Alt")

LoonBestInSlot:AddItem(spec, "29183", L["Bracers"], "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "29523", L["Bracers"], "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28511", L["Bracers"], "Bands of Indwelling", "BIS")

LoonBestInSlot:AddItem(spec, "28521", L["Gloves"], "Mitts of the Treemender", "BIS")
LoonBestInSlot:AddItem(spec, "28508", L["Gloves"], "Gloves of Saintly Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "29090", L["Gloves"], "Handguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29506", L["Gloves"], "Gloves of the Living Touch", "Alt")

LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28655", L["Belt"], "Cord of Nature's Sustenance", "Alt")
LoonBestInSlot:AddItem(spec, "28652", L["Belt"], "Cincture of Will", "Alt")

LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "24261", L["Legs"], "Whitemend Pants", "BIS")
LoonBestInSlot:AddItem(spec, "28591", L["Legs"], "Earthsoul Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30543", L["Legs"], "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "28742", L["Legs"], "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "31343", L["Legs"], "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "29088", L["Legs"], "Legguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29767", L["Legs"], "Leggings of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "28752", L["Feet"], "Forestlord Striders", "BIS")
LoonBestInSlot:AddItem(spec, "28663", L["Feet"], "Boots of the Incorrupt", "Alt")
LoonBestInSlot:AddItem(spec, "25792", L["Feet"], "Curate's Boots", "Alt")

LoonBestInSlot:AddItem(spec, "30726", L["Neck"], "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28822", L["Neck"], "Teeth of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28609", L["Neck"], "Emberspur Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "28731", L["Neck"], "Shining Chain of the Afterworld", "Alt")
LoonBestInSlot:AddItem(spec, "30377", L["Neck"], "Karja's Medallion", "Alt")

LoonBestInSlot:AddItem(spec, "29290", L["Ring"], "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", L["Ring"], "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28790", L["Ring"], "Naaru Lightwarden's Band", "BIS")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "30736", L["Ring"], "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "27780", L["Ring"], "Ring of Fabled Hope", "Alt")
LoonBestInSlot:AddItem(spec, "29168", L["Ring"], "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "29169", L["Ring"], "Ring of Convalescence", "Alt")
LoonBestInSlot:AddItem(spec, "31383", L["Ring"], "Spiritualist's Mark of the Sha'tar", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "25634", L["Trinket"], "Oshu'gun Relic", "BIS")
LoonBestInSlot:AddItem(spec, "28590", L["Trinket"], "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "28727", L["Trinket"], "Pendant of the Violet Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28823", L["Trinket"], "Eye of Gruul", "Alt")

LoonBestInSlot:AddItem(spec, "28771", L["MH"], "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "28522", L["MH"], "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", L["MH"], "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", L["MH"], "Shockwave Truncheon", "Alt")

LoonBestInSlot:AddItem(spec, "30732", L["2H"], "Exodar Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "28782", L["2H"], "Crystalheart Pulse-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "28604", L["2H"], "Nightstaff of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "22632", L["2H"], "Atiesh, Greatstaff of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "27791", L["2H"], "Serpentcrest Life-Staff", "Alt")

LoonBestInSlot:AddItem(spec, "29274", L["OH"], "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", L["OH"], "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "28728", L["OH"], "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28525", L["OH"], "Signet of Unshakable Faith", "Alt")

LoonBestInSlot:AddItem(spec, "27886", L["Idol"], "Idol of the Emerald Queen", "BIS")
