local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "1")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")

LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "31255", "Back", "Cloak of the Craft", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "28601", "Chest", "Chestguard of the Conniver", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")
LoonBestInSlot:AddItem(spec, "24396", "Chest", "Vest of Vengeance", "Alt")

LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "21602", "Bracers", "Qiraji Execution Bracers", "BIS")

LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "BIS")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "29507", "Gloves", "Windslayer Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "27509", "Gloves", "Handgrips of Assassination", "BIS")

LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "BIS")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "BIS")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "30372", "Belt", "Socrethar's Girdle", "Scryer Alt")
LoonBestInSlot:AddItem(spec, "27911", "Belt", "Epoch's Whispering Cinch", "Alt")
LoonBestInSlot:AddItem(spec, "31464", "Belt", "Naaru Belt of Precision", "Alt")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Alt")

LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "Alt")
LoonBestInSlot:AddItem(spec, "31288", "Feet", "The Master's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30939", "Feet", "Felboar Hide Shoes", "Alt")

LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "BIS")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "Alt")
LoonBestInSlot:AddItem(spec, "27779", "Neck", "Bone Chain Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant", "BIS")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "Alt")

LoonBestInSlot:AddItem(spec, "28658", "2H", "Terestian's Stranglestaff", "BIS")
LoonBestInSlot:AddItem(spec, "28476", "2H", "Gladiator's Maul", "BIS")
LoonBestInSlot:AddItem(spec, "29359", "2H", "Feral Staff of Lashing", "Alt")
LoonBestInSlot:AddItem(spec, "31334", "2H", "Staff of Natural Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden", "Alt")
LoonBestInSlot:AddItem(spec, "27877", "2H", "Draenic Wildstaff", "Alt")

LoonBestInSlot:AddItem(spec, "29390", "Idol", "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "28372", "Idol", "Idol of Feral Shadows", "BIS")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild", "Alt")
