local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "1")
LoonBestInSlot:AddItem(spec, "29098", L["Head"], "Stag-Helm of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28796", L["Head"], "Malefic Mask of the Shadows", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28732", L["Head"], "Cowl of Defiance", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "29100", L["Shoulders"], "Mantle of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28755", L["Shoulders"], "Bladed Shoulderpads of the Merciless", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28660", L["Back"], "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28777", L["Back"], "Cloak of the Pit Stalker", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28256", L["Back"], "Thoriumweave Cloak", "Alt Mit")
LoonBestInSlot:AddItem(spec, "24258", L["Back"], "Resolute Cape", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29096", L["Chest"], "Breastplate of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28601", L["Chest"], "Chestguard of the Conniver", "Alt")
LoonBestInSlot:AddItem(spec, "25689", L["Chest"], "Heavy Clefthoof Vest", "Alt")

LoonBestInSlot:AddItem(spec, "28978", L["Bracers"], "Marshal's Dragonhide Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28445", L["Bracers"], "General's Dragonhide Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28988", L["Bracers"], "Marshal's Leather Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28424", L["Bracers"], "General's Leather Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30944", L["Bracers"], "Umberhowl's Collar", "Alt")
LoonBestInSlot:AddItem(spec, "28514", L["Bracers"], "Bracers of Maliciousness", "Alt")
LoonBestInSlot:AddItem(spec, "29246", L["Bracers"], "Nightfall Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "29097", L["Gloves"], "Gauntlets of Malorne", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30644", L["Gloves"], "Grips of Deftness", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28506", L["Gloves"], "Gloves of Dexterous Manipulation", "Alt")
LoonBestInSlot:AddItem(spec, "28776", L["Gloves"], "Liar's Tongue Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "29264", L["Belt"], "Tree-Mender's Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28828", L["Belt"], "Gronn-Stitched Girdle", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28750", L["Belt"], "Girdle of Treachery", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28986", L["Belt"], "Marshal's Leather Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28423", L["Belt"], "General's Leather Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29247", L["Belt"], "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "28976", L["Belt"], "Marshal's Dragonhide Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28443", L["Belt"], "General's Dragonhide Belt", "Alt")

LoonBestInSlot:AddItem(spec, "29099", L["Legs"], "Greaves of Malorne", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29767", L["Legs"], "Leggings of the Fallen Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28741", L["Legs"], "Skulker's Greaves", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30538", L["Legs"], "Midnight Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "30674", L["Feet"], "Zierhut's Lost Treads", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28987", L["Feet"], "Marshal's Leather Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28422", L["Feet"], "General's Leather Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29265", L["Feet"], "Barkchip Boots", "Alt")
LoonBestInSlot:AddItem(spec, "25691", L["Feet"], "Heavy Clefthoof Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28339", L["Feet"], "Boots of the Shifting Sands", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "28509", L["Neck"], "Worgen Claw Necklace", "BIS")
LoonBestInSlot:AddItem(spec, "29381", L["Neck"], "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "28674", L["Neck"], "Saberclaw Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28745", L["Neck"], "Mithril Chain of Heroism", "Alt")
LoonBestInSlot:AddItem(spec, "29386", L["Neck"], "Necklace of the Juggernaut", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "BIS")
LoonBestInSlot:AddItem(spec, "28792", L["Ring"], "A'dal's Signet of Defense", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29384", L["Ring"], "Ring of Unyielding Force", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28675", L["Ring"], "Shermanar Great-Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28757", L["Ring"], "Ring of a Thousand Marks", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28649", L["Ring"], "Garona's Signet Ring", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23836", L["Trinket"], "Goblin Rocket Launcher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "23835", L["Trinket"], "Gnomish Poultryizer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "13503", L["Trinket"], "Alchemist's Stone", "BIS")
LoonBestInSlot:AddItem(spec, "19406", L["Trinket"], "Drake Fang Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "29181", L["Trinket"], "Timelapse Shard", "BIS Mit")
LoonBestInSlot:AddItem(spec, "31113", L["Trinket"], "Violet Badge", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28658", L["2H"], "Terestian's Stranglestaff", "BIS")
LoonBestInSlot:AddItem(spec, "28476", L["2H"], "Gladiator's Maul", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29171", L["2H"], "Earthwarden", "BIS Mit")

LoonBestInSlot:AddItem(spec, "23198", L["Idol"], "Idol of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "28064", L["Idol"], "Idol of the Wild", "BIS")
