local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "1")
LoonBestInSlot:AddItem(spec, "24266", L["Head"], "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "28744", L["Head"], "Uni-Mind Headdress", "BIS")
LoonBestInSlot:AddItem(spec, "23828", L["Head"], "Gnomish Power Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "29093", L["Head"], "Antlers of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28804", L["Head"], "Collar of Cho'gall", "Alt")

LoonBestInSlot:AddItem(spec, "29095", L["Shoulders"], "Pauldrons of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "27796", L["Shoulders"], "Mana-Etched Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "27778", L["Shoulders"], "Spaulders of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "27738", L["Shoulders"], "Incanter's Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "31797", L["Shoulders"], "Elekk Hide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "28766", L["Back"], "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "30735", L["Back"], "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "28797", L["Back"], "Brute Cloak of the Ogre-Magi", "Alt")
LoonBestInSlot:AddItem(spec, "27981", L["Back"], "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28570", L["Back"], "Shadow-Cloak of Dalaran", "Alt")

LoonBestInSlot:AddItem(spec, "21848", L["Chest"], "Spellfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29091", L["Chest"], "Chestpiece of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "BIS")

LoonBestInSlot:AddItem(spec, "29523", L["Bracers"], "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "24250", L["Bracers"], "Bracers of Havok", "BIS")
LoonBestInSlot:AddItem(spec, "28515", L["Bracers"], "Bands of Nefarious Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28453", L["Bracers"], "Bracers of the White Stag", "Alt")

LoonBestInSlot:AddItem(spec, "21847", L["Gloves"], "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "30725", L["Gloves"], "Anger-Spark Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "28507", L["Gloves"], "Handwraps of Flowing Thought", "BIS")
LoonBestInSlot:AddItem(spec, "28780", L["Gloves"], "Soul-Eater's Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "29092", L["Gloves"], "Gloves of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "21846", L["Belt"], "Spellfire Belt", "BIS")
LoonBestInSlot:AddItem(spec, "24256", L["Belt"], "Girdle of Ruination", "BIS")
LoonBestInSlot:AddItem(spec, "28799", L["Belt"], "Belt of Divine Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "28654", L["Belt"], "Malefic Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", L["Legs"], "Leggings of the Seventh Circle", "BIS")
LoonBestInSlot:AddItem(spec, "28594", L["Legs"], "Trial-Fire Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "28517", L["Feet"], "Boots of Foretelling", "BIS")
LoonBestInSlot:AddItem(spec, "28585", L["Feet"], "Ruby Slippers", "BIS")
LoonBestInSlot:AddItem(spec, "27821", L["Feet"], "Extravagant Boots of Malice", "Alt")
LoonBestInSlot:AddItem(spec, "28406", L["Feet"], "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "Alt")

LoonBestInSlot:AddItem(spec, "28530", L["Neck"], "Brooch of Unquenchable Fury", "BIS")
LoonBestInSlot:AddItem(spec, "28762", L["Neck"], "Adornment of Stolen Souls", "BIS")
LoonBestInSlot:AddItem(spec, "28134", L["Neck"], "Brooch of Heightened Potential", "Alt")

LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28753", L["Ring"], "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "29172", L["Ring"], "Ashyen's Gift", "BIS")
LoonBestInSlot:AddItem(spec, "29287", L["Ring"], "Violet Signet of the Archmage", "BIS")
LoonBestInSlot:AddItem(spec, "28227", L["Ring"], "Sparking Arcanite Ring", "Alt")

LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "27683", L["Trinket"], "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29132", L["Trinket"], "Scryer's Bloodgem", "BIS")
LoonBestInSlot:AddItem(spec, "19379", L["Trinket"], "Neltharion's Tear", "BIS")
LoonBestInSlot:AddItem(spec, "28789", L["Trinket"], "Eye of Magtheridon", "Alt")

LoonBestInSlot:AddItem(spec, "28770", L["MH"], "Nathrezim Mindblade", "BIS")
LoonBestInSlot:AddItem(spec, "30723", L["MH"], "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "30832", L["MH"], "Gavel of Unearthed Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "23554", L["MH"], "Eternium Runed Blade", "Alt")

LoonBestInSlot:AddItem(spec, "28633", L["2H"], "Staff of Infinite Mysteries", "BIS")

LoonBestInSlot:AddItem(spec, "29271", L["OH"], "Talisman of Kalecgos", "BIS")
LoonBestInSlot:AddItem(spec, "28734", L["OH"], "Jewel of Infinite Possibilities", "BIS")
LoonBestInSlot:AddItem(spec, "28603", L["OH"], "Talisman of Nightbane", "Alt")

LoonBestInSlot:AddItem(spec, "27518", L["Idol"], "Ivory Idol of the Moongoddess", "BIS")
