local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "1")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29086", "Head", "Crown of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28803", "Head", "Cowl of Nature's Breath", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "29089", "Shoulders", "Shoulderguards of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28612", "Shoulders", "Pauldrons of the Solace-Giver", "Alt")
LoonBestInSlot:AddItem(spec, "28647", "Shoulders", "Forest Wind Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "BIS")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "22960", "Back", "Cloak of Suturing", "Alt")
LoonBestInSlot:AddItem(spec, "27946", "Back", "Avian Cloak of Feathers", "Alt")

LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29087", "Chest", "Chestguard of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28600", "Chest", "Stonebough Jerkin", "Alt")

LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "BIS")

LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "BIS")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "29090", "Gloves", "Handguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28655", "Belt", "Cord of Nature's Sustenance", "Alt")
LoonBestInSlot:AddItem(spec, "28652", "Belt", "Cincture of Will", "Alt")

LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "BIS")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "29088", "Legs", "Legguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders", "BIS")
LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt", "Alt")
LoonBestInSlot:AddItem(spec, "25792", "Feet", "Curate's Boots", "Alt")

LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "28731", "Neck", "Shining Chain of the Afterworld", "Alt")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion", "Alt")

LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "Alt")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "Alt")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "BIS")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "28727", "Trinket", "Pendant of the Violet Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "Alt")

LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")

LoonBestInSlot:AddItem(spec, "30732", "2H", "Exodar Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "28782", "2H", "Crystalheart Pulse-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "28604", "2H", "Nightstaff of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "22632", "2H", "Atiesh, Greatstaff of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "27791", "2H", "Serpentcrest Life-Staff", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28525", "OH", "Signet of Unshakable Faith", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
