local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "1")
LoonBestInSlot:AddItem(spec, "29098", "Head", "Stag-Helm of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28796", "Head", "Malefic Mask of the Shadows", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28732", "Head", "Cowl of Defiance", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28256", "Back", "Thoriumweave Cloak", "Alt Mit")
LoonBestInSlot:AddItem(spec, "24258", "Back", "Resolute Cape", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28601", "Chest", "Chestguard of the Conniver", "Alt")
LoonBestInSlot:AddItem(spec, "25689", "Chest", "Heavy Clefthoof Vest", "Alt")

LoonBestInSlot:AddItem(spec, "28978", "Bracers", "Marshal's Dragonhide Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28445", "Bracers", "General's Dragonhide Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28988", "Bracers", "Marshal's Leather Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28424", "Bracers", "General's Leather Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30944", "Bracers", "Umberhowl's Collar", "Alt")
LoonBestInSlot:AddItem(spec, "28514", "Bracers", "Bracers of Maliciousness", "Alt")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "29097", "Gloves", "Gauntlets of Malorne", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt")
LoonBestInSlot:AddItem(spec, "28776", "Gloves", "Liar's Tongue Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "29264", "Belt", "Tree-Mender's Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28986", "Belt", "Marshal's Leather Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28423", "Belt", "General's Leather Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "28976", "Belt", "Marshal's Dragonhide Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28443", "Belt", "General's Dragonhide Belt", "Alt")

LoonBestInSlot:AddItem(spec, "29099", "Legs", "Greaves of Malorne", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "30674", "Feet", "Zierhut's Lost Treads", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28987", "Feet", "Marshal's Leather Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28422", "Feet", "General's Leather Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29265", "Feet", "Barkchip Boots", "Alt")
LoonBestInSlot:AddItem(spec, "25691", "Feet", "Heavy Clefthoof Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28339", "Feet", "Boots of the Shifting Sands", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "BIS")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism", "Alt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "13503", "Trinket", "Alchemist's Stone", "BIS")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "29181", "Trinket", "Timelapse Shard", "BIS Mit")
LoonBestInSlot:AddItem(spec, "31113", "Trinket", "Violet Badge", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28658", "2H", "Terestian's Stranglestaff", "BIS")
LoonBestInSlot:AddItem(spec, "28476", "2H", "Gladiator's Maul", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden", "BIS Mit")

LoonBestInSlot:AddItem(spec, "23198", "Idol", "Idol of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild", "BIS")
