local spec = LoonBestInSlot:RegisterSpec("Mage", "Arcane", "1")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29076", "Head", "Collar of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29759", "Head", "Helm of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28744", "Head", "Uni-Mind Headdress", "Alt")

LoonBestInSlot:AddItem(spec, "29079", "Shoulders", "Pauldrons of the Aldor", "BIS")
LoonBestInSlot:AddItem(spec, "29762", "Shoulders", "Pauldrons of the Fallen Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "BIS")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "23050", "Back", "Cloak of the Necropolis", "Alt")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran", "Alt")
LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities", "Alt")

LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29077", "Chest", "Vestments of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29755", "Chest", "Chestguard of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28602", "Chest", "Robe of the Elder Scribes", "Alt")

LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom", "BIS")
LoonBestInSlot:AddItem(spec, "28411", "Bracers", "General's Silk Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28477", "Bracers", "Harbinger Bands", "Alt")

LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt")
LoonBestInSlot:AddItem(spec, "29080", "Gloves", "Gloves of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29756", "Gloves", "Gloves of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "Alt")

LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30673", "Belt", "Inferno Waist Cord", "Alt")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "28654", "Belt", "Malefic Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "Alt")
LoonBestInSlot:AddItem(spec, "29078", "Legs", "Legwraps of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29765", "Legs", "Leggings of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers", "BIS")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling", "BIS")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice", "Alt")

LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "BIS")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "BIS")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "BIS")
LoonBestInSlot:AddItem(spec, "31338", "Neck", "Charlotte's Ivy", "BIS")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "BIS")
LoonBestInSlot:AddItem(spec, "31339", "Ring", "Lola's Eve", "BIS")
LoonBestInSlot:AddItem(spec, "21709", "Ring", "Ring of the Fallen God", "BIS")
LoonBestInSlot:AddItem(spec, "28510", "Ring", "Spectral Band of Innervation", "Alt")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "Alt")

LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "28785", "Trinket", "The Lightning Capacitor", "Alt")

LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "Alt")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "Alt")

LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "BIS")
LoonBestInSlot:AddItem(spec, "22589", "2H", "Atiesh, Greatstaff of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "BIS")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane", "BIS")
LoonBestInSlot:AddItem(spec, "29271", "OH", "Talisman of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "28781", "OH", "Karaborian Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy", "BIS")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration", "BIS")
LoonBestInSlot:AddItem(spec, "28386", "Wand", "Nether Core's Control Rod", "Alt")
