local spec = LoonBestInSlot:RegisterSpec("Mage", "Arcane", "1")
LoonBestInSlot:AddItem(spec, "24266", L["Head"], "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29076", L["Head"], "Collar of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29759", L["Head"], "Helm of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28744", L["Head"], "Uni-Mind Headdress", "Alt")

LoonBestInSlot:AddItem(spec, "29079", L["Shoulders"], "Pauldrons of the Aldor", "BIS")
LoonBestInSlot:AddItem(spec, "29762", L["Shoulders"], "Pauldrons of the Fallen Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27994", L["Shoulders"], "Mantle of Three Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "27796", L["Shoulders"], "Mana-Etched Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "28766", L["Back"], "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "28797", L["Back"], "Brute Cloak of the Ogre-Magi", "BIS")
LoonBestInSlot:AddItem(spec, "30735", L["Back"], "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "23050", L["Back"], "Cloak of the Necropolis", "Alt")
LoonBestInSlot:AddItem(spec, "27981", L["Back"], "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28570", L["Back"], "Shadow-Cloak of Dalaran", "Alt")
LoonBestInSlot:AddItem(spec, "29369", L["Back"], "Shawl of Shifting Probabilities", "Alt")

LoonBestInSlot:AddItem(spec, "21848", L["Chest"], "Spellfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29077", L["Chest"], "Vestments of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29755", L["Chest"], "Chestguard of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28602", L["Chest"], "Robe of the Elder Scribes", "Alt")

LoonBestInSlot:AddItem(spec, "27462", L["Bracers"], "Crimson Bracers of Gloom", "BIS")
LoonBestInSlot:AddItem(spec, "28411", L["Bracers"], "General's Silk Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "28515", L["Bracers"], "Bands of Nefarious Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28477", L["Bracers"], "Harbinger Bands", "Alt")

LoonBestInSlot:AddItem(spec, "21847", L["Gloves"], "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "28507", L["Gloves"], "Handwraps of Flowing Thought", "Alt")
LoonBestInSlot:AddItem(spec, "29080", L["Gloves"], "Gloves of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29756", L["Gloves"], "Gloves of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30725", L["Gloves"], "Anger-Spark Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28780", L["Gloves"], "Soul-Eater's Handwraps", "Alt")

LoonBestInSlot:AddItem(spec, "21846", L["Belt"], "Spellfire Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30673", L["Belt"], "Inferno Waist Cord", "Alt")
LoonBestInSlot:AddItem(spec, "28799", L["Belt"], "Belt of Divine Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "28654", L["Belt"], "Malefic Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", L["Legs"], "Leggings of the Seventh Circle", "Alt")
LoonBestInSlot:AddItem(spec, "29078", L["Legs"], "Legwraps of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29765", L["Legs"], "Leggings of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28594", L["Legs"], "Trial-Fire Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "28585", L["Feet"], "Ruby Slippers", "BIS")
LoonBestInSlot:AddItem(spec, "28517", L["Feet"], "Boots of Foretelling", "BIS")
LoonBestInSlot:AddItem(spec, "28406", L["Feet"], "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "27821", L["Feet"], "Extravagant Boots of Malice", "Alt")

LoonBestInSlot:AddItem(spec, "28134", L["Neck"], "Brooch of Heightened Potential", "BIS")
LoonBestInSlot:AddItem(spec, "28530", L["Neck"], "Brooch of Unquenchable Fury", "BIS")
LoonBestInSlot:AddItem(spec, "28762", L["Neck"], "Adornment of Stolen Souls", "BIS")
LoonBestInSlot:AddItem(spec, "31338", L["Neck"], "Charlotte's Ivy", "BIS")
LoonBestInSlot:AddItem(spec, "27758", L["Neck"], "Hydra-fang Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28227", L["Ring"], "Sparking Arcanite Ring", "BIS")
LoonBestInSlot:AddItem(spec, "31339", L["Ring"], "Lola's Eve", "BIS")
LoonBestInSlot:AddItem(spec, "21709", L["Ring"], "Ring of the Fallen God", "BIS")
LoonBestInSlot:AddItem(spec, "28510", L["Ring"], "Spectral Band of Innervation", "Alt")
LoonBestInSlot:AddItem(spec, "29287", L["Ring"], "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "28753", L["Ring"], "Ring of Recurrence", "Alt")

LoonBestInSlot:AddItem(spec, "29132", L["Trinket"], "Scryer's Bloodgem", "BIS")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "28789", L["Trinket"], "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "28785", L["Trinket"], "The Lightning Capacitor", "Alt")

LoonBestInSlot:AddItem(spec, "30723", L["MH"], "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "28802", L["MH"], "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "28770", L["MH"], "Nathrezim Mindblade", "Alt")
LoonBestInSlot:AddItem(spec, "23554", L["MH"], "Eternium Runed Blade", "Alt")

LoonBestInSlot:AddItem(spec, "28633", L["2H"], "Staff of Infinite Mysteries", "BIS")
LoonBestInSlot:AddItem(spec, "22589", L["2H"], "Atiesh, Greatstaff of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "28734", L["OH"], "Jewel of Infinite Possibilities", "BIS")
LoonBestInSlot:AddItem(spec, "28603", L["OH"], "Talisman of Nightbane", "BIS")
LoonBestInSlot:AddItem(spec, "29271", L["OH"], "Talisman of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "28781", L["OH"], "Karaborian Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "28673", L["Wand"], "Tirisfal Wand of Ascendancy", "BIS")
LoonBestInSlot:AddItem(spec, "28783", L["Wand"], "Eredar Wand of Obliteration", "BIS")
LoonBestInSlot:AddItem(spec, "28386", L["Wand"], "Nether Core's Control Rod", "Alt")
