local spec = LoonBestInSlot:RegisterSpec("Mage", "Arcane", "1")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29076", "Head", "Collar of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "28193", "Head", "Mana-Etched Crown", "Alt")
LoonBestInSlot:AddItem(spec, "28744", "Head", "Uni-Mind Headdress", "Alt")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "30515", "Head", "Junior Technician 3rd Grade Goggles", "Alt")

LoonBestInSlot:AddItem(spec, "29079", "Shoulders", "Pauldrons of the Aldor", "BIS")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart", "Alt")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", "Spaulders of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "22983", "Shoulders", "Rime Covered Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "28075", "Shoulders", "Destroyers' Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30514", "Shoulders", "Nether Guards", "Alt")

LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "BIS")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "23050", "Back", "Cloak of the Necropolis", "Alt")
LoonBestInSlot:AddItem(spec, "22731", "Back", "Cloak of the Devoured", "Alt")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran", "Alt")
LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities", "Alt")
LoonBestInSlot:AddItem(spec, "29813", "Back", "Cloak of Woven Energy", "Alt")
LoonBestInSlot:AddItem(spec, "25777", "Back", "Ogre Slayer's Cover", "Alt")

LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order", "Alt")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28342", "Chest", "Warp Infused Drape", "Alt")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd", "Alt")
LoonBestInSlot:AddItem(spec, "29077", "Chest", "Vestments of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "28602", "Chest", "Robe of the Elder Scribes", "Alt")
LoonBestInSlot:AddItem(spec, "29780", "Chest", "Kirin Tor Apprentice's Robes", "Alt")
LoonBestInSlot:AddItem(spec, "31717", "Chest", "Shadowcast Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom", "BIS")
LoonBestInSlot:AddItem(spec, "28411", "Bracers", "General's Silk Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "Alt")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "27746", "Bracers", "Arcanium Signet Bands", "Alt")
LoonBestInSlot:AddItem(spec, "29240", "Bracers", "Bands of Negation", "Alt")
LoonBestInSlot:AddItem(spec, "28477", "Bracers", "Harbinger Bands", "Alt")
LoonBestInSlot:AddItem(spec, "30927", "Bracers", "Earthmender's Bracer of Shattering", "Alt")
LoonBestInSlot:AddItem(spec, "30520", "Bracers", "Gold-Trimmed Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt")
LoonBestInSlot:AddItem(spec, "29080", "Gloves", "Gloves of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "27493", "Gloves", "Gloves of the Deadwatcher", "Alt")
LoonBestInSlot:AddItem(spec, "21585", "Gloves", "Dark Storm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30924", "Gloves", "Gloves of the High Magus", "Alt")
LoonBestInSlot:AddItem(spec, "30930", "Gloves", "Grips of the Void", "Alt")

LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "BIS")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "Alt")
LoonBestInSlot:AddItem(spec, "30673", "Belt", "Inferno Waist Cord", "Alt")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity", "Alt")
LoonBestInSlot:AddItem(spec, "22730", "Belt", "Eyestalk Waist Cord", "Alt")
LoonBestInSlot:AddItem(spec, "28654", "Belt", "Malefic Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "30923", "Belt", "Grom'tor's Bloodied Bandage", "Alt")
LoonBestInSlot:AddItem(spec, "29771", "Belt", "Kirin'Var Journeyman's Belt", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "Alt")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist", "Alt")
LoonBestInSlot:AddItem(spec, "29078", "Legs", "Legwraps of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers", "Alt")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration", "Alt")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers", "Alt")
LoonBestInSlot:AddItem(spec, "30929", "Legs", "Soothsayer's Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "21852", "Legs", "Netherweave Pants", "Alt")

LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers", "BIS")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling", "BIS")
LoonBestInSlot:AddItem(spec, "29258", "Feet", "Boots of Ethereal Manipulation", "Alt")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice", "Alt")
LoonBestInSlot:AddItem(spec, "29242", "Feet", "Boots of Blasphemy", "Alt")
LoonBestInSlot:AddItem(spec, "30519", "Feet", "Boots of the Nexus Warden", "Alt")
LoonBestInSlot:AddItem(spec, "30398", "Feet", "Boots of the Beneficent", "Alt")

LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "BIS")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "BIS")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "BIS")
LoonBestInSlot:AddItem(spec, "31338", "Neck", "Charlotte's Ivy", "BIS")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "18814", "Neck", "Choker of the Fire Lord", "Alt")
LoonBestInSlot:AddItem(spec, "21608", "Neck", "Amulet of Vek'nilash", "Alt")
LoonBestInSlot:AddItem(spec, "29368", "Neck", "Manasurge Pendant", "Alt")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31178", "Neck", "Amulet of Unstable Power", "Alt")

LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "BIS")
LoonBestInSlot:AddItem(spec, "31339", "Ring", "Lola's Eve", "BIS")
LoonBestInSlot:AddItem(spec, "21709", "Ring", "Ring of the Fallen God", "BIS")
LoonBestInSlot:AddItem(spec, "28510", "Ring", "Spectral Band of Innervation", "Alt")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "Alt")
LoonBestInSlot:AddItem(spec, "23062", "Ring", "Frostfire Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa", "Alt")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "31075", "Ring", "Evoker's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "30366", "Ring", "Manastorm Band", "Alt")
LoonBestInSlot:AddItem(spec, "32774", "Ring", "The Black Pearl", "Alt")

LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "BIS")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "28785", "Trinket", "The Lightning Capacitor", "Alt")
LoonBestInSlot:AddItem(spec, "19339", "Trinket", "Mind Quickening Gem", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")
LoonBestInSlot:AddItem(spec, "28418", "Trinket", "Shiffar's Nexus-Horn", "Alt")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "28040", "Trinket", "Vengeance of the Illidari", "Alt")
LoonBestInSlot:AddItem(spec, "25620", "Trinket", "Ancient Crystal Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "25619", "Trinket", "Glowing Crystal Insignia", "Alt")

LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "Alt")
LoonBestInSlot:AddItem(spec, "30787", "MH", "Illidari-Bane Mageblade", "Alt")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "Alt")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "Alt")
LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry", "Alt")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams", "Alt")
LoonBestInSlot:AddItem(spec, "27543", "MH", "Starlight Dagger", "Alt")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "24453", "MH", "Zangartooth Shortblade", "Alt")
LoonBestInSlot:AddItem(spec, "31142", "MH", "Blade of Trapped Knowledge", "Alt")

LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "BIS")
LoonBestInSlot:AddItem(spec, "22589", "2H", "Atiesh, Greatstaff of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff", "Alt")
LoonBestInSlot:AddItem(spec, "29130", "2H", "Auchenai Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28341", "2H", "Warpstaff of Arcanum", "Alt")
LoonBestInSlot:AddItem(spec, "27842", "2H", "Grand Scepter of the Nexus-Kings", "Alt")
LoonBestInSlot:AddItem(spec, "31308", "2H", "The Bringer of Death", "Alt")
LoonBestInSlot:AddItem(spec, "25760", "2H", "Battle Mage's Baton", "Alt")

LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "BIS")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane", "BIS")
LoonBestInSlot:AddItem(spec, "29271", "OH", "Talisman of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance", "Alt")
LoonBestInSlot:AddItem(spec, "28187", "OH", "Star-Heart Lamp", "Alt")
LoonBestInSlot:AddItem(spec, "28781", "OH", "Karaborian Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "31699", "OH", "Imbued Draenethyst Crystal", "Alt")
LoonBestInSlot:AddItem(spec, "31731", "OH", "Mekeda's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy", "BIS")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration", "BIS")
LoonBestInSlot:AddItem(spec, "28386", "Wand", "Nether Core's Control Rod", "Alt")
LoonBestInSlot:AddItem(spec, "22820", "Wand", "Wand of Fates", "Alt")
LoonBestInSlot:AddItem(spec, "22821", "Wand", "Doomfinger", "Alt")
LoonBestInSlot:AddItem(spec, "25939", "Wand", "Voidfire Wand", "Alt")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk", "Alt")
LoonBestInSlot:AddItem(spec, "27890", "Wand", "Wand of the Netherwing", "Alt")
LoonBestInSlot:AddItem(spec, "31724", "Wand", "Arakkoa Divining Rod", "Alt")
LoonBestInSlot:AddItem(spec, "30523", "Wand", "Hotshot Cattle Prod", "Alt")
