local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "1")
LoonBestInSlot:AddItem(spec, "29068", L["Head"], "Justicar Faceguard", "BIS")
LoonBestInSlot:AddItem(spec, "29760", L["Head"], "Helm of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32083", L["Head"], "Faceguard of Determination", "BIS")
LoonBestInSlot:AddItem(spec, "28593", L["Head"], "Eternium Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "27704", L["Head"], "Gladiator's Lamellar Helm", "Alt")
LoonBestInSlot:AddItem(spec, "23536", L["Head"], "Oathkeeper's Helm", "Alt")

LoonBestInSlot:AddItem(spec, "29070", L["Shoulders"], "Justicar Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "29763", L["Shoulders"], "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28743", L["Shoulders"], "Mantle of Abrahmis", "Alt")
LoonBestInSlot:AddItem(spec, "27706", L["Shoulders"], "Gladiator's Lamellar Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "27739", L["Shoulders"], "Spaulders of the Righteous", "Alt")

LoonBestInSlot:AddItem(spec, "27804", L["Back"], "Devilshark Cape", "BIS")
LoonBestInSlot:AddItem(spec, "28660", L["Back"], "Gilded Thorium Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29066", L["Chest"], "Justicar Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29754", L["Chest"], "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28597", L["Chest"], "Panzar'Thar Breastplate", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27702", L["Chest"], "Gladiator's Lamellar Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "28203", L["Chest"], "Breastplate of the Righteous", "BIS")

LoonBestInSlot:AddItem(spec, "29252", L["Bracers"], "Bracers of Dignity", "BIS")
LoonBestInSlot:AddItem(spec, "23538", L["Bracers"], "Bracers of the Green Fortress", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28502", L["Bracers"], "Vambraces of Courage", "Alt")
LoonBestInSlot:AddItem(spec, "29463", L["Bracers"], "Amber Bands of the Aggressor", "Alt")

LoonBestInSlot:AddItem(spec, "29067", L["Gloves"], "Justicar Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "29757", L["Gloves"], "Gloves of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28518", L["Gloves"], "Iron Gauntlets of the Maiden", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30741", L["Gloves"], "Topaz-Studded Battlegrips", "Alt")
LoonBestInSlot:AddItem(spec, "27703", L["Gloves"], "Gladiator's Lamellar Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "32072", L["Gloves"], "Gauntlets of Dissension", "Alt")

LoonBestInSlot:AddItem(spec, "29253", L["Belt"], "Girdle of Valorous Deeds", "BIS")
LoonBestInSlot:AddItem(spec, "28566", L["Belt"], "Crimson Girdle of the Indomitable", "BIS Mit")

LoonBestInSlot:AddItem(spec, "29069", L["Legs"], "Justicar Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "29766", L["Legs"], "Leggings of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28621", L["Legs"], "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27705", L["Legs"], "Gladiator's Lamellar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29184", L["Legs"], "Timewarden's Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "29254", L["Feet"], "Boots of the Righteous Path", "BIS")
LoonBestInSlot:AddItem(spec, "30641", L["Feet"], "Boots of Elusion", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28747", L["Feet"], "Battlescar Boots", "Alt")

LoonBestInSlot:AddItem(spec, "28516", L["Neck"], "Barbed Choker of Discipline", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28245", L["Neck"], "Pendant of Dominance", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28530", L["Neck"], "Brooch of Unquenchable Fury", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29386", L["Neck"], "Necklace of the Juggernaut", "BIS")
LoonBestInSlot:AddItem(spec, "29173", L["Neck"], "Strength of the Untamed", "Alt")

LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28407", L["Ring"], "Elementium Band of the Sentry", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28675", L["Ring"], "Shermanar Great-Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28792", L["Ring"], "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31319", L["Ring"], "Band of Impenetrable Defenses", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28528", L["Trinket"], "Moroes' Lucky Pocket Watch", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27529", L["Trinket"], "Figurine of the Colossus", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27891", L["Trinket"], "Adamantine Figurine", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32534", L["Trinket"], "Brooch of the Immortal King", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28789", L["Trinket"], "Eye of Magtheridon", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "Alt")

LoonBestInSlot:AddItem(spec, "28802", L["MH"], "Bloodmaw Magus-Blade", "BIS")
LoonBestInSlot:AddItem(spec, "32450", L["MH"], "Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "28749", L["MH"], "King's Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30832", L["MH"], "Gavel of Unearthed Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "29153", L["MH"], "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29155", L["MH"], "Stormcaller", "Alt")

LoonBestInSlot:AddItem(spec, "29388", L["Libram"], "Libram of Repentance", "BIS")

LoonBestInSlot:AddItem(spec, "28825", L["Shield"], "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28358", L["Shield"], "Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28606", L["Shield"], "Shield of Impenetrable Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "29176", L["Shield"], "Crest of the Sha'tar", "Alt")
