local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy", "1")
LoonBestInSlot:AddItem(spec, "30728", L["Head"], "Fathom-Helm of the Deeps", "BIS")
LoonBestInSlot:AddItem(spec, "32472", L["Head"], "Justicebringer 2000 Specs", "BIS")
LoonBestInSlot:AddItem(spec, "29061", L["Head"], "Justicar Diadem", "BIS")
LoonBestInSlot:AddItem(spec, "29760", L["Head"], "Helm of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "24264", L["Head"], "Whitemend Hood", "Alt")
LoonBestInSlot:AddItem(spec, "28803", L["Head"], "Cowl of Nature's Breath", "Alt")
LoonBestInSlot:AddItem(spec, "28756", L["Head"], "Headdress of the High Potentate", "Alt")

LoonBestInSlot:AddItem(spec, "29064", L["Shoulders"], "Justicar Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "29763", L["Shoulders"], "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "21874", L["Shoulders"], "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "28631", L["Shoulders"], "Dragon-Quake Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "28666", L["Shoulders"], "Pauldrons of the Justice-Seeker", "Alt")
LoonBestInSlot:AddItem(spec, "28647", L["Shoulders"], "Forest Wind Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "31329", L["Back"], "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", L["Back"], "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "28582", L["Back"], "Red Riding Hood's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29062", L["Chest"], "Justicar Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "29754", L["Chest"], "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "21875", L["Chest"], "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28662", L["Chest"], "Breastplate of the Lightbinder", "Alt")
LoonBestInSlot:AddItem(spec, "28735", L["Chest"], "Earthblood Chestguard", "Alt")

LoonBestInSlot:AddItem(spec, "29523", L["Bracers"], "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29183", L["Bracers"], "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "23539", L["Bracers"], "Blessed Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28512", L["Bracers"], "Bracers of Justice", "Alt")
LoonBestInSlot:AddItem(spec, "28503", L["Bracers"], "Whirlwind Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28511", L["Bracers"], "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "28505", L["Gloves"], "Gauntlets of Renewed Hope", "BIS")
LoonBestInSlot:AddItem(spec, "28520", L["Gloves"], "Gloves of Centering", "Alt")
LoonBestInSlot:AddItem(spec, "28521", L["Gloves"], "Mitts of the Treemender", "Alt")
LoonBestInSlot:AddItem(spec, "29065", L["Gloves"], "Justicar Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29757", L["Gloves"], "Gloves of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29506", L["Gloves"], "Gloves of the Living Touch", "Alt")

LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28733", L["Belt"], "Girdle of Truth", "Alt")
LoonBestInSlot:AddItem(spec, "28655", L["Belt"], "Cord of Nature's Sustenance", "Alt")
LoonBestInSlot:AddItem(spec, "32985", L["Belt"], "Marshal's Ornamented Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28751", L["Legs"], "Heart-Flame Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "28748", L["Legs"], "Legplates of the Innocent", "Alt")
LoonBestInSlot:AddItem(spec, "28591", L["Legs"], "Earthsoul Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "28742", L["Legs"], "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "24261", L["Legs"], "Whitemend Pants", "Alt")

LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "28752", L["Feet"], "Forestlord Striders", "Alt")
LoonBestInSlot:AddItem(spec, "28569", L["Feet"], "Boots of Valiance", "Alt")
LoonBestInSlot:AddItem(spec, "27411", L["Feet"], "Slippers of Serenity", "Alt")

LoonBestInSlot:AddItem(spec, "30726", L["Neck"], "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28609", L["Neck"], "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "31691", L["Neck"], "Natasha's Guardian Cord", "Alt")

LoonBestInSlot:AddItem(spec, "30736", L["Ring"], "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "28763", L["Ring"], "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28790", L["Ring"], "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "29169", L["Ring"], "Ring of Convalescence", "Alt")
LoonBestInSlot:AddItem(spec, "29168", L["Ring"], "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "29290", L["Ring"], "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "27780", L["Ring"], "Ring of Fabled Hope", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "28590", L["Trinket"], "Ribbon of Sacrifice", "BIS")
LoonBestInSlot:AddItem(spec, "23047", L["Trinket"], "Eye of the Dead", "BIS")
LoonBestInSlot:AddItem(spec, "30841", L["Trinket"], "Lower City Prayerbook", "BIS")

LoonBestInSlot:AddItem(spec, "28771", L["MH"], "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "32451", L["MH"], "Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "28522", L["MH"], "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", L["MH"], "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", L["MH"], "Shockwave Truncheon", "Alt")

LoonBestInSlot:AddItem(spec, "29458", L["OH"], "Aegis of the Vindicator", "BIS")
LoonBestInSlot:AddItem(spec, "28728", L["OH"], "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "29274", L["OH"], "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "22819", L["OH"], "Shield of Condemnation", "Alt")

LoonBestInSlot:AddItem(spec, "28592", L["Libram"], "Libram of Souls Redeemed", "BIS")
LoonBestInSlot:AddItem(spec, "28296", L["Libram"], "Libram of the Lightbringer", "Alt")
LoonBestInSlot:AddItem(spec, "23006", L["Libram"], "Libram of Light", "Alt")
