local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy", "1")
LoonBestInSlot:AddItem(spec, "30728", "Head", "Fathom-Helm of the Deeps", "BIS")
LoonBestInSlot:AddItem(spec, "32472", "Head", "Justicebringer 2000 Specs", "BIS")
LoonBestInSlot:AddItem(spec, "29061", "Head", "Justicar Diadem", "BIS")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "Alt")
LoonBestInSlot:AddItem(spec, "28803", "Head", "Cowl of Nature's Breath", "Alt")
LoonBestInSlot:AddItem(spec, "28756", "Head", "Headdress of the High Potentate", "Alt")

LoonBestInSlot:AddItem(spec, "29064", "Shoulders", "Justicar Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "28631", "Shoulders", "Dragon-Quake Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "28666", "Shoulders", "Pauldrons of the Justice-Seeker", "Alt")
LoonBestInSlot:AddItem(spec, "28647", "Shoulders", "Forest Wind Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29062", "Chest", "Justicar Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28662", "Chest", "Breastplate of the Lightbinder", "Alt")
LoonBestInSlot:AddItem(spec, "28735", "Chest", "Earthblood Chestguard", "Alt")

LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "23539", "Bracers", "Blessed Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28512", "Bracers", "Bracers of Justice", "Alt")
LoonBestInSlot:AddItem(spec, "28503", "Bracers", "Whirlwind Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "28505", "Gloves", "Gauntlets of Renewed Hope", "BIS")
LoonBestInSlot:AddItem(spec, "28520", "Gloves", "Gloves of Centering", "Alt")
LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "Alt")
LoonBestInSlot:AddItem(spec, "29065", "Gloves", "Justicar Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28733", "Belt", "Girdle of Truth", "Alt")
LoonBestInSlot:AddItem(spec, "28655", "Belt", "Cord of Nature's Sustenance", "Alt")
LoonBestInSlot:AddItem(spec, "32985", "Belt", "Marshal's Ornamented Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28751", "Legs", "Heart-Flame Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "28748", "Legs", "Legplates of the Innocent", "Alt")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders", "Alt")
LoonBestInSlot:AddItem(spec, "28569", "Feet", "Boots of Valiance", "Alt")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity", "Alt")

LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "Alt")

LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "Alt")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "BIS")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "BIS")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "BIS")

LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")

LoonBestInSlot:AddItem(spec, "29458", "OH", "Aegis of the Vindicator", "BIS")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "22819", "OH", "Shield of Condemnation", "Alt")

LoonBestInSlot:AddItem(spec, "28592", "Libram", "Libram of Souls Redeemed", "BIS")
LoonBestInSlot:AddItem(spec, "28296", "Libram", "Libram of the Lightbringer", "Alt")
LoonBestInSlot:AddItem(spec, "23006", "Libram", "Libram of Light", "Alt")
