local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "1")
LoonBestInSlot:AddItem(spec, "29068", "Head", "Justicar Faceguard", "BIS")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination", "BIS")
LoonBestInSlot:AddItem(spec, "28593", "Head", "Eternium Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "27704", "Head", "Gladiator's Lamellar Helm", "Alt")
LoonBestInSlot:AddItem(spec, "23536", "Head", "Oathkeeper's Helm", "Alt")

LoonBestInSlot:AddItem(spec, "29070", "Shoulders", "Justicar Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28743", "Shoulders", "Mantle of Abrahmis", "Alt")
LoonBestInSlot:AddItem(spec, "27706", "Shoulders", "Gladiator's Lamellar Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "27739", "Shoulders", "Spaulders of the Righteous", "Alt")

LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape", "BIS")
LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29066", "Chest", "Justicar Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27702", "Chest", "Gladiator's Lamellar Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "28203", "Chest", "Breastplate of the Righteous", "BIS")

LoonBestInSlot:AddItem(spec, "29252", "Bracers", "Bracers of Dignity", "BIS")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage", "Alt")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor", "Alt")

LoonBestInSlot:AddItem(spec, "29067", "Gloves", "Justicar Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30741", "Gloves", "Topaz-Studded Battlegrips", "Alt")
LoonBestInSlot:AddItem(spec, "27703", "Gloves", "Gladiator's Lamellar Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "32072", "Gloves", "Gauntlets of Dissension", "Alt")

LoonBestInSlot:AddItem(spec, "29253", "Belt", "Girdle of Valorous Deeds", "BIS")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable", "BIS Mit")

LoonBestInSlot:AddItem(spec, "29069", "Legs", "Justicar Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "29766", "Legs", "Leggings of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27705", "Legs", "Gladiator's Lamellar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "29254", "Feet", "Boots of the Righteous Path", "BIS")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28747", "Feet", "Battlescar Boots", "Alt")

LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28245", "Neck", "Pendant of Dominance", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "BIS")
LoonBestInSlot:AddItem(spec, "29173", "Neck", "Strength of the Untamed", "Alt")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31319", "Ring", "Band of Impenetrable Defenses", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt")

LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "BIS")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "28749", "MH", "King's Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "Alt")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS")

LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28358", "Shield", "Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar", "Alt")
