local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "1")
LoonBestInSlot:AddItem(spec, "29068", "Head", "Justicar Faceguard", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination", "BIS - Avoidance")
LoonBestInSlot:AddItem(spec, "28593", "Head", "Eternium Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "27704", "Head", "Gladiator's Lamellar Helm", "Alt - Alt Required")
LoonBestInSlot:AddItem(spec, "23536", "Head", "Oathkeeper's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "23535", "Head", "Helm of the Stalwart Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28285", "Head", "Helm of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "23519", "Head", "Felsteel Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28180", "Head", "Myrmidon's Headdress", "Alt - Easy to obtain")
LoonBestInSlot:AddItem(spec, "27520", "Head", "Greathelm of the Unbreakable", "Option")

LoonBestInSlot:AddItem(spec, "29070", "Shoulders", "Justicar Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "28743", "Shoulders", "Mantle of Abrahmis", "Alt")
LoonBestInSlot:AddItem(spec, "27706", "Shoulders", "Gladiator's Lamellar Shoulders", "Alt - Alt Required")
LoonBestInSlot:AddItem(spec, "27739", "Shoulders", "Spaulders of the Righteous", "Option")
LoonBestInSlot:AddItem(spec, "27847", "Shoulders", "Fanblade Pauldrons", "Option")
LoonBestInSlot:AddItem(spec, "32073", "Shoulders", "Spaulders of Dementia", "Option")
LoonBestInSlot:AddItem(spec, "30381", "Shoulders", "Kaylaan's Spaulders", "Option")

LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape", "BIS")
LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "24253", "Back", "Cloak of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29385", "Back", "Farstrider Defender's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "27988", "Back", "Burnoose of Shifting Ages", "Alt")
LoonBestInSlot:AddItem(spec, "24379", "Back", "Bogstrok Scale Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "29777", "Back", "Cloak of the Valiant Defender", "Alt")

LoonBestInSlot:AddItem(spec, "29066", "Chest", "Justicar Chestguard", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "27702", "Chest", "Gladiator's Lamellar Chestpiece", "Alt - Alt Required")
LoonBestInSlot:AddItem(spec, "28203", "Chest", "Breastplate of the Righteous", "BIS")
LoonBestInSlot:AddItem(spec, "28262", "Chest", "Jade-Skull Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29127", "Chest", "Vindicator's Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "23507", "Chest", "Adamantite Breastplate", "Option")
LoonBestInSlot:AddItem(spec, "25819", "Chest", "Breastplate of the Warbringer", "Option")

LoonBestInSlot:AddItem(spec, "29252", "Bracers", "Bracers of Dignity", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress", "BIS - Survivability")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage", "Alt")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor", "Alt")
LoonBestInSlot:AddItem(spec, "28167", "Bracers", "Sha'tari Wrought Armguards", "Option")
LoonBestInSlot:AddItem(spec, "27459", "Bracers", "Vambraces of Daring", "Option")
LoonBestInSlot:AddItem(spec, "30400", "Bracers", "Thadell's Bracers", "Option")

LoonBestInSlot:AddItem(spec, "29067", "Gloves", "Justicar Handguards", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "30741", "Gloves", "Topaz-Studded Battlegrips", "Alt")
LoonBestInSlot:AddItem(spec, "27703", "Gloves", "Gladiator's Lamellar Gauntlets", "Alt - Alt Required")
LoonBestInSlot:AddItem(spec, "32072", "Gloves", "Gauntlets of Dissension", "Option")
LoonBestInSlot:AddItem(spec, "23532", "Gloves", "Gauntlets of the Iron Tower", "Option")
LoonBestInSlot:AddItem(spec, "27535", "Gloves", "Gauntlets of the Righteous", "Option")
LoonBestInSlot:AddItem(spec, "23517", "Gloves", "Felsteel Gloves", "Option")
LoonBestInSlot:AddItem(spec, "25788", "Gloves", "Dauntless Handguards", "Option")
LoonBestInSlot:AddItem(spec, "28390", "Gloves", "Thatia's Self-Correcting Gauntlets", "Option")
LoonBestInSlot:AddItem(spec, "29134", "Gloves", "Gauntlets of the Chosen", "Option")

LoonBestInSlot:AddItem(spec, "29253", "Belt", "Girdle of Valorous Deeds", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable", "BIS - Survivability")
LoonBestInSlot:AddItem(spec, "27672", "Belt", "Girdle of the Immovable", "Alt")
LoonBestInSlot:AddItem(spec, "31460", "Belt", "Sha'tari Vindicator's Waistguard", "Alt")
LoonBestInSlot:AddItem(spec, "29238", "Belt", "Lion's Heart Girdle", "Option")
LoonBestInSlot:AddItem(spec, "30371", "Belt", "Lightwarden's Girdle", "Option")
LoonBestInSlot:AddItem(spec, "30330", "Belt", "Starcaller's Plated Belt", "Option")

LoonBestInSlot:AddItem(spec, "29069", "Legs", "Justicar Legguards", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "27705", "Legs", "Gladiator's Lamellar Legguards", "Alt - Alt Required")
LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27839", "Legs", "Legplates of the Righteous", "Alt - D3")
LoonBestInSlot:AddItem(spec, "23518", "Legs", "Felsteel Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27527", "Legs", "Greaves of the Shatterer", "Alt")
LoonBestInSlot:AddItem(spec, "29783", "Legs", "Legguards of the Resolute Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29774", "Legs", "Kirin'Var Defender's Chausses", "Option")

LoonBestInSlot:AddItem(spec, "29254", "Feet", "Boots of the Righteous Path", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "28747", "Feet", "Battlescar Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29239", "Feet", "Eaglecrest Warboots", "Alt")
LoonBestInSlot:AddItem(spec, "27813", "Feet", "Boots of the Colossus", "Alt")
LoonBestInSlot:AddItem(spec, "30334", "Feet", "Starcaller's Plated Stompers", "Alt")
LoonBestInSlot:AddItem(spec, "32866", "Feet", "Ascendant's Boots", "Option")
LoonBestInSlot:AddItem(spec, "29325", "Feet", "Flesh Beast's Metal Greaves", "Option")
LoonBestInSlot:AddItem(spec, "30386", "Feet", "Bloodguard's Greaves", "Option")

LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "28245", "Neck", "Pendant of Dominance", "BIS - Thrt (Requires Alt)")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt - Thrt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "BIS")
LoonBestInSlot:AddItem(spec, "30378", "Neck", "Thalodien's Charm", "Alt")
LoonBestInSlot:AddItem(spec, "31696", "Neck", "Natasha's Battle Chain", "Alt")
LoonBestInSlot:AddItem(spec, "27792", "Neck", "Steam-Hinge Chain of Valor", "Alt")
LoonBestInSlot:AddItem(spec, "29173", "Neck", "Strength of the Untamed", "Alt")
LoonBestInSlot:AddItem(spec, "27871", "Neck", "Maladaar's Blessed Chaplet", "Alt")
LoonBestInSlot:AddItem(spec, "29336", "Neck", "Mark of the Ravenguard", "Alt")
LoonBestInSlot:AddItem(spec, "28321", "Neck", "Enchanted Thorium Torque", "Alt")
LoonBestInSlot:AddItem(spec, "25809", "Neck", "Maimfist's Choker", "Horde Option")
LoonBestInSlot:AddItem(spec, "25803", "Neck", "Medallion of the Valiant Guardian", "Alliance Option")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "Option")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS - Thrt")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry", "BIS - Defensive")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "31319", "Ring", "Band of Impenetrable Defenses", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "27822", "Ring", "Crystal Band of Valor", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "28211", "Ring", "Lieutenant's Signet of Lordaeron", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "31078", "Ring", "Protector's Mark of the Redemption", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "27436", "Ring", "Iron Band of the Unbreakable", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "24088", "Ring", "Delicate Eternium Ring", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "31924", "Ring", "Yor's Revenge", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "29323", "Ring", "Andormu's Tear", "Alt - Defensive")
LoonBestInSlot:AddItem(spec, "28265", "Ring", "Dath'Remar's Ring of Defense", "Alt - Defensive")

LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "BIS - Avoidance")
LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus", "BIS - Uncrushability")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine", "BIS - Defense + Mit")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "BIS - Defense + HP")
LoonBestInSlot:AddItem(spec, "30300", "Trinket", "Dabiri's Enigma", "Alt - Defense")
LoonBestInSlot:AddItem(spec, "19431", "Trinket", "Styleen's Impeding Scarab", "Alt - Defense")
LoonBestInSlot:AddItem(spec, "24125", "Trinket", "Figurine - Dawnstone Crab", "Alt - Avoidance UtilityJewelcrafters")
LoonBestInSlot:AddItem(spec, "28042", "Trinket", "Regal Protectorate", "Alt - Defense + HP")
LoonBestInSlot:AddItem(spec, "23040", "Trinket", "Glyph of Deflection", "Alt - Mit")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600", "Alt - Mit")

LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "BIS")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "BIS - Alt Required - Hard to Get")
LoonBestInSlot:AddItem(spec, "28749", "MH", "King's Defender", "Alt - Blood")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "Alt - Blood")
LoonBestInSlot:AddItem(spec, "29156", "MH", "Honor's Call", "Alt - Blood")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer", "Alt")
LoonBestInSlot:AddItem(spec, "32660", "MH", "Crystalforged Sword", "Alt")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "27899", "MH", "Mana Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams", "Alt")
LoonBestInSlot:AddItem(spec, "22988", "MH", "The End of Dreams", "Option")
LoonBestInSlot:AddItem(spec, "22807", "MH", "Wraith Blade", "Option")
LoonBestInSlot:AddItem(spec, "19360", "MH", "Lok'amir il Romathis", "Option")
LoonBestInSlot:AddItem(spec, "21622", "MH", "Sharpened Silithid Femur", "Option")
LoonBestInSlot:AddItem(spec, "24361", "MH", "Spellfire Longsword", "Option")
LoonBestInSlot:AddItem(spec, "24384", "MH", "Diamond-Core Sledgemace", "Option")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS")
LoonBestInSlot:AddItem(spec, "27917", "Libram", "Libram of the Eternal Rest", "Alt - Thrt")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Option")

LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28358", "Shield", "Gladiator's Shield Wall", "Alt- Alt")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra", "Alt")
LoonBestInSlot:AddItem(spec, "32082", "Shield", "The Fel Barrier", "Alt - Black Temple")
LoonBestInSlot:AddItem(spec, "32652", "Shield", "Ogri'la Aegis", "Alt")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird", "Option")
LoonBestInSlot:AddItem(spec, "27449", "Shield", "Blood Knight Defender", "Option")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous", "Option")
LoonBestInSlot:AddItem(spec, "23043", "Shield", "The Face of Death", "Option")
