local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "1")
LoonBestInSlot:AddItem(spec, "29073", "Head", "Justicar Crown", "BIS")
LoonBestInSlot:AddItem(spec, "27881", "Head", "Gladiator's Scaled Helm", "Alt-PVP")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Optinoal")
LoonBestInSlot:AddItem(spec, "31105", "Head", "Overlord's Helmet of Second Sight", "Alt - No Meta Gem")

LoonBestInSlot:AddItem(spec, "29075", "Shoulders", "Justicar Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "30740", "Shoulders", "Ripfiend Shoulderplates", "WORLD BOSS")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Option")
LoonBestInSlot:AddItem(spec, "27883", "Shoulders", "Gladiator's Scaled Shoulders", "PVP")

LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "BIS-Crafted")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt-Crafted")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "BIS for Hit")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt Hit")
LoonBestInSlot:AddItem(spec, "28249", "Back", "Capacitus' Cloak of Calibration", "Option")

LoonBestInSlot:AddItem(spec, "29071", "Chest", "Justicar Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "WORLD BOSS")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "BIS-CraftedLeatherworking")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt-CraftedLeatherworking")
LoonBestInSlot:AddItem(spec, "28403", "Chest", "Doomplate Chestguard", "BIS-NonCrafted")

LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "BIS")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "Alt-Crafted")
LoonBestInSlot:AddItem(spec, "28646", "Bracers", "General's Scaled Bracers", "Alt-PVP")
LoonBestInSlot:AddItem(spec, "27918", "Bracers", "Bands of Syth", "Option")

LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "BIS")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "Option")
LoonBestInSlot:AddItem(spec, "18823", "Gloves", "Aged Core Leather Gloves", "Option")

LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "BIS")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Option")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt-Hit")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "Option")

LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "BIS-Hit Option")

LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "BIS-NonHit")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS-Hit")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots", "Option")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "Crafted-Hit")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS-HIT")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "BIS-Non HIT")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism", "Option")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "Option")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "BOE")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Never Un-equip")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "WorldBoss")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Bis-Hit")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred", "Alt-Hit")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt-NonHit")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "Option")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Option")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS TRINKET #2")
LoonBestInSlot:AddItem(spec, "23206", "Trinket", "Mark of the Champion", "Undead Only & Demons")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "BIS Non-DST")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "OPTIONAL")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "OPTIONAL UNTIL DST")
LoonBestInSlot:AddItem(spec, "22954", "Trinket", "Kiss of the Spider", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial", "PENDING TESTING")

LoonBestInSlot:AddItem(spec, "28429", "2H", "Lionheart Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30722", "2H", "Ethereum Nexus-Reaver", "WORLD BOSS")
LoonBestInSlot:AddItem(spec, "28441", "2H", "Deep Thunder", "Alt-Crafting")
LoonBestInSlot:AddItem(spec, "28773", "2H", "Gorehowl", "Option")
LoonBestInSlot:AddItem(spec, "24550", "2H", "Gladiator's Greatsword", "PVP")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement", "BIS")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Option")
LoonBestInSlot:AddItem(spec, "23203", "Libram", "Libram of Fervor", "Alt Alt")
LoonBestInSlot:AddItem(spec, "22402", "Libram", "Libram of Grace", "Cleansebot")
