local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "1")
LoonBestInSlot:AddItem(spec, "29049", L["Head"], "Light-Collar of the Incarnate", "BIS")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32090", L["Head"], "Cowl of Naaru Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "28756", L["Head"], "Headdress of the High Potentate", "Alt")

LoonBestInSlot:AddItem(spec, "21874", L["Shoulders"], "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "29054", L["Shoulders"], "Light-Mantle of the Incarnate", "BIS")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28612", L["Shoulders"], "Pauldrons of the Solace-Giver", "Alt")

LoonBestInSlot:AddItem(spec, "28765", L["Back"], "Stainless Cloak of the Pure Hearted", "BIS")
LoonBestInSlot:AddItem(spec, "29354", L["Back"], "Light-Touched Stole of Altruism", "BIS")
LoonBestInSlot:AddItem(spec, "31329", L["Back"], "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28582", L["Back"], "Red Riding Hood's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "29375", L["Back"], "Bishop's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "21875", L["Chest"], "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29050", L["Chest"], "Robes of the Incarnate", "BIS")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28578", L["Chest"], "Masquerade Gown", "Alt")

LoonBestInSlot:AddItem(spec, "29183", L["Bracers"], "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "28511", L["Bracers"], "Bands of Indwelling", "BIS")
LoonBestInSlot:AddItem(spec, "29249", L["Bracers"], "Bands of the Benevolent", "BIS")

LoonBestInSlot:AddItem(spec, "28508", L["Gloves"], "Gloves of Saintly Blessings", "BIS")
LoonBestInSlot:AddItem(spec, "29055", L["Gloves"], "Handwraps of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24393", L["Gloves"], "Bloody Surgeon's Mitts", "Alt")

LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28652", L["Belt"], "Cincture of Will", "BIS")

LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28742", L["Legs"], "Pantaloons of Repentance", "BIS")
LoonBestInSlot:AddItem(spec, "30543", L["Legs"], "Pontifex Kilt", "BIS")
LoonBestInSlot:AddItem(spec, "29053", L["Legs"], "Trousers of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29767", L["Legs"], "Leggings of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "28663", L["Feet"], "Boots of the Incorrupt", "BIS")
LoonBestInSlot:AddItem(spec, "29251", L["Feet"], "Boots of the Pious", "BIS")
LoonBestInSlot:AddItem(spec, "27411", L["Feet"], "Slippers of Serenity", "Alt")
LoonBestInSlot:AddItem(spec, "28179", L["Feet"], "Shattrath Jumpers", "Alt")

LoonBestInSlot:AddItem(spec, "30726", L["Neck"], "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28822", L["Neck"], "Teeth of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28609", L["Neck"], "Emberspur Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "28731", L["Neck"], "Shining Chain of the Afterworld", "BIS")
LoonBestInSlot:AddItem(spec, "30377", L["Neck"], "Karja's Medallion", "Alt")

LoonBestInSlot:AddItem(spec, "30736", L["Ring"], "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "29290", L["Ring"], "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", L["Ring"], "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28661", L["Ring"], "Mender's Heart-Ring", "Alt")
LoonBestInSlot:AddItem(spec, "28790", L["Ring"], "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "28823", L["Trinket"], "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28590", L["Trinket"], "Ribbon of Sacrifice", "Alt")

LoonBestInSlot:AddItem(spec, "28771", L["MH"], "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "30732", L["MH"], "Exodar Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "32451", L["MH"], "Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "28522", L["MH"], "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", L["MH"], "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", L["MH"], "Shockwave Truncheon", "Alt")
LoonBestInSlot:AddItem(spec, "28782", L["MH"], "Crystalheart Pulse-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28604", L["MH"], "Nightstaff of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "31342", L["MH"], "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", L["MH"], "Gavel of Pure Light", "Alt")

LoonBestInSlot:AddItem(spec, "29170", L["OH"], "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "29274", L["OH"], "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "28728", L["OH"], "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28525", L["OH"], "Signet of Unshakable Faith", "Alt")

LoonBestInSlot:AddItem(spec, "28588", L["Wand"], "Blue Diamond Witchwand", "BIS")
