local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "1")
LoonBestInSlot:AddItem(spec, "29049", "Head", "Light-Collar of the Incarnate", "BIS")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32090", "Head", "Cowl of Naaru Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "28756", "Head", "Headdress of the High Potentate", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "29054", "Shoulders", "Light-Mantle of the Incarnate", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28612", "Shoulders", "Pauldrons of the Solace-Giver", "Alt")

LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "BIS")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "BIS")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Bishop's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29050", "Chest", "Robes of the Incarnate", "BIS")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28578", "Chest", "Masquerade Gown", "Alt")

LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "BIS")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent", "BIS")

LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings", "BIS")
LoonBestInSlot:AddItem(spec, "29055", "Gloves", "Handwraps of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24393", "Gloves", "Bloody Surgeon's Mitts", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28652", "Belt", "Cincture of Will", "BIS")

LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "BIS")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "BIS")
LoonBestInSlot:AddItem(spec, "29053", "Legs", "Trousers of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt", "BIS")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious", "BIS")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity", "Alt")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers", "Alt")

LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "BIS")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "28731", "Neck", "Shining Chain of the Afterworld", "BIS")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion", "Alt")

LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "BIS")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "28661", "Ring", "Mender's Heart-Ring", "Alt")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")

LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "BIS")
LoonBestInSlot:AddItem(spec, "30732", "MH", "Exodar Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")
LoonBestInSlot:AddItem(spec, "28782", "MH", "Crystalheart Pulse-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28604", "MH", "Nightstaff of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "Alt")

LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28525", "OH", "Signet of Unshakable Faith", "Alt")

LoonBestInSlot:AddItem(spec, "28588", "Wand", "Blue Diamond Witchwand", "BIS")
