local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "1")
LoonBestInSlot:AddItem(spec, "29040", "Head", "Cyclone Helm", "BIS")
LoonBestInSlot:AddItem(spec, "28732", "Head", "Cowl of Defiance", "Alt")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt")
LoonBestInSlot:AddItem(spec, "31109", "Head", "Stealther's Helmet of Second Sight", "Alt")

LoonBestInSlot:AddItem(spec, "29043", "Shoulders", "Cyclone Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "BIS")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "29038", "Chest", "Cyclone Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "25997", "Chest", "Gladiator's Linked Armor", "Alt")

LoonBestInSlot:AddItem(spec, "28514", "Bracers", "Bracers of Maliciousness", "BIS")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "30399", "Bracers", "Nightstalker's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "BIS")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29503", "Gloves", "Cobrascale Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "Alt")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "27911", "Belt", "Epoch's Whispering Cinch", "Alt")

LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots", "BIS")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust", "Alt")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker", "Alt")
LoonBestInSlot:AddItem(spec, "27546", "Neck", "Traitor's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "BIS")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords", "Alt")
LoonBestInSlot:AddItem(spec, "28323", "Ring", "Ring of Umbral Doom", "Alt")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos", "Alt")

LoonBestInSlot:AddItem(spec, "28313", "MH", "Gladiator's Right Ripper", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "28308", "MH", "Gladiator's Cleaver", "BIS (All)")
LoonBestInSlot:AddItem(spec, "28767", "MH", "The Decapitator", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "27872", "MH", "The Harvester of Souls", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "28944", "MH", "Grand Marshal's Cleaver", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "28920", "MH", "High Warlord's Cleaver", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "28657", "MH", "Fool's Bane", "Alt")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "Alt (2.7 MH)")
LoonBestInSlot:AddItem(spec, "28432", "MH", "Black Planar Edge", "Alt (2.7 MH)")
LoonBestInSlot:AddItem(spec, "28392", "MH", "Reflex Blades", "Alt (2.7 MH)")
LoonBestInSlot:AddItem(spec, "31139", "MH", "Fist of Reckoning", "Alt (2.7 OH)")

LoonBestInSlot:AddItem(spec, "27815", "Totem", "Totem of the Astral Winds", "BIS")
