local spec = LoonBestInSlot:RegisterSpec("Shaman", "Elemental")
LoonBestInSlot:AddItem(spec, "29035", "Head", "Cyclone Faceguard", "BIS")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32086", "Head", "Storm Master's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "Alt")
LoonBestInSlot:AddItem(spec, "31330", "Head", "Lightning Crown", "Alt")
LoonBestInSlot:AddItem(spec, "28583", "Head", "Big Bad Wolf's Head", "Alt")

LoonBestInSlot:AddItem(spec, "29037", "Shoulders", "Cyclone Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32078", "Shoulders", "Pauldrons of Wild Magic", "Alt")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-Heart", "Alt")

LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "BIS")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "Alt")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "29519", "Chest", "Netherstrike Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "29033", "Chest", "Cyclone Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd", "Alt")

LoonBestInSlot:AddItem(spec, "29521", "Bracers", "Netherstrike Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "Alt")
LoonBestInSlot:AddItem(spec, "28638", "Bracers", "General's Mail Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "BIS")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt")
LoonBestInSlot:AddItem(spec, "29034", "Gloves", "Cyclone Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "29520", "Belt", "Netherstrike Belt", "BIS")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "BIS")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "Alt")
LoonBestInSlot:AddItem(spec, "30541", "Legs", "Stormsong Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "29142", "Legs", "Kurenai Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "29141", "Legs", "Tempest Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling", "BIS")
LoonBestInSlot:AddItem(spec, "28810", "Feet", "Windshear Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")

LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "BIS")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt")

LoonBestInSlot:AddItem(spec, "30667", "Ring", "Ring of Unrelenting Storms", "BIS")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "Alt")
LoonBestInSlot:AddItem(spec, "31290", "Ring", "Band of Dominion", "Alt")

LoonBestInSlot:AddItem(spec, "23207", "Trinket", "Mark of the Champion", "Special")
LoonBestInSlot:AddItem(spec, "28785", "Trinket", "The Lightning Capacitor", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "Alt")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "28418", "Trinket", "Shiffar's Nexus-Horn", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")

LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "BIS")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "Alt")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")

LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack", "BIS")
LoonBestInSlot:AddItem(spec, "29268", "OH", "Mazthoril Honor Shield", "BIS")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "Alt")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane", "Alt")

LoonBestInSlot:AddItem(spec, "28248", "Totem", "Totem of the Void", "BIS")
LoonBestInSlot:AddItem(spec, "23199", "Totem", "Totem of the Storm", "Alt")
LoonBestInSlot:AddItem(spec, "29389", "Totem", "Totem of the Pulsing Earth", "Alt")
