local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "1")
LoonBestInSlot:AddItem(spec, "29011", L["Head"], "Warbringer Greathelm", "BIS")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "24545", L["Head"], "Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29021", L["Head"], "Warbringer Battle-Helm", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30731", L["Head"], "Faceguard of the Endless Watch", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28593", L["Head"], "Eternium Greathelm", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29023", L["Shoulders"], "Warbringer Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29016", L["Shoulders"], "Warbringer Shoulderguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "24546", L["Shoulders"], "Gladiator's Plate Shoulders", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28743", L["Shoulders"], "Mantle of Abrahmis", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28529", L["Back"], "Royal Cloak of Arathi Kings", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28660", L["Back"], "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28777", L["Back"], "Cloak of the Pit Stalker", "Alt")
LoonBestInSlot:AddItem(spec, "29385", L["Back"], "Farstrider Defender's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29012", L["Chest"], "Warbringer Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "24544", L["Chest"], "Gladiator's Plate Chestpiece", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28597", L["Chest"], "Panzar'Thar Breastplate", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28484", L["Chest"], "Bulwark of Kings", "Alt")

LoonBestInSlot:AddItem(spec, "28996", L["Bracers"], "Marshal's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28502", L["Bracers"], "Vambraces of Courage", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28795", L["Bracers"], "Bladespire Warbands", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23538", L["Bracers"], "Bracers of the Green Fortress", "Alt")

LoonBestInSlot:AddItem(spec, "30741", L["Gloves"], "Topaz-Studded Battlegrips", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30644", L["Gloves"], "Grips of Deftness", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28518", L["Gloves"], "Iron Gauntlets of the Maiden", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29017", L["Gloves"], "Warbringer Handguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28995", L["Belt"], "Marshal's Plate Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28566", L["Belt"], "Crimson Girdle of the Indomitable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28779", L["Belt"], "Girdle of the Endless Pit", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "28621", L["Legs"], "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "24547", L["Legs"], "Gladiator's Plate Legguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29015", L["Legs"], "Warbringer Legguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29767", L["Legs"], "Leggings of the Fallen Defender", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28747", L["Feet"], "Battlescar Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28608", L["Feet"], "Ironstriders of Urgency", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28997", L["Feet"], "Marshal's Plate Greaves", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30641", L["Feet"], "Boots of Elusion", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29386", L["Neck"], "Necklace of the Juggernaut", "BIS")
LoonBestInSlot:AddItem(spec, "28516", L["Neck"], "Barbed Choker of Discipline", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28509", L["Neck"], "Worgen Claw Necklace", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28244", L["Neck"], "Pendant of Triumph", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28674", L["Neck"], "Saberclaw Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28675", L["Ring"], "Shermanar Great-Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28792", L["Ring"], "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29384", L["Ring"], "Ring of Unyielding Force", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28649", L["Ring"], "Garona's Signet Ring", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29283", L["Ring"], "Violet Signet of the Master Assassin", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "23836", L["Trinket"], "Goblin Rocket Launcher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "23835", L["Trinket"], "Gnomish Poultryizer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "31113", L["Trinket"], "Violet Badge", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28121", L["Trinket"], "Icon of Unyielding Courage", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28579", L["Trinket"], "Romulo's Poison Vial", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28749", L["MH"], "King's Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28426", L["MH"], "Blazeguard", "BIS")
LoonBestInSlot:AddItem(spec, "29165", L["MH"], "Warbringer", "BIS")
LoonBestInSlot:AddItem(spec, "29362", L["MH"], "The Sun Eater", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28189", L["MH"], "Latro's Shifting Sword", "Alt")

LoonBestInSlot:AddItem(spec, "28825", L["Shield"], "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28358", L["Shield"], "Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28606", L["Shield"], "Shield of Impenetrable Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "29176", L["Shield"], "Crest of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29266", L["Shield"], "Azure-Shield of Coldarra", "Alt")

LoonBestInSlot:AddItem(spec, "30724", L["Ranged"], "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28319", L["Ranged"], "Gladiator's War Edge", "Alt")
LoonBestInSlot:AddItem(spec, "28826", L["Ranged"], "Shuriken of Negation", "Alt")
