local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "1")
LoonBestInSlot:AddItem(spec, "29011", "Head", "Warbringer Greathelm", "BIS")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "24545", "Head", "Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29021", "Head", "Warbringer Battle-Helm", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30731", "Head", "Faceguard of the Endless Watch", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28593", "Head", "Eternium Greathelm", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29023", "Shoulders", "Warbringer Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29016", "Shoulders", "Warbringer Shoulderguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "24546", "Shoulders", "Gladiator's Plate Shoulders", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28743", "Shoulders", "Mantle of Abrahmis", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker", "Alt")
LoonBestInSlot:AddItem(spec, "29385", "Back", "Farstrider Defender's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29012", "Chest", "Warbringer Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "24544", "Chest", "Gladiator's Plate Chestpiece", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28484", "Chest", "Bulwark of Kings", "Alt")

LoonBestInSlot:AddItem(spec, "28996", "Bracers", "Marshal's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress", "Alt")

LoonBestInSlot:AddItem(spec, "30741", "Gloves", "Topaz-Studded Battlegrips", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29017", "Gloves", "Warbringer Handguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28995", "Belt", "Marshal's Plate Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "24547", "Legs", "Gladiator's Plate Legguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29015", "Legs", "Warbringer Legguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt Mit")

LoonBestInSlot:AddItem(spec, "28747", "Feet", "Battlescar Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28997", "Feet", "Marshal's Plate Greaves", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "BIS")
LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28244", "Neck", "Pendant of Triumph", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "31113", "Trinket", "Violet Badge", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28749", "MH", "King's Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28426", "MH", "Blazeguard", "BIS")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer", "BIS")
LoonBestInSlot:AddItem(spec, "29362", "MH", "The Sun Eater", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28189", "MH", "Latro's Shifting Sword", "Alt")

LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28358", "Shield", "Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra", "Alt")

LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28319", "Ranged", "Gladiator's War Edge", "Alt")
LoonBestInSlot:AddItem(spec, "28826", "Ranged", "Shuriken of Negation", "Alt")
