local spec = LoonBestInSlot:RegisterSpec("Warrior", "Arms", "1")
LoonBestInSlot:AddItem(spec, "29021", L["Head"], "Warbringer Battle-Helm", "BIS")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32087", L["Head"], "Mask of the Deceiver", "BIS")

LoonBestInSlot:AddItem(spec, "29023", L["Shoulders"], "Warbringer Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30740", L["Shoulders"], "Ripfiend Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "33173", L["Shoulders"], "Ragesteel Shoulders", "BIS")

LoonBestInSlot:AddItem(spec, "24259", L["Back"], "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "30729", L["Back"], "Black-Iron Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "Alt")

LoonBestInSlot:AddItem(spec, "29019", L["Chest"], "Warbringer Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30730", L["Chest"], "Terrorweave Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "23522", L["Chest"], "Ragesteel Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "24544", L["Chest"], "Gladiator's Plate Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "31548", L["Chest"], "Blackened Chestplate", "Alt")

LoonBestInSlot:AddItem(spec, "28795", L["Bracers"], "Bladespire Warbands", "BIS")
LoonBestInSlot:AddItem(spec, "23537", L["Bracers"], "Black Felsteel Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28381", L["Bracers"], "General's Plate Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30399", L["Bracers"], "Nightstalker's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "28824", L["Gloves"], "Gauntlets of Martial Perfection", "BIS")
LoonBestInSlot:AddItem(spec, "30644", L["Gloves"], "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "29020", L["Gloves"], "Warbringer Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "25685", L["Gloves"], "Fel Leather Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "27497", L["Gloves"], "Doomplate Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28776", L["Gloves"], "Liar's Tongue Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "28779", L["Belt"], "Girdle of the Endless Pit", "BIS")
LoonBestInSlot:AddItem(spec, "28828", L["Belt"], "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "27985", L["Belt"], "Deathforge Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "30739", L["Legs"], "Scaled Greaves of the Marksman", "BIS")
LoonBestInSlot:AddItem(spec, "28741", L["Legs"], "Skulker's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "29022", L["Legs"], "Warbringer Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "29767", L["Legs"], "Leggings of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30538", L["Legs"], "Midnight Legguards", "BIS")

LoonBestInSlot:AddItem(spec, "28608", L["Feet"], "Ironstriders of Urgency", "BIS")
LoonBestInSlot:AddItem(spec, "25686", L["Feet"], "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "30401", L["Feet"], "Farahlite Studded Boots", "Alt")

LoonBestInSlot:AddItem(spec, "29381", L["Neck"], "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29349", L["Neck"], "Adamantine Chain of the Unbroken", "BIS")
LoonBestInSlot:AddItem(spec, "28509", L["Neck"], "Worgen Claw Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "30738", L["Ring"], "Ring of Reciprocity", "BIS")
LoonBestInSlot:AddItem(spec, "28757", L["Ring"], "Ring of a Thousand Marks", "BIS")
LoonBestInSlot:AddItem(spec, "28730", L["Ring"], "Mithril Band of the Unscarred", "BIS")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "28649", L["Ring"], "Garona's Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29283", L["Ring"], "Violet Signet of the Master Assassin", "Alt")
LoonBestInSlot:AddItem(spec, "29379", L["Ring"], "Ring of Arathi Warlords", "Alt")

LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "21670", L["Trinket"], "Badge of the Swarmguard", "Alt")

LoonBestInSlot:AddItem(spec, "28438", L["MH"], "Dragonmaw", "BIS")
LoonBestInSlot:AddItem(spec, "28657", L["MH"], "Fool's Bane", "Alt")
LoonBestInSlot:AddItem(spec, "28767", L["MH"], "The Decapitator", "Alt")
LoonBestInSlot:AddItem(spec, "23054", L["MH"], "Gressil, Dawn of Ruin", "Alt")

LoonBestInSlot:AddItem(spec, "28729", L["OH"], "Spiteblade", "BIS")
LoonBestInSlot:AddItem(spec, "30733", L["OH"], "Hope Ender", "BIS")

LoonBestInSlot:AddItem(spec, "28429", L["2H"], "Lionheart Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28573", L["2H"], "Despair", "Alt")
LoonBestInSlot:AddItem(spec, "28773", L["2H"], "Gorehowl", "Alt")

LoonBestInSlot:AddItem(spec, "30724", L["Ranged"], "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28772", L["Ranged"], "Sunfury Bow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "30279", L["Ranged"], "Mama's Insurance", "BIS")
LoonBestInSlot:AddItem(spec, "29211", L["Ranged"], "Fitz's Throwing Axe", "Alt")
LoonBestInSlot:AddItem(spec, "22811", L["Ranged"], "Soulstring", "Alt")
