local spec = LoonBestInSlot:RegisterSpec("Warrior", "Fury", "1")
LoonBestInSlot:AddItem(spec, "29021", "Head", "Warbringer Battle-Helm", "BIS")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "BIS")

LoonBestInSlot:AddItem(spec, "29023", "Shoulders", "Warbringer Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30740", "Shoulders", "Ripfiend Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "33173", "Shoulders", "Ragesteel Shoulders", "BIS")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "30729", "Back", "Black-Iron Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt")

LoonBestInSlot:AddItem(spec, "29019", "Chest", "Warbringer Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "23522", "Chest", "Ragesteel Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "24544", "Chest", "Gladiator's Plate Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "31548", "Chest", "Blackened Chestplate", "Alt")

LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "BIS")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28381", "Bracers", "General's Plate Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30399", "Bracers", "Nightstalker's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "28824", "Gloves", "Gauntlets of Martial Perfection", "BIS")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "29020", "Gloves", "Warbringer Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "27497", "Gloves", "Doomplate Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28776", "Gloves", "Liar's Tongue Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "BIS")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "30739", "Legs", "Scaled Greaves of the Marksman", "BIS")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "29022", "Legs", "Warbringer Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "BIS")

LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "BIS")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29349", "Neck", "Adamantine Chain of the Unbroken", "Alt")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "BIS")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "BIS")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred", "Alt")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "Alt")

LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "BIS")
LoonBestInSlot:AddItem(spec, "28657", "MH", "Fool's Bane", "Alt")
LoonBestInSlot:AddItem(spec, "28767", "MH", "The Decapitator", "Alt")
LoonBestInSlot:AddItem(spec, "23054", "MH", "Gressil, Dawn of Ruin", "Alt")

LoonBestInSlot:AddItem(spec, "28729", "OH", "Spiteblade", "BIS")
LoonBestInSlot:AddItem(spec, "30733", "OH", "Hope Ender", "BIS")

LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "30279", "Ranged", "Mama's Insurance", "BIS")
LoonBestInSlot:AddItem(spec, "29211", "Ranged", "Fitz's Throwing Axe", "Alt")
LoonBestInSlot:AddItem(spec, "22811", "Ranged", "Soulstring", "Alt")
