local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "2")
LoonBestInSlot:AddItem(spec, "30233", "Head", "Nordrassil Headpiece", "BIS")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer", "Alt")
LoonBestInSlot:AddItem(spec, "32480", "Head", "Magnified Moon Specs", "Alt")
LoonBestInSlot:AddItem(spec, "29093", "Head", "Antlers of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "Alt")
LoonBestInSlot:AddItem(spec, "32057", "Head", "Merciless Gladiator's Wyrmhide Helm", "Alt")

LoonBestInSlot:AddItem(spec, "30235", "Shoulders", "Nordrassil Wrath-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings", "Alt")
LoonBestInSlot:AddItem(spec, "30079", "Shoulders", "Illidari Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "29095", "Shoulders", "Pauldrons of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "32059", "Shoulders", "Merciless Gladiator's Wyrmhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "BIS")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "BIS")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran", "Alt")

LoonBestInSlot:AddItem(spec, "30231", "Chest", "Nordrassil Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes", "Alt")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "29091", "Chest", "Chestpiece of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32060", "Chest", "Merciless Gladiator's Wyrmhide Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32655", "Bracers", "Crystalweave Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "Alt")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom", "Alt")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds", "Alt")

LoonBestInSlot:AddItem(spec, "30232", "Gloves", "Nordrassil Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "29092", "Gloves", "Gloves of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "Alt")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "Alt")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "BIS")
LoonBestInSlot:AddItem(spec, "30234", "Legs", "Nordrassil Wrath-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer", "Alt")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist", "Alt")
LoonBestInSlot:AddItem(spec, "29141", "Legs", "Tempest Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29142", "Legs", "Kurenai Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling", "Alt")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers", "Alt")

LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "Alt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "33067", "Neck", "Veteran's Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night", "Alt")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt")

LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "BIS")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "BIS")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29367", "Ring", "Ring of Cryptic Dreams", "Alt")

LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "32963", "MH", "Merciless Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "32053", "MH", "Merciless Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "BIS")
LoonBestInSlot:AddItem(spec, "28297", "MH", "Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "Alt")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")

LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key", "BIS")
LoonBestInSlot:AddItem(spec, "32055", "2H", "Merciless Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "24557", "2H", "Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "35514", "2H", "Frostscythe of Lord Ahune", "Alt")
LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "Alt")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff", "Alt")

LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone", "BIS")
LoonBestInSlot:AddItem(spec, "29271", "OH", "Talisman of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "Alt")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack", "Alt")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance", "Alt")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane", "Alt")

LoonBestInSlot:AddItem(spec, "27518", "Idol", "Ivory Idol of the Moongoddess", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "31025", "Idol", "Idol of the Avenger", "Alt")
LoonBestInSlot:AddItem(spec, "23197", "Idol", "Idol of the Moon", "Alt")
