local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "2")
LoonBestInSlot:AddItem(spec, "30219", "Head", "Nordrassil Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32479", "Head", "Wonderheal XT40 Shades", "BIS")
LoonBestInSlot:AddItem(spec, "29086", "Head", "Crown of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "Alt")

LoonBestInSlot:AddItem(spec, "30221", "Shoulders", "Nordrassil Life-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30111", "Shoulders", "Runetotem's Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "29089", "Shoulders", "Shoulderguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32653", "Back", "Apexis Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "30216", "Chest", "Nordrassil Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30075", "Chest", "Gnarled Chestpiece of the Ancients", "Alt")

LoonBestInSlot:AddItem(spec, "30062", "Bracers", "Grove-Bands of Remulos", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "BIS")
LoonBestInSlot:AddItem(spec, "30217", "Gloves", "Nordrassil Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30029", "Gloves", "Bark-Gloves of Ancient Wisdom", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "29984", "Belt", "Girdle of Zaetar", "BIS")

LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30220", "Legs", "Nordrassil Life-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "Alt")
LoonBestInSlot:AddItem(spec, "29977", "Legs", "Star-Soul Breeches", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30100", "Feet", "Soul-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30035", "Feet", "Boots of the Long Road", "Alt")

LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "Alt")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "32535", "Ring", "Gift of the Talonpriests", "Alt")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "Alt")

LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "BIS")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "Alt")

LoonBestInSlot:AddItem(spec, "29981", "2H", "Ethereum Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "30732", "2H", "Exodar Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28782", "2H", "Crystalheart Pulse-Staff", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
