local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "2")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30230", "Shoulders", "Nordrassil Feral-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")

LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "Alt")
LoonBestInSlot:AddItem(spec, "31255", "Back", "Cloak of the Craft", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")

LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "BIS")
LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne", "BIS")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30222", "Chest", "Nordrassil Chestplate", "BIS")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "28601", "Chest", "Chestguard of the Conniver", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")

LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32814", "Bracers", "Veteran's Leather Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "30223", "Gloves", "Nordrassil Handgrips", "BIS")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "29507", "Gloves", "Windslayer Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "30372", "Belt", "Socrethar's Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "30042", "Belt", "Belt of Natural Power", "Alt")

LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "BIS")
LoonBestInSlot:AddItem(spec, "30229", "Legs", "Nordrassil Feral-Kilt", "BIS")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS")
LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30041", "Feet", "Boots of Natural Grace", "Alt")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking", "Alt")

LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "Alt")

LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")

LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "32654", "Trinket", "Crystalforged Trinket", "Alt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "Alt")

LoonBestInSlot:AddItem(spec, "32014", "2H", "Merciless Gladiator's Maul", "BIS")
LoonBestInSlot:AddItem(spec, "28658", "2H", "Terestian's Stranglestaff", "Alt")
LoonBestInSlot:AddItem(spec, "28476", "2H", "Gladiator's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "30021", "2H", "Wildfury Greatstaff", "Alt")
LoonBestInSlot:AddItem(spec, "29359", "2H", "Feral Staff of Lashing", "Alt")
LoonBestInSlot:AddItem(spec, "31334", "2H", "Staff of Natural Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden", "Alt")
LoonBestInSlot:AddItem(spec, "27877", "2H", "Draenic Wildstaff", "Alt")

LoonBestInSlot:AddItem(spec, "29390", "Idol", "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "28372", "Idol", "Idol of Feral Shadows", "BIS")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild", "Alt")
