local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "2")
LoonBestInSlot:AddItem(spec, "30219", L["Head"], "Nordrassil Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32479", L["Head"], "Wonderheal XT40 Shades", "BIS")
LoonBestInSlot:AddItem(spec, "29086", L["Head"], "Crown of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24264", L["Head"], "Whitemend Hood", "Alt")

LoonBestInSlot:AddItem(spec, "30221", L["Shoulders"], "Nordrassil Life-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30111", L["Shoulders"], "Runetotem's Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "21874", L["Shoulders"], "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "29089", L["Shoulders"], "Shoulderguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "29989", L["Back"], "Sunshower Light Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", L["Back"], "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "31329", L["Back"], "Lifegiving Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32653", L["Back"], "Apexis Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "30216", L["Chest"], "Nordrassil Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21875", L["Chest"], "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30075", L["Chest"], "Gnarled Chestpiece of the Ancients", "Alt")

LoonBestInSlot:AddItem(spec, "30062", L["Bracers"], "Grove-Bands of Remulos", "BIS")
LoonBestInSlot:AddItem(spec, "29523", L["Bracers"], "Windhawk Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29183", L["Bracers"], "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "28511", L["Bracers"], "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "28521", L["Gloves"], "Mitts of the Treemender", "BIS")
LoonBestInSlot:AddItem(spec, "30217", L["Gloves"], "Nordrassil Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30029", L["Gloves"], "Bark-Gloves of Ancient Wisdom", "Alt")

LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30036", L["Belt"], "Belt of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "29984", L["Belt"], "Girdle of Zaetar", "BIS")

LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28591", L["Legs"], "Earthsoul Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30220", L["Legs"], "Nordrassil Life-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24261", L["Legs"], "Whitemend Pants", "Alt")
LoonBestInSlot:AddItem(spec, "29977", L["Legs"], "Star-Soul Breeches", "Alt")

LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "30092", L["Feet"], "Orca-Hide Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30100", L["Feet"], "Soul-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28752", L["Feet"], "Forestlord Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30035", L["Feet"], "Boots of the Long Road", "Alt")

LoonBestInSlot:AddItem(spec, "30018", L["Neck"], "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "28822", L["Neck"], "Teeth of Gruul", "Alt")
LoonBestInSlot:AddItem(spec, "28609", L["Neck"], "Emberspur Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "30110", L["Ring"], "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "28763", L["Ring"], "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "29290", L["Ring"], "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "30736", L["Ring"], "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "32535", L["Ring"], "Gift of the Talonpriests", "Alt")
LoonBestInSlot:AddItem(spec, "28790", L["Ring"], "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "25634", L["Trinket"], "Oshu'gun Relic", "Alt")

LoonBestInSlot:AddItem(spec, "30108", L["MH"], "Lightfathom Scepter", "BIS")
LoonBestInSlot:AddItem(spec, "28771", L["MH"], "Light's Justice", "Alt")

LoonBestInSlot:AddItem(spec, "29981", L["2H"], "Ethereum Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "30732", L["2H"], "Exodar Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28782", L["2H"], "Crystalheart Pulse-Staff", "Alt")

LoonBestInSlot:AddItem(spec, "29274", L["OH"], "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", L["OH"], "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "29923", L["OH"], "Talisman of the Sun King", "Alt")

LoonBestInSlot:AddItem(spec, "27886", L["Idol"], "Idol of the Emerald Queen", "BIS")
