local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "2")
LoonBestInSlot:AddItem(spec, "30228", L["Head"], "Nordrassil Headdress", "BIS")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "8345", L["Head"], "Wolfshead Helm", "BIS")
LoonBestInSlot:AddItem(spec, "29098", L["Head"], "Stag-Helm of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31968", L["Head"], "Merciless Gladiator's Dragonhide Helm", "Alt")

LoonBestInSlot:AddItem(spec, "30230", L["Shoulders"], "Nordrassil Feral-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "29100", L["Shoulders"], "Mantle of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31971", L["Shoulders"], "Merciless Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "28660", L["Back"], "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30098", L["Back"], "Razor-Scale Battlecloak", "Alt")

LoonBestInSlot:AddItem(spec, "30222", L["Chest"], "Nordrassil Chestplate", "BIS")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29096", L["Chest"], "Breastplate of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31972", L["Chest"], "Merciless Gladiator's Dragonhide Tunic", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30101", L["Chest"], "Bloodsea Brigand's Vest", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "29966", L["Bracers"], "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "32810", L["Bracers"], "Veteran's Dragonhide Bracers", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28978", L["Bracers"], "Marshal's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28445", L["Bracers"], "General's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28988", L["Bracers"], "Marshal's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28424", L["Bracers"], "General's Leather Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "30223", L["Gloves"], "Nordrassil Handgrips", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29097", L["Gloves"], "Gauntlets of Malorne", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29758", L["Gloves"], "Gloves of the Fallen Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30644", L["Gloves"], "Grips of Deftness", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "31967", L["Gloves"], "Merciless Gladiator's Dragonhide Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30042", L["Belt"], "Belt of Natural Power", "Alt")
LoonBestInSlot:AddItem(spec, "30040", L["Belt"], "Belt of Deep Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "29264", L["Belt"], "Tree-Mender's Belt", "Alt")
LoonBestInSlot:AddItem(spec, "32802", L["Belt"], "Veteran's Leather Belt", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30229", L["Legs"], "Nordrassil Feral-Kilt", "BIS")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29099", L["Legs"], "Greaves of Malorne", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29767", L["Legs"], "Leggings of the Fallen Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29995", L["Legs"], "Leggings of Murderous Intent", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28741", L["Legs"], "Skulker's Greaves", "Alt")

LoonBestInSlot:AddItem(spec, "30041", L["Feet"], "Boots of Natural Grace", "BIS")
LoonBestInSlot:AddItem(spec, "32790", L["Feet"], "Veteran's Leather Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30674", L["Feet"], "Zierhut's Lost Treads", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30060", L["Feet"], "Boots of Effortless Striking", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "33066", L["Neck"], "Veteran's Pendant of Triumph", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30099", L["Neck"], "Frayed Tether of the Drowned", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28509", L["Neck"], "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "29381", L["Neck"], "Choker of Vile Intent", "Alt")

LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28792", L["Ring"], "A'dal's Signet of Defense", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33054", L["Ring"], "The Seal of Danzalar", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30061", L["Ring"], "Ancestral Ring of Conquest", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32658", L["Trinket"], "Badge of Tenacity", "BIS")
LoonBestInSlot:AddItem(spec, "28579", L["Trinket"], "Romulo's Poison Vial", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28121", L["Trinket"], "Icon of Unyielding Courage", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "38287", L["Trinket"], "Empty Mug of Direbrew", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "23836", L["Trinket"], "Goblin Rocket Launcher", "Alt Mit")
LoonBestInSlot:AddItem(spec, "23835", L["Trinket"], "Gnomish Poultryizer", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30620", L["Trinket"], "Spyglass of the Hidden Fleet", "Alt Mit")
LoonBestInSlot:AddItem(spec, "13503", L["Trinket"], "Alchemist's Stone", "Alt")
LoonBestInSlot:AddItem(spec, "19406", L["Trinket"], "Drake Fang Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29181", L["Trinket"], "Timelapse Shard", "BIS Mit")

LoonBestInSlot:AddItem(spec, "30021", L["2H"], "Wildfury Greatstaff", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32014", L["2H"], "Merciless Gladiator's Maul", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28658", L["2H"], "Terestian's Stranglestaff", "Alt")
LoonBestInSlot:AddItem(spec, "28476", L["2H"], "Gladiator's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "29171", L["2H"], "Earthwarden", "Alt")

LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "23198", L["Idol"], "Idol of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "28064", L["Idol"], "Idol of the Wild", "BIS")
