local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "2")
LoonBestInSlot:AddItem(spec, "30228", "Head", "Nordrassil Headdress", "BIS")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm", "BIS")
LoonBestInSlot:AddItem(spec, "29098", "Head", "Stag-Helm of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31968", "Head", "Merciless Gladiator's Dragonhide Helm", "Alt")

LoonBestInSlot:AddItem(spec, "30230", "Shoulders", "Nordrassil Feral-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31971", "Shoulders", "Merciless Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "Alt")

LoonBestInSlot:AddItem(spec, "30222", "Chest", "Nordrassil Chestplate", "BIS")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "31972", "Chest", "Merciless Gladiator's Dragonhide Tunic", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "32810", "Bracers", "Veteran's Dragonhide Bracers", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28978", "Bracers", "Marshal's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28445", "Bracers", "General's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28988", "Bracers", "Marshal's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28424", "Bracers", "General's Leather Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "30223", "Gloves", "Nordrassil Handgrips", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29097", "Gloves", "Gauntlets of Malorne", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "31967", "Gloves", "Merciless Gladiator's Dragonhide Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30042", "Belt", "Belt of Natural Power", "Alt")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "29264", "Belt", "Tree-Mender's Belt", "Alt")
LoonBestInSlot:AddItem(spec, "32802", "Belt", "Veteran's Leather Belt", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30229", "Legs", "Nordrassil Feral-Kilt", "BIS")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29099", "Legs", "Greaves of Malorne", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "Alt")

LoonBestInSlot:AddItem(spec, "30041", "Feet", "Boots of Natural Grace", "BIS")
LoonBestInSlot:AddItem(spec, "32790", "Feet", "Veteran's Leather Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30674", "Feet", "Zierhut's Lost Treads", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "33066", "Neck", "Veteran's Pendant of Triumph", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30099", "Neck", "Frayed Tether of the Drowned", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33054", "Ring", "The Seal of Danzalar", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32658", "Trinket", "Badge of Tenacity", "BIS")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "Alt Mit")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30620", "Trinket", "Spyglass of the Hidden Fleet", "Alt Mit")
LoonBestInSlot:AddItem(spec, "13503", "Trinket", "Alchemist's Stone", "Alt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29181", "Trinket", "Timelapse Shard", "BIS Mit")

LoonBestInSlot:AddItem(spec, "30021", "2H", "Wildfury Greatstaff", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32014", "2H", "Merciless Gladiator's Maul", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28658", "2H", "Terestian's Stranglestaff", "Alt")
LoonBestInSlot:AddItem(spec, "28476", "2H", "Gladiator's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden", "Alt")

LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "23198", "Idol", "Idol of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild", "BIS")
