local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "2")
LoonBestInSlot:AddItem(spec, "30219", "Head", "Nordrassil Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32479", "Head", "Wonderheal XT40 Shades", "BIS")
LoonBestInSlot:AddItem(spec, "29086", "Head", "Crown of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28803", "Head", "Cowl of Nature's Breath", "Alt")

LoonBestInSlot:AddItem(spec, "30221", "Shoulders", "Nordrassil Life-Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30111", "Shoulders", "Runetotem's Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "29089", "Shoulders", "Shoulderguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28612", "Shoulders", "Pauldrons of the Solace-Giver", "Alt")
LoonBestInSlot:AddItem(spec, "28647", "Shoulders", "Forest Wind Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32653", "Back", "Apexis Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "30216", "Chest", "Nordrassil Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29087", "Chest", "Chestguard of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30075", "Chest", "Gnarled Chestpiece of the Ancients", "Alt")

LoonBestInSlot:AddItem(spec, "30062", "Bracers", "Grove-Bands of Remulos", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "BIS")
LoonBestInSlot:AddItem(spec, "30217", "Gloves", "Nordrassil Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "29090", "Gloves", "Handguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "Alt")
LoonBestInSlot:AddItem(spec, "30029", "Gloves", "Bark-Gloves of Ancient Wisdom", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "29984", "Belt", "Girdle of Zaetar", "BIS")
LoonBestInSlot:AddItem(spec, "28655", "Belt", "Cord of Nature's Sustenance", "Alt")
LoonBestInSlot:AddItem(spec, "28652", "Belt", "Cincture of Will", "Alt")

LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30220", "Legs", "Nordrassil Life-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "Alt")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "29977", "Legs", "Star-Soul Breeches", "Alt")
LoonBestInSlot:AddItem(spec, "29088", "Legs", "Legguards of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30100", "Feet", "Soul-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30035", "Feet", "Boots of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt", "Alt")

LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "Alt")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28731", "Neck", "Shining Chain of the Afterworld", "Alt")

LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "BIS")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "32535", "Ring", "Gift of the Talonpriests", "Alt")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "Alt")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "28727", "Trinket", "Pendant of the Violet Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "Alt")

LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "BIS")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "Alt")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")

LoonBestInSlot:AddItem(spec, "29981", "2H", "Ethereum Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "30732", "2H", "Exodar Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28782", "2H", "Crystalheart Pulse-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28604", "2H", "Nightstaff of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "22632", "2H", "Atiesh, Greatstaff of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28525", "OH", "Signet of Unshakable Faith", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
