local spec = LoonBestInSlot:RegisterSpec("Hunter", "Marks", "2")
LoonBestInSlot:AddItem(spec, "30141", L["Head"], "Rift Stalker Helm", "BIS")
LoonBestInSlot:AddItem(spec, "30244", L["Head"], "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28275", L["Head"], "Beast Lord Helm", "Alt")
LoonBestInSlot:AddItem(spec, "32087", L["Head"], "Mask of the Deceiver", "Alt")

LoonBestInSlot:AddItem(spec, "30143", L["Shoulders"], "Rift Stalker Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30250", L["Shoulders"], "Pauldrons of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27801", L["Shoulders"], "Beast Lord Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "30085", L["Shoulders"], "Mantle of the Tireless Tracker", "Alt")

LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", L["Back"], "Vengeance Wrap", "Alt")

LoonBestInSlot:AddItem(spec, "30139", L["Chest"], "Rift Stalker Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "30238", L["Chest"], "Chestguard of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28228", L["Chest"], "Beast Lord Cuirass", "Alt")
LoonBestInSlot:AddItem(spec, "30054", L["Chest"], "Ranger-General's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29525", L["Chest"], "Primalstrike Vest", "Alt")

LoonBestInSlot:AddItem(spec, "29966", L["Bracers"], "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "30026", L["Bracers"], "Bands of the Celestial Archer", "Alt")
LoonBestInSlot:AddItem(spec, "30091", L["Bracers"], "True-Aim Stalker Bands", "Alt")
LoonBestInSlot:AddItem(spec, "29246", L["Bracers"], "Nightfall Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "29527", L["Bracers"], "Primalstrike Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "30140", L["Gloves"], "Rift Stalker Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "30241", L["Gloves"], "Gloves of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27474", L["Gloves"], "Beast Lord Handguards", "Alt")

LoonBestInSlot:AddItem(spec, "30040", L["Belt"], "Belt of Deep Shadow", "BIS")
LoonBestInSlot:AddItem(spec, "30046", L["Belt"], "Belt of the Black Eagle", "Alt")
LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "Alt")
LoonBestInSlot:AddItem(spec, "28828", L["Belt"], "Gronn-Stitched Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "29995", L["Legs"], "Leggings of Murderous Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29985", L["Legs"], "Void Reaver Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30739", L["Legs"], "Scaled Greaves of the Marksman", "Alt")
LoonBestInSlot:AddItem(spec, "30142", L["Legs"], "Rift Stalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30247", L["Legs"], "Leggings of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30104", L["Feet"], "Cobra-Lash Boots", "BIS")
LoonBestInSlot:AddItem(spec, "29951", L["Feet"], "Star-Strider Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30060", L["Feet"], "Boots of Effortless Striking", "Alt")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "30059", L["Neck"], "Choker of Animalistic Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29381", L["Neck"], "Choker of Vile Intent", "Alt")

LoonBestInSlot:AddItem(spec, "28791", L["Ring"], "Ring of the Recalcitrant", "BIS")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "BIS")
LoonBestInSlot:AddItem(spec, "29298", L["Ring"], "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", L["Ring"], "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "28649", L["Ring"], "Garona's Signet Ring", "Alt")

LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "32944", L["MH"], "Talon of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "27846", L["MH"], "Claw of the Watcher", "Alt")
LoonBestInSlot:AddItem(spec, "29924", L["MH"], "Netherbane", "Alt")

LoonBestInSlot:AddItem(spec, "29948", L["OH"], "Claw of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28315", L["OH"], "Stormreaver Warblades", "Alt")

LoonBestInSlot:AddItem(spec, "29993", L["2H"], "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28436", L["2H"], "Bloodmoon", "BIS")
LoonBestInSlot:AddItem(spec, "28435", L["2H"], "Mooncleaver", "Alt")

LoonBestInSlot:AddItem(spec, "30105", L["Ranged"], "Serpent Spine Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "31986", L["Ranged"], "Merciless Gladiator's Crossbow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28772", L["Ranged"], "Sunfury Bow of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "30724", L["Ranged"], "Barrel-Blade Longrifle", "Alt")
LoonBestInSlot:AddItem(spec, "29949", L["Ranged"], "Arcanite Steam-Pistol", "Alt")
