local spec = LoonBestInSlot:RegisterSpec("Hunter", "BeastMaster", "2")
LoonBestInSlot:AddItem(spec, "30141", "Head", "Rift Stalker Helm", "BIS")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28275", "Head", "Beast Lord Helm", "Alt")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "Alt")

LoonBestInSlot:AddItem(spec, "30143", "Shoulders", "Rift Stalker Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27801", "Shoulders", "Beast Lord Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "30085", "Shoulders", "Mantle of the Tireless Tracker", "Alt")

LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")

LoonBestInSlot:AddItem(spec, "30139", "Chest", "Rift Stalker Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28228", "Chest", "Beast Lord Cuirass", "Alt")
LoonBestInSlot:AddItem(spec, "30054", "Chest", "Ranger-General's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")

LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "30026", "Bracers", "Bands of the Celestial Archer", "Alt")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands", "Alt")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "30140", "Gloves", "Rift Stalker Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27474", "Gloves", "Beast Lord Handguards", "Alt")

LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "BIS")
LoonBestInSlot:AddItem(spec, "30046", "Belt", "Belt of the Black Eagle", "Alt")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "Alt")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29985", "Legs", "Void Reaver Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30739", "Legs", "Scaled Greaves of the Marksman", "Alt")
LoonBestInSlot:AddItem(spec, "30142", "Legs", "Rift Stalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots", "BIS")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking", "Alt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "30059", "Neck", "Choker of Animalistic Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")

LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "BIS")
LoonBestInSlot:AddItem(spec, "29298", "Ring", "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "27846", "MH", "Claw of the Watcher", "Alt")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane", "Alt")

LoonBestInSlot:AddItem(spec, "29948", "OH", "Claw of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28572", "OH", "Blade of the Unrequited", "Alt")

LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28436", "2H", "Bloodmoon", "BIS")
LoonBestInSlot:AddItem(spec, "28435", "2H", "Mooncleaver", "Alt")

LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "31986", "Ranged", "Merciless Gladiator's Crossbow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "Alt")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "Alt")
