local spec = LoonBestInSlot:RegisterSpec("Hunter", "Marks", "2")
LoonBestInSlot:AddItem(spec, "30141", "Head", "Rift Stalker Helm", "BIS")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28275", "Head", "Beast Lord Helm", "Alt")
LoonBestInSlot:AddItem(spec, "32474", "Head", "Surestrike Goggles v2.0", "Alt")
LoonBestInSlot:AddItem(spec, "29081", "Head", "Demon Stalker Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "29759", "Head", "Helm of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "Alt")

LoonBestInSlot:AddItem(spec, "30143", "Shoulders", "Rift Stalker Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27801", "Shoulders", "Beast Lord Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "30085", "Shoulders", "Mantle of the Tireless Tracker", "Alt")

LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker", "Alt")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "30139", "Chest", "Rift Stalker Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28228", "Chest", "Beast Lord Cuirass", "Alt")
LoonBestInSlot:AddItem(spec, "30054", "Chest", "Ranger-General's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor", "Alt")

LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "30026", "Bracers", "Bands of the Celestial Archer", "Alt")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands", "Alt")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "25697", "Bracers", "Felstalker Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "30140", "Gloves", "Rift Stalker Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "27474", "Gloves", "Beast Lord Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt")
LoonBestInSlot:AddItem(spec, "28827", "Gloves", "Gauntlets of the Dragonslayer", "Alt")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "BIS")
LoonBestInSlot:AddItem(spec, "30046", "Belt", "Belt of the Black Eagle", "Alt")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "Alt")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "Alt")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Alt")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28656", "Belt", "Girdle of the Prowler", "Alt")

LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29985", "Legs", "Void Reaver Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30739", "Legs", "Scaled Greaves of the Marksman", "Alt")
LoonBestInSlot:AddItem(spec, "30142", "Legs", "Rift Stalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "27874", "Legs", "Beast Lord Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots", "BIS")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking", "Alt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28669", "Feet", "Rapscallion Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders", "Alt")

LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "30059", "Neck", "Choker of Animalistic Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "19377", "Neck", "Prestor's Talisman of Connivery", "Alt")
LoonBestInSlot:AddItem(spec, "28343", "Neck", "Jagged Bark Pendant", "Alt")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing", "Alt")

LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "BIS")
LoonBestInSlot:AddItem(spec, "29298", "Ring", "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "23038", "Ring", "Band of Unnatural Forces", "Alt")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")
LoonBestInSlot:AddItem(spec, "30973", "Ring", "Band of Anguish", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "Alt")
LoonBestInSlot:AddItem(spec, "28041", "Trinket", "Bladefist's Breadth", "Alt")

LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "27846", "MH", "Claw of the Watcher", "Alt")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane", "Alt")
LoonBestInSlot:AddItem(spec, "29121", "MH", "Guile of Khoraazi", "Alt")
LoonBestInSlot:AddItem(spec, "28524", "MH", "Emerald Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "28584", "MH", "Big Bad Wolf's Paw", "Alt")
LoonBestInSlot:AddItem(spec, "28263", "MH", "Stellaris", "Alt")
LoonBestInSlot:AddItem(spec, "21673", "MH", "Silithid Claw", "Alt")
LoonBestInSlot:AddItem(spec, "30277", "MH", "Ripfang Paw", "Alt")

LoonBestInSlot:AddItem(spec, "29948", "OH", "Claw of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28572", "OH", "Blade of the Unrequited", "Alt")
LoonBestInSlot:AddItem(spec, "28315", "OH", "Stormreaver Warblades", "Alt")
LoonBestInSlot:AddItem(spec, "29372", "OH", "Void-Talon", "Alt")
LoonBestInSlot:AddItem(spec, "23242", "OH", "Claw of the Frost Wyrm", "Alt")

LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28436", "2H", "Bloodmoon", "BIS")
LoonBestInSlot:AddItem(spec, "28435", "2H", "Mooncleaver", "Alt")
LoonBestInSlot:AddItem(spec, "28587", "2H", "Legacy", "Alt")
LoonBestInSlot:AddItem(spec, "27903", "2H", "Sonic Spear", "Alt")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "23039", "2H", "The Eye of Nerub", "Alt")
LoonBestInSlot:AddItem(spec, "29329", "2H", "Terokk's Quill", "Alt")

LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "31986", "Ranged", "Merciless Gladiator's Crossbow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "Alt")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "Alt")
LoonBestInSlot:AddItem(spec, "28581", "Ranged", "Wolfslayer Sniper Rifle", "Alt")
LoonBestInSlot:AddItem(spec, "29351", "Ranged", "Wrathtide Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "31323", "Ranged", "Don Santos' Famous Hunting Rifle", "Alt")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket", "Alt")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow", "Alt")
LoonBestInSlot:AddItem(spec, "28504", "Ranged", "Steelhawk Crossbow", "Alt")
LoonBestInSlot:AddItem(spec, "22812", "Ranged", "Nerubian Slavemaker", "Alt")
LoonBestInSlot:AddItem(spec, "31303", "Ranged", "Valanos' Longbow", "Alt")
