local spec = LoonBestInSlot:RegisterSpec("Mage", "Fire", "2")
LoonBestInSlot:AddItem(spec, "24266", L["Head"], "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29986", L["Head"], "Cowl of the Grand Engineer", "Alt")
LoonBestInSlot:AddItem(spec, "30206", L["Head"], "Cowl of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30244", L["Head"], "Helm of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30210", L["Shoulders"], "Mantle of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30250", L["Shoulders"], "Pauldrons of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30024", L["Shoulders"], "Mantle of the Elven Kings", "BIS")
LoonBestInSlot:AddItem(spec, "30079", L["Shoulders"], "Illidari Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "29079", L["Shoulders"], "Pauldrons of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "29762", L["Shoulders"], "Pauldrons of the Fallen Hero", "Alt")

LoonBestInSlot:AddItem(spec, "28766", L["Back"], "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "29992", L["Back"], "Royal Cloak of the Sunstriders", "Alt")
LoonBestInSlot:AddItem(spec, "30735", L["Back"], "Ancient Spellcloak of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "30107", L["Chest"], "Vestments of the Sea-Witch", "BIS")
LoonBestInSlot:AddItem(spec, "21848", L["Chest"], "Spellfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30196", L["Chest"], "Robes of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30238", L["Chest"], "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30056", L["Chest"], "Robe of Hateful Echoes", "Alt")

LoonBestInSlot:AddItem(spec, "29918", L["Bracers"], "Mindstorm Wristbands", "BIS")
LoonBestInSlot:AddItem(spec, "24250", L["Bracers"], "Bracers of Havok", "Alt")
LoonBestInSlot:AddItem(spec, "28411", L["Bracers"], "General's Silk Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "21847", L["Gloves"], "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "30205", L["Gloves"], "Gloves of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30241", L["Gloves"], "Gloves of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "29987", L["Gloves"], "Gauntlets of the Sun King", "Alt")

LoonBestInSlot:AddItem(spec, "30038", L["Belt"], "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30064", L["Belt"], "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "21846", L["Belt"], "Spellfire Belt", "Alt")

LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30207", L["Legs"], "Leggings of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30247", L["Legs"], "Leggings of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "29972", L["Legs"], "Trousers of the Astromancer", "Alt")

LoonBestInSlot:AddItem(spec, "30037", L["Feet"], "Boots of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30067", L["Feet"], "Velvet Boots of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "28585", L["Feet"], "Ruby Slippers", "Alt")
LoonBestInSlot:AddItem(spec, "28517", L["Feet"], "Boots of Foretelling", "Alt")

LoonBestInSlot:AddItem(spec, "30015", L["Neck"], "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "28134", L["Neck"], "Brooch of Heightened Potential", "Alt")
LoonBestInSlot:AddItem(spec, "28530", L["Neck"], "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28762", L["Neck"], "Adornment of Stolen Souls", "Alt")
LoonBestInSlot:AddItem(spec, "30008", L["Neck"], "Pendant of the Lost Ages", "Alt")

LoonBestInSlot:AddItem(spec, "30109", L["Ring"], "Ring of Endless Coils", "BIS")
LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "28753", L["Ring"], "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "29172", L["Ring"], "Ashyen's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "21709", L["Ring"], "Ring of the Fallen God", "Alt")
LoonBestInSlot:AddItem(spec, "28227", L["Ring"], "Sparking Arcanite Ring", "Alt")
LoonBestInSlot:AddItem(spec, "28555", L["Ring"], "Seal of the Exorcist", "Alt")
LoonBestInSlot:AddItem(spec, "29922", L["Ring"], "Band of Al'ar", "Alt")

LoonBestInSlot:AddItem(spec, "30626", L["Trinket"], "Sextant of Unstable Currents", "BIS")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "29132", L["Trinket"], "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "30720", L["Trinket"], "Serpent-Coil Braid", "Alt")

LoonBestInSlot:AddItem(spec, "30095", L["MH"], "Fang of the Leviathan", "BIS")
LoonBestInSlot:AddItem(spec, "30723", L["MH"], "Talon of the Tempest", "Alt")

LoonBestInSlot:AddItem(spec, "29988", L["2H"], "The Nexus Key", "BIS")
LoonBestInSlot:AddItem(spec, "28633", L["2H"], "Staff of Infinite Mysteries", "Alt")

LoonBestInSlot:AddItem(spec, "29270", L["OH"], "Flametongue Seal", "BIS")
LoonBestInSlot:AddItem(spec, "30049", L["OH"], "Fathomstone", "Alt")

LoonBestInSlot:AddItem(spec, "29982", L["Wand"], "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "28783", L["Wand"], "Eredar Wand of Obliteration", "Alt")
LoonBestInSlot:AddItem(spec, "28673", L["Wand"], "Tirisfal Wand of Ascendancy", "Alt")
