local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "2")
LoonBestInSlot:AddItem(spec, "30125", "Head", "Crystalforge Faceguard", "BIS")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29068", "Head", "Justicar Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32473", "Head", "Tankatronic Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29070", "Shoulders", "Justicar Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30127", "Shoulders", "Crystalforge Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape", "Alt")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "29066", "Chest", "Justicar Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30123", "Chest", "Crystalforge Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "28203", "Chest", "Breastplate of the Righteous", "Alt")

LoonBestInSlot:AddItem(spec, "32515", "Bracers", "Wristguards of Determination", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29252", "Bracers", "Bracers of Dignity", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29998", "Gloves", "Royal Gauntlets of Silvermoon", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30124", "Gloves", "Crystalforge Handguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29067", "Gloves", "Justicar Handguards", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30034", "Belt", "Belt of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "30096", "Belt", "Girdle of the Invulnerable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29253", "Belt", "Girdle of Valorous Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable", "Alt")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30126", "Legs", "Crystalforge Legguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29069", "Legs", "Justicar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29766", "Legs", "Leggings of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30033", "Feet", "Boots of the Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32267", "Feet", "Boots of the Resilient", "Alt")
LoonBestInSlot:AddItem(spec, "29254", "Feet", "Boots of the Righteous Path", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30031", "Feet", "Red Havoc Boots", "Alt")

LoonBestInSlot:AddItem(spec, "30007", "Neck", "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline", "Alt")
LoonBestInSlot:AddItem(spec, "30099", "Neck", "Frayed Tether of the Drowned", "Alt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "Alt")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30008", "Neck", "Pendant of the Lost Ages", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33065", "Neck", "Veteran's Pendant of Dominance", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30083", "Ring", "Ring of Sundered Souls", "BIS")
LoonBestInSlot:AddItem(spec, "30028", "Ring", "Seventh Ring of the Tirisfalen", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa", "Alt")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt Stam")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33054", "Ring", "The Seal of Danzalar", "Alt")
LoonBestInSlot:AddItem(spec, "32774", "Ring", "The Black Pearl", "Alt")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30629", "Trinket", "Scarab of Displacement", "Alt Mit")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30447", "Trinket", "Tome of Fiery Redemption", "Alt")

LoonBestInSlot:AddItem(spec, "32963", "MH", "Merciless Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan", "BIS")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27917", "Libram", "Libram of the Eternal Rest", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "32045", "Shield", "Merciless Gladiator's Shield Wall", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33313", "Shield", "Merciless Gladiator's Barrier", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "BIS")
