local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "2")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "30131", "Head", "Crystalforge War-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32041", "Head", "Merciless Gladiator's Scaled Helm", "Alt")
LoonBestInSlot:AddItem(spec, "29073", "Head", "Justicar Crown", "Alt")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29983", "Head", "Fel-Steel Warhelm", "Alt")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "30133", "Shoulders", "Crystalforge Shoulderbraces", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29075", "Shoulders", "Justicar Shoulderplates", "Alt")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32043", "Shoulders", "Merciless Gladiator's Scaled Shoulders", "Alt")

LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "BIS")
LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings", "Alt")

LoonBestInSlot:AddItem(spec, "30129", "Chest", "Crystalforge Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28485", "Chest", "Bulwark of the Ancient Kings", "Alt")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "30102", "Chest", "Krakken-Heart Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29071", "Chest", "Justicar Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32039", "Chest", "Merciless Gladiator's Scaled Chestpiece", "Alt")

LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication", "BIS")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "BIS")

LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "Alt")

LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder", "BIS")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30132", "Legs", "Crystalforge Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration", "BIS")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "Alt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "BIS")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "BIS")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "28430", "2H", "Lionheart Executioner", "BIS")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28442", "2H", "Stormherald", "Alt")
LoonBestInSlot:AddItem(spec, "31984", "2H", "Merciless Gladiator's Greatsword", "Alt")
LoonBestInSlot:AddItem(spec, "30090", "2H", "World Breaker", "Alt")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement", "BIS")
