local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "2")
LoonBestInSlot:AddItem(spec, "32461", L["Head"], "Furious Gizmatic Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "30131", L["Head"], "Crystalforge War-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32041", L["Head"], "Merciless Gladiator's Scaled Helm", "Alt")
LoonBestInSlot:AddItem(spec, "29073", L["Head"], "Justicar Crown", "Alt")
LoonBestInSlot:AddItem(spec, "29760", L["Head"], "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29983", L["Head"], "Fel-Steel Warhelm", "Alt")

LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "30133", L["Shoulders"], "Crystalforge Shoulderbraces", "Alt")
LoonBestInSlot:AddItem(spec, "30248", L["Shoulders"], "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29075", L["Shoulders"], "Justicar Shoulderplates", "Alt")
LoonBestInSlot:AddItem(spec, "29763", L["Shoulders"], "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32043", L["Shoulders"], "Merciless Gladiator's Scaled Shoulders", "Alt")

LoonBestInSlot:AddItem(spec, "30098", L["Back"], "Razor-Scale Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "27878", L["Back"], "Auchenai Death Shroud", "BIS")
LoonBestInSlot:AddItem(spec, "28529", L["Back"], "Royal Cloak of Arathi Kings", "Alt")

LoonBestInSlot:AddItem(spec, "30129", L["Chest"], "Crystalforge Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28485", L["Chest"], "Bulwark of the Ancient Kings", "Alt")
LoonBestInSlot:AddItem(spec, "30101", L["Chest"], "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "30102", L["Chest"], "Krakken-Heart Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29071", L["Chest"], "Justicar Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29754", L["Chest"], "Chestguard of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32039", L["Chest"], "Merciless Gladiator's Scaled Chestpiece", "Alt")

LoonBestInSlot:AddItem(spec, "30057", L["Bracers"], "Bracers of Eradication", "BIS")
LoonBestInSlot:AddItem(spec, "28795", L["Bracers"], "Bladespire Warbands", "BIS")

LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "30644", L["Gloves"], "Grips of Deftness", "Alt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "28779", L["Belt"], "Girdle of the Endless Pit", "Alt")

LoonBestInSlot:AddItem(spec, "29950", L["Legs"], "Greaves of the Bloodwarder", "BIS")
LoonBestInSlot:AddItem(spec, "30257", L["Legs"], "Shattrath Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "29995", L["Legs"], "Leggings of Murderous Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30132", L["Legs"], "Crystalforge Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30245", L["Legs"], "Leggings of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "31544", L["Legs"], "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30081", L["Feet"], "Warboots of Obliteration", "BIS")
LoonBestInSlot:AddItem(spec, "29951", L["Feet"], "Star-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30104", L["Feet"], "Cobra-Lash Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28608", L["Feet"], "Ironstriders of Urgency", "Alt")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "30022", L["Neck"], "Pendant of the Perilous", "BIS")
LoonBestInSlot:AddItem(spec, "29381", L["Neck"], "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "28509", L["Neck"], "Worgen Claw Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30061", L["Ring"], "Ancestral Ring of Conquest", "BIS")
LoonBestInSlot:AddItem(spec, "30738", L["Ring"], "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", L["Ring"], "Ring of a Thousand Marks", "Alt")

LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "28288", L["Trinket"], "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "38287", L["Trinket"], "Empty Mug of Direbrew", "Alt")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "28430", L["2H"], "Lionheart Executioner", "BIS")
LoonBestInSlot:AddItem(spec, "29993", L["2H"], "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "28442", L["2H"], "Stormherald", "Alt")
LoonBestInSlot:AddItem(spec, "31984", L["2H"], "Merciless Gladiator's Greatsword", "Alt")
LoonBestInSlot:AddItem(spec, "30090", L["2H"], "World Breaker", "Alt")

LoonBestInSlot:AddItem(spec, "27484", L["Libram"], "Libram of Avengement", "BIS")
