local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "2")
LoonBestInSlot:AddItem(spec, "30125", L["Head"], "Crystalforge Faceguard", "BIS")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29068", L["Head"], "Justicar Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "29760", L["Head"], "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32473", L["Head"], "Tankatronic Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "32083", L["Head"], "Faceguard of Determination", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29070", L["Shoulders"], "Justicar Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "29763", L["Shoulders"], "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30127", L["Shoulders"], "Crystalforge Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "30248", L["Shoulders"], "Pauldrons of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "29925", L["Back"], "Phoenix-Wing Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "27804", L["Back"], "Devilshark Cape", "Alt")
LoonBestInSlot:AddItem(spec, "29992", L["Back"], "Royal Cloak of the Sunstriders", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "29066", L["Chest"], "Justicar Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29754", L["Chest"], "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30123", L["Chest"], "Crystalforge Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28597", L["Chest"], "Panzar'Thar Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "28203", L["Chest"], "Breastplate of the Righteous", "Alt")

LoonBestInSlot:AddItem(spec, "32515", L["Bracers"], "Wristguards of Determination", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29252", L["Bracers"], "Bracers of Dignity", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23538", L["Bracers"], "Bracers of the Green Fortress", "Alt Mit")

LoonBestInSlot:AddItem(spec, "29998", L["Gloves"], "Royal Gauntlets of Silvermoon", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30124", L["Gloves"], "Crystalforge Handguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30239", L["Gloves"], "Gloves of the Vanquished Champion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29067", L["Gloves"], "Justicar Handguards", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29757", L["Gloves"], "Gloves of the Fallen Champion", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28518", L["Gloves"], "Iron Gauntlets of the Maiden", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30034", L["Belt"], "Belt of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "30096", L["Belt"], "Girdle of the Invulnerable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29253", L["Belt"], "Girdle of Valorous Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28566", L["Belt"], "Crimson Girdle of the Indomitable", "Alt")
LoonBestInSlot:AddItem(spec, "30064", L["Belt"], "Cord of Screaming Terrors", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30126", L["Legs"], "Crystalforge Legguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30245", L["Legs"], "Leggings of the Vanquished Champion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28621", L["Legs"], "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29069", L["Legs"], "Justicar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29766", L["Legs"], "Leggings of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30033", L["Feet"], "Boots of the Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30641", L["Feet"], "Boots of Elusion", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32267", L["Feet"], "Boots of the Resilient", "Alt")
LoonBestInSlot:AddItem(spec, "29254", L["Feet"], "Boots of the Righteous Path", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30031", L["Feet"], "Red Havoc Boots", "Alt")

LoonBestInSlot:AddItem(spec, "30007", L["Neck"], "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28516", L["Neck"], "Barbed Choker of Discipline", "Alt")
LoonBestInSlot:AddItem(spec, "30099", L["Neck"], "Frayed Tether of the Drowned", "Alt")
LoonBestInSlot:AddItem(spec, "29386", L["Neck"], "Necklace of the Juggernaut", "Alt")
LoonBestInSlot:AddItem(spec, "30015", L["Neck"], "The Sun King's Talisman", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30008", L["Neck"], "Pendant of the Lost Ages", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33065", L["Neck"], "Veteran's Pendant of Dominance", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30083", L["Ring"], "Ring of Sundered Souls", "BIS")
LoonBestInSlot:AddItem(spec, "30028", L["Ring"], "Seventh Ring of the Tirisfalen", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28407", L["Ring"], "Elementium Band of the Sentry", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "29922", L["Ring"], "Band of Al'ar", "Alt")
LoonBestInSlot:AddItem(spec, "30109", L["Ring"], "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "29352", L["Ring"], "Cobalt Band of Tyrigosa", "Alt")
LoonBestInSlot:AddItem(spec, "29126", L["Ring"], "Seer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29287", L["Ring"], "Violet Signet of the Archmage", "Alt Stam")
LoonBestInSlot:AddItem(spec, "28555", L["Ring"], "Seal of the Exorcist", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33054", L["Ring"], "The Seal of Danzalar", "Alt")
LoonBestInSlot:AddItem(spec, "32774", L["Ring"], "The Black Pearl", "Alt")
LoonBestInSlot:AddItem(spec, "29172", L["Ring"], "Ashyen's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "28528", L["Trinket"], "Moroes' Lucky Pocket Watch", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27529", L["Trinket"], "Figurine of the Colossus", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30629", L["Trinket"], "Scarab of Displacement", "Alt Mit")
LoonBestInSlot:AddItem(spec, "27891", L["Trinket"], "Adamantine Figurine", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32534", L["Trinket"], "Brooch of the Immortal King", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28789", L["Trinket"], "Eye of Magtheridon", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30447", L["Trinket"], "Tome of Fiery Redemption", "Alt")

LoonBestInSlot:AddItem(spec, "32963", L["MH"], "Merciless Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30095", L["MH"], "Fang of the Leviathan", "BIS")
LoonBestInSlot:AddItem(spec, "28802", L["MH"], "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "32450", L["MH"], "Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30832", L["MH"], "Gavel of Unearthed Secrets", "Alt")

LoonBestInSlot:AddItem(spec, "29388", L["Libram"], "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27917", L["Libram"], "Libram of the Eternal Rest", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "32045", L["Shield"], "Merciless Gladiator's Shield Wall", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33313", L["Shield"], "Merciless Gladiator's Barrier", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28825", L["Shield"], "Aldori Legacy Defender", "BIS")
