local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "2")
LoonBestInSlot:AddItem(spec, "30125", "Head", "Crystalforge Faceguard", "BIS")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29068", "Head", "Justicar Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32473", "Head", "Tankatronic Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28593", "Head", "Eternium Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "27704", "Head", "Gladiator's Lamellar Helm", "Alt")
LoonBestInSlot:AddItem(spec, "23536", "Head", "Oathkeeper's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28285", "Head", "Helm of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "23519", "Head", "Felsteel Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28180", "Head", "Myrmidon's Headdress", "Alt")

LoonBestInSlot:AddItem(spec, "29070", "Shoulders", "Justicar Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30127", "Shoulders", "Crystalforge Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28743", "Shoulders", "Mantle of Abrahmis", "Alt")
LoonBestInSlot:AddItem(spec, "27706", "Shoulders", "Gladiator's Lamellar Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "27739", "Shoulders", "Spaulders of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "27847", "Shoulders", "Fanblade Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "32073", "Shoulders", "Spaulders of Dementia", "Alt")
LoonBestInSlot:AddItem(spec, "30381", "Shoulders", "Kaylaan's Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape", "Alt")
LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "24253", "Back", "Cloak of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "27988", "Back", "Burnoose of Shifting Ages", "Alt")
LoonBestInSlot:AddItem(spec, "24379", "Back", "Bogstrok Scale Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "29777", "Back", "Cloak of the Valiant Defender", "Alt")

LoonBestInSlot:AddItem(spec, "29066", "Chest", "Justicar Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30123", "Chest", "Crystalforge Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "27702", "Chest", "Gladiator's Lamellar Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "28203", "Chest", "Breastplate of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "28262", "Chest", "Jade-Skull Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29127", "Chest", "Vindicator's Hauberk", "Alt")

LoonBestInSlot:AddItem(spec, "32515", "Bracers", "Wristguards of Determination", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29252", "Bracers", "Bracers of Dignity", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage", "Alt")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor", "Alt")
LoonBestInSlot:AddItem(spec, "28167", "Bracers", "Sha'tari Wrought Armguards", "Alt")
LoonBestInSlot:AddItem(spec, "30400", "Bracers", "Thadell's Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "29998", "Gloves", "Royal Gauntlets of Silvermoon", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30124", "Gloves", "Crystalforge Handguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29067", "Gloves", "Justicar Handguards", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30741", "Gloves", "Topaz-Studded Battlegrips", "Alt")
LoonBestInSlot:AddItem(spec, "27703", "Gloves", "Gladiator's Lamellar Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "32072", "Gloves", "Gauntlets of Dissension", "Alt")
LoonBestInSlot:AddItem(spec, "27535", "Gloves", "Gauntlets of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "23517", "Gloves", "Felsteel Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29134", "Gloves", "Gauntlets of the Chosen", "Alt")

LoonBestInSlot:AddItem(spec, "30034", "Belt", "Belt of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "30096", "Belt", "Girdle of the Invulnerable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29253", "Belt", "Girdle of Valorous Deeds", "Alt")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable", "Alt")
LoonBestInSlot:AddItem(spec, "27672", "Belt", "Girdle of the Immovable", "Alt")
LoonBestInSlot:AddItem(spec, "31460", "Belt", "Sha'tari Vindicator's Waistguard", "Alt")
LoonBestInSlot:AddItem(spec, "29238", "Belt", "Lion's Heart Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "30371", "Belt", "Lightwarden's Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "30330", "Belt", "Starcaller's Plated Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30126", "Legs", "Crystalforge Legguards", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29069", "Legs", "Justicar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29766", "Legs", "Leggings of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27839", "Legs", "Legplates of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "23518", "Legs", "Felsteel Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29774", "Legs", "Kirin'Var Defender's Chausses", "Alt")

LoonBestInSlot:AddItem(spec, "30033", "Feet", "Boots of the Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32267", "Feet", "Boots of the Resilient", "Alt")
LoonBestInSlot:AddItem(spec, "29254", "Feet", "Boots of the Righteous Path", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30031", "Feet", "Red Havoc Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28747", "Feet", "Battlescar Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29239", "Feet", "Eaglecrest Warboots", "Alt")
LoonBestInSlot:AddItem(spec, "27813", "Feet", "Boots of the Colossus", "Alt")
LoonBestInSlot:AddItem(spec, "30334", "Feet", "Starcaller's Plated Stompers", "Alt")
LoonBestInSlot:AddItem(spec, "29325", "Feet", "Flesh Beast's Metal Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30386", "Feet", "Bloodguard's Greaves", "Alt")

LoonBestInSlot:AddItem(spec, "30007", "Neck", "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline", "Alt")
LoonBestInSlot:AddItem(spec, "29173", "Neck", "Strength of the Untamed", "Alt")
LoonBestInSlot:AddItem(spec, "27871", "Neck", "Maladaar's Blessed Chaplet", "Alt")
LoonBestInSlot:AddItem(spec, "30099", "Neck", "Frayed Tether of the Drowned", "Alt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "Alt")
LoonBestInSlot:AddItem(spec, "27792", "Neck", "Steam-Hinge Chain of Valor", "Alt")
LoonBestInSlot:AddItem(spec, "29336", "Neck", "Mark of the Ravenguard", "Alt")
LoonBestInSlot:AddItem(spec, "28321", "Neck", "Enchanted Thorium Torque", "Alt")
LoonBestInSlot:AddItem(spec, "25809", "Neck", "Maimfist's Choker", "Horde Alt")
LoonBestInSlot:AddItem(spec, "25803", "Neck", "Medallion of the Valiant Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "Alt")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30008", "Neck", "Pendant of the Lost Ages", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33065", "Neck", "Veteran's Pendant of Dominance", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30083", "Ring", "Ring of Sundered Souls", "BIS")
LoonBestInSlot:AddItem(spec, "30028", "Ring", "Seventh Ring of the Tirisfalen", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "Alt Stam")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring", "Alt Stam")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "Alt Stam")
LoonBestInSlot:AddItem(spec, "31319", "Ring", "Band of Impenetrable Defenses", "Alt")
LoonBestInSlot:AddItem(spec, "31924", "Ring", "Yor's Revenge", "Alt Stam")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force", "Alt Stam")
LoonBestInSlot:AddItem(spec, "27822", "Ring", "Crystal Band of Valor", "Alt")
LoonBestInSlot:AddItem(spec, "28211", "Ring", "Lieutenant's Signet of Lordaeron", "Alt")
LoonBestInSlot:AddItem(spec, "24088", "Ring", "Delicate Eternium Ring", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29323", "Ring", "Andormu's Tear", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28265", "Ring", "Dath'Remar's Ring of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa", "Alt")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt Stam")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33054", "Ring", "The Seal of Danzalar", "Alt")
LoonBestInSlot:AddItem(spec, "32774", "Ring", "The Black Pearl", "Alt")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30629", "Trinket", "Scarab of Displacement", "Alt  Mit")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30300", "Trinket", "Dabiri's Enigma", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "19431", "Trinket", "Styleen's Impeding Scarab", "Alt Mit")
LoonBestInSlot:AddItem(spec, "24125", "Trinket", "Figurine Dawnstone Crab", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28042", "Trinket", "Regal Protectorate", "Alt Mit")
LoonBestInSlot:AddItem(spec, "23040", "Trinket", "Glyph of Deflection", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600", "Alt Mit")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "Alt")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "Alt")
LoonBestInSlot:AddItem(spec, "32864", "Trinket", "Commander's Badge", "Alt")
LoonBestInSlot:AddItem(spec, "27770", "Trinket", "Argussian Compass", "Alt")
LoonBestInSlot:AddItem(spec, "24126", "Trinket", "Figurine - Living Ruby Serpent", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "13503", "Trinket", "Alchemist's Stone", "Alt")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt")
LoonBestInSlot:AddItem(spec, "30447", "Trinket", "Tome of Fiery Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "24126", "Trinket", "Figurine - Living Ruby Serpent", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "18820", "Trinket", "Talisman of Ephemeral Power", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "19950", "Trinket", "Zandalarian Hero Charm", "Alt")

LoonBestInSlot:AddItem(spec, "32963", "MH", "Merciless Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan", "BIS")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "Alt")
LoonBestInSlot:AddItem(spec, "32660", "MH", "Crystalforged Sword", "Alt")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "27899", "MH", "Mana Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams", "Alt")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27917", "Libram", "Libram of the Eternal Rest", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "32045", "Shield", "Merciless Gladiator's Shield Wall", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33313", "Shield", "Merciless Gladiator's Barrier", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28358", "Shield", "Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra", "Alt")
LoonBestInSlot:AddItem(spec, "32082", "Shield", "The Fel Barrier", "Alt")
LoonBestInSlot:AddItem(spec, "32652", "Shield", "Ogri'la Aegis", "Alt")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird", "Alt")
LoonBestInSlot:AddItem(spec, "27449", "Shield", "Blood Knight Defender", "Alt")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous", "Alt")
LoonBestInSlot:AddItem(spec, "23043", "Shield", "The Face of Death", "Alt")

