local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "2")
LoonBestInSlot:AddItem(spec, "30152", L["Head"], "Cowl of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32495", L["Head"], "Powerheal 4000 Lens", "Alt")
LoonBestInSlot:AddItem(spec, "29049", L["Head"], "Light-Collar of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29761", L["Head"], "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29990", L["Head"], "Crown of the Sun", "Alt")

LoonBestInSlot:AddItem(spec, "30154", L["Shoulders"], "Mantle of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21874", L["Shoulders"], "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "29054", L["Shoulders"], "Light-Mantle of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "29989", L["Back"], "Sunshower Light Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", L["Back"], "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "29354", L["Back"], "Light-Touched Stole of Altruism", "Alt")
LoonBestInSlot:AddItem(spec, "31329", L["Back"], "Lifegiving Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "30150", L["Chest"], "Vestments of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21875", L["Chest"], "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29050", L["Chest"], "Robes of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32980", L["Bracers"], "Veteran's Mooncloth Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "29183", L["Bracers"], "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "32516", L["Bracers"], "Wraps of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "28511", L["Bracers"], "Bands of Indwelling", "BIS")
LoonBestInSlot:AddItem(spec, "29249", L["Bracers"], "Bands of the Benevolent", "BIS")

LoonBestInSlot:AddItem(spec, "30151", L["Gloves"], "Gloves of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28508", L["Gloves"], "Gloves of Saintly Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "30036", L["Belt"], "Belt of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "BIS")

LoonBestInSlot:AddItem(spec, "30153", L["Legs"], "Breeches of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28742", L["Legs"], "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "29977", L["Legs"], "Star-Soul Breeches", "Alt")
LoonBestInSlot:AddItem(spec, "30543", L["Legs"], "Pontifex Kilt", "Alt")

LoonBestInSlot:AddItem(spec, "30100", L["Feet"], "Soul-Strider Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30035", L["Feet"], "Boots of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "28663", L["Feet"], "Boots of the Incorrupt", "Alt")
LoonBestInSlot:AddItem(spec, "29251", L["Feet"], "Boots of the Pious", "Alt")

LoonBestInSlot:AddItem(spec, "30018", L["Neck"], "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "30726", L["Neck"], "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "28609", L["Neck"], "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28822", L["Neck"], "Teeth of Gruul", "Alt")

LoonBestInSlot:AddItem(spec, "30110", L["Ring"], "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "29290", L["Ring"], "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "30736", L["Ring"], "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "28763", L["Ring"], "Jade Ring of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "29307", L["Ring"], "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29920", L["Ring"], "Phoenix-Ring of Rebirth", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "28823", L["Trinket"], "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "30665", L["Trinket"], "Earring of Soulful Meditation", "Alt")

LoonBestInSlot:AddItem(spec, "30108", L["MH"], "Lightfathom Scepter", "BIS")
LoonBestInSlot:AddItem(spec, "32964", L["MH"], "Merciless Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "29981", L["MH"], "Ethereum Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28771", L["MH"], "Light's Justice", "Alt")

LoonBestInSlot:AddItem(spec, "29923", L["OH"], "Talisman of the Sun King", "BIS")
LoonBestInSlot:AddItem(spec, "29170", L["OH"], "Windcaller's Orb", "Alt")
LoonBestInSlot:AddItem(spec, "29274", L["OH"], "Tears of Heaven", "Alt")

LoonBestInSlot:AddItem(spec, "30080", L["Wand"], "Luminescent Rod of the Naaru", "BIS")
LoonBestInSlot:AddItem(spec, "28588", L["Wand"], "Blue Diamond Witchwand", "Alt")
