local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "2")
LoonBestInSlot:AddItem(spec, "30152", "Head", "Cowl of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32495", "Head", "Powerheal 4000 Lens", "Alt")
LoonBestInSlot:AddItem(spec, "29049", "Head", "Light-Collar of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29990", "Head", "Crown of the Sun", "Alt")

LoonBestInSlot:AddItem(spec, "30154", "Shoulders", "Mantle of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "29054", "Shoulders", "Light-Mantle of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "Alt")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "30150", "Chest", "Vestments of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29050", "Chest", "Robes of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32980", "Bracers", "Veteran's Mooncloth Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "32516", "Bracers", "Wraps of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "BIS")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent", "BIS")

LoonBestInSlot:AddItem(spec, "30151", "Gloves", "Gloves of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")

LoonBestInSlot:AddItem(spec, "30153", "Legs", "Breeches of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "BIS")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "Alt")
LoonBestInSlot:AddItem(spec, "29977", "Legs", "Star-Soul Breeches", "Alt")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")

LoonBestInSlot:AddItem(spec, "30100", "Feet", "Soul-Strider Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30035", "Feet", "Boots of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt", "Alt")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious", "Alt")

LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "Alt")

LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "29307", "Ring", "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "30665", "Trinket", "Earring of Soulful Meditation", "Alt")

LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "BIS")
LoonBestInSlot:AddItem(spec, "32964", "MH", "Merciless Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "29981", "MH", "Ethereum Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "Alt")

LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "Alt")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")

LoonBestInSlot:AddItem(spec, "30080", "Wand", "Luminescent Rod of the Naaru", "BIS")
LoonBestInSlot:AddItem(spec, "28588", "Wand", "Blue Diamond Witchwand", "Alt")
