local spec = LoonBestInSlot:RegisterSpec("Rogue", "", "2")
LoonBestInSlot:AddItem(spec, "30146", "Head", "Deathmantle Helm", "BIS")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32478", "Head", "Deathblow X11 Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "29044", "Head", "Netherblade Facemask", "Alt")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30149", "Shoulders", "Deathmantle Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")

LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")

LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "BIS")
LoonBestInSlot:AddItem(spec, "30144", "Chest", "Deathmantle Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "29045", "Chest", "Netherblade Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "BIS")
LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "30145", "Gloves", "Deathmantle Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "Alt")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")

LoonBestInSlot:AddItem(spec, "30148", "Legs", "Deathmantle Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt")
LoonBestInSlot:AddItem(spec, "29046", "Legs", "Netherblade Breeches", "Alt")
LoonBestInSlot:AddItem(spec, "29766", "Legs", "Leggings of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "Alt")

LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS")
LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")

LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "30450", "Trinket", "Warp-Spring Coil", "BIS")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "Alt")

LoonBestInSlot:AddItem(spec, "30082", "MH", "Talon of Azshara", "BIS")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike", "Alt")
LoonBestInSlot:AddItem(spec, "32052", "MH", "Merciless Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "Alt")
LoonBestInSlot:AddItem(spec, "28295", "MH", "Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "30103", "MH", "Fang of Vashj", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "29962", "MH", "Heartrazor", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "32027", "OH", "Merciless Gladiator's Quickblade", "BIS")
LoonBestInSlot:AddItem(spec, "28307", "OH", "Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "28189", "OH", "Latro's Shifting Sword", "Alt")
LoonBestInSlot:AddItem(spec, "32046", "OH", "Merciless Gladiator's Shiv", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "29275", "OH", "Searing Sunblade", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "BIS")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket", "Alt")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow", "Alt")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "Alt")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt")
