local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "2")
LoonBestInSlot:AddItem(spec, "30190", "Head", "Cataclysm Helm", "BIS")
LoonBestInSlot:AddItem(spec, "32474", "Head", "Surestrike Goggles v2.0", "Alt")
LoonBestInSlot:AddItem(spec, "29040", "Head", "Cyclone Helm", "Alt")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt")
LoonBestInSlot:AddItem(spec, "28732", "Head", "Cowl of Defiance", "Alt")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "29043", "Shoulders", "Cyclone Shoulderplates", "Alt")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")

LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "30185", "Chest", "Cataclysm Chestplate", "BIS")
LoonBestInSlot:AddItem(spec, "29038", "Chest", "Cyclone Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "Alt")

LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands", "BIS")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "Alt")
LoonBestInSlot:AddItem(spec, "28514", "Bracers", "Bracers of Maliciousness", "Alt")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "30189", "Gloves", "Cataclysm Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "28776", "Gloves", "Liar's Tongue Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "29503", "Gloves", "Cobrascale Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")

LoonBestInSlot:AddItem(spec, "30192", "Legs", "Cataclysm Legplates", "BIS")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness", "BIS")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "Alt")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust", "Alt")

LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "BIS")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker", "Alt")
LoonBestInSlot:AddItem(spec, "27546", "Neck", "Traitor's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "BIS")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29298", "Ring", "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")

LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King", "BIS (All)")
LoonBestInSlot:AddItem(spec, "28433", "MH", "Wicked Edge of the Planes", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "31965", "MH", "Merciless Gladiator's Cleaver", "BIS (All)")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane", "BIS (All)")
LoonBestInSlot:AddItem(spec, "28308", "MH", "Gladiator's Cleaver", "BIS (All)")
LoonBestInSlot:AddItem(spec, "28767", "MH", "The Decapitator", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "27872", "MH", "The Harvester of Souls", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "28944", "MH", "Grand Marshal's Cleaver", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "28920", "MH", "High Warlord's Cleaver", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "28657", "MH", "Fool's Bane", "Alt")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "28432", "MH", "Black Planar Edge", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "28392", "MH", "Reflex Blades", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "31139", "MH", "Fist of Reckoning", "Alt (OH)")

LoonBestInSlot:AddItem(spec, "27815", "Totem", "Totem of the Astral Winds", "BIS")
