local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto", "2")
LoonBestInSlot:AddItem(spec, "30166", "Head", "Cataclysm Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "32475", "Head", "Living Replicator Specs", "BIS")
LoonBestInSlot:AddItem(spec, "29028", "Head", "Cyclone Headdress", "Alt")
LoonBestInSlot:AddItem(spec, "30728", "Head", "Fathom-Helm of the Deeps", "Alt")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "Alt")
LoonBestInSlot:AddItem(spec, "29508", "Head", "Living Dragonscale Helm", "Alt")

LoonBestInSlot:AddItem(spec, "30168", "Shoulders", "Cataclysm Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "30097", "Shoulders", "Coral-Barbed Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "29031", "Shoulders", "Cyclone Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "28631", "Shoulders", "Dragon-Quake Shoulderguards", "Alt")

LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape", "Alt")

LoonBestInSlot:AddItem(spec, "30164", "Chest", "Cataclysm Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "29921", "Chest", "Fire Crest Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29029", "Chest", "Cyclone Hauberk", "Alt")

LoonBestInSlot:AddItem(spec, "30047", "Bracers", "Blackfathom Warbands", "BIS")
LoonBestInSlot:AddItem(spec, "32516", "Bracers", "Wraps of Purification", "Alt")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "28503", "Bracers", "Whirlwind Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "29976", "Gloves", "Worldstorm Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "30165", "Gloves", "Cataclysm Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28520", "Gloves", "Gloves of Centering", "Alt")
LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "Alt")
LoonBestInSlot:AddItem(spec, "29032", "Gloves", "Cyclone Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30030", "Belt", "Girdle of Fallen Stars", "BIS")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "Alt")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28567", "Belt", "Belt of Gale Force", "Alt")

LoonBestInSlot:AddItem(spec, "29991", "Legs", "Sunhawk Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30167", "Legs", "Cataclysm Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "28751", "Legs", "Heart-Flame Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30066", "Feet", "Tempest-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "27525", "Feet", "Jeweled Boots of Sanctification", "Alt")

LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "Alt")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "Alt")

LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth", "BIS")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "BIS")
LoonBestInSlot:AddItem(spec, "29307", "Ring", "Band of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "Alt")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "Alt")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband", "Alt")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring", "Alt")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "BIS")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "BIS")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "BIS")
LoonBestInSlot:AddItem(spec, "21625", "Trinket", "Scarab Brooch", "Alt")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler", "Alt")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "Alt")

LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "BIS")
LoonBestInSlot:AddItem(spec, "32964", "MH", "Merciless Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "Alt")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "Alt")

LoonBestInSlot:AddItem(spec, "29458", "OH", "Aegis of the Vindicator", "BIS")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire", "Alt")
LoonBestInSlot:AddItem(spec, "28754", "OH", "Triptych Shield of the Ancients", "Alt")
LoonBestInSlot:AddItem(spec, "22819", "OH", "Shield of Condemnation", "Alt")

LoonBestInSlot:AddItem(spec, "28523", "Totem", "Totem of Healing Rains", "BIS")
LoonBestInSlot:AddItem(spec, "27544", "Totem", "Totem of Spontaneous Regrowth", "Alt")
LoonBestInSlot:AddItem(spec, "22396", "Totem", "Totem of Life", "Alt")
LoonBestInSlot:AddItem(spec, "25645", "Totem", "Totem of the Plains", "Alt")
