local spec = LoonBestInSlot:RegisterSpec("Warlock", "Destro", "2")
LoonBestInSlot:AddItem(spec, "32494", "Head", "Destruction Holo-gogs", "BIS")
LoonBestInSlot:AddItem(spec, "30212", "Head", "Hood of the Corruptor", "BIS")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28963", "Head", "Voidheart Crown", "Alt")
LoonBestInSlot:AddItem(spec, "29759", "Head", "Helm of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer", "Alt")

LoonBestInSlot:AddItem(spec, "28967", "Shoulders", "Voidheart Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "29762", "Shoulders", "Pauldrons of the Fallen Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30215", "Shoulders", "Mantle of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings", "Alt")
LoonBestInSlot:AddItem(spec, "30079", "Shoulders", "Illidari Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt")

LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "BIS")
LoonBestInSlot:AddItem(spec, "30214", "Chest", "Robe of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes", "Alt")
LoonBestInSlot:AddItem(spec, "28964", "Chest", "Voidheart Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29755", "Chest", "Chestguard of the Fallen Hero", "Alt")

LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands", "BIS")
LoonBestInSlot:AddItem(spec, "32820", "Bracers", "Veteran's Silk Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "Alt")

LoonBestInSlot:AddItem(spec, "28968", "Gloves", "Voidheart Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "29756", "Gloves", "Gloves of the Fallen Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "30211", "Gloves", "Gloves of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "Alt")
LoonBestInSlot:AddItem(spec, "30020", "Belt", "Fire-Cord of the Magus", "Alt")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "Alt")

LoonBestInSlot:AddItem(spec, "30213", "Legs", "Leggings of the Corruptor", "BIS")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "BIS")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer", "Alt")

LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30050", "Feet", "Boots of the Shifting Nightmare", "Alt")
LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night", "Buff")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "Alt")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "Alt")
LoonBestInSlot:AddItem(spec, "33067", "Neck", "Veteran's Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "30008", "Neck", "Pendant of the Lost Ages", "Alt")

LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "BIS")
LoonBestInSlot:AddItem(spec, "29302", "Ring", "Band of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "BIS")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar", "Alt")

LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt")

LoonBestInSlot:AddItem(spec, "22630", "2H", "Atiesh, Greatstaff of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "32055", "2H", "Merciless Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key", "Alt")

LoonBestInSlot:AddItem(spec, "32053", "MH", "Merciless Gladiator's Spellblade", "BIS")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan", "BIS")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "BIS")

LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone", "BIS")
LoonBestInSlot:AddItem(spec, "29270", "OH", "Flametongue Seal", "BIS")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack", "Alt")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration", "Alt")
LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy", "Alt")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk", "Alt")
