local spec = LoonBestInSlot:RegisterSpec("Warlock", "Afflic", "2")
LoonBestInSlot:AddItem(spec, "32494", L["Head"], "Destruction Holo-gogs", "BIS")
LoonBestInSlot:AddItem(spec, "30212", L["Head"], "Hood of the Corruptor", "BIS")
LoonBestInSlot:AddItem(spec, "30244", L["Head"], "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "28963", L["Head"], "Voidheart Crown", "Alt")
LoonBestInSlot:AddItem(spec, "29759", L["Head"], "Helm of the Fallen Hero", "Alt")
LoonBestInSlot:AddItem(spec, "29986", L["Head"], "Cowl of the Grand Engineer", "Alt")

LoonBestInSlot:AddItem(spec, "28967", L["Shoulders"], "Voidheart Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "29762", L["Shoulders"], "Pauldrons of the Fallen Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30215", L["Shoulders"], "Mantle of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30250", L["Shoulders"], "Pauldrons of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30079", L["Shoulders"], "Illidari Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30024", L["Shoulders"], "Mantle of the Elven Kings", "Alt")

LoonBestInSlot:AddItem(spec, "28766", L["Back"], "Ruby Drape of the Mysticant", "BIS")
LoonBestInSlot:AddItem(spec, "30735", L["Back"], "Ancient Spellcloak of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "29992", L["Back"], "Royal Cloak of the Sunstriders", "Alt")

LoonBestInSlot:AddItem(spec, "30107", L["Chest"], "Vestments of the Sea-Witch", "BIS")
LoonBestInSlot:AddItem(spec, "30214", L["Chest"], "Robe of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30238", L["Chest"], "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30056", L["Chest"], "Robe of Hateful Echoes", "Alt")
LoonBestInSlot:AddItem(spec, "28964", L["Chest"], "Voidheart Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29755", L["Chest"], "Chestguard of the Fallen Hero", "Alt")

LoonBestInSlot:AddItem(spec, "29918", L["Bracers"], "Mindstorm Wristbands", "BIS")
LoonBestInSlot:AddItem(spec, "32820", L["Bracers"], "Veteran's Silk Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "24250", L["Bracers"], "Bracers of Havok", "Alt")

LoonBestInSlot:AddItem(spec, "28968", L["Gloves"], "Voidheart Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "29756", L["Gloves"], "Gloves of the Fallen Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30725", L["Gloves"], "Anger-Spark Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "29987", L["Gloves"], "Gauntlets of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "30211", L["Gloves"], "Gloves of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30241", L["Gloves"], "Gloves of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30038", L["Belt"], "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30064", L["Belt"], "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "24256", L["Belt"], "Girdle of Ruination", "Alt")

LoonBestInSlot:AddItem(spec, "30213", L["Legs"], "Leggings of the Corruptor", "BIS")
LoonBestInSlot:AddItem(spec, "30247", L["Legs"], "Leggings of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30734", L["Legs"], "Leggings of the Seventh Circle", "BIS")
LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "29972", L["Legs"], "Trousers of the Astromancer", "Alt")

LoonBestInSlot:AddItem(spec, "30037", L["Feet"], "Boots of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30050", L["Feet"], "Boots of the Shifting Nightmare", "Alt")
LoonBestInSlot:AddItem(spec, "21870", L["Feet"], "Frozen Shadoweave Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30067", L["Feet"], "Velvet Boots of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "24116", L["Neck"], "Eye of the Night", "Alt")
LoonBestInSlot:AddItem(spec, "30015", L["Neck"], "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "24121", L["Neck"], "Chain of the Twilight Owl", "Alt")
LoonBestInSlot:AddItem(spec, "33067", L["Neck"], "Veteran's Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "28530", L["Neck"], "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "30008", L["Neck"], "Pendant of the Lost Ages", "Alt")

LoonBestInSlot:AddItem(spec, "30109", L["Ring"], "Ring of Endless Coils", "BIS")
LoonBestInSlot:AddItem(spec, "29302", L["Ring"], "Band of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "28753", L["Ring"], "Ring of Recurrence", "BIS")
LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "BIS")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "BIS")
LoonBestInSlot:AddItem(spec, "21709", L["Ring"], "Ring of the Fallen God", "BIS")
LoonBestInSlot:AddItem(spec, "29172", L["Ring"], "Ashyen's Gift", "BIS")
LoonBestInSlot:AddItem(spec, "29287", L["Ring"], "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29922", L["Ring"], "Band of Al'ar", "Alt")

LoonBestInSlot:AddItem(spec, "27683", L["Trinket"], "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", L["Trinket"], "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "30626", L["Trinket"], "Sextant of Unstable Currents", "Alt")

LoonBestInSlot:AddItem(spec, "22630", L["2H"], "Atiesh, Greatstaff of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "32055", L["2H"], "Merciless Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "29988", L["2H"], "The Nexus Key", "Alt")

LoonBestInSlot:AddItem(spec, "32053", L["MH"], "Merciless Gladiator's Spellblade", "BIS")
LoonBestInSlot:AddItem(spec, "30095", L["MH"], "Fang of the Leviathan", "BIS")
LoonBestInSlot:AddItem(spec, "30723", L["MH"], "Talon of the Tempest", "BIS")

LoonBestInSlot:AddItem(spec, "30049", L["OH"], "Fathomstone", "BIS")
LoonBestInSlot:AddItem(spec, "29273", L["OH"], "Khadgar's Knapsack", "Alt")

LoonBestInSlot:AddItem(spec, "29982", L["Wand"], "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "28673", L["Wand"], "Tirisfal Wand of Ascendancy", "Alt")
