local spec = LoonBestInSlot:RegisterSpec("Warrior", "Fury", "2")
LoonBestInSlot:AddItem(spec, "30120", "Head", "Destroyer Battle-Helm", "BIS")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "29021", "Head", "Warbringer Battle-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "Alt")
LoonBestInSlot:AddItem(spec, "29983", "Head", "Fel-Steel Warhelm", "Alt")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "30122", "Shoulders", "Destroyer Shoulderblades", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30053", "Shoulders", "Pauldrons of the Wardancer", "Alt")
LoonBestInSlot:AddItem(spec, "30740", "Shoulders", "Ripfiend Shoulderplates", "BIS")
LoonBestInSlot:AddItem(spec, "29023", "Shoulders", "Warbringer Shoulderplates", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "33173", "Shoulders", "Ragesteel Shoulders", "BIS")

LoonBestInSlot:AddItem(spec, "30729", "Back", "Black-Iron Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "Alt")

LoonBestInSlot:AddItem(spec, "30118", "Chest", "Destroyer Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "BIS")
LoonBestInSlot:AddItem(spec, "30102", "Chest", "Krakken-Heart Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "29019", "Chest", "Warbringer Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication", "BIS")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "BIS")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands", "Alt")

LoonBestInSlot:AddItem(spec, "28824", "Gloves", "Gauntlets of Martial Perfection", "BIS")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "28776", "Gloves", "Liar's Tongue Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30119", "Gloves", "Destroyer Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30032", "Belt", "Red Belt of Battle", "Alt")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "Alt")

LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder", "Alt")
LoonBestInSlot:AddItem(spec, "30121", "Legs", "Destroyer Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration", "BIS")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "Alt")

LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "BIS")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "30059", "Neck", "Choker of Animalistic Fury", "Alt")
LoonBestInSlot:AddItem(spec, "29349", "Neck", "Adamantine Chain of the Unbroken", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")

LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")

LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike", "BIS")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "BIS")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "30082", "MH", "Talon of Azshara", "Alt")
LoonBestInSlot:AddItem(spec, "32052", "MH", "Merciless Gladiator's Slicer", "Alt")

LoonBestInSlot:AddItem(spec, "29924", "OH", "Netherbane", "Orc Alt")

LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "30279", "Ranged", "Mama's Insurance", "BIS")
