local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "2")
LoonBestInSlot:AddItem(spec, "32473", L["Head"], "Tankatronic Goggles", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30488", L["Head"], "Merciless Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30115", L["Head"], "Destroyer Greathelm", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30120", L["Head"], "Destroyer Battle-Helm", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30117", L["Shoulders"], "Destroyer Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "30122", L["Shoulders"], "Destroyer Shoulderblades", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30490", L["Shoulders"], "Merciless Gladiator's Plate Shoulders", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28529", L["Back"], "Royal Cloak of Arathi Kings", "BIS")
LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "Alt")
LoonBestInSlot:AddItem(spec, "30098", L["Back"], "Razor-Scale Battlecloak", "Alt")
LoonBestInSlot:AddItem(spec, "28777", L["Back"], "Cloak of the Pit Stalker", "Alt")
LoonBestInSlot:AddItem(spec, "29925", L["Back"], "Phoenix-Wing Cloak", "BIS Mit")

LoonBestInSlot:AddItem(spec, "30113", L["Chest"], "Destroyer Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "28485", L["Chest"], "Bulwark of the Ancient Kings", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30486", L["Chest"], "Merciless Gladiator's Plate Chestpiece", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32818", L["Bracers"], "Veteran's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28996", L["Bracers"], "Marshal's Plate Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30057", L["Bracers"], "Bracers of Eradication", "Alt")
LoonBestInSlot:AddItem(spec, "28502", L["Bracers"], "Vambraces of Courage", "Alt")
LoonBestInSlot:AddItem(spec, "28795", L["Bracers"], "Bladespire Warbands", "Alt")

LoonBestInSlot:AddItem(spec, "30114", L["Gloves"], "Destroyer Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29998", L["Gloves"], "Royal Gauntlets of Silvermoon", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30644", L["Gloves"], "Grips of Deftness", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30096", L["Belt"], "Girdle of the Invulnerable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32805", L["Belt"], "Veteran's Plate Belt", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30032", L["Belt"], "Red Belt of Battle", "Alt")

LoonBestInSlot:AddItem(spec, "30116", L["Legs"], "Destroyer Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "29950", L["Legs"], "Greaves of the Bloodwarder", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30489", L["Legs"], "Merciless Gladiator's Plate Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "30121", L["Legs"], "Destroyer Greaves", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32793", L["Feet"], "Veteran's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "32267", L["Feet"], "Boots of the Resilient", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28608", L["Feet"], "Ironstriders of Urgency", "Alt")

LoonBestInSlot:AddItem(spec, "30099", L["Neck"], "Frayed Tether of the Drowned", "BIS")
LoonBestInSlot:AddItem(spec, "33066", L["Neck"], "Veteran's Pendant of Triumph", "Alt")
LoonBestInSlot:AddItem(spec, "28674", L["Neck"], "Saberclaw Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "29294", L["Ring"], "Band of Eternity", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29298", L["Ring"], "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "30061", L["Ring"], "Ancestral Ring of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "30083", L["Ring"], "Ring of Sundered Souls", "Alt Mit")

LoonBestInSlot:AddItem(spec, "23836", L["Trinket"], "Goblin Rocket Launcher", "BIS Stam")
LoonBestInSlot:AddItem(spec, "23835", L["Trinket"], "Gnomish Poultryizer", "BIS Stam")
LoonBestInSlot:AddItem(spec, "30620", L["Trinket"], "Spyglass of the Hidden Fleet", "Alt Stam")
LoonBestInSlot:AddItem(spec, "28121", L["Trinket"], "Icon of Unyielding Courage", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30058", L["MH"], "Mallet of the Tides", "BIS")
LoonBestInSlot:AddItem(spec, "30103", L["MH"], "Fang of Vashj", "Alt")
LoonBestInSlot:AddItem(spec, "28427", L["MH"], "Blazefury", "Alt")
LoonBestInSlot:AddItem(spec, "29165", L["MH"], "Warbringer", "Alt")
LoonBestInSlot:AddItem(spec, "28749", L["MH"], "King's Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29362", L["MH"], "The Sun Eater", "BIS Mit")

LoonBestInSlot:AddItem(spec, "28825", L["Shield"], "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32045", L["Shield"], "Merciless Gladiator's Shield Wall", "Alt")

LoonBestInSlot:AddItem(spec, "32756", L["Ranged"], "Gyro-Balanced Khorium Destroyer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29949", L["Ranged"], "Arcanite Steam-Pistol", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30724", L["Ranged"], "Barrel-Blade Longrifle", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32054", L["Ranged"], "Merciless Gladiator's War Edge", "Alt")
LoonBestInSlot:AddItem(spec, "30025", L["Ranged"], "Serpentshrine Shuriken", "Alt")
LoonBestInSlot:AddItem(spec, "32645", L["Ranged"], "Crystalline Crossbow", "Alt")
