local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "2")
LoonBestInSlot:AddItem(spec, "32473", "Head", "Tankatronic Goggles", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30488", "Head", "Merciless Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30115", "Head", "Destroyer Greathelm", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30120", "Head", "Destroyer Battle-Helm", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30117", "Shoulders", "Destroyer Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "30122", "Shoulders", "Destroyer Shoulderblades", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30490", "Shoulders", "Merciless Gladiator's Plate Shoulders", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings", "BIS")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Hit Alt")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "No Hit (Contested)")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "No Hit Alt")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker", "No Hit Alt")
LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak", "BIS Mit")

LoonBestInSlot:AddItem(spec, "30113", "Chest", "Destroyer Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "28485", "Chest", "Bulwark of the Ancient Kings", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30486", "Chest", "Merciless Gladiator's Plate Chestpiece", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32818", "Bracers", "Veteran's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28996", "Bracers", "Marshal's Plate Bracers", "Second best")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage", "No Alt option")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "No def option")

LoonBestInSlot:AddItem(spec, "30114", "Gloves", "Destroyer Handguards", "T5 4pc bonus")
LoonBestInSlot:AddItem(spec, "29998", "Gloves", "Royal Gauntlets of Silvermoon", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30096", "Belt", "Girdle of the Invulnerable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32805", "Belt", "Veteran's Plate Belt", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30032", "Belt", "Red Belt of Battle", "No def Alt")

LoonBestInSlot:AddItem(spec, "30116", "Legs", "Destroyer Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30489", "Legs", "Merciless Gladiator's Plate Legguards", "Arena Alt")
LoonBestInSlot:AddItem(spec, "30121", "Legs", "Destroyer Greaves", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32793", "Feet", "Veteran's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "32267", "Feet", "Boots of the Resilient", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "No def Alt")

LoonBestInSlot:AddItem(spec, "30099", "Neck", "Frayed Tether of the Drowned", "BIS")
LoonBestInSlot:AddItem(spec, "33066", "Neck", "Veteran's Pendant of Triumph", "No hit Alt")
LoonBestInSlot:AddItem(spec, "35511", "Neck", "Hailstone Pendant", "Hit Alt")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman", "No hit Alt")

LoonBestInSlot:AddItem(spec, "29294", "Ring", "Band of Eternity", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Hit Alt")
LoonBestInSlot:AddItem(spec, "29298", "Ring", "Band of Eternity", "No hit Alt")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "No hit Alt")

LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "45 Stamina")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "45 Stamina")
LoonBestInSlot:AddItem(spec, "30620", "Trinket", "Spyglass of the Hidden Fleet", "40 Stamina")
LoonBestInSlot:AddItem(spec, "27770", "Trinket", "Argussian Compass", "36 Stamina")
LoonBestInSlot:AddItem(spec, "31113", "Trinket", "Violet Badge", "36 Stamina")
LoonBestInSlot:AddItem(spec, "29181", "Trinket", "Timelapse Shard", "27 Stamina - 24 resilience")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "Snap Thrt")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial", "Steady Thrt")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600", "Alt")

LoonBestInSlot:AddItem(spec, "30058", "MH", "Mallet of the Tides", "BIS")
LoonBestInSlot:AddItem(spec, "30103", "MH", "Fang of Vashj", "Close Second")
LoonBestInSlot:AddItem(spec, "28427", "MH", "Blazefury", "Human Second")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer", "Orc Third")
LoonBestInSlot:AddItem(spec, "28749", "MH", "King's Defender", "Phase 1 BIS")
LoonBestInSlot:AddItem(spec, "29362", "MH", "The Sun Eater", "BIS Mit")

LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32045", "Shield", "Merciless Gladiator's Shield Wall", "Season 2 Alt")
LoonBestInSlot:AddItem(spec, "28358", "Shield", "Gladiator's Shield Wall", "Season 1 Alt")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness", "Waiting for Aldori...")

LoonBestInSlot:AddItem(spec, "32756", "Ranged", "Gyro-Balanced Khorium Destroyer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32054", "Ranged", "Merciless Gladiator's War Edge", "Resilience and Crit")
LoonBestInSlot:AddItem(spec, "30025", "Ranged", "Serpentshrine Shuriken", "Hit and Crit")
LoonBestInSlot:AddItem(spec, "32645", "Ranged", "Crystalline Crossbow", "Hit Alt")
LoonBestInSlot:AddItem(spec, "28826", "Ranged", "Shuriken of Negation", "AP and Stam")
