local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "0")
LoonBestInSlot:AddItem(spec, "32479", "Head", "Wonderheal XT40 Shades", "BIS")
LoonBestInSlot:AddItem(spec, "31988", "Head", "Merciless Gladiator's Kodohide Helm", "Alt")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "Alt")
LoonBestInSlot:AddItem(spec, "31376", "Head", "Gladiator's Kodohide Helm", "Alt")
LoonBestInSlot:AddItem(spec, "32090", "Head", "Cowl of Naaru Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown", "Alt")
LoonBestInSlot:AddItem(spec, "28348", "Head", "Moonglade Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "29174", "Head", "Watcher's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "29505", "Head", "Hood of Primal Life", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "31990", "Shoulders", "Merciless Gladiator's Kodohide Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "31378", "Shoulders", "Gladiator's Kodohide Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance", "Alt")
LoonBestInSlot:AddItem(spec, "27737", "Shoulders", "Moonglade Shoulders", "Alt")

LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "22960", "Back", "Cloak of Suturing", "BIS")
LoonBestInSlot:AddItem(spec, "27946", "Back", "Avian Cloak of Feathers", "BIS")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "Alt")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Bishop's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape", "Alt")

LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "31991", "Chest", "Merciless Gladiator's Kodohide Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "31379", "Chest", "Gladiator's Kodohide Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments", "Alt")
LoonBestInSlot:AddItem(spec, "28202", "Chest", "Moonglade Robe", "Alt")
LoonBestInSlot:AddItem(spec, "27456", "Chest", "Raiments of Nature's Breath", "Alt")
LoonBestInSlot:AddItem(spec, "27506", "Chest", "Robe of Effervescent Light", "Alt")

LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent", "Alt")
LoonBestInSlot:AddItem(spec, "21604", "Bracers", "Bracelets of Royal Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "27827", "Bracers", "Lucid Dream Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "22495", "Bracers", "Dreamwalker Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "BIS")
LoonBestInSlot:AddItem(spec, "31987", "Gloves", "Merciless Gladiator's Kodohide Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31375", "Gloves", "Gladiator's Kodohide Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "24393", "Gloves", "Bloody Surgeon's Mitts", "Alt")
LoonBestInSlot:AddItem(spec, "25791", "Gloves", "Gloves of Preservation", "Alt")
LoonBestInSlot:AddItem(spec, "28268", "Gloves", "Natural Mender's Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "29327", "Gloves", "Cryo-mitts", "Alt")

LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "Alt")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification", "Alt")
LoonBestInSlot:AddItem(spec, "31594", "Belt", "General's Kodohide Belt", "Alt")
LoonBestInSlot:AddItem(spec, "27542", "Belt", "Cord of Belief", "Alt")
LoonBestInSlot:AddItem(spec, "28398", "Belt", "The Sleeper's Cord", "Alt")

LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "BIS")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "BIS")
LoonBestInSlot:AddItem(spec, "31335", "Legs", "Pants of Living Growth", "Alt")
LoonBestInSlot:AddItem(spec, "28218", "Legs", "Pontiff's Pantaloons of Prophecy", "Alt")
LoonBestInSlot:AddItem(spec, "31989", "Legs", "Merciless Gladiator's Kodohide Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "31377", "Legs", "Gladiator's Kodohide Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "29345", "Legs", "Haramad's Leg Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers", "Alt")
LoonBestInSlot:AddItem(spec, "27875", "Legs", "Hallowed Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "30035", "Feet", "Boots of the Long Road", "BIS")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity", "Alt")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious", "Alt")
LoonBestInSlot:AddItem(spec, "25792", "Feet", "Curate's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "31595", "Feet", "General's Kodohide Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28251", "Feet", "Boots of the Glade-Keeper", "Alt")
LoonBestInSlot:AddItem(spec, "27525", "Feet", "Jeweled Boots of Sanctification", "Alt")

LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion", "BIS")
LoonBestInSlot:AddItem(spec, "33068", "Neck", "Veteran's Pendant of Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "Alt")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope", "Alt")
LoonBestInSlot:AddItem(spec, "23036", "Neck", "Necklace of Necropsy", "Alt")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope", "Alt")
LoonBestInSlot:AddItem(spec, "21712", "Neck", "Amulet of the Fallen God", "Alt")

LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "BIS")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "BIS")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "BIS")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "BIS")
LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos", "Alt")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void", "Alt")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29322", "Ring", "Keeper's Ring of Piety", "Alt")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "Alt")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "Alt")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "Alt")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler", "Alt")

LoonBestInSlot:AddItem(spec, "32964", "MH", "Merciless Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "BIS")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "Alt")
LoonBestInSlot:AddItem(spec, "28257", "MH", "Hammer of the Penitent", "Alt")
LoonBestInSlot:AddItem(spec, "28216", "MH", "Dathrohan's Ceremonial Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "27538", "MH", "Lightsworn Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "31304", "MH", "The Essence Focuser", "Alt")

LoonBestInSlot:AddItem(spec, "22632", "2H", "Atiesh, Greatstaff of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "27791", "2H", "Serpentcrest Life-Staff", "BIS")
LoonBestInSlot:AddItem(spec, "29133", "2H", "Seer's Cane", "Alt")
LoonBestInSlot:AddItem(spec, "28033", "2H", "Epoch-Mender", "Alt")
LoonBestInSlot:AddItem(spec, "31289", "2H", "Staff of Divine Infusion", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "32961", "OH", "Merciless Gladiator's Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "23048", "OH", "Sapphiron's Right Eye", "Alt")
LoonBestInSlot:AddItem(spec, "23029", "OH", "Noth's Frigid Heart", "Alt")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing", "Alt")
LoonBestInSlot:AddItem(spec, "27714", "OH", "Swamplight Lantern", "Alt")
LoonBestInSlot:AddItem(spec, "28213", "OH", "Lordaeron Medical Guide", "Alt")
LoonBestInSlot:AddItem(spec, "31493", "OH", "Netherwing Spiritualist's Charm", "Alt")
LoonBestInSlot:AddItem(spec, "28387", "OH", "Lamp of Peaceful Repose", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "Alt")
LoonBestInSlot:AddItem(spec, "25643", "Idol", "Harold's Rejuvenating Broach", "Alt")
