local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "0")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")
LoonBestInSlot:AddItem(spec, "27776", "Shoulders", "Shoulderpads of Assassination", "Alt")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "27995", "Shoulders", "Sun-Gilded Shouldercaps", "Alt")

LoonBestInSlot:AddItem(spec, "31255", "Back", "Cloak of the Craft", "BIS")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28031", "Back", "Nomad's Woven Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28032", "Back", "Delicate Green Poncho", "Alt")

LoonBestInSlot:AddItem(spec, "28204", "Chest", "Tunic of Assassination", "BIS")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "BIS")
LoonBestInSlot:AddItem(spec, "24396", "Chest", "Vest of Vengeance", "Alt")
LoonBestInSlot:AddItem(spec, "31972", "Chest", "Merciless Gladiator's Dragonhide Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "28264", "Chest", "Wastewalker Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "29340", "Chest", "Auchenai Monk's Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "32814", "Bracers", "Veteran's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32810", "Bracers", "Veteran's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "28396", "Gloves", "Gloves of the Unbound", "BIS")
LoonBestInSlot:AddItem(spec, "29507", "Gloves", "Windslayer Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "27509", "Gloves", "Handgrips of Assassination", "Alt")
LoonBestInSlot:AddItem(spec, "27531", "Gloves", "Wastewalker Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30372", "Belt", "Socrethar's Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "31464", "Belt", "Naaru Belt of Precision", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "BIS")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Alt")
LoonBestInSlot:AddItem(spec, "27911", "Belt", "Epoch's Whispering Cinch", "Alt")

LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "27908", "Legs", "Leggings of Assassination", "Alt")
LoonBestInSlot:AddItem(spec, "30535", "Legs", "Forestwalker Kilt", "Alt")

LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "31288", "Feet", "The Master's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "32790", "Feet", "Veteran's Leather Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30939", "Feet", "Felboar Hide Shoes", "Alt")

LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "Alt")
LoonBestInSlot:AddItem(spec, "27779", "Neck", "Bone Chain Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "19377", "Neck", "Prestor's Talisman of Connivery", "Alt")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing", "Alt")

LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "BIS")
LoonBestInSlot:AddItem(spec, "32654", "Trinket", "Crystalforged Trinket", "Alt")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "Alt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos", "Alt")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")

LoonBestInSlot:AddItem(spec, "31334", "2H", "Staff of Natural Fury", "Alt")
LoonBestInSlot:AddItem(spec, "32014", "2H", "Merciless Gladiator's Maul", "BIS")
LoonBestInSlot:AddItem(spec, "28476", "2H", "Gladiator's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "29359", "2H", "Feral Staff of Lashing", "Alt")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden", "Alt")
LoonBestInSlot:AddItem(spec, "27877", "2H", "Draenic Wildstaff", "Alt")
LoonBestInSlot:AddItem(spec, "28325", "2H", "Dreamer's Dragonstaff", "Alt")
LoonBestInSlot:AddItem(spec, "30010", "2H", "Fleshling Simulation Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28948", "2H", "Grand Marshal's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "28919", "2H", "High Warlord's Maul", "Alt")

LoonBestInSlot:AddItem(spec, "28372", "Idol", "Idol of Feral Shadows", "BIS")
LoonBestInSlot:AddItem(spec, "29390", "Idol", "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild", "Alt")
