local spec = LoonBestInSlot:RegisterSpec("Hunter", "Marks", "0")
LoonBestInSlot:AddItem(spec, "28275", "Head", "Beast Lord Helm", "BIS")
LoonBestInSlot:AddItem(spec, "32474", "Head", "Surestrike Goggles v2.0", "Alt")
LoonBestInSlot:AddItem(spec, "22438", "Head", "Cryptstalker Headpiece", "Alt")
LoonBestInSlot:AddItem(spec, "31109", "Head", "Stealther's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "31106", "Head", "Stalker's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "31281", "Head", "Mask of Veiled Death", "Alt")
LoonBestInSlot:AddItem(spec, "27414", "Head", "Mok'Nathal Beast-Mask", "Alt")

LoonBestInSlot:AddItem(spec, "27801", "Shoulders", "Beast Lord Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "22439", "Shoulders", "Cryptstalker Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "28228", "Chest", "Beast Lord Cuirass", "BIS")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "BIS")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "22436", "Chest", "Cryptstalker Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "25697", "Bracers", "Felstalker Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "22443", "Bracers", "Cryptstalker Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "27474", "Gloves", "Beast Lord Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "16463", "Gloves", "Marshal's Chain Grips", "Alt")
LoonBestInSlot:AddItem(spec, "16571", "Gloves", "General's Chain Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30951", "Gloves", "Ar'tor's Mainstay", "Alt")
LoonBestInSlot:AddItem(spec, "22441", "Gloves", "Cryptstalker Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "30003", "Gloves", "Gloves of the Nether-Stalker", "Alt")

LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "BIS")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Alt")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt")
LoonBestInSlot:AddItem(spec, "25695", "Belt", "Felstalker Belt", "Alt")
LoonBestInSlot:AddItem(spec, "22442", "Belt", "Cryptstalker Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "27874", "Legs", "Beast Lord Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "22437", "Legs", "Cryptstalker Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "31288", "Feet", "The Master's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "22440", "Feet", "Cryptstalker Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "19377", "Neck", "Prestor's Talisman of Connivery", "Alt")
LoonBestInSlot:AddItem(spec, "28343", "Neck", "Jagged Bark Pendant", "Alt")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing", "Alt")

LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "BIS")
LoonBestInSlot:AddItem(spec, "23038", "Ring", "Band of Unnatural Forces", "Alt")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")
LoonBestInSlot:AddItem(spec, "30973", "Ring", "Band of Anguish", "Alt")

LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "Alt")
LoonBestInSlot:AddItem(spec, "28041", "Trinket", "Bladefist's Breadth", "Alt")

LoonBestInSlot:AddItem(spec, "27846", "MH", "Claw of the Watcher", "BIS")
LoonBestInSlot:AddItem(spec, "30277", "MH", "Ripfang Paw", "Alt")
LoonBestInSlot:AddItem(spec, "21673", "MH", "Silithid Claw", "Alt")
LoonBestInSlot:AddItem(spec, "28263", "MH", "Stellaris", "Alt")

LoonBestInSlot:AddItem(spec, "28315", "OH", "Stormreaver Warblades", "BIS")
LoonBestInSlot:AddItem(spec, "29372", "OH", "Void-Talon", "Alt")
LoonBestInSlot:AddItem(spec, "23242", "OH", "Claw of the Frost Wyrm", "Alt")
LoonBestInSlot:AddItem(spec, "29121", "OH", "Guile of Khoraazi", "Alt")

LoonBestInSlot:AddItem(spec, "28435", "2H", "Mooncleaver", "BIS")
LoonBestInSlot:AddItem(spec, "27903", "2H", "Sonic Spear", "Alt")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "23039", "2H", "The Eye of Nerub", "Alt")
LoonBestInSlot:AddItem(spec, "29329", "2H", "Terokk's Quill", "Alt")

LoonBestInSlot:AddItem(spec, "31986", "Ranged", "Merciless Gladiator's Crossbow of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "29351", "Ranged", "Wrathtide Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "22812", "Ranged", "Nerubian Slavemaker", "Alt")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket", "Alt")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow", "Alt")
LoonBestInSlot:AddItem(spec, "31323", "Ranged", "Don Santos' Famous Hunting Rifle", "Alt")
LoonBestInSlot:AddItem(spec, "31303", "Ranged", "Valanos' Longbow", "Alt")
