local spec = LoonBestInSlot:RegisterSpec("Mage", "Frost", "0")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "32494", "Head", "Destruction Holo-gogs", "Alt")
LoonBestInSlot:AddItem(spec, "28169", "Head", "Mag'hari Ritualist's Horns", "Alt")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "28193", "Head", "Mana-Etched Crown", "Alt")
LoonBestInSlot:AddItem(spec, "22498", "Head", "Frostfire Circlet", "Alt")
LoonBestInSlot:AddItem(spec, "19375", "Head", "Mish'undare, Circlet of the Mind Flayer", "Alt")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "30515", "Head", "Junior Technician 3rd Grade Goggles", "Alt")

LoonBestInSlot:AddItem(spec, "21869", "Shoulders", "Frozen Shadoweave Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart", "Alt")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", "Spaulders of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "22983", "Shoulders", "Rime Covered Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "22499", "Shoulders", "Frostfire Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "28075", "Shoulders", "Destroyers' Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30514", "Shoulders", "Nether Guards", "Alt")

LoonBestInSlot:AddItem(spec, "23050", "Back", "Cloak of the Necropolis", "BIS")
LoonBestInSlot:AddItem(spec, "22731", "Back", "Cloak of the Devoured", "Alt")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "31140", "Back", "Cloak of Entropy", "Alt")
LoonBestInSlot:AddItem(spec, "24252", "Back", "Cloak of the Black Void", "Alt")
LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities", "Alt")
LoonBestInSlot:AddItem(spec, "29813", "Back", "Cloak of Woven Energy", "Alt")
LoonBestInSlot:AddItem(spec, "25777", "Back", "Ogre Slayer's Cover", "Alt")

LoonBestInSlot:AddItem(spec, "21871", "Chest", "Frozen Shadoweave Robe", "BIS")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order", "Alt")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28342", "Chest", "Warp Infused Drape", "Alt")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd", "Alt")
LoonBestInSlot:AddItem(spec, "28232", "Chest", "Robe of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "22496", "Chest", "Frostfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29780", "Chest", "Kirin Tor Apprentice's Robes", "Alt")
LoonBestInSlot:AddItem(spec, "31717", "Chest", "Shadowcast Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "32655", "Bracers", "Crystalweave Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "Alt")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom", "Alt")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "27746", "Bracers", "Arcanium Signet Bands", "Alt")
LoonBestInSlot:AddItem(spec, "29240", "Bracers", "Bands of Negation", "Alt")
LoonBestInSlot:AddItem(spec, "23021", "Bracers", "The Soul Harvester's Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "30927", "Bracers", "Earthmender's Bracer of Shattering", "Alt")
LoonBestInSlot:AddItem(spec, "30520", "Bracers", "Gold-Trimmed Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "27493", "Gloves", "Gloves of the Deadwatcher", "BIS")
LoonBestInSlot:AddItem(spec, "21585", "Gloves", "Dark Storm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "27537", "Gloves", "Gloves of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", "Tempest's Touch", "Alt")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30924", "Gloves", "Gloves of the High Magus", "Alt")
LoonBestInSlot:AddItem(spec, "30930", "Gloves", "Grips of the Void", "Alt")

LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "BIS")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity", "Alt")
LoonBestInSlot:AddItem(spec, "22730", "Belt", "Eyestalk Waist Cord", "Alt")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "27795", "Belt", "Sash of Serpentra", "Alt")
LoonBestInSlot:AddItem(spec, "30923", "Belt", "Grom'tor's Bloodied Bandage", "Alt")
LoonBestInSlot:AddItem(spec, "29771", "Belt", "Kirin'Var Journeyman's Belt", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist", "Alt")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration", "Alt")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers", "Alt")
LoonBestInSlot:AddItem(spec, "28338", "Legs", "Devil-Stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "23070", "Legs", "Leggings of Polarity", "Alt")
LoonBestInSlot:AddItem(spec, "30929", "Legs", "Soothsayer's Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "21852", "Legs", "Netherweave Pants", "Alt")

LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots", "BIS")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice", "Alt")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers", "Alt")
LoonBestInSlot:AddItem(spec, "22500", "Feet", "Frostfire Sandals", "Alt")
LoonBestInSlot:AddItem(spec, "29242", "Feet", "Boots of Blasphemy", "Alt")
LoonBestInSlot:AddItem(spec, "30519", "Feet", "Boots of the Nexus Warden", "Alt")
LoonBestInSlot:AddItem(spec, "30398", "Feet", "Boots of the Beneficent", "Alt")

LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "BIS")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace", "BIS")
LoonBestInSlot:AddItem(spec, "31338", "Neck", "Charlotte's Ivy", "BIS")
LoonBestInSlot:AddItem(spec, "18814", "Neck", "Choker of the Fire Lord", "BIS")
LoonBestInSlot:AddItem(spec, "21608", "Neck", "Amulet of Vek'nilash", "Alt")
LoonBestInSlot:AddItem(spec, "29368", "Neck", "Manasurge Pendant", "Alt")
LoonBestInSlot:AddItem(spec, "23057", "Neck", "Gem of Trapped Innocents", "Alt")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31178", "Neck", "Amulet of Unstable Power", "Alt")

LoonBestInSlot:AddItem(spec, "21709", "Ring", "Ring of the Fallen God", "BIS")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "BIS")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "BIS")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist", "BIS")
LoonBestInSlot:AddItem(spec, "31339", "Ring", "Lola's Eve", "BIS")
LoonBestInSlot:AddItem(spec, "23062", "Ring", "Frostfire Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "23025", "Ring", "Seal of the Damned", "Alt")
LoonBestInSlot:AddItem(spec, "23031", "Ring", "Band of the Inevitable", "Alt")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa", "Alt")
LoonBestInSlot:AddItem(spec, "31075", "Ring", "Evoker's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "30366", "Ring", "Manastorm Band", "Alt")
LoonBestInSlot:AddItem(spec, "32774", "Ring", "The Black Pearl", "Alt")

LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "19339", "Trinket", "Mind Quickening Gem", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")
LoonBestInSlot:AddItem(spec, "28418", "Trinket", "Shiffar's Nexus-Horn", "Alt")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "28040", "Trinket", "Vengeance of the Illidari", "Alt")
LoonBestInSlot:AddItem(spec, "25620", "Trinket", "Ancient Crystal Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "25619", "Trinket", "Glowing Crystal Insignia", "Alt")

LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "BIS")
LoonBestInSlot:AddItem(spec, "30787", "MH", "Illidari-Bane Mageblade", "Alt")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "Alt")
LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry", "Alt")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams", "Alt")
LoonBestInSlot:AddItem(spec, "27543", "MH", "Starlight Dagger", "Alt")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "24453", "MH", "Zangartooth Shortblade", "Alt")
LoonBestInSlot:AddItem(spec, "31142", "MH", "Blade of Trapped Knowledge", "Alt")

LoonBestInSlot:AddItem(spec, "22589", "2H", "Atiesh, Greatstaff of the Guardian", "BIS")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff", "Alt")
LoonBestInSlot:AddItem(spec, "29130", "2H", "Auchenai Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28341", "2H", "Warpstaff of Arcanum", "Alt")
LoonBestInSlot:AddItem(spec, "27842", "2H", "Grand Scepter of the Nexus-Kings", "Alt")
LoonBestInSlot:AddItem(spec, "31308", "2H", "The Bringer of Death", "Alt")
LoonBestInSlot:AddItem(spec, "25760", "2H", "Battle Mage's Baton", "Alt")

LoonBestInSlot:AddItem(spec, "29269", "OH", "Sapphiron's Wing Bone", "BIS")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance", "Alt")
LoonBestInSlot:AddItem(spec, "32651", "OH", "Crystal Orb of Enlightenment", "Alt")
LoonBestInSlot:AddItem(spec, "28187", "OH", "Star-Heart Lamp", "Alt")
LoonBestInSlot:AddItem(spec, "28260", "OH", "Manual of the Nethermancer", "Alt")
LoonBestInSlot:AddItem(spec, "27534", "OH", "Hortus' Seal of Brilliance", "Alt")
LoonBestInSlot:AddItem(spec, "31699", "OH", "Imbued Draenethyst Crystal", "Alt")
LoonBestInSlot:AddItem(spec, "31731", "OH", "Mekeda's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "22821", "Wand", "Doomfinger", "BIS")
LoonBestInSlot:AddItem(spec, "28386", "Wand", "Nether Core's Control Rod", "BIS")
LoonBestInSlot:AddItem(spec, "22820", "Wand", "Wand of Fates", "Alt")
LoonBestInSlot:AddItem(spec, "32872", "Wand", "Illidari Rod of Discipline", "Alt")
LoonBestInSlot:AddItem(spec, "25939", "Wand", "Voidfire Wand", "Alt")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk", "Alt")
LoonBestInSlot:AddItem(spec, "27890", "Wand", "Wand of the Netherwing", "Alt")
LoonBestInSlot:AddItem(spec, "31724", "Wand", "Arakkoa Divining Rod", "Alt")
LoonBestInSlot:AddItem(spec, "30523", "Wand", "Hotshot Cattle Prod", "Alt")
