local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot")
LoonBestInSlot:AddItem(spec, "29388", "Head", "Libram of Repentance", "1 - ESSENTIAL")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination", "2 - Survivability")
LoonBestInSlot:AddItem(spec, "29370", "Head", "Icon of the Silver Crescent", "3 - Thrt")
LoonBestInSlot:AddItem(spec, "29266", "Head", "Azure-Shield of Coldarra", "4")
LoonBestInSlot:AddItem(spec, "29387", "Head", "Gnomeregan Auto-Dodger 600", "5")

LoonBestInSlot:AddItem(spec, "32083", "Shoulders", "Faceguard of Determination", "BIS - Survival")
LoonBestInSlot:AddItem(spec, "23536", "Shoulders", "Oathkeeper's Helm", "BIS - Thrt")
LoonBestInSlot:AddItem(spec, "23535", "Shoulders", "Helm of the Stalwart Defender", "Viable - Crit Reduction")
LoonBestInSlot:AddItem(spec, "28285", "Shoulders", "Helm of the Righteous", "Viable")
LoonBestInSlot:AddItem(spec, "28180", "Shoulders", "Myrmidon's Headdress", "Viable - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "23519", "Shoulders", "Felsteel Helm", "Viable")
LoonBestInSlot:AddItem(spec, "27520", "Shoulders", "Greathelm of the Unbreakable", "Viable")
LoonBestInSlot:AddItem(spec, "30016", "Shoulders", "X-52 Technician's Helm", "Viable")

LoonBestInSlot:AddItem(spec, "27739", "Back", "Spaulders of the Righteous", "BIS")
LoonBestInSlot:AddItem(spec, "27847", "Back", "Fanblade Pauldrons", "Viable")
LoonBestInSlot:AddItem(spec, "32073", "Back", "Spaulders of Dementia", "Viable")
LoonBestInSlot:AddItem(spec, "30381", "Back", "Kaylaan's Spaulders", "Viable - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "29316", "Back", "Warchief's Mantle", "Alt - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "24463", "Back", "Pauldrons of Brute Force", "Option")

LoonBestInSlot:AddItem(spec, "27804", "Chest", "Devilshark Cape", "BIS")
LoonBestInSlot:AddItem(spec, "24253", "Chest", "Cloak of Eternity", "Viable")
LoonBestInSlot:AddItem(spec, "29385", "Chest", "Farstrider Defender's Cloak", "Viable")
LoonBestInSlot:AddItem(spec, "27988", "Chest", "Burnoose of Shifting Ages", "Viable")
LoonBestInSlot:AddItem(spec, "24379", "Chest", "Bogstrok Scale Cloak", "Viable")
LoonBestInSlot:AddItem(spec, "29777", "Chest", "Cloak of the Valiant Defender", "Viable - Easy to Obtain")

LoonBestInSlot:AddItem(spec, "28203", "Bracers", "Breastplate of the Righteous", "BIS")
LoonBestInSlot:AddItem(spec, "28262", "Bracers", "Jade-Skull Breastplate", "Viable")
LoonBestInSlot:AddItem(spec, "29127", "Bracers", "Vindicator's Hauberk", "Viable")
LoonBestInSlot:AddItem(spec, "23507", "Bracers", "Adamantite Breastplate", "Option")
LoonBestInSlot:AddItem(spec, "25819", "Bracers", "Breastplate of the Warbringer", "Option")
LoonBestInSlot:AddItem(spec, "30270", "Bracers", "Scavenged Breastplate", "Option")
LoonBestInSlot:AddItem(spec, "30296", "Bracers", "Lost Chestplate of the Reverent", "Alt - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "29337", "Bracers", "The Exarch's Protector", "Option")

LoonBestInSlot:AddItem(spec, "29252", "Gloves", "Bracers of Dignity", "BIS - Overall")
LoonBestInSlot:AddItem(spec, "23538", "Gloves", "Bracers of the Green Fortress", "Viable - High Stamina")
LoonBestInSlot:AddItem(spec, "29463", "Gloves", "Amber Bands of the Aggressor", "BIS - Avoidance")
LoonBestInSlot:AddItem(spec, "28167", "Gloves", "Sha'tari Wrought Armguards", "Viable - High Stamina")
LoonBestInSlot:AddItem(spec, "27459", "Gloves", "Vambraces of Daring", "Viable")
LoonBestInSlot:AddItem(spec, "30400", "Gloves", "Thadell's Bracers", "Viable - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "30225", "Gloves", "Junior Technician 3rd Grade Bracers", "Viable - Easy to Obtain")

LoonBestInSlot:AddItem(spec, "32072", "Belt", "Gauntlets of Dissension", "BIS")
LoonBestInSlot:AddItem(spec, "23532", "Belt", "Gauntlets of the Iron Tower", "Viable")
LoonBestInSlot:AddItem(spec, "27535", "Belt", "Gauntlets of the Righteous", "Viable")
LoonBestInSlot:AddItem(spec, "23517", "Belt", "Felsteel Gloves", "Viable")
LoonBestInSlot:AddItem(spec, "25788", "Belt", "Dauntless Handguards", "Viable")
LoonBestInSlot:AddItem(spec, "28390", "Belt", "Thatia's Self-Correcting Gauntlets", "Viable")
LoonBestInSlot:AddItem(spec, "29134", "Belt", "Gauntlets of the Chosen", "Viable")
LoonBestInSlot:AddItem(spec, "29959", "Belt", "Spiritualist's Gauntlets", "Viable - Easy to Obtain")

LoonBestInSlot:AddItem(spec, "29253", "Legs", "Girdle of Valorous Deeds", "BIS")
LoonBestInSlot:AddItem(spec, "27672", "Legs", "Girdle of the Immovable", "Viable")
LoonBestInSlot:AddItem(spec, "29238", "Legs", "Lion's Heart Girdle", "Viable")
LoonBestInSlot:AddItem(spec, "31460", "Legs", "Sha'tari Vindicator's Waistguard", "Viable - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "30371", "Legs", "Lightwarden's Girdle", "Viable")
LoonBestInSlot:AddItem(spec, "30330", "Legs", "Starcaller's Plated Belt", "Option")
LoonBestInSlot:AddItem(spec, "30380", "Legs", "Girdle of the Lost Vindicator", "Option")

LoonBestInSlot:AddItem(spec, "29184", "Feet", "Timewarden's Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "23518", "Feet", "Felsteel Leggings", "Viable")
LoonBestInSlot:AddItem(spec, "27527", "Feet", "Greaves of the Shatterer", "Viable")
LoonBestInSlot:AddItem(spec, "29783", "Feet", "Legguards of the Resolute Defender", "Viable")
LoonBestInSlot:AddItem(spec, "27839", "Feet", "Legplates of the Righteous", "Viable")
LoonBestInSlot:AddItem(spec, "29774", "Feet", "Kirin'Var Defender's Chausses", "Option")

LoonBestInSlot:AddItem(spec, "29254", "Neck", "Boots of the Righteous Path", "BIS")
LoonBestInSlot:AddItem(spec, "29239", "Neck", "Eaglecrest Warboots", "Viable")
LoonBestInSlot:AddItem(spec, "27813", "Neck", "Boots of the Colossus", "Viable")
LoonBestInSlot:AddItem(spec, "32866", "Neck", "Ascendant's Boots", "Viable")
LoonBestInSlot:AddItem(spec, "29325", "Neck", "Flesh Beast's Metal Greaves", "Viable - Easy to Obtain")
LoonBestInSlot:AddItem(spec, "30334", "Neck", "Starcaller's Plated Stompers", "Viable")
LoonBestInSlot:AddItem(spec, "30386", "Neck", "Bloodguard's Greaves", "Viable")
LoonBestInSlot:AddItem(spec, "28318", "Neck", "Obsidian Clodstompers", "Option")

LoonBestInSlot:AddItem(spec, "29173", "Ring", "Strength of the Untamed", "BIS ")
LoonBestInSlot:AddItem(spec, "27871", "Ring", "Maladaar's Blessed Chaplet", "Viable")
LoonBestInSlot:AddItem(spec, "27792", "Ring", "Steam-Hinge Chain of Valor", "Viable")
LoonBestInSlot:AddItem(spec, "29386", "Ring", "Necklace of the Juggernaut", "Viable")
LoonBestInSlot:AddItem(spec, "30378", "Ring", "Thalodien's Charm", "Viable")
LoonBestInSlot:AddItem(spec, "31696", "Ring", "Natasha's Battle Chain", "Viable")
LoonBestInSlot:AddItem(spec, "27792", "Ring", "Steam-Hinge Chain of Valor", "Viable")
LoonBestInSlot:AddItem(spec, "29336", "Ring", "Mark of the Ravenguard", "Viable")
LoonBestInSlot:AddItem(spec, "28321", "Ring", "Enchanted Thorium Torque", "Viable")
LoonBestInSlot:AddItem(spec, "25809", "Ring", "Maimfist's Choker", "Horde Option")
LoonBestInSlot:AddItem(spec, "25803", "Ring", "Medallion of the Valiant Guardian", "Alliance Option")
LoonBestInSlot:AddItem(spec, "24121", "Ring", "Chain of the Twilight Owl", "Option")

LoonBestInSlot:AddItem(spec, "31319", "Trinket", "Band of Impenetrable Defenses", "BIS")
LoonBestInSlot:AddItem(spec, "28407", "Trinket", "Elementium Band of the Sentry", "BIS")
LoonBestInSlot:AddItem(spec, "30006", "Trinket", "Wind Trader's Band", "Viable")
LoonBestInSlot:AddItem(spec, "27822", "Trinket", "Crystal Band of Valor", "Viable")
LoonBestInSlot:AddItem(spec, "28211", "Trinket", "Lieutenant's Signet of Lordaeron", "Viable")
LoonBestInSlot:AddItem(spec, "29384", "Trinket", "Ring of Unyielding Force", "Viable")
LoonBestInSlot:AddItem(spec, "31078", "Trinket", "Protector's Mark of the Redemption", "Viable")
LoonBestInSlot:AddItem(spec, "27436", "Trinket", "Iron Band of the Unbreakable", "Viable")
LoonBestInSlot:AddItem(spec, "24088", "Trinket", "Delicate Eternium Ring", "Viable")
LoonBestInSlot:AddItem(spec, "31924", "Trinket", "Yor's Revenge", "Viable")
LoonBestInSlot:AddItem(spec, "29323", "Trinket", "Andormu's Tear", "Viable")
LoonBestInSlot:AddItem(spec, "28265", "Trinket", "Dath'Remar's Ring of Defense", "Viable")

LoonBestInSlot:AddItem(spec, "27529", "MH", "Figurine of the Colossus", "BIS - Uncrushability")
LoonBestInSlot:AddItem(spec, "27891", "MH", "Adamantine Figurine", "BIS - Defense + Mit")
LoonBestInSlot:AddItem(spec, "32534", "MH", "Brooch of the Immortal King", "BIS - Defense + HP")
LoonBestInSlot:AddItem(spec, "30300", "MH", "Dabiri's Enigma", "Viable - Defense")
LoonBestInSlot:AddItem(spec, "19431", "MH", "Styleen's Impeding Scarab", "Viable - Defense ")
LoonBestInSlot:AddItem(spec, "24125", "MH", "Figurine - Dawnstone Crab", "Viable - Avoidance UtilityJewelcrafters")
LoonBestInSlot:AddItem(spec, "28042", "MH", "Regal Protectorate", "Viable - Defense + HP")
LoonBestInSlot:AddItem(spec, "23040", "MH", "Glyph of Deflection", "Viable - Mit")
LoonBestInSlot:AddItem(spec, "29387", "MH", "Gnomeregan Auto-Dodger 600", "Viable - Mit")

LoonBestInSlot:AddItem(spec, "31858", "Libram", "Darkmoon Card: Vengeance", "BIS - Stamina")
LoonBestInSlot:AddItem(spec, "31859", "Libram", "Darkmoon Card: Madness", "Viable")
LoonBestInSlot:AddItem(spec, "23836", "Libram", "Goblin Rocket Launcher", "Viable - Pull Utility, Alt to ")
LoonBestInSlot:AddItem(spec, "23835", "Libram", "Gnomish Poultryizer", "Viable - Crowd Control")
LoonBestInSlot:AddItem(spec, "32864", "Libram", "Commander's Badge", "Viable")
LoonBestInSlot:AddItem(spec, "27770", "Libram", "Argussian Compass", "Viable")
LoonBestInSlot:AddItem(spec, "24126", "Libram", "Figurine - Living Ruby Serpent", "Viable - ThrtJewelcrafters")
LoonBestInSlot:AddItem(spec, "13503", "Libram", "Alchemist Stone", "Viable Alchemists")

LoonBestInSlot:AddItem(spec, "29370", "Shield", "Icon of the Silver Crescent", "BIS - Thrt")
LoonBestInSlot:AddItem(spec, "24126", "Shield", "Figurine - Living Ruby Serpent", "ViableJewelcrafters")
LoonBestInSlot:AddItem(spec, "23046", "Shield", "The Restrained Essence of Sapphiron", "Viable")
LoonBestInSlot:AddItem(spec, "19379", "Shield", "Neltharion's Tear", "Viable")
LoonBestInSlot:AddItem(spec, "23207", "Shield", "Mark of the Champion", "Viable - Demons/Undead Only")
LoonBestInSlot:AddItem(spec, "18820", "Shield", "Talisman of Ephemeral Power", "Viable (Thrt)")
LoonBestInSlot:AddItem(spec, "19950", "Shield", "Zandalarian Hero Charm", "Viable")
