local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "0")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination", "BIS Mit")
LoonBestInSlot:AddItem(spec, "23536", "Head", "Oathkeeper's Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23535", "Head", "Helm of the Stalwart Defender", "Alt")
LoonBestInSlot:AddItem(spec, "28285", "Head", "Helm of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "28180", "Head", "Myrmidon's Headdress", "Alt")
LoonBestInSlot:AddItem(spec, "23519", "Head", "Felsteel Helm", "Alt")
LoonBestInSlot:AddItem(spec, "27520", "Head", "Greathelm of the Unbreakable", "Alt")
LoonBestInSlot:AddItem(spec, "30016", "Head", "X-52 Technician's Helm", "Alt")

LoonBestInSlot:AddItem(spec, "27739", "Shoulders", "Spaulders of the Righteous", "BIS")
LoonBestInSlot:AddItem(spec, "27847", "Shoulders", "Fanblade Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "32073", "Shoulders", "Spaulders of Dementia", "Alt")
LoonBestInSlot:AddItem(spec, "30381", "Shoulders", "Kaylaan's Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "29316", "Shoulders", "Warchief's Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "24463", "Shoulders", "Pauldrons of Brute Force", "Alt")

LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape", "BIS")
LoonBestInSlot:AddItem(spec, "24253", "Back", "Cloak of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29385", "Back", "Farstrider Defender's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "27988", "Back", "Burnoose of Shifting Ages", "Alt")
LoonBestInSlot:AddItem(spec, "24379", "Back", "Bogstrok Scale Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "29777", "Back", "Cloak of the Valiant Defender", "Alt")

LoonBestInSlot:AddItem(spec, "28203", "Chest", "Breastplate of the Righteous", "BIS")
LoonBestInSlot:AddItem(spec, "28262", "Chest", "Jade-Skull Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29127", "Chest", "Vindicator's Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "23507", "Chest", "Adamantite Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "25819", "Chest", "Breastplate of the Warbringer", "Alt")
LoonBestInSlot:AddItem(spec, "30270", "Chest", "Scavenged Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30296", "Chest", "Lost Chestplate of the Reverent", "Alt")
LoonBestInSlot:AddItem(spec, "29337", "Chest", "The Exarch's Protector", "Alt")

LoonBestInSlot:AddItem(spec, "29252", "Bracers", "Bracers of Dignity", "BIS")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor", "BIS Mit")
LoonBestInSlot:AddItem(spec, "28167", "Bracers", "Sha'tari Wrought Armguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "27459", "Bracers", "Vambraces of Daring", "Alt")
LoonBestInSlot:AddItem(spec, "30400", "Bracers", "Thadell's Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30225", "Bracers", "Junior Technician 3rd Grade Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "32072", "Gloves", "Gauntlets of Dissension", "BIS")
LoonBestInSlot:AddItem(spec, "23532", "Gloves", "Gauntlets of the Iron Tower", "Alt")
LoonBestInSlot:AddItem(spec, "27535", "Gloves", "Gauntlets of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "23517", "Gloves", "Felsteel Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "25788", "Gloves", "Dauntless Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "28390", "Gloves", "Thatia's Self-Correcting Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29134", "Gloves", "Gauntlets of the Chosen", "Alt")
LoonBestInSlot:AddItem(spec, "29959", "Gloves", "Spiritualist's Gauntlets", "Alt")

LoonBestInSlot:AddItem(spec, "29253", "Belt", "Girdle of Valorous Deeds", "BIS")
LoonBestInSlot:AddItem(spec, "27672", "Belt", "Girdle of the Immovable", "Alt")
LoonBestInSlot:AddItem(spec, "29238", "Belt", "Lion's Heart Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "31460", "Belt", "Sha'tari Vindicator's Waistguard", "Alt")
LoonBestInSlot:AddItem(spec, "30371", "Belt", "Lightwarden's Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "30330", "Belt", "Starcaller's Plated Belt", "Alt")
LoonBestInSlot:AddItem(spec, "30380", "Belt", "Girdle of the Lost Vindicator", "Alt")

LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "23518", "Legs", "Felsteel Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27527", "Legs", "Greaves of the Shatterer", "Alt")
LoonBestInSlot:AddItem(spec, "29783", "Legs", "Legguards of the Resolute Defender", "Alt")
LoonBestInSlot:AddItem(spec, "27839", "Legs", "Legplates of the Righteous", "Alt")
LoonBestInSlot:AddItem(spec, "29774", "Legs", "Kirin'Var Defender's Chausses", "Alt")

LoonBestInSlot:AddItem(spec, "29254", "Feet", "Boots of the Righteous Path", "BIS")
LoonBestInSlot:AddItem(spec, "29239", "Feet", "Eaglecrest Warboots", "Alt")
LoonBestInSlot:AddItem(spec, "27813", "Feet", "Boots of the Colossus", "Alt")
LoonBestInSlot:AddItem(spec, "32866", "Feet", "Ascendant's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29325", "Feet", "Flesh Beast's Metal Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30334", "Feet", "Starcaller's Plated Stompers", "Alt")
LoonBestInSlot:AddItem(spec, "30386", "Feet", "Bloodguard's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "28318", "Feet", "Obsidian Clodstompers", "Alt")

LoonBestInSlot:AddItem(spec, "29173", "Neck", "Strength of the Untamed", "BIS")
LoonBestInSlot:AddItem(spec, "27871", "Neck", "Maladaar's Blessed Chaplet", "Alt")
LoonBestInSlot:AddItem(spec, "27792", "Neck", "Steam-Hinge Chain of Valor", "Alt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "Alt")
LoonBestInSlot:AddItem(spec, "30378", "Neck", "Thalodien's Charm", "Alt")
LoonBestInSlot:AddItem(spec, "31696", "Neck", "Natasha's Battle Chain", "Alt")
LoonBestInSlot:AddItem(spec, "29336", "Neck", "Mark of the Ravenguard", "Alt")
LoonBestInSlot:AddItem(spec, "28321", "Neck", "Enchanted Thorium Torque", "Alt")
LoonBestInSlot:AddItem(spec, "25809", "Neck", "Maimfist's Choker", "Alt")
LoonBestInSlot:AddItem(spec, "25803", "Neck", "Medallion of the Valiant Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "Alt")

LoonBestInSlot:AddItem(spec, "31319", "Ring", "Band of Impenetrable Defenses", "BIS")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry", "BIS")
LoonBestInSlot:AddItem(spec, "30006", "Ring", "Wind Trader's Band", "Alt")
LoonBestInSlot:AddItem(spec, "27822", "Ring", "Crystal Band of Valor", "Alt")
LoonBestInSlot:AddItem(spec, "28211", "Ring", "Lieutenant's Signet of Lordaeron", "Alt")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force", "Alt")
LoonBestInSlot:AddItem(spec, "31078", "Ring", "Protector's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "27436", "Ring", "Iron Band of the Unbreakable", "Alt")
LoonBestInSlot:AddItem(spec, "24088", "Ring", "Delicate Eternium Ring", "Alt")
LoonBestInSlot:AddItem(spec, "31924", "Ring", "Yor's Revenge", "Alt")
LoonBestInSlot:AddItem(spec, "29323", "Ring", "Andormu's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "28265", "Ring", "Dath'Remar's Ring of Defense", "Alt")

LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30300", "Trinket", "Dabiri's Enigma", "Alt Mit")
LoonBestInSlot:AddItem(spec, "19431", "Trinket", "Styleen's Impeding Scarab", "Alt Mit")
LoonBestInSlot:AddItem(spec, "24125", "Trinket", "Figurine - Dawnstone Crab", "Alt Mit")
LoonBestInSlot:AddItem(spec, "28042", "Trinket", "Regal Protectorate", "Alt Mit")
LoonBestInSlot:AddItem(spec, "23040", "Trinket", "Glyph of Deflection", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600", "Alt Mit")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "Alt")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "Alt")
LoonBestInSlot:AddItem(spec, "32864", "Trinket", "Commander's Badge", "Alt")
LoonBestInSlot:AddItem(spec, "27770", "Trinket", "Argussian Compass", "Alt")
LoonBestInSlot:AddItem(spec, "24126", "Trinket", "Figurine - Living Ruby Serpent", "Alt")
LoonBestInSlot:AddItem(spec, "13503", "Trinket", "Alchemist's Stone", "Alt")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "18820", "Trinket", "Talisman of Ephemeral Power", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "19950", "Trinket", "Zandalarian Hero Charm", "Alt")

LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "BIS")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "BIS")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "29156", "MH", "Honor's Call", "Alt")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer", "Alt")
LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry", "Alt")
LoonBestInSlot:AddItem(spec, "32660", "MH", "Crystalforged Sword", "Alt")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "27899", "MH", "Mana Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams", "Alt")
LoonBestInSlot:AddItem(spec, "22988", "MH", "The End of Dreams", "Alt")
LoonBestInSlot:AddItem(spec, "22807", "MH", "Wraith Blade", "Alt")
LoonBestInSlot:AddItem(spec, "19360", "MH", "Lok'amir il Romathis", "Alt")
LoonBestInSlot:AddItem(spec, "21622", "MH", "Sharpened Silithid Femur", "Alt")
LoonBestInSlot:AddItem(spec, "24361", "MH", "Spellfire Longsword", "Alt")
LoonBestInSlot:AddItem(spec, "24384", "MH", "Diamond-Core Sledgemace", "Alt")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS")
LoonBestInSlot:AddItem(spec, "27917", "Libram", "Libram of the Eternal Rest", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Alt")

LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar", "BIS")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra", "Alt")
LoonBestInSlot:AddItem(spec, "32082", "Shield", "The Fel Barrier", "Alt")
LoonBestInSlot:AddItem(spec, "32652", "Shield", "Ogri'la Aegis", "Alt")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird", "Alt")
LoonBestInSlot:AddItem(spec, "27449", "Shield", "Blood Knight Defender", "Alt")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous", "Alt")
LoonBestInSlot:AddItem(spec, "28166", "Shield", "Shield of the Void", "Alt")
LoonBestInSlot:AddItem(spec, "31200", "Shield", "Shield of the Wayward Footman", "Alt")
LoonBestInSlot:AddItem(spec, "23043", "Shield", "The Face of Death", "Alt")
LoonBestInSlot:AddItem(spec, "21269", "Shield", "Blessed Qiraji Bulwark", "Alt")
