local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy", "0")
LoonBestInSlot:AddItem(spec, "32472", "Head", "Justicebringer 2000 Specs", "BIS")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "BIS")
LoonBestInSlot:AddItem(spec, "32084", "Head", "Helmet of the Steadfast Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown", "Alt")
LoonBestInSlot:AddItem(spec, "28348", "Head", "Moonglade Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "25820", "Head", "Metallic Headband of Simm'onz", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance", "Alt")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart", "Alt")

LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "Alt")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape", "Alt")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Bishop's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "25805", "Back", "Mantle of Vivification", "Alt")
LoonBestInSlot:AddItem(spec, "25810", "Back", "Vicar's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments", "Alt")
LoonBestInSlot:AddItem(spec, "28202", "Chest", "Moonglade Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30298", "Chest", "Void Slayer's Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "23539", "Bracers", "Blessed Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "21604", "Bracers", "Bracelets of Royal Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent", "Alt")
LoonBestInSlot:AddItem(spec, "28029", "Bracers", "Goldenvine Wraps", "Alt")

LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "BIS")
LoonBestInSlot:AddItem(spec, "27457", "Gloves", "Life Bearer's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28304", "Gloves", "Prismatic Mittens of Mending", "Alt")
LoonBestInSlot:AddItem(spec, "29327", "Gloves", "Cryo-mitts", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "Alt")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification", "Alt")
LoonBestInSlot:AddItem(spec, "21582", "Belt", "Grasp of the Old God", "Alt")
LoonBestInSlot:AddItem(spec, "30932", "Belt", "Akama's Sash", "Alt")

LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "30299", "Legs", "Starcaller's Plated Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "30256", "Legs", "Pants of the Naaru", "Alt")

LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity", "BIS")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious", "Alt")
LoonBestInSlot:AddItem(spec, "28221", "Feet", "Boots of the Watchful Heart", "Alt")
LoonBestInSlot:AddItem(spec, "27549", "Feet", "Wavefury Boots", "Alt")
LoonBestInSlot:AddItem(spec, "25792", "Feet", "Curate's Boots", "Alt")

LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "BIS")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion", "Alt")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope", "Alt")
LoonBestInSlot:AddItem(spec, "21712", "Neck", "Amulet of the Fallen God", "Alt")

LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "BIS")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "BIS")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "BIS")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband", "Alt")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "BIS")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "BIS")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "Alt")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "Alt")

LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "BIS")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "Alt")
LoonBestInSlot:AddItem(spec, "25759", "MH", "Mogor's Anointing Club", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "22819", "OH", "Shield of Condemnation", "BIS")
LoonBestInSlot:AddItem(spec, "23048", "OH", "Sapphiron's Right Eye", "Alt")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "Alt")
LoonBestInSlot:AddItem(spec, "27772", "OH", "Stormshield of Renewal", "Alt")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing", "Alt")
LoonBestInSlot:AddItem(spec, "31493", "OH", "Netherwing Spiritualist's Charm", "Alt")

LoonBestInSlot:AddItem(spec, "23006", "Libram", "Libram of Light", "BIS")
LoonBestInSlot:AddItem(spec, "28296", "Libram", "Libram of the Lightbringer", "Alt")
LoonBestInSlot:AddItem(spec, "25644", "Libram", "Blessed Book of Nagrand", "Alt")
