local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "0")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "BIS")
LoonBestInSlot:AddItem(spec, "31105", "Head", "Overlord's Helmet of Second Sight", "BIS")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt")

LoonBestInSlot:AddItem(spec, "33173", "Shoulders", "Ragesteel Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "27771", "Shoulders", "Doomplate Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")
LoonBestInSlot:AddItem(spec, "28865", "Shoulders", "High Warlord's Scaled Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "28713", "Shoulders", "Grand Marshal's Scaled Shoulders", "Alt")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "BIS")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")
LoonBestInSlot:AddItem(spec, "28249", "Back", "Capacitus' Cloak of Calibration", "Alt")

LoonBestInSlot:AddItem(spec, "23522", "Chest", "Ragesteel Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "28403", "Chest", "Doomplate Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "24396", "Chest", "Vest of Vengeance", "Alt")
LoonBestInSlot:AddItem(spec, "31548", "Chest", "Blackened Chestplate", "Alt")

LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28646", "Bracers", "General's Scaled Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "27918", "Bracers", "Bands of Syth", "Alt")

LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "18823", "Gloves", "Aged Core Leather Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29509", "Gloves", "Windstrike Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "BIS")
LoonBestInSlot:AddItem(spec, "27755", "Belt", "Girdle of Gallantry", "BIS")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Alt")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "BIS")

LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust", "Alt")
LoonBestInSlot:AddItem(spec, "28318", "Feet", "Obsidian Clodstompers", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "BIS")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "Alt")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "29177", "Ring", "A'dal's Command", "BIS")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "23038", "Ring", "Band of Unnatural Forces", "Alt")
LoonBestInSlot:AddItem(spec, "31380", "Ring", "Acrobat's Mark of the Sha'tar", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "22954", "Trinket", "Kiss of the Spider", "Alt")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos", "Alt")

LoonBestInSlot:AddItem(spec, "28429", "2H", "Lionheart Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28441", "2H", "Deep Thunder", "BIS")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "31322", "2H", "The Hammer of Destiny", "Alt")
LoonBestInSlot:AddItem(spec, "23541", "2H", "Khorium Champion", "Alt")
LoonBestInSlot:AddItem(spec, "22798", "2H", "Might of Menethil", "Alt")
LoonBestInSlot:AddItem(spec, "27986", "2H", "Crow Wing Reaper", "Alt")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement", "BIS")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Alt")
LoonBestInSlot:AddItem(spec, "23203", "Libram", "Libram of Fervor", "Alt")
LoonBestInSlot:AddItem(spec, "22402", "Libram", "Libram of Grace", "Alt")
