local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "0")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "BIS - Engineer")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "BIS - Non Engineer")
LoonBestInSlot:AddItem(spec, "31105", "Head", "Overlord's Helmet of Second Sight", "BIS - No Meta Gem")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt - Meta Gem")

LoonBestInSlot:AddItem(spec, "33173", "Shoulders", "Ragesteel Shoulders", "Ragesteel Setup BIS")
LoonBestInSlot:AddItem(spec, "27771", "Shoulders", "Doomplate Shoulderguards", "Doomplate Setup BIS")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Option")
LoonBestInSlot:AddItem(spec, "28865", "Shoulders", "High Warlord's Scaled Shoulders", "PVP")
LoonBestInSlot:AddItem(spec, "28713", "Shoulders", "Grand Marshal's Scaled Shoulders", "PVP")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS-Crafted")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "BIS for Hit")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt Hit")
LoonBestInSlot:AddItem(spec, "28249", "Back", "Capacitus' Cloak of Calibration", "Option")

LoonBestInSlot:AddItem(spec, "23522", "Chest", "Ragesteel Breastplate", "Ragesteel BIS")
LoonBestInSlot:AddItem(spec, "28403", "Chest", "Doomplate Chestguard", "Doomplate BIS")
LoonBestInSlot:AddItem(spec, "24396", "Chest", "Vest of Vengeance", "Option")
LoonBestInSlot:AddItem(spec, "31548", "Chest", "Blackened Chestplate", "Option")

LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28646", "Bracers", "General's Scaled Bracers", "Alt-PVP")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt-Crafted")
LoonBestInSlot:AddItem(spec, "27918", "Bracers", "Bands of Syth", "Option")

LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "18823", "Gloves", "Aged Core Leather Gloves", "Option")
LoonBestInSlot:AddItem(spec, "29509", "Gloves", "Windstrike Gloves", "Alt-Crafted")

LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "BIS-Hit")
LoonBestInSlot:AddItem(spec, "27755", "Belt", "Girdle of Gallantry", "BIS-NoHit")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Option")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt-CraftedLeatherworking")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle", "Non-heroic")

LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "BIS-Hit Option")
LoonBestInSlot:AddItem(spec, "30533", "Legs", "Vanquisher's Legplates", "Seriously Don't use this")

LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS-Hit")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves", "BIS-Non Hit")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust", "Option")
LoonBestInSlot:AddItem(spec, "28318", "Feet", "Obsidian Clodstompers", "Option")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS-HIT")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "BIS-Non HIT")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "BOE")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker", "Easy to acquire")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Never Un-equip")
LoonBestInSlot:AddItem(spec, "29177", "Ring", "A'dal's Command", "BIS-NonHit")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "Bis-Hit")
LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet", "Easy Hit")
LoonBestInSlot:AddItem(spec, "23038", "Ring", "Band of Unnatural Forces", "CLASSIC ITEM")
LoonBestInSlot:AddItem(spec, "31380", "Ring", "Acrobat's Mark of the Sha'tar", "Easy non-hit")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "2nd Trinket")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "OPTIONAL 2nd Trinket")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "OPTIONAL 2nd trinket")
LoonBestInSlot:AddItem(spec, "22954", "Trinket", "Kiss of the Spider", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "23206", "Trinket", "Mark of the Champion", "Undead Only & Demons")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos", "Option")

LoonBestInSlot:AddItem(spec, "28429", "2H", "Lionheart Champion", "BIS")
LoonBestInSlot:AddItem(spec, "28441", "2H", "Deep Thunder", "Second BIS")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade", "Option")
LoonBestInSlot:AddItem(spec, "31322", "2H", "The Hammer of Destiny", "Option")
LoonBestInSlot:AddItem(spec, "23541", "2H", "Khorium Champion", "Option")
LoonBestInSlot:AddItem(spec, "22798", "2H", "Might of Menethil", "Old Weapon")
LoonBestInSlot:AddItem(spec, "27986", "2H", "Crow Wing Reaper", "Option")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement", "BIS")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Option")
LoonBestInSlot:AddItem(spec, "23203", "Libram", "Libram of Fervor", "Alt Alt")
LoonBestInSlot:AddItem(spec, "22402", "Libram", "Libram of Grace", "Cleansebot")
