local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "0")
LoonBestInSlot:AddItem(spec, "32495", "Head", "Powerheal 4000 Lens", "BIS")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "Alt")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown", "Alt")
LoonBestInSlot:AddItem(spec, "32016", "Head", "Merciless Gladiator's Mooncloth Hood", "Alt")
LoonBestInSlot:AddItem(spec, "31410", "Head", "Gladiator's Mooncloth Hood", "Alt")
LoonBestInSlot:AddItem(spec, "29174", "Head", "Watcher's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "31412", "Shoulders", "Gladiator's Mooncloth Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance", "Alt")
LoonBestInSlot:AddItem(spec, "22515", "Shoulders", "Shoulderpads of Faith", "Alt")
LoonBestInSlot:AddItem(spec, "28250", "Shoulders", "Vestia's Pauldrons of Inner Grace", "Alt")

LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "22960", "Back", "Cloak of Suturing", "BIS")
LoonBestInSlot:AddItem(spec, "21583", "Back", "Cloak of Clarity", "BIS")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Bishop's Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "Alt")
LoonBestInSlot:AddItem(spec, "27448", "Back", "Cloak of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape", "Alt")
LoonBestInSlot:AddItem(spec, "28373", "Back", "Cloak of Scintillating Auras", "Alt")
LoonBestInSlot:AddItem(spec, "27789", "Back", "Cloak of Whispering Shells", "Alt")
LoonBestInSlot:AddItem(spec, "25810", "Back", "Vicar's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "25805", "Back", "Mantle of Vivification", "Alt")
LoonBestInSlot:AddItem(spec, "27946", "Back", "Avian Cloak of Feathers", "Alt")
LoonBestInSlot:AddItem(spec, "25945", "Back", "Cloak of Revival", "Alt")
LoonBestInSlot:AddItem(spec, "31465", "Back", "Sha'tari Anchorite's Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments", "Alt")
LoonBestInSlot:AddItem(spec, "31413", "Chest", "Gladiator's Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "24397", "Chest", "Raiments of Divine Authority", "Alt")
LoonBestInSlot:AddItem(spec, "27506", "Chest", "Robe of Effervescent Light", "Alt")
LoonBestInSlot:AddItem(spec, "22512", "Chest", "Robe of Faith", "Alt")

LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "BIS")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent", "BIS")
LoonBestInSlot:AddItem(spec, "21604", "Bracers", "Bracelets of Royal Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "22519", "Bracers", "Bindings of Faith", "Alt")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps", "Alt")

LoonBestInSlot:AddItem(spec, "24393", "Gloves", "Bloody Surgeon's Mitts", "BIS")
LoonBestInSlot:AddItem(spec, "22517", "Gloves", "Gloves of Faith", "BIS")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", "Tempest's Touch", "Alt")
LoonBestInSlot:AddItem(spec, "27536", "Gloves", "Hallowed Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "28304", "Gloves", "Prismatic Mittens of Mending", "Alt")
LoonBestInSlot:AddItem(spec, "29315", "Gloves", "Gloves of Penitence", "Alt")
LoonBestInSlot:AddItem(spec, "31409", "Gloves", "Gladiator's Mooncloth Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification", "Alt")
LoonBestInSlot:AddItem(spec, "27542", "Belt", "Cord of Belief", "Alt")
LoonBestInSlot:AddItem(spec, "21582", "Belt", "Grasp of the Old God", "Alt")
LoonBestInSlot:AddItem(spec, "22518", "Belt", "Belt of Faith", "Alt")
LoonBestInSlot:AddItem(spec, "27843", "Belt", "Glyph-Lined Sash", "Alt")

LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "Alt")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "28218", "Legs", "Pontiff's Pantaloons of Prophecy", "Alt")
LoonBestInSlot:AddItem(spec, "22513", "Legs", "Leggings of Faith", "Alt")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration", "Alt")
LoonBestInSlot:AddItem(spec, "30256", "Legs", "Pants of the Naaru", "Alt")
LoonBestInSlot:AddItem(spec, "19385", "Legs", "Empowered Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious", "BIS")
LoonBestInSlot:AddItem(spec, "22516", "Feet", "Sandals of Faith", "Alt")
LoonBestInSlot:AddItem(spec, "19437", "Feet", "Boots of Pure Thought", "Alt")

LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope", "BIS")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion", "BIS")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope", "BIS")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "BIS")
LoonBestInSlot:AddItem(spec, "23036", "Neck", "Necklace of Necropsy", "BIS")
LoonBestInSlot:AddItem(spec, "21712", "Neck", "Amulet of the Fallen God", "BIS")
LoonBestInSlot:AddItem(spec, "27766", "Neck", "Swampstone Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28419", "Neck", "Choker of Fluid Thought", "Alt")
LoonBestInSlot:AddItem(spec, "29334", "Neck", "Sethekk Oracle's Focus", "Alt")

LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos", "BIS")
LoonBestInSlot:AddItem(spec, "23061", "Ring", "Ring of Faith", "BIS")
LoonBestInSlot:AddItem(spec, "22939", "Ring", "Band of Unanswered Prayers", "BIS")
LoonBestInSlot:AddItem(spec, "19382", "Ring", "Pure Elementium Band", "BIS")
LoonBestInSlot:AddItem(spec, "21620", "Ring", "Ring of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "BIS")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void", "BIS")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "BIS")
LoonBestInSlot:AddItem(spec, "29322", "Ring", "Keeper's Ring of Piety", "Alt")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband", "Alt")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope", "Alt")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "21625", "Trinket", "Scarab Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "Alt")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "Alt")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "Alt")
LoonBestInSlot:AddItem(spec, "28370", "Trinket", "Bangle of Endless Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "32964", "MH", "Merciless Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "BIS")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "BIS")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "BIS")
LoonBestInSlot:AddItem(spec, "28257", "MH", "Hammer of the Penitent", "Alt")
LoonBestInSlot:AddItem(spec, "23056", "MH", "Hammer of the Twisting Nether", "Alt")
LoonBestInSlot:AddItem(spec, "31304", "MH", "The Essence Focuser", "Alt")
LoonBestInSlot:AddItem(spec, "27538", "MH", "Lightsworn Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "28216", "MH", "Dathrohan's Ceremonial Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "27791", "MH", "Serpentcrest Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28033", "MH", "Epoch-Mender", "Alt")
LoonBestInSlot:AddItem(spec, "29133", "MH", "Seer's Cane", "Alt")

LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "BIS")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "BIS")
LoonBestInSlot:AddItem(spec, "23048", "OH", "Sapphiron's Right Eye", "Alt")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing", "Alt")
LoonBestInSlot:AddItem(spec, "28213", "OH", "Lordaeron Medical Guide", "Alt")
LoonBestInSlot:AddItem(spec, "23029", "OH", "Noth's Frigid Heart", "Alt")
LoonBestInSlot:AddItem(spec, "27714", "OH", "Swamplight Lantern", "Alt")
LoonBestInSlot:AddItem(spec, "28387", "OH", "Lamp of Peaceful Repose", "Alt")

LoonBestInSlot:AddItem(spec, "29779", "Wand", "Rejuvenating Scepter", "Alt")
LoonBestInSlot:AddItem(spec, "27885", "Wand", "Soul-Wand of the Aldor", "Alt")
LoonBestInSlot:AddItem(spec, "23009", "Wand", "Wand of the Whispering Dead", "Alt")
