local spec = LoonBestInSlot:RegisterSpec("Priest", "Shadow")
LoonBestInSlot:AddItem(spec, "32494", "Head", " Destruction Holo-gogs", "BIS - Engineering")
LoonBestInSlot:AddItem(spec, "24266", "Head", " Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "31104", "Head", " Evoker's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "28415", "Head", " Hood of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "28183", "Head", " Hydromancer's Headwrap", "Alt")
LoonBestInSlot:AddItem(spec, "28169", "Head", " Mag'hari Ritualist's Horns", "Alt")
LoonBestInSlot:AddItem(spec, "24689", "Head", " Elementalist Skullcap", "Alt")

LoonBestInSlot:AddItem(spec, "21869", "Shoulders", " Frozen Shadoweave Shoulders", "BIS - Tailoring")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", " Spaulders of Oblivion", "BIS")
LoonBestInSlot:AddItem(spec, "31162", "Shoulders", " Felstone Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "24691", "Shoulders", " Elementalist Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", " Spaulders of the Torn-heart", "Alt")

LoonBestInSlot:AddItem(spec, "31201", "Back", " Illidari Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "25043", "Back", " Amber Cape", "Alt")
LoonBestInSlot:AddItem(spec, "25042", "Back", " Nether Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "31254", "Back", " Striderhide Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "25041", "Back", " Ambusher's Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "24252", "Back", " Cloak of the Black Void", "Alt")
LoonBestInSlot:AddItem(spec, "32541", "Back", " Terokk's Wisdom", "Alt")

LoonBestInSlot:AddItem(spec, "21871", "Chest", " Frozen Shadoweave Robe", "BIS - Tailoring")
LoonBestInSlot:AddItem(spec, "28232", "Chest", " Robe of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "31297", "Chest", " Robe of the Crimson Order", "Alt")
LoonBestInSlot:AddItem(spec, "29341", "Chest", " Auchenai Anchorite's Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28342", "Chest", " Warp Infused Drape", "Alt")

LoonBestInSlot:AddItem(spec, "31225", "Bracers", " Illidari Bindings", "BIS")
LoonBestInSlot:AddItem(spec, "24692", "Bracers", " Elementalist Bracelets", "Alt")
LoonBestInSlot:AddItem(spec, "24684", "Bracers", " Archmage Bracelets", "Alt")
LoonBestInSlot:AddItem(spec, "24676", "Bracers", " Eldr'naan Bracelets", "Alt")
LoonBestInSlot:AddItem(spec, "31192", "Bracers", " Crocolisk Hide Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", " Bracers of Havok", "Alt")
LoonBestInSlot:AddItem(spec, "32655", "Bracers", " Crystalweave Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "27746", "Bracers", " Arcanium Signet Bands", "Alt")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", " Shattrath Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "29240", "Bracers", " Bands of Negation", "Alt")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", " Crimson Bracers of Gloom", "Alt")

LoonBestInSlot:AddItem(spec, "31166", "Gloves", " Nethersteel-Lined Handwraps", "BIS")
LoonBestInSlot:AddItem(spec, "24688", "Gloves", " Elementalist Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "24680", "Gloves", " Archmage Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31181", "Gloves", " Rockwurm Hide Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "24672", "Gloves", " Eldr'naan Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", " Tempest's Touch", "Alt")
LoonBestInSlot:AddItem(spec, "27889", "Gloves", " Jaedenfire Gloves of Annihilation", "Alt")
LoonBestInSlot:AddItem(spec, "21585", "Gloves", " Dark Storm Gauntlets", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "19407", "Gloves", " Ebony Flame Gloves", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "27493", "Gloves", " Gloves of the Deadwatcher", "Alt")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", " Mana-Etched Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30038", "Belt", " Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "24256", "Belt", " Girdle of Ruination", "Alt")
LoonBestInSlot:AddItem(spec, "27843", "Belt", " Glyph-Lined Sash", "Alt")
LoonBestInSlot:AddItem(spec, "31461", "Belt", " A'dal's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "31199", "Belt", " Voidweave Cilice", "Alt")
LoonBestInSlot:AddItem(spec, "24685", "Belt", " Elementalist Belt", "Alt")
LoonBestInSlot:AddItem(spec, "24677", "Belt", " Archmage Belt", "Alt")
LoonBestInSlot:AddItem(spec, "22730", "Belt", " Eyestalk Waist Cord", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "29241", "Belt", " Belt of Depravity", "Alt")
LoonBestInSlot:AddItem(spec, "24395", "Belt", " Mindfire Waistband", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", " Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30531", "Legs", " Breeches of the Occultist", "Alt")
LoonBestInSlot:AddItem(spec, "30532", "Legs", " Kirin Tor Master's Trousers", "Alt")
LoonBestInSlot:AddItem(spec, "31212", "Legs", " Chimaerahide Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "24690", "Legs", " Elementalist Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "24682", "Legs", " Archmage Pants", "Alt")
LoonBestInSlot:AddItem(spec, "28185", "Legs", " Khadgar's Kilt of Abjuration", "Alt")
LoonBestInSlot:AddItem(spec, "27948", "Legs", " Trousers of Oblivion", "Alt")

LoonBestInSlot:AddItem(spec, "21870", "Feet", " Frozen Shadoweave Boots", "BIS - Tailoring")
LoonBestInSlot:AddItem(spec, "28179", "Feet", " Shattrath Jumpers", "BIS")
LoonBestInSlot:AddItem(spec, "35581", "Feet", " Rocket Boots Xtreme Lite", "Alt - Engineering")
LoonBestInSlot:AddItem(spec, "31216", "Feet", " Abyssal Cloth Footwraps", "Alt")
LoonBestInSlot:AddItem(spec, "24686", "Feet", " Elementalist Boots", "Alt")
LoonBestInSlot:AddItem(spec, "24678", "Feet", " Archmage Slippers", "Alt")

LoonBestInSlot:AddItem(spec, "18814", "Neck", " Choker of the Fire Lord", "BIS - Classic")
LoonBestInSlot:AddItem(spec, "33921", "Neck", " Vindicator's Pendant of Dominance", "BIS - Alt")
LoonBestInSlot:AddItem(spec, "31693", "Neck", " Natasha's Arcane Filament", "BIS")
LoonBestInSlot:AddItem(spec, "24121", "Neck", " Chain of the Twilight Owl", "BIS - Group Content")
LoonBestInSlot:AddItem(spec, "24116", "Neck", " Eye of the Night", "BIS - Group Content")
LoonBestInSlot:AddItem(spec, "31692", "Neck", " Natasha's Ember Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28134", "Neck", " Brooch of Heightened Potential", "Alt")
LoonBestInSlot:AddItem(spec, "20966", "Neck", " Jade Pendant of Blasting", "Alt - Group Content")

LoonBestInSlot:AddItem(spec, "21709", "Ring", " Ring of the Fallen God", "BIS - Classic")
LoonBestInSlot:AddItem(spec, "23031", "Ring", " Band of the Inevitable", "BIS - Classic")
LoonBestInSlot:AddItem(spec, "29352", "Ring", " Cobalt Band of Tyrigosa", "BIS")
LoonBestInSlot:AddItem(spec, "32941", "Ring", " Corruptor's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "28555", "Ring", " Seal of the Exorcist", "BIS - Hit")
LoonBestInSlot:AddItem(spec, "19434", "Ring", " Band of Dark Dominion", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "19147", "Ring", " Ring of Spell Power", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "29126", "Ring", " Seer's Signet", "Alt - Scryers")
LoonBestInSlot:AddItem(spec, "31290", "Ring", " Band of Dominion", "Alt")
LoonBestInSlot:AddItem(spec, "31075", "Ring", " Evoker's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "31075", "Ring", " Evoker's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "29172", "Ring", " Ashyen's Gift", "Alt - Hit")
LoonBestInSlot:AddItem(spec, "34073", "Ring", " The Horseman's Signet Ring", "BIS - Unobtainable")

LoonBestInSlot:AddItem(spec, "29370", "Trinket", " Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", " Darkmoon Card: Crusade", "BIS")
LoonBestInSlot:AddItem(spec, "23207", "Trinket", " Mark of the Champion", "BIS - Classic")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", " Quagmirran's Eye", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", " The Restrained Essence of Sapphiron", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", " Neltharion's Tear", "Alt - Classic")
LoonBestInSlot:AddItem(spec, "25619", "Trinket", " Glowing Crystal Insignia", "Alt")
LoonBestInSlot:AddItem(spec, "25620", "Trinket", " Ancient Crystal Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28223", "Trinket", " Arcanist's Stone", "Alt - Hit")
LoonBestInSlot:AddItem(spec, "25936", "Trinket", " Terokkar Tablet of Vim", "Alt - Hit")
LoonBestInSlot:AddItem(spec, "30340", "Trinket", " Starkiller's Bauble", "Alt - Hit")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", " Scryer's Bloodgem", "Alt - Scryers")
LoonBestInSlot:AddItem(spec, "27922", "Trinket", " Mark of Defiance", "Alt - Alt")
LoonBestInSlot:AddItem(spec, "27924", "Trinket", " Mark of Defiance", "Alt - Alt")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", " Dark Iron Smoking Pipe", "BIS (Unobtainable)")

LoonBestInSlot:AddItem(spec, "30832", "MH", " Gavel of Unearthed Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "23554", "MH", " Eternium Runed Blade", "BIS")
LoonBestInSlot:AddItem(spec, "30723", "MH", " Talon of the Tempest", "BIS - World Boss")
LoonBestInSlot:AddItem(spec, "33687", "MH", " Vengeful Gladiator's Gavel", "BIS - Alt")
LoonBestInSlot:AddItem(spec, "32963", "MH", " Merciless Gladiator's Gavel", "Alt - Alt")
LoonBestInSlot:AddItem(spec, "32450", "MH", " Gladiator's Gavel", "Alt - Alt")
LoonBestInSlot:AddItem(spec, "27937", "MH", " Sky Breaker", "Alt")
LoonBestInSlot:AddItem(spec, "27543", "MH", " Starlight Dagger", "Alt")
LoonBestInSlot:AddItem(spec, "27868", "MH", " Runesong Dagger", "Alt")
LoonBestInSlot:AddItem(spec, "27741", "MH", " Bleeding Hollow Warhammer", "Alt")

LoonBestInSlot:AddItem(spec, "29272", "OH", " Orb of the Soul-Eater", "BIS")
LoonBestInSlot:AddItem(spec, "29273", "OH", " Khadgar's Knapsack", "Alt")
LoonBestInSlot:AddItem(spec, "25099", "OH", " Draenei Crystal Rod", "Alt")
LoonBestInSlot:AddItem(spec, "25098", "OH", " Tuurik Torch", "Alt")
LoonBestInSlot:AddItem(spec, "19309", "OH", " Tome of Shadow Force", "Alt - Classic")

LoonBestInSlot:AddItem(spec, "32872", "Wand", " Illidari Rod of Discipline", "BIS")
LoonBestInSlot:AddItem(spec, "25295", "Wand", " Flawless Wand", "BIS")
LoonBestInSlot:AddItem(spec, "25294", "Wand", " Dragonscale Wand", "Alt")
LoonBestInSlot:AddItem(spec, "25293", "Wand", " Draenethyst Wand", "Alt")
LoonBestInSlot:AddItem(spec, "29350", "Wand", " The Black Stalk", "Alt")
LoonBestInSlot:AddItem(spec, "30859", "Wand", " Wand of the Seer", "Alt")
LoonBestInSlot:AddItem(spec, "28386", "Wand", " Nether Core's Control Rod", "Alt")
LoonBestInSlot:AddItem(spec, "27890", "Wand", " Wand of the Netherwing", "Alt")
LoonBestInSlot:AddItem(spec, "25292", "Wand", " Mechano-Wand", "Alt")
LoonBestInSlot:AddItem(spec, "25291", "Wand", " Nobility Torch", "Alt")
LoonBestInSlot:AddItem(spec, "25290", "Wand", " Solitaire Wand", "Alt")
LoonBestInSlot:AddItem(spec, "25289", "Wand", " Majestic Wand", "Alt")
LoonBestInSlot:AddItem(spec, "25294", "Wand", " Dragonscale Wand", "Alt")
