local spec = LoonBestInSlot:RegisterSpec("Rogue", "", "0")
LoonBestInSlot:AddItem(spec, "32478", "Head", "Deathblow X11 Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm", "Alt")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "Alt")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt")

LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "29148", "Shoulders", "Blackened Leather Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "29147", "Shoulders", "Talbuk Hide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28032", "Back", "Delicate Green Poncho", "Alt")

LoonBestInSlot:AddItem(spec, "28264", "Chest", "Wastewalker Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "BIS")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor", "Alt")

LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "27531", "Gloves", "Wastewalker Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "30003", "Gloves", "Gloves of the Nether-Stalker", "Alt")

LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "BIS")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30372", "Belt", "Socrethar's Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "31464", "Belt", "Naaru Belt of Precision", "Alt")

LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30939", "Feet", "Felboar Hide Shoes", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing", "Alt")
LoonBestInSlot:AddItem(spec, "19377", "Neck", "Prestor's Talisman of Connivery", "Alt")

LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "BIS")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "30973", "Ring", "Band of Anguish", "Alt")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "BIS")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")
LoonBestInSlot:AddItem(spec, "22954", "Trinket", "Kiss of the Spider", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "Alt")

LoonBestInSlot:AddItem(spec, "32052", "MH", "Merciless Gladiator's Slicer", "BIS")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "Alt")
LoonBestInSlot:AddItem(spec, "28295", "MH", "Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "31332", "MH", "Blinkstrike", "Alt")
LoonBestInSlot:AddItem(spec, "29124", "MH", "Vindicator's Brand", "Alt")
LoonBestInSlot:AddItem(spec, "28312", "MH", "Gladiator's Shanker", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "31331", "MH", "The Night Blade", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "32027", "OH", "Merciless Gladiator's Quickblade", "BIS")
LoonBestInSlot:AddItem(spec, "28307", "OH", "Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "28189", "OH", "Latro's Shifting Sword", "Alt")
LoonBestInSlot:AddItem(spec, "29275", "OH", "Searing Sunblade", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "28310", "OH", "Gladiator's Shiv", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket", "BIS")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow", "BIS")
LoonBestInSlot:AddItem(spec, "30279", "Ranged", "Mama's Insurance", "Alt")
LoonBestInSlot:AddItem(spec, "30227", "Ranged", "Mark V's Throwing Star", "Alt")
