local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto", "0")
LoonBestInSlot:AddItem(spec, "32475", "Head", "Living Replicator Specs", "BIS")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood", "BIS")
LoonBestInSlot:AddItem(spec, "29508", "Head", "Living Dragonscale Helm", "Alt")
LoonBestInSlot:AddItem(spec, "27759", "Head", "Headdress of the Tides", "Alt")
LoonBestInSlot:AddItem(spec, "29174", "Head", "Watcher's Cowl", "Alt")

LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "27826", "Shoulders", "Mantle of the Sea Wolf", "Alt")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons", "Alt")

LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape", "Alt")
LoonBestInSlot:AddItem(spec, "27448", "Back", "Cloak of the Everliving", "Alt")

LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "BIS")
LoonBestInSlot:AddItem(spec, "23527", "Chest", "Earthpeace Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30298", "Chest", "Void Slayer's Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "28194", "Bracers", "Primal Surge Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "27806", "Gloves", "Fathomheart Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "28304", "Gloves", "Prismatic Mittens of Mending", "Alt")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch", "Alt")

LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "BIS")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification", "Alt")

LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt", "Alt")
LoonBestInSlot:AddItem(spec, "27875", "Legs", "Hallowed Trousers", "Alt")

LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity", "BIS")
LoonBestInSlot:AddItem(spec, "27549", "Feet", "Wavefury Boots", "Alt")
LoonBestInSlot:AddItem(spec, "27525", "Feet", "Jeweled Boots of Sanctification", "Alt")

LoonBestInSlot:AddItem(spec, "32531", "Neck", "Gezzarak's Fang", "BIS")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord", "BIS")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope", "Alt")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope", "Alt")

LoonBestInSlot:AddItem(spec, "32535", "Ring", "Gift of the Talonpriests", "BIS")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence", "BIS")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band", "BIS")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband", "BIS")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void", "BIS")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos", "BIS")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "BIS")
LoonBestInSlot:AddItem(spec, "21625", "Trinket", "Scarab Brooch", "Alt")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "Alt")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler", "Alt")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic", "Alt")

LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation", "BIS")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min", "Alt")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light", "Alt")

LoonBestInSlot:AddItem(spec, "29267", "OH", "Light-Bearer's Faith Shield", "BIS")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "22819", "OH", "Shield of Condemnation", "Alt")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing", "Alt")
LoonBestInSlot:AddItem(spec, "27772", "OH", "Stormshield of Renewal", "Alt")
LoonBestInSlot:AddItem(spec, "31292", "OH", "Crystal Pulse Shield", "Alt")

LoonBestInSlot:AddItem(spec, "27544", "Totem", "Totem of Spontaneous Regrowth", "BIS")
LoonBestInSlot:AddItem(spec, "22396", "Totem", "Totem of Life", "Alt")
LoonBestInSlot:AddItem(spec, "25645", "Totem", "Totem of the Plains", "Alt")
