local spec = LoonBestInSlot:RegisterSpec("Shaman", "Elemental", "0")
LoonBestInSlot:AddItem(spec, "32476", "Head", "Gadgetstorm Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "32086", "Head", "Storm Master's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "Alt")
LoonBestInSlot:AddItem(spec, "31330", "Head", "Lightning Crown", "Alt")
LoonBestInSlot:AddItem(spec, "31107", "Head", "Shamanistic Helmet of Second Sight", "Alt")

LoonBestInSlot:AddItem(spec, "32078", "Shoulders", "Pauldrons of Wild Magic", "BIS")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart", "Alt")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities", "BIS")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "29519", "Chest", "Netherstrike Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "28191", "Chest", "Mana-Etched Vestments", "Alt")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd", "Alt")

LoonBestInSlot:AddItem(spec, "29521", "Bracers", "Netherstrike Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "Alt")

LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "27793", "Gloves", "Earth Mantle Handwraps", "BIS")
LoonBestInSlot:AddItem(spec, "31149", "Gloves", "Gloves of Pandemonium", "Alt")
LoonBestInSlot:AddItem(spec, "31280", "Gloves", "Thundercaller's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30930", "Gloves", "Grips of the Void", "Alt")

LoonBestInSlot:AddItem(spec, "29520", "Belt", "Netherstrike Belt", "BIS")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "BIS")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt", "BIS")
LoonBestInSlot:AddItem(spec, "31283", "Belt", "Sash of Sealed Fate", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30541", "Legs", "Stormsong Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "29142", "Legs", "Kurenai Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "29141", "Legs", "Tempest Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30709", "Legs", "Pantaloons of Flaming Wrath", "Alt")

LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers", "Alt")

LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "BIS")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "29333", "Neck", "Torc of the Sethekk Prophet", "Alt")

LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "29367", "Ring", "Ring of Cryptic Dreams", "BIS")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa", "BIS")
LoonBestInSlot:AddItem(spec, "31290", "Ring", "Band of Dominion", "BIS")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "Alt")

LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "28418", "Trinket", "Shiffar's Nexus-Horn", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")

LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade", "Alt")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "27868", "MH", "Runesong Dagger", "Alt")

LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack", "BIS")
LoonBestInSlot:AddItem(spec, "29268", "OH", "Mazthoril Honor Shield", "BIS")
LoonBestInSlot:AddItem(spec, "31287", "OH", "Draenei Honor Guard Shield", "Alt")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance", "Alt")

LoonBestInSlot:AddItem(spec, "28248", "Totem", "Totem of the Void", "BIS")
LoonBestInSlot:AddItem(spec, "23199", "Totem", "Totem of the Storm", "Alt")
LoonBestInSlot:AddItem(spec, "29389", "Totem", "Totem of the Pulsing Earth", "Alt")
