local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "0")
LoonBestInSlot:AddItem(spec, "32474", "Head", "Surestrike Goggles v2.0", "BIS")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "BIS")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm", "BIS")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt")
LoonBestInSlot:AddItem(spec, "31109", "Head", "Stealther's Helmet of Second Sight", "Alt")

LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")
LoonBestInSlot:AddItem(spec, "29148", "Shoulders", "Blackened Leather Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "29147", "Shoulders", "Talbuk Hide Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "32665", "Back", "Crystalweave Cape", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "BIS")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor", "Alt")

LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "25697", "Bracers", "Felstalker Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "30399", "Bracers", "Nightstalker's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "27509", "Gloves", "Handgrips of Assassination", "Alt")
LoonBestInSlot:AddItem(spec, "27825", "Gloves", "Predatory Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29503", "Gloves", "Cobrascale Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28396", "Gloves", "Gloves of the Unbound", "Alt")

LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "BIS")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "BIS")
LoonBestInSlot:AddItem(spec, "27911", "Belt", "Epoch's Whispering Cinch", "Alt")
LoonBestInSlot:AddItem(spec, "31462", "Belt", "Shattrath's Champion Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust", "Alt")
LoonBestInSlot:AddItem(spec, "31288", "Feet", "The Master's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders", "Alt")
LoonBestInSlot:AddItem(spec, "30939", "Feet", "Felboar Hide Shoes", "Alt")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots", "Alt")

LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker", "Alt")
LoonBestInSlot:AddItem(spec, "27546", "Neck", "Traitor's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "BIS")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "31380", "Ring", "Acrobat's Mark of the Sha'tar", "Alt")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords", "Alt")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "28323", "Ring", "Ring of Umbral Doom", "Alt")
LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "25633", "Trinket", "Uniting Charm", "Alt")
LoonBestInSlot:AddItem(spec, "25628", "Trinket", "Ogre Mauler's Badge", "Alt")

LoonBestInSlot:AddItem(spec, "28308", "MH", "Gladiator's Cleaver", "BIS")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "29348", "MH", "The Bladefist", "Alt")
LoonBestInSlot:AddItem(spec, "28392", "MH", "Reflex Blades", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "27872", "MH", "The Harvester of Souls", "Alt")
LoonBestInSlot:AddItem(spec, "31139", "MH", "Fist of Reckoning", "Alt (OH)")

LoonBestInSlot:AddItem(spec, "27815", "Totem", "Totem of the Astral Winds", "BIS")
