local spec = LoonBestInSlot:RegisterSpec("Warlock", "Afflic", "0")
LoonBestInSlot:AddItem(spec, "32494", "Head", "Destruction Holo-gogs", "BIS")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "BIS")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl", "Alt")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "28169", "Head", "Mag'hari Ritualist's Horns", "Alt")

LoonBestInSlot:AddItem(spec, "21869", "Shoulders", "Frozen Shadoweave Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "22507", "Shoulders", "Plagueheart Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart", "BIS")

LoonBestInSlot:AddItem(spec, "23050", "Back", "Cloak of the Necropolis", "BIS")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "22731", "Back", "Cloak of the Devoured", "Alt")
LoonBestInSlot:AddItem(spec, "31140", "Back", "Cloak of Entropy", "Alt")

LoonBestInSlot:AddItem(spec, "21871", "Chest", "Frozen Shadoweave Robe", "BIS")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order", "BIS")
LoonBestInSlot:AddItem(spec, "22504", "Chest", "Plagueheart Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe", "Alt")
LoonBestInSlot:AddItem(spec, "28191", "Chest", "Mana-Etched Vestments", "Alt")
LoonBestInSlot:AddItem(spec, "28232", "Chest", "Robe of Oblivion", "Alt")

LoonBestInSlot:AddItem(spec, "21186", "Bracers", "Rockfury Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok", "BIS")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom", "Alt")

LoonBestInSlot:AddItem(spec, "31149", "Gloves", "Gloves of Pandemonium", "BIS")
LoonBestInSlot:AddItem(spec, "21585", "Gloves", "Dark Storm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "27537", "Gloves", "Gloves of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "24450", "Gloves", "Manaspark Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination", "BIS")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity", "BIS")
LoonBestInSlot:AddItem(spec, "22730", "Belt", "Eyestalk Waist Cord", "Alt")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "27795", "Belt", "Sash of Serpentra", "Alt")

LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "BIS")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist", "BIS")
LoonBestInSlot:AddItem(spec, "23070", "Legs", "Leggings of Polarity", "Alt")
LoonBestInSlot:AddItem(spec, "19133", "Legs", "Fel Infused Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27948", "Legs", "Trousers of Oblivion", "Alt")
LoonBestInSlot:AddItem(spec, "27907", "Legs", "Mana-Etched Pantaloons", "Alt")

LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots", "BIS")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice", "Alt")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers", "Alt")
LoonBestInSlot:AddItem(spec, "22508", "Feet", "Plagueheart Sandals", "Alt")

LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "BIS")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace", "BIS")
LoonBestInSlot:AddItem(spec, "21608", "Neck", "Amulet of Vek'nilash", "Alt")
LoonBestInSlot:AddItem(spec, "23057", "Neck", "Gem of Trapped Innocents", "Alt")
LoonBestInSlot:AddItem(spec, "18814", "Neck", "Choker of the Fire Lord", "Alt")

LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "BIS")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring", "BIS")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist", "Alt")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "21709", "Ring", "Ring of the Fallen God", "Alt")
LoonBestInSlot:AddItem(spec, "23031", "Ring", "Band of the Inevitable", "Alt")
LoonBestInSlot:AddItem(spec, "23025", "Ring", "Seal of the Damned", "Alt")

LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")
LoonBestInSlot:AddItem(spec, "19337", "Trinket", "The Black Book", "Alt")

LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry", "BIS")
LoonBestInSlot:AddItem(spec, "30787", "MH", "Illidari-Bane Mageblade", "Alt")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller", "Alt")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams", "Alt")

LoonBestInSlot:AddItem(spec, "22630", "2H", "Atiesh, Greatstaff of the Guardian", "BIS")

LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack", "BIS")
LoonBestInSlot:AddItem(spec, "29272", "OH", "Orb of the Soul-Eater", "Alt")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance", "BIS")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "21597", "OH", "Royal Scepter of Vek'lor", "Alt")

LoonBestInSlot:AddItem(spec, "22821", "Wand", "Doomfinger", "BIS")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk", "BIS")
LoonBestInSlot:AddItem(spec, "22820", "Wand", "Wand of Fates", "Alt")
LoonBestInSlot:AddItem(spec, "28386", "Wand", "Nether Core's Control Rod", "Alt")
