local spec = LoonBestInSlot:RegisterSpec("Warrior", "Fury", "0")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver", "BIS")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm", "Alt")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw", "Alt")
LoonBestInSlot:AddItem(spec, "31105", "Head", "Overlord's Helmet of Second Sight", "Alt")

LoonBestInSlot:AddItem(spec, "33173", "Shoulders", "Ragesteel Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde", "Alt")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets", "Alt")

LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "BIS")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "23045", "Back", "Shroud of Dominion", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "24544", "Chest", "Gladiator's Plate Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "23522", "Chest", "Ragesteel Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "28403", "Chest", "Doomplate Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30258", "Chest", "Chestplate of A'dal", "Alt")

LoonBestInSlot:AddItem(spec, "32818", "Bracers", "Veteran's Plate Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "22936", "Bracers", "Wristguards of Vengeance", "Alt")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards", "Alt")

LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "27497", "Gloves", "Doomplate Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "23520", "Gloves", "Ragesteel Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "32805", "Belt", "Veteran's Plate Belt", "BIS")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "31462", "Belt", "Shattrath's Champion Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "32793", "Feet", "Veteran's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "32648", "Feet", "Vortex Walking Boots", "BIS")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "BIS")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust", "Alt")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves", "Alt")

LoonBestInSlot:AddItem(spec, "33057", "Neck", "Veteran's Band of Triumph", "BIS")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "BIS")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker", "Alt")
LoonBestInSlot:AddItem(spec, "27546", "Neck", "Traitor's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "23038", "Ring", "Band of Unnatural Forces", "BIS")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords", "BIS")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "28323", "Ring", "Ring of Umbral Doom", "Alt")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "Alt")

LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "BIS")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")

LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw", "BIS")
LoonBestInSlot:AddItem(spec, "28437", "MH", "Drakefist Hammer", "Alt")
LoonBestInSlot:AddItem(spec, "28295", "MH", "Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "27872", "MH", "The Harvester of Souls", "Alt")
LoonBestInSlot:AddItem(spec, "29124", "MH", "Vindicator's Brand", "Alt")

LoonBestInSlot:AddItem(spec, "23542", "OH", "Fel Edged Battleaxe", "Alt")
LoonBestInSlot:AddItem(spec, "28189", "OH", "Latro's Shifting Sword", "Alt")

LoonBestInSlot:AddItem(spec, "28429", "2H", "Lionheart Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "28441", "2H", "Deep Thunder", "Alt")
LoonBestInSlot:AddItem(spec, "24550", "2H", "Gladiator's Greatsword", "Alt")
LoonBestInSlot:AddItem(spec, "28428", "2H", "Lionheart Blade", "Alt")

LoonBestInSlot:AddItem(spec, "30279", "Ranged", "Mama's Insurance", "BIS")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow", "Alt")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket", "Alt")
