local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "0")
LoonBestInSlot:AddItem(spec, "32473", "Head", "Tankatronic Goggles", "BIS")
LoonBestInSlot:AddItem(spec, "28180", "Head", "Myrmidon's Headdress", "Alt")
LoonBestInSlot:AddItem(spec, "23519", "Head", "Felsteel Helm", "Alt")
LoonBestInSlot:AddItem(spec, "27408", "Head", "Hope Bearer Helm", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28350", "Head", "Warhelm of the Bold", "Alt Mit")

LoonBestInSlot:AddItem(spec, "35411", "Shoulders", "Savage Plate Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "27847", "Shoulders", "Fanblade Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "32073", "Shoulders", "Spaulders of Dementia", "Alt")
LoonBestInSlot:AddItem(spec, "27803", "Shoulders", "Shoulderguards of the Bold", "Alt")
LoonBestInSlot:AddItem(spec, "29316", "Shoulders", "Warchief's Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape", "BIS")
LoonBestInSlot:AddItem(spec, "24253", "Back", "Cloak of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "28328", "Back", "Mithril-Bark Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "35407", "Chest", "Savage Plate Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "28205", "Chest", "Breastplate of the Bold", "Alt")
LoonBestInSlot:AddItem(spec, "28262", "Chest", "Jade-Skull Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "25819", "Chest", "Breastplate of the Warbringer", "Alt")
LoonBestInSlot:AddItem(spec, "22416", "Chest", "Dreadnaught Breastplate", "Alt")

LoonBestInSlot:AddItem(spec, "32818", "Bracers", "Veteran's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "28996", "Bracers", "Marshal's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor", "Alt")
LoonBestInSlot:AddItem(spec, "27459", "Bracers", "Vambraces of Daring", "Alt")
LoonBestInSlot:AddItem(spec, "28167", "Bracers", "Sha'tari Wrought Armguards", "Alt")
LoonBestInSlot:AddItem(spec, "30225", "Bracers", "Junior Technician 3rd Grade Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "27475", "Gloves", "Gauntlets of the Bold", "BIS")
LoonBestInSlot:AddItem(spec, "32072", "Gloves", "Gauntlets of Dissension", "Alt")
LoonBestInSlot:AddItem(spec, "23517", "Gloves", "Felsteel Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29134", "Gloves", "Gauntlets of the Chosen", "Alt")
LoonBestInSlot:AddItem(spec, "30375", "Gloves", "Gauntlets of the Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "32805", "Belt", "Veteran's Plate Belt", "BIS")
LoonBestInSlot:AddItem(spec, "28995", "Belt", "Marshal's Plate Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30032", "Belt", "Red Belt of Battle", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "27672", "Belt", "Girdle of the Immovable", "Alt")
LoonBestInSlot:AddItem(spec, "29238", "Belt", "Lion's Heart Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "31460", "Belt", "Sha'tari Vindicator's Waistguard", "Alt")
LoonBestInSlot:AddItem(spec, "25922", "Belt", "Fearless Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "22422", "Belt", "Dreadnaught Waistguard", "Alt")

LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30533", "Legs", "Vanquisher's Legplates", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "23518", "Legs", "Felsteel Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27527", "Legs", "Greaves of the Shatterer", "Alt")
LoonBestInSlot:AddItem(spec, "28175", "Legs", "Mag'hari Warlord's Legplates", "Alt")
LoonBestInSlot:AddItem(spec, "29783", "Legs", "Legguards of the Resolute Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32793", "Feet", "Veteran's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "28997", "Feet", "Marshal's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "30031", "Feet", "Red Havoc Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29239", "Feet", "Eaglecrest Warboots", "Alt")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30386", "Feet", "Bloodguard's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "22420", "Feet", "Dreadnaught Sabatons", "Alt")

LoonBestInSlot:AddItem(spec, "33066", "Neck", "Veteran's Pendant of Triumph", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35511", "Neck", "Hailstone Pendant", "Alt")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut", "Alt")
LoonBestInSlot:AddItem(spec, "29336", "Neck", "Mark of the Ravenguard", "Alt")
LoonBestInSlot:AddItem(spec, "30378", "Neck", "Thalodien's Charm", "Alt")
LoonBestInSlot:AddItem(spec, "31696", "Neck", "Natasha's Battle Chain", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "27822", "Ring", "Crystal Band of Valor", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33057", "Ring", "Veteran's Band of Triumph", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28553", "Ring", "Band of the Exorcist", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30006", "Ring", "Wind Trader's Band", "Alt")
LoonBestInSlot:AddItem(spec, "31078", "Ring", "Protector's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry", "Alt")
LoonBestInSlot:AddItem(spec, "23059", "Ring", "Ring of the Dreadnaught", "Alt")

LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27770", "Trinket", "Argussian Compass", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29181", "Trinket", "Timelapse Shard", "Alt Mit")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine", "Alt")
LoonBestInSlot:AddItem(spec, "30300", "Trinket", "Dabiri's Enigma", "Alt")
LoonBestInSlot:AddItem(spec, "28042", "Trinket", "Regal Protectorate", "Alt")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "28189", "MH", "Latro's Shifting Sword", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer", "BIS")
LoonBestInSlot:AddItem(spec, "29362", "MH", "The Sun Eater", "Alt")
LoonBestInSlot:AddItem(spec, "27980", "MH", "Terokk's Nightmace", "Alt")
LoonBestInSlot:AddItem(spec, "23577", "MH", "The Hungering Cold", "Alt")
LoonBestInSlot:AddItem(spec, "29156", "MH", "Honor's Call", "Alt")
LoonBestInSlot:AddItem(spec, "19019", "MH", "Thunderfury, Blessed Blade of the Windseeker", "Alt")
LoonBestInSlot:AddItem(spec, "31071", "MH", "Grom'tor's Charge", "Alt")

LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra", "BIS")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar", "BIS")
LoonBestInSlot:AddItem(spec, "32652", "Shield", "Ogri'la Aegis", "Alt")
LoonBestInSlot:AddItem(spec, "32082", "Shield", "The Fel Barrier", "Alt")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird", "Alt")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous", "Alt")
LoonBestInSlot:AddItem(spec, "31490", "Shield", "Netherwing Protector's Shield", "Alt")
LoonBestInSlot:AddItem(spec, "23043", "Shield", "The Face of Death", "Alt")

LoonBestInSlot:AddItem(spec, "32756", "Ranged", "Gyro-Balanced Khorium Destroyer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32645", "Ranged", "Crystalline Crossbow", "BIS")
LoonBestInSlot:AddItem(spec, "32780", "Ranged", "The Boomstick", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34622", "Ranged", "Spinesever", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "27817", "Ranged", "Starbolt Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "30227", "Ranged", "Mark V's Throwing Star", "Alt")
LoonBestInSlot:AddItem(spec, "32832", "Ranged", "Scout's Throwing Knives", "Alt")
LoonBestInSlot:AddItem(spec, "29115", "Ranged", "Consortium Blaster", "Alt")
LoonBestInSlot:AddItem(spec, "28258", "Ranged", "Nethershrike", "Alt")
LoonBestInSlot:AddItem(spec, "21459", "Ranged", "Crossbow of Imminent Doom", "Alt")
