LBIS.EnchantSources =
{
    [22530] = { Name = "Formula: Enchant Bracer - Major Defense", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [25080] = { Name = "Enchant Gloves - Superior Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [27914] = { Name = "Enchant Bracer - Fortitude", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [27984] = { Name = "Enchant Weapon - Mongoose", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [28888] = { Name = "Greater Inscription of Vengeance", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [33990] = { Name = "Enchant Chest - Major Spirit", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [33994] = { Name = "Enchant Gloves - Precise Strikes", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [34007] = { Name = "Enchant Boots - Cat's Swiftness", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [34009] = { Name = "Enchant Shield - Major Stamina", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [34207] = { Name = "Glove Reinforcements", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [37336] = { Name = "Formula: Enchant Chest - Greater Defense", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [37347] = { Name = "Formula: Enchant Cloak - Titanweave", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38371] = { Name = "Jormungar Leg Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38372] = { Name = "Nerubian Leg Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38373] = { Name = "Frosthide Leg Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38374] = { Name = "Icescale Leg Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38376] = { Name = "Heavy Borean Armor Kit", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38928] = { Name = "Scroll of Enchant Chest - Major Spirit", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38979] = { Name = "Scroll of Enchant Gloves - Exceptional Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [39003] = { Name = "Scroll of Enchant Cloak - Greater Speed", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [39006] = { Name = "Scroll of Enchant Boots - Tuskarr's Vitality", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41093] = { Name = "Hyperspeed Accelerators", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41111] = { Name = "Flexweave Underlay", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41118] = { Name = "Nitro Boosts", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41146] = { Name = "Sun Scope", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41167] = { Name = "Heartseeker Scope", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41601] = { Name = "Shining Spellthread", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41602] = { Name = "Brilliant Spellthread", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41603] = { Name = "Azure Spellthread", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41604] = { Name = "Sapphire Spellthread", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41611] = { Name = "Eternal Belt Buckle", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [41976] = { Name = "Titanium Weapon Chain", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [43097] = { Name = "Fur Lining - Attack Power", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44075] = { Name = "Arcanum of Dominance", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44129] = { Name = "Lesser Inscription of the Storm", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44131] = { Name = "Lesser Inscription of the Axe", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44133] = { Name = "Greater Inscription of the Axe", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44465] = { Name = "Scroll of Enchant Chest - Powerful Stats", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44467] = { Name = "Scroll of Enchant Weapon - Mighty Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44470] = { Name = "Scroll of Enchant Bracer - Superior Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44471] = { Name = "Formula: Enchant Cloak - Mighty Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44484] = { Name = "Enchant Gloves - Expertise", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44488] = { Name = "Enchant Gloves - Precision", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44489] = { Name = "Formula: Enchant Chest - Powerful Stats", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44508] = { Name = "Enchant Boots - Greater Spirit", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44509] = { Name = "Enchant Chest - Greater Mana Restoration", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44528] = { Name = "Enchant Boots - Greater Fortitude", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44529] = { Name = "Enchant Gloves - Major Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44575] = { Name = "Enchant Bracers - Greater Assault", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44584] = { Name = "Enchant Boots - Greater Vitality", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44588] = { Name = "Enchant Chest - Exceptional Resilience", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44589] = { Name = "Enchant Boots - Superior Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44591] = { Name = "Enchant Cloak - Titanweave", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44592] = { Name = "Enchant Gloves - Exceptional Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44598] = { Name = "Enchant Bracers - Expertise", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44623] = { Name = "Enchant Chest - Super Stats", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44625] = { Name = "Enchant Gloves - Armsman", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44633] = { Name = "Enchant Weapon - Exceptional Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44636] = { Name = "Enchant Ring - Greater Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44645] = { Name = "Enchant Ring - Assault", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44739] = { Name = "Diamond-cut Refractor Scope", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44871] = { Name = "Greater Inscription of the Axe", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44875] = { Name = "Arcanum of the Savage Gladiator", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44876] = { Name = "Arcanum of Blissful Mending", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44877] = { Name = "Arcanum of Burning Mysteries", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44878] = { Name = "Arcanum of the Stalwart Protector", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44879] = { Name = "Arcanum of Torment", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44936] = { Name = "Titanium Plating", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44944] = { Name = "Formula: Enchant Bracer - Major Stamina", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44957] = { Name = "Greater Inscription of the Gladiator", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44963] = { Name = "Earthen Leg Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [45056] = { Name = "Scroll of Enchant Staff - Greater Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [47672] = { Name = "Enchant Cloak - Mighty Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [47766] = { Name = "Enchant Chest - Greater Defense", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [47898] = { Name = "Enchant Cloak - Greater Speed", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [47900] = { Name = "Enchant Chest - Super Health", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [47901] = { Name = "Enchant Boots - Tuskarr's Vitality", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [50335] = { Name = "Greater Inscription of the Axe", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50336] = { Name = "Greater Inscription of the Crag", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50337] = { Name = "Greater Inscription of the Pinnacle", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50338] = { Name = "Greater Inscription of the Storm", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50367] = { Name = "Arcanum of Torment", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50368] = { Name = "Arcanum of Burning Mysteries", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50369] = { Name = "Arcanum of the Stalwart Protector", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50370] = { Name = "Arcanum of Blissful Mending", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [50963] = { Name = "Heavy Borean Armor Kit", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [53323] = { Name = "Rune of Swordshattering", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [53343] = { Name = "Rune of Razorice", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [53344] = { Name = "Rune of the Fallen Crusader", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [54446] = { Name = "Rune of Swordbreaking", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [54793] = { Name = "Frag Belt", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [54861] = { Name = "Nitro Boosts", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [54999] = { Name = "Hyperspeed Accelerators", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55002] = { Name = "Flexweave Underlay", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55016] = { Name = "Nitro Boosts", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55628] = { Name = "Socket Bracer", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55641] = { Name = "Socket Gloves", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55642] = { Name = "Lightweave Embroidery", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55769] = { Name = "Darkglow Embroidery", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [55777] = { Name = "Swordguard Embroidery", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [56039] = { Name = "Sanctified Spellthread", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [57683] = { Name = "Fur Lining - Attack Power", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [57690] = { Name = "Fur Lining - Stamina", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [57691] = { Name = "Fur Lining - Spell Power", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [59619] = { Name = "Enchant Weapon - Accuracy", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [59621] = { Name = "Enchant Weapon - Berserking", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [59625] = { Name = "Enchant Weapon - Black Magic", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [59636] = { Name = "Enchant Ring - Stamina", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60583] = { Name = "Jormungar Leg Reinforcements", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60609] = { Name = "Enchant Cloak - Speed", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60616] = { Name = "Enchant Bracers - Striking", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60623] = { Name = "Enchant Boots - Icewalker", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60653] = { Name = "Enchant Shield - Greater Intellect", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60663] = { Name = "Enchant Cloak - Major Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60668] = { Name = "Enchant Gloves - Crusher", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60691] = { Name = "Enchant 2H Weapon - Massacre", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60692] = { Name = "Enchant Chest - Powerful Stats", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60707] = { Name = "Enchant Weapon - Superior Potency", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60714] = { Name = "Enchant Weapon - Mighty Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60763] = { Name = "Enchant Boots - Greater Assault", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60767] = { Name = "Enchant Bracers - Superior Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [61117] = { Name = "Master's Inscription of the Axe", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [61118] = { Name = "Master's Inscription of the Crag", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [61119] = { Name = "Master's Inscription of the Pinnacle", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [61120] = { Name = "Master's Inscription of the Storm", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [62158] = { Name = "Rune of the Stoneskin Gargoyle", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [62256] = { Name = "Enchant Bracers - Major Stamina", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [62948] = { Name = "Enchant Staff - Greater Spellpower", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [63765] = { Name = "Springy Arachnoweave", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [63770] = { Name = "Reticulated Armor Webbing", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [67839] = { Name = "Mind Amplification Dish", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [70164] = { Name = "Rune of the Nerubian Carapace", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
}
