LBIS.EnchantSources =
{
    [22530] = { Name = "Formula: Enchant Bracer - Major Defense", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [27914] = { Name = "Enchant Bracer - Fortitude", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [33994] = { Name = "Enchant Gloves - Precise Strikes", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [34207] = { Name = "Glove Reinforcements", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [37336] = { Name = "Formula: Enchant Chest - Greater Defense", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [37347] = { Name = "Formula: Enchant Cloak - Titanweave", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [38373] = { Name = "Frosthide Leg Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44471] = { Name = "Formula: Enchant Cloak - Mighty Armor", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44484] = { Name = "Enchant Gloves - Expertise", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44489] = { Name = "Formula: Enchant Chest - Powerful Stats", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44528] = { Name = "Enchant Boots - Greater Fortitude", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44529] = { Name = "Enchant Gloves - Major Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [44875] = { Name = "Arcanum of the Savage Gladiator", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44878] = { Name = "Arcanum of the Stalwart Protector", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44944] = { Name = "Formula: Enchant Bracer - Major Stamina", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [44957] = { Name = "Greater Inscription of the Gladiator", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "False" },
    [47901] = { Name = "Enchant Boots - Tuskarr's Vitality", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [50963] = { Name = "Heavy Borean Armor Kit", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [53323] = { Name = "Rune of Swordshattering", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [53343] = { Name = "Rune of Razorice", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [53344] = { Name = "Rune of the Fallen Crusader", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [54446] = { Name = "Rune of Swordbreaking", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [60663] = { Name = "Enchant Cloak - Major Agility", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [62158] = { Name = "Rune of the Stoneskin Gargoyle", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
    [70164] = { Name = "Rune of the Nerubian Carapace", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"], IsSpell = "True" },
}
