LBIS.GemSources =
{
    [32410] = { Name = "Thundering Skyfire Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [34220] = { Name = "Chaotic Skyfire Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [36767] = { Name = "Solid Dragon's Eye", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [39996] = { Name = "Bold Scarlet Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [39997] = { Name = "Delicate Scarlet Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [39998] = { Name = "Runed Scarlet Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [39999] = { Name = "Bright Scarlet Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40003] = { Name = "Precise Scarlet Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40008] = { Name = "Solid Sky Sapphire", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40013] = { Name = "Smooth Autumn's Glow", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40014] = { Name = "Rigid Autumn's Glow", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40015] = { Name = "Thick Autumn's Glow", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40017] = { Name = "Quick Autumn's Glow", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40022] = { Name = "Sovereign Twilight Opal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40023] = { Name = "Shifting Twilight Opal", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40025] = { Name = "Glowing Twilight Opal", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40026] = { Name = "Purified Twilight Opal", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40027] = { Name = "Royal Twilight Opal", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40029] = { Name = "Balanced Twilight Opal", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40031] = { Name = "Regal Twilight Opal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40034] = { Name = "Guardian's Twilight Opal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40037] = { Name = "Inscribed Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40038] = { Name = "Etched Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40041] = { Name = "Fierce Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40043] = { Name = "Deadly Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40044] = { Name = "Glinting Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40046] = { Name = "Deft Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40047] = { Name = "Luminous Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40048] = { Name = "Potent Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40049] = { Name = "Veiled Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40051] = { Name = "Reckless Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40053] = { Name = "Pristine Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40055] = { Name = "Stark Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40058] = { Name = "Accurate Monarch Topaz", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40088] = { Name = "Vivid Forest Emerald", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40089] = { Name = "Enduring Forest Emerald", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40102] = { Name = "Turbid Forest Emerald", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40112] = { Name = "Delicate Cardinal Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40113] = { Name = "Runed Cardinal Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40114] = { Name = "Bright Cardinal Ruby", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40119] = { Name = "Solid Majestic Zircon", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40125] = { Name = "Rigid King's Amber", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40129] = { Name = "Sovereign Dreadstone", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40133] = { Name = "Purified Dreadstone", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40138] = { Name = "Regal Dreadstone", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40141] = { Name = "Guardian's Dreadstone", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40148] = { Name = "Glinting Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40150] = { Name = "Deft Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40153] = { Name = "Veiled Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40155] = { Name = "Reckless Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40157] = { Name = "Pristine Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40159] = { Name = "Stark Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40162] = { Name = "Accurate Ametrine", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40166] = { Name = "Vivid Eye of Zul", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40167] = { Name = "Enduring Eye of Zul", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41285] = { Name = "Chaotic Skyflare Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41333] = { Name = "Ember Skyflare Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41376] = { Name = "Revitalizing Skyflare Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41377] = { Name = "Effulgent Skyflare Diamond", DesignId = "41705", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41380] = { Name = "Austere Earthsiege Diamond", DesignId = "41797", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41396] = { Name = "Eternal Earthsiege Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41397] = { Name = "Powerful Earthsiege Diamond", DesignId = "41406", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41398] = { Name = "Relentless Earthsiege Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41400] = { Name = "Thundering Skyflare Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41401] = { Name = "Insightful Earthsiege Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41432] = { Name = "Perfect Bold Bloodstone", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41441] = { Name = "Perfect Solid Chalcedony", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41453] = { Name = "Perfect Guardian's Shadow Crystal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41458] = { Name = "Perfect Regal Shadow Crystal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41461] = { Name = "Perfect Sovereign Shadow Crystal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41464] = { Name = "Perfect Enduring Dark Jade", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41481] = { Name = "Perfect Vivid Dark Jade", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [42142] = { Name = "Bold Dragon's Eye", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [42143] = { Name = "Delicate Dragon's Eye", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [42144] = { Name = "Runed Dragon's Eye", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [42156] = { Name = "Rigid Dragon's Eye", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [42157] = { Name = "Thick Dragon's Eye", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [42702] = { Name = "Enchanted Tear", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [45880] = { Name = "Solid Stormjewel", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [49110] = { Name = "Nightmare Tear", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [55389] = { Name = "Chaotic Skyflare Diamond", DesignId = "0", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
}
