LBIS.GemSources =
{
    [40008] = { Name = "Solid Sky Sapphire", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40022] = { Name = "Sovereign Twilight Opal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40031] = { Name = "Regal Twilight Opal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40034] = { Name = "Guardian's Twilight Opal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40088] = { Name = "Vivid Forest Emerald", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40089] = { Name = "Enduring Forest Emerald", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40119] = { Name = "Solid Majestic Zircon", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40129] = { Name = "Sovereign Dreadstone", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40138] = { Name = "Regal Dreadstone", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40141] = { Name = "Guardian's Dreadstone", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40166] = { Name = "Vivid Eye of Zul", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [40167] = { Name = "Enduring Eye of Zul", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41377] = { Name = "Effulgent Skyflare Diamond", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41380] = { Name = "Austere Earthsiege Diamond", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41397] = { Name = "Powerful Earthsiege Diamond", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41441] = { Name = "Perfect Solid Chalcedony", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41453] = { Name = "Perfect Guardian's Shadow Crystal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41458] = { Name = "Perfect Regal Shadow Crystal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41461] = { Name = "Perfect Sovereign Shadow Crystal", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41464] = { Name = "Perfect Enduring Dark Jade", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [41481] = { Name = "Perfect Vivid Dark Jade", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
    [45880] = { Name = "Solid Stormjewel", DesignId = "-9999", Source = LBIS.L["undefined"], SourceLocation = LBIS.L["undefined"] },
}
