local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "5")
LoonBestInSlot:AddItem(spec, "34340", L["Head"], "Dark Conjuror's Collar", "BIS")
LoonBestInSlot:AddItem(spec, "34403", L["Head"], "Cover of Ursoc the Mighty", "Alt")
LoonBestInSlot:AddItem(spec, "34245", L["Head"], "Cover of Ursol the Wise", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "35182", L["Head"], "Hyper-Magnified Moon Specs", "Alt")
LoonBestInSlot:AddItem(spec, "34405", L["Head"], "Helm of Arcane Purity", "Alt")
LoonBestInSlot:AddItem(spec, "34339", L["Head"], "Cowl of Light's Purity", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31040", L["Head"], "Thunderheart Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "31096", L["Head"], "Helm of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34210", L["Shoulders"], "Amice of the Convoker", "BIS")
LoonBestInSlot:AddItem(spec, "34391", L["Shoulders"], "Spaulders of Devastation", "BIS")
LoonBestInSlot:AddItem(spec, "34209", L["Shoulders"], "Spaulders of Reclamation", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "31049", L["Shoulders"], "Thunderheart Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "34393", L["Shoulders"], "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", L["Shoulders"], "Shawl of Wonderment", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34242", L["Back"], "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32331", L["Back"], "Cloak of the Illidari Council", "Alt")
LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "34792", L["Back"], "Cloak of the Betrayed", "Alt")

LoonBestInSlot:AddItem(spec, "34364", L["Chest"], "Sunfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "34232", L["Chest"], "Fel Conquerer Raiments", "BIS")
LoonBestInSlot:AddItem(spec, "34399", L["Chest"], "Robes of Ghostly Hatred", "Alt")
LoonBestInSlot:AddItem(spec, "34233", L["Chest"], "Robes of Faltered Light", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31043", L["Chest"], "Thunderheart Vest", "Alt")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "34398", L["Chest"], "Utopian Tunic of Elune", "Alt")
LoonBestInSlot:AddItem(spec, "34212", L["Chest"], "Sunglow Vest", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34446", L["Bracers"], "Thunderheart Bands", "BIS")
LoonBestInSlot:AddItem(spec, "34852", L["Bracers"], "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32586", L["Bracers"], "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34344", L["Gloves"], "Handguards of Defiled Worlds", "BIS")
LoonBestInSlot:AddItem(spec, "34406", L["Gloves"], "Gloves of Tyri's Power", "Alt")
LoonBestInSlot:AddItem(spec, "34342", L["Gloves"], "Handguards of the Dawn", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34366", L["Gloves"], "Sunfire Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "34407", L["Gloves"], "Tranquil Moonlight Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "34351", L["Gloves"], "Tranquil Majesty Wraps", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31035", L["Gloves"], "Thunderheart Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34555", L["Belt"], "Thunderheart Cord", "BIS")
LoonBestInSlot:AddItem(spec, "34855", L["Belt"], "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30888", L["Belt"], "Anetheron's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "34181", L["Legs"], "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34169", L["Legs"], "Breeches of Natural Aggression", "Alt")
LoonBestInSlot:AddItem(spec, "34386", L["Legs"], "Pantaloons of Growing Strife", "Alt")
LoonBestInSlot:AddItem(spec, "34170", L["Legs"], "Pantaloons of Calming Strife", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30916", L["Legs"], "Leggings of Channeled Elements", "Alt")

LoonBestInSlot:AddItem(spec, "34572", L["Feet"], "Thunderheart Footwraps", "BIS")
LoonBestInSlot:AddItem(spec, "34858", L["Feet"], "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32239", L["Feet"], "Slippers of the Seacaller", "Alt")

LoonBestInSlot:AddItem(spec, "34359", L["Neck"], "Pendant of Sunfire", "BIS")
LoonBestInSlot:AddItem(spec, "34204", L["Neck"], "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "33281", L["Neck"], "Brooch of Nature's Mercy", "Alt")
LoonBestInSlot:AddItem(spec, "34678", L["Neck"], "Shattered Sun Pendant of Acumen", "Alt")
LoonBestInSlot:AddItem(spec, "35290", L["Neck"], "Sin'dorei Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "37928", L["Neck"], "Guardian's Pendant of Subjugation", "Alt")
LoonBestInSlot:AddItem(spec, "35132", L["Neck"], "Guardian's Pendant of Conquest", "Alt")

LoonBestInSlot:AddItem(spec, "34362", L["Ring"], "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "34230", L["Ring"], "Ring of Omnipotence", "BIS")
LoonBestInSlot:AddItem(spec, "32527", L["Ring"], "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "33497", L["Ring"], "Mana Attuned Band", "Alt")
LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "Alt")
LoonBestInSlot:AddItem(spec, "34889", L["Ring"], "Fused Nethergon Band", "Alt")

LoonBestInSlot:AddItem(spec, "34429", L["Trinket"], "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", L["Trinket"], "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "33829", L["Trinket"], "Hex Shrunken Head", "Alt")
LoonBestInSlot:AddItem(spec, "35749", L["Trinket"], "Sorcerer's Alchemist Stone", "Alt")
LoonBestInSlot:AddItem(spec, "34470", L["Trinket"], "Timbal's Focusing Crystal", "Alt")

LoonBestInSlot:AddItem(spec, "34336", L["MH"], "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "34176", L["MH"], "Reign of Misery", "Alt")
LoonBestInSlot:AddItem(spec, "35014", L["MH"], "Brutal Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35102", L["MH"], "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "34895", L["MH"], "Scryer's Blade of Focus", "Alt")
LoonBestInSlot:AddItem(spec, "32237", L["MH"], "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "34009", L["MH"], "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "33354", L["MH"], "Wub's Cursed Hexblade", "Alt")

LoonBestInSlot:AddItem(spec, "34182", L["2H"], "Grand Magister's Staff of Torrents", "BIS")
LoonBestInSlot:AddItem(spec, "32374", L["2H"], "Zhar'doom, Greatstaff of the Devourer", "Alt")
LoonBestInSlot:AddItem(spec, "34987", L["2H"], "Brutal Gladiator's Battle Staff", "Alt")

LoonBestInSlot:AddItem(spec, "34179", L["OH"], "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30872", L["OH"], "Chronicle of Dark Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "35008", L["OH"], "Brutal Gladiator's Endgame", "Alt")

LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "27518", L["Idol"], "Ivory Idol of the Moongoddess", "BIS")
