local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "5")
LoonBestInSlot:AddItem(spec, "34404", "Head", "Mask of the Fury Hunter", "BIS")
LoonBestInSlot:AddItem(spec, "34244", "Head", "Duplicitous Guise", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34999", "Head", "Brutal Gladiator's Dragonhide Helm", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34392", "Shoulders", "Demontooth Shoulderpads", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34195", "Shoulders", "Shoulderpads of Vehemence", "Transmute BIS Mit")
LoonBestInSlot:AddItem(spec, "31048", "Shoulders", "Thunderheart Pauldrons", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35001", "Shoulders", "Brutal Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "34190", "Back", "Crimson Paragon's Cover", "BIS")
LoonBestInSlot:AddItem(spec, "34241", "Back", "Cloak of Unforgivable Sin", "Alt")

LoonBestInSlot:AddItem(spec, "34211", "Chest", "Harness of Carnal Instinct", "BIS")
LoonBestInSlot:AddItem(spec, "31042", "Chest", "Thunderheart Chestguard", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34369", "Chest", "Carapace of Sun and Shadow", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "35002", "Chest", "Brutal Gladiator's Dragonhide Tunic", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34397", "Chest", "Bladed Chaos Tunic", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34906", "Chest", "Embrace of Everlasting Prowess", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34444", "Bracers", "Thunderheart Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34852", "Bracers", "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "35171", "Bracers", "Guardian's Leather Bracers", "Alt Mit")
LoonBestInSlot:AddItem(spec, "35167", "Bracers", "Guardian's Dragonhide Bracers", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34408", "Gloves", "Gloves of the Forest Drifter", "BIS")
LoonBestInSlot:AddItem(spec, "34234", "Gloves", "Shadowed Gauntlets of Paroxysm", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34911", "Gloves", "Handwraps of the Aggressor", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31034", "Gloves", "Thunderheart Gauntlets", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34370", "Gloves", "Gloves of Immortal Dusk", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "35156", "Belt", "Guardian's Leather Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34556", "Belt", "Thunderheart Waistguard", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34855", "Belt", "Belt of the Forgotten Vanquisher", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "Alt")

LoonBestInSlot:AddItem(spec, "34385", "Legs", "Leggings of the Immortal Beast", "BIS")
LoonBestInSlot:AddItem(spec, "34188", "Legs", "Leggings of the Immortal Night", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34910", "Legs", "Tameless Breeches", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31044", "Legs", "Thunderheart Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34573", "Feet", "Thunderheart Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34858", "Feet", "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32593", "Feet", "Treads of the Den Mother", "Alt")
LoonBestInSlot:AddItem(spec, "35137", "Feet", "Guardian's Dragonhide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "34178", "Neck", "Collar of the Pit Lord", "BIS")
LoonBestInSlot:AddItem(spec, "33296", "Neck", "Brooch of Deftness", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34358", "Neck", "Hard Khorium Choker", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34213", "Ring", "Ring of Hardened Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "34888", "Ring", "Ring of the Stalwart Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34361", "Ring", "Hard Khorium Band", "BIS")
LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "Alt")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt")

LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "32658", "Trinket", "Badge of Tenacity", "BIS")
LoonBestInSlot:AddItem(spec, "34473", "Trinket", "Commendation of Kael'thas", "Alt")
LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "Alt")
LoonBestInSlot:AddItem(spec, "34428", "Trinket", "Steely Naaru Sliver", "Alt")
LoonBestInSlot:AddItem(spec, "34578", "Trinket", "Battlemaster's Determination", "Alt")
LoonBestInSlot:AddItem(spec, "34472", "Trinket", "Shard of Contempt", "Alt")

LoonBestInSlot:AddItem(spec, "30883", "2H", "Pillar of Ferocity", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34198", "2H", "Stanchion of Primal Instinct", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35103", "2H", "Brutal Gladiator's Staff", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34898", "2H", "Staff of the Forest Lord", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "33509", "Idol", "Idol of Terror", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
