local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "5")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "34392", "Shoulders", "Demontooth Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "34195", "Shoulders", "Shoulderpads of Vehemence", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "31048", "Shoulders", "Thunderheart Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "35001", "Shoulders", "Brutal Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "34241", "Back", "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "Alt")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")

LoonBestInSlot:AddItem(spec, "34397", "Chest", "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", "Chest", "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34369", "Chest", "Carapace of Sun and Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "31042", "Chest", "Thunderheart Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "35002", "Chest", "Brutal Gladiator's Dragonhide Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "34444", "Bracers", "Thunderheart Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34852", "Bracers", "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "35167", "Bracers", "Guardian's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "Alt")
LoonBestInSlot:AddItem(spec, "33881", "Bracers", "Vindicator's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "35171", "Bracers", "Guardian's Leather Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "34370", "Gloves", "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "34408", "Gloves", "Gloves of the Forest Drifter", "Alt")
LoonBestInSlot:AddItem(spec, "34234", "Gloves", "Shadowed Gauntlets of Paroxysm", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31034", "Gloves", "Thunderheart Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "34998", "Gloves", "Brutal Gladiator's Dragonhide Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "34556", "Belt", "Thunderheart Waistguard", "BIS")
LoonBestInSlot:AddItem(spec, "34855", "Belt", "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "Alt")
LoonBestInSlot:AddItem(spec, "34929", "Belt", "Belt of the Silent Path", "Alt")

LoonBestInSlot:AddItem(spec, "34188", "Legs", "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "31044", "Legs", "Thunderheart Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "34385", "Legs", "Leggings of the Immortal Beast", "Alt")
LoonBestInSlot:AddItem(spec, "34928", "Legs", "Trousers of the Scryers' Retainer", "Alt")
LoonBestInSlot:AddItem(spec, "35000", "Legs", "Brutal Gladiator's Dragonhide Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "33222", "Feet", "Nyn'jah's Tabi Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34573", "Feet", "Thunderheart Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34858", "Feet", "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "34809", "Feet", "Sunrage Treads", "Alt")
LoonBestInSlot:AddItem(spec, "35137", "Feet", "Guardian's Dragonhide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "34358", "Neck", "Hard Khorium Choker", "BIS")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "34177", "Neck", "Clutch of Demise", "Alt")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "Alt")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "34189", "Ring", "Band of Ruinous Delight", "BIS")
LoonBestInSlot:AddItem(spec, "34887", "Ring", "Angelista's Revenge", "BIS")
LoonBestInSlot:AddItem(spec, "33496", "Ring", "Signet of Primal Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "34361", "Ring", "Hard Khorium Band", "Alt")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "Alt")

LoonBestInSlot:AddItem(spec, "34472", "Trinket", "Shard of Contempt", "BIS")
LoonBestInSlot:AddItem(spec, "34427", "Trinket", "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "34428", "Trinket", "Steely Naaru Sliver", "Alt")
LoonBestInSlot:AddItem(spec, "33831", "Trinket", "Berserker's Call", "Alt")

LoonBestInSlot:AddItem(spec, "34198", "2H", "Stanchion of Primal Instinct", "BIS")
LoonBestInSlot:AddItem(spec, "35103", "2H", "Brutal Gladiator's Staff", "Alt")
LoonBestInSlot:AddItem(spec, "34898", "2H", "Staff of the Forest Lord", "Alt")
LoonBestInSlot:AddItem(spec, "33716", "2H", "Vengeful Gladiator's Staff", "Alt")
LoonBestInSlot:AddItem(spec, "33465", "2H", "Staff of Primal Fury", "Alt")

LoonBestInSlot:AddItem(spec, "29390", "Idol", "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
