local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "5")
LoonBestInSlot:AddItem(spec, "34339", "Head", "Cowl of Light's Purity", "BIS")
LoonBestInSlot:AddItem(spec, "34245", "Head", "Cover of Ursol the Wise", "BIS")
LoonBestInSlot:AddItem(spec, "35183", "Head", "Wonderheal XT68 Shades", "Alt")
LoonBestInSlot:AddItem(spec, "31037", "Head", "Thunderheart Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "32329", "Head", "Cowl of Benevolence", "Alt")

LoonBestInSlot:AddItem(spec, "34209", "Shoulders", "Spaulders of Reclamation", "BIS")
LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "BIS")
LoonBestInSlot:AddItem(spec, "31047", "Shoulders", "Thunderheart Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness", "BIS")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34205", "Back", "Shroud of Redeemed Souls", "Alt")

LoonBestInSlot:AddItem(spec, "34212", "Chest", "Sunglow Vest", "BIS")
LoonBestInSlot:AddItem(spec, "34233", "Chest", "Robes of Faltered Light", "BIS")
LoonBestInSlot:AddItem(spec, "34365", "Chest", "Robe of Eternal Light", "BIS")
LoonBestInSlot:AddItem(spec, "34371", "Chest", "Leather Chestguard of the Sun", "BIS")
LoonBestInSlot:AddItem(spec, "31041", "Chest", "Thunderheart Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34445", "Bracers", "Thunderheart Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34852", "Bracers", "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30868", "Bracers", "Rejuvenating Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30871", "Bracers", "Bracers of Martyrdom", "Alt")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "32582", "Bracers", "Bracers of Renewed Life", "Alt")
LoonBestInSlot:AddItem(spec, "34602", "Bracers", "Eversong Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "BIS")
LoonBestInSlot:AddItem(spec, "34372", "Gloves", "Leather Gauntlets of the Sun", "BIS")
LoonBestInSlot:AddItem(spec, "34367", "Gloves", "Hands of Eternal Light", "BIS")
LoonBestInSlot:AddItem(spec, "34351", "Gloves", "Tranquil Majesty Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "Alt")

LoonBestInSlot:AddItem(spec, "34554", "Belt", "Thunderheart Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34855", "Belt", "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash", "Alt")
LoonBestInSlot:AddItem(spec, "32339", "Belt", "Belt of Primal Majesty", "Alt")
LoonBestInSlot:AddItem(spec, "33483", "Belt", "Life-step Belt", "Alt")

LoonBestInSlot:AddItem(spec, "34384", "Legs", "Breeches of Natural Splendor", "BIS")
LoonBestInSlot:AddItem(spec, "34169", "Legs", "Breeches of Natural Aggression", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34170", "Legs", "Pantaloons of Calming Strife", "BIS")
LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "34901", "Legs", "Grovewalker's Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "34571", "Feet", "Thunderheart Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34858", "Feet", "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light", "Alt")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "Alt")
LoonBestInSlot:AddItem(spec, "34926", "Feet", "Slippers of Dutiful Mending", "Alt")

LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34360", "Neck", "Amulet of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "34677", "Neck", "Shattered Sun Pendant of Restoration", "Alt")
LoonBestInSlot:AddItem(spec, "37929", "Neck", "Guardian's Pendant of Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "34184", "Neck", "Brooch of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "35291", "Neck", "Sin'dorei Pendant of Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "35134", "Neck", "Guardian's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34166", "Ring", "Band of Lucent Beams", "BIS")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "34363", "Ring", "Ring of Flowing Life", "Alt")
LoonBestInSlot:AddItem(spec, "35733", "Ring", "Ring of Harmonic Beauty", "Alt")
LoonBestInSlot:AddItem(spec, "34625", "Ring", "Kharmaa's Ring of Fate", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "35750", "Trinket", "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "34430", "Trinket", "Glimmering Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")

LoonBestInSlot:AddItem(spec, "34335", "MH", "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34199", "MH", "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35082", "MH", "Brutal Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34896", "MH", "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34337", "2H", "Golden Staff of the Sin'dorei", "BIS")
LoonBestInSlot:AddItem(spec, "30908", "2H", "Apostle of Argus", "Alt")
LoonBestInSlot:AddItem(spec, "34608", "2H", "Rod of the Blazing Light", "Alt")

LoonBestInSlot:AddItem(spec, "34206", "OH", "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "35074", "OH", "Brutal Gladiator's Reprieve", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
