local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "5")
LoonBestInSlot:AddItem(spec, "34339", L["Head"], "Cowl of Light's Purity", "BIS")
LoonBestInSlot:AddItem(spec, "34245", L["Head"], "Cover of Ursol the Wise", "BIS")
LoonBestInSlot:AddItem(spec, "35183", L["Head"], "Wonderheal XT68 Shades", "Alt")
LoonBestInSlot:AddItem(spec, "31037", L["Head"], "Thunderheart Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31096", L["Head"], "Helm of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "32329", L["Head"], "Cowl of Benevolence", "Alt")

LoonBestInSlot:AddItem(spec, "34209", L["Shoulders"], "Spaulders of Reclamation", "BIS")
LoonBestInSlot:AddItem(spec, "34202", L["Shoulders"], "Shawl of Wonderment", "BIS")
LoonBestInSlot:AddItem(spec, "31047", L["Shoulders"], "Thunderheart Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "32337", L["Back"], "Shroud of Forgiveness", "BIS")
LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34205", L["Back"], "Shroud of Redeemed Souls", "Alt")

LoonBestInSlot:AddItem(spec, "34212", L["Chest"], "Sunglow Vest", "BIS")
LoonBestInSlot:AddItem(spec, "34233", L["Chest"], "Robes of Faltered Light", "BIS")
LoonBestInSlot:AddItem(spec, "34365", L["Chest"], "Robe of Eternal Light", "BIS")
LoonBestInSlot:AddItem(spec, "34371", L["Chest"], "Leather Chestguard of the Sun", "BIS")
LoonBestInSlot:AddItem(spec, "31041", L["Chest"], "Thunderheart Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34445", L["Bracers"], "Thunderheart Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34852", L["Bracers"], "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30868", L["Bracers"], "Rejuvenating Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30871", L["Bracers"], "Bracers of Martyrdom", "Alt")
LoonBestInSlot:AddItem(spec, "32584", L["Bracers"], "Swiftheal Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "32582", L["Bracers"], "Bracers of Renewed Life", "Alt")
LoonBestInSlot:AddItem(spec, "34602", L["Bracers"], "Eversong Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "34342", L["Gloves"], "Handguards of the Dawn", "BIS")
LoonBestInSlot:AddItem(spec, "34372", L["Gloves"], "Leather Gauntlets of the Sun", "BIS")
LoonBestInSlot:AddItem(spec, "34367", L["Gloves"], "Hands of Eternal Light", "BIS")
LoonBestInSlot:AddItem(spec, "34351", L["Gloves"], "Tranquil Majesty Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "Alt")

LoonBestInSlot:AddItem(spec, "34554", L["Belt"], "Thunderheart Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34855", L["Belt"], "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30895", L["Belt"], "Angelista's Sash", "Alt")
LoonBestInSlot:AddItem(spec, "32339", L["Belt"], "Belt of Primal Majesty", "Alt")
LoonBestInSlot:AddItem(spec, "33483", L["Belt"], "Life-step Belt", "Alt")

LoonBestInSlot:AddItem(spec, "34384", L["Legs"], "Breeches of Natural Splendor", "BIS")
LoonBestInSlot:AddItem(spec, "34169", L["Legs"], "Breeches of Natural Aggression", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34170", L["Legs"], "Pantaloons of Calming Strife", "BIS")
LoonBestInSlot:AddItem(spec, "30912", L["Legs"], "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "34901", L["Legs"], "Grovewalker's Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "34571", L["Feet"], "Thunderheart Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34858", L["Feet"], "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32609", L["Feet"], "Boots of the Divine Light", "Alt")
LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "Alt")
LoonBestInSlot:AddItem(spec, "34926", L["Feet"], "Slippers of Dutiful Mending", "Alt")

LoonBestInSlot:AddItem(spec, "33281", L["Neck"], "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34360", L["Neck"], "Amulet of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "34677", L["Neck"], "Shattered Sun Pendant of Restoration", "Alt")
LoonBestInSlot:AddItem(spec, "37929", L["Neck"], "Guardian's Pendant of Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "34184", L["Neck"], "Brooch of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "35291", L["Neck"], "Sin'dorei Pendant of Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "35134", L["Neck"], "Guardian's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34166", L["Ring"], "Band of Lucent Beams", "BIS")
LoonBestInSlot:AddItem(spec, "29309", L["Ring"], "Band of the Eternal Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "30110", L["Ring"], "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "34363", L["Ring"], "Ring of Flowing Life", "Alt")
LoonBestInSlot:AddItem(spec, "35733", L["Ring"], "Ring of Harmonic Beauty", "Alt")
LoonBestInSlot:AddItem(spec, "34625", L["Ring"], "Kharmaa's Ring of Fate", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "35750", L["Trinket"], "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "34430", L["Trinket"], "Glimmering Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")

LoonBestInSlot:AddItem(spec, "34335", L["MH"], "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34199", L["MH"], "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35082", L["MH"], "Brutal Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34896", L["MH"], "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34337", L["2H"], "Golden Staff of the Sin'dorei", "BIS")
LoonBestInSlot:AddItem(spec, "30908", L["2H"], "Apostle of Argus", "Alt")
LoonBestInSlot:AddItem(spec, "34608", L["2H"], "Rod of the Blazing Light", "Alt")

LoonBestInSlot:AddItem(spec, "34206", L["OH"], "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "30911", L["OH"], "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "35074", L["OH"], "Brutal Gladiator's Reprieve", "Alt")

LoonBestInSlot:AddItem(spec, "27886", L["Idol"], "Idol of the Emerald Queen", "BIS")
LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
