local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "5")
LoonBestInSlot:AddItem(spec, "34404", L["Head"], "Mask of the Fury Hunter", "BIS")
LoonBestInSlot:AddItem(spec, "34244", L["Head"], "Duplicitous Guise", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34999", L["Head"], "Brutal Gladiator's Dragonhide Helm", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34392", L["Shoulders"], "Demontooth Shoulderpads", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34195", L["Shoulders"], "Shoulderpads of Vehemence", "Transmute BIS Mit")
LoonBestInSlot:AddItem(spec, "31048", L["Shoulders"], "Thunderheart Pauldrons", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35001", L["Shoulders"], "Brutal Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "34190", L["Back"], "Crimson Paragon's Cover", "BIS")
LoonBestInSlot:AddItem(spec, "34241", L["Back"], "Cloak of Unforgivable Sin", "Alt")

LoonBestInSlot:AddItem(spec, "34211", L["Chest"], "Harness of Carnal Instinct", "BIS")
LoonBestInSlot:AddItem(spec, "31042", L["Chest"], "Thunderheart Chestguard", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34369", L["Chest"], "Carapace of Sun and Shadow", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "35002", L["Chest"], "Brutal Gladiator's Dragonhide Tunic", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34397", L["Chest"], "Bladed Chaos Tunic", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34906", L["Chest"], "Embrace of Everlasting Prowess", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34444", L["Bracers"], "Thunderheart Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34852", L["Bracers"], "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "35171", L["Bracers"], "Guardian's Leather Bracers", "Alt Mit")
LoonBestInSlot:AddItem(spec, "35167", L["Bracers"], "Guardian's Dragonhide Bracers", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34408", L["Gloves"], "Gloves of the Forest Drifter", "BIS")
LoonBestInSlot:AddItem(spec, "34234", L["Gloves"], "Shadowed Gauntlets of Paroxysm", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34911", L["Gloves"], "Handwraps of the Aggressor", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31034", L["Gloves"], "Thunderheart Gauntlets", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34370", L["Gloves"], "Gloves of Immortal Dusk", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "35156", L["Belt"], "Guardian's Leather Belt", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34556", L["Belt"], "Thunderheart Waistguard", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34855", L["Belt"], "Belt of the Forgotten Vanquisher", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "Alt")

LoonBestInSlot:AddItem(spec, "34385", L["Legs"], "Leggings of the Immortal Beast", "BIS")
LoonBestInSlot:AddItem(spec, "34188", L["Legs"], "Leggings of the Immortal Night", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34910", L["Legs"], "Tameless Breeches", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31044", L["Legs"], "Thunderheart Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34573", L["Feet"], "Thunderheart Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34858", L["Feet"], "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32593", L["Feet"], "Treads of the Den Mother", "Alt")
LoonBestInSlot:AddItem(spec, "35137", L["Feet"], "Guardian's Dragonhide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "34178", L["Neck"], "Collar of the Pit Lord", "BIS")
LoonBestInSlot:AddItem(spec, "33296", L["Neck"], "Brooch of Deftness", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34358", L["Neck"], "Hard Khorium Choker", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34213", L["Ring"], "Ring of Hardened Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "34888", L["Ring"], "Ring of the Stalwart Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34361", L["Ring"], "Hard Khorium Band", "BIS")
LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "Alt")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "Alt")

LoonBestInSlot:AddItem(spec, "32501", L["Trinket"], "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "32658", L["Trinket"], "Badge of Tenacity", "BIS")
LoonBestInSlot:AddItem(spec, "34473", L["Trinket"], "Commendation of Kael'thas", "Alt")
LoonBestInSlot:AddItem(spec, "28528", L["Trinket"], "Moroes' Lucky Pocket Watch", "Alt")
LoonBestInSlot:AddItem(spec, "34428", L["Trinket"], "Steely Naaru Sliver", "Alt")
LoonBestInSlot:AddItem(spec, "34578", L["Trinket"], "Battlemaster's Determination", "Alt")
LoonBestInSlot:AddItem(spec, "34472", L["Trinket"], "Shard of Contempt", "Alt")

LoonBestInSlot:AddItem(spec, "30883", L["2H"], "Pillar of Ferocity", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34198", L["2H"], "Stanchion of Primal Instinct", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35103", L["2H"], "Brutal Gladiator's Staff", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34898", L["2H"], "Staff of the Forest Lord", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "33509", L["Idol"], "Idol of Terror", "BIS")
LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
