local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "5")
LoonBestInSlot:AddItem(spec, "34340", "Head", "Dark Conjuror's Collar", "BIS")
LoonBestInSlot:AddItem(spec, "34403", "Head", "Cover of Ursoc the Mighty", "Alt")
LoonBestInSlot:AddItem(spec, "34245", "Head", "Cover of Ursol the Wise", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "35182", "Head", "Hyper-Magnified Moon Specs", "Alt")
LoonBestInSlot:AddItem(spec, "34405", "Head", "Helm of Arcane Purity", "Alt")
LoonBestInSlot:AddItem(spec, "34339", "Head", "Cowl of Light's Purity", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31040", "Head", "Thunderheart Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34210", "Shoulders", "Amice of the Convoker", "BIS")
LoonBestInSlot:AddItem(spec, "34391", "Shoulders", "Spaulders of Devastation", "BIS")
LoonBestInSlot:AddItem(spec, "34209", "Shoulders", "Spaulders of Reclamation", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "31049", "Shoulders", "Thunderheart Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "34393", "Shoulders", "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "Alt")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "34792", "Back", "Cloak of the Betrayed", "Alt")

LoonBestInSlot:AddItem(spec, "34364", "Chest", "Sunfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "34232", "Chest", "Fel Conquerer Raiments", "BIS")
LoonBestInSlot:AddItem(spec, "34399", "Chest", "Robes of Ghostly Hatred", "Alt")
LoonBestInSlot:AddItem(spec, "34233", "Chest", "Robes of Faltered Light", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31043", "Chest", "Thunderheart Vest", "Alt")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "34398", "Chest", "Utopian Tunic of Elune", "Alt")
LoonBestInSlot:AddItem(spec, "34212", "Chest", "Sunglow Vest", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34446", "Bracers", "Thunderheart Bands", "BIS")
LoonBestInSlot:AddItem(spec, "34852", "Bracers", "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34344", "Gloves", "Handguards of Defiled Worlds", "BIS")
LoonBestInSlot:AddItem(spec, "34406", "Gloves", "Gloves of Tyri's Power", "Alt")
LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34366", "Gloves", "Sunfire Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "34407", "Gloves", "Tranquil Moonlight Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "34351", "Gloves", "Tranquil Majesty Wraps", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31035", "Gloves", "Thunderheart Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34555", "Belt", "Thunderheart Cord", "BIS")
LoonBestInSlot:AddItem(spec, "34855", "Belt", "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "34181", "Legs", "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34169", "Legs", "Breeches of Natural Aggression", "Alt")
LoonBestInSlot:AddItem(spec, "34386", "Legs", "Pantaloons of Growing Strife", "Alt")
LoonBestInSlot:AddItem(spec, "34170", "Legs", "Pantaloons of Calming Strife", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")

LoonBestInSlot:AddItem(spec, "34572", "Feet", "Thunderheart Footwraps", "BIS")
LoonBestInSlot:AddItem(spec, "34858", "Feet", "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "Alt")

LoonBestInSlot:AddItem(spec, "34359", "Neck", "Pendant of Sunfire", "BIS")
LoonBestInSlot:AddItem(spec, "34204", "Neck", "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "Alt")
LoonBestInSlot:AddItem(spec, "34678", "Neck", "Shattered Sun Pendant of Acumen", "Alt")
LoonBestInSlot:AddItem(spec, "35290", "Neck", "Sin'dorei Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "37928", "Neck", "Guardian's Pendant of Subjugation", "Alt")
LoonBestInSlot:AddItem(spec, "35132", "Neck", "Guardian's Pendant of Conquest", "Alt")

LoonBestInSlot:AddItem(spec, "34362", "Ring", "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "34230", "Ring", "Ring of Omnipotence", "BIS")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "33497", "Ring", "Mana Attuned Band", "Alt")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "Alt")
LoonBestInSlot:AddItem(spec, "34889", "Ring", "Fused Nethergon Band", "Alt")

LoonBestInSlot:AddItem(spec, "34429", "Trinket", "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "33829", "Trinket", "Hex Shrunken Head", "Alt")
LoonBestInSlot:AddItem(spec, "35749", "Trinket", "Sorcerer's Alchemist Stone", "Alt")
LoonBestInSlot:AddItem(spec, "34470", "Trinket", "Timbal's Focusing Crystal", "Alt")

LoonBestInSlot:AddItem(spec, "34336", "MH", "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "34176", "MH", "Reign of Misery", "Alt")
LoonBestInSlot:AddItem(spec, "35014", "MH", "Brutal Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35102", "MH", "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "34895", "MH", "Scryer's Blade of Focus", "Alt")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "33354", "MH", "Wub's Cursed Hexblade", "Alt")

LoonBestInSlot:AddItem(spec, "34182", "2H", "Grand Magister's Staff of Torrents", "BIS")
LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "Alt")
LoonBestInSlot:AddItem(spec, "34987", "2H", "Brutal Gladiator's Battle Staff", "Alt")

LoonBestInSlot:AddItem(spec, "34179", "OH", "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "35008", "OH", "Brutal Gladiator's Endgame", "Alt")

LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "27518", "Idol", "Ivory Idol of the Moongoddess", "BIS")
