local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "5")
LoonBestInSlot:AddItem(spec, "8345", L["Head"], "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "34392", L["Shoulders"], "Demontooth Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "34195", L["Shoulders"], "Shoulderpads of Vehemence", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "31048", L["Shoulders"], "Thunderheart Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "35001", L["Shoulders"], "Brutal Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "34241", L["Back"], "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "Alt")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "Alt")

LoonBestInSlot:AddItem(spec, "34397", L["Chest"], "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", L["Chest"], "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34369", L["Chest"], "Carapace of Sun and Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "31042", L["Chest"], "Thunderheart Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "35002", L["Chest"], "Brutal Gladiator's Dragonhide Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "34444", L["Bracers"], "Thunderheart Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34852", L["Bracers"], "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "35167", L["Bracers"], "Guardian's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "Alt")
LoonBestInSlot:AddItem(spec, "33881", L["Bracers"], "Vindicator's Dragonhide Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "35171", L["Bracers"], "Guardian's Leather Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "34370", L["Gloves"], "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "34408", L["Gloves"], "Gloves of the Forest Drifter", "Alt")
LoonBestInSlot:AddItem(spec, "34234", L["Gloves"], "Shadowed Gauntlets of Paroxysm", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "31034", L["Gloves"], "Thunderheart Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "34998", L["Gloves"], "Brutal Gladiator's Dragonhide Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "34556", L["Belt"], "Thunderheart Waistguard", "BIS")
LoonBestInSlot:AddItem(spec, "34855", L["Belt"], "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "Alt")
LoonBestInSlot:AddItem(spec, "34929", L["Belt"], "Belt of the Silent Path", "Alt")

LoonBestInSlot:AddItem(spec, "34188", L["Legs"], "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "31044", L["Legs"], "Thunderheart Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "34385", L["Legs"], "Leggings of the Immortal Beast", "Alt")
LoonBestInSlot:AddItem(spec, "34928", L["Legs"], "Trousers of the Scryers' Retainer", "Alt")
LoonBestInSlot:AddItem(spec, "35000", L["Legs"], "Brutal Gladiator's Dragonhide Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "33222", L["Feet"], "Nyn'jah's Tabi Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34573", L["Feet"], "Thunderheart Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34858", L["Feet"], "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "34809", L["Feet"], "Sunrage Treads", "Alt")
LoonBestInSlot:AddItem(spec, "35137", L["Feet"], "Guardian's Dragonhide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "34358", L["Neck"], "Hard Khorium Choker", "BIS")
LoonBestInSlot:AddItem(spec, "24114", L["Neck"], "Braided Eternium Chain", "BIS")
LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "34177", L["Neck"], "Clutch of Demise", "Alt")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "Alt")

LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "34189", L["Ring"], "Band of Ruinous Delight", "BIS")
LoonBestInSlot:AddItem(spec, "34887", L["Ring"], "Angelista's Revenge", "BIS")
LoonBestInSlot:AddItem(spec, "33496", L["Ring"], "Signet of Primal Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "34361", L["Ring"], "Hard Khorium Band", "Alt")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "Alt")

LoonBestInSlot:AddItem(spec, "34472", L["Trinket"], "Shard of Contempt", "BIS")
LoonBestInSlot:AddItem(spec, "34427", L["Trinket"], "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "34428", L["Trinket"], "Steely Naaru Sliver", "Alt")
LoonBestInSlot:AddItem(spec, "33831", L["Trinket"], "Berserker's Call", "Alt")

LoonBestInSlot:AddItem(spec, "34198", L["2H"], "Stanchion of Primal Instinct", "BIS")
LoonBestInSlot:AddItem(spec, "35103", L["2H"], "Brutal Gladiator's Staff", "Alt")
LoonBestInSlot:AddItem(spec, "34898", L["2H"], "Staff of the Forest Lord", "Alt")
LoonBestInSlot:AddItem(spec, "33716", L["2H"], "Vengeful Gladiator's Staff", "Alt")
LoonBestInSlot:AddItem(spec, "33465", L["2H"], "Staff of Primal Fury", "Alt")

LoonBestInSlot:AddItem(spec, "29390", L["Idol"], "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
