local spec = LoonBestInSlot:RegisterSpec("Hunter", "Survival", "5")
LoonBestInSlot:AddItem(spec, "34333", "Head", "Coif of Alleria", "BIS")
LoonBestInSlot:AddItem(spec, "34244", "Head", "Duplicitous Guise", "BIS")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "Alt")
LoonBestInSlot:AddItem(spec, "31003", "Head", "Gronnstalker's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "33666", "Head", "Vengeful Gladiator's Chain Helm", "Alt")

LoonBestInSlot:AddItem(spec, "31006", "Shoulders", "Gronnstalker's Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34194", "Shoulders", "Mantle of the Golden Forest", "Alt")
LoonBestInSlot:AddItem(spec, "34195", "Shoulders", "Shoulderpads of Vehemence", "Alt")

LoonBestInSlot:AddItem(spec, "34241", "Back", "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "33484", "Back", "Dory's Embrace", "Alt")
LoonBestInSlot:AddItem(spec, "33590", "Back", "Cloak of Fiends", "Alt")

LoonBestInSlot:AddItem(spec, "34397", "Chest", "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", "Chest", "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34228", "Chest", "Vicious Hawkstrider Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "34373", "Chest", "Embrace of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "34369", "Chest", "Carapace of Sun and Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "31004", "Chest", "Gronnstalker's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "34443", "Bracers", "Gronnstalker's Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34851", "Bracers", "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "Alt")
LoonBestInSlot:AddItem(spec, "33540", "Bracers", "Master Assassin Wristwraps", "Alt")
LoonBestInSlot:AddItem(spec, "33529", "Bracers", "Steadying Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32251", "Bracers", "Wraps of Precise Flight", "Alt")

LoonBestInSlot:AddItem(spec, "34343", "Gloves", "Thalassian Ranger Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34370", "Gloves", "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "31001", "Gloves", "Gronnstalker's Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "30140", "Gloves", "Rift Stalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "34549", "Belt", "Gronnstalker's Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34854", "Belt", "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "BIS")
LoonBestInSlot:AddItem(spec, "32346", "Belt", "Boneweave Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "34188", "Legs", "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "34168", "Legs", "Starstalker Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "34928", "Legs", "Trousers of the Scryers' Retainer", "Alt")
LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30142", "Legs", "Rift Stalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "34570", "Feet", "Gronnstalker's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34857", "Feet", "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "Alt")
LoonBestInSlot:AddItem(spec, "30880", "Feet", "Quickstrider Moccasins", "Alt")

LoonBestInSlot:AddItem(spec, "34177", "Neck", "Clutch of Demise", "BIS")
LoonBestInSlot:AddItem(spec, "34358", "Neck", "Hard Khorium Choker", "Alt")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "Alt")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")

LoonBestInSlot:AddItem(spec, "34361", "Ring", "Hard Khorium Band", "BIS")
LoonBestInSlot:AddItem(spec, "34887", "Ring", "Angelista's Revenge", "BIS")
LoonBestInSlot:AddItem(spec, "33496", "Ring", "Signet of Primal Wrath", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "34189", "Ring", "Band of Ruinous Delight", "Alt")
LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "Alt")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt")

LoonBestInSlot:AddItem(spec, "34427", "Trinket", "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")

LoonBestInSlot:AddItem(spec, "34331", "MH", "Hand of the Deceiver", "BIS")
LoonBestInSlot:AddItem(spec, "34197", "MH", "Shiv of Exsanguination", "BIS")
LoonBestInSlot:AddItem(spec, "34329", "MH", "Crux of the Apocalypse", "Alt")
LoonBestInSlot:AddItem(spec, "34893", "MH", "Vanir's Right Fist of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "33389", "MH", "Dagger of Bad Mojo", "Alt")
LoonBestInSlot:AddItem(spec, "30901", "MH", "Boundless Agony", "Alt")
LoonBestInSlot:AddItem(spec, "33737", "MH", "Vengeful Gladiator's Right Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "Alt")

LoonBestInSlot:AddItem(spec, "34203", "OH", "Grip of Mannoroth", "BIS")
LoonBestInSlot:AddItem(spec, "34951", "OH", "Vanir's Left Fist of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "34165", "OH", "Fang of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "34346", "OH", "Mounting Vengeance", "Alt")
LoonBestInSlot:AddItem(spec, "33705", "OH", "Vengeful Gladiator's Left Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "30865", "OH", "Tracker's Blade", "Alt")

LoonBestInSlot:AddItem(spec, "34183", "2H", "Shivering Felspine", "BIS")
LoonBestInSlot:AddItem(spec, "34247", "2H", "Apolyon, the Soul-Render", "Alt")
LoonBestInSlot:AddItem(spec, "32248", "2H", "Halberd of Desolation", "BIS")

LoonBestInSlot:AddItem(spec, "34334", "Ranged", "Thori'dal, the Stars' Fury", "BIS")
LoonBestInSlot:AddItem(spec, "34196", "Ranged", "Golden Bow of Quel'Thalas", "BIS")
LoonBestInSlot:AddItem(spec, "30906", "Ranged", "Bristleblitz Striker", "Alt")
LoonBestInSlot:AddItem(spec, "34530", "Ranged", "Vengeful Gladiator's Rifle", "Alt")
