local spec = LoonBestInSlot:RegisterSpec("Hunter", "Survival", "5")
LoonBestInSlot:AddItem(spec, "34333", L["Head"], "Coif of Alleria", "BIS")
LoonBestInSlot:AddItem(spec, "34244", L["Head"], "Duplicitous Guise", "BIS")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "Alt")
LoonBestInSlot:AddItem(spec, "31003", L["Head"], "Gronnstalker's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "33666", L["Head"], "Vengeful Gladiator's Chain Helm", "Alt")

LoonBestInSlot:AddItem(spec, "31006", L["Shoulders"], "Gronnstalker's Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34194", L["Shoulders"], "Mantle of the Golden Forest", "Alt")
LoonBestInSlot:AddItem(spec, "34195", L["Shoulders"], "Shoulderpads of Vehemence", "Alt")

LoonBestInSlot:AddItem(spec, "34241", L["Back"], "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "33484", L["Back"], "Dory's Embrace", "Alt")
LoonBestInSlot:AddItem(spec, "33590", L["Back"], "Cloak of Fiends", "Alt")

LoonBestInSlot:AddItem(spec, "34397", L["Chest"], "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", L["Chest"], "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34228", L["Chest"], "Vicious Hawkstrider Hauberk", "BIS")
LoonBestInSlot:AddItem(spec, "34373", L["Chest"], "Embrace of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "34369", L["Chest"], "Carapace of Sun and Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "31004", L["Chest"], "Gronnstalker's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "34443", L["Bracers"], "Gronnstalker's Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34851", L["Bracers"], "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "Alt")
LoonBestInSlot:AddItem(spec, "33540", L["Bracers"], "Master Assassin Wristwraps", "Alt")
LoonBestInSlot:AddItem(spec, "33529", L["Bracers"], "Steadying Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32251", L["Bracers"], "Wraps of Precise Flight", "Alt")

LoonBestInSlot:AddItem(spec, "34343", L["Gloves"], "Thalassian Ranger Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34370", L["Gloves"], "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "31001", L["Gloves"], "Gronnstalker's Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31094", L["Gloves"], "Gloves of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "30140", L["Gloves"], "Rift Stalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30241", L["Gloves"], "Gloves of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "34549", L["Belt"], "Gronnstalker's Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34854", L["Belt"], "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30879", L["Belt"], "Don Alejandro's Money Belt", "BIS")
LoonBestInSlot:AddItem(spec, "32346", L["Belt"], "Boneweave Girdle", "Alt")

LoonBestInSlot:AddItem(spec, "34188", L["Legs"], "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "34168", L["Legs"], "Starstalker Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "34928", L["Legs"], "Trousers of the Scryers' Retainer", "Alt")
LoonBestInSlot:AddItem(spec, "30900", L["Legs"], "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30142", L["Legs"], "Rift Stalker Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30247", L["Legs"], "Leggings of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "34570", L["Feet"], "Gronnstalker's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34857", L["Feet"], "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "32510", L["Feet"], "Softstep Boots of Tracking", "Alt")
LoonBestInSlot:AddItem(spec, "30880", L["Feet"], "Quickstrider Moccasins", "Alt")

LoonBestInSlot:AddItem(spec, "34177", L["Neck"], "Clutch of Demise", "BIS")
LoonBestInSlot:AddItem(spec, "34358", L["Neck"], "Hard Khorium Choker", "Alt")
LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "Alt")
LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "Alt")

LoonBestInSlot:AddItem(spec, "34361", L["Ring"], "Hard Khorium Band", "BIS")
LoonBestInSlot:AddItem(spec, "34887", L["Ring"], "Angelista's Revenge", "BIS")
LoonBestInSlot:AddItem(spec, "33496", L["Ring"], "Signet of Primal Wrath", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "34189", L["Ring"], "Band of Ruinous Delight", "Alt")
LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "Alt")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "Alt")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "Alt")

LoonBestInSlot:AddItem(spec, "34427", L["Trinket"], "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "Alt")

LoonBestInSlot:AddItem(spec, "34331", L["MH"], "Hand of the Deceiver", "BIS")
LoonBestInSlot:AddItem(spec, "34197", L["MH"], "Shiv of Exsanguination", "BIS")
LoonBestInSlot:AddItem(spec, "34329", L["MH"], "Crux of the Apocalypse", "Alt")
LoonBestInSlot:AddItem(spec, "34893", L["MH"], "Vanir's Right Fist of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "33389", L["MH"], "Dagger of Bad Mojo", "Alt")
LoonBestInSlot:AddItem(spec, "30901", L["MH"], "Boundless Agony", "Alt")
LoonBestInSlot:AddItem(spec, "33737", L["MH"], "Vengeful Gladiator's Right Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "32944", L["MH"], "Talon of the Phoenix", "Alt")

LoonBestInSlot:AddItem(spec, "34203", L["OH"], "Grip of Mannoroth", "BIS")
LoonBestInSlot:AddItem(spec, "34951", L["OH"], "Vanir's Left Fist of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "34165", L["OH"], "Fang of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "34346", L["OH"], "Mounting Vengeance", "Alt")
LoonBestInSlot:AddItem(spec, "33705", L["OH"], "Vengeful Gladiator's Left Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "30865", L["OH"], "Tracker's Blade", "Alt")

LoonBestInSlot:AddItem(spec, "34183", L["2H"], "Shivering Felspine", "BIS")
LoonBestInSlot:AddItem(spec, "34247", L["2H"], "Apolyon, the Soul-Render", "Alt")
LoonBestInSlot:AddItem(spec, "32248", L["2H"], "Halberd of Desolation", "BIS")

LoonBestInSlot:AddItem(spec, "34334", L["Ranged"], "Thori'dal, the Stars' Fury", "BIS")
LoonBestInSlot:AddItem(spec, "34196", L["Ranged"], "Golden Bow of Quel'Thalas", "BIS")
LoonBestInSlot:AddItem(spec, "30906", L["Ranged"], "Bristleblitz Striker", "Alt")
LoonBestInSlot:AddItem(spec, "34530", L["Ranged"], "Vengeful Gladiator's Rifle", "Alt")
