local spec = LoonBestInSlot:RegisterSpec("Mage", "Arcane", "5")
LoonBestInSlot:AddItem(spec, "30206", "Head", "Cowl of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "34340", "Head", "Dark Conjuror's Collar", "Alt")
LoonBestInSlot:AddItem(spec, "34847", "Head", "Annihilator Holo-Gogs", "Alt")

LoonBestInSlot:AddItem(spec, "30210", "Shoulders", "Mantle of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "34393", "Shoulders", "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34210", "Shoulders", "Amice of the Convoker", "Alt")

LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34399", "Chest", "Robes of Ghostly Hatred", "BIS")
LoonBestInSlot:AddItem(spec, "34233", "Chest", "Robes of Faltered Light", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34364", "Chest", "Sunfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30196", "Chest", "Robes of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "31057", "Chest", "Robes of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34447", "Bracers", "Bracers of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "34852", "Bracers", "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34406", "Gloves", "Gloves of Tyri's Power", "BIS")
LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "30205", "Gloves", "Gloves of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "34344", "Gloves", "Handguards of Defiled Worlds", "Alt")
LoonBestInSlot:AddItem(spec, "34366", "Gloves", "Sunfire Handwraps", "Alt")

LoonBestInSlot:AddItem(spec, "34557", "Belt", "Belt of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "34855", "Belt", "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "34181", "Legs", "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34386", "Legs", "Pantaloons of Growing Strife", "Alt")
LoonBestInSlot:AddItem(spec, "34170", "Legs", "Pantaloons of Calming Strife", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "34937", "Legs", "Corrupted Soulcloth Pantaloons", "Alt")

LoonBestInSlot:AddItem(spec, "34574", "Feet", "Boots of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "34858", "Feet", "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "Alt")
LoonBestInSlot:AddItem(spec, "34919", "Feet", "Boots of Incantations", "Alt")

LoonBestInSlot:AddItem(spec, "34204", "Neck", "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34359", "Neck", "Pendant of Sunfire", "Alt")
LoonBestInSlot:AddItem(spec, "37928", "Neck", "Guardian's Pendant of Subjugation", "Alt")

LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "34362", "Ring", "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "34230", "Ring", "Ring of Omnipotence", "Alt")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "33497", "Ring", "Mana Attuned Band", "Alt")

LoonBestInSlot:AddItem(spec, "34429", "Trinket", "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "33829", "Trinket", "Hex Shrunken Head", "BIS")
LoonBestInSlot:AddItem(spec, "32488", "Trinket", "Ashtongue Talisman of Insight", "Alt")

LoonBestInSlot:AddItem(spec, "34336", "MH", "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "34182", "MH", "Grand Magister's Staff of Torrents", "Alt")
LoonBestInSlot:AddItem(spec, "32374", "MH", "Zhar'doom, Greatstaff of the Devourer", "Alt")
LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos", "Alt")
LoonBestInSlot:AddItem(spec, "35102", "MH", "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "34895", "MH", "Scryer's Blade of Focus", "Alt")

LoonBestInSlot:AddItem(spec, "34179", "OH", "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "33334", "OH", "Fetish of the Primal Gods", "Alt")

LoonBestInSlot:AddItem(spec, "34347", "Wand", "Wand of the Demonsoul", "BIS")
LoonBestInSlot:AddItem(spec, "33192", "Wand", "Carved Witch Doctor's Stick", "Alt")
