local spec = LoonBestInSlot:RegisterSpec("Mage", "Arcane", "5")
LoonBestInSlot:AddItem(spec, "30206", L["Head"], "Cowl of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30244", L["Head"], "Helm of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "34340", L["Head"], "Dark Conjuror's Collar", "Alt")
LoonBestInSlot:AddItem(spec, "34847", L["Head"], "Annihilator Holo-Gogs", "Alt")

LoonBestInSlot:AddItem(spec, "30210", L["Shoulders"], "Mantle of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30250", L["Shoulders"], "Pauldrons of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "34393", L["Shoulders"], "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", L["Shoulders"], "Shawl of Wonderment", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34210", L["Shoulders"], "Amice of the Convoker", "Alt")

LoonBestInSlot:AddItem(spec, "34242", L["Back"], "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34399", L["Chest"], "Robes of Ghostly Hatred", "BIS")
LoonBestInSlot:AddItem(spec, "34233", L["Chest"], "Robes of Faltered Light", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34364", L["Chest"], "Sunfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30196", L["Chest"], "Robes of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30238", L["Chest"], "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "31057", L["Chest"], "Robes of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "Alt")

LoonBestInSlot:AddItem(spec, "34447", L["Bracers"], "Bracers of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "34852", L["Bracers"], "Bracers of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30870", L["Bracers"], "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32586", L["Bracers"], "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34406", L["Gloves"], "Gloves of Tyri's Power", "BIS")
LoonBestInSlot:AddItem(spec, "34342", L["Gloves"], "Handguards of the Dawn", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "30205", L["Gloves"], "Gloves of Tirisfal", "BIS")
LoonBestInSlot:AddItem(spec, "30241", L["Gloves"], "Gloves of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "34344", L["Gloves"], "Handguards of Defiled Worlds", "Alt")
LoonBestInSlot:AddItem(spec, "34366", L["Gloves"], "Sunfire Handwraps", "Alt")

LoonBestInSlot:AddItem(spec, "34557", L["Belt"], "Belt of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "34855", L["Belt"], "Belt of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30888", L["Belt"], "Anetheron's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "34181", L["Legs"], "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34386", L["Legs"], "Pantaloons of Growing Strife", "Alt")
LoonBestInSlot:AddItem(spec, "34170", L["Legs"], "Pantaloons of Calming Strife", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30916", L["Legs"], "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "34937", L["Legs"], "Corrupted Soulcloth Pantaloons", "Alt")

LoonBestInSlot:AddItem(spec, "34574", L["Feet"], "Boots of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "34858", L["Feet"], "Boots of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32239", L["Feet"], "Slippers of the Seacaller", "Alt")
LoonBestInSlot:AddItem(spec, "34919", L["Feet"], "Boots of Incantations", "Alt")

LoonBestInSlot:AddItem(spec, "34204", L["Neck"], "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "33281", L["Neck"], "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34359", L["Neck"], "Pendant of Sunfire", "Alt")
LoonBestInSlot:AddItem(spec, "37928", L["Neck"], "Guardian's Pendant of Subjugation", "Alt")

LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "34362", L["Ring"], "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "34230", L["Ring"], "Ring of Omnipotence", "Alt")
LoonBestInSlot:AddItem(spec, "32527", L["Ring"], "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "33497", L["Ring"], "Mana Attuned Band", "Alt")

LoonBestInSlot:AddItem(spec, "34429", L["Trinket"], "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", L["Trinket"], "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "33829", L["Trinket"], "Hex Shrunken Head", "BIS")
LoonBestInSlot:AddItem(spec, "32488", L["Trinket"], "Ashtongue Talisman of Insight", "Alt")

LoonBestInSlot:AddItem(spec, "34336", L["MH"], "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "34182", L["MH"], "Grand Magister's Staff of Torrents", "Alt")
LoonBestInSlot:AddItem(spec, "32374", L["MH"], "Zhar'doom, Greatstaff of the Devourer", "Alt")
LoonBestInSlot:AddItem(spec, "30910", L["MH"], "Tempest of Chaos", "Alt")
LoonBestInSlot:AddItem(spec, "35102", L["MH"], "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "34895", L["MH"], "Scryer's Blade of Focus", "Alt")

LoonBestInSlot:AddItem(spec, "34179", L["OH"], "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30872", L["OH"], "Chronicle of Dark Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "33334", L["OH"], "Fetish of the Primal Gods", "Alt")

LoonBestInSlot:AddItem(spec, "34347", L["Wand"], "Wand of the Demonsoul", "BIS")
LoonBestInSlot:AddItem(spec, "33192", L["Wand"], "Carved Witch Doctor's Stick", "Alt")
