local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "5")
LoonBestInSlot:AddItem(spec, "34401", "Head", "Helm of Uther's Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "34243", "Head", "Helm of Burning Righteousness", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34400", "Head", "Crown of Dath'Remar", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34345", "Head", "Crown of Anasterian", "Transmute BIS Mit")
LoonBestInSlot:AddItem(spec, "32521", "Head", "Faceplate of the Impenetrable", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30987", "Head", "Lightbringer Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34357", "Head", "Hard Khorium Goggles", "Alt")

LoonBestInSlot:AddItem(spec, "34389", "Shoulders", "Spaulders of the Thalassian Defender", "BIS")
LoonBestInSlot:AddItem(spec, "34193", "Shoulders", "Spaulders of the Thalassian Savior", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34192", "Shoulders", "Pauldrons of Perseverance", "Mit")
LoonBestInSlot:AddItem(spec, "30998", "Shoulders", "Lightbringer Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "Alt")

LoonBestInSlot:AddItem(spec, "34190", "Back", "Crimson Paragon's Cover", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33593", "Back", "Slikk's Cloak of Placation", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34216", "Chest", "Heroic Judicator's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30991", "Chest", "Lightbringer Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34945", "Chest", "Shattrath Protectorate's Breastplate", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34939", "Chest", "Chestplate of Stoicism", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34433", "Bracers", "Lightbringer Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34848", "Bracers", "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32232", "Bracers", "Eternium Shell Bracers", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34352", "Gloves", "Borderland Fortress Grips", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30985", "Gloves", "Lightbringer Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "BIS")

LoonBestInSlot:AddItem(spec, "34488", "Belt", "Lightbringer Waistguard", "BIS")
LoonBestInSlot:AddItem(spec, "32342", "Belt", "Girdle of Mighty Resolve", "Alt")
LoonBestInSlot:AddItem(spec, "33524", "Belt", "Girdle of the Protector", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34382", "Legs", "Judicator's Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "34167", "Legs", "Legplates of the Holy Juggernaut", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "30995", "Legs", "Lightbringer Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "32263", "Legs", "Praetorian's Legguards", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34560", "Feet", "Lightbringer Stompers", "BIS")
LoonBestInSlot:AddItem(spec, "34856", "Feet", "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32245", "Feet", "Tide-stomper's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "34947", "Feet", "Blue's Greaves of the Righteous Guardian", "Thrt")

LoonBestInSlot:AddItem(spec, "34178", "Neck", "Collar of the Pit Lord", "BIS")
LoonBestInSlot:AddItem(spec, "30007", "Neck", "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34680", "Neck", "Shattered Sun Pendant of Resolve", "Alt")
LoonBestInSlot:AddItem(spec, "34678", "Neck", "Shattered Sun Pendant of Acumen", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35133", "Neck", "Guardian's Pendant of Dominance", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35290", "Neck", "Sin'dorei Pendant of Conquest", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34213", "Ring", "Ring of Hardened Resolve", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34888", "Ring", "Ring of the Stalwart Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30083", "Ring", "Ring of Sundered Souls", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34889", "Ring", "Fused Nethergon Band", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34362", "Ring", "Loop of Forged Power", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35129", "Ring", "Guardian's Band of Dominance", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34473", "Trinket", "Commendation of Kael'thas", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "34428", "Trinket", "Steely Naaru Sliver", "Alt")
LoonBestInSlot:AddItem(spec, "35700", "Trinket", "Figurine - Crimson Serpent", "Alt")

LoonBestInSlot:AddItem(spec, "35014", "MH", "Brutal Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "34176", "MH", "Reign of Misery", "Alt")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel", "Alt")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32368", "Libram", "Tome of the Lightbringer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33504", "Libram", "Libram of Divine Purpose", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "34185", "Shield", "Sword Breaker's Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "35094", "Shield", "Brutal Gladiator's Shield Wall", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34986", "Shield", "Brutal Gladiator's Barrier", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32375", "Shield", "Bulwark of Azzinoth", "Alt")
LoonBestInSlot:AddItem(spec, "30909", "Shield", "Antonidas's Aegis of Rapt Concentration", "Alt Thrt")
