local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "5")
LoonBestInSlot:AddItem(spec, "34401", L["Head"], "Helm of Uther's Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "34243", L["Head"], "Helm of Burning Righteousness", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34400", L["Head"], "Crown of Dath'Remar", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34345", L["Head"], "Crown of Anasterian", "Transmute BIS Mit")
LoonBestInSlot:AddItem(spec, "32521", L["Head"], "Faceplate of the Impenetrable", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30987", L["Head"], "Lightbringer Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34357", L["Head"], "Hard Khorium Goggles", "Alt")

LoonBestInSlot:AddItem(spec, "34389", L["Shoulders"], "Spaulders of the Thalassian Defender", "BIS")
LoonBestInSlot:AddItem(spec, "34193", L["Shoulders"], "Spaulders of the Thalassian Savior", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34192", L["Shoulders"], "Pauldrons of Perseverance", "Mit")
LoonBestInSlot:AddItem(spec, "30998", L["Shoulders"], "Lightbringer Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "Alt")

LoonBestInSlot:AddItem(spec, "34190", L["Back"], "Crimson Paragon's Cover", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33593", L["Back"], "Slikk's Cloak of Placation", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34242", L["Back"], "Tattered Cape of Antonidas", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34216", L["Chest"], "Heroic Judicator's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30991", L["Chest"], "Lightbringer Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34945", L["Chest"], "Shattrath Protectorate's Breastplate", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34939", L["Chest"], "Chestplate of Stoicism", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34433", L["Bracers"], "Lightbringer Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34848", L["Bracers"], "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32232", L["Bracers"], "Eternium Shell Bracers", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34352", L["Gloves"], "Borderland Fortress Grips", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30985", L["Gloves"], "Lightbringer Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "BIS")

LoonBestInSlot:AddItem(spec, "34488", L["Belt"], "Lightbringer Waistguard", "BIS")
LoonBestInSlot:AddItem(spec, "32342", L["Belt"], "Girdle of Mighty Resolve", "Alt")
LoonBestInSlot:AddItem(spec, "33524", L["Belt"], "Girdle of the Protector", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34382", L["Legs"], "Judicator's Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "34167", L["Legs"], "Legplates of the Holy Juggernaut", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "30995", L["Legs"], "Lightbringer Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "32263", L["Legs"], "Praetorian's Legguards", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34560", L["Feet"], "Lightbringer Stompers", "BIS")
LoonBestInSlot:AddItem(spec, "34856", L["Feet"], "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32245", L["Feet"], "Tide-stomper's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "34947", L["Feet"], "Blue's Greaves of the Righteous Guardian", "Thrt")

LoonBestInSlot:AddItem(spec, "34178", L["Neck"], "Collar of the Pit Lord", "BIS")
LoonBestInSlot:AddItem(spec, "30007", L["Neck"], "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32362", L["Neck"], "Pendant of Titans", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34680", L["Neck"], "Shattered Sun Pendant of Resolve", "Alt")
LoonBestInSlot:AddItem(spec, "34678", L["Neck"], "Shattered Sun Pendant of Acumen", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35133", L["Neck"], "Guardian's Pendant of Dominance", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35290", L["Neck"], "Sin'dorei Pendant of Conquest", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34213", L["Ring"], "Ring of Hardened Resolve", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34888", L["Ring"], "Ring of the Stalwart Protector", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30083", L["Ring"], "Ring of Sundered Souls", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34889", L["Ring"], "Fused Nethergon Band", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34362", L["Ring"], "Loop of Forged Power", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "35129", L["Ring"], "Guardian's Band of Dominance", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "34473", L["Trinket"], "Commendation of Kael'thas", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31858", L["Trinket"], "Darkmoon Card: Vengeance", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32501", L["Trinket"], "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "34428", L["Trinket"], "Steely Naaru Sliver", "Alt")
LoonBestInSlot:AddItem(spec, "35700", L["Trinket"], "Figurine - Crimson Serpent", "Alt")

LoonBestInSlot:AddItem(spec, "35014", L["MH"], "Brutal Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "30910", L["MH"], "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "34176", L["MH"], "Reign of Misery", "Alt")
LoonBestInSlot:AddItem(spec, "33687", L["MH"], "Vengeful Gladiator's Gavel", "Alt")

LoonBestInSlot:AddItem(spec, "29388", L["Libram"], "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32368", L["Libram"], "Tome of the Lightbringer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33504", L["Libram"], "Libram of Divine Purpose", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "34185", L["Shield"], "Sword Breaker's Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "35094", L["Shield"], "Brutal Gladiator's Shield Wall", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34986", L["Shield"], "Brutal Gladiator's Barrier", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32375", L["Shield"], "Bulwark of Azzinoth", "Alt")
LoonBestInSlot:AddItem(spec, "30909", L["Shield"], "Antonidas's Aegis of Rapt Concentration", "Alt Thrt")
