local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy", "5")
LoonBestInSlot:AddItem(spec, "34243", L["Head"], "Helm of Burning Righteousness", "BIS")
LoonBestInSlot:AddItem(spec, "34402", L["Head"], "Shroud of Chieftain Ner'zhul", "Alt")
LoonBestInSlot:AddItem(spec, "34332", L["Head"], "Cowl of Gul'dan", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "35185", L["Head"], "Justicebringer 3000 Specs", "Alt")
LoonBestInSlot:AddItem(spec, "30988", L["Head"], "Lightbringer Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "Alt")

LoonBestInSlot:AddItem(spec, "34193", L["Shoulders"], "Spaulders of the Thalassian Savior", "BIS")
LoonBestInSlot:AddItem(spec, "34208", L["Shoulders"], "Equilibrium Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "30996", L["Shoulders"], "Lightbringer Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "Alt")

LoonBestInSlot:AddItem(spec, "34205", L["Back"], "Shroud of Redeemed Souls", "BIS")
LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "34012", L["Back"], "Shroud of the Final Stand", "Alt")

LoonBestInSlot:AddItem(spec, "34229", L["Chest"], "Garments of Serene Shores", "BIS")
LoonBestInSlot:AddItem(spec, "34379", L["Chest"], "Sunblessed Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "34395", L["Chest"], "Noble Judicator's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "34216", L["Chest"], "Heroic Judicator's Chestguard", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30992", L["Chest"], "Lightbringer Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "Alt")

LoonBestInSlot:AddItem(spec, "34432", L["Bracers"], "Lightbringer Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34848", L["Bracers"], "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30862", L["Bracers"], "Blessed Adamantite Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "34380", L["Gloves"], "Sunblessed Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34240", L["Gloves"], "Gauntlets of the Soothed Soul", "BIS")
LoonBestInSlot:AddItem(spec, "30112", L["Gloves"], "Glorious Gauntlets of Crestfall", "Alt")

LoonBestInSlot:AddItem(spec, "34487", L["Belt"], "Lightbringer Belt", "BIS")
LoonBestInSlot:AddItem(spec, "30897", L["Belt"], "Girdle of Hope", "Alt")
LoonBestInSlot:AddItem(spec, "33446", L["Belt"], "Girdle of Stromgarde's Hope", "Alt")

LoonBestInSlot:AddItem(spec, "34167", L["Legs"], "Legplates of the Holy Juggernaut", "BIS")
LoonBestInSlot:AddItem(spec, "34383", L["Legs"], "Kilt of Spiritual Reconstruction", "Alt")
LoonBestInSlot:AddItem(spec, "34186", L["Legs"], "Chain Links of the Tumultuous Storm", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30994", L["Legs"], "Lightbringer Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "Alt")

LoonBestInSlot:AddItem(spec, "34559", L["Feet"], "Lightbringer Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34856", L["Feet"], "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32243", L["Feet"], "Pearl Inlaid Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32370", L["Neck"], "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "34360", L["Neck"], "Amulet of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "34184", L["Neck"], "Brooch of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34363", L["Ring"], "Ring of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34166", L["Ring"], "Band of Lucent Beams", "Alt")
LoonBestInSlot:AddItem(spec, "32238", L["Ring"], "Ring of Calming Waves", "Alt")
LoonBestInSlot:AddItem(spec, "29309", L["Ring"], "Band of the Eternal Restorer", "Alt")

LoonBestInSlot:AddItem(spec, "34430", L["Trinket"], "Glimmering Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "35750", L["Trinket"], "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "Alt")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "Alt")

LoonBestInSlot:AddItem(spec, "34335", L["MH"], "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34199", L["MH"], "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "30918", L["MH"], "Hammer of Atonement", "Alt")
LoonBestInSlot:AddItem(spec, "34896", L["MH"], "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34231", L["OH"], "Aegis of Angelic Fortune", "BIS")
LoonBestInSlot:AddItem(spec, "34206", L["OH"], "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "32255", L["OH"], "Felstone Bulwark", "Alt")
LoonBestInSlot:AddItem(spec, "30882", L["OH"], "Bastion of Light", "Alt")
LoonBestInSlot:AddItem(spec, "30911", L["OH"], "Scepter of Purification", "Alt")

LoonBestInSlot:AddItem(spec, "28592", L["Libram"], "Libram of Souls Redeemed", "BIS")
LoonBestInSlot:AddItem(spec, "23006", L["Libram"], "Libram of Light", "BIS")
LoonBestInSlot:AddItem(spec, "30063", L["Libram"], "Libram of Absolute Truth", "BIS")
LoonBestInSlot:AddItem(spec, "28296", L["Libram"], "Libram of the Lightbringer", "BIS")
