local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "5")
LoonBestInSlot:AddItem(spec, "34339", L["Head"], "Cowl of Light's Purity", "BIS")
LoonBestInSlot:AddItem(spec, "35181", L["Head"], "Powerheal 9000 Lens", "Alt")
LoonBestInSlot:AddItem(spec, "31063", L["Head"], "Cowl of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30152", L["Head"], "Cowl of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "34202", L["Shoulders"], "Shawl of Wonderment", "BIS")
LoonBestInSlot:AddItem(spec, "31069", L["Shoulders"], "Mantle of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30154", L["Shoulders"], "Mantle of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32585", L["Shoulders"], "Swiftheal Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34205", L["Back"], "Shroud of Redeemed Souls", "Alt")

LoonBestInSlot:AddItem(spec, "34233", L["Chest"], "Robes of Faltered Light", "BIS")
LoonBestInSlot:AddItem(spec, "34365", L["Chest"], "Robe of Eternal Light", "BIS")
LoonBestInSlot:AddItem(spec, "31066", L["Chest"], "Vestments of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30150", L["Chest"], "Vestments of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "34924", L["Chest"], "Gown of Spiritual Wonder", "Alt")

LoonBestInSlot:AddItem(spec, "34435", L["Bracers"], "Cuffs of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "34848", L["Bracers"], "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32584", L["Bracers"], "Swiftheal Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "30871", L["Bracers"], "Bracers of Martyrdom", "Alt")

LoonBestInSlot:AddItem(spec, "34342", L["Gloves"], "Handguards of the Dawn", "BIS")
LoonBestInSlot:AddItem(spec, "34367", L["Gloves"], "Hands of Eternal Light", "Alt")
LoonBestInSlot:AddItem(spec, "31060", L["Gloves"], "Gloves of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30151", L["Gloves"], "Gloves of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "34527", L["Belt"], "Belt of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "30895", L["Belt"], "Angelista's Sash", "Alt")
LoonBestInSlot:AddItem(spec, "32519", L["Belt"], "Belt of Divine Guidance", "Alt")

LoonBestInSlot:AddItem(spec, "34170", L["Legs"], "Pantaloons of Calming Strife", "Alt")
LoonBestInSlot:AddItem(spec, "30912", L["Legs"], "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "33585", L["Legs"], "Achromic Trousers of the Naaru", "Alt")
LoonBestInSlot:AddItem(spec, "34925", L["Legs"], "Adorned Supernal Legwraps", "Alt")

LoonBestInSlot:AddItem(spec, "34562", L["Feet"], "Boots of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "34856", L["Feet"], "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32609", L["Feet"], "Boots of the Divine Light", "Alt")
LoonBestInSlot:AddItem(spec, "34926", L["Feet"], "Slippers of Dutiful Mending", "Alt")

LoonBestInSlot:AddItem(spec, "33281", L["Neck"], "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34360", L["Neck"], "Amulet of Flowing Life", "Alt")
LoonBestInSlot:AddItem(spec, "37929", L["Neck"], "Guardian's Pendant of Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "34184", L["Neck"], "Brooch of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34363", L["Ring"], "Ring of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34166", L["Ring"], "Band of Lucent Beams", "Alt")
LoonBestInSlot:AddItem(spec, "35733", L["Ring"], "Ring of Harmonic Beauty", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "28823", L["Trinket"], "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "19288", L["Trinket"], "Darkmoon Card: Blue Dragon", "BIS")
LoonBestInSlot:AddItem(spec, "35750", L["Trinket"], "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "34430", L["Trinket"], "Glimmering Naaru Sliver", "Alt")

LoonBestInSlot:AddItem(spec, "34335", L["MH"], "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34337", L["MH"], "Golden Staff of the Sin'dorei", "BIS")
LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "34199", L["MH"], "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35082", L["MH"], "Brutal Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "34896", L["MH"], "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34206", L["OH"], "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "30911", L["OH"], "Scepter of Purification", "Alt")

LoonBestInSlot:AddItem(spec, "34348", L["Wand"], "Wand of Cleansing Light", "BIS")
LoonBestInSlot:AddItem(spec, "32363", L["Wand"], "Naaru-Blessed Life Rod", "Alt")
