local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "5")
LoonBestInSlot:AddItem(spec, "34339", "Head", "Cowl of Light's Purity", "BIS")
LoonBestInSlot:AddItem(spec, "35181", "Head", "Powerheal 9000 Lens", "Alt")
LoonBestInSlot:AddItem(spec, "31063", "Head", "Cowl of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30152", "Head", "Cowl of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "BIS")
LoonBestInSlot:AddItem(spec, "31069", "Shoulders", "Mantle of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30154", "Shoulders", "Mantle of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32585", "Shoulders", "Swiftheal Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34205", "Back", "Shroud of Redeemed Souls", "Alt")

LoonBestInSlot:AddItem(spec, "34233", "Chest", "Robes of Faltered Light", "BIS")
LoonBestInSlot:AddItem(spec, "34365", "Chest", "Robe of Eternal Light", "BIS")
LoonBestInSlot:AddItem(spec, "31066", "Chest", "Vestments of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30150", "Chest", "Vestments of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "34924", "Chest", "Gown of Spiritual Wonder", "Alt")

LoonBestInSlot:AddItem(spec, "34435", "Bracers", "Cuffs of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "34848", "Bracers", "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "30871", "Bracers", "Bracers of Martyrdom", "Alt")

LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "BIS")
LoonBestInSlot:AddItem(spec, "34367", "Gloves", "Hands of Eternal Light", "Alt")
LoonBestInSlot:AddItem(spec, "31060", "Gloves", "Gloves of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30151", "Gloves", "Gloves of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "34527", "Belt", "Belt of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash", "Alt")
LoonBestInSlot:AddItem(spec, "32519", "Belt", "Belt of Divine Guidance", "Alt")

LoonBestInSlot:AddItem(spec, "34170", "Legs", "Pantaloons of Calming Strife", "Alt")
LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "33585", "Legs", "Achromic Trousers of the Naaru", "Alt")
LoonBestInSlot:AddItem(spec, "34925", "Legs", "Adorned Supernal Legwraps", "Alt")

LoonBestInSlot:AddItem(spec, "34562", "Feet", "Boots of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "34856", "Feet", "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light", "Alt")
LoonBestInSlot:AddItem(spec, "34926", "Feet", "Slippers of Dutiful Mending", "Alt")

LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34360", "Neck", "Amulet of Flowing Life", "Alt")
LoonBestInSlot:AddItem(spec, "37929", "Neck", "Guardian's Pendant of Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "34184", "Neck", "Brooch of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34363", "Ring", "Ring of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34166", "Ring", "Band of Lucent Beams", "Alt")
LoonBestInSlot:AddItem(spec, "35733", "Ring", "Ring of Harmonic Beauty", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "19288", "Trinket", "Darkmoon Card: Blue Dragon", "BIS")
LoonBestInSlot:AddItem(spec, "35750", "Trinket", "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "34430", "Trinket", "Glimmering Naaru Sliver", "Alt")

LoonBestInSlot:AddItem(spec, "34335", "MH", "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34337", "MH", "Golden Staff of the Sin'dorei", "BIS")
LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "34199", "MH", "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35082", "MH", "Brutal Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "34896", "MH", "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34206", "OH", "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification", "Alt")

LoonBestInSlot:AddItem(spec, "34348", "Wand", "Wand of Cleansing Light", "BIS")
LoonBestInSlot:AddItem(spec, "32363", "Wand", "Naaru-Blessed Life Rod", "Alt")
