local spec = LoonBestInSlot:RegisterSpec("Priest", "Shadow", "5")
LoonBestInSlot:AddItem(spec, "34340", "Head", "Dark Conjuror's Collar", "BIS")
LoonBestInSlot:AddItem(spec, "34847", "Head", "Annihilator Holo-Gogs", "Alt")
LoonBestInSlot:AddItem(spec, "31064", "Head", "Hood of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34405", "Head", "Helm of Arcane Purity", "Alt")
LoonBestInSlot:AddItem(spec, "34339", "Head", "Cowl of Light's Purity", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "31070", "Shoulders", "Shoulderpads of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "34210", "Shoulders", "Amice of the Convoker", "BIS")
LoonBestInSlot:AddItem(spec, "34393", "Shoulders", "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34607", "Shoulders", "Fel-tinged Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32590", "Back", "Nethervoid Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "34364", "Chest", "Sunfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "34232", "Chest", "Fel Conquerer Raiments", "BIS")
LoonBestInSlot:AddItem(spec, "31065", "Chest", "Shroud of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34399", "Chest", "Robes of Ghostly Hatred", "Alt")
LoonBestInSlot:AddItem(spec, "34233", "Chest", "Robes of Faltered Light", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34917", "Chest", "Shroud of the Lore`nial", "Alt")
LoonBestInSlot:AddItem(spec, "34936", "Chest", "Tormented Demonsoul Robes", "Alt")
LoonBestInSlot:AddItem(spec, "34610", "Chest", "Scarlet Sin'dorei Robes", "Alt")

LoonBestInSlot:AddItem(spec, "34434", "Bracers", "Bracers of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "34848", "Bracers", "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34344", "Gloves", "Handguards of Defiled Worlds", "BIS")
LoonBestInSlot:AddItem(spec, "31061", "Gloves", "Handguards of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34406", "Gloves", "Gloves of Tyri's Power", "Alt")
LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34366", "Gloves", "Sunfire Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "34938", "Gloves", "Enslaved Doomguard Soulgrips", "Alt")
LoonBestInSlot:AddItem(spec, "34808", "Gloves", "Gloves of Arcane Acuity", "Alt")

LoonBestInSlot:AddItem(spec, "34528", "Belt", "Cord of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "Alt")

LoonBestInSlot:AddItem(spec, "34181", "Legs", "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34386", "Legs", "Pantaloons of Growing Strife", "BIS")
LoonBestInSlot:AddItem(spec, "34170", "Legs", "Pantaloons of Calming Strife", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "34918", "Legs", "Legwraps of Sweltering Flame", "Alt")
LoonBestInSlot:AddItem(spec, "34937", "Legs", "Corrupted Soulcloth Pantaloons", "Alt")

LoonBestInSlot:AddItem(spec, "34563", "Feet", "Treads of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "34856", "Feet", "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "Alt")
LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots", "Alt")
LoonBestInSlot:AddItem(spec, "34919", "Feet", "Boots of Incantations", "Alt")

LoonBestInSlot:AddItem(spec, "34204", "Neck", "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "BIS")
LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night", "BIS")
LoonBestInSlot:AddItem(spec, "34359", "Neck", "Pendant of Sunfire", "Alt")
LoonBestInSlot:AddItem(spec, "33466", "Neck", "Loop of Cursed Bones", "Alt")
LoonBestInSlot:AddItem(spec, "37928", "Neck", "Guardian's Pendant of Subjugation", "Alt")
LoonBestInSlot:AddItem(spec, "35290", "Neck", "Sin'dorei Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "34678", "Neck", "Shattered Sun Pendant of Acumen", "Alt")

LoonBestInSlot:AddItem(spec, "34230", "Ring", "Ring of Omnipotence", "BIS")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "34362", "Ring", "Loop of Forged Power", "Alt")
LoonBestInSlot:AddItem(spec, "34889", "Ring", "Fused Nethergon Band", "Alt")
LoonBestInSlot:AddItem(spec, "35129", "Ring", "Guardian's Band of Dominance", "Alt")
LoonBestInSlot:AddItem(spec, "35282", "Ring", "Sin'dorei Band of Dominance", "Alt")

LoonBestInSlot:AddItem(spec, "34429", "Trinket", "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "33829", "Trinket", "Hex Shrunken Head", "BIS")
LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "Alt")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "Alt")
LoonBestInSlot:AddItem(spec, "34470", "Trinket", "Timbal's Focusing Crystal", "Alt")
LoonBestInSlot:AddItem(spec, "35749", "Trinket", "Sorcerer's Alchemist Stone", "Alt")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "Alt")

LoonBestInSlot:AddItem(spec, "34336", "MH", "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "34176", "MH", "Reign of Misery", "Alt")
LoonBestInSlot:AddItem(spec, "35014", "MH", "Brutal Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "35102", "MH", "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "32374", "MH", "Zhar'doom, Greatstaff of the Devourer", "Alt")
LoonBestInSlot:AddItem(spec, "34895", "MH", "Scryer's Blade of Focus", "Alt")
LoonBestInSlot:AddItem(spec, "34182", "MH", "Grand Magister's Staff of Torrents", "Alt")
LoonBestInSlot:AddItem(spec, "34611", "MH", "Cudgel of Consecration", "Alt")
LoonBestInSlot:AddItem(spec, "34604", "MH", "Jaded Crystal Dagger", "Alt")

LoonBestInSlot:AddItem(spec, "34179", "OH", "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "33334", "OH", "Fetish of the Primal Gods", "Alt")

LoonBestInSlot:AddItem(spec, "34347", "Wand", "Wand of the Demonsoul", "BIS")
LoonBestInSlot:AddItem(spec, "33192", "Wand", "Carved Witch Doctor's Stick", "Alt")
