local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto", "5")
LoonBestInSlot:AddItem(spec, "34402", L["Head"], "Shroud of Chieftain Ner'zhul", "BIS")
LoonBestInSlot:AddItem(spec, "34332", L["Head"], "Cowl of Gul'dan", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34339", L["Head"], "Cowl of Light's Purity", "Alt")
LoonBestInSlot:AddItem(spec, "35184", L["Head"], "Primal-Attuned Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "31012", L["Head"], "Skyshatter Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "31022", L["Shoulders"], "Skyshatter Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34208", L["Shoulders"], "Equilibrium Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "34202", L["Shoulders"], "Shawl of Wonderment", "Alt")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34242", L["Back"], "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "34205", L["Back"], "Shroud of Redeemed Souls", "Alt")

LoonBestInSlot:AddItem(spec, "34375", L["Chest"], "Sun-Drenched Scale Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "34212", L["Chest"], "Sunglow Vest", "Alt")
LoonBestInSlot:AddItem(spec, "34229", L["Chest"], "Garments of Serene Shores", "Alt")
LoonBestInSlot:AddItem(spec, "31016", L["Chest"], "Skyshatter Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "34930", L["Chest"], "Wave of Life Chestguard", "Alt")

LoonBestInSlot:AddItem(spec, "34438", L["Bracers"], "Skyshatter Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34851", L["Bracers"], "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32577", L["Bracers"], "Living Earth Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "32584", L["Bracers"], "Swiftheal Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "32582", L["Bracers"], "Bracers of Renewed Life", "Alt")

LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "BIS")
LoonBestInSlot:AddItem(spec, "34372", L["Gloves"], "Leather Gauntlets of the Sun", "BIS")
LoonBestInSlot:AddItem(spec, "34409", L["Gloves"], "Gauntlets of the Ancient Frostwolf", "BIS")
LoonBestInSlot:AddItem(spec, "34350", L["Gloves"], "Gauntlets of the Ancient Shadowmoon", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34376", L["Gloves"], "Sun-Drenched Scale Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "34543", L["Belt"], "Skyshatter Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34854", L["Belt"], "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32258", L["Belt"], "Naturalist's Preserving Cinch", "Alt")
LoonBestInSlot:AddItem(spec, "32339", L["Belt"], "Belt of Primal Majesty", "Alt")
LoonBestInSlot:AddItem(spec, "30895", L["Belt"], "Angelista's Sash", "Alt")
LoonBestInSlot:AddItem(spec, "34932", L["Belt"], "Clutch of the Soothing Breeze", "Alt")

LoonBestInSlot:AddItem(spec, "34383", L["Legs"], "Kilt of Spiritual Reconstruction", "BIS")
LoonBestInSlot:AddItem(spec, "34186", L["Legs"], "Chain Links of the Tumultuous Storm", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "31019", L["Legs"], "Skyshatter Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31100", L["Legs"], "Leggings of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "34931", L["Legs"], "Runed Scales of Antiquity", "Alt")

LoonBestInSlot:AddItem(spec, "34565", L["Feet"], "Skyshatter Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34857", L["Feet"], "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "33324", L["Feet"], "Treads of the Life Path", "Alt")
LoonBestInSlot:AddItem(spec, "33471", L["Feet"], "Two-toed Sandals", "Alt")
LoonBestInSlot:AddItem(spec, "35147", L["Feet"], "Guardian's Ringmail Sabatons", "Alt")

LoonBestInSlot:AddItem(spec, "34360", L["Neck"], "Amulet of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "33281", L["Neck"], "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34184", L["Neck"], "Brooch of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "37929", L["Neck"], "Guardian's Pendant of Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "32370", L["Neck"], "Nadina's Pendant of Purity", "Alt")

LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34363", L["Ring"], "Ring of Flowing Life", "Alt")
LoonBestInSlot:AddItem(spec, "34166", L["Ring"], "Band of Lucent Beams", "Alt")
LoonBestInSlot:AddItem(spec, "34890", L["Ring"], "Anveena's Touch", "Alt")

LoonBestInSlot:AddItem(spec, "35750", L["Trinket"], "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "34430", L["Trinket"], "Glimmering Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")

LoonBestInSlot:AddItem(spec, "34335", L["MH"], "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34199", L["MH"], "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "35082", L["MH"], "Brutal Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "34896", L["MH"], "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34206", L["OH"], "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "34231", L["OH"], "Aegis of Angelic Fortune", "BIS")
LoonBestInSlot:AddItem(spec, "30882", L["OH"], "Bastion of Light", "BIS")
LoonBestInSlot:AddItem(spec, "32255", L["OH"], "Felstone Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "33332", L["OH"], "Enamelled Disc of Mojo", "BIS")

LoonBestInSlot:AddItem(spec, "28523", L["Totem"], "Totem of Healing Rains", "BIS")
