local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "5")
LoonBestInSlot:AddItem(spec, "34244", L["Head"], "Duplicitous Guise", "BIS")
LoonBestInSlot:AddItem(spec, "34333", L["Head"], "Coif of Alleria", "BIS")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "34356", L["Head"], "Surestrike Goggles v3.0", "Alt")

LoonBestInSlot:AddItem(spec, "34392", L["Shoulders"], "Demontooth Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "34195", L["Shoulders"], "Shoulderpads of Vehemence", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34194", L["Shoulders"], "Mantle of the Golden Forest", "BIS")
LoonBestInSlot:AddItem(spec, "32581", L["Shoulders"], "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "32575", L["Shoulders"], "Shoulders of Lightning Reflexes", "Alt")

LoonBestInSlot:AddItem(spec, "34241", L["Back"], "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "BIS")

LoonBestInSlot:AddItem(spec, "34397", L["Chest"], "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", L["Chest"], "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34369", L["Chest"], "Carapace of Sun and Shadow", "BIS")
LoonBestInSlot:AddItem(spec, "34373", L["Chest"], "Embrace of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "34228", L["Chest"], "Vicious Hawkstrider Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "30905", L["Chest"], "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "34927", L["Chest"], "Tunic of the Dark Hour", "Alt")

LoonBestInSlot:AddItem(spec, "34439", L["Bracers"], "Skyshatter Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34851", L["Bracers"], "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "32574", L["Bracers"], "Bindings of Lightning Reflexes", "Alt")
LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "Alt")

LoonBestInSlot:AddItem(spec, "34343", L["Gloves"], "Thalassian Ranger Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34370", L["Gloves"], "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "34234", L["Gloves"], "Shadowed Gauntlets of Paroxysm", "Alt")
LoonBestInSlot:AddItem(spec, "34374", L["Gloves"], "Fletcher's Gloves of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "32347", L["Gloves"], "Grips of Damnation", "Alt")
LoonBestInSlot:AddItem(spec, "32234", L["Gloves"], "Fists of Mukoa", "Alt")
LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "Alt")

LoonBestInSlot:AddItem(spec, "34545", L["Belt"], "Skyshatter Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "34854", L["Belt"], "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")

LoonBestInSlot:AddItem(spec, "34188", L["Legs"], "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "30900", L["Legs"], "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "34168", L["Legs"], "Starstalker Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "34928", L["Legs"], "Trousers of the Scryers' Retainer", "Alt")

LoonBestInSlot:AddItem(spec, "34567", L["Feet"], "Skyshatter Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "34857", L["Feet"], "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32510", L["Feet"], "Softstep Boots of Tracking", "Alt")
LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "33222", L["Feet"], "Nyn'jah's Tabi Boots", "Alt")

LoonBestInSlot:AddItem(spec, "34358", L["Neck"], "Hard Khorium Choker", "BIS")
LoonBestInSlot:AddItem(spec, "34177", L["Neck"], "Clutch of Demise", "BIS")
LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "34679", L["Neck"], "Shattered Sun Pendant of Might", "Alt")

LoonBestInSlot:AddItem(spec, "34189", L["Ring"], "Band of Ruinous Delight", "BIS")
LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "34361", L["Ring"], "Hard Khorium Band", "Alt")
LoonBestInSlot:AddItem(spec, "34887", L["Ring"], "Angelista's Revenge", "Alt")
LoonBestInSlot:AddItem(spec, "33496", L["Ring"], "Signet of Primal Wrath", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "BIS")

LoonBestInSlot:AddItem(spec, "34427", L["Trinket"], "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "34472", L["Trinket"], "Shard of Contempt", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "Alt")
LoonBestInSlot:AddItem(spec, "33831", L["Trinket"], "Berserker's Call", "Alt")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "35702", L["Trinket"], "Figurine - Shadowsong Panther", "Alt")

LoonBestInSlot:AddItem(spec, "34331", L["MH"], "Hand of the Deceiver", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "34346", L["MH"], "Mounting Vengeance", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "34996", L["MH"], "Brutal Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "33669", L["MH"], "Vengeful Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "32262", L["MH"], "Syphon of the Nathrezim", "Alt (All)")
LoonBestInSlot:AddItem(spec, "34893", L["MH"], "Vanir's Right Fist of Brutality", "Alt (2.5 MH)")
LoonBestInSlot:AddItem(spec, "34951", L["MH"], "Vanir's Left Fist of Brutality", "Alt (2.5 OH)")

LoonBestInSlot:AddItem(spec, "33507", L["Totem"], "Stonebreaker's Totem", "BIS")
