local spec = LoonBestInSlot:RegisterSpec("Shaman", "Elemental", "5")
LoonBestInSlot:AddItem(spec, "34332", "Head", "Cowl of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "34340", "Head", "Dark Conjuror's Collar", "BIS")
LoonBestInSlot:AddItem(spec, "34847", "Head", "Annihilator Holo-Gogs", "Alt")
LoonBestInSlot:AddItem(spec, "31014", "Head", "Skyshatter Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "31023", "Shoulders", "Skyshatter Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34210", "Shoulders", "Amice of the Convoker", "Alt")
LoonBestInSlot:AddItem(spec, "34390", "Shoulders", "Erupting Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "34208", "Shoulders", "Equilibrium Epaulets", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "Alt")

LoonBestInSlot:AddItem(spec, "34364", "Chest", "Sunfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "34396", "Chest", "Garments of Crashing Shores", "BIS")
LoonBestInSlot:AddItem(spec, "34229", "Chest", "Garments of Serene Shores", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34232", "Chest", "Fel Conquerer Raiments", "Alt")
LoonBestInSlot:AddItem(spec, "31017", "Chest", "Skyshatter Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "34933", "Chest", "Hauberk of Whirling Fury", "Alt")

LoonBestInSlot:AddItem(spec, "34437", "Bracers", "Skyshatter Bands", "BIS")
LoonBestInSlot:AddItem(spec, "34851", "Bracers", "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34350", "Gloves", "Gauntlets of the Ancient Shadowmoon", "BIS")
LoonBestInSlot:AddItem(spec, "34406", "Gloves", "Gloves of Tyri's Power", "BIS")
LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34344", "Gloves", "Handguards of Defiled Worlds", "BIS")
LoonBestInSlot:AddItem(spec, "34366", "Gloves", "Sunfire Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "34938", "Gloves", "Enslaved Doomguard Soulgrips", "Alt")
LoonBestInSlot:AddItem(spec, "31008", "Gloves", "Skyshatter Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "34542", "Belt", "Skyshatter Cord", "BIS")
LoonBestInSlot:AddItem(spec, "34854", "Belt", "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32276", "Belt", "Flashfire Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "34935", "Belt", "Aftershock Waistguard", "Alt")

LoonBestInSlot:AddItem(spec, "34186", "Legs", "Chain Links of the Tumultuous Storm", "BIS")
LoonBestInSlot:AddItem(spec, "34181", "Legs", "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34169", "Legs", "Breeches of Natural Aggression", "Alt")
LoonBestInSlot:AddItem(spec, "34934", "Legs", "Rushing Storm Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "33584", "Legs", "Pantaloons of Arcane Annihilation", "Alt")
LoonBestInSlot:AddItem(spec, "31020", "Legs", "Skyshatter Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "34566", "Feet", "Skyshatter Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34857", "Feet", "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "Alt")
LoonBestInSlot:AddItem(spec, "32352", "Feet", "Naturewarden's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "33357", "Feet", "Footpads of Madness", "Alt")

LoonBestInSlot:AddItem(spec, "34359", "Neck", "Pendant of Sunfire", "BIS")
LoonBestInSlot:AddItem(spec, "34204", "Neck", "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "37928", "Neck", "Guardian's Pendant of Subjugation", "BIS")
LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "33466", "Neck", "Loop of Cursed Bones", "BIS")

LoonBestInSlot:AddItem(spec, "34230", "Ring", "Ring of Omnipotence", "BIS")
LoonBestInSlot:AddItem(spec, "34362", "Ring", "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "Alt")

LoonBestInSlot:AddItem(spec, "34429", "Trinket", "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "28785", "Trinket", "The Lightning Capacitor", "BIS")
LoonBestInSlot:AddItem(spec, "33829", "Trinket", "Hex Shrunken Head", "BIS")
LoonBestInSlot:AddItem(spec, "35749", "Trinket", "Sorcerer's Alchemist Stone", "Alt")

LoonBestInSlot:AddItem(spec, "34336", "MH", "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "34176", "MH", "Reign of Misery", "Alt")
LoonBestInSlot:AddItem(spec, "32374", "MH", "Zhar'doom, Greatstaff of the Devourer", "Alt")
LoonBestInSlot:AddItem(spec, "35014", "MH", "Brutal Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "34895", "MH", "Scryer's Blade of Focus", "Alt")

LoonBestInSlot:AddItem(spec, "34179", "OH", "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30909", "OH", "Antonidas's Aegis of Rapt Concentration", "Alt")
LoonBestInSlot:AddItem(spec, "33334", "OH", "Fetish of the Primal Gods", "Alt")

LoonBestInSlot:AddItem(spec, "32330", "Totem", "Totem of Ancestral Guidance", "BIS")
LoonBestInSlot:AddItem(spec, "33506", "Totem", "Skycall Totem", "BIS")
