local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "5")
LoonBestInSlot:AddItem(spec, "34244", "Head", "Duplicitous Guise", "BIS")
LoonBestInSlot:AddItem(spec, "34333", "Head", "Coif of Alleria", "BIS")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")

LoonBestInSlot:AddItem(spec, "34392", "Shoulders", "Demontooth Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "34195", "Shoulders", "Shoulderpads of Vehemence", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34194", "Shoulders", "Mantle of the Golden Forest", "BIS")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "32575", "Shoulders", "Shoulders of Lightning Reflexes", "Alt")

LoonBestInSlot:AddItem(spec, "34241", "Back", "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS")

LoonBestInSlot:AddItem(spec, "34397", "Chest", "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", "Chest", "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34369", "Chest", "Carapace of Sun and Shadow", "BIS")
LoonBestInSlot:AddItem(spec, "34373", "Chest", "Embrace of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "34228", "Chest", "Vicious Hawkstrider Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "34927", "Chest", "Tunic of the Dark Hour", "Alt")

LoonBestInSlot:AddItem(spec, "34439", "Bracers", "Skyshatter Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34851", "Bracers", "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "Alt")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "Alt")

LoonBestInSlot:AddItem(spec, "34343", "Gloves", "Thalassian Ranger Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34370", "Gloves", "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "34234", "Gloves", "Shadowed Gauntlets of Paroxysm", "Alt")
LoonBestInSlot:AddItem(spec, "34374", "Gloves", "Fletcher's Gloves of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation", "Alt")
LoonBestInSlot:AddItem(spec, "32234", "Gloves", "Fists of Mukoa", "Alt")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "Alt")

LoonBestInSlot:AddItem(spec, "34545", "Belt", "Skyshatter Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "34854", "Belt", "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")

LoonBestInSlot:AddItem(spec, "34188", "Legs", "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "34168", "Legs", "Starstalker Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "34928", "Legs", "Trousers of the Scryers' Retainer", "Alt")

LoonBestInSlot:AddItem(spec, "34567", "Feet", "Skyshatter Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "34857", "Feet", "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "Alt")
LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "Alt")
LoonBestInSlot:AddItem(spec, "33222", "Feet", "Nyn'jah's Tabi Boots", "Alt")

LoonBestInSlot:AddItem(spec, "34358", "Neck", "Hard Khorium Choker", "BIS")
LoonBestInSlot:AddItem(spec, "34177", "Neck", "Clutch of Demise", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "34679", "Neck", "Shattered Sun Pendant of Might", "Alt")

LoonBestInSlot:AddItem(spec, "34189", "Ring", "Band of Ruinous Delight", "BIS")
LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "34361", "Ring", "Hard Khorium Band", "Alt")
LoonBestInSlot:AddItem(spec, "34887", "Ring", "Angelista's Revenge", "Alt")
LoonBestInSlot:AddItem(spec, "33496", "Ring", "Signet of Primal Wrath", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")

LoonBestInSlot:AddItem(spec, "34427", "Trinket", "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "34472", "Trinket", "Shard of Contempt", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "Alt")
LoonBestInSlot:AddItem(spec, "33831", "Trinket", "Berserker's Call", "Alt")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "35702", "Trinket", "Figurine - Shadowsong Panther", "Alt")

LoonBestInSlot:AddItem(spec, "34331", "MH", "Hand of the Deceiver", "BIS (MH)")
LoonBestInSlot:AddItem(spec, "34346", "MH", "Mounting Vengeance", "BIS (OH)")
LoonBestInSlot:AddItem(spec, "34996", "MH", "Brutal Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "33669", "MH", "Vengeful Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "32262", "MH", "Syphon of the Nathrezim", "Alt (All)")
LoonBestInSlot:AddItem(spec, "34893", "MH", "Vanir's Right Fist of Brutality", "Alt (2.5 MH)")
LoonBestInSlot:AddItem(spec, "34951", "MH", "Vanir's Left Fist of Brutality", "Alt (2.5 OH)")

LoonBestInSlot:AddItem(spec, "33507", "Totem", "Stonebreaker's Totem", "BIS")
