local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto", "5")
LoonBestInSlot:AddItem(spec, "34402", "Head", "Shroud of Chieftain Ner'zhul", "BIS")
LoonBestInSlot:AddItem(spec, "34332", "Head", "Cowl of Gul'dan", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34339", "Head", "Cowl of Light's Purity", "Alt")
LoonBestInSlot:AddItem(spec, "35184", "Head", "Primal-Attuned Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "31012", "Head", "Skyshatter Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "31022", "Shoulders", "Skyshatter Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34208", "Shoulders", "Equilibrium Epaulets", "Alt")
LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "34205", "Back", "Shroud of Redeemed Souls", "Alt")

LoonBestInSlot:AddItem(spec, "34375", "Chest", "Sun-Drenched Scale Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "34212", "Chest", "Sunglow Vest", "Alt")
LoonBestInSlot:AddItem(spec, "34229", "Chest", "Garments of Serene Shores", "Alt")
LoonBestInSlot:AddItem(spec, "31016", "Chest", "Skyshatter Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "34930", "Chest", "Wave of Life Chestguard", "Alt")

LoonBestInSlot:AddItem(spec, "34438", "Bracers", "Skyshatter Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34851", "Bracers", "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32577", "Bracers", "Living Earth Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps", "Alt")
LoonBestInSlot:AddItem(spec, "32582", "Bracers", "Bracers of Renewed Life", "Alt")

LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "BIS")
LoonBestInSlot:AddItem(spec, "34372", "Gloves", "Leather Gauntlets of the Sun", "BIS")
LoonBestInSlot:AddItem(spec, "34409", "Gloves", "Gauntlets of the Ancient Frostwolf", "BIS")
LoonBestInSlot:AddItem(spec, "34350", "Gloves", "Gauntlets of the Ancient Shadowmoon", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34376", "Gloves", "Sun-Drenched Scale Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "34543", "Belt", "Skyshatter Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34854", "Belt", "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32258", "Belt", "Naturalist's Preserving Cinch", "Alt")
LoonBestInSlot:AddItem(spec, "32339", "Belt", "Belt of Primal Majesty", "Alt")
LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash", "Alt")
LoonBestInSlot:AddItem(spec, "34932", "Belt", "Clutch of the Soothing Breeze", "Alt")

LoonBestInSlot:AddItem(spec, "34383", "Legs", "Kilt of Spiritual Reconstruction", "BIS")
LoonBestInSlot:AddItem(spec, "34186", "Legs", "Chain Links of the Tumultuous Storm", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "31019", "Legs", "Skyshatter Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "34931", "Legs", "Runed Scales of Antiquity", "Alt")

LoonBestInSlot:AddItem(spec, "34565", "Feet", "Skyshatter Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34857", "Feet", "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "33324", "Feet", "Treads of the Life Path", "Alt")
LoonBestInSlot:AddItem(spec, "33471", "Feet", "Two-toed Sandals", "Alt")
LoonBestInSlot:AddItem(spec, "35147", "Feet", "Guardian's Ringmail Sabatons", "Alt")

LoonBestInSlot:AddItem(spec, "34360", "Neck", "Amulet of Flowing Life", "BIS")
LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "BIS")
LoonBestInSlot:AddItem(spec, "34184", "Neck", "Brooch of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "37929", "Neck", "Guardian's Pendant of Reprieve", "Alt")
LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity", "Alt")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "34363", "Ring", "Ring of Flowing Life", "Alt")
LoonBestInSlot:AddItem(spec, "34166", "Ring", "Band of Lucent Beams", "Alt")
LoonBestInSlot:AddItem(spec, "34890", "Ring", "Anveena's Touch", "Alt")

LoonBestInSlot:AddItem(spec, "35750", "Trinket", "Redeemer's Alchemist Stone", "BIS")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "34430", "Trinket", "Glimmering Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")

LoonBestInSlot:AddItem(spec, "34335", "MH", "Hammer of Sanctification", "BIS")
LoonBestInSlot:AddItem(spec, "34199", "MH", "Archon's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "35082", "MH", "Brutal Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "34896", "MH", "Gavel of Naaru Blessings", "Alt")

LoonBestInSlot:AddItem(spec, "34206", "OH", "Book of Highborne Hymns", "BIS")
LoonBestInSlot:AddItem(spec, "34231", "OH", "Aegis of Angelic Fortune", "BIS")
LoonBestInSlot:AddItem(spec, "30882", "OH", "Bastion of Light", "BIS")
LoonBestInSlot:AddItem(spec, "32255", "OH", "Felstone Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "33332", "OH", "Enamelled Disc of Mojo", "BIS")

LoonBestInSlot:AddItem(spec, "28523", "Totem", "Totem of Healing Rains", "BIS")
