local spec = LoonBestInSlot:RegisterSpec("Warlock", "Demo", "5")
LoonBestInSlot:AddItem(spec, "34340", "Head", "Dark Conjuror's Collar", "BIS")
LoonBestInSlot:AddItem(spec, "34847", "Head", "Annihilator Holo-Gogs", "Alt")
LoonBestInSlot:AddItem(spec, "31051", "Head", "Hood of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34405", "Head", "Helm of Arcane Purity", "Alt")
LoonBestInSlot:AddItem(spec, "34339", "Head", "Cowl of Light's Purity", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34210", "Shoulders", "Amice of the Convoker", "BIS")
LoonBestInSlot:AddItem(spec, "31054", "Shoulders", "Mantle of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "34393", "Shoulders", "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", "Shoulders", "Shawl of Wonderment", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34242", "Back", "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34364", "Chest", "Sunfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "34232", "Chest", "Fel Conquerer Raiments", "BIS")
LoonBestInSlot:AddItem(spec, "34399", "Chest", "Robes of Ghostly Hatred", "Alt")
LoonBestInSlot:AddItem(spec, "34233", "Chest", "Robes of Faltered Light", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "31052", "Chest", "Robe of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34610", "Chest", "Scarlet Sin'dorei Robes", "Alt")
LoonBestInSlot:AddItem(spec, "34917", "Chest", "Shroud of the Lore`nial", "Alt")

LoonBestInSlot:AddItem(spec, "34436", "Bracers", "Bracers of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "34848", "Bracers", "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34344", "Gloves", "Handguards of Defiled Worlds", "BIS")
LoonBestInSlot:AddItem(spec, "34406", "Gloves", "Gloves of Tyri's Power", "Alt")
LoonBestInSlot:AddItem(spec, "34342", "Gloves", "Handguards of the Dawn", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34366", "Gloves", "Sunfire Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "31050", "Gloves", "Gloves of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34808", "Gloves", "Gloves of Arcane Acuity", "Alt")
LoonBestInSlot:AddItem(spec, "34938", "Gloves", "Enslaved Doomguard Soulgrips", "Alt")

LoonBestInSlot:AddItem(spec, "34541", "Belt", "Belt of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "Alt")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "34181", "Legs", "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34386", "Legs", "Pantaloons of Growing Strife", "Alt")
LoonBestInSlot:AddItem(spec, "34170", "Legs", "Pantaloons of Calming Strife", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "31053", "Legs", "Leggings of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34918", "Legs", "Legwraps of Sweltering Flame", "Alt")
LoonBestInSlot:AddItem(spec, "34937", "Legs", "Corrupted Soulcloth Pantaloons", "Alt")

LoonBestInSlot:AddItem(spec, "34564", "Feet", "Boots of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "34856", "Feet", "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "Alt")
LoonBestInSlot:AddItem(spec, "34919", "Feet", "Boots of Incantations", "Alt")

LoonBestInSlot:AddItem(spec, "34359", "Neck", "Pendant of Sunfire", "BIS")
LoonBestInSlot:AddItem(spec, "34204", "Neck", "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "37928", "Neck", "Guardian's Pendant of Subjugation", "Alt")
LoonBestInSlot:AddItem(spec, "33281", "Neck", "Brooch of Nature's Mercy", "Alt")
LoonBestInSlot:AddItem(spec, "34678", "Neck", "Shattered Sun Pendant of Acumen", "Alt")
LoonBestInSlot:AddItem(spec, "35290", "Neck", "Sin'dorei Pendant of Conquest", "Alt")

LoonBestInSlot:AddItem(spec, "34230", "Ring", "Ring of Omnipotence", "BIS")
LoonBestInSlot:AddItem(spec, "34362", "Ring", "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "33497", "Ring", "Mana Attuned Band", "Alt")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "34889", "Ring", "Fused Nethergon Band", "Alt")

LoonBestInSlot:AddItem(spec, "34429", "Trinket", "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "33829", "Trinket", "Hex Shrunken Head", "BIS")

LoonBestInSlot:AddItem(spec, "34182", "2H", "Grand Magister's Staff of Torrents", "BIS")
LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "Alt")

LoonBestInSlot:AddItem(spec, "34336", "MH", "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos", "Alt")
LoonBestInSlot:AddItem(spec, "35102", "MH", "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "34895", "MH", "Scryer's Blade of Focus", "Alt")

LoonBestInSlot:AddItem(spec, "34179", "OH", "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "BIS")

LoonBestInSlot:AddItem(spec, "34347", "Wand", "Wand of the Demonsoul", "BIS")
LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star", "Alt")
LoonBestInSlot:AddItem(spec, "33192", "Wand", "Carved Witch Doctor's Stick", "Alt")
