local spec = LoonBestInSlot:RegisterSpec("Warlock", "Destro", "5")
LoonBestInSlot:AddItem(spec, "34340", L["Head"], "Dark Conjuror's Collar", "BIS")
LoonBestInSlot:AddItem(spec, "34847", L["Head"], "Annihilator Holo-Gogs", "Alt")
LoonBestInSlot:AddItem(spec, "31051", L["Head"], "Hood of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34405", L["Head"], "Helm of Arcane Purity", "Alt")
LoonBestInSlot:AddItem(spec, "34339", L["Head"], "Cowl of Light's Purity", "Transmute Alt")

LoonBestInSlot:AddItem(spec, "34210", L["Shoulders"], "Amice of the Convoker", "BIS")
LoonBestInSlot:AddItem(spec, "31054", L["Shoulders"], "Mantle of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "34393", L["Shoulders"], "Shoulderpads of Knowledge's Pursuit", "Alt")
LoonBestInSlot:AddItem(spec, "34202", L["Shoulders"], "Shawl of Wonderment", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34607", L["Shoulders"], "Fel-tinged Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "34242", L["Back"], "Tattered Cape of Antonidas", "BIS")
LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "34364", L["Chest"], "Sunfire Robe", "BIS")
LoonBestInSlot:AddItem(spec, "34232", L["Chest"], "Fel Conquerer Raiments", "BIS")
LoonBestInSlot:AddItem(spec, "34399", L["Chest"], "Robes of Ghostly Hatred", "Alt")
LoonBestInSlot:AddItem(spec, "34233", L["Chest"], "Robes of Faltered Light", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30107", L["Chest"], "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "31052", L["Chest"], "Robe of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34936", L["Chest"], "Tormented Demonsoul Robes", "Alt")
LoonBestInSlot:AddItem(spec, "34610", L["Chest"], "Scarlet Sin'dorei Robes", "Alt")

LoonBestInSlot:AddItem(spec, "34436", L["Bracers"], "Bracers of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "34848", L["Bracers"], "Bracers of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32586", L["Bracers"], "Bracers of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "34344", L["Gloves"], "Handguards of Defiled Worlds", "BIS")
LoonBestInSlot:AddItem(spec, "34406", L["Gloves"], "Gloves of Tyri's Power", "Alt")
LoonBestInSlot:AddItem(spec, "34342", L["Gloves"], "Handguards of the Dawn", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "34366", L["Gloves"], "Sunfire Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "31050", L["Gloves"], "Gloves of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34938", L["Gloves"], "Enslaved Doomguard Soulgrips", "Alt")
LoonBestInSlot:AddItem(spec, "34808", L["Gloves"], "Gloves of Arcane Acuity", "Alt")

LoonBestInSlot:AddItem(spec, "34541", L["Belt"], "Belt of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "30038", L["Belt"], "Belt of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "30888", L["Belt"], "Anetheron's Noose", "Alt")
LoonBestInSlot:AddItem(spec, "32256", L["Belt"], "Waistwrap of Infinity", "Alt")

LoonBestInSlot:AddItem(spec, "34181", L["Legs"], "Leggings of Calamity", "BIS")
LoonBestInSlot:AddItem(spec, "34386", L["Legs"], "Pantaloons of Growing Strife", "Alt")
LoonBestInSlot:AddItem(spec, "34170", L["Legs"], "Pantaloons of Calming Strife", "Transmute Alt")
LoonBestInSlot:AddItem(spec, "30916", L["Legs"], "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "32367", L["Legs"], "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "31053", L["Legs"], "Leggings of the Malefic", "Alt")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "34937", L["Legs"], "Corrupted Soulcloth Pantaloons", "Alt")

LoonBestInSlot:AddItem(spec, "34564", L["Feet"], "Boots of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "34856", L["Feet"], "Boots of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32239", L["Feet"], "Slippers of the Seacaller", "Alt")
LoonBestInSlot:AddItem(spec, "34919", L["Feet"], "Boots of Incantations", "Alt")

LoonBestInSlot:AddItem(spec, "34359", L["Neck"], "Pendant of Sunfire", "BIS")
LoonBestInSlot:AddItem(spec, "34204", L["Neck"], "Amulet of Unfettered Magics", "BIS")
LoonBestInSlot:AddItem(spec, "32349", L["Neck"], "Translucent Spellthread Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "37928", L["Neck"], "Guardian's Pendant of Subjugation", "Alt")
LoonBestInSlot:AddItem(spec, "35290", L["Neck"], "Sin'dorei Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "33281", L["Neck"], "Brooch of Nature's Mercy", "Alt")
LoonBestInSlot:AddItem(spec, "34678", L["Neck"], "Shattered Sun Pendant of Acumen", "Alt")

LoonBestInSlot:AddItem(spec, "34230", L["Ring"], "Ring of Omnipotence", "BIS")
LoonBestInSlot:AddItem(spec, "34362", L["Ring"], "Loop of Forged Power", "BIS")
LoonBestInSlot:AddItem(spec, "33497", L["Ring"], "Mana Attuned Band", "Alt")
LoonBestInSlot:AddItem(spec, "32247", L["Ring"], "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "32527", L["Ring"], "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "34889", L["Ring"], "Fused Nethergon Band", "Alt")

LoonBestInSlot:AddItem(spec, "34429", L["Trinket"], "Shifting Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "32483", L["Trinket"], "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "33829", L["Trinket"], "Hex Shrunken Head", "BIS")

LoonBestInSlot:AddItem(spec, "34182", L["2H"], "Grand Magister's Staff of Torrents", "BIS")
LoonBestInSlot:AddItem(spec, "32374", L["2H"], "Zhar'doom, Greatstaff of the Devourer", "Alt")

LoonBestInSlot:AddItem(spec, "34336", L["MH"], "Sunflare", "BIS")
LoonBestInSlot:AddItem(spec, "30910", L["MH"], "Tempest of Chaos", "Alt")
LoonBestInSlot:AddItem(spec, "35102", L["MH"], "Brutal Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "34895", L["MH"], "Scryer's Blade of Focus", "Alt")

LoonBestInSlot:AddItem(spec, "34179", L["OH"], "Heart of the Pit", "BIS")
LoonBestInSlot:AddItem(spec, "30872", L["OH"], "Chronicle of Dark Secrets", "BIS")

LoonBestInSlot:AddItem(spec, "34347", L["Wand"], "Wand of the Demonsoul", "BIS")
LoonBestInSlot:AddItem(spec, "29982", L["Wand"], "Wand of the Forgotten Star", "Alt")
LoonBestInSlot:AddItem(spec, "33192", L["Wand"], "Carved Witch Doctor's Stick", "Alt")
