local spec = LoonBestInSlot:RegisterSpec("Warrior", "Fury", "5")
LoonBestInSlot:AddItem(spec, "34333", L["Head"], "Coif of Alleria", "BIS")
LoonBestInSlot:AddItem(spec, "34345", L["Head"], "Crown of Anasterian", "BIS")
LoonBestInSlot:AddItem(spec, "34354", L["Head"], "Mayhem Projection Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "Alt")

LoonBestInSlot:AddItem(spec, "34388", L["Shoulders"], "Pauldrons of Berserking", "BIS")
LoonBestInSlot:AddItem(spec, "34192", L["Shoulders"], "Pauldrons of Perseverance", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34392", L["Shoulders"], "Demontooth Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "34195", L["Shoulders"], "Shoulderpads of Vehemence", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34194", L["Shoulders"], "Mantle of the Golden Forest", "BIS")
LoonBestInSlot:AddItem(spec, "30979", L["Shoulders"], "Onslaught Shoulderblades", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32570", L["Shoulders"], "Swiftsteel Shoulders", "Alt")

LoonBestInSlot:AddItem(spec, "34241", L["Back"], "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "Alt")
LoonBestInSlot:AddItem(spec, "33484", L["Back"], "Dory's Embrace", "Alt")
LoonBestInSlot:AddItem(spec, "33122", L["Back"], "Cloak of Darkness", "BIS")

LoonBestInSlot:AddItem(spec, "34397", L["Chest"], "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", L["Chest"], "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34377", L["Chest"], "Hard Khorium Battleplate", "BIS")
LoonBestInSlot:AddItem(spec, "34215", L["Chest"], "Warharness of Reckless Fury", "Alt")
LoonBestInSlot:AddItem(spec, "30975", L["Chest"], "Onslaught Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "34441", L["Bracers"], "Onslaught Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34851", L["Bracers"], "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "32574", L["Bracers"], "Bindings of Lightning Reflexes", "BIS")

LoonBestInSlot:AddItem(spec, "34343", L["Gloves"], "Thalassian Ranger Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34370", L["Gloves"], "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "34341", L["Gloves"], "Borderland Paingrips", "Alt")
LoonBestInSlot:AddItem(spec, "32278", L["Gloves"], "Grips of Silent Justice", "Alt")

LoonBestInSlot:AddItem(spec, "34546", L["Belt"], "Onslaught Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34854", L["Belt"], "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")

LoonBestInSlot:AddItem(spec, "34180", L["Legs"], "Felfury Legplates", "BIS")
LoonBestInSlot:AddItem(spec, "34188", L["Legs"], "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "32341", L["Legs"], "Leggings of Divine Retribution", "Alt")

LoonBestInSlot:AddItem(spec, "34569", L["Feet"], "Onslaught Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34857", L["Feet"], "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32345", L["Feet"], "Dreadboots of the Legion", "Alt")

LoonBestInSlot:AddItem(spec, "34358", L["Neck"], "Hard Khorium Choker", "BIS")
LoonBestInSlot:AddItem(spec, "34177", L["Neck"], "Clutch of Demise", "BIS")
LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "Alt")

LoonBestInSlot:AddItem(spec, "34189", L["Ring"], "Band of Ruinous Delight", "BIS")
LoonBestInSlot:AddItem(spec, "34361", L["Ring"], "Hard Khorium Band", "BIS")
LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "34887", L["Ring"], "Angelista's Revenge", "Alt")
LoonBestInSlot:AddItem(spec, "33496", L["Ring"], "Signet of Primal Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "32335", L["Ring"], "Unstoppable Aggressor's Ring", "Alt")

LoonBestInSlot:AddItem(spec, "34427", L["Trinket"], "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "34472", L["Trinket"], "Shard of Contempt", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "33831", L["Trinket"], "Berserker's Call", "Alt")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "32837", L["MH"], "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "35101", L["MH"], "Brutal Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "34996", L["MH"], "Brutal Gladiator's Cleaver", "Alt")
LoonBestInSlot:AddItem(spec, "34214", L["MH"], "Muramasa", "Alt")
LoonBestInSlot:AddItem(spec, "34331", L["MH"], "Hand of the Deceiver", "Alt")

LoonBestInSlot:AddItem(spec, "32838", L["OH"], "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "34346", L["OH"], "Mounting Vengeance", "Alt")
LoonBestInSlot:AddItem(spec, "34164", L["OH"], "Dragonscale-Encrusted Longblade", "Alt")

LoonBestInSlot:AddItem(spec, "34196", L["Ranged"], "Golden Bow of Quel'Thalas", "BIS")
LoonBestInSlot:AddItem(spec, "34892", L["Ranged"], "Crossbow of Relentless Strikes", "BIS")
LoonBestInSlot:AddItem(spec, "33474", L["Ranged"], "Ancient Amani Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "32326", L["Ranged"], "Twisted Blades of Zarak", "Alt")
LoonBestInSlot:AddItem(spec, "30105", L["Ranged"], "Serpent Spine Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "30724", L["Ranged"], "Barrel-Blade Longrifle", "Alt")
