local spec = LoonBestInSlot:RegisterSpec("Warrior", "Arms", "5")
LoonBestInSlot:AddItem(spec, "34333", "Head", "Coif of Alleria", "BIS")
LoonBestInSlot:AddItem(spec, "34345", "Head", "Crown of Anasterian", "BIS")
LoonBestInSlot:AddItem(spec, "34354", "Head", "Mayhem Projection Goggles", "Alt")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "Alt")

LoonBestInSlot:AddItem(spec, "34388", "Shoulders", "Pauldrons of Berserking", "BIS")
LoonBestInSlot:AddItem(spec, "34192", "Shoulders", "Pauldrons of Perseverance", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34392", "Shoulders", "Demontooth Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "34195", "Shoulders", "Shoulderpads of Vehemence", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34194", "Shoulders", "Mantle of the Golden Forest", "BIS")
LoonBestInSlot:AddItem(spec, "30979", "Shoulders", "Onslaught Shoulderblades", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32570", "Shoulders", "Swiftsteel Shoulders", "BIS")

LoonBestInSlot:AddItem(spec, "34241", "Back", "Cloak of Unforgivable Sin", "BIS")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "Alt")
LoonBestInSlot:AddItem(spec, "33484", "Back", "Dory's Embrace", "Alt")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "34397", "Chest", "Bladed Chaos Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "34211", "Chest", "Harness of Carnal Instinct", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34377", "Chest", "Hard Khorium Battleplate", "BIS")
LoonBestInSlot:AddItem(spec, "34215", "Chest", "Warharness of Reckless Fury", "Alt")
LoonBestInSlot:AddItem(spec, "30975", "Chest", "Onslaught Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "33728", "Chest", "Vengeful Gladiator's Plate Chestpiece", "Alt")

LoonBestInSlot:AddItem(spec, "34441", "Bracers", "Onslaught Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "34851", "Bracers", "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "BIS")

LoonBestInSlot:AddItem(spec, "34343", "Gloves", "Thalassian Ranger Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "34370", "Gloves", "Gloves of Immortal Dusk", "BIS")
LoonBestInSlot:AddItem(spec, "34341", "Gloves", "Borderland Paingrips", "BIS")
LoonBestInSlot:AddItem(spec, "32278", "Gloves", "Grips of Silent Justice", "Alt")

LoonBestInSlot:AddItem(spec, "34546", "Belt", "Onslaught Belt", "BIS")
LoonBestInSlot:AddItem(spec, "34854", "Belt", "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "33331", "Belt", "Chain of Unleashed Rage", "Alt")

LoonBestInSlot:AddItem(spec, "34180", "Legs", "Felfury Legplates", "BIS")
LoonBestInSlot:AddItem(spec, "34188", "Legs", "Leggings of the Immortal Night", "BIS")
LoonBestInSlot:AddItem(spec, "32341", "Legs", "Leggings of Divine Retribution", "Alt")

LoonBestInSlot:AddItem(spec, "34569", "Feet", "Onslaught Treads", "BIS")
LoonBestInSlot:AddItem(spec, "34857", "Feet", "Boots of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion", "Alt")

LoonBestInSlot:AddItem(spec, "34358", "Neck", "Hard Khorium Choker", "BIS")
LoonBestInSlot:AddItem(spec, "34177", "Neck", "Clutch of Demise", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "Alt")

LoonBestInSlot:AddItem(spec, "34189", "Ring", "Band of Ruinous Delight", "BIS")
LoonBestInSlot:AddItem(spec, "34361", "Ring", "Hard Khorium Band", "BIS")
LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "34887", "Ring", "Angelista's Revenge", "BIS")
LoonBestInSlot:AddItem(spec, "33496", "Ring", "Signet of Primal Wrath", "Alt")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring", "Alt")

LoonBestInSlot:AddItem(spec, "34427", "Trinket", "Blackened Naaru Sliver", "BIS")
LoonBestInSlot:AddItem(spec, "34472", "Trinket", "Shard of Contempt", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "33831", "Trinket", "Berserker's Call", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "34247", "2H", "Apolyon, the Soul-Render", "BIS")
LoonBestInSlot:AddItem(spec, "30902", "2H", "Cataclysm's Edge", "BIS")
LoonBestInSlot:AddItem(spec, "32348", "2H", "Soul Cleaver", "BIS")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "BIS")

LoonBestInSlot:AddItem(spec, "32837", "MH", "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "35101", "MH", "Brutal Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "34996", "MH", "Brutal Gladiator's Cleaver", "Alt")
LoonBestInSlot:AddItem(spec, "34214", "MH", "Muramasa", "Alt")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike", "Alt")

LoonBestInSlot:AddItem(spec, "32838", "OH", "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "35072", "OH", "Brutal Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "34164", "OH", "Dragonscale-Encrusted Longblade", "Alt")

LoonBestInSlot:AddItem(spec, "34196", "Ranged", "Golden Bow of Quel'Thalas", "BIS")
LoonBestInSlot:AddItem(spec, "34892", "Ranged", "Crossbow of Relentless Strikes", "BIS")
LoonBestInSlot:AddItem(spec, "33474", "Ranged", "Ancient Amani Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "32326", "Ranged", "Twisted Blades of Zarak", "Alt")
LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "Alt")
