local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "5")
LoonBestInSlot:AddItem(spec, "34400", "Head", "Crown of Dath'Remar", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34345", "Head", "Crown of Anasterian", "Transmute BIS Mit")
LoonBestInSlot:AddItem(spec, "34357", "Head", "Hard Khorium Goggles", "BIS Mit")
LoonBestInSlot:AddItem(spec, "35068", "Head", "Brutal Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34354", "Head", "Mayhem Projection Goggles", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "35070", "Shoulders", "Brutal Gladiator's Plate Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "34388", "Shoulders", "Pauldrons of Berserking", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34192", "Shoulders", "Pauldrons of Perseverance", "Transmute BIS Thrt")
LoonBestInSlot:AddItem(spec, "30980", "Shoulders", "Onslaught Shoulderguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34190", "Back", "Crimson Paragon's Cover", "BIS")
LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification", "Alt")

LoonBestInSlot:AddItem(spec, "35066", "Chest", "Brutal Gladiator's Plate Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "34377", "Chest", "Hard Khorium Battleplate", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34215", "Chest", "Warharness of Reckless Fury", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34394", "Chest", "Breastplate of Agony's Aversion", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30976", "Chest", "Onslaught Chestguard", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34442", "Bracers", "Onslaught Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34851", "Bracers", "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "33516", "Bracers", "Bracers of the Ancient Phalanx", "Alt")
LoonBestInSlot:AddItem(spec, "32232", "Bracers", "Eternium Shell Bracers", "Alt Mit")

LoonBestInSlot:AddItem(spec, "32280", "Gloves", "Gauntlets of Enforcement", "Alt")
LoonBestInSlot:AddItem(spec, "34378", "Gloves", "Hard Khorium Battlefists", "Alt")
LoonBestInSlot:AddItem(spec, "34341", "Gloves", "Borderland Paingrips", "Alt")
LoonBestInSlot:AddItem(spec, "34352", "Gloves", "Borderland Fortress Grips", "BIS Mit")

LoonBestInSlot:AddItem(spec, "34547", "Belt", "Onslaught Waistguard", "BIS")
LoonBestInSlot:AddItem(spec, "34854", "Belt", "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34941", "Belt", "Girdle of the Fearless", "Alt")

LoonBestInSlot:AddItem(spec, "34381", "Legs", "Felstrength Legplates", "BIS")
LoonBestInSlot:AddItem(spec, "34180", "Legs", "Felfury Legplates", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34940", "Legs", "Sunguard Legplates", "Alt")
LoonBestInSlot:AddItem(spec, "35069", "Legs", "Brutal Gladiator's Plate Legguards", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34382", "Legs", "Judicator's Legguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34167", "Legs", "Legplates of the Holy Juggernaut", "Transmute Alt Mit")

LoonBestInSlot:AddItem(spec, "34568", "Feet", "Onslaught Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34857", "Feet", "Boots of the Forgotten Protector", "BIS")

LoonBestInSlot:AddItem(spec, "34178", "Neck", "Collar of the Pit Lord", "BIS")
LoonBestInSlot:AddItem(spec, "33296", "Neck", "Brooch of Deftness", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34680", "Neck", "Shattered Sun Pendant of Resolve", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34213", "Ring", "Ring of Hardened Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "34888", "Ring", "Ring of the Stalwart Protector", "BIS")
LoonBestInSlot:AddItem(spec, "29296", "Ring", "Band of Eternity", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34361", "Ring", "Hard Khorium Band", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34887", "Ring", "Angelista's Revenge", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33496", "Ring", "Signet of Primal Wrath", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "34473", "Trinket", "Commendation of Kael'thas", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance", "Alt Stam")
LoonBestInSlot:AddItem(spec, "31859", "Trinket", "Darkmoon Card: Madness", "Alt Stam")
LoonBestInSlot:AddItem(spec, "33830", "Trinket", "Ancient Aqir Artifact", "BIS")
LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "Alt")
LoonBestInSlot:AddItem(spec, "34472", "Trinket", "Shard of Contempt", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34428", "Trinket", "Steely Naaru Sliver", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "Snap Thrt")

LoonBestInSlot:AddItem(spec, "34164", "MH", "Dragonscale-Encrusted Longblade", "BIS")
LoonBestInSlot:AddItem(spec, "32254", "MH", "The Brutalizer", "Alt")
LoonBestInSlot:AddItem(spec, "32369", "MH", "Blade of Savagery", "Alt")
LoonBestInSlot:AddItem(spec, "34165", "MH", "Fang of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "30874", "MH", "The Unbreakable Will", "BIS Mit")

LoonBestInSlot:AddItem(spec, "34185", "Shield", "Sword Breaker's Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "32375", "Shield", "Bulwark of Azzinoth", "Alt")
LoonBestInSlot:AddItem(spec, "35094", "Shield", "Brutal Gladiator's Shield Wall", "Alt")

LoonBestInSlot:AddItem(spec, "32253", "Ranged", "Legionkiller", "BIS")
LoonBestInSlot:AddItem(spec, "34349", "Ranged", "Blade of Life's Inevitability", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "Alt")
LoonBestInSlot:AddItem(spec, "32325", "Ranged", "Rifle of the Stoic Guardian", "BIS Mit")
