local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "5")
LoonBestInSlot:AddItem(spec, "34400", L["Head"], "Crown of Dath'Remar", "BIS Mit")
LoonBestInSlot:AddItem(spec, "34345", L["Head"], "Crown of Anasterian", "Transmute BIS Mit")
LoonBestInSlot:AddItem(spec, "34357", L["Head"], "Hard Khorium Goggles", "BIS Mit")
LoonBestInSlot:AddItem(spec, "35068", L["Head"], "Brutal Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34354", L["Head"], "Mayhem Projection Goggles", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "35070", L["Shoulders"], "Brutal Gladiator's Plate Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "34388", L["Shoulders"], "Pauldrons of Berserking", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34192", L["Shoulders"], "Pauldrons of Perseverance", "Transmute BIS Thrt")
LoonBestInSlot:AddItem(spec, "30980", L["Shoulders"], "Onslaught Shoulderguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34190", L["Back"], "Crimson Paragon's Cover", "BIS")
LoonBestInSlot:AddItem(spec, "34010", L["Back"], "Pepe's Shroud of Pacification", "Alt")

LoonBestInSlot:AddItem(spec, "35066", L["Chest"], "Brutal Gladiator's Plate Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "34377", L["Chest"], "Hard Khorium Battleplate", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34215", L["Chest"], "Warharness of Reckless Fury", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34394", L["Chest"], "Breastplate of Agony's Aversion", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30976", L["Chest"], "Onslaught Chestguard", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34442", L["Bracers"], "Onslaught Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "34851", L["Bracers"], "Bracers of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "33516", L["Bracers"], "Bracers of the Ancient Phalanx", "Alt")
LoonBestInSlot:AddItem(spec, "32232", L["Bracers"], "Eternium Shell Bracers", "Alt Mit")

LoonBestInSlot:AddItem(spec, "32280", L["Gloves"], "Gauntlets of Enforcement", "Alt")
LoonBestInSlot:AddItem(spec, "34378", L["Gloves"], "Hard Khorium Battlefists", "Alt")
LoonBestInSlot:AddItem(spec, "34341", L["Gloves"], "Borderland Paingrips", "Alt")
LoonBestInSlot:AddItem(spec, "34352", L["Gloves"], "Borderland Fortress Grips", "BIS Mit")

LoonBestInSlot:AddItem(spec, "34547", L["Belt"], "Onslaught Waistguard", "BIS")
LoonBestInSlot:AddItem(spec, "34854", L["Belt"], "Belt of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "34941", L["Belt"], "Girdle of the Fearless", "Alt")

LoonBestInSlot:AddItem(spec, "34381", L["Legs"], "Felstrength Legplates", "BIS")
LoonBestInSlot:AddItem(spec, "34180", L["Legs"], "Felfury Legplates", "Transmute BIS")
LoonBestInSlot:AddItem(spec, "34940", L["Legs"], "Sunguard Legplates", "Alt")
LoonBestInSlot:AddItem(spec, "35069", L["Legs"], "Brutal Gladiator's Plate Legguards", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "34382", L["Legs"], "Judicator's Legguards", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34167", L["Legs"], "Legplates of the Holy Juggernaut", "Transmute Alt Mit")

LoonBestInSlot:AddItem(spec, "34568", L["Feet"], "Onslaught Boots", "BIS")
LoonBestInSlot:AddItem(spec, "34857", L["Feet"], "Boots of the Forgotten Protector", "BIS")

LoonBestInSlot:AddItem(spec, "34178", L["Neck"], "Collar of the Pit Lord", "BIS")
LoonBestInSlot:AddItem(spec, "33296", L["Neck"], "Brooch of Deftness", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34680", L["Neck"], "Shattered Sun Pendant of Resolve", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34213", L["Ring"], "Ring of Hardened Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "34888", L["Ring"], "Ring of the Stalwart Protector", "BIS")
LoonBestInSlot:AddItem(spec, "29296", L["Ring"], "Band of Eternity", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34361", L["Ring"], "Hard Khorium Band", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34887", L["Ring"], "Angelista's Revenge", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33496", L["Ring"], "Signet of Primal Wrath", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "34473", L["Trinket"], "Commendation of Kael'thas", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31858", L["Trinket"], "Darkmoon Card: Vengeance", "Alt Stam")
LoonBestInSlot:AddItem(spec, "31859", L["Trinket"], "Darkmoon Card: Madness", "Alt Stam")
LoonBestInSlot:AddItem(spec, "33830", L["Trinket"], "Ancient Aqir Artifact", "BIS")
LoonBestInSlot:AddItem(spec, "28528", L["Trinket"], "Moroes' Lucky Pocket Watch", "Alt")
LoonBestInSlot:AddItem(spec, "34472", L["Trinket"], "Shard of Contempt", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34428", L["Trinket"], "Steely Naaru Sliver", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "21670", L["Trinket"], "Badge of the Swarmguard", "Snap Thrt")

LoonBestInSlot:AddItem(spec, "34164", L["MH"], "Dragonscale-Encrusted Longblade", "BIS")
LoonBestInSlot:AddItem(spec, "32254", L["MH"], "The Brutalizer", "Alt")
LoonBestInSlot:AddItem(spec, "32369", L["MH"], "Blade of Savagery", "Alt")
LoonBestInSlot:AddItem(spec, "34165", L["MH"], "Fang of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "30874", L["MH"], "The Unbreakable Will", "BIS Mit")

LoonBestInSlot:AddItem(spec, "34185", L["Shield"], "Sword Breaker's Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "32375", L["Shield"], "Bulwark of Azzinoth", "Alt")
LoonBestInSlot:AddItem(spec, "35094", L["Shield"], "Brutal Gladiator's Shield Wall", "Alt")

LoonBestInSlot:AddItem(spec, "32253", L["Ranged"], "Legionkiller", "BIS")
LoonBestInSlot:AddItem(spec, "34349", L["Ranged"], "Blade of Life's Inevitability", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "29949", L["Ranged"], "Arcanite Steam-Pistol", "Alt")
LoonBestInSlot:AddItem(spec, "32325", L["Ranged"], "Rifle of the Stoic Guardian", "BIS Mit")
