local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "3")
LoonBestInSlot:AddItem(spec, "31039", L["Head"], "Thunderheart Cover", "BIS Mit")
LoonBestInSlot:AddItem(spec, "31096", L["Head"], "Helm of the Forgotten Vanquisher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33672", L["Head"], "Vengeful Gladiator's Dragonhide Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "Alt")
LoonBestInSlot:AddItem(spec, "30228", L["Head"], "Nordrassil Headdress", "Alt")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "31048", L["Shoulders"], "Thunderheart Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "33674", L["Shoulders"], "Vengeful Gladiator's Dragonhide Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "30230", L["Shoulders"], "Nordrassil Feral-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30917", L["Shoulders"], "Razorfury Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "28660", L["Back"], "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34010", L["Back"], "Pepe's Shroud of Pacification", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "31042", L["Chest"], "Thunderheart Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30222", L["Chest"], "Nordrassil Chestplate", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33675", L["Chest"], "Vengeful Gladiator's Dragonhide Tunic", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32252", L["Chest"], "Nether Shadow Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "30905", L["Chest"], "Midnight Chestguard", "Alt")

LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "33881", L["Bracers"], "Vindicator's Dragonhide Bracers", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33893", L["Bracers"], "Vindicator's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32580", L["Bracers"], "Swiftstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "31034", L["Gloves"], "Thunderheart Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30223", L["Gloves"], "Nordrassil Handgrips", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33671", L["Gloves"], "Vengeful Gladiator's Dragonhide Gloves", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30879", L["Belt"], "Don Alejandro's Money Belt", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33879", L["Belt"], "Vindicator's Dragonhide Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31044", L["Legs"], "Thunderheart Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30229", L["Legs"], "Nordrassil Feral-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30898", L["Legs"], "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "33673", L["Legs"], "Vengeful Gladiator's Dragonhide Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "32593", L["Feet"], "Treads of the Den Mother", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33880", L["Feet"], "Vindicator's Dragonhide Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30041", L["Feet"], "Boots of Natural Grace", "Alt")
LoonBestInSlot:AddItem(spec, "33892", L["Feet"], "Vindicator's Leather Boots", "Alt")

LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "33923", L["Neck"], "Vindicator's Pendant of Triumph", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32362", L["Neck"], "Pendant of Titans", "BIS Mit")

LoonBestInSlot:AddItem(spec, "29279", L["Ring"], "Violet Signet of the Great Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28792", L["Ring"], "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29300", L["Ring"], "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "Alt")

LoonBestInSlot:AddItem(spec, "32501", L["Trinket"], "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "34578", L["Trinket"], "Battlemaster's Determination", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "38287", L["Trinket"], "Empty Mug of Direbrew", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32658", L["Trinket"], "Badge of Tenacity", "Alt")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "34576", L["Trinket"], "Battlemaster's Cruelty", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31858", L["Trinket"], "Darkmoon Card: Vengeance", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30883", L["2H"], "Pillar of Ferocity", "BIS")
LoonBestInSlot:AddItem(spec, "33716", L["2H"], "Vengeful Gladiator's Staff", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30021", L["2H"], "Wildfury Greatstaff", "Alt")
LoonBestInSlot:AddItem(spec, "32014", L["2H"], "Merciless Gladiator's Maul", "Alt")

LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "32257", L["Idol"], "Idol of the White Stag", "BIS")
LoonBestInSlot:AddItem(spec, "23198", L["Idol"], "Idol of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "28064", L["Idol"], "Idol of the Wild", "Alt")
