local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "3")
LoonBestInSlot:AddItem(spec, "31037", L["Head"], "Thunderheart Helmet", "BIS")
LoonBestInSlot:AddItem(spec, "31096", L["Head"], "Helm of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32329", L["Head"], "Cowl of Benevolence", "BIS")
LoonBestInSlot:AddItem(spec, "30219", L["Head"], "Nordrassil Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32479", L["Head"], "Wonderheal XT40 Shades", "Alt")
LoonBestInSlot:AddItem(spec, "32240", L["Head"], "Guise of the Tidal Lurker", "Alt")

LoonBestInSlot:AddItem(spec, "31047", L["Shoulders"], "Thunderheart Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30221", L["Shoulders"], "Nordrassil Life-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32583", L["Shoulders"], "Shoulderpads of Renewed Life", "Alt")
LoonBestInSlot:AddItem(spec, "32585", L["Shoulders"], "Swiftheal Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "32518", L["Shoulders"], "Veil of Turning Leaves", "Alt")
LoonBestInSlot:AddItem(spec, "32273", L["Shoulders"], "Amice of Brilliant Light", "Alt")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "32337", L["Back"], "Shroud of Forgiveness", "BIS")
LoonBestInSlot:AddItem(spec, "29989", L["Back"], "Sunshower Light Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "34012", L["Back"], "Shroud of the Final Stand", "Alt")

LoonBestInSlot:AddItem(spec, "31041", L["Chest"], "Thunderheart Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30216", L["Chest"], "Nordrassil Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30868", L["Bracers"], "Rejuvenating Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30871", L["Bracers"], "Bracers of Martyrdom", "BIS")
LoonBestInSlot:AddItem(spec, "32584", L["Bracers"], "Swiftheal Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "32582", L["Bracers"], "Bracers of Renewed Life", "BIS")
LoonBestInSlot:AddItem(spec, "30062", L["Bracers"], "Grove-Bands of Remulos", "Alt")
LoonBestInSlot:AddItem(spec, "32513", L["Bracers"], "Wristbands of Divine Influence", "Alt")

LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "BIS")
LoonBestInSlot:AddItem(spec, "32353", L["Gloves"], "Gloves of Unfailing Faith", "Alt")
LoonBestInSlot:AddItem(spec, "31032", L["Gloves"], "Thunderheart Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "28521", L["Gloves"], "Mitts of the Treemender", "Alt")

LoonBestInSlot:AddItem(spec, "30895", L["Belt"], "Angelista's Sash", "BIS")
LoonBestInSlot:AddItem(spec, "32339", L["Belt"], "Belt of Primal Majesty", "BIS")
LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "Alt")
LoonBestInSlot:AddItem(spec, "32519", L["Belt"], "Belt of Divine Guidance", "Alt")
LoonBestInSlot:AddItem(spec, "30036", L["Belt"], "Belt of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "29984", L["Belt"], "Girdle of Zaetar", "Alt")

LoonBestInSlot:AddItem(spec, "30912", L["Legs"], "Leggings of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "32271", L["Legs"], "Kilt of Immortal Nature", "Alt")
LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "Alt")
LoonBestInSlot:AddItem(spec, "31045", L["Legs"], "Thunderheart Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "28591", L["Legs"], "Earthsoul Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "32609", L["Feet"], "Boots of the Divine Light", "BIS")
LoonBestInSlot:AddItem(spec, "30092", L["Feet"], "Orca-Hide Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30885", L["Feet"], "Archbishop's Slippers", "Alt")
LoonBestInSlot:AddItem(spec, "30886", L["Feet"], "Enchanted Leather Sandals", "Alt")

LoonBestInSlot:AddItem(spec, "30018", L["Neck"], "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "32370", L["Neck"], "Nadina's Pendant of Purity", "Alt")
LoonBestInSlot:AddItem(spec, "30726", L["Neck"], "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "33922", L["Neck"], "Vindicator's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "30110", L["Ring"], "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "29309", L["Ring"], "Band of the Eternal Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", L["Ring"], "Jade Ring of the Everliving", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "32486", L["Trinket"], "Ashtongue Talisman of Equilibrium", "Alt")

LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "33743", L["MH"], "Vengeful Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30108", L["MH"], "Lightfathom Scepter", "Alt")
LoonBestInSlot:AddItem(spec, "30918", L["MH"], "Hammer of Atonement", "Alt")

LoonBestInSlot:AddItem(spec, "30908", L["2H"], "Apostle of Argus", "BIS")
LoonBestInSlot:AddItem(spec, "32344", L["2H"], "Staff of Immaculate Recovery", "Alt")
LoonBestInSlot:AddItem(spec, "29981", L["2H"], "Ethereum Life-Staff", "Alt")

LoonBestInSlot:AddItem(spec, "30911", L["OH"], "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "29274", L["OH"], "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "32350", L["OH"], "Touch of Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "29170", L["OH"], "Windcaller's Orb", "Alt")

LoonBestInSlot:AddItem(spec, "27886", L["Idol"], "Idol of the Emerald Queen", "BIS")
