local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear", "3")
LoonBestInSlot:AddItem(spec, "31039", "Head", "Thunderheart Cover", "BIS Mit")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33672", "Head", "Vengeful Gladiator's Dragonhide Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "Alt")
LoonBestInSlot:AddItem(spec, "30228", "Head", "Nordrassil Headdress", "Alt")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "31048", "Shoulders", "Thunderheart Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "33674", "Shoulders", "Vengeful Gladiator's Dragonhide Spaulders", "Alt")
LoonBestInSlot:AddItem(spec, "30230", "Shoulders", "Nordrassil Feral-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30917", "Shoulders", "Razorfury Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak", "BIS Mit")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "31042", "Chest", "Thunderheart Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30222", "Chest", "Nordrassil Chestplate", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33675", "Chest", "Vengeful Gladiator's Dragonhide Tunic", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "Alt")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "33881", "Bracers", "Vindicator's Dragonhide Bracers", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33893", "Bracers", "Vindicator's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "31034", "Gloves", "Thunderheart Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30223", "Gloves", "Nordrassil Handgrips", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33671", "Gloves", "Vengeful Gladiator's Dragonhide Gloves", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33879", "Belt", "Vindicator's Dragonhide Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31044", "Legs", "Thunderheart Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30229", "Legs", "Nordrassil Feral-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "33673", "Legs", "Vengeful Gladiator's Dragonhide Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "32593", "Feet", "Treads of the Den Mother", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33880", "Feet", "Vindicator's Dragonhide Boots", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30041", "Feet", "Boots of Natural Grace", "Alt")
LoonBestInSlot:AddItem(spec, "33892", "Feet", "Vindicator's Leather Boots", "Alt")

LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "33923", "Neck", "Vindicator's Pendant of Triumph", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans", "BIS Mit")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense", "Alt Mit")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29300", "Ring", "Band of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt")

LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "34578", "Trinket", "Battlemaster's Determination", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32658", "Trinket", "Badge of Tenacity", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "34576", "Trinket", "Battlemaster's Cruelty", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30883", "2H", "Pillar of Ferocity", "BIS")
LoonBestInSlot:AddItem(spec, "33716", "2H", "Vengeful Gladiator's Staff", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30021", "2H", "Wildfury Greatstaff", "Alt")
LoonBestInSlot:AddItem(spec, "32014", "2H", "Merciless Gladiator's Maul", "Alt")

LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "32257", "Idol", "Idol of the White Stag", "BIS")
LoonBestInSlot:AddItem(spec, "23198", "Idol", "Idol of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild", "Alt")
