local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "3")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "31048", "Shoulders", "Thunderheart Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30230", "Shoulders", "Nordrassil Feral-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "33674", "Shoulders", "Vengeful Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "31042", "Chest", "Thunderheart Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30222", "Chest", "Nordrassil Chestplate", "Alt")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "33675", "Chest", "Vengeful Gladiator's Dragonhide Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "33881", "Bracers", "Vindicator's Dragonhide Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "33893", "Bracers", "Vindicator's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "Alt")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "31034", "Gloves", "Thunderheart Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30223", "Gloves", "Nordrassil Handgrips", "Alt")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "Alt")
LoonBestInSlot:AddItem(spec, "32265", "Belt", "Shadow-walker's Cord", "Alt")
LoonBestInSlot:AddItem(spec, "33879", "Belt", "Vindicator's Dragonhide Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31044", "Legs", "Thunderheart Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30229", "Legs", "Nordrassil Feral-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "33673", "Legs", "Vengeful Gladiator's Dragonhide Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "33880", "Feet", "Vindicator's Dragonhide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "BIS")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring", "Alt")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "Alt")

LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32658", "Trinket", "Badge of Tenacity", "Alt")

LoonBestInSlot:AddItem(spec, "33716", "2H", "Vengeful Gladiator's Staff", "BIS")
LoonBestInSlot:AddItem(spec, "32014", "2H", "Merciless Gladiator's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "30883", "2H", "Pillar of Ferocity", "Alt")

LoonBestInSlot:AddItem(spec, "29390", "Idol", "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "32257", "Idol", "Idol of the White Stag", "Alt")
LoonBestInSlot:AddItem(spec, "28372", "Idol", "Idol of Feral Shadows", "Alt")
