local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "3")
LoonBestInSlot:AddItem(spec, "31040", "Head", "Thunderheart Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "Alt")
LoonBestInSlot:AddItem(spec, "30233", "Head", "Nordrassil Headpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer", "Alt")
LoonBestInSlot:AddItem(spec, "32480", "Head", "Magnified Moon Specs", "Alt")

LoonBestInSlot:AddItem(spec, "31049", "Shoulders", "Thunderheart Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30235", "Shoulders", "Nordrassil Wrath-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings", "Alt")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "Alt")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "Alt")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt")

LoonBestInSlot:AddItem(spec, "31043", "Chest", "Thunderheart Vest", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30231", "Chest", "Nordrassil Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin", "Alt")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "Alt")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "32351", "Bracers", "Elunite Empowered Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands", "Alt")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "31035", "Gloves", "Thunderheart Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30232", "Gloves", "Nordrassil Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "Alt")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "Alt")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "29092", "Gloves", "Gloves of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "BIS")
LoonBestInSlot:AddItem(spec, "30914", "Belt", "Belt of the Crescent Moon", "Alt")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "Alt")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "BIS")
LoonBestInSlot:AddItem(spec, "31046", "Legs", "Thunderheart Pants", "Alt")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "Alt")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "Alt")
LoonBestInSlot:AddItem(spec, "30234", "Legs", "Nordrassil Wrath-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer", "Alt")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "32352", "Feet", "Naturewarden's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes", "Alt")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling", "Alt")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers", "Alt")

LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "35319", "Neck", "Vindicator's Pendant of Subjugation", "BIS")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "33920", "Neck", "Vindicator's Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "Alt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night", "Alt")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "Alt")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "Alt")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "Alt")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "32486", "Trinket", "Ashtongue Talisman of Equilibrium", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "Alt")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "Alt")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "19379", "Trinket", "Neltharion's Tear", "Alt")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "23046", "Trinket", "The Restrained Essence of Sapphiron", "Alt")

LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "33763", "MH", "Vengeful Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury", "BIS")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement", "BIS")
LoonBestInSlot:AddItem(spec, "32963", "MH", "Merciless Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "32053", "MH", "Merciless Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "Alt")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "34540", "2H", "Vengeful Gladiator's Battle Staff", "Alt")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key", "Alt")
LoonBestInSlot:AddItem(spec, "33766", "2H", "Vengeful Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "32055", "2H", "Merciless Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "24557", "2H", "Gladiator's War Staff", "Alt")
LoonBestInSlot:AddItem(spec, "35514", "2H", "Frostscythe of Lord Ahune", "Alt")
LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "Alt")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff", "Alt")

LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "32361", "OH", "Blind-Seers Icon", "Alt")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone", "Alt")
LoonBestInSlot:AddItem(spec, "29271", "OH", "Talisman of Kalecgos", "Alt")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "Alt")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack", "Alt")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance", "Alt")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane", "Alt")

LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "27518", "Idol", "Ivory Idol of the Moongoddess", "BIS")
LoonBestInSlot:AddItem(spec, "31025", "Idol", "Idol of the Avenger", "Alt")
LoonBestInSlot:AddItem(spec, "23197", "Idol", "Idol of the Moon", "Alt")
