local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat", "3")
LoonBestInSlot:AddItem(spec, "8345", L["Head"], "Wolfshead Helm", "BIS")

LoonBestInSlot:AddItem(spec, "31048", L["Shoulders"], "Thunderheart Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "29100", L["Shoulders"], "Mantle of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29764", L["Shoulders"], "Pauldrons of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30230", L["Shoulders"], "Nordrassil Feral-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "33674", L["Shoulders"], "Vengeful Gladiator's Dragonhide Spaulders", "Alt")

LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "Alt")
LoonBestInSlot:AddItem(spec, "33122", L["Back"], "Cloak of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "32252", L["Chest"], "Nether Shadow Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "31042", L["Chest"], "Thunderheart Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "29096", L["Chest"], "Breastplate of Malorne", "Alt")
LoonBestInSlot:AddItem(spec, "29753", L["Chest"], "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30222", L["Chest"], "Nordrassil Chestplate", "Alt")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30905", L["Chest"], "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "33675", L["Chest"], "Vengeful Gladiator's Dragonhide Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "33881", L["Bracers"], "Vindicator's Dragonhide Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "33893", L["Bracers"], "Vindicator's Leather Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29966", L["Bracers"], "Vambraces of Ending", "Alt")
LoonBestInSlot:AddItem(spec, "32580", L["Bracers"], "Swiftstrike Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "31034", L["Gloves"], "Thunderheart Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30223", L["Gloves"], "Nordrassil Handgrips", "Alt")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32347", L["Gloves"], "Grips of Damnation", "Alt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "30879", L["Belt"], "Don Alejandro's Money Belt", "Alt")
LoonBestInSlot:AddItem(spec, "32265", L["Belt"], "Shadow-walker's Cord", "Alt")
LoonBestInSlot:AddItem(spec, "33879", L["Belt"], "Vindicator's Dragonhide Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31044", L["Legs"], "Thunderheart Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "28741", L["Legs"], "Skulker's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30898", L["Legs"], "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "29995", L["Legs"], "Leggings of Murderous Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30229", L["Legs"], "Nordrassil Feral-Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "33673", L["Legs"], "Vengeful Gladiator's Dragonhide Legguards", "Alt")

LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "33880", L["Feet"], "Vindicator's Dragonhide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "24114", L["Neck"], "Braided Eternium Chain", "BIS")

LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "32335", L["Ring"], "Unstoppable Aggressor's Ring", "Alt")
LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "Alt")

LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "38287", L["Trinket"], "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32658", L["Trinket"], "Badge of Tenacity", "Alt")

LoonBestInSlot:AddItem(spec, "33716", L["2H"], "Vengeful Gladiator's Staff", "BIS")
LoonBestInSlot:AddItem(spec, "32014", L["2H"], "Merciless Gladiator's Maul", "Alt")
LoonBestInSlot:AddItem(spec, "30883", L["2H"], "Pillar of Ferocity", "Alt")

LoonBestInSlot:AddItem(spec, "29390", L["Idol"], "Everbloom Idol", "BIS")
LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "32257", L["Idol"], "Idol of the White Stag", "Alt")
LoonBestInSlot:AddItem(spec, "28372", L["Idol"], "Idol of Feral Shadows", "Alt")
