local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto", "3")
LoonBestInSlot:AddItem(spec, "31037", "Head", "Thunderheart Helmet", "BIS")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32329", "Head", "Cowl of Benevolence", "BIS")
LoonBestInSlot:AddItem(spec, "30219", "Head", "Nordrassil Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32479", "Head", "Wonderheal XT40 Shades", "Alt")
LoonBestInSlot:AddItem(spec, "32240", "Head", "Guise of the Tidal Lurker", "Alt")

LoonBestInSlot:AddItem(spec, "31047", "Shoulders", "Thunderheart Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30221", "Shoulders", "Nordrassil Life-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32583", "Shoulders", "Shoulderpads of Renewed Life", "Alt")
LoonBestInSlot:AddItem(spec, "32585", "Shoulders", "Swiftheal Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "32518", "Shoulders", "Veil of Turning Leaves", "Alt")
LoonBestInSlot:AddItem(spec, "32273", "Shoulders", "Amice of Brilliant Light", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness", "BIS")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand", "Alt")

LoonBestInSlot:AddItem(spec, "31041", "Chest", "Thunderheart Tunic", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30216", "Chest", "Nordrassil Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30868", "Bracers", "Rejuvenating Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30871", "Bracers", "Bracers of Martyrdom", "BIS")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "32582", "Bracers", "Bracers of Renewed Life", "BIS")
LoonBestInSlot:AddItem(spec, "30062", "Bracers", "Grove-Bands of Remulos", "Alt")
LoonBestInSlot:AddItem(spec, "32513", "Bracers", "Wristbands of Divine Influence", "Alt")

LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "BIS")
LoonBestInSlot:AddItem(spec, "32353", "Gloves", "Gloves of Unfailing Faith", "Alt")
LoonBestInSlot:AddItem(spec, "31032", "Gloves", "Thunderheart Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender", "Alt")

LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash", "BIS")
LoonBestInSlot:AddItem(spec, "32339", "Belt", "Belt of Primal Majesty", "BIS")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "Alt")
LoonBestInSlot:AddItem(spec, "32519", "Belt", "Belt of Divine Guidance", "Alt")
LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "29984", "Belt", "Girdle of Zaetar", "Alt")

LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "32271", "Legs", "Kilt of Immortal Nature", "Alt")
LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "Alt")
LoonBestInSlot:AddItem(spec, "31045", "Legs", "Thunderheart Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "BIS")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light", "BIS")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30885", "Feet", "Archbishop's Slippers", "Alt")
LoonBestInSlot:AddItem(spec, "30886", "Feet", "Enchanted Leather Sandals", "Alt")

LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity", "Alt")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "33922", "Neck", "Vindicator's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "BIS")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "32486", "Trinket", "Ashtongue Talisman of Equilibrium", "Alt")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "33743", "MH", "Vengeful Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "Alt")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement", "Alt")

LoonBestInSlot:AddItem(spec, "30908", "2H", "Apostle of Argus", "BIS")
LoonBestInSlot:AddItem(spec, "32344", "2H", "Staff of Immaculate Recovery", "Alt")
LoonBestInSlot:AddItem(spec, "29981", "2H", "Ethereum Life-Staff", "Alt")

LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "32350", "OH", "Touch of Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "Alt")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen", "BIS")
