local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance", "3")
LoonBestInSlot:AddItem(spec, "31040", L["Head"], "Thunderheart Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "31096", L["Head"], "Helm of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32525", L["Head"], "Cowl of the Illidari High Lord", "Alt")
LoonBestInSlot:AddItem(spec, "30233", L["Head"], "Nordrassil Headpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "31049", L["Shoulders"], "Thunderheart Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30884", L["Shoulders"], "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30235", L["Shoulders"], "Nordrassil Wrath-Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32338", L["Shoulders"], "Blood-cursed Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "32587", L["Shoulders"], "Mantle of Nimble Thought", "Alt")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "32331", L["Back"], "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28766", L["Back"], "Ruby Drape of the Mysticant", "Alt")
LoonBestInSlot:AddItem(spec, "30735", L["Back"], "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "28797", L["Back"], "Brute Cloak of the Ogre-Magi", "Alt")
LoonBestInSlot:AddItem(spec, "29992", L["Back"], "Royal Cloak of the Sunstriders", "Alt")

LoonBestInSlot:AddItem(spec, "31043", L["Chest"], "Thunderheart Vest", "BIS")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30231", L["Chest"], "Nordrassil Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30913", L["Chest"], "Robes of Rhonin", "Alt")

LoonBestInSlot:AddItem(spec, "32586", L["Bracers"], "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "32270", L["Bracers"], "Focused Mana Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "32351", L["Bracers"], "Elunite Empowered Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30870", L["Bracers"], "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "29918", L["Bracers"], "Mindstorm Wristbands", "Alt")

LoonBestInSlot:AddItem(spec, "31035", L["Gloves"], "Thunderheart Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30232", L["Gloves"], "Nordrassil Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "Alt")

LoonBestInSlot:AddItem(spec, "30888", L["Belt"], "Anetheron's Noose", "BIS")
LoonBestInSlot:AddItem(spec, "30914", L["Belt"], "Belt of the Crescent Moon", "Alt")
LoonBestInSlot:AddItem(spec, "30038", L["Belt"], "Belt of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "32256", L["Belt"], "Waistwrap of Infinity", "Alt")

LoonBestInSlot:AddItem(spec, "30916", L["Legs"], "Leggings of Channeled Elements", "BIS")
LoonBestInSlot:AddItem(spec, "31046", L["Legs"], "Thunderheart Pants", "Alt")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "32367", L["Legs"], "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "Alt")
LoonBestInSlot:AddItem(spec, "30734", L["Legs"], "Leggings of the Seventh Circle", "Alt")

LoonBestInSlot:AddItem(spec, "32239", L["Feet"], "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "32352", L["Feet"], "Naturewarden's Treads", "Alt")
LoonBestInSlot:AddItem(spec, "30894", L["Feet"], "Blue Suede Shoes", "Alt")
LoonBestInSlot:AddItem(spec, "30037", L["Feet"], "Boots of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "30067", L["Feet"], "Velvet Boots of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "30015", L["Neck"], "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "35319", L["Neck"], "Vindicator's Pendant of Subjugation", "BIS")
LoonBestInSlot:AddItem(spec, "32349", L["Neck"], "Translucent Spellthread Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "33920", L["Neck"], "Vindicator's Pendant of Conquest", "Alt")
LoonBestInSlot:AddItem(spec, "24121", L["Neck"], "Chain of the Twilight Owl", "Alt")

LoonBestInSlot:AddItem(spec, "32527", L["Ring"], "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "32247", L["Ring"], "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30109", L["Ring"], "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "28753", L["Ring"], "Ring of Recurrence", "Alt")
LoonBestInSlot:AddItem(spec, "29287", L["Ring"], "Violet Signet of the Archmage", "Alt")
LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "32483", L["Trinket"], "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "32486", L["Trinket"], "Ashtongue Talisman of Equilibrium", "BIS")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "Alt")
LoonBestInSlot:AddItem(spec, "38290", L["Trinket"], "Dark Iron Smoking Pipe", "Alt")
LoonBestInSlot:AddItem(spec, "27683", L["Trinket"], "Quagmirran's Eye", "Alt")

LoonBestInSlot:AddItem(spec, "33687", L["MH"], "Vengeful Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "33763", L["MH"], "Vengeful Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "32237", L["MH"], "The Maelstrom's Fury", "BIS")
LoonBestInSlot:AddItem(spec, "34009", L["MH"], "Hammer of Judgement", "BIS")
LoonBestInSlot:AddItem(spec, "30723", L["MH"], "Talon of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "28770", L["MH"], "Nathrezim Mindblade", "Alt")

LoonBestInSlot:AddItem(spec, "32374", L["2H"], "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "34540", L["2H"], "Vengeful Gladiator's Battle Staff", "Alt")
LoonBestInSlot:AddItem(spec, "29988", L["2H"], "The Nexus Key", "Alt")
LoonBestInSlot:AddItem(spec, "33766", L["2H"], "Vengeful Gladiator's War Staff", "Alt")

LoonBestInSlot:AddItem(spec, "30872", L["OH"], "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "32361", L["OH"], "Blind-Seers Icon", "Alt")
LoonBestInSlot:AddItem(spec, "30049", L["OH"], "Fathomstone", "Alt")

LoonBestInSlot:AddItem(spec, "32387", L["Idol"], "Idol of the Raven Goddess", "BIS")
LoonBestInSlot:AddItem(spec, "27518", L["Idol"], "Ivory Idol of the Moongoddess", "BIS")
