local spec = LoonBestInSlot:RegisterSpec("Hunter", "BeastMaster", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "33666", "Head", "Vengeful Gladiator's Chain Helm", "BIS")
LoonBestInSlot:AddItem(spec, "31003", "Head", "Gronnstalker's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30141", "Head", "Rift Stalker Helm", "Alt")

LoonBestInSlot:AddItem(spec, "31006", "Shoulders", "Gronnstalker's Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "30143", "Shoulders", "Rift Stalker Mantle", "BIS Until T6")
LoonBestInSlot:AddItem(spec, "30892", "Shoulders", "Beast-tamer's Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32264", "Shoulders", "Shoulders of the Hidden Predator", "Alt")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32575", "Shoulders", "Shoulders of Lightning Reflexes", "Alt")
LoonBestInSlot:AddItem(spec, "27801", "Shoulders", "Beast Lord Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS without Madness/Stormrage")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt Temporary Hit Alt")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "Alt")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter", "Alt")

LoonBestInSlot:AddItem(spec, "31004", "Chest", "Gronnstalker's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30139", "Chest", "Rift Stalker Hauberk", "BIS Until Tier 6")
LoonBestInSlot:AddItem(spec, "28228", "Chest", "Beast Lord Cuirass", "BIS Until Tier 5")
LoonBestInSlot:AddItem(spec, "30054", "Chest", "Ranger-General's Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest", "Alt")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor", "Alt")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "Alt")
LoonBestInSlot:AddItem(spec, "32251", "Bracers", "Wraps of Precise Flight", "Alt")
LoonBestInSlot:AddItem(spec, "30026", "Bracers", "Bands of the Celestial Archer", "Alt")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "Alt")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands", "Alt")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards", "Alt")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "25697", "Bracers", "Felstalker Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "31001", "Gloves", "Gronnstalker's Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "30140", "Gloves", "Rift Stalker Gauntlets", "BIS Until Tier 6")
LoonBestInSlot:AddItem(spec, "27474", "Gloves", "Beast Lord Handguards", "BIS Until Tier 5")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt")
LoonBestInSlot:AddItem(spec, "28827", "Gloves", "Gauntlets of the Dragonslayer", "Alt")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "BIS")
LoonBestInSlot:AddItem(spec, "32346", "Belt", "Boneweave Girdle", "BIS Hit Alt")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "Alt")
LoonBestInSlot:AddItem(spec, "30046", "Belt", "Belt of the Black Eagle", "Alt")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "Alt")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt", "Alt")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash", "Alt")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt", "Alt")
LoonBestInSlot:AddItem(spec, "28656", "Belt", "Girdle of the Prowler", "Alt")

LoonBestInSlot:AddItem(spec, "31005", "Legs", "Gronnstalker's Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30142", "Legs", "Rift Stalker Leggings", "BIS with early CVoS")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Realistic Alt without CVoS")
LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt")
LoonBestInSlot:AddItem(spec, "29985", "Legs", "Void Reaver Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30739", "Legs", "Scaled Greaves of the Marksman", "Alt")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "27874", "Legs", "Beast Lord Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "BIS for early 4p Tier 6")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "Temporary Hit Alt")
LoonBestInSlot:AddItem(spec, "30880", "Feet", "Quickstrider Moccasins", "Temporary Hit Alt")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking", "Alt")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots", "Alt")
LoonBestInSlot:AddItem(spec, "28669", "Feet", "Rapscallion Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders", "Alt")

LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "Alt Hit Alt")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "30059", "Neck", "Choker of Animalistic Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "19377", "Neck", "Prestor's Talisman of Connivery", "Alt")
LoonBestInSlot:AddItem(spec, "28343", "Neck", "Jagged Bark Pendant", "Alt")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing", "Alt")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS 6% and 9%")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS 6% and 9%")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS Realistic 6% Alt")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt Hit Alt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt Hit Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt Hit Alt")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring", "Alt Hit Alt")
LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant", "Alt")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "Alt")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet", "Alt")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "23038", "Ring", "Band of Unnatural Forces", "Alt")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band", "Alt")
LoonBestInSlot:AddItem(spec, "30973", "Ring", "Band of Anguish", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "Alt option until Madness")
LoonBestInSlot:AddItem(spec, "32487", "Trinket", "Ashtongue Talisman of Swiftness", "Alt option until Madness")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "21670", "Trinket", "Badge of the Swarmguard", "Alt")
LoonBestInSlot:AddItem(spec, "28041", "Trinket", "Bladefist's Breadth", "Alt")

LoonBestInSlot:AddItem(spec, "30901", "MH", "Boundless Agony", "BIS")
LoonBestInSlot:AddItem(spec, "33737", "MH", "Vengeful Gladiator's Right Ripper", "Alt and hit option")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "Alt hit option")
LoonBestInSlot:AddItem(spec, "27846", "MH", "Claw of the Watcher", "Alt option with regem/enchant")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane", "Alt")
LoonBestInSlot:AddItem(spec, "29121", "MH", "Guile of Khoraazi", "Alt")
LoonBestInSlot:AddItem(spec, "28524", "MH", "Emerald Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "28584", "MH", "Big Bad Wolf's Paw", "Alt")
LoonBestInSlot:AddItem(spec, "28263", "MH", "Stellaris", "Alt")
LoonBestInSlot:AddItem(spec, "21673", "MH", "Silithid Claw", "Alt")
LoonBestInSlot:AddItem(spec, "30277", "MH", "Ripfang Paw", "Alt")

LoonBestInSlot:AddItem(spec, "30881", "OH", "Blade of Infamy", "BIS 7700 Bosses")
LoonBestInSlot:AddItem(spec, "33705", "OH", "Vengeful Gladiator's Left Ripper", "BIS 6200 Bosses")
LoonBestInSlot:AddItem(spec, "30865", "OH", "Tracker's Blade", "Alt early hit option")
LoonBestInSlot:AddItem(spec, "32269", "OH", "Messenger of Fate", "Alt")
LoonBestInSlot:AddItem(spec, "29948", "OH", "Claw of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "29924", "OH", "Netherbane", "Alt")
LoonBestInSlot:AddItem(spec, "28572", "OH", "Blade of the Unrequited", "Alt")
LoonBestInSlot:AddItem(spec, "28315", "OH", "Stormreaver Warblades", "Alt")
LoonBestInSlot:AddItem(spec, "29372", "OH", "Void-Talon", "Alt")
LoonBestInSlot:AddItem(spec, "29121", "OH", "Guile of Khoraazi", "Alt")
LoonBestInSlot:AddItem(spec, "23242", "OH", "Claw of the Frost Wyrm", "Alt")

LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "BIS for weaving")
LoonBestInSlot:AddItem(spec, "32248", "2H", "Halberd of Desolation", "BIS for hit rating")
LoonBestInSlot:AddItem(spec, "28436", "2H", "Bloodmoon", "Alt blacksMithing")
LoonBestInSlot:AddItem(spec, "28435", "2H", "Mooncleaver", "Alt blacksMithing")
LoonBestInSlot:AddItem(spec, "28587", "2H", "Legacy", "Alt")
LoonBestInSlot:AddItem(spec, "27903", "2H", "Sonic Spear", "Alt")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade", "Alt")
LoonBestInSlot:AddItem(spec, "23039", "2H", "The Eye of Nerub", "Alt")
LoonBestInSlot:AddItem(spec, "29329", "2H", "Terokk's Quill", "Alt")

LoonBestInSlot:AddItem(spec, "30906", "Ranged", "Bristleblitz Striker", "BIS")
LoonBestInSlot:AddItem(spec, "34530", "Ranged", "Vengeful Gladiator's Rifle", "BIS Dwarf")
LoonBestInSlot:AddItem(spec, "32336", "Ranged", "Black Bow of the Betrayer", "Close Second BIS")
LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "31986", "Ranged", "Merciless Gladiator's Crossbow of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "Alt")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "Alt")
LoonBestInSlot:AddItem(spec, "28581", "Ranged", "Wolfslayer Sniper Rifle", "Alt")
LoonBestInSlot:AddItem(spec, "29351", "Ranged", "Wrathtide Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "31323", "Ranged", "Don Santos' Famous Hunting Rifle", "Alt")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket", "Alt")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow", "Alt")
LoonBestInSlot:AddItem(spec, "28504", "Ranged", "Steelhawk Crossbow", "Alt")
LoonBestInSlot:AddItem(spec, "22812", "Ranged", "Nerubian Slavemaker", "Alt")
LoonBestInSlot:AddItem(spec, "31303", "Ranged", "Valanos' Longbow", "Alt")
