local spec = LoonBestInSlot:RegisterSpec("Hunter", "BeastMaster", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "33666", "Head", "Vengeful Gladiator's Chain Helm", "BIS")
LoonBestInSlot:AddItem(spec, "31003", "Head", "Gronnstalker's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30141", "Head", "Rift Stalker Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "31006", "Shoulders", "Gronnstalker's Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30143", "Shoulders", "Rift Stalker Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30892", "Shoulders", "Beast-tamer's Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32264", "Shoulders", "Shoulders of the Hidden Predator", "Alt")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32575", "Shoulders", "Shoulders of Lightning Reflexes", "Alt")

LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS")

LoonBestInSlot:AddItem(spec, "31004", "Chest", "Gronnstalker's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30139", "Chest", "Rift Stalker Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "Alt")
LoonBestInSlot:AddItem(spec, "32251", "Bracers", "Wraps of Precise Flight", "Alt")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "Alt")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "31001", "Gloves", "Gronnstalker's Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30140", "Gloves", "Rift Stalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "BIS")
LoonBestInSlot:AddItem(spec, "32346", "Belt", "Boneweave Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "Alt")

LoonBestInSlot:AddItem(spec, "31005", "Legs", "Gronnstalker's Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30142", "Legs", "Rift Stalker Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "Alt")
LoonBestInSlot:AddItem(spec, "30880", "Feet", "Quickstrider Moccasins", "Alt")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "Alt")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "Alt")
LoonBestInSlot:AddItem(spec, "32487", "Trinket", "Ashtongue Talisman of Swiftness", "Alt")

LoonBestInSlot:AddItem(spec, "30901", "MH", "Boundless Agony", "BIS")
LoonBestInSlot:AddItem(spec, "33737", "MH", "Vengeful Gladiator's Right Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "32946", "MH", "Claw of Molten Fury", "Alt")

LoonBestInSlot:AddItem(spec, "30881", "OH", "Blade of Infamy", "BIS")
LoonBestInSlot:AddItem(spec, "33705", "OH", "Vengeful Gladiator's Left Ripper", "BIS")
LoonBestInSlot:AddItem(spec, "30865", "OH", "Tracker's Blade", "Alt")
LoonBestInSlot:AddItem(spec, "32269", "OH", "Messenger of Fate", "Alt")
LoonBestInSlot:AddItem(spec, "29948", "OH", "Claw of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "32945", "OH", "Fist of Molten Fury", "Alt")

LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "32248", "2H", "Halberd of Desolation", "BIS")
LoonBestInSlot:AddItem(spec, "28436", "2H", "Bloodmoon", "Alt")

LoonBestInSlot:AddItem(spec, "30906", "Ranged", "Bristleblitz Striker", "BIS")
LoonBestInSlot:AddItem(spec, "34530", "Ranged", "Vengeful Gladiator's Rifle", "BIS")
LoonBestInSlot:AddItem(spec, "32336", "Ranged", "Black Bow of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "31986", "Ranged", "Merciless Gladiator's Crossbow of the Phoenix", "Alt")
