local spec = LoonBestInSlot:RegisterSpec("Hunter", "Marks", "3")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "33666", L["Head"], "Vengeful Gladiator's Chain Helm", "BIS")
LoonBestInSlot:AddItem(spec, "31003", L["Head"], "Gronnstalker's Helmet", "Alt")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "32376", L["Head"], "Forest Prowler's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30141", L["Head"], "Rift Stalker Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30244", L["Head"], "Helm of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "31006", L["Shoulders"], "Gronnstalker's Spaulders", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30143", L["Shoulders"], "Rift Stalker Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30250", L["Shoulders"], "Pauldrons of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30892", L["Shoulders"], "Beast-tamer's Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32264", L["Shoulders"], "Shoulders of the Hidden Predator", "Alt")
LoonBestInSlot:AddItem(spec, "32581", L["Shoulders"], "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32575", L["Shoulders"], "Shoulders of Lightning Reflexes", "Alt")

LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "BIS")
LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "BIS")

LoonBestInSlot:AddItem(spec, "31004", L["Chest"], "Gronnstalker's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30139", L["Chest"], "Rift Stalker Hauberk", "Alt")
LoonBestInSlot:AddItem(spec, "30238", L["Chest"], "Chestguard of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "29966", L["Bracers"], "Vambraces of Ending", "Alt")
LoonBestInSlot:AddItem(spec, "32574", L["Bracers"], "Bindings of Lightning Reflexes", "Alt")
LoonBestInSlot:AddItem(spec, "32580", L["Bracers"], "Swiftstrike Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "31001", L["Gloves"], "Gronnstalker's Gloves", "BIS")
LoonBestInSlot:AddItem(spec, "31094", L["Gloves"], "Gloves of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30140", L["Gloves"], "Rift Stalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30241", L["Gloves"], "Gloves of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "30879", L["Belt"], "Don Alejandro's Money Belt", "BIS")
LoonBestInSlot:AddItem(spec, "32346", L["Belt"], "Boneweave Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "30040", L["Belt"], "Belt of Deep Shadow", "Alt")

LoonBestInSlot:AddItem(spec, "31005", L["Legs"], "Gronnstalker's Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31100", L["Legs"], "Leggings of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30142", L["Legs"], "Rift Stalker Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30247", L["Legs"], "Leggings of the Vanquished Hero", "BIS")
LoonBestInSlot:AddItem(spec, "30898", L["Legs"], "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30900", L["Legs"], "Bow-stitched Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29995", L["Legs"], "Leggings of Murderous Intent", "Alt")

LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "BIS")
LoonBestInSlot:AddItem(spec, "32510", L["Feet"], "Softstep Boots of Tracking", "Alt")
LoonBestInSlot:AddItem(spec, "30880", L["Feet"], "Quickstrider Moccasins", "Alt")
LoonBestInSlot:AddItem(spec, "30104", L["Feet"], "Cobra-Lash Boots", "Alt")
LoonBestInSlot:AddItem(spec, "29951", L["Feet"], "Star-Strider Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "Alt")

LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "28791", L["Ring"], "Ring of the Recalcitrant", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "Alt")
LoonBestInSlot:AddItem(spec, "32487", L["Trinket"], "Ashtongue Talisman of Swiftness", "Alt")

LoonBestInSlot:AddItem(spec, "30901", L["MH"], "Boundless Agony", "BIS")
LoonBestInSlot:AddItem(spec, "33737", L["MH"], "Vengeful Gladiator's Right Ripper", "Alt")
LoonBestInSlot:AddItem(spec, "32944", L["MH"], "Talon of the Phoenix", "Alt")

LoonBestInSlot:AddItem(spec, "30881", L["OH"], "Blade of Infamy", "BIS")
LoonBestInSlot:AddItem(spec, "33705", L["OH"], "Vengeful Gladiator's Left Ripper", "BIS")
LoonBestInSlot:AddItem(spec, "30865", L["OH"], "Tracker's Blade", "Alt")
LoonBestInSlot:AddItem(spec, "29948", L["OH"], "Claw of the Phoenix", "Alt")

LoonBestInSlot:AddItem(spec, "29993", L["2H"], "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "32248", L["2H"], "Halberd of Desolation", "BIS")
LoonBestInSlot:AddItem(spec, "28436", L["2H"], "Bloodmoon", "Alt")

LoonBestInSlot:AddItem(spec, "30906", L["Ranged"], "Bristleblitz Striker", "BIS")
LoonBestInSlot:AddItem(spec, "34530", L["Ranged"], "Vengeful Gladiator's Rifle", "BIS")
LoonBestInSlot:AddItem(spec, "32336", L["Ranged"], "Black Bow of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "30105", L["Ranged"], "Serpent Spine Longbow", "Alt")
LoonBestInSlot:AddItem(spec, "31986", L["Ranged"], "Merciless Gladiator's Crossbow of the Phoenix", "Alt")
