local spec = LoonBestInSlot:RegisterSpec("Mage", "Fire", "3")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "BIS")
LoonBestInSlot:AddItem(spec, "31056", "Head", "Cowl of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "Alt")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer", "Alt")
LoonBestInSlot:AddItem(spec, "30206", "Head", "Cowl of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "31059", "Shoulders", "Mantle of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought", "Alt")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30210", "Shoulders", "Mantle of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings", "Alt")

LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "Alt")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "31057", "Chest", "Robes of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin", "Alt")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30196", "Chest", "Robes of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes", "Alt")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands", "Alt")

LoonBestInSlot:AddItem(spec, "31055", "Gloves", "Gloves of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30205", "Gloves", "Gloves of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King", "Alt")

LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "Alt")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "Alt")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31058", "Legs", "Leggings of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "Alt")
LoonBestInSlot:AddItem(spec, "30207", "Legs", "Leggings of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes", "Alt")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting", "Alt")

LoonBestInSlot:AddItem(spec, "32589", "Neck", "Hellfire-Encased Pendant", "BIS")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "Alt")

LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms", "BIS")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "BIS")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "30720", "Trinket", "Serpent-Coil Braid", "Alt")

LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan", "Alt")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "Alt")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key", "Alt")
LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "Alt")

LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "29270", "OH", "Flametongue Seal", "Alt")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone", "Alt")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "32343", "Wand", "Wand of Prismatic Focus", "Alt")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration", "Alt")
LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy", "Alt")
