local spec = LoonBestInSlot:RegisterSpec("Mage", "Fire", "3")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "BIS")
LoonBestInSlot:AddItem(spec, "31056", "Head", "Cowl of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood", "Alt")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer", "Alt")
LoonBestInSlot:AddItem(spec, "30206", "Head", "Cowl of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "Alt")
LoonBestInSlot:AddItem(spec, "30515", "Head", "Junior Technician 3rd Grade Goggles", "Alt")

LoonBestInSlot:AddItem(spec, "31059", "Shoulders", "Mantle of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought", "Alt")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30210", "Shoulders", "Mantle of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings", "Alt")
LoonBestInSlot:AddItem(spec, "28075", "Shoulders", "Destroyers' Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30514", "Shoulders", "Nether Guards", "Alt")

LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant", "Alt")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "29813", "Back", "Cloak of Woven Energy", "Alt")
LoonBestInSlot:AddItem(spec, "25777", "Back", "Ogre Slayer's Cover", "Alt")

LoonBestInSlot:AddItem(spec, "31057", "Chest", "Robes of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin", "Alt")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe", "Alt")
LoonBestInSlot:AddItem(spec, "30196", "Chest", "Robes of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes", "Alt")
LoonBestInSlot:AddItem(spec, "29780", "Chest", "Kirin Tor Apprentice's Robes", "Alt")
LoonBestInSlot:AddItem(spec, "31717", "Chest", "Shadowcast Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands", "Alt")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom", "Alt")
LoonBestInSlot:AddItem(spec, "30927", "Bracers", "Earthmender's Bracer of Shattering", "Alt")
LoonBestInSlot:AddItem(spec, "30520", "Bracers", "Gold-Trimmed Cuffs", "Alt")

LoonBestInSlot:AddItem(spec, "31055", "Gloves", "Gloves of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "30205", "Gloves", "Gloves of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "30924", "Gloves", "Gloves of the High Magus", "Alt")
LoonBestInSlot:AddItem(spec, "30930", "Gloves", "Grips of the Void", "Alt")

LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "Alt")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "Alt")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt", "Alt")
LoonBestInSlot:AddItem(spec, "30923", "Belt", "Grom'tor's Bloodied Bandage", "Alt")
LoonBestInSlot:AddItem(spec, "29771", "Belt", "Kirin'Var Journeyman's Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31058", "Legs", "Leggings of the Tempest", "BIS")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "Alt")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "Alt")
LoonBestInSlot:AddItem(spec, "30207", "Legs", "Leggings of Tirisfal", "Alt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Hero", "Alt")
LoonBestInSlot:AddItem(spec, "30929", "Legs", "Soothsayer's Kilt", "Alt")
LoonBestInSlot:AddItem(spec, "21852", "Legs", "Netherweave Pants", "Alt")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes", "Alt")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "30519", "Feet", "Boots of the Nexus Warden", "Alt")
LoonBestInSlot:AddItem(spec, "30398", "Feet", "Boots of the Beneficent", "Alt")

LoonBestInSlot:AddItem(spec, "32589", "Neck", "Hellfire-Encased Pendant", "BIS")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls", "Alt")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "31178", "Neck", "Amulet of Unstable Power", "Alt")

LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms", "BIS")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence", "Alt")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift", "Alt")
LoonBestInSlot:AddItem(spec, "31075", "Ring", "Evoker's Mark of the Redemption", "Alt")
LoonBestInSlot:AddItem(spec, "30366", "Ring", "Manastorm Band", "Alt")
LoonBestInSlot:AddItem(spec, "32774", "Ring", "The Black Pearl", "Alt")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "BIS")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem", "Alt")
LoonBestInSlot:AddItem(spec, "30720", "Trinket", "Serpent-Coil Braid", "Alt")
LoonBestInSlot:AddItem(spec, "28040", "Trinket", "Vengeance of the Illidari", "Alt")
LoonBestInSlot:AddItem(spec, "25620", "Trinket", "Ancient Crystal Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "25619", "Trinket", "Glowing Crystal Insignia", "Alt")

LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan", "Alt")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "Alt")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade", "Alt")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "Alt")
LoonBestInSlot:AddItem(spec, "30787", "MH", "Illidari-Bane Mageblade", "Alt")
LoonBestInSlot:AddItem(spec, "24453", "MH", "Zangartooth Shortblade", "Alt")
LoonBestInSlot:AddItem(spec, "31142", "MH", "Blade of Trapped Knowledge", "Alt")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key", "Alt")
LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries", "Alt")
LoonBestInSlot:AddItem(spec, "22589", "2H", "Atiesh, Greatstaff of the Guardian", "Alt")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff", "Alt")
LoonBestInSlot:AddItem(spec, "31308", "2H", "The Bringer of Death", "Alt")
LoonBestInSlot:AddItem(spec, "25760", "2H", "Battle Mage's Baton", "Alt")

LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "29270", "OH", "Flametongue Seal", "Alt")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone", "Alt")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "Alt")
LoonBestInSlot:AddItem(spec, "23049", "OH", "Sapphiron's Left Eye", "Alt")
LoonBestInSlot:AddItem(spec, "31699", "OH", "Imbued Draenethyst Crystal", "Alt")
LoonBestInSlot:AddItem(spec, "31731", "OH", "Mekeda's Gift", "Alt")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "32343", "Wand", "Wand of Prismatic Focus", "Alt")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration", "Alt")
LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy", "Alt")
LoonBestInSlot:AddItem(spec, "31724", "Wand", "Arakkoa Divining Rod", "Alt")
LoonBestInSlot:AddItem(spec, "30523", "Wand", "Hotshot Cattle Prod", "Alt")
