local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "3")
LoonBestInSlot:AddItem(spec, "32521", "Head", "Faceplate of the Impenetrable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30987", "Head", "Lightbringer Faceguard", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30125", "Head", "Crystalforge Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30998", "Shoulders", "Lightbringer Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "29070", "Shoulders", "Justicar Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32250", "Shoulders", "Pauldrons of Abyssal Fury", "Alt")

LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification", "BIS")
LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30991", "Chest", "Lightbringer Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30896", "Chest", "Glory of the Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33695", "Chest", "Vengeful Gladiator's Lamellar Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "29066", "Chest", "Justicar Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32279", "Bracers", "The Seeker's Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "32232", "Bracers", "Eternium Shell Bracers", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33889", "Bracers", "Vindicator's Lamellar Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32515", "Bracers", "Wristguards of Determination", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30985", "Gloves", "Lightbringer Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "29998", "Gloves", "Royal Gauntlets of Silvermoon", "Alt")
LoonBestInSlot:AddItem(spec, "30124", "Gloves", "Crystalforge Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32342", "Belt", "Girdle of Mighty Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "32333", "Belt", "Girdle of Stability", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30096", "Belt", "Girdle of the Invulnerable", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30995", "Legs", "Lightbringer Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32263", "Legs", "Praetorian's Legguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33698", "Legs", "Vengeful Gladiator's Lamellar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32245", "Feet", "Tide-stomper's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans", "BIS")
LoonBestInSlot:AddItem(spec, "30007", "Neck", "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33921", "Neck", "Vindicator's Pendant of Dominance", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "30083", "Ring", "Ring of Sundered Souls", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32261", "Ring", "Band of the Abyssal Lord", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29297", "Ring", "Band of the Eternal Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31859", "Trinket", "Darkmoon Card: Madness", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch", "Alt")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "Alt")
LoonBestInSlot:AddItem(spec, "34579", "Trinket", "Battlemaster's Audacity", "Alt")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "32489", "Trinket", "Ashtongue Talisman of Zeal", "Alt")

LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "32963", "MH", "Merciless Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan", "Alt")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32368", "Libram", "Tome of the Lightbringer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27917", "Libram", "Libram of the Eternal Rest", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "32375", "Shield", "Bulwark of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "30909", "Shield", "Antonidas's Aegis of Rapt Concentration", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30889", "Shield", "Kaz'rogal's Hardened Heart", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34011", "Shield", "Illidari Runeshield", "Alt Thrt")
