local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm", "Alt - low competition")
LoonBestInSlot:AddItem(spec, "32373", "Head", "Helm of the Illidari Shatterer", "Alt - low competition")
LoonBestInSlot:AddItem(spec, "30989", "Head", "Lightbringer War-Helm", "Tier")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "P2 BIS")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "BIS - no expertise option")
LoonBestInSlot:AddItem(spec, "30997", "Shoulders", "Lightbringer Shoulderbraces", "T6")
LoonBestInSlot:AddItem(spec, "30133", "Shoulders", "Crystalforge Shoulderbraces", "Alt")
LoonBestInSlot:AddItem(spec, "29075", "Shoulders", "Justicar Shoulderplates", "Alt")

LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "BIS - crafted")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt-Crafted")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "BIS for Hit")
LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings", "Alt Hit")

LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "BIS - non tier")
LoonBestInSlot:AddItem(spec, "30990", "Chest", "Lightbringer Breastplate", "Alt - tier")
LoonBestInSlot:AddItem(spec, "30129", "Chest", "Crystalforge Breastplate", "Old Tier")
LoonBestInSlot:AddItem(spec, "28485", "Chest", "Bulwark of the Ancient Kings", "Crafting - Alternate")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "33749", "Chest", "Vengeful Gladiator's Scaled Chestpiece", "Alt-PVP")
LoonBestInSlot:AddItem(spec, "29071", "Chest", "Justicar Breastplate", "Older Tier")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "WORLD BOSS")

LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "32568", "Bracers", "Swiftsteel Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication", "Alt Hit")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "Alt - Non Hit")
LoonBestInSlot:AddItem(spec, "33910", "Bracers", "Vindicator's Scaled Bracers", "Alt-PVP")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "Alt-Crafted")

LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation", "BIS")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "18823", "Gloves", "Aged Core Leather Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "Alt")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt-Hit")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "Alt")

LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30993", "Legs", "Lightbringer Greaves", "Alt - tier")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder", "Alt - Human")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion", "Alt Hit")
LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration", "Alt")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "Alt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt-Hit")

LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "BIS Hit")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt-HIT")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism", "Alt")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "Alt")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "BOE")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "Never Un-equip")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS Hit")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring", "Alt")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "BIS - NonHit")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "WorldBoss")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt-Hit")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS TRINKET")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS #2")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "22954", "Trinket", "Kiss of the Spider", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Old Trinkets")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Old Trinkets")

LoonBestInSlot:AddItem(spec, "32332", "2H", "Torch of the Damned", "BIS")
LoonBestInSlot:AddItem(spec, "30902", "2H", "Cataclysm's Edge", "Alt")
LoonBestInSlot:AddItem(spec, "33688", "2H", "Vengeful Gladiator's Greatsword", "PVP")
LoonBestInSlot:AddItem(spec, "28430", "2H", "Lionheart Executioner", "P2 Crafted")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "P2 - Non-Crafted")
LoonBestInSlot:AddItem(spec, "28442", "2H", "Stormherald", "Alt")
LoonBestInSlot:AddItem(spec, "30090", "2H", "World Breaker", "Alt")
LoonBestInSlot:AddItem(spec, "28773", "2H", "Gorehowl", "Alt")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement", "BIS")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Alt")
LoonBestInSlot:AddItem(spec, "23203", "Libram", "Libram of Fervor", "Alt")
LoonBestInSlot:AddItem(spec, "22402", "Libram", "Libram of Grace", "Cleansebot")
