local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "32373", "Head", "Helm of the Illidari Shatterer", "Alt")
LoonBestInSlot:AddItem(spec, "30989", "Head", "Lightbringer War-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles", "Alt")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "BIS")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "30997", "Shoulders", "Lightbringer Shoulderbraces", "Alt")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30133", "Shoulders", "Crystalforge Shoulderbraces", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "29075", "Shoulders", "Justicar Shoulderplates", "Alt")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "BIS")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud", "BIS")
LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings", "Alt")

LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "30990", "Chest", "Lightbringer Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30129", "Chest", "Crystalforge Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "28485", "Chest", "Bulwark of the Ancient Kings", "Alt")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "33749", "Chest", "Vengeful Gladiator's Scaled Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "29071", "Chest", "Justicar Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic", "Alt")

LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "32568", "Bracers", "Swiftsteel Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication", "Alt")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "Alt")
LoonBestInSlot:AddItem(spec, "33910", "Bracers", "Vindicator's Scaled Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers", "Alt")

LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "BIS")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation", "BIS")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness", "Alt")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "18823", "Gloves", "Aged Core Leather Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit", "Alt")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer", "Alt")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery", "Alt")

LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30993", "Legs", "Lightbringer Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder", "Alt")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion", "Alt")
LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration", "Alt")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency", "Alt")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "BIS")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace", "Alt")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism", "Alt")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain", "Alt")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring", "Alt")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest", "BIS")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity", "Alt")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks", "Alt")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds", "Alt")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "Alt")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "Alt")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt")
LoonBestInSlot:AddItem(spec, "22954", "Trinket", "Kiss of the Spider", "Alt")
LoonBestInSlot:AddItem(spec, "23041", "Trinket", "Slayer's Crest", "Alt")
LoonBestInSlot:AddItem(spec, "19406", "Trinket", "Drake Fang Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "32332", "2H", "Torch of the Damned", "BIS")
LoonBestInSlot:AddItem(spec, "30902", "2H", "Cataclysm's Edge", "Alt")
LoonBestInSlot:AddItem(spec, "33688", "2H", "Vengeful Gladiator's Greatsword", "Alt")
LoonBestInSlot:AddItem(spec, "28430", "2H", "Lionheart Executioner", "Alt")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix", "Alt")
LoonBestInSlot:AddItem(spec, "28442", "2H", "Stormherald", "Alt")
LoonBestInSlot:AddItem(spec, "30090", "2H", "World Breaker", "Alt")
LoonBestInSlot:AddItem(spec, "28773", "2H", "Gorehowl", "Alt")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement", "BIS")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope", "Alt")
LoonBestInSlot:AddItem(spec, "23203", "Libram", "Libram of Fervor", "Alt")
LoonBestInSlot:AddItem(spec, "22402", "Libram", "Libram of Grace", "Alt")
