local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy", "3")
LoonBestInSlot:AddItem(spec, "30988", "Head", "Lightbringer Greathelm", "BIS")
LoonBestInSlot:AddItem(spec, "32354", "Head", "Crown of Empowered Fate", "Alt")
LoonBestInSlot:AddItem(spec, "32241", "Head", "Helm of Soothing Currents", "Alt")
LoonBestInSlot:AddItem(spec, "30136", "Head", "Crystalforge Greathelm", "Alt")

LoonBestInSlot:AddItem(spec, "30996", "Shoulders", "Lightbringer Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "30878", "Shoulders", "Glimmering Steel Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30138", "Shoulders", "Crystalforge Pauldrons", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand", "BIS")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness", "Alt")

LoonBestInSlot:AddItem(spec, "30992", "Chest", "Lightbringer Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "30904", "Chest", "Savior's Grasp", "Alt")
LoonBestInSlot:AddItem(spec, "30134", "Chest", "Crystalforge Chestpiece", "Alt")

LoonBestInSlot:AddItem(spec, "30862", "Bracers", "Blessed Adamantite Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30869", "Bracers", "Howling Wind Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32571", "Bracers", "Dawnsteel Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30047", "Bracers", "Blackfathom Warbands", "Alt")

LoonBestInSlot:AddItem(spec, "30112", "Gloves", "Glorious Gauntlets of Crestfall", "BIS")
LoonBestInSlot:AddItem(spec, "30983", "Gloves", "Lightbringer Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "29976", "Gloves", "Worldstorm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "Alt")

LoonBestInSlot:AddItem(spec, "30897", "Belt", "Girdle of Hope", "BIS")
LoonBestInSlot:AddItem(spec, "30030", "Belt", "Girdle of Fallen Stars", "Alt")
LoonBestInSlot:AddItem(spec, "29965", "Belt", "Girdle of the Righteous Path", "Alt")

LoonBestInSlot:AddItem(spec, "30994", "Legs", "Lightbringer Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "32271", "Legs", "Kilt of Immortal Nature", "Alt")
LoonBestInSlot:AddItem(spec, "30893", "Legs", "Sun-touched Chain Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "32243", "Feet", "Pearl Inlaid Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30027", "Feet", "Boots of Courage Unending", "Alt")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light", "Alt")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "Alt")

LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "Alt")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "32238", "Ring", "Ring of Calming Waves", "BIS")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "Alt")
LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth", "Alt")

LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "Alt")
LoonBestInSlot:AddItem(spec, "19395", "Trinket", "Rejuvenating Gem", "Alt")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement", "BIS")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "Alt")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "Alt")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous", "Alt")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon", "Alt")

LoonBestInSlot:AddItem(spec, "32255", "OH", "Felstone Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "30882", "OH", "Bastion of Light", "BIS")
LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "29458", "OH", "Aegis of the Vindicator", "Alt")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")
LoonBestInSlot:AddItem(spec, "29267", "OH", "Light-Bearer's Faith Shield", "Alt")

LoonBestInSlot:AddItem(spec, "28592", "Libram", "Libram of Souls Redeemed", "BIS")
LoonBestInSlot:AddItem(spec, "23006", "Libram", "Libram of Light", "BIS")
LoonBestInSlot:AddItem(spec, "30063", "Libram", "Libram of Absolute Truth", "BIS")
LoonBestInSlot:AddItem(spec, "28296", "Libram", "Libram of the Lightbringer", "BIS")
LoonBestInSlot:AddItem(spec, "25644", "Libram", "Blessed Book of Nagrand", "Alt")
