local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy", "3")
LoonBestInSlot:AddItem(spec, "30988", L["Head"], "Lightbringer Greathelm", "BIS")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32354", L["Head"], "Crown of Empowered Fate", "Alt")
LoonBestInSlot:AddItem(spec, "32241", L["Head"], "Helm of Soothing Currents", "Alt")
LoonBestInSlot:AddItem(spec, "30136", L["Head"], "Crystalforge Greathelm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30996", L["Shoulders"], "Lightbringer Pauldrons", "BIS")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30878", L["Shoulders"], "Glimmering Steel Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "30138", L["Shoulders"], "Crystalforge Pauldrons", "Alt")
LoonBestInSlot:AddItem(spec, "30248", L["Shoulders"], "Pauldrons of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34012", L["Back"], "Shroud of the Final Stand", "BIS")
LoonBestInSlot:AddItem(spec, "29989", L["Back"], "Sunshower Light Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32337", L["Back"], "Shroud of Forgiveness", "Alt")

LoonBestInSlot:AddItem(spec, "30992", L["Chest"], "Lightbringer Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30904", L["Chest"], "Savior's Grasp", "Alt")
LoonBestInSlot:AddItem(spec, "30134", L["Chest"], "Crystalforge Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30862", L["Bracers"], "Blessed Adamantite Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30869", L["Bracers"], "Howling Wind Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32571", L["Bracers"], "Dawnsteel Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30047", L["Bracers"], "Blackfathom Warbands", "Alt")

LoonBestInSlot:AddItem(spec, "30112", L["Gloves"], "Glorious Gauntlets of Crestfall", "BIS")
LoonBestInSlot:AddItem(spec, "30983", L["Gloves"], "Lightbringer Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "Alt")

LoonBestInSlot:AddItem(spec, "30897", L["Belt"], "Girdle of Hope", "BIS")
LoonBestInSlot:AddItem(spec, "30030", L["Belt"], "Girdle of Fallen Stars", "Alt")

LoonBestInSlot:AddItem(spec, "30994", L["Legs"], "Lightbringer Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30912", L["Legs"], "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "32271", L["Legs"], "Kilt of Immortal Nature", "Alt")
LoonBestInSlot:AddItem(spec, "30893", L["Legs"], "Sun-touched Chain Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "32243", L["Feet"], "Pearl Inlaid Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30027", L["Feet"], "Boots of Courage Unending", "Alt")
LoonBestInSlot:AddItem(spec, "32609", L["Feet"], "Boots of the Divine Light", "Alt")

LoonBestInSlot:AddItem(spec, "32370", L["Neck"], "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "30018", L["Neck"], "Lord Sanguinar's Claim", "Alt")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "Alt")

LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "32238", L["Ring"], "Ring of Calming Waves", "BIS")
LoonBestInSlot:AddItem(spec, "29309", L["Ring"], "Band of the Eternal Restorer", "BIS")
LoonBestInSlot:AddItem(spec, "30110", L["Ring"], "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "30736", L["Ring"], "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "28790", L["Ring"], "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28590", L["Trinket"], "Ribbon of Sacrifice", "Alt")

LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "30918", L["MH"], "Hammer of Atonement", "BIS")
LoonBestInSlot:AddItem(spec, "30108", L["MH"], "Lightfathom Scepter", "Alt")

LoonBestInSlot:AddItem(spec, "32255", L["OH"], "Felstone Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "30882", L["OH"], "Bastion of Light", "BIS")
LoonBestInSlot:AddItem(spec, "30911", L["OH"], "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "29458", L["OH"], "Aegis of the Vindicator", "Alt")
LoonBestInSlot:AddItem(spec, "29923", L["OH"], "Talisman of the Sun King", "Alt")

LoonBestInSlot:AddItem(spec, "28592", L["Libram"], "Libram of Souls Redeemed", "BIS")
LoonBestInSlot:AddItem(spec, "23006", L["Libram"], "Libram of Light", "Alt")
LoonBestInSlot:AddItem(spec, "30063", L["Libram"], "Libram of Absolute Truth", "Alt")
LoonBestInSlot:AddItem(spec, "28296", L["Libram"], "Libram of the Lightbringer", "Alt")
