local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot", "3")
LoonBestInSlot:AddItem(spec, "32521", L["Head"], "Faceplate of the Impenetrable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30987", L["Head"], "Lightbringer Faceguard", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30125", L["Head"], "Crystalforge Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30998", L["Shoulders"], "Lightbringer Shoulderguards", "BIS")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "29070", L["Shoulders"], "Justicar Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "29763", L["Shoulders"], "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32250", L["Shoulders"], "Pauldrons of Abyssal Fury", "Alt")

LoonBestInSlot:AddItem(spec, "34010", L["Back"], "Pepe's Shroud of Pacification", "BIS")
LoonBestInSlot:AddItem(spec, "29925", L["Back"], "Phoenix-Wing Cloak", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29992", L["Back"], "Royal Cloak of the Sunstriders", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32331", L["Back"], "Cloak of the Illidari Council", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30991", L["Chest"], "Lightbringer Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30896", L["Chest"], "Glory of the Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "33695", L["Chest"], "Vengeful Gladiator's Lamellar Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "29066", L["Chest"], "Justicar Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "29754", L["Chest"], "Chestguard of the Fallen Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32279", L["Bracers"], "The Seeker's Wristguards", "BIS")
LoonBestInSlot:AddItem(spec, "32232", L["Bracers"], "Eternium Shell Bracers", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33889", L["Bracers"], "Vindicator's Lamellar Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "32515", L["Bracers"], "Wristguards of Determination", "Alt Mit")

LoonBestInSlot:AddItem(spec, "30985", L["Gloves"], "Lightbringer Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "29998", L["Gloves"], "Royal Gauntlets of Silvermoon", "Alt")
LoonBestInSlot:AddItem(spec, "30124", L["Gloves"], "Crystalforge Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "30239", L["Gloves"], "Gloves of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32342", L["Belt"], "Girdle of Mighty Resolve", "BIS")
LoonBestInSlot:AddItem(spec, "32333", L["Belt"], "Girdle of Stability", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30096", L["Belt"], "Girdle of the Invulnerable", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30064", L["Belt"], "Cord of Screaming Terrors", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "30995", L["Legs"], "Lightbringer Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32263", L["Legs"], "Praetorian's Legguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33698", L["Legs"], "Vengeful Gladiator's Lamellar Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "32367", L["Legs"], "Leggings of Devastation", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32245", L["Feet"], "Tide-stomper's Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "30894", L["Feet"], "Blue Suede Shoes", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "32362", L["Neck"], "Pendant of Titans", "BIS")
LoonBestInSlot:AddItem(spec, "30007", L["Neck"], "The Darkener's Grasp", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33921", L["Neck"], "Vindicator's Pendant of Dominance", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "30083", L["Ring"], "Ring of Sundered Souls", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32261", L["Ring"], "Band of the Abyssal Lord", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29297", L["Ring"], "Band of the Eternal Defender", "Alt Mit")
LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "31858", L["Trinket"], "Darkmoon Card: Vengeance", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31859", L["Trinket"], "Darkmoon Card: Madness", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32501", L["Trinket"], "Shadowmoon Insignia", "BIS")
LoonBestInSlot:AddItem(spec, "28528", L["Trinket"], "Moroes' Lucky Pocket Watch", "Alt")
LoonBestInSlot:AddItem(spec, "32534", L["Trinket"], "Brooch of the Immortal King", "Alt")
LoonBestInSlot:AddItem(spec, "34579", L["Trinket"], "Battlemaster's Audacity", "Alt")
LoonBestInSlot:AddItem(spec, "28789", L["Trinket"], "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "32489", L["Trinket"], "Ashtongue Talisman of Zeal", "Alt")

LoonBestInSlot:AddItem(spec, "30910", L["MH"], "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "33687", L["MH"], "Vengeful Gladiator's Gavel", "BIS")
LoonBestInSlot:AddItem(spec, "34009", L["MH"], "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "32963", L["MH"], "Merciless Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "30095", L["MH"], "Fang of the Leviathan", "Alt")

LoonBestInSlot:AddItem(spec, "29388", L["Libram"], "Libram of Repentance", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32368", L["Libram"], "Tome of the Lightbringer", "BIS Mit")
LoonBestInSlot:AddItem(spec, "27917", L["Libram"], "Libram of the Eternal Rest", "BIS Thrt")

LoonBestInSlot:AddItem(spec, "32375", L["Shield"], "Bulwark of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "30909", L["Shield"], "Antonidas's Aegis of Rapt Concentration", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30889", L["Shield"], "Kaz'rogal's Hardened Heart", "Alt Mit")
LoonBestInSlot:AddItem(spec, "34011", L["Shield"], "Illidari Runeshield", "Alt Thrt")
