local spec = LoonBestInSlot:RegisterSpec("Priest", "Shadow", "3")
LoonBestInSlot:AddItem(spec, "31064", "Head", "Hood of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "Alt")
LoonBestInSlot:AddItem(spec, "32494", "Head", "Destruction Holo-gogs", "Alt")
LoonBestInSlot:AddItem(spec, "30161", "Head", "Hood of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "31070", "Shoulders", "Shoulderpads of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought", "Alt")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "21869", "Shoulders", "Frozen Shadoweave Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "30163", "Shoulders", "Wings of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32590", "Back", "Nethervoid Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "Alt")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "Alt")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "Alt")

LoonBestInSlot:AddItem(spec, "31065", "Chest", "Shroud of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin", "Alt")
LoonBestInSlot:AddItem(spec, "32327", "Chest", "Robe of the Shadow Council", "Alt")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings", "Alt")

LoonBestInSlot:AddItem(spec, "31061", "Gloves", "Handguards of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt")

LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "BIS")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "Alt")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose", "Alt")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "BIS")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "31067", "Legs", "Leggings of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer", "Alt")
LoonBestInSlot:AddItem(spec, "30162", "Legs", "Leggings of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots", "BIS")
LoonBestInSlot:AddItem(spec, "30050", "Feet", "Boots of the Shifting Nightmare", "Alt")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes", "Alt")

LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "BIS")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl", "BIS")
LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night", "BIS")
LoonBestInSlot:AddItem(spec, "30666", "Neck", "Ritssyn's Lost Pendant", "Alt")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "Alt")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar", "Alt")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye", "Alt")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon", "Alt")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "BIS")

LoonBestInSlot:AddItem(spec, "32374", "MH", "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade", "Alt")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest", "Alt")

LoonBestInSlot:AddItem(spec, "29272", "OH", "Orb of the Soul-Eater", "BIS")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "Alt")
LoonBestInSlot:AddItem(spec, "32361", "OH", "Blind-Seers Icon", "Alt")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "32343", "Wand", "Wand of Prismatic Focus", "Alt")
