local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "3")
LoonBestInSlot:AddItem(spec, "31063", L["Head"], "Cowl of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30152", L["Head"], "Cowl of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32329", L["Head"], "Cowl of Benevolence", "Alt")

LoonBestInSlot:AddItem(spec, "31069", L["Shoulders"], "Mantle of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30154", L["Shoulders"], "Mantle of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32585", L["Shoulders"], "Swiftheal Mantle", "BIS")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "29989", L["Back"], "Sunshower Light Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32337", L["Back"], "Shroud of Forgiveness", "Alt")
LoonBestInSlot:AddItem(spec, "34012", L["Back"], "Shroud of the Final Stand", "Alt")

LoonBestInSlot:AddItem(spec, "31066", L["Chest"], "Vestments of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30150", L["Chest"], "Vestments of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32340", L["Chest"], "Garments of Temperance", "Alt")

LoonBestInSlot:AddItem(spec, "32584", L["Bracers"], "Swiftheal Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "30871", L["Bracers"], "Bracers of Martyrdom", "BIS")
LoonBestInSlot:AddItem(spec, "32513", L["Bracers"], "Wristbands of Divine Influence", "Alt")
LoonBestInSlot:AddItem(spec, "33901", L["Bracers"], "Vindicator's Mooncloth Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "29183", L["Bracers"], "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "32516", L["Bracers"], "Wraps of Purification", "Alt")
LoonBestInSlot:AddItem(spec, "28511", L["Bracers"], "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "31060", L["Gloves"], "Gloves of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30151", L["Gloves"], "Gloves of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "30240", L["Gloves"], "Gloves of the Vanquished Defender", "BIS")
LoonBestInSlot:AddItem(spec, "32353", L["Gloves"], "Gloves of Unfailing Faith", "Alt")

LoonBestInSlot:AddItem(spec, "30895", L["Belt"], "Angelista's Sash", "BIS")
LoonBestInSlot:AddItem(spec, "32519", L["Belt"], "Belt of Divine Guidance", "BIS")
LoonBestInSlot:AddItem(spec, "30036", L["Belt"], "Belt of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "21873", L["Belt"], "Primal Mooncloth Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30912", L["Legs"], "Leggings of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "31068", L["Legs"], "Breeches of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "Alt")
LoonBestInSlot:AddItem(spec, "30153", L["Legs"], "Breeches of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30246", L["Legs"], "Leggings of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30727", L["Legs"], "Gilded Trousers of Benediction", "Alt")

LoonBestInSlot:AddItem(spec, "32609", L["Feet"], "Boots of the Divine Light", "BIS")
LoonBestInSlot:AddItem(spec, "30100", L["Feet"], "Soul-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30885", L["Feet"], "Archbishop's Slippers", "Alt")

LoonBestInSlot:AddItem(spec, "32370", L["Neck"], "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "30018", L["Neck"], "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "33922", L["Neck"], "Vindicator's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "29309", L["Ring"], "Band of the Eternal Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "30110", L["Ring"], "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "29290", L["Ring"], "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "32238", L["Ring"], "Ring of Calming Waves", "Alt")

LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "28823", L["Trinket"], "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "19288", L["Trinket"], "Darkmoon Card: Blue Dragon", "BIS")
LoonBestInSlot:AddItem(spec, "32490", L["Trinket"], "Ashtongue Talisman of Acumen", "Situational")

LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "33743", L["MH"], "Vengeful Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30918", L["MH"], "Hammer of Atonement", "Alt")
LoonBestInSlot:AddItem(spec, "30108", L["MH"], "Lightfathom Scepter", "Alt")
LoonBestInSlot:AddItem(spec, "30908", L["MH"], "Apostle of Argus", "Alt")
LoonBestInSlot:AddItem(spec, "32964", L["MH"], "Merciless Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "32344", L["MH"], "Staff of Immaculate Recovery", "Alt")

LoonBestInSlot:AddItem(spec, "30911", L["OH"], "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "32350", L["OH"], "Touch of Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "29923", L["OH"], "Talisman of the Sun King", "Alt")

LoonBestInSlot:AddItem(spec, "32363", L["Wand"], "Naaru-Blessed Life Rod", "BIS")
LoonBestInSlot:AddItem(spec, "30080", L["Wand"], "Luminescent Rod of the Naaru", "Alt")
