local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy", "3")
LoonBestInSlot:AddItem(spec, "31063", "Head", "Cowl of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "30152", "Head", "Cowl of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "32329", "Head", "Cowl of Benevolence", "Alt")
LoonBestInSlot:AddItem(spec, "32495", "Head", "Powerheal 4000 Lens", "Alt")
LoonBestInSlot:AddItem(spec, "29049", "Head", "Light-Collar of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "29990", "Head", "Crown of the Sun", "Alt")

LoonBestInSlot:AddItem(spec, "31069", "Shoulders", "Mantle of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "30154", "Shoulders", "Mantle of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "32585", "Shoulders", "Swiftheal Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "29054", "Shoulders", "Light-Mantle of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "Alt")
LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness", "Alt")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand", "Alt")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt")

LoonBestInSlot:AddItem(spec, "31066", "Chest", "Vestments of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "30150", "Chest", "Vestments of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe", "Alt")
LoonBestInSlot:AddItem(spec, "29050", "Chest", "Robes of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt")
LoonBestInSlot:AddItem(spec, "32340", "Chest", "Garments of Temperance", "Alt")

LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "30871", "Bracers", "Bracers of Martyrdom", "BIS")
LoonBestInSlot:AddItem(spec, "33901", "Bracers", "Vindicator's Mooncloth Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker", "Alt")
LoonBestInSlot:AddItem(spec, "32516", "Bracers", "Wraps of Purification", "Alt")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling", "Alt")

LoonBestInSlot:AddItem(spec, "31060", "Gloves", "Gloves of Absolution", "BIS")
LoonBestInSlot:AddItem(spec, "30151", "Gloves", "Gloves of the Avatar", "BIS")
LoonBestInSlot:AddItem(spec, "32353", "Gloves", "Gloves of Unfailing Faith", "Alt")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings", "Alt")
LoonBestInSlot:AddItem(spec, "29055", "Gloves", "Handwraps of the Incarnate", "Alt")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash", "BIS")
LoonBestInSlot:AddItem(spec, "32519", "Belt", "Belt of Divine Guidance", "BIS")
LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road", "Alt")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt", "Alt")

LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity", "BIS")
LoonBestInSlot:AddItem(spec, "31068", "Legs", "Breeches of Absolution", "Alt")
LoonBestInSlot:AddItem(spec, "30153", "Legs", "Breeches of the Avatar", "Alt")
LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "Alt")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance", "Alt")

LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light", "BIS")
LoonBestInSlot:AddItem(spec, "30100", "Feet", "Soul-Strider Boots", "Alt")
LoonBestInSlot:AddItem(spec, "30885", "Feet", "Archbishop's Slippers", "Alt")
LoonBestInSlot:AddItem(spec, "30035", "Feet", "Boots of the Long Road", "Alt")

LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "BIS")
LoonBestInSlot:AddItem(spec, "33922", "Neck", "Vindicator's Pendant of Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence", "Alt")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman", "Alt")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul", "Alt")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived", "Alt")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "32238", "Ring", "Ring of Calming Waves", "Alt")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light", "Alt")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving", "Alt")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul", "BIS")
LoonBestInSlot:AddItem(spec, "19288", "Trinket", "Darkmoon Card: Blue Dragon", "BIS")
LoonBestInSlot:AddItem(spec, "30665", "Trinket", "Earring of Soulful Meditation", "Alt")
LoonBestInSlot:AddItem(spec, "32490", "Trinket", "Ashtongue Talisman of Acumen", "Situational")
LoonBestInSlot:AddItem(spec, "23047", "Trinket", "Eye of the Dead", "Alt")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "Alt")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "33743", "MH", "Vengeful Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement", "Alt")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "Alt")
LoonBestInSlot:AddItem(spec, "30908", "MH", "Apostle of Argus", "Alt")
LoonBestInSlot:AddItem(spec, "32964", "MH", "Merciless Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "32344", "MH", "Staff of Immaculate Recovery", "Alt")
LoonBestInSlot:AddItem(spec, "29981", "MH", "Ethereum Life-Staff", "Alt")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice", "Alt")

LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification", "BIS")
LoonBestInSlot:AddItem(spec, "32350", "OH", "Touch of Inspiration", "Alt")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King", "Alt")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb", "Alt")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven", "Alt")

LoonBestInSlot:AddItem(spec, "32363", "Wand", "Naaru-Blessed Life Rod", "BIS")
LoonBestInSlot:AddItem(spec, "30080", "Wand", "Luminescent Rod of the Naaru", "Alt")
LoonBestInSlot:AddItem(spec, "28588", "Wand", "Blue Diamond Witchwand", "Alt")
