local spec = LoonBestInSlot:RegisterSpec("Rogue", "", "3")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "31027", L["Head"], "Slayer's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "31096", L["Head"], "Helm of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "30146", L["Head"], "Deathmantle Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "31030", L["Shoulders"], "Slayer's Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31102", L["Shoulders"], "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32581", L["Shoulders"], "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32377", L["Shoulders"], "Mantle of Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "30149", L["Shoulders"], "Deathmantle Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30248", L["Shoulders"], "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "30917", L["Shoulders"], "Razorfury Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "28672", L["Back"], "Drape of the Dark Reavers", "Alt")

LoonBestInSlot:AddItem(spec, "31028", L["Chest"], "Slayer's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31090", L["Chest"], "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30905", L["Chest"], "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "32252", L["Chest"], "Nether Shadow Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "30101", L["Chest"], "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "30144", L["Chest"], "Deathmantle Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "32580", L["Bracers"], "Swiftstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "29966", L["Bracers"], "Vambraces of Ending", "Alt")

LoonBestInSlot:AddItem(spec, "31026", L["Gloves"], "Slayer's Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31093", L["Gloves"], "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32347", L["Gloves"], "Grips of Damnation", "Alt")
LoonBestInSlot:AddItem(spec, "30145", L["Gloves"], "Deathmantle Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "30239", L["Gloves"], "Gloves of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "32265", L["Belt"], "Shadow-walker's Cord", "Alt")
LoonBestInSlot:AddItem(spec, "30879", L["Belt"], "Don Alejandro's Money Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31029", L["Legs"], "Slayer's Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "31099", L["Legs"], "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30898", L["Legs"], "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30148", L["Legs"], "Deathmantle Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "30245", L["Legs"], "Leggings of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", L["Feet"], "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "Alt")
LoonBestInSlot:AddItem(spec, "29381", L["Neck"], "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "24114", L["Neck"], "Braided Eternium Chain", "Alt")

LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "Alt")

LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "30450", L["Trinket"], "Warp-Spring Coil", "BIS")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "32492", L["Trinket"], "Ashtongue Talisman of Lethality", "Alt")

LoonBestInSlot:AddItem(spec, "32837", L["MH"], "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "33762", L["MH"], "Vengeful Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "30881", L["MH"], "Blade of Infamy", "Alt")
LoonBestInSlot:AddItem(spec, "30082", L["MH"], "Talon of Azshara", "Alt")
LoonBestInSlot:AddItem(spec, "32471", L["MH"], "Shard of Azzinoth", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "33754", L["MH"], "Vengeful Gladiator's Shanker", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "32838", L["OH"], "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "32369", L["OH"], "Blade of Savagery", "BIS")
LoonBestInSlot:AddItem(spec, "33734", L["OH"], "Vengeful Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "32027", L["OH"], "Merciless Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "33756", L["OH"], "Vengeful Gladiator's Shiv", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "30865", L["OH"], "Tracker's Blade", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "29949", L["Ranged"], "Arcanite Steam-Pistol", "BIS")
LoonBestInSlot:AddItem(spec, "32326", L["Ranged"], "Twisted Blades of Zarak", "Alt")
