local spec = LoonBestInSlot:RegisterSpec("Rogue", "", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "31027", "Head", "Slayer's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt")
LoonBestInSlot:AddItem(spec, "30146", "Head", "Deathmantle Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "31030", "Shoulders", "Slayer's Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "32377", "Shoulders", "Mantle of Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "30149", "Shoulders", "Deathmantle Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "30917", "Shoulders", "Razorfury Mantle", "Alt")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers", "Alt")

LoonBestInSlot:AddItem(spec, "31028", "Chest", "Slayer's Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "30144", "Chest", "Deathmantle Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending", "Alt")

LoonBestInSlot:AddItem(spec, "31026", "Gloves", "Slayer's Handguards", "BIS")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation", "Alt")
LoonBestInSlot:AddItem(spec, "30145", "Gloves", "Deathmantle Handguards", "Alt")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "32265", "Belt", "Shadow-walker's Cord", "Alt")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "Alt")

LoonBestInSlot:AddItem(spec, "31029", "Legs", "Slayer's Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30148", "Legs", "Deathmantle Legguards", "Alt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots", "Alt")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "Alt")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent", "Alt")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain", "Alt")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "30450", "Trinket", "Warp-Spring Coil", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "Alt")
LoonBestInSlot:AddItem(spec, "32492", "Trinket", "Ashtongue Talisman of Lethality", "Alt")

LoonBestInSlot:AddItem(spec, "32837", "MH", "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "33762", "MH", "Vengeful Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "30881", "MH", "Blade of Infamy", "Alt")
LoonBestInSlot:AddItem(spec, "30082", "MH", "Talon of Azshara", "Alt")
LoonBestInSlot:AddItem(spec, "32471", "MH", "Shard of Azzinoth", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "33754", "MH", "Vengeful Gladiator's Shanker", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "32838", "OH", "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "32369", "OH", "Blade of Savagery", "BIS")
LoonBestInSlot:AddItem(spec, "33734", "OH", "Vengeful Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "32027", "OH", "Merciless Gladiator's Quickblade", "Alt")
LoonBestInSlot:AddItem(spec, "33756", "OH", "Vengeful Gladiator's Shiv", "BIS Dagger")
LoonBestInSlot:AddItem(spec, "30865", "OH", "Tracker's Blade", "Alt Dagger")

LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "BIS")
LoonBestInSlot:AddItem(spec, "32326", "Ranged", "Twisted Blades of Zarak", "Alt")
