local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "31015", "Head", "Skyshatter Cover", "Alt")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30190", "Head", "Cataclysm Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "32575", "Shoulders", "Shoulders of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "32377", "Shoulders", "Mantle of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "30185", "Chest", "Cataclysm Chestplate", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands", "Alt")

LoonBestInSlot:AddItem(spec, "32234", "Gloves", "Fists of Mukoa", "BIS")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation", "BIS")
LoonBestInSlot:AddItem(spec, "30189", "Gloves", "Cataclysm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "32346", "Belt", "Boneweave Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "32265", "Belt", "Shadow-walker's Cord", "Alt")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "Alt")
LoonBestInSlot:AddItem(spec, "30919", "Belt", "Valestalker Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow", "Alt")

LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30192", "Legs", "Cataclysm Legplates", "Alt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "BIS")
LoonBestInSlot:AddItem(spec, "30880", "Feet", "Quickstrider Moccasins", "Alt")
LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "Alt")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring", "Alt")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality", "Alt")

LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "Alt")

LoonBestInSlot:AddItem(spec, "33669", "MH", "Vengeful Gladiator's Cleaver", "BIS (All)")
LoonBestInSlot:AddItem(spec, "32262", "MH", "Syphon of the Nathrezim", "BIS (All)")
LoonBestInSlot:AddItem(spec, "32946", "MH", "Claw of Molten Fury", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King", "Alt (OH)")
LoonBestInSlot:AddItem(spec, "28433", "MH", "Wicked Edge of the Planes", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "32236", "MH", "Rising Tide", "Alt (All)")
LoonBestInSlot:AddItem(spec, "31965", "MH", "Merciless Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28308", "MH", "Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28767", "MH", "The Decapitator", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "27872", "MH", "The Harvester of Souls", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28944", "MH", "Grand Marshal's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28920", "MH", "High Warlord's Cleaver", "Alt (All)")

LoonBestInSlot:AddItem(spec, "27815", "Totem", "Totem of the Astral Winds", "BIS")
