local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto", "3")
LoonBestInSlot:AddItem(spec, "31012", L["Head"], "Skyshatter Helmet", "BIS")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32241", L["Head"], "Helm of Soothing Currents", "Alt")
LoonBestInSlot:AddItem(spec, "30166", L["Head"], "Cataclysm Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32475", L["Head"], "Living Replicator Specs", "Alt")

LoonBestInSlot:AddItem(spec, "31022", L["Shoulders"], "Skyshatter Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32579", L["Shoulders"], "Living Earth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "30168", L["Shoulders"], "Cataclysm Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "30248", L["Shoulders"], "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30097", L["Shoulders"], "Coral-Barbed Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34012", L["Back"], "Shroud of the Final Stand", "Alt")
LoonBestInSlot:AddItem(spec, "29989", L["Back"], "Sunshower Light Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "31016", L["Chest"], "Skyshatter Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30164", L["Chest"], "Cataclysm Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30887", L["Chest"], "Golden Links of Restoration", "Alt")

LoonBestInSlot:AddItem(spec, "32577", L["Bracers"], "Living Earth Bindings", "BIS")
LoonBestInSlot:AddItem(spec, "32584", L["Bracers"], "Swiftheal Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "32582", L["Bracers"], "Bracers of Renewed Life", "BIS")
LoonBestInSlot:AddItem(spec, "30869", L["Bracers"], "Howling Wind Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30047", L["Bracers"], "Blackfathom Warbands", "Alt")

LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "BIS")
LoonBestInSlot:AddItem(spec, "32275", L["Gloves"], "Spiritwalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29976", L["Gloves"], "Worldstorm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31007", L["Gloves"], "Skyshatter Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31094", L["Gloves"], "Gloves of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "32258", L["Belt"], "Naturalist's Preserving Cinch", "BIS")
LoonBestInSlot:AddItem(spec, "32339", L["Belt"], "Belt of Primal Majesty", "BIS")
LoonBestInSlot:AddItem(spec, "30895", L["Belt"], "Angelista's Sash", "BIS")
LoonBestInSlot:AddItem(spec, "30030", L["Belt"], "Girdle of Fallen Stars", "Alt")

LoonBestInSlot:AddItem(spec, "31019", L["Legs"], "Skyshatter Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31100", L["Legs"], "Leggings of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30912", L["Legs"], "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "32271", L["Legs"], "Kilt of Immortal Nature", "Alt")
LoonBestInSlot:AddItem(spec, "30893", L["Legs"], "Sun-touched Chain Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29991", L["Legs"], "Sunhawk Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30873", L["Feet"], "Stillwater Boots", "BIS")
LoonBestInSlot:AddItem(spec, "32609", L["Feet"], "Boots of the Divine Light", "BIS")
LoonBestInSlot:AddItem(spec, "30737", L["Feet"], "Gold-Leaf Wildboots", "Alt")
LoonBestInSlot:AddItem(spec, "30092", L["Feet"], "Orca-Hide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32370", L["Neck"], "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "30018", L["Neck"], "Lord Sanguinar's Claim", "Alt")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "33922", L["Neck"], "Vindicator's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", L["Ring"], "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "29309", L["Ring"], "Band of the Eternal Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "32238", L["Ring"], "Ring of Calming Waves", "Alt")
LoonBestInSlot:AddItem(spec, "29920", L["Ring"], "Phoenix-Ring of Rebirth", "Alt")
LoonBestInSlot:AddItem(spec, "28790", L["Ring"], "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "32496", L["Trinket"], "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "29376", L["Trinket"], "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", L["Trinket"], "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28190", L["Trinket"], "Scarab of the Infinite Cycle", "Alt")
LoonBestInSlot:AddItem(spec, "28590", L["Trinket"], "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "30841", L["Trinket"], "Lower City Prayerbook", "Alt")

LoonBestInSlot:AddItem(spec, "32500", L["MH"], "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "33743", L["MH"], "Vengeful Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30918", L["MH"], "Hammer of Atonement", "Alt")
LoonBestInSlot:AddItem(spec, "30108", L["MH"], "Lightfathom Scepter", "Alt")

LoonBestInSlot:AddItem(spec, "30882", L["OH"], "Bastion of Light", "BIS")
LoonBestInSlot:AddItem(spec, "32255", L["OH"], "Felstone Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "29458", L["OH"], "Aegis of the Vindicator", "Alt")
LoonBestInSlot:AddItem(spec, "33735", L["OH"], "Vengeful Gladiator's Redoubt", "Alt")
LoonBestInSlot:AddItem(spec, "33309", L["OH"], "Merciless Gladiator's Redoubt", "Alt")

LoonBestInSlot:AddItem(spec, "28523", L["Totem"], "Totem of Healing Rains", "BIS")
