local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto", "3")
LoonBestInSlot:AddItem(spec, "31012", "Head", "Skyshatter Helmet", "BIS")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32241", "Head", "Helm of Soothing Currents", "Alt")
LoonBestInSlot:AddItem(spec, "30166", "Head", "Cataclysm Headguard", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "32475", "Head", "Living Replicator Specs", "Alt")

LoonBestInSlot:AddItem(spec, "31022", "Shoulders", "Skyshatter Shoulderpads", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32579", "Shoulders", "Living Earth Shoulders", "Alt")
LoonBestInSlot:AddItem(spec, "30168", "Shoulders", "Cataclysm Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30097", "Shoulders", "Coral-Barbed Shoulderpads", "Alt")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand", "Alt")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak", "Alt")

LoonBestInSlot:AddItem(spec, "31016", "Chest", "Skyshatter Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30164", "Chest", "Cataclysm Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30887", "Chest", "Golden Links of Restoration", "Alt")

LoonBestInSlot:AddItem(spec, "32577", "Bracers", "Living Earth Bindings", "BIS")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps", "BIS")
LoonBestInSlot:AddItem(spec, "32582", "Bracers", "Bracers of Renewed Life", "BIS")
LoonBestInSlot:AddItem(spec, "30869", "Bracers", "Howling Wind Bracers", "Alt")
LoonBestInSlot:AddItem(spec, "30047", "Bracers", "Blackfathom Warbands", "Alt")

LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "BIS")
LoonBestInSlot:AddItem(spec, "32275", "Gloves", "Spiritwalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29976", "Gloves", "Worldstorm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31007", "Gloves", "Skyshatter Gloves", "Alt")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "Alt")

LoonBestInSlot:AddItem(spec, "32258", "Belt", "Naturalist's Preserving Cinch", "BIS")
LoonBestInSlot:AddItem(spec, "32339", "Belt", "Belt of Primal Majesty", "BIS")
LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash", "BIS")
LoonBestInSlot:AddItem(spec, "30030", "Belt", "Girdle of Fallen Stars", "Alt")

LoonBestInSlot:AddItem(spec, "31019", "Legs", "Skyshatter Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity", "Alt")
LoonBestInSlot:AddItem(spec, "32271", "Legs", "Kilt of Immortal Nature", "Alt")
LoonBestInSlot:AddItem(spec, "30893", "Legs", "Sun-touched Chain Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "29991", "Legs", "Sunhawk Leggings", "Alt")

LoonBestInSlot:AddItem(spec, "30873", "Feet", "Stillwater Boots", "BIS")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light", "BIS")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots", "Alt")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots", "Alt")

LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity", "BIS")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim", "Alt")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "33922", "Neck", "Vindicator's Pendant of Salvation", "Alt")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer", "Alt")
LoonBestInSlot:AddItem(spec, "32238", "Ring", "Ring of Calming Waves", "Alt")
LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth", "Alt")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band", "Alt")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head", "Alt")

LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande", "BIS")
LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr", "BIS")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops", "BIS")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "Alt")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice", "Alt")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook", "Alt")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor", "BIS")
LoonBestInSlot:AddItem(spec, "33743", "MH", "Vengeful Gladiator's Salvation", "Alt")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement", "Alt")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter", "Alt")

LoonBestInSlot:AddItem(spec, "30882", "OH", "Bastion of Light", "BIS")
LoonBestInSlot:AddItem(spec, "32255", "OH", "Felstone Bulwark", "BIS")
LoonBestInSlot:AddItem(spec, "29458", "OH", "Aegis of the Vindicator", "Alt")
LoonBestInSlot:AddItem(spec, "33735", "OH", "Vengeful Gladiator's Redoubt", "Alt")
LoonBestInSlot:AddItem(spec, "33309", "OH", "Merciless Gladiator's Redoubt", "Alt")

LoonBestInSlot:AddItem(spec, "28523", "Totem", "Totem of Healing Rains", "BIS")
