local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance", "3")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "31015", L["Head"], "Skyshatter Cover", "Alt")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "32376", L["Head"], "Forest Prowler's Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30190", L["Head"], "Cataclysm Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32581", L["Shoulders"], "Swiftstrike Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "32575", L["Shoulders"], "Shoulders of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")
LoonBestInSlot:AddItem(spec, "32377", L["Shoulders"], "Mantle of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "29994", L["Back"], "Thalassian Wildercloak", "Alt")
LoonBestInSlot:AddItem(spec, "33122", L["Back"], "Cloak of Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "30905", L["Chest"], "Midnight Chestguard", "BIS")
LoonBestInSlot:AddItem(spec, "32252", L["Chest"], "Nether Shadow Tunic", "Alt")
LoonBestInSlot:AddItem(spec, "30101", L["Chest"], "Bloodsea Brigand's Vest", "Alt")
LoonBestInSlot:AddItem(spec, "30185", L["Chest"], "Cataclysm Chestplate", "Alt")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "32574", L["Bracers"], "Bindings of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "BIS")
LoonBestInSlot:AddItem(spec, "30091", L["Bracers"], "True-Aim Stalker Bands", "Alt")

LoonBestInSlot:AddItem(spec, "32234", L["Gloves"], "Fists of Mukoa", "BIS")
LoonBestInSlot:AddItem(spec, "32347", L["Gloves"], "Grips of Damnation", "BIS")
LoonBestInSlot:AddItem(spec, "30189", L["Gloves"], "Cataclysm Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "30239", L["Gloves"], "Gloves of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")
LoonBestInSlot:AddItem(spec, "32346", L["Belt"], "Boneweave Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "32265", L["Belt"], "Shadow-walker's Cord", "Alt")
LoonBestInSlot:AddItem(spec, "30879", L["Belt"], "Don Alejandro's Money Belt", "Alt")
LoonBestInSlot:AddItem(spec, "30919", L["Belt"], "Valestalker Girdle", "Alt")
LoonBestInSlot:AddItem(spec, "30040", L["Belt"], "Belt of Deep Shadow", "Alt")

LoonBestInSlot:AddItem(spec, "30900", L["Legs"], "Bow-stitched Leggings", "BIS")
LoonBestInSlot:AddItem(spec, "30898", L["Legs"], "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30192", L["Legs"], "Cataclysm Legplates", "Alt")
LoonBestInSlot:AddItem(spec, "30245", L["Legs"], "Leggings of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32366", L["Feet"], "Shadowmaster's Boots", "BIS")
LoonBestInSlot:AddItem(spec, "32510", L["Feet"], "Softstep Boots of Tracking", "BIS")
LoonBestInSlot:AddItem(spec, "30880", L["Feet"], "Quickstrider Moccasins", "Alt")
LoonBestInSlot:AddItem(spec, "30039", L["Feet"], "Boots of Utter Darkness", "Alt")

LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "30017", L["Neck"], "Telonicus's Pendant of Mayhem", "Alt")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "Alt")
LoonBestInSlot:AddItem(spec, "30022", L["Neck"], "Pendant of the Perilous", "Alt")

LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "BIS")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "BIS")
LoonBestInSlot:AddItem(spec, "32526", L["Ring"], "Band of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32335", L["Ring"], "Unstoppable Aggressor's Ring", "Alt")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "Alt")
LoonBestInSlot:AddItem(spec, "30052", L["Ring"], "Ring of Lethality", "Alt")

LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS")
LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "38287", L["Trinket"], "Empty Mug of Direbrew", "BIS")
LoonBestInSlot:AddItem(spec, "31856", L["Trinket"], "Darkmoon Card: Crusade", "Alt")

LoonBestInSlot:AddItem(spec, "33669", L["MH"], "Vengeful Gladiator's Cleaver", "BIS (All)")
LoonBestInSlot:AddItem(spec, "32262", L["MH"], "Syphon of the Nathrezim", "BIS (All)")
LoonBestInSlot:AddItem(spec, "32946", L["MH"], "Claw of Molten Fury", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "32944", L["MH"], "Talon of the Phoenix", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "29996", L["MH"], "Rod of the Sun King", "Alt (OH)")
LoonBestInSlot:AddItem(spec, "28433", L["MH"], "Wicked Edge of the Planes", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "32236", L["MH"], "Rising Tide", "Alt (All)")
LoonBestInSlot:AddItem(spec, "31965", L["MH"], "Merciless Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28439", L["MH"], "Dragonstrike", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "29924", L["MH"], "Netherbane", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28308", L["MH"], "Gladiator's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28767", L["MH"], "The Decapitator", "Alt (MH)")
LoonBestInSlot:AddItem(spec, "27872", L["MH"], "The Harvester of Souls", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28944", L["MH"], "Grand Marshal's Cleaver", "Alt (All)")
LoonBestInSlot:AddItem(spec, "28920", L["MH"], "High Warlord's Cleaver", "Alt (All)")

LoonBestInSlot:AddItem(spec, "27815", L["Totem"], "Totem of the Astral Winds", "BIS")
