local spec = LoonBestInSlot:RegisterSpec("Shaman", "Elemental", "3")
LoonBestInSlot:AddItem(spec, "31014", L["Head"], "Skyshatter Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32525", L["Head"], "Cowl of the Illidari High Lord", "Alt")
LoonBestInSlot:AddItem(spec, "29035", L["Head"], "Cyclone Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "29760", L["Head"], "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30171", L["Head"], "Cataclysm Headpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30242", L["Head"], "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "31023", L["Shoulders"], "Skyshatter Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32587", L["Shoulders"], "Mantle of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30884", L["Shoulders"], "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "29037", L["Shoulders"], "Cyclone Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "29763", L["Shoulders"], "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30173", L["Shoulders"], "Cataclysm Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30248", L["Shoulders"], "Pauldrons of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32331", L["Back"], "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28797", L["Back"], "Brute Cloak of the Ogre-Magi", "Alt")

LoonBestInSlot:AddItem(spec, "31017", L["Chest"], "Skyshatter Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32592", L["Chest"], "Chestguard of Relentless Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30169", L["Chest"], "Cataclysm Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30236", L["Chest"], "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30107", L["Chest"], "Vestments of the Sea-Witch", "Alt")

LoonBestInSlot:AddItem(spec, "32586", L["Bracers"], "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30870", L["Bracers"], "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32259", L["Bracers"], "Bands of the Coming Storm", "Alt")
LoonBestInSlot:AddItem(spec, "29918", L["Bracers"], "Mindstorm Wristbands", "Alt")

LoonBestInSlot:AddItem(spec, "31008", L["Gloves"], "Skyshatter Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "31094", L["Gloves"], "Gloves of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32328", L["Gloves"], "Botanist's Gloves of Growth", "Alt")
LoonBestInSlot:AddItem(spec, "32275", L["Gloves"], "Spiritwalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28780", L["Gloves"], "Soul-Eater's Handwraps", "Alt")

LoonBestInSlot:AddItem(spec, "32276", L["Belt"], "Flashfire Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "32256", L["Belt"], "Waistwrap of Infinity", "Alt")
LoonBestInSlot:AddItem(spec, "30038", L["Belt"], "Belt of Blasting", "Alt")

LoonBestInSlot:AddItem(spec, "30916", L["Legs"], "Leggings of Channeled Elements", "BIS")
LoonBestInSlot:AddItem(spec, "31020", L["Legs"], "Skyshatter Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "31100", L["Legs"], "Leggings of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30172", L["Legs"], "Cataclysm Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30245", L["Legs"], "Leggings of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "Alt")

LoonBestInSlot:AddItem(spec, "32239", L["Feet"], "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "32352", L["Feet"], "Naturewarden's Treads", "BIS")
LoonBestInSlot:AddItem(spec, "32242", L["Feet"], "Boots of Oceanic Fury", "BIS")
LoonBestInSlot:AddItem(spec, "30067", L["Feet"], "Velvet Boots of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "30015", L["Neck"], "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "32349", L["Neck"], "Translucent Spellthread Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "32527", L["Ring"], "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "32247", L["Ring"], "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30667", L["Ring"], "Ring of Unrelenting Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30109", L["Ring"], "Ring of Endless Coils", "Alt")

LoonBestInSlot:AddItem(spec, "32483", L["Trinket"], "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "28785", L["Trinket"], "The Lightning Capacitor", "BIS")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", L["Trinket"], "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "31856", L["Trinket"], "Darkmoon Card: Crusade", "Alt")

LoonBestInSlot:AddItem(spec, "32374", L["MH"], "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "32237", L["MH"], "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "33687", L["MH"], "Vengeful Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "34009", L["MH"], "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "29988", L["MH"], "The Nexus Key", "Alt")

LoonBestInSlot:AddItem(spec, "30909", L["OH"], "Antonidas's Aegis of Rapt Concentration", "BIS")
LoonBestInSlot:AddItem(spec, "30872", L["OH"], "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "30049", L["OH"], "Fathomstone", "Alt")

LoonBestInSlot:AddItem(spec, "32330", L["Totem"], "Totem of Ancestral Guidance", "BIS")
LoonBestInSlot:AddItem(spec, "28248", L["Totem"], "Totem of the Void", "Alt")
