local spec = LoonBestInSlot:RegisterSpec("Shaman", "Elemental", "3")
LoonBestInSlot:AddItem(spec, "31014", "Head", "Skyshatter Headguard", "BIS")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "Alt")
LoonBestInSlot:AddItem(spec, "29035", "Head", "Cyclone Faceguard", "Alt")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30171", "Head", "Cataclysm Headpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "31023", "Shoulders", "Skyshatter Mantle", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "29037", "Shoulders", "Cyclone Shoulderguards", "Alt")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30173", "Shoulders", "Cataclysm Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt")

LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi", "Alt")

LoonBestInSlot:AddItem(spec, "31017", "Chest", "Skyshatter Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32592", "Chest", "Chestguard of Relentless Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30169", "Chest", "Cataclysm Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch", "Alt")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "32259", "Bracers", "Bands of the Coming Storm", "Alt")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands", "Alt")

LoonBestInSlot:AddItem(spec, "31008", "Gloves", "Skyshatter Gauntlets", "BIS")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth", "Alt")
LoonBestInSlot:AddItem(spec, "32275", "Gloves", "Spiritwalker Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps", "Alt")

LoonBestInSlot:AddItem(spec, "32276", "Belt", "Flashfire Girdle", "BIS")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity", "Alt")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting", "Alt")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "BIS")
LoonBestInSlot:AddItem(spec, "31020", "Legs", "Skyshatter Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30172", "Legs", "Cataclysm Leggings", "Alt")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants", "Alt")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "32352", "Feet", "Naturewarden's Treads", "BIS")
LoonBestInSlot:AddItem(spec, "32242", "Feet", "Boots of Oceanic Fury", "BIS")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere", "BIS")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30667", "Ring", "Ring of Unrelenting Storms", "Alt")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils", "Alt")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "28785", "Trinket", "The Lightning Capacitor", "BIS")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade", "Alt")

LoonBestInSlot:AddItem(spec, "32374", "MH", "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel", "Alt")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement", "Alt")
LoonBestInSlot:AddItem(spec, "29988", "MH", "The Nexus Key", "Alt")

LoonBestInSlot:AddItem(spec, "30909", "OH", "Antonidas's Aegis of Rapt Concentration", "BIS")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone", "Alt")

LoonBestInSlot:AddItem(spec, "32330", "Totem", "Totem of Ancestral Guidance", "BIS")
LoonBestInSlot:AddItem(spec, "28248", "Totem", "Totem of the Void", "Alt")
