local spec = LoonBestInSlot:RegisterSpec("Warlock", "Afflic", "3")
LoonBestInSlot:AddItem(spec, "31051", L["Head"], "Hood of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31097", L["Head"], "Helm of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32525", L["Head"], "Cowl of the Illidari High Lord", "BIS")
LoonBestInSlot:AddItem(spec, "32494", L["Head"], "Destruction Holo-gogs", "Alt")
LoonBestInSlot:AddItem(spec, "30212", L["Head"], "Hood of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30244", L["Head"], "Helm of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "31054", L["Shoulders"], "Mantle of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31101", L["Shoulders"], "Pauldrons of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "32338", L["Shoulders"], "Blood-cursed Shoulderpads", "Alt")
LoonBestInSlot:AddItem(spec, "30884", L["Shoulders"], "Hatefury Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "32587", L["Shoulders"], "Mantle of Nimble Thought", "Alt")
LoonBestInSlot:AddItem(spec, "28967", L["Shoulders"], "Voidheart Mantle", "Alt")
LoonBestInSlot:AddItem(spec, "29762", L["Shoulders"], "Pauldrons of the Fallen Hero", "Alt")

LoonBestInSlot:AddItem(spec, "32590", L["Back"], "Nethervoid Cloak", "BIS")
LoonBestInSlot:AddItem(spec, "32524", L["Back"], "Shroud of the Highborne", "BIS")
LoonBestInSlot:AddItem(spec, "32331", L["Back"], "Cloak of the Illidari Council", "BIS")
LoonBestInSlot:AddItem(spec, "28766", L["Back"], "Ruby Drape of the Mysticant", "Alt")
LoonBestInSlot:AddItem(spec, "30735", L["Back"], "Ancient Spellcloak of the Highborne", "Alt")

LoonBestInSlot:AddItem(spec, "30107", L["Chest"], "Vestments of the Sea-Witch", "BIS")
LoonBestInSlot:AddItem(spec, "31052", L["Chest"], "Robe of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31089", L["Chest"], "Chestguard of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30913", L["Chest"], "Robes of Rhonin", "Alt")
LoonBestInSlot:AddItem(spec, "32327", L["Chest"], "Robe of the Shadow Council", "Alt")

LoonBestInSlot:AddItem(spec, "32586", L["Bracers"], "Bracers of Nimble Thought", "BIS")
LoonBestInSlot:AddItem(spec, "32270", L["Bracers"], "Focused Mana Bindings", "Alt")
LoonBestInSlot:AddItem(spec, "30870", L["Bracers"], "Cuffs of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "33913", L["Bracers"], "Vindicator's Silk Cuffs", "Alt")
LoonBestInSlot:AddItem(spec, "29918", L["Bracers"], "Mindstorm Wristbands", "Alt")

LoonBestInSlot:AddItem(spec, "31050", L["Gloves"], "Gloves of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31092", L["Gloves"], "Gloves of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30725", L["Gloves"], "Anger-Spark Gloves", "Alt")

LoonBestInSlot:AddItem(spec, "30038", L["Belt"], "Belt of Blasting", "BIS")
LoonBestInSlot:AddItem(spec, "30888", L["Belt"], "Anetheron's Noose", "BIS")
LoonBestInSlot:AddItem(spec, "32256", L["Belt"], "Waistwrap of Infinity", "BIS")

LoonBestInSlot:AddItem(spec, "30916", L["Legs"], "Leggings of Channeled Elements", "BIS")
LoonBestInSlot:AddItem(spec, "32367", L["Legs"], "Leggings of Devastation", "BIS")
LoonBestInSlot:AddItem(spec, "31053", L["Legs"], "Leggings of the Malefic", "BIS")
LoonBestInSlot:AddItem(spec, "31098", L["Legs"], "Leggings of the Forgotten Conqueror", "BIS")
LoonBestInSlot:AddItem(spec, "30734", L["Legs"], "Leggings of the Seventh Circle", "Alt")
LoonBestInSlot:AddItem(spec, "24262", L["Legs"], "Spellstrike Pants", "Alt")
LoonBestInSlot:AddItem(spec, "30213", L["Legs"], "Leggings of the Corruptor", "Alt")
LoonBestInSlot:AddItem(spec, "30247", L["Legs"], "Leggings of the Vanquished Hero", "Alt")

LoonBestInSlot:AddItem(spec, "32239", L["Feet"], "Slippers of the Seacaller", "BIS")
LoonBestInSlot:AddItem(spec, "30894", L["Feet"], "Blue Suede Shoes", "Alt")
LoonBestInSlot:AddItem(spec, "30037", L["Feet"], "Boots of Blasting", "Alt")

LoonBestInSlot:AddItem(spec, "32349", L["Neck"], "Translucent Spellthread Necklace", "BIS")
LoonBestInSlot:AddItem(spec, "30015", L["Neck"], "The Sun King's Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "32405", L["Neck"], "Verdant Sphere", "BIS")

LoonBestInSlot:AddItem(spec, "32527", L["Ring"], "Ring of Ancient Knowledge", "BIS")
LoonBestInSlot:AddItem(spec, "32247", L["Ring"], "Ring of Captured Storms", "BIS")
LoonBestInSlot:AddItem(spec, "29305", L["Ring"], "Band of the Eternal Sage", "BIS")
LoonBestInSlot:AddItem(spec, "30109", L["Ring"], "Ring of Endless Coils", "Alt")
LoonBestInSlot:AddItem(spec, "28753", L["Ring"], "Ring of Recurrence", "Alt")
LoonBestInSlot:AddItem(spec, "28793", L["Ring"], "Band of Crimson Fury", "Alt")
LoonBestInSlot:AddItem(spec, "32385", L["Ring"], "Magtheridon's Head", "Alt")
LoonBestInSlot:AddItem(spec, "32941", L["Ring"], "Corruptor's Signet", "Alt")

LoonBestInSlot:AddItem(spec, "32483", L["Trinket"], "The Skull of Gul'dan", "BIS")
LoonBestInSlot:AddItem(spec, "27683", L["Trinket"], "Quagmirran's Eye", "BIS")
LoonBestInSlot:AddItem(spec, "29370", L["Trinket"], "Icon of the Silver Crescent", "BIS")
LoonBestInSlot:AddItem(spec, "38290", L["Trinket"], "Dark Iron Smoking Pipe", "BIS")
LoonBestInSlot:AddItem(spec, "31856", L["Trinket"], "Darkmoon Card: Crusade", "Alt")

LoonBestInSlot:AddItem(spec, "32374", L["2H"], "Zhar'doom, Greatstaff of the Devourer", "BIS")
LoonBestInSlot:AddItem(spec, "22630", L["2H"], "Atiesh, Greatstaff of the Guardian", "Alt")

LoonBestInSlot:AddItem(spec, "30910", L["MH"], "Tempest of Chaos", "BIS")
LoonBestInSlot:AddItem(spec, "33763", L["MH"], "Vengeful Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "32237", L["MH"], "The Maelstrom's Fury", "Alt")
LoonBestInSlot:AddItem(spec, "32053", L["MH"], "Merciless Gladiator's Spellblade", "Alt")
LoonBestInSlot:AddItem(spec, "30095", L["MH"], "Fang of the Leviathan", "Alt")
LoonBestInSlot:AddItem(spec, "30723", L["MH"], "Talon of the Tempest", "Alt")

LoonBestInSlot:AddItem(spec, "30872", L["OH"], "Chronicle of Dark Secrets", "BIS")
LoonBestInSlot:AddItem(spec, "32361", L["OH"], "Blind-Seers Icon", "Alt")
LoonBestInSlot:AddItem(spec, "30049", L["OH"], "Fathomstone", "Alt")

LoonBestInSlot:AddItem(spec, "29982", L["Wand"], "Wand of the Forgotten Star", "BIS")
LoonBestInSlot:AddItem(spec, "32343", L["Wand"], "Wand of Prismatic Focus", "Alt")
