local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "3")
LoonBestInSlot:AddItem(spec, "32521", L["Head"], "Faceplate of the Impenetrable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33730", L["Head"], "Vengeful Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30974", L["Head"], "Onslaught Greathelm", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30972", L["Head"], "Onslaught Battle-Helm", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "33732", L["Shoulders"], "Vengeful Gladiator's Plate Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "30979", L["Shoulders"], "Onslaught Shoulderblades", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30122", L["Shoulders"], "Destroyer Shoulderblades", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30249", L["Shoulders"], "Pauldrons of the Vanquished Defender", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30980", L["Shoulders"], "Onslaught Shoulderguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32250", L["Shoulders"], "Pauldrons of Abyssal Fury", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34010", L["Back"], "Pepe's Shroud of Pacification", "BIS")
LoonBestInSlot:AddItem(spec, "33122", L["Back"], "Cloak of Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "28529", L["Back"], "Royal Cloak of Arathi Kings", "Alt")
LoonBestInSlot:AddItem(spec, "29925", L["Back"], "Phoenix-Wing Cloak", "BIS Mit")

LoonBestInSlot:AddItem(spec, "33728", L["Chest"], "Vengeful Gladiator's Plate Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "30975", L["Chest"], "Onslaught Breastplate", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30113", L["Chest"], "Destroyer Chestguard", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30896", L["Chest"], "Glory of the Defender", "Alt Mit")

LoonBestInSlot:AddItem(spec, "33813", L["Bracers"], "Vindicator's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30861", L["Bracers"], "Furious Shackles", "Alt")
LoonBestInSlot:AddItem(spec, "32232", L["Bracers"], "Eternium Shell Bracers", "BIS Mit")

LoonBestInSlot:AddItem(spec, "32280", L["Gloves"], "Gauntlets of Enforcement", "BIS")
LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32608", L["Gloves"], "Pillager's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29998", L["Gloves"], "Royal Gauntlets of Silvermoon", "BIS Mit")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32333", L["Belt"], "Girdle of Stability", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32342", L["Belt"], "Girdle of Mighty Resolve", "Alt Mit")

LoonBestInSlot:AddItem(spec, "33731", L["Legs"], "Vengeful Gladiator's Plate Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "30977", L["Legs"], "Onslaught Greaves", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31100", L["Legs"], "Leggings of the Forgotten Protector", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30903", L["Legs"], "Legguards of Endless Rage", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32263", L["Legs"], "Praetorian's Legguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30978", L["Legs"], "Onslaught Legguards", "Alt Mit")

LoonBestInSlot:AddItem(spec, "33812", L["Feet"], "Vindicator's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "32345", L["Feet"], "Dreadboots of the Legion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32268", L["Feet"], "Myrmidon's Treads", "BIS Mit")

LoonBestInSlot:AddItem(spec, "32362", L["Neck"], "Pendant of Titans", "BIS")
LoonBestInSlot:AddItem(spec, "33923", L["Neck"], "Vindicator's Pendant of Triumph", "Alt")
LoonBestInSlot:AddItem(spec, "30099", L["Neck"], "Frayed Tether of the Drowned", "Alt")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "Alt")

LoonBestInSlot:AddItem(spec, "30834", L["Ring"], "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32266", L["Ring"], "Ring of Deceitful Intent", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33919", L["Ring"], "Vindicator's Band of Triumph", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29296", L["Ring"], "Band of Eternity", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32261", L["Ring"], "Band of the Abyssal Lord", "Alt Mit")

LoonBestInSlot:AddItem(spec, "31858", L["Trinket"], "Darkmoon Card: Vengeance", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31859", L["Trinket"], "Darkmoon Card: Madness", "BIS Stam")
LoonBestInSlot:AddItem(spec, "37128", L["Trinket"], "Balebrew Charm", "Alt Stam")
LoonBestInSlot:AddItem(spec, "37127", L["Trinket"], "Brightbrew Charm", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32864", L["Trinket"], "Commander's Badge", "Alt Stam")
LoonBestInSlot:AddItem(spec, "23836", L["Trinket"], "Goblin Rocket Launcher", "Alt Stam")
LoonBestInSlot:AddItem(spec, "23835", L["Trinket"], "Gnomish Poultryizer", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32501", L["Trinket"], "Shadowmoon Insignia", "Alt Mit")
LoonBestInSlot:AddItem(spec, "10725", L["Trinket"], "Gnomish Battle Chicken", "Alt")

LoonBestInSlot:AddItem(spec, "32254", L["MH"], "The Brutalizer", "BIS")
LoonBestInSlot:AddItem(spec, "32369", L["MH"], "Blade of Savagery", "BIS")
LoonBestInSlot:AddItem(spec, "32943", L["MH"], "Swiftsteel Bludgeon", "Alt")
LoonBestInSlot:AddItem(spec, "30874", L["MH"], "The Unbreakable Will", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30058", L["MH"], "Mallet of the Tides", "Alt")

LoonBestInSlot:AddItem(spec, "32375", L["Shield"], "Bulwark of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "30889", L["Shield"], "Kaz'rogal's Hardened Heart", "Alt")
LoonBestInSlot:AddItem(spec, "33755", L["Shield"], "Vengeful Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28825", L["Shield"], "Aldori Legacy Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32253", L["Ranged"], "Legionkiller", "BIS")
LoonBestInSlot:AddItem(spec, "29949", L["Ranged"], "Arcanite Steam-Pistol", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33765", L["Ranged"], "Vengeful Gladiator's War Edge", "Alt")
LoonBestInSlot:AddItem(spec, "32756", L["Ranged"], "Gyro-Balanced Khorium Destroyer", "BIS Mit")
