local spec = LoonBestInSlot:RegisterSpec("Warrior", "Arms", "3")
LoonBestInSlot:AddItem(spec, "32235", L["Head"], "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "32373", L["Head"], "Helm of the Illidari Shatterer", "Alt")
LoonBestInSlot:AddItem(spec, "30972", L["Head"], "Onslaught Battle-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "31095", L["Head"], "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "30120", L["Head"], "Destroyer Battle-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30243", L["Head"], "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30979", L["Shoulders"], "Onslaught Shoulderblades", "BIS")
LoonBestInSlot:AddItem(spec, "31103", L["Shoulders"], "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32570", L["Shoulders"], "Swiftsteel Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "30055", L["Shoulders"], "Shoulderpads of the Stranger", "Alt")

LoonBestInSlot:AddItem(spec, "32323", L["Back"], "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "33122", L["Back"], "Cloak of Darkness", "BIS")
LoonBestInSlot:AddItem(spec, "24259", L["Back"], "Vengeance Wrap", "Alt")

LoonBestInSlot:AddItem(spec, "30975", L["Chest"], "Onslaught Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "31091", L["Chest"], "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30905", L["Chest"], "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "30118", L["Chest"], "Destroyer Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30237", L["Chest"], "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30101", L["Chest"], "Bloodsea Brigand's Vest", "Alt")

LoonBestInSlot:AddItem(spec, "30863", L["Bracers"], "Deadly Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "32324", L["Bracers"], "Insidious Bands", "Alt")
LoonBestInSlot:AddItem(spec, "32574", L["Bracers"], "Bindings of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "30057", L["Bracers"], "Bracers of Eradication", "Alt")
LoonBestInSlot:AddItem(spec, "28795", L["Bracers"], "Bladespire Warbands", "Alt")
LoonBestInSlot:AddItem(spec, "30861", L["Bracers"], "Furious Shackles", "Alt")

LoonBestInSlot:AddItem(spec, "32278", L["Gloves"], "Grips of Silent Justice", "BIS")
LoonBestInSlot:AddItem(spec, "30969", L["Gloves"], "Onslaught Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31094", L["Gloves"], "Gloves of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "32608", L["Gloves"], "Pillager's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28824", L["Gloves"], "Gauntlets of Martial Perfection", "Alt")
LoonBestInSlot:AddItem(spec, "29947", L["Gloves"], "Gloves of the Searing Grip", "Alt")

LoonBestInSlot:AddItem(spec, "30106", L["Belt"], "Belt of One-Hundred Deaths", "BIS")

LoonBestInSlot:AddItem(spec, "32341", L["Legs"], "Leggings of Divine Retribution", "BIS")
LoonBestInSlot:AddItem(spec, "30898", L["Legs"], "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30903", L["Legs"], "Legguards of Endless Rage", "Alt")
LoonBestInSlot:AddItem(spec, "30977", L["Legs"], "Onslaught Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "31100", L["Legs"], "Leggings of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "29995", L["Legs"], "Leggings of Murderous Intent", "Alt")

LoonBestInSlot:AddItem(spec, "32345", L["Feet"], "Dreadboots of the Legion", "BIS")
LoonBestInSlot:AddItem(spec, "30081", L["Feet"], "Warboots of Obliteration", "Alt")

LoonBestInSlot:AddItem(spec, "32260", L["Neck"], "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "32591", L["Neck"], "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "30022", L["Neck"], "Pendant of the Perilous", "Alt")

LoonBestInSlot:AddItem(spec, "32497", L["Ring"], "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "32335", L["Ring"], "Unstoppable Aggressor's Ring", "BIS")
LoonBestInSlot:AddItem(spec, "32526", L["Ring"], "Band of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "29997", L["Ring"], "Band of the Ranger-General", "Alt")
LoonBestInSlot:AddItem(spec, "29301", L["Ring"], "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "33919", L["Ring"], "Vindicator's Band of Triumph", "Alt")

LoonBestInSlot:AddItem(spec, "28830", L["Trinket"], "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", L["Trinket"], "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "30627", L["Trinket"], "Tsunami Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "29383", L["Trinket"], "Bloodlust Brooch", "BIS")

LoonBestInSlot:AddItem(spec, "30902", L["2H"], "Cataclysm's Edge", "BIS")
LoonBestInSlot:AddItem(spec, "32348", L["2H"], "Soul Cleaver", "BIS")
LoonBestInSlot:AddItem(spec, "29993", L["2H"], "Twinblade of the Phoenix", "BIS")
LoonBestInSlot:AddItem(spec, "33688", L["2H"], "Vengeful Gladiator's Greatsword", "Alt")

LoonBestInSlot:AddItem(spec, "32837", L["MH"], "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "33669", L["MH"], "Vengeful Gladiator's Cleaver", "Alt")
LoonBestInSlot:AddItem(spec, "33762", L["MH"], "Vengeful Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "30082", L["MH"], "Talon of Azshara", "Alt")

LoonBestInSlot:AddItem(spec, "32838", L["OH"], "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "30881", L["OH"], "Blade of Infamy", "Alt")
LoonBestInSlot:AddItem(spec, "32369", L["OH"], "Blade of Savagery", "Alt")

LoonBestInSlot:AddItem(spec, "32326", L["Ranged"], "Twisted Blades of Zarak", "BIS")
LoonBestInSlot:AddItem(spec, "30105", L["Ranged"], "Serpent Spine Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "30724", L["Ranged"], "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28772", L["Ranged"], "Sunfury Bow of the Phoenix", "Alt")
