local spec = LoonBestInSlot:RegisterSpec("Warrior", "Fury", "3")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras", "BIS")
LoonBestInSlot:AddItem(spec, "32373", "Head", "Helm of the Illidari Shatterer", "Alt")
LoonBestInSlot:AddItem(spec, "30972", "Head", "Onslaught Battle-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "30120", "Head", "Destroyer Battle-Helm", "Alt")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt")

LoonBestInSlot:AddItem(spec, "30979", "Shoulders", "Onslaught Shoulderblades", "BIS")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "32570", "Shoulders", "Swiftsteel Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger", "Alt")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "BIS")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap", "Alt")

LoonBestInSlot:AddItem(spec, "30975", "Chest", "Onslaught Breastplate", "BIS")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard", "Alt")
LoonBestInSlot:AddItem(spec, "33728", "Chest", "Vengeful Gladiator's Plate Chestpiece", "Alt")
LoonBestInSlot:AddItem(spec, "30118", "Chest", "Destroyer Breastplate", "Alt")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest", "Alt")

LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs", "BIS")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands", "Alt")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "BIS")
LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication", "Alt")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands", "Alt")
LoonBestInSlot:AddItem(spec, "30861", "Bracers", "Furious Shackles", "Alt")

LoonBestInSlot:AddItem(spec, "32278", "Gloves", "Grips of Silent Justice", "BIS")
LoonBestInSlot:AddItem(spec, "30969", "Gloves", "Onslaught Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "32608", "Gloves", "Pillager's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "28824", "Gloves", "Gauntlets of Martial Perfection", "Alt")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "Alt")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS")

LoonBestInSlot:AddItem(spec, "32341", "Legs", "Leggings of Divine Retribution", "BIS")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons", "Alt")
LoonBestInSlot:AddItem(spec, "30903", "Legs", "Legguards of Endless Rage", "Alt")
LoonBestInSlot:AddItem(spec, "30977", "Legs", "Onslaught Greaves", "Alt")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "Alt")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent", "Alt")

LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion", "BIS")
LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration", "Alt")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares", "BIS")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "BIS")
LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous", "Alt")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring", "BIS")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring", "BIS")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation", "Alt")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "Alt")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "Alt")
LoonBestInSlot:AddItem(spec, "33919", "Ring", "Vindicator's Band of Triumph", "Alt")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy", "BIS")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer", "BIS")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman", "BIS")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch", "Alt")

LoonBestInSlot:AddItem(spec, "32837", "MH", "Warglaive of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "33669", "MH", "Vengeful Gladiator's Cleaver", "Alt")
LoonBestInSlot:AddItem(spec, "33762", "MH", "Vengeful Gladiator's Slicer", "Alt")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike", "Alt")
LoonBestInSlot:AddItem(spec, "30881", "MH", "Blade of Infamy", "Alt")

LoonBestInSlot:AddItem(spec, "32838", "OH", "Warglaive of Azzinoth", "BIS")

LoonBestInSlot:AddItem(spec, "32326", "Ranged", "Twisted Blades of Zarak", "BIS")
LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow", "BIS")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle", "BIS")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt")
