local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot", "3")
LoonBestInSlot:AddItem(spec, "32521", "Head", "Faceplate of the Impenetrable", "BIS Mit")
LoonBestInSlot:AddItem(spec, "33730", "Head", "Vengeful Gladiator's Plate Helm", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30974", "Head", "Onslaught Greathelm", "Alt Mit")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt Mit")
LoonBestInSlot:AddItem(spec, "30972", "Head", "Onslaught Battle-Helm", "Alt Thrt")

LoonBestInSlot:AddItem(spec, "33732", "Shoulders", "Vengeful Gladiator's Plate Shoulders", "BIS")
LoonBestInSlot:AddItem(spec, "30979", "Shoulders", "Onslaught Shoulderblades", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30122", "Shoulders", "Destroyer Shoulderblades", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "30980", "Shoulders", "Onslaught Shoulderguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32250", "Shoulders", "Pauldrons of Abyssal Fury", "Alt Mit")

LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification", "BIS")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness", "Alt")
LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings", "Alt")
LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak", "BIS Mit")

LoonBestInSlot:AddItem(spec, "33728", "Chest", "Vengeful Gladiator's Plate Chestpiece", "BIS")
LoonBestInSlot:AddItem(spec, "30975", "Chest", "Onslaught Breastplate", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30113", "Chest", "Destroyer Chestguard", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30896", "Chest", "Glory of the Defender", "Alt Mit")

LoonBestInSlot:AddItem(spec, "33813", "Bracers", "Vindicator's Plate Bracers", "BIS")
LoonBestInSlot:AddItem(spec, "30861", "Bracers", "Furious Shackles", "Alt")
LoonBestInSlot:AddItem(spec, "32232", "Bracers", "Eternium Shell Bracers", "BIS Mit")

LoonBestInSlot:AddItem(spec, "32280", "Gloves", "Gauntlets of Enforcement", "BIS")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32608", "Gloves", "Pillager's Gauntlets", "Alt")
LoonBestInSlot:AddItem(spec, "29998", "Gloves", "Royal Gauntlets of Silvermoon", "BIS Mit")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32333", "Belt", "Girdle of Stability", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32342", "Belt", "Girdle of Mighty Resolve", "Alt Mit")

LoonBestInSlot:AddItem(spec, "33731", "Legs", "Vengeful Gladiator's Plate Legguards", "BIS")
LoonBestInSlot:AddItem(spec, "30977", "Legs", "Onslaught Greaves", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "30903", "Legs", "Legguards of Endless Rage", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "32263", "Legs", "Praetorian's Legguards", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30978", "Legs", "Onslaught Legguards", "Alt Mit")

LoonBestInSlot:AddItem(spec, "33812", "Feet", "Vindicator's Plate Greaves", "BIS")
LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32268", "Feet", "Myrmidon's Treads", "BIS Mit")

LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans", "BIS")
LoonBestInSlot:AddItem(spec, "33923", "Neck", "Vindicator's Pendant of Triumph", "Alt")
LoonBestInSlot:AddItem(spec, "30099", "Neck", "Frayed Tether of the Drowned", "Alt")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades", "Alt")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "33919", "Ring", "Vindicator's Band of Triumph", "Alt Thrt")
LoonBestInSlot:AddItem(spec, "29296", "Ring", "Band of Eternity", "BIS Mit")
LoonBestInSlot:AddItem(spec, "32261", "Ring", "Band of the Abyssal Lord", "Alt Mit")

LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance", "BIS Stam")
LoonBestInSlot:AddItem(spec, "31859", "Trinket", "Darkmoon Card: Madness", "BIS Stam")
LoonBestInSlot:AddItem(spec, "37128", "Trinket", "Balebrew Charm", "Alt Stam")
LoonBestInSlot:AddItem(spec, "37127", "Trinket", "Brightbrew Charm", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32864", "Trinket", "Commander's Badge", "Alt Stam")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher", "Alt Stam")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer", "Alt Stam")
LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia", "Alt Mit")
LoonBestInSlot:AddItem(spec, "10725", "Trinket", "Gnomish Battle Chicken", "Alt")

LoonBestInSlot:AddItem(spec, "32254", "MH", "The Brutalizer", "BIS")
LoonBestInSlot:AddItem(spec, "32369", "MH", "Blade of Savagery", "BIS")
LoonBestInSlot:AddItem(spec, "32943", "MH", "Swiftsteel Bludgeon", "Alt")
LoonBestInSlot:AddItem(spec, "30874", "MH", "The Unbreakable Will", "BIS Mit")
LoonBestInSlot:AddItem(spec, "30058", "MH", "Mallet of the Tides", "Alt")

LoonBestInSlot:AddItem(spec, "32375", "Shield", "Bulwark of Azzinoth", "BIS")
LoonBestInSlot:AddItem(spec, "30889", "Shield", "Kaz'rogal's Hardened Heart", "Alt")
LoonBestInSlot:AddItem(spec, "33755", "Shield", "Vengeful Gladiator's Shield Wall", "Alt")
LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender", "Alt")

LoonBestInSlot:AddItem(spec, "32253", "Ranged", "Legionkiller", "BIS")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol", "BIS Thrt")
LoonBestInSlot:AddItem(spec, "33765", "Ranged", "Vengeful Gladiator's War Edge", "Alt")
LoonBestInSlot:AddItem(spec, "32756", "Ranged", "Gyro-Balanced Khorium Destroyer", "BIS Mit")
