local spec0 = LBIS:RegisterSpec(LBIS.L["Death Knight"], LBIS.L["Unholy"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Death Knight"], LBIS.L["Unholy"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Death Knight"], LBIS.L["Unholy"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Death Knight"], LBIS.L["Unholy"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Death Knight"], LBIS.L["Unholy"], "4")
