local spec0 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Marksmanship"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Marksmanship"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Marksmanship"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Marksmanship"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Marksmanship"], "4")
