local spec0 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Beast Mastery"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Beast Mastery"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Beast Mastery"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Beast Mastery"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Hunter"], LBIS.L["Beast Mastery"], "4")
