local spec0 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Frost"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Frost"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Frost"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Frost"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Frost"], "4")
