local spec0 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Arcane"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Arcane"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Arcane"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Arcane"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Arcane"], "4")
