local spec0 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Fire"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Fire"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Fire"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Fire"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Mage"], LBIS.L["Fire"], "4")
