local spec0 = LBIS:RegisterSpec(LBIS.L["Monk"], LBIS.L["Windwalker"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Monk"], LBIS.L["Windwalker"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Monk"], LBIS.L["Windwalker"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Monk"], LBIS.L["Windwalker"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Monk"], LBIS.L["Windwalker"], "4")
