local spec0 = LBIS:RegisterSpec(LBIS.L["Priest"], LBIS.L["Discipline"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Priest"], LBIS.L["Discipline"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Priest"], LBIS.L["Discipline"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Priest"], LBIS.L["Discipline"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Priest"], LBIS.L["Discipline"], "4")
