local spec0 = LBIS:RegisterSpec(LBIS.L["Shaman"], LBIS.L["Enhancement"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Shaman"], LBIS.L["Enhancement"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Shaman"], LBIS.L["Enhancement"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Shaman"], LBIS.L["Enhancement"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Shaman"], LBIS.L["Enhancement"], "4")
