local spec0 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Affliction"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Affliction"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Affliction"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Affliction"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Affliction"], "4")
