local spec0 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Destruction"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Destruction"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Destruction"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Destruction"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Warlock"], LBIS.L["Destruction"], "4")
