local spec0 = LBIS:RegisterSpec(LBIS.L["Warrior"], LBIS.L["Arms"], "0")
local spec1 = LBIS:RegisterSpec(LBIS.L["Warrior"], LBIS.L["Arms"], "1")
local spec2 = LBIS:RegisterSpec(LBIS.L["Warrior"], LBIS.L["Arms"], "2")
local spec3 = LBIS:RegisterSpec(LBIS.L["Warrior"], LBIS.L["Arms"], "3")
local spec4 = LBIS:RegisterSpec(LBIS.L["Warrior"], LBIS.L["Arms"], "4")
