local spec = LoonBestInSlot:RegisterSpec("Druid", "Cat")
LoonBestInSlot:AddItem(spec, "8345", "Head", "Wolfshead Helm",                      "BIS", "1>3", "Profession", "Leatherworking (225)")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",          "Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "33672", "Head", "Vengeful Gladiator's Dragonhide Helm","Alt", "3", "PvP", "1875  Arena Points")

LoonBestInSlot:AddItem(spec, "31048", "Shoulders", "Thunderheart Pauldrons",            "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "33674", "Shoulders", "Vengeful Gladiator's Dragonhide Spaulders", "Alt", "3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",      "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30230", "Shoulders", "Nordrassil Feral-Mantle",           "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne",                 "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",  "Alt", "1>3", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt", "1",  "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",          "Alt", "1",  "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets",       "PreRaid", "0",  "Quest", "Fel Embers", "Magus Zabraxis, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde",               "PreRaid", "0",  "Drop", "Epoch Hunter", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "27776", "Shoulders", "Shoulderpads of Assassination",     "PreRaid", "0",  "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "27995", "Shoulders", "Sun-Gilded Shouldercaps",           "PreRaid", "0",  "Drop", "Chrono Lord Deja", "The Black Morass")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape",       "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",             "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",          "Alt", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak",            "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap",                     "Alt", "1>2",  "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak",             "Alt", "1",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "31255", "Back", "Cloak of the Craft",                 "PreRaid", "0",  "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud",              "PreRaid", "0",  "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28031", "Back", "Nomad's Woven Cloak",                "PreRaid", "0",  "Quest", "Bring Me The Egg!", "Wazat, Nagrand")
LoonBestInSlot:AddItem(spec, "28032", "Back", "Delicate Green Poncho",              "PreRaid", "0",  "Quest", "Bring Me The Egg!", "Wazat, Nagrand")
LoonBestInSlot:AddItem(spec, "28249", "Back", "Capacitus' Cloak of Calibration",    "PreRaid", "0",  "Drop", "Cache of the Legion", "The Mechanar")

LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic",                   "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "31042", "Chest", "Thunderheart Chestguard",               "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard",                   "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33675", "Chest", "Vengeful Gladiator's Dragonhide Tunic", "Alt", "3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest",               "Alt", "2", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30222", "Chest", "Nordrassil Chestplate",                 "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne",                "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender",     "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic",                     "Alt", "1>2",  "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28601", "Chest", "Chestguard of the Conniver",            "Alt", "1>2",  "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28204", "Chest", "Tunic of Assassination",                "PreRaid", "0",  "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "24396", "Chest", "Vest of Vengeance",                     "PreRaid", "0",  "Drop", "Keli'dan the Breaker", "The Blood Furnace")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest",                     "PreRaid", "0",  "Profession", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28264", "Chest", "Wastewalker Tunic",                     "PreRaid", "0",  "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "27461", "Chest", "Chestguard of the Prowler",             "PreRaid", "0",  "Drop", "Vazruden the Herald", "Hellfire Ramparts (Heroic)")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands",                 "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "33881", "Bracers", "Vindicator's Dragonhide Bracers", "BIS", "3", "PvP", "11794 Honor Points, 20 Warsong Gulch Marks")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs",                    "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers",             "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending",             "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers",             "Alt", "2", "Reputation", "Ogri'la (Exalted)", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards",           "Alt", "1>2", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards",       "Alt", "1>2", "Quest", "The Soul Devices", "Spy To'gun, Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28988", "Bracers", "Marshal's Leather Bracers",       "PreRaid", "0", "PvP", "5897 Honor Points", "20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "28424", "Bracers", "General's Leather Bracers",       "PreRaid", "0", "PvP", "5897 Honor Points", "20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers",            "PreRaid", "0", "Drop", "Elemental Leatherworking (375)")

LoonBestInSlot:AddItem(spec, "31034", "Gloves", "Thunderheart Gauntlets",           "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",       "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30223", "Gloves", "Nordrassil Handgrips",             "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt", "1>3", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",                "Alt", "1>2",  "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28396", "Gloves", "Gloves of the Unbound",            "PreRaid", "0",  "Drop", "Wrath-Scryer Soccothrates and Zereketh the Unbound", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves",               "PreRaid", "0",  "Profession", "Leatherworking (340)")
LoonBestInSlot:AddItem(spec, "27509", "Gloves", "Handgrips of Assassination",       "PreRaid", "0",  "Drop", "Aeonus and Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "29507", "Gloves", "Windslayer Wraps",                 "PreRaid", "0",  "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "27531", "Gloves", "Wastewalker Gloves",               "PreRaid", "0",  "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths",         "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt",         "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32265", "Belt", "Shadow-walker's Cord",               "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "33879", "Belt", "Vindicator's Dragonhide Belt",       "Alt", "3", "PvP", "17850 Honor Points, 40 Arathi Basin Marks")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow",                "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer",          "Alt", "1>3", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "30042", "Belt", "Belt of Natural Power",              "Alt", "2", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",              "Alt Hit", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery",                "Alt Hit", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30372", "Belt", "Socrethar's Girdle",                 "PreRaid", "0",  "Quest", "Turning Point", "Voren'thal the Seer, Shattrath City")
LoonBestInSlot:AddItem(spec, "31464", "Belt", "Naaru Belt of Precision",            "PreRaid", "0",  "Quest", "How to Break Into the Arcatraz", "A'dal, Shattrath City")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash",                      "PreRaid", "0",  "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "27911", "Belt", "Epoch's Whispering Cinch",           "PreRaid", "0",  "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "31044", "Legs", "Thunderheart Leggings",              "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons",          "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves",                  "Alt", "1>3", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent",       "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30229", "Legs", "Nordrassil Feral-Kilt",              "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings",            "PreRaid", "0",  "Quest", "Showdown - Baron Sablemane/Showdown", "Rexxar, Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings",               "PreRaid", "0",  "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings",               "PreRaid", "0",  "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards",                 "PreRaid", "0",  "Drop", "Quagmirran", "Heroic The Slave Pens")
LoonBestInSlot:AddItem(spec, "30535", "Legs", "Forestwalker Kilt",                  "PreRaid", "0",  "Drop", "Nexus-Prince Shaffar", "Heroic Mana-Tombs")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots",               "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "33880", "Feet", "Vindicator's Dragonhide Boots",      "Alt", "3", "PvP", "17850 Honor Points, 40 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",               "Alt", "1>3", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness",            "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30041", "Feet", "Boots of Natural Grace",             "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots",                  "PreRaid", "0",  "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "31288", "Feet", "The Master's Treads",                "PreRaid", "0",  "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders",                "PreRaid", "0",  "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "30939", "Feet", "Felboar Hide Shoes",                 "PreRaid", "0",  "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Borak, Son of Oronok, Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28987", "Feet", "Marshal's Leather Boots",            "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "28422", "Feet", "General's Leather Boots",            "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Eye of the Storm Mark")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares",       "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades",          "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                     "BIS", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem",      "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain",             "Alt", "1>3", "Profession", "Jewelcrafting (360)")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",               "Alt", "1>2",  "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",              "Alt", "1>2",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism",           "Alt", "1",  "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies",               "PreRaid", "0",  "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain",                  "PreRaid", "0",  "Reputation", "The Consortium Exalted", "Paulsta'ats / Karaaz")
LoonBestInSlot:AddItem(spec, "27779", "Neck", "Bone Chain Necklace",                "PreRaid", "0",  "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing",             "PreRaid", "0",  "Quest", "Gurok the Usurper", "Gordawg, Nagrand")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion",       "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring",       "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality",                  "Alt Hit", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General",         "Alt Hit", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest",         "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",              "Alt", "1>3", "Reputation", "Nakodu", "Lower City Exalted")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",               "Alt Hit", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",                 "Alt Hit", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant",           "Alt Hit", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",           "Alt", "1",  "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity",                "Alt", "1",  "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt", "1",   "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet",                  "PreRaid", "0",  "Quest", "Shutting Down Manaforge Ara", "Anchorite Karja, Netherstorm (Aldor)")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band",                     "PreRaid", "0",  "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet",                   "PreRaid", "0",  "Quest", "Deathblow to the Legion", "Ishanah, Shattrath City")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption",    "PreRaid", "0",  "Quest", "Dissension Amongst the Ranks...", "Thane Yoregar / Overlord Or'barokh, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",         "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",                "BIS", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew",           "Alt", "3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",                "Alt", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",              "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller",     "Alt", "1>2",  "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage",      "PreRaid", "0",  "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos",                "PreRaid", "0",  "Quest", "Ar'kelos the Guardian")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",          "PreRaid", "0",  "Drop", "Pathaleon the Calculator", "The Mechanar")

LoonBestInSlot:AddItem(spec, "33716", "2H", "Vengeful Gladiator's Staff",           "BIS", "3", "PvP", "3750 Arena Points")
LoonBestInSlot:AddItem(spec, "30883", "2H", "Pillar of Ferocity",                   "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "28658", "2H", "Terestian's Stranglestaff",            "Alt", "1>3", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "32014", "2H", "Merciless Gladiator's Maul",           "Alt", "1>3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "30021", "2H", "Wildfury Greatstaff",                  "Alt", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "31334", "2H", "Staff of Natural Fury",                "PreRaid", "0",  "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29359", "2H", "Feral Staff of Lashing",               "PreRaid", "0",  "Drop", "Warp Splinter", "The Botanica (Heroic)")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden",                          "PreRaid", "0",  "Reputation", "Cenarion Expidition (Exalted)", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "27877", "2H", "Draenic Wildstaff",                    "PreRaid", "0",  "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28325", "2H", "Dreamer's Dragonstaff",                "PreRaid", "0",  "Drop", "Thorngrin the Tender", "The Botanica")
LoonBestInSlot:AddItem(spec, "30010", "2H", "Fleshling Simulation Staff",           "PreRaid", "0",  "Quest", "Nexus-King Salhadaar")
LoonBestInSlot:AddItem(spec, "28948", "2H", "Grand Marshal's Maul",                 "PreRaid", "0",  "PvP", "9563 Honor Points, 20 Alterac Valley Mark")
LoonBestInSlot:AddItem(spec, "28919", "2H", "High Warlord's Maul",                  "PreRaid", "0",  "PvP", "9563 Honor Points, 20 Alterac Valley Mark")

LoonBestInSlot:AddItem(spec, "29390", "Idols", "Everbloom Idol",                    "Alt", "1>3", "Dungeon Token", "15 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess",          "Alt", "2>3", "Quest", "Vanquish the Raven God", "Swift Flight Questline")
LoonBestInSlot:AddItem(spec, "32257", "Idol", "Idol of the White Stag",             "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "28372", "Idols", "Idol of Feral Shadows",             "PreRaid", "0",  "Drop", "Zereketh the Unbound", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28064", "Idols", "Idol of the Wild",                  "PreRaid", "0",  "Quest", "Colossal Menace", "Hellfire Peninsula")