local spec = LoonBestInSlot:RegisterSpec("Druid", "Bear")

LoonBestInSlot:AddItem(spec, "31039", "Head", "Thunderheart Cover",                 "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher",   "BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33672", "Head", "Vengeful Gladiator's Dragonhide Helm", "Alt", "3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",          "Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30228", "Head", "Nordrassil Headdress",               "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender",    "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32478", "Head", "Deathblow X11 Goggles",              "Alt", "2>3", "Profession", "Engineering (360)")
LoonBestInSlot:AddItem(spec, "29098", "Head", "Stag-Helm of Malorne",               "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",        "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28796", "Head", "Malefic Mask of the Shadows",        "Alt Thrt", "1", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28732", "Head", "Cowl of Defiance",                   "Alt Thrt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw",                   "PreRaid", "0",  "Quest", "The Warlord's Hideout", "Watcher Jhang, Zangarmarsh")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver",               "PreRaid", "0",  "Dungeon Token", "50 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "32088", "Head", "Cowl of Beastly Rage",               "PreRaid", "0",  "Dungeon Token", "50 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "29502", "Head", "Cobrascale Hood",                    "PreRaid", "0",  "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm",                   "PreRaid", "0",  "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "31109", "Head", "Stealther's Helmet of Second Sight", "PreRaid", "0",  "Quest", "Teron Gorefiend, I am...", "Ancient Shadowmoon Spirit, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "31048", "Shoulders", "Thunderheart Pauldrons",                "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "33674", "Shoulders", "Vengeful Gladiator's Dragonhide Spaulders", "Alt", "3", "PvP", "1500 Arena Points")
LoonBestInSlot:AddItem(spec, "30917", "Shoulders", "Razorfury Mantle",                      "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30230", "Shoulders", "Nordrassil Feral-Mantle",               "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender",  "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",          "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29100", "Shoulders", "Mantle of Malorne",                     "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",      "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless",  "Alt", "1>2",  "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde",                   "PreRaid", "0",  "Drop", "Epoch Hunter", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "27776", "Shoulders", "Shoulderpads of Assassination",         "PreRaid", "0",  "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "32080", "Shoulders", "Mantle of Shadowy Embrace",             "PreRaid", "0",  "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",              "PreRaid", "0",  "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28622", "Shoulders", "Grand Marshal's Dragonhide Spaulders",  "PreRaid", "0",  "PvP", "3156 Honor Points, 10 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "28814", "Shoulders", "High Warlord's Dragonhide Spaulders",   "PreRaid", "0",  "PvP", "3156 Honor Points, 10 Arathi Basin Mark")

LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak",       "BIS Mit", "1>3", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",     "BIS Thrt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "Alt Thrt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification", "Alt Mit", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "24258", "Back", "Resolute Cape",              "Alt Mit", "1>2",  "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak",    "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",  "Alt Thrt", "1>2",  "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker",   "Alt", "1",  "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28256", "Back", "Thoriumweave Cloak",         "PreRaid", "0",  "Drop", "Mechano-Lord Capacitus", "The Mechanar")
LoonBestInSlot:AddItem(spec, "29385", "Back", "Farstrider Defender's Cloak", "PreRaid", "0",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak",     "PreRaid", "0",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "24379", "Back", "Bogstrok Scale Cloak",       "PreRaid", "0",  "Drop", "Rokmar the Crackler", "The Slave Pens")
LoonBestInSlot:AddItem(spec, "28377", "Back", "Sergeant's Heavy Cloak",     "PreRaid", "0",  "PvP", "2949 Honor Points, 10 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "29777", "Back", "Cloak of the Valiant Defender", "PreRaid", "0",  "Quest", "Ar'kelos the Guardian")

LoonBestInSlot:AddItem(spec, "31042", "Chest", "Thunderheart Chestguard",           "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "33675", "Chest", "Vengeful Gladiator's Dragonhide Tunic", "Alt Thrt", "3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic",               "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard",               "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30222", "Chest", "Nordrassil Chestplate",             "Alt Mit", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt Mit", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest",           "Alt", "2", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29096", "Chest", "Breastplate of Malorne",            "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest",                 "Alt", "1>2",  "Profession", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28601", "Chest", "Chestguard of the Conniver",        "Alt", "1",  "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "25689", "Chest", "Heavy Clefthoof Vest",              "PreRaid", "0",  "Profession", "Leatherworking (360)")
LoonBestInSlot:AddItem(spec, "28264", "Chest", "Wastewalker Tunic",                 "PreRaid", "0",  "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands",                 "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "33881", "Bracers", "Vindicator's Dragonhide Bracers", "BIS Mit", "3", "PvP", "11794 Honor Points, 20 Warsong Gulch Marks")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers",             "Alt", "3", "Profession", "Leatherworking (375)", "")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs",                    "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending",             "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29263", "Bracers", "Forestheart Bracers",             "Alt", "1>2", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls (Heroic)")
LoonBestInSlot:AddItem(spec, "28514", "Bracers", "Bracers of Maliciousness",        "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28978", "Bracers", "Marshal's Dragonhide Bracers",    "Alt", "1", "PvP", "5897 Honor Points, 20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "28445", "Bracers", "General's Dragonhide Bracers",    "Alt", "1", "PvP", "5897 Honor Points, 20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "30944", "Bracers", "Umberhowl's Collar",              "PreRaid", "0",  "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Borak, Son of Oronok, Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28988", "Bracers", "Marshal's Leather Bracers",       "PreRaid", "0",  "PvP", "5897 Honor Points", "20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "28424", "Bracers", "General's Leather Bracers",       "PreRaid", "0",  "PvP", "5897 Honor Points", "20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards",           "PreRaid", "0",  "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers",            "PreRaid", "0",  "Drop", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards",       "PreRaid", "0",  "Quest", "The Soul Devices", "Spy To'gun, Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "31034", "Gloves", "Thunderheart Gauntlets",           "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33671", "Gloves", "Vengeful Gladiator's Dragonhide Gloves", "Alt Thrt", "3", "PvP", "1125 Arena Points")
LoonBestInSlot:AddItem(spec, "30223", "Gloves", "Nordrassil Handgrips",             "Alt Mit", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt Mit", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",       "Alt Thrt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29097", "Gloves", "Gauntlets of Malorne",             "Alt Mit", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender",    "Alt Mit", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",                "Alt Thrt", "1", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt", "1",  "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28776", "Gloves", "Liar's Tongue Gloves",             "Alt", "1",  "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30943", "Gloves", "Verdant Gloves",                   "PreRaid", "0",  "Quest", "Akama's Promise", "Akama, Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29507", "Gloves", "Windslayer Wraps",                 "PreRaid", "0",  "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "29503", "Gloves", "Cobrascale Gloves",                "PreRaid", "0",  "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "27531", "Gloves", "Wastewalker Gloves",               "PreRaid", "0",  "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets",        "PreRaid", "0",  "Quest", "The Flesh Lies...", "Agent Araxes, Netherstorm")
LoonBestInSlot:AddItem(spec, "28396", "Gloves", "Gloves of the Unbound",            "PreRaid", "0",  "Drop", "Wrath-Scryer Soccothrates and Zereketh the Unbound", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths",         "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt",         "Alt Thrt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33879", "Belt", "Vindicator's Dragonhide Belt",       "Alt", "3", "PvP", "17850 Honor Points, 40 Arathi Basin Marks")
LoonBestInSlot:AddItem(spec, "30042", "Belt", "Belt of Natural Power",              "Alt Mit", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow",                "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29264", "Belt", "Tree-Mender's Belt",                 "Alt", "1>2", "Drop", "Reinforced Fel Iron Chest", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",              "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery",                "Alt", "1",  "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28986", "Belt", "Marshal's Leather Belt",             "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "28423", "Belt", "General's Leather Belt",             "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer",          "PreRaid", "0",  "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "28976", "Belt", "Marshal's Dragonhide Belt",          "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "28443", "Belt", "General's Dragonhide Belt",          "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "30942", "Belt", "Manimal's Cinch",                    "PreRaid", "0",  "Quest", "Enraged Spirits of Air", "Earthmender Torlok, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "31044", "Legs", "Thunderheart Leggings",              "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons",          "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30229", "Legs", "Nordrassil Feral-Kilt",              "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent",       "Alt Thrt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29099", "Legs", "Greaves of Malorne",                 "Alt Thrt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29767", "Legs", "Leggings of the Fallen Defender",    "Alt Thrt", "1>2", "Token", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves",                  "Alt", "1",  "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "25690", "Legs", "Heavy Clefthoof Leggings",           "PreRaid", "0",  "Profession", "Leatherworking (355)")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings",            "PreRaid", "0",  "Quest", "Showdown - Baron Sablemane/Showdown", "Rexxar, Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "30535", "Legs", "Forestwalker Kilt",                  "PreRaid", "0",  "Drop", "Nexus-Prince Shaffar", "Heroic Mana-Tombs")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards",                 "PreRaid", "0",  "Drop", "Quagmirran", "Heroic The Slave Pens")
LoonBestInSlot:AddItem(spec, "30941", "Legs", "Ash Tempered Legguards",             "PreRaid", "0",  "Quest", "Thwart the Dark Conclave", "Parshah, Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings",                 "PreRaid", "0",  "Quest", "Special Delivery to Shattrath City", "Image of Nexus-Prince Haramad, Netherstorm")

LoonBestInSlot:AddItem(spec, "32593", "Feet", "Treads of the Den Mother",           "BIS Mit", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots",               "BIS Thrt", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "33880", "Feet", "Vindicator's Dragonhide Boots",      "Alt", "3", "PvP", "17850 Honor Points, 40  Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "30041", "Feet", "Boots of Natural Grace",             "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking",       "Alt Thrt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30674", "Feet", "Zierhut's Lost Treads",              "Alt Mit", "1>2", "Drop", "Zone Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",               "Alt Thrt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "25691", "Feet", "Heavy Clefthoof Boots",              "PreRaid", "0",  "Profession", "Leatherworking (355)")
LoonBestInSlot:AddItem(spec, "28339", "Feet", "Boots of the Shifting Sands",        "PreRaid", "0",  "Drop", "Laj", "The Botanica")
LoonBestInSlot:AddItem(spec, "29265", "Feet", "Barkchip Boots",                     "PreRaid", "0",  "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "28987", "Feet", "Marshal's Leather Boots",            "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "28422", "Feet", "General's Leather Boots",            "PreRaid", "0",  "PvP", "8925 Honor Points, 40 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders",                "PreRaid", "0",  "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "31532", "Feet", "Supple Leather Boots",               "PreRaid", "0",  "Quest", "Whispers of the Raven God", "Timeon, Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                     "BIS", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem",      "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans",                  "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",               "Alt", "1>3", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman",                 "Alt", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",              "Alt", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism",           "Alt", "1>2",  "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut",         "Alt", "1",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "29815", "Neck", "Chain of Glowing Tendrils",          "PreRaid", "0",  "Quest", "Hitting the Motherlode", "Zuben Elgenubi, Netherstorm")
LoonBestInSlot:AddItem(spec, "28168", "Neck", "Insignia of the Mag'hari Hero",      "PreRaid", "0",  "Quest", "Hero of the Mag'har", "Greatmother Geyah, Nagrand (Horde)")
LoonBestInSlot:AddItem(spec, "28244", "Neck", "Pendant of Triumph",                 "PreRaid", "0",  "PvP", "7650 Honor Points, 10 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "27779", "Neck", "Bone Chain Necklace",                "PreRaid", "0",  "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "28343", "Neck", "Jagged Bark Pendant",                "PreRaid", "0",  "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "31727", "Neck", "Choker of Bloodied Feathers",        "PreRaid", "0",  "Quest", "The Skettis Offensive", "Defender Grashna, Shattrath City")

LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "BIS Mit", "1>3",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "32266", "Neck", "Ring of Deceitful Intent",           "BIS", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion",       "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32497", "Neck", "Stormrage Signet Ring",              "Alt Thrt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29300", "Neck", "Band of Eternity",                   "Alt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Revered)")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",              "Alt Thrt", "1>3", "Reputation", "Nakodu", "Lower City Exalted")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",                 "Alt Mit", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense",          "Alt Mit", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality",                  "Alt Thrt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "33054", "Ring", "The Seal of Danzalar",               "Alt Mit", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General",         "Alt Thrt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest",         "Alt Thrt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",               "Alt Thrt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring",               "Alt Mit", "1", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",           "Alt Thrt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "27436", "Ring", "Iron Band of the Unbreakable",       "PreRaid", "0",  "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "29177", "Ring", "A'dal's Command",                    "PreRaid", "0",  "Reputation", "The Sha'tar Exalted", "Almaador, Shattrath City")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force",           "PreRaid", "0",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28211", "Ring", "Lieutenant's Signet of Lordaeron",   "PreRaid", "0",  "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords",            "PreRaid", "0",  "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "29128", "Ring", "Lightwarden's Band",                 "PreRaid", "0",  "Reputation", "The Aldor (Revered)", "Quartermaster Endarin, Shattrath City")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band",                     "PreRaid", "0",  "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia",             "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",                "BIS Thrt", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "34578", "Trinket", "Battlemaster's Determination",    "BIS Mit", "3", "PvP", "30,000 Honor Points, 40 Alterac Valley Marks")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew",           "BIS Thrt", "3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",         "BIS Thrt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "34576", "Trinket", "Battlemaster's Cruelty",          "Alt Mit", "3", "PvP", "30,000 Honor Points, 40 Alterac Valley Marks")
LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance",        "Alt", "3", "Quest", "Darkmoon Furies Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "32658", "Trinket", "Badge of Tenacity",               "Alt Thrt", "2", "Quest", "Apexis Crystal Infusion", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",              "Alt Thrt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",                "Alt Thrt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher",          "Alt Surv", "1>2", "Profession", "Engineering (360)")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer",             "Alt Surv", "1>2", "Profession", "Engineering (360)")
LoonBestInSlot:AddItem(spec, "13503", "Trinket", "Alchemist's Stone",               "Alt", "1>2",  "Profession", "Alchemy (350)")
LoonBestInSlot:AddItem(spec, "29181", "Trinket", "Timelapse Shard",                 "Alt", "1>2",  "Reputation", "Keepers of Time (Exalted)", "Alurmi, Tanaris")
LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch",      "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller",     "PreRaid", "0",  "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",          "PreRaid", "0",  "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "27770", "Trinket", "Argussian Compass",               "PreRaid", "0",  "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "13966", "Trinket", "Mark of Tyranny",                 "PreRaid", "0",  "Quest", "General Drakkisath's Demise - Marshal Maxwell/For The Horde!", "Thrall")

LoonBestInSlot:AddItem(spec, "30883", "2H", "Pillar of Ferocity",           "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33716", "2H", "Vengeful Gladiator's Staff",   "Alt", "3", "PvP", "3750 Arena Points")
LoonBestInSlot:AddItem(spec, "30021", "2H", "Wildfury Greatstaff",          "Alt", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28658", "2H", "Terestian's Stranglestaff",    "Alt", "1>3", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29171", "2H", "Earthwarden",                  "Alt Mit", "1>2", "Reputation", "Cenarion Expidition (Exalted)", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "29359", "2H", "Feral Staff of Lashing",       "PreRaid", "0",  "Drop", "Warp Splinter", "The Botanica (Heroic)")
LoonBestInSlot:AddItem(spec, "31334", "2H", "Staff of Natural Fury",        "PreRaid", "0",  "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27757", "2H", "Greatstaff of the Leviathan",  "PreRaid", "0",  "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "27877", "2H", "Draenic Wildstaff",            "PreRaid", "0",  "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28948", "2H", "Grand Marshal's Maul",         "PreRaid", "0",  "PvP", "9563 Honor Points, 20 Alterac Valley Mark")
LoonBestInSlot:AddItem(spec, "28919", "2H", "High Warlord's Maul",          "PreRaid", "0",  "PvP", "9563 Honor Points, 20 Alterac Valley Mark")
LoonBestInSlot:AddItem(spec, "30010", "2H", "Fleshling Simulation Staff",   "PreRaid", "0",  "Quest", "Nexus-King Salhadaar")
LoonBestInSlot:AddItem(spec, "28325", "2H", "Dreamer's Dragonstaff",        "PreRaid", "0",  "Drop", "Thorngrin the Tender", "The Botanica")

LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess",  "BIS", "2>3", "Quest", "Vanquish the Raven God", "Swift Flight Questline")
LoonBestInSlot:AddItem(spec, "32257", "Idol", "Idol of the White Stag",     "BIS Thrt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "23198", "Idol", "Idol of Brutality",          "Alt", "1>3", "Drop", "Magistrate Barthilas", "Stratholme")
LoonBestInSlot:AddItem(spec, "28064", "Idol", "Idol of the Wild",           "Alt", "1>3", "Quest", "Colossal Menace", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27744", "Idol", "Idol of Ursoc",              "PreRaid", "0",  "Drop", "Hungarfen", "The Underbog (Heroic)")