local spec = LoonBestInSlot:RegisterSpec("Mage", "")

LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30206", "Head", "Cowl of Tirisfal",               "BIS Arc", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero",    "BIS Arc", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "31056", "Head", "Cowl of the Tempest",            "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood",               "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer",     "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29076", "Head", "Collar of the Aldor",            "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29759", "Head", "Helm of the Fallen Hero",        "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28744", "Head", "Uni-Mind Headdress",             "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion",               "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl",                "PreRaid", "0", "Drop", "Pathaleon the Calculator", "Mechanar")
LoonBestInSlot:AddItem(spec, "28193", "Head", "Mana-Etched Crown",              "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "PreRaid", "0", "Quest", " Teron Gorefiend, I am...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30515", "Head", "Junior Technician 3rd Grade Goggles", "PreRaid", "0", "Quest", "You're Hired!", "Netherstorm")

LoonBestInSlot:AddItem(spec, "30210", "Shoulders", "Mantle of Tirisfal",                    "BIS Arc", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero",      "BIS Arc", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "31059", "Shoulders", "Mantle of the Tempest",                 "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought",              "Alt", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle",                       "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads",             "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings",             "Alt", "2>3", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30079", "Shoulders", "Illidari Shoulderpads",                 "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29079", "Shoulders", "Pauldrons of the Aldor",                "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29762", "Shoulders", "Pauldrons of the Fallen Hero",          "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart",           "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", "Spaulders of Oblivion",                 "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders",                 "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors",               "PreRaid", "0", "Drop", "Chrono Lord Deja", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28075", "Shoulders", "Destroyers' Mantle",                    "PreRaid", "0", "Quest", "Natural Remedies", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "30514", "Shoulders", "Nether Guards",                         "PreRaid", "0", "Quest", "Dr. Boom!", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",            "BIS Arc", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council",      "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant",        "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi",       "Alt Arc", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran",            "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "31140", "Back", "Cloak of Entropy",                   "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "24252", "Back", "Cloak of the Black Void",            "PreRaid", "0", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities",    "PreRaid", "0", "Heroics", "G'eras", "25 Badges of Justice ")
LoonBestInSlot:AddItem(spec, "29813", "Back", "Cloak of Woven Energy",              "PreRaid", "0", "Quest", "Hitting the Motherlode", "Netherstorm")
LoonBestInSlot:AddItem(spec, "25777", "Back", "Ogre Slayer's Cover",                "PreRaid", "0", "Quest", "Cho'war the Pillager", "Nagrand")

LoonBestInSlot:AddItem(spec, "31057", "Chest", "Robes of the Tempest",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30196", "Chest", "Robes of Tirisfal",                 "BIS Arc", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "BIS Arc", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin",                   "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch",        "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes",            "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe",                    "Alt", "1>3", "Profession", "Spellfire Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29077", "Chest", "Vestments of the Aldor",            "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29755", "Chest", "Chestguard of the Fallen Hero",     "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28602", "Chest", "Robe of the Elder Scribes",         "Alt", "1", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order",         "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe",         "PreRaid", "0", "Quest", "Everything Will Be Alright", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "28342", "Chest", "Warp Infused Drape",                "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd",            "PreRaid", "0", "Drop", "World Drop")
LoonBestInSlot:AddItem(spec, "28232", "Chest", "Robe of Oblivion",                  "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29780", "Chest", "Kirin Tor Apprentice's Robes",      "PreRaid", "0", "Quest", "Destroy Naberius!", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31717", "Chest", "Shadowcast Tunic",                  "PreRaid", "0", "Quest", "Drill the Drillmaster/The Foot of the Citadel", "Hellfire Peninsula")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought",       "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation",            "BIS Arc", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings",           "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands",            "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok",                "Alt", "1", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds",        "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28477", "Bracers", "Harbinger Bands",                 "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom",        "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps",                 "PreRaid", "0", "Quest", "The Soul Devices", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27746", "Bracers", "Arcanium Signet Bands",           "PreRaid", "0", "Drop", "Hungarfen", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "29240", "Bracers", "Bands of Negation",               "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "30927", "Bracers", "Earthmender's Bracer of Shattering", "PreRaid", "0", "Quest", "Escape from Coilskar Cistern", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30520", "Bracers", "Gold-Trimmed Cuffs",              "PreRaid", "0", "Quest", "Success!", "Netherstorm")

LoonBestInSlot:AddItem(spec, "31055", "Gloves", "Gloves of the Tempest",            "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30205", "Gloves", "Gloves of Tirisfal",               "BIS Arc", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero",    "BIS Arc", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King",        "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves",                 "Alt Fire", "1>2", "Profession", "Spellfire Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought",     "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves",               "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29080", "Gloves", "Gloves of the Aldor",              "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29756", "Gloves", "Gloves of the Fallen Hero",        "Alt", "1", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps",           "Alt", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "27493", "Gloves", "Gloves of the Deadwatcher",        "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27537", "Gloves", "Gloves of Oblivion",               "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", "Tempest's Touch",                  "PreRaid", "0", "Quest", "Return to Andormu", "Caverns of Time")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves",               "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts")
LoonBestInSlot:AddItem(spec, "30924", "Gloves", "Gloves of the High Magus",         "PreRaid", "0", "Quest", "News of Victory / News of Victory", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30930", "Gloves", "Grips of the Void",                "PreRaid", "0", "Quest", "Enraged Spirits of Air", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity",          "BIS Arc", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose",              "BIS Arc", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting",               "BIS", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors",      "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt",                 "Alt", "1>3", "Profession", "Spellfire Tailoring (355)")
LoonBestInSlot:AddItem(spec, "30673", "Belt", "Inferno Waist Cord",             "Alt", "1>2", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination",            "Alt", "1>2", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration",     "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28654", "Belt", "Malefic Girdle",                 "Alt", "1>2", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity",              "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift",                   "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "27795", "Belt", "Sash of Serpentra",              "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "30923", "Belt", "Grom'tor's Bloodied Bandage",    "PreRaid", "0", "Quest", "The Cipher of Damnation - The First Fragment Recovered", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29771", "Belt", "Kirin'Var Journeyman's Belt",    "PreRaid", "0", "Quest", "The Sigil of Krasus", "Netherstorm")

LoonBestInSlot:AddItem(spec, "31058", "Legs", "Leggings of the Tempest",            "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher","BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation",            "Alt", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements",     "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30207", "Legs", "Leggings of Tirisfal",               "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero",    "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants",                  "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle",     "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer",        "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29078", "Legs", "Legwraps of the Aldor",              "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29765", "Legs", "Leggings of the Fallen Hero",        "Alt", "1", "Token", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers",                "Alt", "1", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist",          "PreRaid", "0", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration",       "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers",        "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "28338", "Legs", "Devil-Stitched Leggings",            "PreRaid", "0", "Drop", "Laj", "The Botanica")
LoonBestInSlot:AddItem(spec, "30929", "Legs", "Soothsayer's Kilt",                  "PreRaid", "0", "Quest", "Blast the Infernals!", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "21852", "Legs", "Netherweave Pants",                  "PreRaid", "0", "Profession", "Tailoring (325)")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller",      "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes",               "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting",              "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian",   "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots",        "Alt Frost", "1>2", "Profession", "Shadowweave Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers",                  "Alt", "1", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling",           "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice",    "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots",              "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers",              "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29242", "Feet", "Boots of Blasphemy",             "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "30519", "Feet", "Boots of the Nexus Warden",      "PreRaid", "0", "Quest", "The Flesh Lies...", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30398", "Feet", "Boots of the Beneficent",        "PreRaid", "0", "Quest", "Building a Perimeter", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32589", "Neck", "Hellfire-Encased Pendant",       "BIS Fire", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "BIS Frost", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "BIS Arc", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman",        "BIS Arc", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30008", "Neck", "Pendant of the Lost Ages",       "Alt Arc", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury",    "Alt", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls",      "Alt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt", "1", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "31338", "Neck", "Charlotte's Ivy",                "Alt", "1", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace",            "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "18814", "Neck", "Choker of the Fire Lord",        "PreRaid", "0", "Drop", "Ragnaros", "Molten Core")
LoonBestInSlot:AddItem(spec, "29368", "Neck", "Manasurge Pendant",              "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace",       "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "31178", "Neck", "Amulet of Unstable Power",       "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge",      "BIS Arc", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms",        "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage",       "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils",          "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence",             "Alt", "1>3", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury",           "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift",                  "Alt", "1>3", "Reputation", "Cenarion Expedition Exalted", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar",                  "Alt", "2", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage",  "Alt", "1>2", "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "28510", "Ring", "Spectral Band of Innervation",   "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring",         "Alt", "1", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist",           "Alt", "1", "Dungeons", "50 Spirit Shard", "Spirit Sage Gartok and Spirit Sage Zran")
LoonBestInSlot:AddItem(spec, "31339", "Ring", "Lola's Eve",                     "Alt", "1", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet",                  "PreRaid", "0", "Reputation", "The Scryers Exalted", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa",        "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "31075", "Ring", "Evoker's Mark of the Redemption", "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30366", "Ring", "Manastorm Band",                 "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara", "Netherstorm")
LoonBestInSlot:AddItem(spec, "32774", "Ring", "The Black Pearl",                "PreRaid", "0", "Profession", "Jewelcrafting (330)")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan",        "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",      "BIS", "3", "Quest", "Darkmoon Blessings Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "30720", "Trinket", "Serpent-Coil Braid",          "BIS Arc", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32488", "Trinket", "Ashtongue Talisman of Insight", "Alt", "3", "Reputation", "Ashtongue Deathsworn (Exalted)", "Okuno")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt Fire", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt", "1>3", "Dungeon Token", "41 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye",            "Alt", "1>2", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem",           "Alt", "1>2", "Reputation", "The Scryers Revered", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "28418", "Trinket", "Shiffar's Nexus-Horn",        "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift",                "PreRaid", "0", "Reputation", "Almaador", "The Sha'tar Revered, Shattrath City")
LoonBestInSlot:AddItem(spec, "28040", "Trinket", "Vengeance of the Illidari",   "PreRaid", "0", "Quest", "Overlord /  Cruel's Intentions", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "25620", "Trinket", "Ancient Crystal Talisman",    "PreRaid", "0", "Quest", "A Spirit Ally?", "Zangarmarsh")
LoonBestInSlot:AddItem(spec, "25619", "Trinket", "Glowing Crystal Insignia",    "PreRaid", "0", "Quest", "Overlord Gorefist", "Zangarmarsh")

LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos",             "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury",         "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan",        "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest",         "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade",         "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade",          "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade",         "PreRaid", "0", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage",        "PreRaid", "0", "Reputation", "Honor Hold Exalted", "Logistics Officer Ulrike, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller",                  "PreRaid", "0", "Reputation", "Thrallmar Exalted", "Quartermaster Urgronn, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry",            "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams",  "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27543", "MH", "Starlight Dagger",             "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade",              "PreRaid", "0", "Drop", "Alurmi", "Keepers of Time Revered, Tanaris")
LoonBestInSlot:AddItem(spec, "24453", "MH", "Zangartooth Shortblade",       "PreRaid", "0", "Drop", "Swamplord Musel'ek", "The Underbog")
LoonBestInSlot:AddItem(spec, "31142", "MH", "Blade of Trapped Knowledge",   "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key",                        "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries",          "Alt", "1>3", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff",                 "Alt", "1>3", "Drop", "Talon King Ikiss", "Sethekk Halls (Heroic)")
LoonBestInSlot:AddItem(spec, "29130", "2H", "Auchenai Staff",                       "PreRaid", "0", "Reputation", "The Aldor Revered", "Quartermaster Endarin")
LoonBestInSlot:AddItem(spec, "28341", "2H", "Warpstaff of Arcanum",                 "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")
LoonBestInSlot:AddItem(spec, "27842", "2H", "Grand Scepter of the Nexus-Kings",     "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "31308", "2H", "The Bringer of Death",                 "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "25760", "2H", "Battle Mage's Baton",                  "PreRaid", "0", "Quest", "The Ring of Blood: The Final Challenge", "Nagrand")

LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets",        "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone",                      "Alt Arc", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29270", "OH", "Flametongue Seal",                 "Alt Fire", "1>3", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities",  "Alt", "1>3", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane",            "Alt", "1>3", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28781", "OH", "Karaborian Talisman",              "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29269", "OH", "Sapphiron's Wing Bone",            "Alt Frost", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance",        "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28187", "OH", "Star-Heart Lamp",                  "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28260", "OH", "Manual of the Nethermancer",       "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "27534", "OH", "Hortus' Seal of Brilliance",       "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "31699", "OH", "Imbued Draenethyst Crystal",       "PreRaid", "0", "Quest", "Teleport This!", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31731", "OH", "Mekeda's Gift",                    "PreRaid", "0", "Quest", "Escaping the Tomb", "Terokkar Forest")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star",     "BIS", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration",    "BIS Arc", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "32343", "Wand", "Wand of Prismatic Focus",        "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy",    "Alt", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28386", "Wand", "Nether Core's Control Rod",      "PreRaid", "0", "Drop", "Dalliah the Doomsayer", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "32872", "Wand", "Illidari Rod of Discipline",     "PreRaid", "0", "Quest", "Subdue the Subduer", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "25939", "Wand", "Voidfire Wand",                  "PreRaid", "0", "Drop", "Pandemonius", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk",                "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "27890", "Wand", "Wand of the Netherwing",         "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "31724", "Wand", "Arakkoa Divining Rod",           "PreRaid", "0", "Quest", "A Personal Favor", "Terokkar Forest")
LoonBestInSlot:AddItem(spec, "30523", "Wand", "Hotshot Cattle Prod",            "PreRaid", "0", "Quest", "When the Cows Come Home", "Netherstorm")