local spec = LoonBestInSlot:RegisterSpec("Paladin", "Prot")

LoonBestInSlot:AddItem(spec, "30987", "Head", "Lightbringer Faceguard",         "BIS", "3", "Drop", "Archimonde", "Black Temple")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "BIS", "3", "Token", "Archimonde", "Black Temple")
LoonBestInSlot:AddItem(spec, "32521", "Head", "Faceplate of the Impenetrable",  "BIS Def", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30125", "Head", "Crystalforge Faceguard",         "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32473", "Head", "Tankatronic Goggles",            "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "32083", "Head", "Faceguard of Determination",     "Alt", "1>2", "Dungeon Token", "50 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "29068", "Head", "Justicar Faceguard",             "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",    "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28593", "Head", "Eternium Greathelm",             "Alt", "1>2", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "23536", "Head", "Oathkeeper's Helm",              "PreRaid", "0", "Profession", "Blacksmithing")
LoonBestInSlot:AddItem(spec, "23535", "Head", "Helm of the Stalwart Defender",  "PreRaid", "0", "Profession", "Blacksmithing")
LoonBestInSlot:AddItem(spec, "28285", "Head", "Helm of the Righteous",          "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "28180", "Head", "Myrmidon's Headdress",           "PreRaid", "0", "Quest", "The Warlord's Hideout", "Watcher Jhang, The Steamvault")
LoonBestInSlot:AddItem(spec, "23519", "Head", "Felsteel Helm",                  "PreRaid", "0", "Profession", "Blacksmithing")
LoonBestInSlot:AddItem(spec, "27520", "Head", "Greathelm of the Unbreakable",   "PreRaid", "0", "Drop", "Grand Warlock Nethekurse", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "30016", "Head", "X-52 Technician's Helm",         "PreRaid", "0", "Quest", "Back to the Chief!", "Netherstorm")

LoonBestInSlot:AddItem(spec, "30998", "Shoulders", "Lightbringer Shoulderguards",       "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32250", "Shoulders", "Pauldrons of Abyssal Fury",         "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29070", "Shoulders", "Justicar Shoulderguards",           "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion",  "Alt", "1>3", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30127", "Shoulders", "Crystalforge Shoulderguards",       "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28743", "Shoulders", "Mantle of Abrahmis",                "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "27739", "Shoulders", "Spaulders of the Righteous",        "PreRaid", "0", "Drop", "Laj", "The Botanica")
LoonBestInSlot:AddItem(spec, "27847", "Shoulders", "Fanblade Pauldrons",                "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts Heroic")
LoonBestInSlot:AddItem(spec, "32073", "Shoulders", "Spaulders of Dementia",             "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls Heroic")
LoonBestInSlot:AddItem(spec, "30381", "Shoulders", "Kaylaan's Spaulders",               "PreRaid", "0", "Quest", "Aldor No More", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29316", "Shoulders", "Warchief's Mantle",                 "PreRaid", "0", "Quest", "Return to Andormu", "Caverns of Time")
LoonBestInSlot:AddItem(spec, "24463", "Shoulders", "Pauldrons of Brute Force",          "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog")

LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak",             "BIS Def", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders", "BIS Thrt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification",  "Alt Mit", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council",  "Alt Thrt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape",                "Alt Def", "1>3", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "30642", "Back", "Drape of the Righteous",         "Alt Thrt", "1>2", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran",        "Alt Thrt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant",    "Alt Thrt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi",   "Alt Thrt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak",           "Alt Def", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "24253", "Back", "Cloak of Eternity",              "PreRaid", "0", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "29385", "Back", "Farstrider Defender's Cloak",    "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "27988", "Back", "Burnoose of Shifting Ages",      "PreRaid", "0", "Drop", "Chrono Lord Deja", "The Black Morass")
LoonBestInSlot:AddItem(spec, "24379", "Back", "Bogstrok Scale Cloak",           "PreRaid", "0", "Drop", "Rokmar the Crackler", "The Slave Pens")
LoonBestInSlot:AddItem(spec, "29777", "Back", "Cloak of the Valiant Defender",  "PreRaid", "0", "Quest", "Ar'kelos the Guardian")

LoonBestInSlot:AddItem(spec, "30991", "Chest", "Lightbringer Chestguard",               "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30123", "Chest", "Crystalforge Chestguard",               "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29066", "Chest", "Justicar Chestguard",                   "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion",     "Alt", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate",               "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28203", "Chest", "Breastplate of the Righteous",          "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "28262", "Chest", "Jade-Skull Breastplate",                "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "29127", "Chest", "Vindicator's Hauberk",                  "PreRaid", "0", "Reputation", "The Aldor (Revered)", "Quartermaster Endarin, Shattrath City")
LoonBestInSlot:AddItem(spec, "23507", "Chest", "Adamantite Breastplate",                "PreRaid", "0", "Profession", "Blacksmithing (340)")
LoonBestInSlot:AddItem(spec, "25819", "Chest", "Breastplate of the Warbringer",         "PreRaid", "0", "Quest", "Forge Camp: Annihilated", "Nagrand")
LoonBestInSlot:AddItem(spec, "30270", "Chest", "Scavenged Breastplate",                 "PreRaid", "0", "Quest", "It's a Fel Reaver, But with Heart", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30296", "Chest", "Lost Chestplate of the Reverent",       "PreRaid", "0", "Quest", "Wanted: Annihilator Servo!", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29337", "Chest", "The Exarch's Protector",                "PreRaid", "0", "Quest", "Everything Will Be Alright", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "32279", "Bracers", "The Seeker's Wristguards",        "BIS", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "33889", "Bracers", "Vindicator's Lamellar Bracers",   "BIS", "3", "PvP", "11794 Honor Points, 20 Warsong Gulch Marks")
LoonBestInSlot:AddItem(spec, "32232", "Bracers", "Eternium Shell Bracers",          "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32515", "Bracers", "Wristguards of Determination",    "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29252", "Bracers", "Bracers of Dignity",              "Alt Thrt", "1>3", "Drop", "Harbinger Skyriss", "The Arcatraz Heroic")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress",   "Alt", "1>2", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage",            "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor",    "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault Heroic")
LoonBestInSlot:AddItem(spec, "28167", "Bracers", "Sha'tari Wrought Armguards",      "PreRaid", "0", "Quest", "The Soul Devices", "Auchindoun")
LoonBestInSlot:AddItem(spec, "27459", "Bracers", "Vambraces of Daring",             "PreRaid", "0", "Drop", "Vazruden the Herald", "Hellfire Ramparts Heroic")
LoonBestInSlot:AddItem(spec, "30400", "Bracers", "Thadell's Bracers",               "PreRaid", "0", "Quest", "When the Cows Come Home", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30225", "Bracers", "Junior Technician 3rd Grade Bracers", "PreRaid", "0", "Quest", "You're Hired!", "Area 52, Netherstorm")

LoonBestInSlot:AddItem(spec, "30985", "Gloves", "Lightbringer Handguards",          "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32280", "Gloves", "Gauntlets of Enforcement",         "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32515", "Gloves", "Wristguards of Determination",     "Alt Def", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30124", "Gloves", "Crystalforge Handguards",          "Alt Thrt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt Thrt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29067", "Gloves", "Justicar Handguards",              "Alt Thrt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion",    "Alt Thrt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "30741", "Gloves", "Topaz-Studded Battlegrips",        "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden",     "Alt Def", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "32072", "Gloves", "Gauntlets of Dissension",          "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica Heroic")
LoonBestInSlot:AddItem(spec, "23532", "Gloves", "Gauntlets of the Iron Tower",      "PreRaid", "0", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "27535", "Gloves", "Gauntlets of the Righteous",       "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "23517", "Gloves", "Felsteel Gloves",                  "PreRaid", "0", "Profession", "Blacksmithing (360)")
LoonBestInSlot:AddItem(spec, "25788", "Gloves", "Dauntless Handguards",             "PreRaid", "0", "Quest", "Fel Embers", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "28390", "Gloves", "Thatia's Self-Correcting Gauntlets", "PreRaid", "0", "Drop", "Dalliah the Doomsayer", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "29134", "Gloves", "Gauntlets of the Chosen",          "PreRaid", "0", "Reputation", "The Scryers Revered", "Quartermaster Enuril, Shattrath City")
LoonBestInSlot:AddItem(spec, "29959", "Gloves", "Spiritualist's Gauntlets",         "PreRaid", "0", "Quest", "A Fate Worse Than Death", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32342", "Belt", "Girdle of Mighty Resolve",       "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30034", "Belt", "Belt of the Guardian",           "BIS", "2>3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "32333", "Belt", "Girdle of Stability",            "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30096", "Belt", "Girdle of the Invulnerable",     "Alt Def", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable", "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "29253", "Belt", "Girdle of Valorous Deeds",       "Alt", "1>2", "Drop", "Aeonus", "The Black Morass Heroic")
LoonBestInSlot:AddItem(spec, "27672", "Belt", "Girdle of the Immovable",        "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens Heroic")
LoonBestInSlot:AddItem(spec, "29238", "Belt", "Lion's Heart Girdle",            "PreRaid", "0", "Drop", "Vazruden the Herald", "Hellfire Ramparts Heroic")
LoonBestInSlot:AddItem(spec, "31460", "Belt", "Sha'tari Vindicator's Waistguard", "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30371", "Belt", "Lightwarden's Girdle",           "PreRaid", "0", "Quest", "Deathblow to the Legion", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30330", "Belt", "Starcaller's Plated Belt",       "PreRaid", "0", "Quest", "Arconus the Insatiable", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30380", "Belt", "Girdle of the Lost Vindicator",  "PreRaid", "0", "Quest", "Aldor No More", "Netherstorm")

LoonBestInSlot:AddItem(spec, "30995", "Legs", "Lightbringer Legguards",             "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30126", "Legs", "Crystalforge Legguards",             "BIS Thrt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "BIS Thrt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32263", "Legs", "Praetorian's Legguards",             "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves",              "Alt Def", "1>3", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29069", "Legs", "Justicar Legguards",                 "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29766", "Legs", "Leggings of the Fallen Champion",    "Alt", "1>2", "Token", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings",              "PreRaid", "0", "Reputation", "Keepers of Time (Revered)", "Alurmi, Tanaris")
LoonBestInSlot:AddItem(spec, "23518", "Legs", "Felsteel Leggings",                  "PreRaid", "0", "Profession", "Blacksmithing (360)")
LoonBestInSlot:AddItem(spec, "27527", "Legs", "Greaves of the Shatterer",           "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "29783", "Legs", "Legguards of the Resolute Defender", "PreRaid", "0", "Quest", "Destroy Naberius!", "Netherstorm")
LoonBestInSlot:AddItem(spec, "27839", "Legs", "Legplates of the Righteous",         "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "29774", "Legs", "Kirin'Var Defender's Chausses",      "PreRaid", "0", "Quest", "The Sigil of Krasus", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32245", "Feet", "Tide-stomper's Greaves",         "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32268", "Feet", "Myrmidon's Treads",              "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30033", "Feet", "Boots of the Protector",         "Alt", "2>3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "32267", "Feet", "Boots of the Resilient",         "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion",               "Alt Mit", "1>3", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "29254", "Feet", "Boots of the Righteous Path",    "Alt Thrt", "1>3", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls Heroic")
LoonBestInSlot:AddItem(spec, "30031", "Feet", "Red Havoc Boots",                "Alt", "2>3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "28747", "Feet", "Battlescar Boots",               "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29239", "Feet", "Eaglecrest Warboots",            "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace Heroic")
LoonBestInSlot:AddItem(spec, "27813", "Feet", "Boots of the Colossus",          "PreRaid", "0", "Drop", "Pandemonius", "Mana-Tombs Heroic")
LoonBestInSlot:AddItem(spec, "32866", "Feet", "Ascendant's Boots",              "PreRaid", "0", "Quest", "A Job Unfinished...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29325", "Feet", "Flesh Beast's Metal Greaves",    "PreRaid", "0", "Quest", "Someone Else's Hard Work Pays Off", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "30334", "Feet", "Starcaller's Plated Stompers",   "PreRaid", "0", "Quest", "Escape from the Staging Grounds", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30386", "Feet", "Bloodguard's Greaves",           "PreRaid", "0", "Quest", "Information Gathering", "Netherstorm")
LoonBestInSlot:AddItem(spec, "28318", "Feet", "Obsidian Clodstompers",          "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")

LoonBestInSlot:AddItem(spec, "33921", "Neck", "Vindicator's Pendant of Dominance", "BIS Thrt", "2>3", "PvP", "15300 Honor, 10 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "30007", "Neck", "The Darkener's Grasp",           "BIS Def", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "BIS Def", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt Thrt", "3", "", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans",              "Alt Def", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman",        "Alt Thrt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30008", "Neck", "Pendant of the Lost Ages",       "Alt Thrt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline",    "Alt Def", "1>3", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29173", "Neck", "Strength of the Untamed",        "Alt Def", "1>2", "Reputation", "Cenarion Expedition (Revered)", "Fedryen Swiftspear, Zangarmarsh")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut",     "Alt Def", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury",    "Alt Thrt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27871", "Neck", "Maladaar's Blessed Chaplet",     "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27792", "Neck", "Steam-Hinge Chain of Valor",     "PreRaid", "0", "Drop", "Mekgineer Steamrigger", "The Steamvault")
LoonBestInSlot:AddItem(spec, "30378", "Neck", "Thalodien's Charm",              "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31696", "Neck", "Natasha's Battle Chain",         "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29336", "Neck", "Mark of the Ravenguard",         "PreRaid", "0", "Quest", "Brother Against Brother", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "28321", "Neck", "Enchanted Thorium Torque",       "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "25809", "Neck", "Maimfist's Choker",              "PreRaid", "0", "Quest", "The Will of the Warchief", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "25803", "Neck", "Medallion of the Valiant Guardian", "PreRaid", "0", "Quest", "Turning the Tide", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "24121", "Neck", "Chain of the Twilight Owl",      "PreRaid", "0", "Profession", "Jewelcrafting (365)")

LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage",       "BIS Thrt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "30083", "Ring", "Ring of Sundered Souls",         "BIS", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30028", "Ring", "Seventh Ring of the Tirisfalen", "BIS", "2>3", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "33054", "Ring", "The Seal of Danzalar",           "Alt Mit", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32261", "Ring", "Band of the Abyssal Lord",       "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29297", "Ring", "Band of the Eternal Defender",   "Alt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "33853", "Ring", "Vindicator's Band of Dominance", "Alt", "3", "PvP", "15300 Honor, 10 Alterac Valley Marks")
LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector", "Alt", "1>3",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense",      "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar",                  "Alt Thrt", "2", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils",          "Alt Thrt", "2", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury",           "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry",  "Alt", "1>2", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "31319", "Ring", "Band of Impenetrable Defenses",  "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "30006", "Ring", "Wind Trader's Band",             "PreRaid", "0", "Quest", "Dealing with the Overmaster", "Netherstorm")
LoonBestInSlot:AddItem(spec, "27822", "Ring", "Crystal Band of Valor",          "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28211", "Ring", "Lieutenant's Signet of Lordaeron", "PreRaid", "0", "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force",       "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "31078", "Ring", "Protector's Mark of the Redemption", "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "27436", "Ring", "Iron Band of the Unbreakable",   "PreRaid", "0", "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "24088", "Ring", "Delicate Eternium Ring",         "PreRaid", "0", "Profession", "Jewelcrafting (355)")
LoonBestInSlot:AddItem(spec, "31924", "Ring", "Yor's Revenge",                  "PreRaid", "0", "Drop", "Yor", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "29323", "Ring", "Andormu's Tear",                 "PreRaid", "0", "Quest", "The Opening of the Dark Portal", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28265", "Ring", "Dath'Remar's Ring of Defense",   "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")

LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia",         "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "28528", "Trinket", "Moroes' Lucky Pocket Watch",  "BIS Mit", "1>3", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus",    "BIS Mit", "1>3", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance",    "BIS Stam", "3", "Quest", "Darkmoon Furies Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon",          "BIS Thrt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",      "Alt", "3", "Quest", "Darkmoon Blessings Deck", "Darkmoon Fair")
LoonBestInSlot:AddItem(spec, "32489", "Trinket", "Ashtongue Talisman of Zeal",  "Alt", "3", "Reputation", "Ashtongue Deathsworn  (Exalted)", "Okuno")
LoonBestInSlot:AddItem(spec, "30447", "Trinket", "Tome of Fiery Redemption",    "Alt Thrt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30629", "Trinket", "Scarab of Displacement",      "Alt Mit", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32534", "Trinket", "Brooch of the Immortal King", "Alt Mit", "1>3", "Drop", "Terokk", "Terokkar Forest")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine",         "Alt Mit", "1", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "Alt Thrt", "1", "Dungeon Token", "41 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "24126", "Trinket", "Figurine - Living Ruby Serpent", "Alt", "1", "Profession", "Jewelcrafting (370)")
LoonBestInSlot:AddItem(spec, "30300", "Trinket", "Dabiri's Enigma",             "PreRaid", "0", "Quest", "Dimensius the All-Devouring", "Netherstorm")
LoonBestInSlot:AddItem(spec, "24125", "Trinket", "Figurine - Dawnstone Crab",   "PreRaid", "0", "Profession", "Jewelcrafting (370)")
LoonBestInSlot:AddItem(spec, "28042", "Trinket", "Regal Protectorate",          "PreRaid", "0", "Quest", "Overlord/Cruel's Intentions", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600", "PreRaid", "0", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")

LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos",                 "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel",       "BIS", "3", "PvP", "3150 Arena Points")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement",              "Alt", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan",            "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade",             "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets",       "Alt", "1>2", "Reputation", "Lower City Exalted", "Nakodu")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage",            "Alt", "1>2", "Reputation", "Honor Hold Exalted", "Logistics Officer Ulrike, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller",                      "Alt", "1>2", "Reputation", "Thrallmar Exalted", "Quartermaster Urgronn, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28749", "MH", "King's Defender",                  "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29156", "MH", "Honor's Call",                     "PreRaid", "0", "Reputation", "Honor Hold (Exalted)", "Quartermaster Urgronn, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer",                       "PreRaid", "0", "Reputation", "Thrallmar (Exalted)", "Logistics Officer Ulrike, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry",                "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "32660", "MH", "Crystalforged Sword",              "PreRaid", "0", "Quest", "Wierd Blades Edged Quest w/ Depleted Sword")
LoonBestInSlot:AddItem(spec, "29185", "MH", "Continuum Blade",                  "PreRaid", "0", "Drop", "Alurmi", "Keepers of Time Revered, Tanaris")
LoonBestInSlot:AddItem(spec, "27899", "MH", "Mana Wrath",                       "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams",      "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "24361", "MH", "Spellfire Longsword",              "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens")
LoonBestInSlot:AddItem(spec, "24384", "MH", "Diamond-Core Sledgemace",          "PreRaid", "0", "Drop", "The Maker", "The Blood Furnace")

LoonBestInSlot:AddItem(spec, "32375", "Shield", "Bulwark of Azzinoth",              "BIS Mit", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30909", "Shield", "Antonidas's Aegis of Rapt Concentration", "BIS Thrt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30889", "Shield", "Kaz'rogal's Hardened Heart",       "Alt Mit", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33755", "Shield", "Vengeful Gladiator's Shield Wall", "Alt Mit", "3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "33661", "Shield", "Vengeful Gladiator's Barrier",     "Alt Thrt", "3", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender",           "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness",  "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar",             "Alt", "1>2", "Reputation", "The Sha'tar", "Exalted")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra",         "Alt", "1>2", "Dungeon Token", "33 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "32082", "Shield", "The Fel Barrier",                  "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs Heroic")
LoonBestInSlot:AddItem(spec, "32652", "Shield", "Ogri'la Aegis",                    "PreRaid", "0", "Reputation", "Ogri'la (Revered)", "Jho'nass, Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird",             "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "27449", "Shield", "Blood Knight Defender",            "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous",  "PreRaid", "0", "Drop", "Ambassador Hellmaw", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28166", "Shield", "Shield of the Void",               "PreRaid", "0", "Drop", "Pandemonius", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "31200", "Shield", "Shield of the Wayward Footman",    "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "29388", "Libram", "Libram of Repentance",         "BIS Mit", "1>3", "Dungeon Token", "15 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "32368", "Libram", "Tome of the Lightbringer",     "BIS Mit", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "27917", "Libram", "Libram of the Eternal Rest",   "BIS Thrt", "1>3", "Drop", "Darkweaver Syth", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope",               "PreRaid", "0", "Drop", "Isalien", "Dire Maul")