local spec = LoonBestInSlot:RegisterSpec("Priest", "Holy")
LoonBestInSlot:AddItem(spec, "31063", "Head", "Cowl of Absolution",             "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror","BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32329", "Head", "Cowl of Benevolence",            "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "30152", "Head", "Cowl of the Avatar",             "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32495", "Head", "Powerheal 4000 Lens",            "Alt", "2>3", "Profession", "Engineering (370)")
LoonBestInSlot:AddItem(spec, "29990", "Head", "Crown of the Sun",               "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29049", "Head", "Light-Collar of the Incarnate",  "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",    "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood",                 "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28756", "Head", "Headdress of the High Potentate", "Alt", "1", "Drop", "Dust Covered Chest", "Karazhan")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown",                 "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "19132", "Head", "Crystal Adorned Crown",          "PreRaid", "0", "Drop", "Azuregos")
LoonBestInSlot:AddItem(spec, "31410", "Head", "Gladiator's Mooncloth Hood",     "PreRaid", "0", "PvP", "1,875 Arena Points")
LoonBestInSlot:AddItem(spec, "29174", "Head", "Watcher's Cowl",                 "PreRaid", "0", "Reputation", "Cenarion Expedition", "Revered")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "PreRaid", "0", "Quest", " Teron Gorefiend, I am...", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "31069", "Shoulders", "Mantle of Absolution",              "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32585", "Shoulders", "Swiftheal Mantle",                  "Alt", "3", "Profession", "Tailoring (375)", "")
LoonBestInSlot:AddItem(spec, "30154", "Shoulders", "Mantle of the Avatar",              "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders",        "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29054", "Shoulders", "Light-Mantle of the Incarnate",     "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",  "Alt,2", "1", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28612", "Shoulders", "Pauldrons of the Solace-Giver",     "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons",                "PreRaid", "0", "Drop", "Grandmaster Vorpil", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "31412", "Shoulders", "Gladiator's Mooncloth Mantle",      "PreRaid", "0", "PvP", "1,875 Arena Points")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance",           "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills ")
LoonBestInSlot:AddItem(spec, "28250", "Shoulders", "Vestia's Pauldrons of Inner Grace", "PreRaid", "0", "Drop", "Cache of the Legion", "The Mechanar")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",        "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness",          "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak",          "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand",      "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak",               "Alt", "1>2", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Althop's Cloak",                 "Alt", "1", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak",        "Alt", "1", "Drop", "The Big Bad Wolf", "Karazhan")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism", "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27448", "Back", "Cloak of the Everliving",        "PreRaid", "0", "Drop", "Watchkeeper Gargolmar", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape",              "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "28373", "Back", "Cloak of Scintillating Auras",   "PreRaid", "0", "Drop", "Zereketh the Unbound", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "27789", "Back", "Cloak of Whispering Shells",     "PreRaid", "0", "Drop", "Hydromancer Thespia", "The Steamvault")
LoonBestInSlot:AddItem(spec, "25810", "Back", "Vicar's Cloak",                  "PreRaid", "0", "Quest", "The Will of the Warchief", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "25805", "Back", "Mantle of Vivification",         "PreRaid", "0", "Quest", "Turning the Tide", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27946", "Back", "Avian Cloak of Feathers",        "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "25945", "Back", "Cloak of Revival",               "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "31465", "Back", "Sha'tari Anchorite's Cloak",     "PreRaid", "0", "Quest", "How to Break Into the Arcatraz")

LoonBestInSlot:AddItem(spec, "31066", "Chest", "Vestments of Absolution",           "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30150", "Chest", "Vestments of the Avatar",           "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32340", "Chest", "Garments of Temperance",            "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29050", "Chest", "Robes of the Incarnate",            "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe",             "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments",                 "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "31413", "Chest", "Gladiator's Mooncloth Robe",        "PreRaid", "0", "PvP", "1,875 Arena Points")
LoonBestInSlot:AddItem(spec, "24397", "Chest", "Raiments of Divine Authority",      "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace ")
LoonBestInSlot:AddItem(spec, "27506", "Chest", "Robe of Effervescent Light",        "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")

LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps",             "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30871", "Bracers", "Bracers of Martyrdom",        "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32516", "Bracers", "Wraps of Purification",       "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker",  "Alt", "1>3", "Reputation", "Keepers of Time – Exalted")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling",         "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent",     "Alt", "1", "Drop", "Talon King Ikiss", "Sethekk Halls (Heroic)")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps",             "PreRaid", "0", "Quest", "The Soul Devices", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "31060", "Gloves", "Gloves of Absolution",             "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30151", "Gloves", "Gloves of the Avatar",             "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32353", "Gloves", "Gloves of Unfailing Faith",        "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "29055", "Gloves", "Handwraps of the Incarnate",       "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender",    "Alt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings",      "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "27536", "Gloves", "Hallowed Handwraps",               "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "28304", "Gloves", "Prismatic Mittens of Mending",     "PreRaid", "0", "Drop", "Commander Sarannis", "The Botanica")
LoonBestInSlot:AddItem(spec, "24393", "Gloves", "Bloody Surgeon's Mitts",           "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace ")
LoonBestInSlot:AddItem(spec, "29315", "Gloves", "Gloves of Penitence",              "PreRaid", "0", "Quest", "Levixus the Soul Caller", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "31409", "Gloves", "Gladiator's Mooncloth Gloves",     "PreRaid", "0", "PvP", "1,125 Arena Points")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", "Tempest's Touch",                  "PreRaid", "0", "Quest", "Return to Andormu", "Caverns of Time")

LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash",               "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32519", "Belt", "Belt of Divine Guidance",        "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road",          "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt",          "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30675", "Belt", "Lurker's Cord",                  "Alt", "1", "Drop", "Hyakiss the Lurker", "Karazhan")
LoonBestInSlot:AddItem(spec, "28652", "Belt", "Cincture of Will",               "Alt", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification",         "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "27542", "Belt", "Cord of Belief",                 "PreRaid", "0", "Drop", "Commander Sarannis", "The Botanica (Heroic)")
LoonBestInSlot:AddItem(spec, "27843", "Belt", "Glyph-Lined Sash",               "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")

LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity",           "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31068", "Legs", "Breeches of Absolution",         "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30153", "Legs", "Breeches of the Avatar",         "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29977", "Legs", "Star-Soul Breeches",             "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance",       "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt",                  "Alt", "1>2", "Drop", "Warlord Kalithresh ", "The Steamvault (Heroic)")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants",                "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt",        "Alt", "1>2", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "28218", "Legs", "Pontiff's Pantaloons of Prophecy", "PreRaid", "0", "Drop", "Captain Skarloc", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration",   "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "30256", "Legs", "Pants of the Naaru",             "PreRaid", "0", "Quest", "Levixus the Soul Caller", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light",      "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "30100", "Feet", "Soul-Strider Boots",             "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30885", "Feet", "Archbishop's Slippers",          "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30035", "Feet", "Boots of the Long Road",         "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious",             "Alt", "1>2", "Drop", "Pathaleon the Calculator", "The Mechanar (Heroic)")
LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt",         "Alt", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity",           "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity",     "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim",         "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman",             "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence",      "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul",                 "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28731", "Neck", "Shining Chain of the Afterworld", "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope",       "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion",              "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara Netherstorm")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope",   "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord",        "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "27766", "Neck", "Swampstone Necklace",            "PreRaid", "0", "Drop", "Swamplord Musel'ek", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "28419", "Neck", "Choker of Fluid Thought",        "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "29334", "Neck", "Sethekk Oracle's Focus",         "PreRaid", "0", "Quest", "Brother Against Brother", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor",            "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer",       "Alt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived",          "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt", "1>3",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light",              "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth",            "Alt", "2", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving",        "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",                 "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band",           "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28661", "Ring", "Mender's Heart-Ring",                "Alt", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos",                      "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence",              "PreRaid", "0", "Reputation", "Honor Hold Revered", "Logistics Officer Ulrike")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band",                     "PreRaid", "0", "Reputation", "Thrallmar Revered", "Quartermaster Urgronn")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void",       "PreRaid", "0", "Drop", "Yor", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "PreRaid", "0", "Quest", "Battle of the Crimson Watch", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29322", "Ring", "Keeper's Ring of Piety",             "PreRaid", "0", "Quest", "The Opening of the Dark Portal", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband",                    "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope",                "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring",               "PreRaid", "0", "Quest", "Hitting the Motherlode", "Netherstorm")

LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr",           "BIS", "1>3", "Dungeon Token", "G'eras", "41 Badge of Justice")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops",                   "BIS", "2>3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "19288", "Trinket", "Darkmoon Card: Blue Dragon",      "BIS", "3", "Quest", "Darkmoon Beast Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul",                    "BIS", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "32490", "Trinket", "Ashtongue Talisman of Acumen",    "Alt", "3", "Reputation", "Ashtongue Deathsworn (Exalted)", "Okuno")
LoonBestInSlot:AddItem(spec, "30665", "Trinket", "Earring of Soulful Meditation",   "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice",             "Alt", "1>2", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "19288", "Trinket", "Darkmoon Card: Blue Dragon",      "Alt", "1>2", "Quest", "Beasts Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle",    "Alt", "1>2", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook",           "PreRaid", "0", "Reputation", "Lower City Revered")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler",       "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic",                  "PreRaid", "0", "Quest", "Gava'xi", "Nagrand")
LoonBestInSlot:AddItem(spec, "28370", "Trinket", "Bangle of Endless Blessings",     "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor",         "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "33743", "MH", "Vengeful Gladiator's Salvation",   "Alt", "3", "PvP", "3,150 Arena Points")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement",              "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter",              "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice",                  "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous",            "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation",            "Alt", "1", "PvP", "17786 Honor Points, 20 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity",                 "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon",              "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min",   "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light",              "PreRaid", "0", "Reputation", "The Sha'tar Exalted")
LoonBestInSlot:AddItem(spec, "28257", "MH", "Hammer of the Penitent",           "PreRaid", "0", "Drop", "Mechano-Lord Capacitus", "The Mechanar")
LoonBestInSlot:AddItem(spec, "31304", "MH", "The Essence Focuser",              "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27538", "MH", "Lightsworn Hammer",                "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "28216", "MH", "Dathrohan's Ceremonial Hammer",    "PreRaid", "0", "Drop", "Captain Skarloc", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "30908", "2H", "Apostle of Argus",                 "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32344", "2H", "Staff of Immaculate Recovery",     "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29981", "2H", "Ethereum Life-Staff",              "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30732", "2H", "Exodar Life-Staff",                "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28782", "2H", "Crystalheart Pulse-Staff",         "Alt", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28604", "2H", "Nightstaff of the Everliving",     "Alt", "1", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "27791", "2H", "Serpentcrest Life-Staff",          "PreRaid", "0", "Drop", "Mekgineer Steamrigger", "The Steamvault")
LoonBestInSlot:AddItem(spec, "28033", "2H", "Epoch-Mender",                     "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "29133", "2H", "Seer's Cane",                      "PreRaid", "0", "Reputation", "The Scryers — Revered", "Quartermaster Enuril")

LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification",      "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32350", "OH", "Touch of Inspiration",         "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King",     "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven",              "Alt", "1>3", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb",             "Alt", "1>3", "Reputation", "Cenarion Expedition (Exalted)", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire",     "Alt", "1", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing",   "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "28213", "OH", "Lordaeron Medical Guide",      "PreRaid", "0", "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "27714", "OH", "Swamplight Lantern",           "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "28387", "OH", "Lamp of Peaceful Repose",      "PreRaid", "0", "Drop", "Dalliah the Doomsayer", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "32363", "Wand", "Naaru-Blessed Life Rod",         "BIS", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30080", "Wand", "Luminescent Rod of the Naaru",   "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28588", "Wand", "Blue Diamond Witchwand",         "Alt", "1>3", "Drop", "The Wizard of Oz", "Karazhan")
LoonBestInSlot:AddItem(spec, "29779", "Wand", "Rejuvenating Scepter",           "Alt", "1", "Quest", "Ar'kelos the Guardian", "Netherstorm")
LoonBestInSlot:AddItem(spec, "27885", "Wand", "Soul-Wand of the Aldor",         "Alt", "1", "Drop", "Ambassador Hellmaw", "Shadow Labyrinth")