local spec = LoonBestInSlot:RegisterSpec("Warlock", "")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror", "BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31051", "Head", "Hood of the Malefic",            "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32494", "Head", "Destruction Holo-gogs",          "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "30212", "Head", "Hood of the Corruptor",          "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero",    "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28963", "Head", "Voidheart Crown",                "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29759", "Head", "Helm of the Fallen Hero",        "Alt", "1>3", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer",     "Alt", "2", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28744", "Head", "Uni-Mind Headdress",             "Alt Hit", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood",               "Alt", "1", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "PreRaid", "0", "Quest", " Teron Gorefiend, I am...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl",                "PreRaid", "0", "Drop", "Pathaleon the Calculator", "Mechanar")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion",               "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28169", "Head", "Mag'hari Ritualist's Horns",     "PreRaid", "0",  "Quest", "Hero of the Mag'har", "Nagrand")

LoonBestInSlot:AddItem(spec, "31054", "Shoulders", "Mantle of the Malefic",         "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads",     "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle",               "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought",      "Alt", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28967", "Shoulders", "Voidheart Mantle",              "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29762", "Shoulders", "Pauldrons of the Fallen Hero",  "Alt", "1>3", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30215", "Shoulders", "Mantle of the Corruptor",        "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings",     "Alt", "2>3", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30079", "Shoulders", "Illidari Shoulderpads",         "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21869", "Shoulders", "Frozen Shadoweave Shoulders",   "Alt", "1>2", "Profession", "Shadoweave Tailoring (355)")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders",         "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors",       "PreRaid", "0", "Drop", "Chrono Lord Deja", "The Black Morass")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart",   "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32590", "Back", "Nethervoid Cloak",                   "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",            "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council",      "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders",     "Alt Demo", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant",        "Alt Hit", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi",       "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran",            "Alt Demo", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "31140", "Back", "Cloak of Entropy",                   "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "31052", "Chest", "Robe of the Malefic",           "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch",    "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin",               "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30214", "Chest", "Robe of the Corruptor",         "Alt", "2>3", "Drop","Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes",        "Alt", "2", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28964", "Chest", "Voidheart Robe",                "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29755", "Chest", "Chestguard of the Fallen Hero", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe",                "Alt Destruc", "1>2", "Profession", "Spellfire Tailoring (375)")
LoonBestInSlot:AddItem(spec, "21871", "Chest", "Frozen Shadoweave Robe",        "Alt", "1>2", "Profession", "Shadoweave Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28602", "Chest", "Robe of the Elder Scribes",     "Alt", "1", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order",     "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe",     "PreRaid", "0", "Quest", "Everything Will Be Alright", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "28191", "Chest", "Mana-Etched Vestments",         "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28232", "Chest", "Robe of Oblivion",              "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought",   "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings",       "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation",        "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands",        "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32820", "Bracers", "Veteran's Silk Cuffs",        "Alt", "2", "PvP", "11794 Honor - 20 Warsong Gulch Marks", "Honor")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok",            "Alt", "1>2", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds",    "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "21186", "Bracers", "Rockfury Bracers",            "PreRaid", "0", "Reputation", "Cenarion Circle Revered", "Vargus")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom",    "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts (Heroic)")

LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31050", "Gloves", "Gloves of the Malefic",            "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves",                 "Alt Destruc", "1>3", "Profession", "Spellfire Tailoring (365)")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves",               "Alt Hit", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero",    "Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30211", "Gloves", "Gloves of the Corruptor",          "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps",           "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King",        "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought",     "Alt", "1>3", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28968", "Gloves", "Voidheart Gloves",                 "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29756", "Gloves", "Gloves of the Fallen Hero",        "Alt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "31149", "Gloves", "Gloves of Pandemonium",            "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves",               "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts")
LoonBestInSlot:AddItem(spec, "27537", "Gloves", "Gloves of Oblivion",               "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "24450", "Gloves", "Manaspark Gloves",                 "PreRaid", "0", "Drop", "Hungarfen", "The Underbog")

LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting",           "BIS", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose",          "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity",      "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors",  "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30020", "Belt", "Fire-Cord of the Magus",     "Alt Destruc", "2>3", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt",             "Alt Destruc", "1>3", "Profession", "Spellfire Tailoring (355)")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination",        "Alt", "1>2", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity",          "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift",               "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "27795", "Belt", "Sash of Serpentra",          "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements",     "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation",            "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31053", "Legs", "Leggings of the Malefic",            "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero",    "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30213", "Legs", "Leggings of the Corruptor",          "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants",                  "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle",     "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer",        "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28966", "Legs", "Voidheart Leggings",                 "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29765", "Legs", "Leggings of the Fallen Hero",        "Alt", "1>2", "Token", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist",          "PreRaid", "0", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "19133", "Legs", "Fel Infused Leggings",               "PreRaid", "0", "Drop", "Lord Kazzak", "Blasted Lands")
LoonBestInSlot:AddItem(spec, "27948", "Legs", "Trousers of Oblivion",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "27907", "Legs", "Mana-Etched Pantaloons",             "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller",          "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes",                   "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting",                  "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30050", "Feet", "Boots of the Shifting Nightmare",    "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian",       "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots",            "Alt", "1>3", "Profession", "Shadoweave Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers",                      "Alt Hit", "1>2", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling",               "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice",        "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots",                  "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers",                  "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace",   "BIS", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "32589", "Neck", "Hellfire-Encased Pendant",           "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night",                   "BIS", "3", "Profession", "Jewelcrafting (360)")
LoonBestInSlot:AddItem(spec, "35319", "Neck", "Vindicator's Pendant of Subjugation", "BIS", "3", "PvP", "15300 Honor Points - 10 Eye of the Storm Marks", "PvP Vendor")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                     "BIS", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman",            "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30008", "Neck", "Pendant of the Lost Ages",           "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury",        "Alt Hit", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "30666", "Neck", "Ritssyn's Lost Pendant",             "Alt", "1>2", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls",          "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential",     "Alt Hit", "1>2", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace",                "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "18814", "Neck", "Choker of the Fire Lord",            "PreRaid", "0", "Drop", "Ragnaros", "Molten Core")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge",  "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms",    "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage",   "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32941", "Ring", "Corruptor's Signet",         "Alt", "3", "Quest", "Shartuul", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils",      "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar",              "Alt", "2", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence",         "Alt", "1>3", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",         "Alt Hit", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury",       "Alt Hit", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt", "1>2",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift",              "Alt Hit", "1>2", "Reputation", "Cenarion Expedition Exalted", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring",     "Alt Hit", "1>2", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist",       "PreRaid", "0", "Dungeon Token", "50 Spirit Shard", "Spirit Sage Gartok and Spirit Sage Zran")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet",              "PreRaid", "0", "Reputation", "The Scryers Exalted", "Quartermaster Enuril")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan",        "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe",      "BIS", "3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS", "1>3", "Dungeon Token", "41 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye",            "BIS", "1>3", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "30449", "Trinket", "Void Star Talisman",          "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",      "Alt", "3", "Quest", "Darkmoon Blessings Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents","Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem",           "Alt Hit", "1>2", "Reputation", "The Scryers Revered", "Quartermaster Enuril")

LoonBestInSlot:AddItem(spec, "30910", "MH", "Tempest of Chaos",             "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury",         "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30095", "MH", "Fang of the Leviathan",        "Alt", "2>3", "Drop", "Leotheras the Blind", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest",         "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28802", "MH", "Bloodmaw Magus-Blade",         "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade",          "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28297", "MH", "Gladiator's Spellblade",       "Alt", "2", "PvP", "2739 Points", "Arena")
LoonBestInSlot:AddItem(spec, "30787", "MH", "Illidari-Bane Mageblade",      "Alt Demon", "1", "Quest", "Quenching the Blade", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "31336", "MH", "Blade of Wizardry",            "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29155", "MH", "Stormcaller",                  "PreRaid", "0", "Reputation", "Thrallmar Exalted", "Quartermaster Urgronn, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29153", "MH", "Blade of the Archmage",        "PreRaid", "0", "Reputation", "Honor Hold Exalted", "Logistics Officer Ulrike, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27905", "MH", "Greatsword of Horrid Dreams",  "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade",         "PreRaid", "0", "Profession", "Blacksmithing (365)")

LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets",    "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32361", "OH", "Blind-Seers Icon",             "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone",                  "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29270", "OH", "Flametongue Seal",             "Alt Destruc", "1>3", "Dungeon Token", "25 Badge of Justice", "G'eras - Shattrath City")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack",           "Alt", "1>3", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "29272", "OH", "Orb of the Soul-Eater",        "Alt", "1>3", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities", "Alt", "1>3", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance",    "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32055", "2H", "Merciless Gladiator's War Staff",      "Alt", "2", "PvP", "3261 Points", "Arena")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key",                        "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star",     "BIS", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32343", "Wand", "Wand of Prismatic Focus",        "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk",                "Alt", "1>3", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy",    "Alt Hit", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28783", "Wand", "Eredar Wand of Obliteration",    "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28386", "Wand", "Nether Core's Control Rod",      "Alt", "1>2", "Drop", "Dalliah the Doomsayer", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "22128", "Wand", "Master Firestone",               "PreRaid (Destro)", "0", "Conjured", "Soul Shard")