local spec = LoonBestInSlot:RegisterSpec("Warrior", "Prot")

LoonBestInSlot:AddItem(spec, "32521", "Head", "Faceplate of the Impenetrable",  "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30974", "Head", "Onslaught Greathelm",             "Alt Mit", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30972", "Head", "Onslaught Battle-Helm",           "Alt Thrt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32473", "Head", "Tankatronic Goggles",           "Alt Mit", "2", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "30488", "Head", "Merciless Gladiator's Plate Helm", "Alt Thrt", "2","PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt", "2","Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30115", "Head", "Destroyer Greathelm",            "Alt", "2","Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30120", "Head", "Destroyer Battle-Helm",          "Alt", "2","Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29011", "Head", "Warbringer Greathelm",           "Alt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",    "Alt", "1", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29021", "Head", "Warbringer Battle-Helm",         "Alt Thrt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30731", "Head", "Faceguard of the Endless Watch", "Alt", "1", "Drop", "Doomwalker", "World Boss")
LoonBestInSlot:AddItem(spec, "28593", "Head", "Eternium Greathelm",             "Alt", "1", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28180", "Head", "Myrmidon's Headdress",           "PreRaid", "0", "Quest", "The Warlord's Hideout", "Watcher Jhang, The Steamvault")
LoonBestInSlot:AddItem(spec, "23519", "Head", "Felsteel Helm",                  "PreRaid", "0", "Profession", "Blacksmithing")
LoonBestInSlot:AddItem(spec, "28350", "Head", "Warhelm of the Bold",            "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")
LoonBestInSlot:AddItem(spec, "27408", "Head", "Hope Bearer Helm",               "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector",  "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30979", "Shoulders", "Onslaught Shoulderblades",              "BIS Thrt", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30980", "Shoulders", "Onslaught Shoulderguards",              "BIS Mit", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32250", "Shoulders", "Pauldrons of Abyssal Fury",             "Alt Mit", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30117", "Shoulders", "Destroyer Shoulderblades",              "Alt Thrt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender",  "Alt Thrt", "2","Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30122", "Shoulders", "Destroyer Shoulderguards",              "Alt", "2", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30490", "Shoulders", "Merciless Gladiator's Plate Shoulders", "Alt Thrt", "2", "PvP", "1500 Points", "Arena")
LoonBestInSlot:AddItem(spec, "29023", "Shoulders", "Warbringer Shoulderplates",             "Alt", "1", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",      "Alt Mit", "1", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29016", "Shoulders", "Warbringer Shoulderguards",             "Alt Mit", "1", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28743", "Shoulders", "Mantle of Abrahmis",                    "Alt Mit", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "24546", "Shoulders", "Gladiator's Plate Shoulders",           "Alt Thrt", "1", "PvP", "1500 Arena Points")
LoonBestInSlot:AddItem(spec, "27803", "Shoulders", "Shoulderguards of the Bold",            "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29316", "Shoulders", "Warchief's Mantle",                     "PreRaid", "0",  "Quest", "Return to Andormu", "Caverns of Time")

LoonBestInSlot:AddItem(spec, "34010", "Back", "Pepe's Shroud of Pacification",  "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29925", "Back", "Phoenix-Wing Cloak",             "BIS Mit", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak",        "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness",              "Alt", "1>3", "Profession", "Leatherworking (360)")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",      "Alt Thrt", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28529", "Back", "Royal Cloak of Arathi Kings",    "Alt Thrt", "1>3", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",         "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28660", "Back", "Gilded Thorium Cloak",           "Alt Mit", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29385", "Back", "Farstrider Defender's Cloak",    "Alt", "1", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "27804", "Back", "Devilshark Cape",                "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "24253", "Back", "Cloak of Eternity",              "PreRaid", "0", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "27988", "Back", "Burnoose of Shifting Ages",      "PreRaid", "0", "Drop", "Chrono Lord Deja", "The Black Morass")

LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS Thrt", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30975", "Chest", "Onslaught Breastplate",             "BIS Thrt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30896", "Chest", "Glory of the Defender",             "Alt Mit", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30113", "Chest", "Destroyer Chestguard",              "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2",  "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28485", "Chest", "Bulwark of the Ancient Kings",      "Alt Thrt", "2", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "30486", "Chest", "Merciless Gladiator's Plate Chestpiece", "Alt Thrt", "2", "PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "29012", "Chest", "Warbringer Chestguard",             "Alt", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt", "1", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "24544", "Chest", "Gladiator's Plate Chestpiece",      "Alt Thrt", "1", "PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "28597", "Chest", "Panzar'Thar Breastplate",           "Alt Mit", "1", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28484", "Chest", "Bulwark of Kings",                  "Alt", "1", "Profession", "Armorsmith")
LoonBestInSlot:AddItem(spec, "28205", "Chest", "Breastplate of the Bold",           "PreRaid Mit", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28262", "Chest", "Jade-Skull Breastplate",            "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "25819", "Chest", "Breastplate of the Warbringer",     "PreRaid", "0", "Quest", "Forge Camp: Annihilated", "Nagrand")
LoonBestInSlot:AddItem(spec, "29127", "Chest", "Vindicator's Hauberk",              "PreRaid", "0", "Reputation", "The Aldor - Revered", "Quartermaster Endarin, Shattrath City")

LoonBestInSlot:AddItem(spec, "32232", "Bracers", "Eternium Shell Bracers",              "BIS Mit", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30861", "Bracers", "Furious Shackles",                    "Alt Thrt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication",              "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32818", "Bracers", "Veteran's Plate Bracers",             "Alt Thrt", "1>2", "PvP", "11794 Points - 20 Warsong Gulch Mark", "Honor")
LoonBestInSlot:AddItem(spec, "28996", "Bracers", "Marshal's Plate Bracers",             "Alt Thrt", "1>2", "PvP", "11794 Points - 20 Warsong Gulch Mark", "Honor")
LoonBestInSlot:AddItem(spec, "28502", "Bracers", "Vambraces of Courage",                "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands",                 "Alt Thrt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28167", "Bracers", "Sha'tari Wrought Armguards",          "PreRaid", "0", "Quest", "The Soul Devices", "Auchindoun")
LoonBestInSlot:AddItem(spec, "30225", "Bracers", "Junior Technician 3rd Grade Bracers", "PreRaid", "0", "Quest", "You're Hired!", "Area 52, Netherstorm")
LoonBestInSlot:AddItem(spec, "23538", "Bracers", "Bracers of the Green Fortress",       "PreRaid", "0", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "29463", "Bracers", "Amber Bands of the Aggressor",        "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault Heroic")

LoonBestInSlot:AddItem(spec, "32280", "Gloves", "Gauntlets of Enforcement",         "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32608", "Gloves", "Pillager's Gauntlets",             "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",       "Alt Thrt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29998", "Gloves", "Royal Gauntlets of Silvermoon",    "Alt Thrt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender","Alt 4pc", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30114", "Gloves", "Destroyer Handguards",             "Alt 4pc", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",                "Alt Thrt", "1>2", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "30741", "Gloves", "Topaz-Studded Battlegrips",        "Alt Mit", "1", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28518", "Gloves", "Iron Gauntlets of the Maiden",     "Alt Mit", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29017", "Gloves", "Warbringer Handguards",            "Alt Mit", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender",    "Alt Mit", "1", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "27475", "Gloves", "Gauntlets of the Bold",            "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "23517", "Gloves", "Felsteel Gloves",                  "PreRaid", "0", "Profession", "Blacksmithing (360)")
LoonBestInSlot:AddItem(spec, "29134", "Gloves", "Gauntlets of the Chosen",          "PreRaid", "0", "Reputation", "The Scryers Revered", "Quartermaster Enuril, Shattrath City")
LoonBestInSlot:AddItem(spec, "25788", "Gloves", "Dauntless Handguards",             "PreRaid", "0", "Quest", "Fel Embers", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "30375", "Gloves", "Gauntlets of the Vanquisher",      "PreRaid", "0", "Quest", "Turning Point", "Netherstorm")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths",         "BIS Thrt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32333", "Belt", "Girdle of Stability",                "BIS Mit", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "32342", "Belt", "Girdle of Mighty Resolve",           "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30032", "Belt", "Red Belt of Battle",                 "Alt", "2>3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "30096", "Belt", "Girdle of the Invulnerable",         "Alt Mit", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32805", "Belt", "Veteran's Plate Belt",               "Alt Thrt", "2", "PvP", "17850 Honor Points", "40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "28995", "Belt", "Marshal's Plate Belt",               "Alt", "1", "PvP", "17850 Honor Points", "40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "28566", "Belt", "Crimson Girdle of the Indomitable",  "Alt Mit", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit",          "Alt Thrt", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29238", "Belt", "Lion's Heart Girdle",                "PreRaid", "0", "Drop", "Vazruden the Herald", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "31460", "Belt", "Sha'tari Vindicator's Waistguard",   "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "Netherstorm")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle",                  "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "25922", "Belt", "Fearless Girdle",                    "PreRaid", "0", "Quest", "The Terror of Marshlight Lake/Pursuing Terrorclaw", "Zangarmarsh")

LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector",    "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30977", "Legs", "Onslaught Greaves",                      "BIS Thrt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "32263", "Legs", "Praetorian's Legguards",                 "BIS Mit", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30978", "Legs", "Onslaught Legguards",                    "Alt Mit", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30903", "Legs", "Legguards of Endless Rage",              "Alt Thrt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender",    "Alt", "2", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30116", "Legs", "Destroyer Legguards",                    "Alt", "2", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder",             "Alt Thrt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30489", "Legs", "Merciless Gladiator's Plate Legguards",  "Alt", "2", "PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "30121", "Legs", "Destroyer Greaves",                      "Alt Thrt", "2", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28621", "Legs", "Wrynn Dynasty Greaves",                  "Alt Mit", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "24547", "Legs", "Gladiator's Plate Legguards",            "Alt Thrt", "1", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "29015", "Legs", "Warbringer Legguards",                   "Alt Mit", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29184", "Legs", "Timewarden's Leggings",                  "PreRaid", "0", "Reputation", "Keepers of Time - Revered", "Alurmi, Tanaris")
LoonBestInSlot:AddItem(spec, "23518", "Legs", "Felsteel Leggings",                      "PreRaid", "0", "Profession", "Blacksmithing (360)")
LoonBestInSlot:AddItem(spec, "27527", "Legs", "Greaves of the Shatterer",               "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "28175", "Legs", "Mag'hari Warlord's Legplates",           "PreRaid", "0", "Quest", "Hero of the Mag'har (Horde only)", "Nagrand")
LoonBestInSlot:AddItem(spec, "29783", "Legs", "Legguards of the Resolute Defender",     "PreRaid", "0", "Quest", "Destroy Naberius!", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion",       "BIS Thrt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "32268", "Feet", "Myrmidon's Treads",              "BIS Mit", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "32793", "Feet", "Veteran's Plate Greaves",        "Alt", "2", "PvP", "8925 Points - 40 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "32267", "Feet", "Boots of the Resilient",         "Alt Mit", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency",        "Alt Thrt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28747", "Feet", "Battlescar Boots",               "Alt Mit", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28997", "Feet", "Marshal's Plate Greaves",        "Alt Thrt", "1", "PvP", "17850  Honor Points", "40 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "30641", "Feet", "Boots of Elusion",               "Alt Mit", "1", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "29239", "Feet", "Eaglecrest Warboots",            "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace Heroic")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves",       "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28318", "Feet", "Obsidian Clodstompers",          "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "30386", "Feet", "Bloodguard's Greaves",           "PreRaid", "0", "Quest", "Information Gathering", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32362", "Neck", "Pendant of Titans",              "BIS", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades",      "Alt", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "30099", "Neck", "Frayed Tether of the Drowned",   "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "33066", "Neck", "Veteran's Pendant of Triumph",   "Alt", "2>3", "PvP", "15300 Points - 10 Eye of the Storm Marks", "Honor")
LoonBestInSlot:AddItem(spec, "29386", "Neck", "Necklace of the Juggernaut",     "Alt", "1", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28516", "Neck", "Barbed Choker of Discipline",    "Alt Mit", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",           "Alt Thrt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28244", "Neck", "Pendant of Triumph",             "Alt Thrt", "1", "PvP", "18000 Honor Points, 10 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "30378", "Neck", "Thalodien's Charm",              "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29336", "Neck", "Mark of the Ravenguard",         "PreRaid", "0", "Quest", "Brother Against Brother", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "31696", "Neck", "Natasha's Battle Chain",         "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",                  "BIS Thrt", "1>3", "Reputation", "Nakodu", "Lower City (Exalted)")
LoonBestInSlot:AddItem(spec, "29296", "Ring", "Band of Eternity",                       "BIS Mit", "3", "Reputation", "Soridormi", "The Scale of the Sands (Revered)")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent",               "Alt Thrt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion",           "Alt Thrt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32261", "Ring", "Band of the Abyssal Lord",               "Alt Mit", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29279", "Ring", "Violet Signet of the Great Protector",   "Alt Mit", "1>3", "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "30083", "Ring", "Ring of Sundered Souls",                 "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest",             "Alt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",                     "Alt Mit", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28675", "Ring", "Shermanar Great-Ring",                   "Alt Mit", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28792", "Ring", "A'dal's Signet of Defense",              "Alt Mit", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin",   "Alt Thrt", "1>2", "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "29384", "Ring", "Ring of Unyielding Force",               "Alt Mit", "1", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",                   "Alt Thrt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred",          "Alt Thrt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28407", "Ring", "Elementium Band of the Sentry",          "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "27436", "Ring", "Iron Band of the Unbreakable",           "PreRaid", "0", "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "27822", "Ring", "Crystal Band of Valor",                  "PreRaid Thrt", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "30006", "Ring", "Wind Trader's Band",                     "PreRaid", "0", "Quest", "Dealing with the Overmaster", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31078", "Ring", "Protector's Mark of the Redemption",     "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "31858", "Trinket", "Darkmoon Card: Vengeance",        "BIS", "3", "Quest", "Darkmoon Furies Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "31859", "Trinket", "Darkmoon Card: Madness",          "BIS", "3", "Quest", "Darkmoon Lunacy Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "32501", "Trinket", "Shadowmoon Insignia",             "Alt Mit", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "32864", "Trinket", "Commander's Badge",               "Alt Mit", "3", "Quest", "Hail, Commander!", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28121", "Trinket", "Icon of Unyielding Courage",      "Alt Thrt", "1>3", "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "23836", "Trinket", "Goblin Rocket Launcher",          "Alt Mit", "1>3", "Profession", "Engineering (360)")
LoonBestInSlot:AddItem(spec, "23835", "Trinket", "Gnomish Poultryizer",             "Alt Mit", "1>3", "Profession", "Engineering (360)")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial",            "Alt Thrt", "1>3", "Drop", "Julianne", "Karazhan")
LoonBestInSlot:AddItem(spec, "29181", "Trinket", "Timelapse Shard",                 "Alt Mit", "1>3", "Reputation", "Keepers of Time - Exalted", "Alurmi, Tanaris")
LoonBestInSlot:AddItem(spec, "31113", "Trinket", "Violet Badge",                    "Alt Mit", "1>2", "Dungeon Token", "41 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "27770", "Trinket", "Argussian Compass",               "Alt Mit", "1>2", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "30620", "Trinket", "Spyglass of the Hidden Fleet",    "Alt", "2", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29387", "Trinket", "Gnomeregan Auto-Blocker 600",     "Alt", "1", "Dungeon Token", "41 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "27891", "Trinket", "Adamantine Figurine",             "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "30300", "Trinket", "Dabiri's Enigma",                 "PreRaid", "0", "Quest", "Dimensius the All-Devouring", "Netherstorm")
LoonBestInSlot:AddItem(spec, "28042", "Trinket", "Regal Protectorate",              "PreRaid", "0", "Quest", "Overlord/Cruel's Intentions", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27529", "Trinket", "Figurine of the Colossus",        "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "32254", "MH", "The Brutalizer",               "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32369", "MH", "Blade of Savagery",            "BIS(Human)", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30874", "MH", "The Unbreakable Will",         "BIS Mit", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32943", "MH", "Swiftsteel Bludgeon",          "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "28427", "MH", "Blazefury(Blazeguard)",        "Alt", "1>3", "Profession", "Master Swordsmith")
LoonBestInSlot:AddItem(spec, "30058", "MH", "Mallet of the Tides",          "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30103", "MH", "Fang of Vashj",                "Alt", "2", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28749", "MH", "King's Defender",              "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29165", "MH", "Warbringer",                   "Alt(Orc)", "1>2", "Reputation", "Thrallmar - Exalted", "Logistics Officer Ulrike, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29362", "MH", "The Sun Eater",                "Alt Mit", "1>2", "Drop", "Pathaleon the Calculator", "The Mechanar (Heroic)")
LoonBestInSlot:AddItem(spec, "29156", "MH", "Honor's Call",                 "PreRaid", "0", "Reputation", "Honor Hold - Exalted", "Quartermaster Urgronn, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27980", "MH", "Terokk's Nightmace",           "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "28189", "MH", "Latro's Shifting Sword",       "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "31071", "MH", "Grom'tor's Charge",            "PreRaid", "0", "Quest", "The Cipher of Damnation", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32375", "Shield", "Bulwark of Azzinoth",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30889", "Shield", "Kaz'rogal's Hardened Heart",       "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender",           "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "32045", "Shield", "Merciless Gladiator's Shield Wall", "Alt", "2", "PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness",  "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28358", "Shield", "Gladiator's Shield Wall",          "Alt", "1", "PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra",         "PreRaid", "0", "Dungeon Token", "33 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar",             "PreRaid", "0", "Reputation", "The Sha'tar", "Exalted")
LoonBestInSlot:AddItem(spec, "32082", "Shield", "The Fel Barrier",                  "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird",             "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous",  "PreRaid", "0", "Drop", "Ambassador Hellmaw", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28166", "Shield", "Shield of the Void",               "PreRaid", "0", "Drop", "Pandemonius", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "31490", "Shield", "Netherwing Protector's Shield",    "PreRaid", "0", "Quest", "Ally of the Netherwing", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32253", "Ranged", "Legionkiller",                     "MIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32756", "Ranged", "Gyro-Balanced Khorium Destroyer",  "BIS Mit", "3", "Profession", "Engineering (375)")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol",            "MIS Thrt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30025", "Ranged", "Serpentshrine Shuriken",           "Alt", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle",           "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "32645", "Ranged", "Crystalline Crossbow",             "Alt Hit", "2", "Reputation", "Ogri'la (Exalted)", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "28319", "Ranged", "Gladiator's War Edge",             "Alt", "1", "PvP", "1000 Points", "Arena")
LoonBestInSlot:AddItem(spec, "28826", "Ranged", "Shuriken of Negation",             "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30227", "Ranged", "Mark V's Throwing Star",           "PreRaid", "0", "Quest", "Mark V is Alive!", "Netherstorm")
LoonBestInSlot:AddItem(spec, "32832", "Ranged", "Scout's Throwing Knives",          "PreRaid", "0", "Quest", "Terokk's Downfall", "Terokkar Forest")
LoonBestInSlot:AddItem(spec, "29115", "Ranged", "Consortium Blaster",               "PreRaid", "0", "Reputation", "The Consortium", "Revered")
LoonBestInSlot:AddItem(spec, "28258", "Ranged", "Nethershrike",                     "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")