local spec = LoonBestInSlot:RegisterSpec("Warrior", "DPS")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",          "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32373", "Head", "Helm of the Illidari Shatterer",     "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30972", "Head", "Onslaught Battle-Helm",              "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector",    "Alt", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30120", "Head", "Destroyer Battle-Helm",              "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender",    "Alt", "2>3","Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles",           "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",        "Alt", "1>3", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29021", "Head", "Warbringer Battle-Helm",             "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29983", "Head", "Fel-Steel Warhelm",                  "Alt", "2", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver",               "Alt", "1>2", "Dungeon Token", "50 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw",                   "PreRaid", "0", "Quest", "The Warlord's Hideout", "Watcher Jhang, Zangarmarsh")
LoonBestInSlot:AddItem(spec, "31105", "Head", "Overlord's Helmet of Second Sight",  "PreRaid", "0", "Quest", "Teron Gorefiend, I am...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm",                   "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "30979", "Shoulders", "Onslaught Shoulderblades",              "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector",  "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32570", "Shoulders", "Swiftsteel Shoulders",                  "Alt", "3", "Profession", "Blacksmith(375)")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",          "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30122", "Shoulders", "Destroyer Shoulderblades",              "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender",  "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30053", "Shoulders", "Pauldrons of the Wardancer",            "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29023", "Shoulders", "Warbringer Shoulderplates",             "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",      "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30740", "Shoulders", "Ripfiend Shoulderplates",               "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "33173", "Shoulders", "Ragesteel Shoulders",                   "PreRaid", "0", "Profession", "Blacksmithing (350)")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",              "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde",                   "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets",           "PreRaid", "0", "Quest", "Fel Embers", "Magus Zabraxis, Hellfire Peninsula")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape",   "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness",              "BIS", "3", "Profession", "Leatherworking (360)")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap",                 "Alt", "1>3", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",         "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak",        "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30729", "Back", "Black-Iron Battlecloak",         "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",      "Alt", "1", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud",          "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter",           "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "30975", "Chest", "Onslaught Breastplate",                 "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard",                   "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30118", "Chest", "Destroyer Breastplate",                 "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest",               "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30102", "Chest", "Krakken-Heart Breastplate",             "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29019", "Chest", "Warbringer Breastplate",                "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender",     "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic",                     "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "24544", "Chest", "Gladiator's Plate Chestpiece",          "Alt", "1", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "23522", "Chest", "Ragesteel Breastplate",                 "PreRaid", "0", "Profession", "Blacksmithing (350)")
LoonBestInSlot:AddItem(spec, "31548", "Chest", "Blackened Chestplate",                  "PreRaid", "0", "Quest", "Showdown", "Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs",                "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands",             "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30861", "Bracers", "Furious Shackles",            "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication",      "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands",      "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands",         "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers",      "Alt", "1", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "28381", "Bracers", "General's Plate Bracers",     "Alt", "1", "PvP", "11794 Honor points, 20 Warsong Gulch Mark")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards",   "PreRaid", "0", "Quest", "The Soul Devices", "Spy To'gun, Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "30399", "Bracers", "Nightstalker's Wristguards",  "PreRaid", "0", "Quest", "Down with Daelis", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32278", "Gloves", "Grips of Silent Justice",          "BIS", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30969", "Gloves", "Onslaught Gauntlets",              "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "Alt", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32608", "Gloves", "Pillager's Gauntlets",             "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "28824", "Gloves", "Gauntlets of Martial Perfection",  "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",       "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30119", "Gloves", "Destroyer Gauntlets",              "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender","Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29020", "Gloves", "Warbringer Gauntlets",             "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender",    "Alt", "1", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",                "Alt", "1", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves",               "PreRaid", "0", "Profession", "Leatherworking (340)")
LoonBestInSlot:AddItem(spec, "27497", "Gloves", "Doomplate Gauntlets",              "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace")
LoonBestInSlot:AddItem(spec, "23520", "Gloves", "Ragesteel Gloves",                 "PreRaid", "0", "Profession", "Blacksmithing (365)")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30032", "Belt", "Red Belt of Battle",         "Alt", "2>3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit",  "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",      "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle",          "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer",  "PreRaid", "0", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "31464", "Belt", "Naaru Belt of Precision",    "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "A'dal, Shattrath City")

LoonBestInSlot:AddItem(spec, "32341", "Legs", "Leggings of Divine Retribution", "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons",      "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30903", "Legs", "Legguards of Endless Rage",      "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30977", "Legs", "Onslaught Greaves",              "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "Alt", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent",   "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder",     "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30121", "Legs", "Destroyer Greaves",              "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards",             "Alt", "1>2", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "30739", "Legs", "Scaled Greaves of the Marksman", "Alt", "1", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29022", "Legs", "Warbringer Greaves",             "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings",           "PreRaid", "0", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings",             "PreRaid", "0", "Quest", "Special Delivery to Shattrath City", "Shattrath City")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings",        "PreRaid", "0", "Quest", "Showdown - Baron Sablemane/Showdown", "Rexxar, Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion",   "BIS", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration",   "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency",    "Alt", "1>3", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots",         "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",       "Alt", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots",          "Alt", "1", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust",        "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves",   "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots",    "PreRaid", "0", "Quest", "A Fate Worse Than Death", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades",          "BIS", "3", "Drop", "Supremus", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares",       "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous",            "Alt", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                     "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem",      "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30059", "Neck", "Choker of Animalistic Fury",         "Alt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",              "Alt", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "29349", "Neck", "Adamantine Chain of the Unbroken",   "Alt Arms", "1>2", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",               "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker",                   "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "27546", "Neck", "Traitor's Noose",                    "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens (Heroic)")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring",                  "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring",           "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation",                    "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion",           "Alt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General",             "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest",             "Alt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality",                      "Alt", "2", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality",            "Alt", "1>2", "Drop", "Yor", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity",                    "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",               "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred",          "Alt Arms", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords",                "Alt", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",                  "Alt", "1>2", "Reputation", "Nakodu", "Lower City (Exalted)")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",                   "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin",   "Alt", "1",  "Reputation", "Karazhan", "Violet Eye (Exalted)")
LoonBestInSlot:AddItem(spec, "28323", "Ring", "Ring of Umbral Doom",                    "PreRaid", "0", "Drop", "Thorngrin the Tender", "The Botanica")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption",        "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Thane Yoregar / Overlord Or'barokh, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",         "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",              "BIS", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",                "BIS", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",                "Alt", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "30446", "Trinket", "Solarian's Sapphire",             "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller",     "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",          "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")

LoonBestInSlot:AddItem(spec, "32837", "MH", "Warglaive of Azzinoth",    "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike",             "Alt", "2>3", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw",                "Alt", "1>2", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King",      "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30082", "MH", "Talon of Azshara",         "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32052", "MH", "Merciless Gladiator's Slicer", "Alt", "2", "PvP", "2625 Points", "Arena")
LoonBestInSlot:AddItem(spec, "28437", "MH", "Drakefist Hammer",         "Alt", "1", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "28657", "MH", "Fool's Bane",              "Alt", "1", "Drop","Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "28767", "MH", "The Decapitator",          "Alt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "27490", "MH", "Firebrand Battleaxe",      "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace")

LoonBestInSlot:AddItem(spec, "32838", "OH", "Warglaive of Azzinoth",        "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30881", "OH", "Blade of Infamy",              "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30082", "OH", "Talon of Azshara",             "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29924", "OH", "Netherbane",                   "Alt(Orc)", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29996", "OH", "Rod of the Sun King",          "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32052", "OH", "Merciless Gladiator's Slicer", "Alt", "2", "PvP", "2625 Points", "Arena")
LoonBestInSlot:AddItem(spec, "30733", "OH", "Hope Ender",                   "Alt", "1", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28729", "OH", "Spiteblade",                   "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "23542", "OH", "Fel Edged Battleaxe",          "PreRaid(Orc)", "1", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "28189", "OH", "Latro's Shifting Sword",       "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")

LoonBestInSlot:AddItem(spec, "30902", "2H", "Cataclysm's Edge",                 "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32348", "2H", "Soul Cleaver",                     "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix",         "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28430", "2H", "Lionheart Executioner(Champion)",  "Alt", "2", "Profession", "Master Swordsmith (Blacksmithing)")
LoonBestInSlot:AddItem(spec, "28436", "2H", "Bloodmoon",                        "Alt(Orc)", "2", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "24550", "2H", "Merciless Gladiator's Greatsword", "Alt", "2", "PvP", "2750 Points", "Arena")
LoonBestInSlot:AddItem(spec, "28573", "2H", "Despair",                          "Alt", "1>2", "Drop", "Julianne", "Karazhan")
LoonBestInSlot:AddItem(spec, "28773", "2H", "Gorehowl",                         "Alt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade",                    "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28441", "2H", "Deep Thunder",                     "PreRaid", "0", "Profession", "Master Hammersmith (Blacksmithing)")
LoonBestInSlot:AddItem(spec, "28428", "2H", "Lionheart Blade",                  "PreRaid", "0", "Profession", "Master Swordsmith (Blacksmithing)")

LoonBestInSlot:AddItem(spec, "32326", "Ranged", "Twisted Blades of Zarak",      "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow",        "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix",   "BIS", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle",       "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30279", "Ranged", "Mama's Insurance",             "Alt", "1>2", "Quest", "Declawing Doomclaw", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29211", "Ranged", "Fitz's Throwing Axe",          "PreRaid", "0", "Quest", "The Ultimate Bloodsport", "Nagrand")

LoonBestInSlot:AddItem(spec, "28825", "Shield", "Aldori Legacy Defender",           "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28606", "Shield", "Shield of Impenetrable Darkness",  "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "32045", "Shield", "Merciless Gladiator's Shield Wall", "Alt", "2", "PvP", "1875 Points", "Arena")
LoonBestInSlot:AddItem(spec, "29176", "Shield", "Crest of the Sha'tar",             "PreRaid", "0", "Reputation", "The Sha'tar", "Exalted")
LoonBestInSlot:AddItem(spec, "29266", "Shield", "Azure-Shield of Coldarra",         "PreRaid", "0", "Dungeon Token", "33 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28316", "Shield", "Aegis of the Sunbird",             "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "27887", "Shield", "Platinum Shield of the Valorous",  "PreRaid", "0", "Drop", "Ambassador Hellmaw", "Shadow Labyrinth")