LBIS.EnchantSources =
{
    [2823] = { Name = "Deadly Poison", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Rogue Skill"], SourceLocation = "", TextureId = "2892" },
    [8679] = { Name = "Instant Poison", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Rogue Skill"], SourceLocation = "", TextureId = "6947" },
    [44529] = { Name = "Enchant Gloves - Major Agility", DesignId = "38967", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [44590] = { Name = "Enchant Cloak - Superior Shadow Resistance", DesignId = "37334", ScrollId = "0", Source = LBIS.L["Cultist Shard Watcher"], SourceLocation = LBIS.L["Icecrown"], TextureId = "" },
    [47901] = { Name = "Enchant Boots - Tuskarr's Vitality", DesignId = "44491", ScrollId = "0", Source = LBIS.L["Shard Trader"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [52763] = { Name = "Arc Weld", DesignId = "99999", ScrollId = "0", Source = "unknown", SourceLocation = "unknown", TextureId = "" },
    [53343] = { Name = "Rune of Razorice", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Death Knight Skill"], SourceLocation = "", TextureId = "" },
    [53344] = { Name = "Rune of the Fallen Crusader", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Death Knight Skill"], SourceLocation = "", TextureId = "" },
    [55002] = { Name = "Flexweave Underlay", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Dalaran"], TextureId = "41111" },
    [55016] = { Name = "Nitro Boosts", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Engineering Trainer"], SourceLocation = LBIS.L["Dalaran"], TextureId = "41118" },
    [55628] = { Name = "Socket Bracer", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Blacksmithing Trainer"], SourceLocation = "", TextureId = "" },
    [55641] = { Name = "Socket Gloves", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Blacksmithing Trainer"], SourceLocation = "", TextureId = "" },
    [60663] = { Name = "Enchant Cloak - Major Agility", DesignId = "44457", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [60692] = { Name = "Enchant Chest - Powerful Stats", DesignId = "44489", ScrollId = "0", Source = LBIS.L["Shard Trader"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [62256] = { Name = "Enchant Bracer - Major Stamina", DesignId = "44944", ScrollId = "0", Source = LBIS.L["Shard Trader"], SourceLocation = LBIS.L["Dalaran"], TextureId = "" },
    [74132] = { Name = "Enchant Gloves - Mastery", DesignId = "52687", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74189] = { Name = "Enchant Boots - Earthen Vitality", DesignId = "52743", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74198] = { Name = "Enchant Gloves - Haste", DesignId = "52749", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74199] = { Name = "Enchant Boots - Haste", DesignId = "52750", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74213] = { Name = "Enchant Boots - Major Agility", DesignId = "52757", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74215] = { Name = "Enchant Ring - Strength", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74216] = { Name = "Enchant Ring - Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74217] = { Name = "Enchant Ring - Intellect", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74218] = { Name = "Enchant Ring - Greater Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74220] = { Name = "Enchant Gloves - Greater Expertise", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74225] = { Name = "Enchant Weapon - Heartsong", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74226] = { Name = "Enchant Shield - Mastery", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74232] = { Name = "Enchant Bracer - Precision", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74234] = { Name = "Enchant Cloak - Protection", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74235] = { Name = "Enchant Off-Hand - Superior Intellect", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74236] = { Name = "Enchant Boots - Precision", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74237] = { Name = "Enchant Bracer - Exceptional Spirit", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74238] = { Name = "Enchant Boots - Mastery", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74239] = { Name = "Enchant Bracer - Greater Expertise", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74240] = { Name = "Enchant Cloak - Greater Intellect", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [74242] = { Name = "Enchant Weapon - Power Torrent", DesignId = "52733", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74244] = { Name = "Enchant Weapon - Windwalk", DesignId = "52735", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74246] = { Name = "Enchant Weapon - Landslide", DesignId = "52736", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74247] = { Name = "Enchant Cloak - Greater Critical Strike", DesignId = "52737", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74250] = { Name = "Enchant Chest - Peerless Stats", DesignId = "52739", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74251] = { Name = "Enchant Chest - Greater Stamina", DesignId = "52740", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74253] = { Name = "Enchant Boots - Lavawalker", DesignId = "64412", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74254] = { Name = "Enchant Gloves - Mighty Strength", DesignId = "64415", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [74255] = { Name = "Enchant Gloves - Greater Mastery", DesignId = "64414", ScrollId = "0", Source = LBIS.L["Enchanting Supplies"], SourceLocation = "", TextureId = "" },
    [75154] = { Name = "Master's Spellthread", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [75172] = { Name = "Lightweave Embroidery", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [75178] = { Name = "Swordguard Embroidery", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Tailoring Trainer"], SourceLocation = "", TextureId = "" },
    [78166] = { Name = "Heavy Savage Armor Kit", DesignId = "56517", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "56517" },
    [78171] = { Name = "Dragonscale Leg Armor", DesignId = "56550", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "56550" },
    [82175] = { Name = "Synapse Springs", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [82177] = { Name = "Quickflip Deflection Plates", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [84427] = { Name = "Grounded Plasma Shield", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Engineering Trainer"], SourceLocation = "", TextureId = "" },
    [85007] = { Name = "Draconic Embossment - Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [85008] = { Name = "Draconic Embossment - Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [85010] = { Name = "Draconic Embossment - Intellect", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
    [86375] = { Name = "Swiftsteel Inscription", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [86402] = { Name = "Inscription of the Earth Prince", DesignId = "99999", ScrollId = "0", LBIS.L["Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [86403] = { Name = "Felfire Inscription", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Inscription Trainer"], SourceLocation = "", TextureId = "" },
    [86907] = { Name = "Greater Inscription of Shattered Crystal", DesignId = "62346", ScrollId = "0", Source = LBIS.L["Therazane - Exalted"], SourceLocation = LBIS.L["Deepholm"], TextureId = "" },
    [86931] = { Name = "Arcanum of the Earthern Ring", DesignId = "62366", ScrollId = "0", Source = LBIS.L["Earthen Ring - Revered"], SourceLocation = LBIS.L["Shimmering Expanse"], TextureId = "" },
    [86932] = { Name = "Arcanum of Hyjal", DesignId = "62367", ScrollId = "0", Source = LBIS.L["Guardians of Hyjal - Revered"], SourceLocation = LBIS.L["Mount Hyjal"], TextureId = "" },
    [86934] = { Name = "Arcanum of Ramkahen", DesignId = "62369", ScrollId = "0", Source = LBIS.L["Ramkahen - Revered"], SourceLocation = LBIS.L["Uldum"], TextureId = "" },
    [95471] = { Name = "Enchant 2H Weapon - Mighty Agility", DesignId = "68134", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [96261] = { Name = "Enchant Bracer - Major Strength", DesignId = "68788", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [96262] = { Name = "Enchant Bracer - Mighty Intellect", DesignId = "68789", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [96264] = { Name = "Enchant Bracer - Agility", DesignId = "68787", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [101600] = { Name = "Drakehide Leg Reinforcements", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "" },
}
