LBIS.EnchantSources =
{
    [2833] = { Name = "Heavy Armor Kit", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "4265" },
    [6296] = { Name = "Fiery Blaze Enchantment", DesignId = "5421", ScrollId = "0", Source = LBIS.L["Sigrun Ironhew"], SourceLocation = LBIS.L["Badlands"], TextureId = "5421" },
    [7218] = { Name = "Weapon Counterweight", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Blacksmithing Trainer"], SourceLocation = "", TextureId = "6043" },
    [7221] = { Name = "Iron Shield Spike", DesignId = "6044", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "6042" },
    [7222] = { Name = "Iron Counterweight", DesignId = "6045", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "6043" },
    [7224] = { Name = "Steel Weapon Chain", DesignId = "6046", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "6041" },
    [7779] = { Name = "Enchant Bracer - Minor Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [7786] = { Name = "Enchant Weapon - Minor Beastslayer", DesignId = "6348", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [7793] = { Name = "Enchant 2H Weapon - Lesser Intellect", DesignId = "6349", ScrollId = "0", Source = LBIS.L["Enchanting Vendor"], SourceLocation = "", TextureId = "" },
    [7857] = { Name = "Enchant Chest - Health", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [7859] = { Name = "Enchant Bracer - Lesser Spirit", DesignId = "6375", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [7863] = { Name = "Enchant Boots - Minor Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [7867] = { Name = "Enchant Boots - Minor Agility", DesignId = "6377", ScrollId = "0", Source = LBIS.L["Zixil"], SourceLocation = LBIS.L["Hillsbrad Foothills"], TextureId = "" },
    [9939] = { Name = "Mithril Shield Spike", DesignId = "7976", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "7967" },
    [10344] = { Name = "Thick Armor Kit", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "8173" },
    [13378] = { Name = "Enchant Shield - Minor Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13380] = { Name = "Enchant 2H Weapon - Lesser Spirit", DesignId = "11038", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [13419] = { Name = "Enchant Cloak - Minor Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["World Drop and Vendors"], SourceLocation = "", TextureId = "" },
    [13421] = { Name = "Enchant Cloak - Lesser Protection", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13501] = { Name = "Enchant Bracer - Lesser Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13503] = { Name = "Enchant Weapon - Lesser Striking", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13522] = { Name = "Enchant Cloak - Lesser Shadow Resistance", DesignId = "99999", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [13529] = { Name = "Enchant 2H Weapon - Lesser Impact", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13536] = { Name = "Enchant Bracer - Lesser Strength", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Trade Vendors"], SourceLocation = LBIS.L["Ashenvale and Stonetalon"], TextureId = "" },
    [13538] = { Name = "Enchant Chest - Lesser Absorption", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13607] = { Name = "Enchant Chest - Mana", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13622] = { Name = "Enchant Bracer - Lesser Intellect", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13626] = { Name = "Enchant Chest - Minor Stats", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13637] = { Name = "Enchant Boots - Lesser Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13648] = { Name = "Enchant Bracer - Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13657] = { Name = "Enchant Cloak - Fire Resistance", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13661] = { Name = "Enchant Bracer - Strength", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13663] = { Name = "Enchant Chest - Greater Mana", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13689] = { Name = "Enchant Shield - Lesser Block", DesignId = "11168", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [13693] = { Name = "Enchant Weapon - Striking", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13695] = { Name = "Enchant 2H Weapon - Impact", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13700] = { Name = "Enchant Chest - Lesser Stats", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13746] = { Name = "Enchant Cloak - Greater Defense", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13794] = { Name = "Enchant Cloak - Resistance", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13815] = { Name = "Enchant Gloves - Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13817] = { Name = "Enchant Shield - Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13822] = { Name = "Enchant Bracer - Intellect", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13836] = { Name = "Enchant Boots - Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13882] = { Name = "Enchant Cloak - Lesser Agility", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13887] = { Name = "Enchant Gloves - Strength", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13890] = { Name = "Enchant Boots - Minor Speed", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Enchanting Trainer"], SourceLocation = "", TextureId = "" },
    [13898] = { Name = "Enchant Weapon - Fiery Weapon", DesignId = "11207", ScrollId = "0", Source = LBIS.L["Pyromancer Loregrain"], SourceLocation = LBIS.L["Blackrock Depths"], TextureId = "" },
    [13939] = { Name = "Enchant Bracer - Greater Strength", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Master Enchanting Trainer"], SourceLocation = LBIS.L["Uldaman"], TextureId = "" },
    [13941] = { Name = "Enchant Chest - Stats", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Master Enchanting Trainer"], SourceLocation = LBIS.L["Uldaman"], TextureId = "" },
    [13945] = { Name = "Enchant Bracer - Greater Stamina", DesignId = "99999", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "11225" },
    [13948] = { Name = "Enchant Gloves - Minor Haste", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Master Enchanting Trainer"], SourceLocation = LBIS.L["Uldaman"], TextureId = "" },
    [15340] = { Name = "Lesser Arcanum of Rumination", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Mathredis Firestar (Librams)"], SourceLocation = LBIS.L["Burning Steppes"], TextureId = "11622" },
    [15394] = { Name = "Lesser Arcane Amalgamation", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Mathredis Firestar (Librams)"], SourceLocation = LBIS.L["Burning Steppes"], TextureId = "11644" },
    [15397] = { Name = "Lesser Arcane Amalgamation", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Mathredis Firestar (Librams)"], SourceLocation = LBIS.L["Burning Steppes"], TextureId = "11645" },
    [15400] = { Name = "Lesser Arcanum of Voracity", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Mathredis Firestar (Librams)"], SourceLocation = LBIS.L["Burning Steppes"], TextureId = "11646" },
    [15402] = { Name = "Lesser Arcanum of Voracity", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Mathredis Firestar (Librams)"], SourceLocation = LBIS.L["Burning Steppes"], TextureId = "11647" },
    [15404] = { Name = "Lesser Arcane Amalgamation", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Mathredis Firestar (Librams)"], SourceLocation = LBIS.L["Burning Steppes"], TextureId = "11648" },
    [16623] = { Name = "Thorium Shield Spike", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Blacksmithing Trainer"], SourceLocation = "", TextureId = "12645" },
    [19057] = { Name = "Rugged Armor Kit", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "15564" },
    [19058] = { Name = "Rugged Armor Kit", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Leatherworking Trainer"], SourceLocation = "", TextureId = "15564" },
    [20008] = { Name = "Enchant Bracer - Greater Intellect", DesignId = "16214", ScrollId = "0", Source = LBIS.L["Vilebranch Shadowcaster"], SourceLocation = LBIS.L["The Hinterlands"], TextureId = "" },
    [20009] = { Name = "Enchant Bracer - Superior Spirit", DesignId = "16218", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [20010] = { Name = "Enchant Bracer - Superior Strength", DesignId = "16246", ScrollId = "0", Source = LBIS.L["Deadwind Warlock"], SourceLocation = LBIS.L["Deadwind Pass"], TextureId = "" },
    [20011] = { Name = "Enchant Bracer - Superior Stamina", DesignId = "16251", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [20012] = { Name = "Enchant Gloves - Greater Agility", DesignId = "16219", ScrollId = "0", Source = LBIS.L["Legashi Rogue"], SourceLocation = LBIS.L["Azshara"], TextureId = "" },
    [20013] = { Name = "Enchant Gloves - Greater Strength", DesignId = "16244", ScrollId = "0", Source = LBIS.L["Spirestone Mystic"], SourceLocation = LBIS.L["Blackrock Spire"], TextureId = "" },
    [20014] = { Name = "Enchant Cloak - Greater Resistance", DesignId = "16216", ScrollId = "0", Source = LBIS.L["Atal'ai Witch Doctor"], SourceLocation = LBIS.L["Sunken Temple"], TextureId = "" },
    [20015] = { Name = "Enchant Cloak - Superior Defense", DesignId = "16224", ScrollId = "0", Source = LBIS.L["Lorelae Wintersong"], SourceLocation = LBIS.L["Moonglade"], TextureId = "" },
    [20017] = { Name = "Enchant Shield - Greater Stamina", DesignId = "16217", ScrollId = "0", Source = LBIS.L["Daniel Bartlett"].." & "..LBIS.L["Mythrin'dir"], SourceLocation = LBIS.L["Undercity"].." & "..LBIS.L["Darnassus"], TextureId = "" },
    [20020] = { Name = "Enchant Boots - Greater Stamina", DesignId = "16215", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [20023] = { Name = "Enchant Boots - Greater Agility", DesignId = "16245", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [20025] = { Name = "Enchant Chest - Greater Stats", DesignId = "16253", ScrollId = "0", Source = LBIS.L["World Drop"], SourceLocation = "", TextureId = "" },
    [20026] = { Name = "Enchant Chest - Major Health", DesignId = "16221", ScrollId = "0", Source = LBIS.L["Qia"], SourceLocation = LBIS.L["Winterspring"], TextureId = "" },
    [20028] = { Name = "Enchant Chest - Major Mana", DesignId = "16242", ScrollId = "0", Source = LBIS.L["Scarlet Enchanter"], SourceLocation = LBIS.L["Eastern Plaguelands"], TextureId = "" },
    [20031] = { Name = "Enchant Weapon - Superior Striking", DesignId = "16250", ScrollId = "0", Source = LBIS.L["Trash Drop"], SourceLocation = LBIS.L["Blackrock Spire"], TextureId = "" },
    [20034] = { Name = "Enchant Weapon - Crusader", DesignId = "16252", ScrollId = "0", Source = LBIS.L["Scarlet Spellbinder"], SourceLocation = LBIS.L["Western Plaguelands"], TextureId = "" },
    [20081] = { Name = "Formula: Enchant Bracer - Superior Strength", DesignId = "16246", ScrollId = "0", Source = LBIS.L["Deadwind Warlock"], SourceLocation = LBIS.L["Deadwind Pass"], TextureId = "" },
    [21931] = { Name = "Enchant Weapon - Winter's Might", DesignId = "17725", ScrollId = "0", Source = LBIS.L["Present"], SourceLocation = LBIS.L["Winter Veil (Seasonal)"], TextureId = "" },
    [22749] = { Name = "Enchant Weapon - Spell Power", DesignId = "18259", ScrollId = "0", Source = LBIS.L["Boss Drop"], SourceLocation = LBIS.L["Molten Core"], TextureId = "" },
    [22750] = { Name = "Enchant Weapon - Healing Power", DesignId = "18260", ScrollId = "0", Source = LBIS.L["Boss Drop"], SourceLocation = LBIS.L["Molten Core"], TextureId = "" },
    [22840] = { Name = "Arcanum of Rapidity", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Lorekeeper Lydros (Librams)"], SourceLocation = LBIS.L["Dire Maul"], TextureId = "18329" },
    [22844] = { Name = "Arcanum of Focus", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Lorekeeper Lydros"], SourceLocation = LBIS.L["Dire Maul"], TextureId = "18330" },
    [23799] = { Name = "Enchant Weapon - Strength", DesignId = "19444", ScrollId = "0", Source = LBIS.L["Thorium Brotherhood"], SourceLocation = LBIS.L["Blackrock Depths"], TextureId = "" },
    [23800] = { Name = "Enchant Weapon - Agility", DesignId = "19445", ScrollId = "0", Source = LBIS.L["Timbermaw Hold - Honored"], SourceLocation = LBIS.L["Felwood"], TextureId = "" },
    [23802] = { Name = "Enchant Bracer - Healing Power", DesignId = "19447", ScrollId = "0", Source = LBIS.L["Argent Dawn - Revered"], SourceLocation = LBIS.L["Eastern Plaguelands"], TextureId = "" },
    [23803] = { Name = "Enchant Weapon - Mighty Spirit", DesignId = "19448", ScrollId = "0", Source = LBIS.L["Thorium Brotherhood"], SourceLocation = LBIS.L["Blackrock Depths"], TextureId = "" },
    [23804] = { Name = "Enchant Weapon - Mighty Intellect", DesignId = "19449", ScrollId = "0", Source = LBIS.L["Thorium Brotherhood"], SourceLocation = LBIS.L["Blackrock Depths"], TextureId = "" },
    [25079] = { Name = "Enchant Gloves - Healing Power", DesignId = "20730", ScrollId = "0", Source = LBIS.L["Boss Drop"], SourceLocation = LBIS.L["Ahn'Qiraj"], TextureId = "" },
    [27837] = { Name = "Enchant 2H Weapon - Agility", DesignId = "22392", ScrollId = "0", Source = LBIS.L["Timbermaw Hold - Friendly"], SourceLocation = LBIS.L["Felwood"], TextureId = "" },
    [432190] = { Name = "Wolfshead Trophy", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Emerald Wardens Vendors"], SourceLocation = LBIS.L["Various Vendors"], TextureId = "212568" },
    [435481] = { Name = "Enchant Weapon - Dismantle", DesignId = "215129", ScrollId = "0", Source = LBIS.L["Ziri Littlesprocket"], SourceLocation = LBIS.L["Gnomeregan"], TextureId = "" },
    [435903] = { Name = "Enchant Chest - Retricutioner", DesignId = "215138", ScrollId = "0", Source = LBIS.L["Ziri Littlesprocket"], SourceLocation = LBIS.L["Gnomeregan"], TextureId = "" },
    [446451] = { Name = "Atal'ai Signet of Might", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Zalgo the Explorer"], SourceLocation = LBIS.L["Yojamba Isle"], TextureId = "221321" },
    [446459] = { Name = "Atal'ai Signet of Mojo", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Zalgo the Explorer"], SourceLocation = LBIS.L["Yojamba Isle"], TextureId = "221322" },
    [446472] = { Name = "Atal'ai Signet of Serenity", DesignId = "99999", ScrollId = "0", Source = LBIS.L["Zalgo the Explorer"], SourceLocation = LBIS.L["Yojamba Isle"], TextureId = "221323" },
    [461129] = { Name = "Hydraxian Coronation", DesignId = "227926", ScrollId = "0", Source = LBIS.L["Duke Hydraxis"], SourceLocation = LBIS.L["Azshara"], TextureId = "" },
    [463871] = { Name = "Enchant Shield - Law of Nature", DesignId = "228982", ScrollId = "0", Source = LBIS.L["Timbermaw Hold"], SourceLocation = LBIS.L["Revered"], TextureId = "" },
}
