LBIS.GemSources =
{
    [52234] = { Name = "Retaliating Demonseye", DesignId = "52407", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59478] = { Name = "Smooth Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59479] = { Name = "Quick Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59480] = { Name = "Fractured Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [68779] = { Name = "Reverberating Shadowspirit Diamond", DesignId = "68782", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [68780] = { Name = "Burning Shadowspirit Diamond", DesignId = "68783", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [76636] = { Name = "Rigid River's Heart", DesignId = "83928", Source = unknown, SourceLocation = unknown },
    [76639] = { Name = "Solid River's Heart", DesignId = "83947", Source = unknown, SourceLocation = unknown },
    [76640] = { Name = "Misty Wild Jade", DesignId = "83888", Source = unknown, SourceLocation = unknown },
    [76641] = { Name = "Piercing Wild Jade", DesignId = "83896", Source = unknown, SourceLocation = unknown },
    [76642] = { Name = "Lightning Wild Jade", DesignId = "83882", Source = unknown, SourceLocation = unknown },
    [76643] = { Name = "Sensei's Wild Jade", DesignId = "83935", Source = unknown, SourceLocation = unknown },
    [76645] = { Name = "Zen Wild Jade", DesignId = "83982", Source = unknown, SourceLocation = unknown },
    [76651] = { Name = "Energized Wild Jade", DesignId = "83847", Source = unknown, SourceLocation = unknown },
    [76652] = { Name = "Jagged Wild Jade", DesignId = "83876", Source = unknown, SourceLocation = unknown },
    [76654] = { Name = "Forceful Wild Jade", DesignId = "83861", Source = unknown, SourceLocation = unknown },
    [76656] = { Name = "Puissant Wild Jade", DesignId = "83906", Source = unknown, SourceLocation = unknown },
    [76658] = { Name = "Deadly Vermilion Onyx", DesignId = "83832", Source = unknown, SourceLocation = unknown },
    [76659] = { Name = "Crafty Vermilion Onyx", DesignId = "83829", Source = unknown, SourceLocation = unknown },
    [76660] = { Name = "Potent Vermilion Onyx", DesignId = "83900", Source = unknown, SourceLocation = unknown },
    [76661] = { Name = "Inscribed Vermilion Onyx", DesignId = "83874", Source = unknown, SourceLocation = unknown },
    [76664] = { Name = "Stalwart Vermilion Onyx", DesignId = "83957", Source = unknown, SourceLocation = unknown },
    [76666] = { Name = "Deft Vermilion Onyx", DesignId = "83836", Source = unknown, SourceLocation = unknown },
    [76667] = { Name = "Wicked Vermilion Onyx", DesignId = "83977", Source = unknown, SourceLocation = unknown },
    [76668] = { Name = "Reckless Vermilion Onyx", DesignId = "83915", Source = unknown, SourceLocation = unknown },
    [76669] = { Name = "Fierce Vermilion Onyx", DesignId = "83853", Source = unknown, SourceLocation = unknown },
    [76670] = { Name = "Adept Vermilion Onyx", DesignId = "83810", Source = unknown, SourceLocation = unknown },
    [76671] = { Name = "Keen Vermilion Onyx", DesignId = "83879", Source = unknown, SourceLocation = unknown },
    [76672] = { Name = "Artful Vermilion Onyx", DesignId = "83814", Source = unknown, SourceLocation = unknown },
    [76674] = { Name = "Skillful Vermilion Onyx", DesignId = "83941", Source = unknown, SourceLocation = unknown },
    [76680] = { Name = "Glinting Imperial Amethyst", DesignId = "83866", Source = unknown, SourceLocation = unknown },
    [76681] = { Name = "Accurate Imperial Amethyst", DesignId = "83807", Source = unknown, SourceLocation = unknown },
    [76682] = { Name = "Veiled Imperial Amethyst", DesignId = "83972", Source = unknown, SourceLocation = unknown },
    [76683] = { Name = "Retaliating Imperial Amethyst", DesignId = "83923", Source = unknown, SourceLocation = unknown },
    [76684] = { Name = "Etched Imperial Amethyst", DesignId = "83849", Source = unknown, SourceLocation = unknown },
    [76686] = { Name = "Purified Imperial Amethyst", DesignId = "83907", Source = unknown, SourceLocation = unknown },
    [76688] = { Name = "Guardian's Imperial Amethyst", DesignId = "83869", Source = unknown, SourceLocation = unknown },
    [76690] = { Name = "Defender's Imperial Amethyst", DesignId = "83833", Source = unknown, SourceLocation = unknown },
    [76692] = { Name = "Delicate Primordial Ruby", DesignId = "83838", Source = unknown, SourceLocation = unknown },
    [76693] = { Name = "Precise Primordial Ruby", DesignId = "83903", Source = unknown, SourceLocation = unknown },
    [76694] = { Name = "Brilliant Primordial Ruby", DesignId = "83823", Source = unknown, SourceLocation = unknown },
    [76695] = { Name = "Flashing Primordial Ruby", DesignId = "83857", Source = unknown, SourceLocation = unknown },
    [76696] = { Name = "Bold Primordial Ruby", DesignId = "83820", Source = unknown, SourceLocation = unknown },
    [76697] = { Name = "Smooth Sun's Radiance", DesignId = "83944", Source = unknown, SourceLocation = unknown },
    [76699] = { Name = "Quick Sun's Radiance", DesignId = "83910", Source = unknown, SourceLocation = unknown },
    [76700] = { Name = "Fractured Sun's Radiance", DesignId = "83864", Source = unknown, SourceLocation = unknown },
    [76879] = { Name = "Ember Primal Diamond", DesignId = "83844", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [76884] = { Name = "Agile Primal Diamond", DesignId = "83811", Source = unknown, SourceLocation = unknown },
    [76885] = { Name = "Burning Primal Diamond", DesignId = "83825", Source = unknown, SourceLocation = unknown },
    [76886] = { Name = "Reverberating Primal Diamond", DesignId = "83925", Source = LBIS.L["Kor'kron Arcweaver"], SourceLocation = "" },
    [76895] = { Name = "Austere Primal Diamond", DesignId = "83815", Source = unknown, SourceLocation = unknown },
    [77540] = { Name = "Subtle Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77541] = { Name = "Smooth Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77542] = { Name = "Quick Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77543] = { Name = "Precise Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77544] = { Name = "Flashing Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77545] = { Name = "Rigid Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77546] = { Name = "Sparkling Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [77547] = { Name = "Fractured Tinker's Gear", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [83150] = { Name = "Brilliant Serpent's Eye", DesignId = "83824", Source = unknown, SourceLocation = unknown },
    [89873] = { Name = "Crystallized Dread", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [89881] = { Name = "Crystallized Terror", DesignId = "99999", Source = unknown, SourceLocation = unknown },
    [89882] = { Name = "Crystallized Horror", DesignId = "99999", Source = unknown, SourceLocation = unknown },
}
