LBIS.GemSources =
{
    [52204] = { Name = "Adept Ember Topaz", DesignId = "52419", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52205] = { Name = "Artful Ember Topaz", DesignId = "52421", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52206] = { Name = "Bold Inferno Ruby", DesignId = "52362", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52207] = { Name = "Brilliant Inferno Ruby", DesignId = "52387", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52208] = { Name = "Reckless Ember Topaz", DesignId = "52417", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52209] = { Name = "Deadly Ember Topaz", DesignId = "52413", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52210] = { Name = "Defender's Demonseye", DesignId = "52401", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52212] = { Name = "Delicate Inferno Ruby", DesignId = "52380", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52213] = { Name = "Etched Demonseye", DesignId = "52405", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52217] = { Name = "Veiled Demonseye", DesignId = "52408", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52219] = { Name = "Fractured Amberjewel", DesignId = "52398", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52220] = { Name = "Glinting Demonseye", DesignId = "52406", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52221] = { Name = "Guardian's Demonseye", DesignId = "52403", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52224] = { Name = "Keen Ember Topaz", DesignId = "52422", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52231] = { Name = "Puissant Dream Emerald", DesignId = "52430", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52233] = { Name = "Regal Dream Emerald", DesignId = "52423", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52236] = { Name = "Purified Demonseye", DesignId = "52404", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52239] = { Name = "Potent Ember Topaz", DesignId = "52414", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52242] = { Name = "Solid Ocean Sapphire", DesignId = "52390", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52243] = { Name = "Sovereign Demonseye", DesignId = "52399", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52258] = { Name = "Delicate Chimera's Eye", DesignId = "52447", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52291] = { Name = "Chaotic Shadowspirit Diamond", DesignId = "52434", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52293] = { Name = "Eternal Shadowspirit Diamond", DesignId = "52436", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52294] = { Name = "Austere Shadowspirit Diamond", DesignId = "52437", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [52296] = { Name = "Ember Shadowspirit Diamond", DesignId = "52439", Source = LBIS.L["Jewelcrafting Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59477] = { Name = "Subtle Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59478] = { Name = "Smooth Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59479] = { Name = "Quick Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59480] = { Name = "Fractured Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59489] = { Name = "Precise Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59493] = { Name = "Rigid Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [59496] = { Name = "Sparkling Cogwheel", DesignId = "99999", Source = LBIS.L["Engineering Supplies"], SourceLocation = LBIS.L["Faction Capital"] },
    [68778] = { Name = "Agile Shadowspirit Diamond", DesignId = "68781", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [68779] = { Name = "Reverberating Shadowspirit Diamond", DesignId = "68782", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [68780] = { Name = "Burning Shadowspirit Diamond", DesignId = "68783", Source = LBIS.L["World Drop"], SourceLocation = "" },
}
