LBIS.GemSources =
{
    [23097] = { Name = "Delicate Blood Garnet", DesignId = "23134", Source = LBIS.L["Consortium Quartermaster"], SourceLocation = LBIS.L["Netherstorm"] },
    [23100] = { Name = "Glinting Flame Spessarite", DesignId = "23137", Source = LBIS.L["Starting Vendors"], SourceLocation = LBIS.L["Hellfire Peninsula"] },
    [23118] = { Name = "Solid Azure Moonstone", DesignId = "23152", Source = LBIS.L["Starting Vendors"], SourceLocation = LBIS.L["Hellfire Peninsula"] },
    [24027] = { Name = "Bold Living Ruby", DesignId = "24193", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24028] = { Name = "Delicate Living Ruby", DesignId = "24194", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24029] = { Name = "Teardrop Living Ruby", DesignId = "24195", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24030] = { Name = "Runed Living Ruby", DesignId = "35305", Source = LBIS.L["Kael'thas Sunstrider"], SourceLocation = LBIS.L["Magisters' Terrace"] },
    [24033] = { Name = "Solid Star of Elune", DesignId = "35304", Source = LBIS.L["Kael'thas Sunstrider"], SourceLocation = LBIS.L["Magisters' Terrace"] },
    [24047] = { Name = "Brilliant Dawnstone", DesignId = "24203", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24048] = { Name = "Smooth Dawnstone", DesignId = "24204", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24054] = { Name = "Sovereign Nightseye", DesignId = "24209", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24055] = { Name = "Shifting Nightseye", DesignId = "24210", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24056] = { Name = "Glowing Nightseye", DesignId = "24211", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24057] = { Name = "Royal Nightseye", DesignId = "24212", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24058] = { Name = "Inscribed Noble Topaz", DesignId = "24213", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24059] = { Name = "Potent Noble Topaz", DesignId = "24214", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24060] = { Name = "Luminous Noble Topaz", DesignId = "24215", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24061] = { Name = "Glinting Noble Topaz", DesignId = "24216", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [24067] = { Name = "Jagged Talasite", DesignId = "24220", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [25896] = { Name = "Powerful Earthstorm Diamond", DesignId = "25902", Source = LBIS.L["Ythyar"], SourceLocation = LBIS.L["Karazhan"] },
    [25897] = { Name = "Bracing Earthstorm Diamond", DesignId = "25903", Source = LBIS.L["Ythyar"], SourceLocation = LBIS.L["Karazhan"] },
    [25901] = { Name = "Insightful Earthstorm Diamond", DesignId = "25904", Source = LBIS.L["Sha'tari Quartermaster"], SourceLocation = LBIS.L["Shattrath City"] },
    [28118] = { Name = "Runed Ornate Ruby", DesignId = "99999", Source = LBIS.L["PvP Vendor"], SourceLocation = LBIS.L["Capital Cities"] },
    [30550] = { Name = "Sundered Chrysoprase", DesignId = "99999", Source = LBIS.L["Trash Drop"], SourceLocation = LBIS.L["The Steamvault"] },
    [30555] = { Name = "Glowing Tanzanite", DesignId = "99999", Source = LBIS.L["Trash Drop"], SourceLocation = LBIS.L["The Black Morass"] },
    [30582] = { Name = "Deadly Fire Opal", DesignId = "99999", Source = LBIS.L["Trash Drop"], SourceLocation = LBIS.L["The Arcatraz"] },
    [30602] = { Name = "Jagged Chrysoprase", DesignId = "99999", Source = LBIS.L["Trash Drop"], SourceLocation = LBIS.L["The Blood Furnace"] },
    [31861] = { Name = "Great Dawnstone", DesignId = "31875", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [31867] = { Name = "Veiled Noble Topaz", DesignId = "31878", Source = LBIS.L["World Drop"], SourceLocation = "" },
    [32200] = { Name = "Solid Empyrean Sapphire", DesignId = "99999", Source = LBIS.L["Indormi"], SourceLocation = LBIS.L["Hyjal Summit"] },
    [32208] = { Name = "Thick Lionseye", DesignId = "99999", Source = LBIS.L["Indormi"], SourceLocation = LBIS.L["Hyjal Summit"] },
    [32223] = { Name = "Enduring Seaspray Emerald", DesignId = "99999", Source = LBIS.L["Indormi"], SourceLocation = LBIS.L["Hyjal Summit"] },
    [32409] = { Name = "Relentless Earthstorm Diamond", DesignId = "99999", Source = LBIs.L["The Consortium (Exalted)"], SourceLocation = LBIS.L["Nagrand"] },
    [32836] = { Name = "Purified Shadow Pearl", DesignId = "99999", Source = LBIS.L["Jewelcrafting Trainer"], SourceLocation = LBIS.L["Shattrath City"] },
    [34220] = { Name = "Chaotic Skyfire Diamond", DesignId = "99999", Source = LBIS.L["Coilskar Siren"], SourceLocation = LBIS.L["Shadowmoon Valley"] },
    [35501] = { Name = "Eternal Earthstorm Diamond", DesignId = "35502", Source = LBIS.L["Shattered Sun Quartermaster"], SourceLocation = LBIS.L["Isle of Quel'Danas"] },
    [35707] = { Name = "Regal Nightseye", DesignId = "35708", Source = LBIS.L["Shattered Sun Quartermaster"], SourceLocation = LBIS.L["Isle of Quel'Danas"] },
}
