local spec = LoonBestInSlot:RegisterSpec("Druid", "Resto")
LoonBestInSlot:AddItem(spec, "31037", "Head", "Thunderheart Helmet",            "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32329", "Head", "Cowl of Benevolence",            "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32240", "Head", "Guise of the Tidal Lurker",      "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30219", "Head", "Nordrassil Headguard",           "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32479", "Head", "Wonderheal XT40 Shades",         "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood",                 "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29086", "Head", "Crown of Malorne",               "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",    "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28803", "Head", "Cowl of Nature's Breath",        "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "32090", "Head", "Cowl of Naaru Blessings",        "PreRaid", "0", "Dungeon Token", "50 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown",                 "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28348", "Head", "Moonglade Cowl",                 "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "29174", "Head", "Watcher's Cowl",                 "PreRaid", "0", "Reputation", "Cenarion Expedition", "Revered")
LoonBestInSlot:AddItem(spec, "29505", "Head", "Hood of Primal Life",            "PreRaid", "0", "Profession", "Leatherworking (365)")

LoonBestInSlot:AddItem(spec, "31047", "Shoulders", "Thunderheart Spaulders",            "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32518", "Shoulders", "Veil of Turning Leaves",            "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30221", "Shoulders", "Nordrassil Life-Mantle",            "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30111", "Shoulders", "Runetotem's Mantle",                "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders",        "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29089", "Shoulders", "Shoulderguards of Malorne",         "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",  "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28612", "Shoulders", "Pauldrons of the Solace-Giver",     "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "28647", "Shoulders", "Forest Wind Shoulderpads",          "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons",                "PreRaid", "0", "Drop", "Grandmaster Vorpil", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance",           "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills ")
LoonBestInSlot:AddItem(spec, "27737", "Shoulders", "Moonglade Shoulders",               "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",            "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness",              "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand",          "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak",              "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak",                   "Alt", "1>3", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak",            "Alt", "1", "Drop", "The Big Bad Wolf", "Karazhan")
LoonBestInSlot:AddItem(spec, "27946", "Back", "Avian Cloak of Feathers",            "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism",    "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Althop's Cloak",                     "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape",                  "PreRaid", "0", "Drop", "BoE World Drop")

LoonBestInSlot:AddItem(spec, "31041", "Chest", "Thunderheart Tunic",                "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30216", "Chest", "Nordrassil Chestguard",             "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe",             "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29087", "Chest", "Chestguard of Malorne",             "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28600", "Chest", "Stonebough Jerkin",                 "Alt", "1", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk",                  "PreRaid", "0", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments",                 "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28202", "Chest", "Moonglade Robe",                    "PreRaid", "0", "Drop", "Nethermancer Sepethrea and Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "27456", "Chest", "Raiments of Nature's Breath",       "PreRaid", "0", "Drop", "Reinforced Fel Iron Chest", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "27506", "Chest", "Robe of Effervescent Light",        "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")

LoonBestInSlot:AddItem(spec, "30868", "Bracers", "Rejuvenating Bracers",        "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30871", "Bracers", "Bracers of Martyrdom",        "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps",             "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "32582", "Bracers", "Bracers of Renewed Life",     "BIS", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32513", "Bracers", "Wristbands of Divine Influence", "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30062", "Bracers", "Grove-Bands of Remulos",      "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker",  "Alt", "1>2", "Reputation", "Keepers of Time (Exalted)")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers",            "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling",         "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent",     "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls (Heroic)")
LoonBestInSlot:AddItem(spec, "27827", "Bracers", "Lucid Dream Bracers",         "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")

LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth",      "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32353", "Gloves", "Gloves of Unfailing Faith",        "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "31032", "Gloves", "Thunderheart Gloves",              "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher","Alt", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender",          "Alt", "1>3", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "30217", "Gloves", "Nordrassil Gloves",                "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28508", "Gloves", "Gloves of Saintly Blessings",      "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "29090", "Gloves", "Handguards of Malorne",            "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender",    "Alt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch",       "Alt", "0", "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "24393", "Gloves", "Bloody Surgeon's Mitts",           "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace ")
LoonBestInSlot:AddItem(spec, "25791", "Gloves", "Gloves of Preservation",           "PreRaid", "0", "Quest", "Fel Embers", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "28268", "Gloves", "Natural Mender's Wraps",           "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "29327", "Gloves", "Cryo-mitts",                       "PreRaid", "0", "Quest", "Someone Else's Hard Work Pays Off", "Mana-Tombs")

LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash",               "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32339", "Belt", "Belt of Primal Majesty",         "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "32519", "Belt", "Belt of Divine Guidance",        "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29984", "Belt", "Girdle of Zaetar",               "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30036", "Belt", "Belt of the Long Road",          "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt",          "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28655", "Belt", "Cord of Nature's Sustenance",    "Alt", "1>2", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "28652", "Belt", "Cincture of Will",               "Alt", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt",                  "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification",         "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "31594", "Belt", "General's Kodohide Belt",        "PreRaid", "0", "PvP", "8925 Honor Points + 40 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "27542", "Belt", "Cord of Belief",                 "PreRaid", "0", "Drop", "Commander Sarannis", "The Botanica (Heroic)")
LoonBestInSlot:AddItem(spec, "28398", "Belt", "The Sleeper's Cord",             "PreRaid", "0", "Drop", "Wrath-Scryer Soccothrates", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity",           "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32271", "Legs", "Kilt of Immortal Nature",        "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "31045", "Legs", "Thunderheart Legguards",         "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "Alt", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings",             "Alt", "1>3", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30220", "Legs", "Nordrassil Life-Kilt",           "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants",                "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance",       "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt",                  "PreRaid", "0", "Drop", "Warlord Kalithresh ", "The Steamvault (Heroic)")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt",        "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "31335", "Legs", "Pants of Living Growth",         "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "28218", "Legs", "Pontiff's Pantaloons of Prophecy", "PreRaid", "0", "Drop", "Captain Skarloc", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "31377", "Legs", "Gladiator's Kodohide Legguards", "PreRaid", "0", "PvP", "10328 Honor Points, 30 Warsong Gulch Marks")
LoonBestInSlot:AddItem(spec, "29345", "Legs", "Haramad's Leg Wraps",            "PreRaid", "0", "Quest", "Undercutting the Competition", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers",    "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "27875", "Legs", "Hallowed Trousers",              "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light",      "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30885", "Feet", "Archbishop's Slippers",          "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30886", "Feet", "Enchanted Leather Sandals",      "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots",            "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots",                "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30100", "Feet", "Soul-Strider Boots",             "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders",            "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28663", "Feet", "Boots of the Incorrupt",         "Alt", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity",           "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious",             "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar (Heroic)")
LoonBestInSlot:AddItem(spec, "25792", "Feet", "Curate's Boots",                 "PreRaid", "0", "Quest", "Fel Embers", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "31595", "Feet", "General's Kodohide Boots",       "PreRaid", "0", "PvP", "8925 Honor Points + 40 Eye of the Storm Mark")
LoonBestInSlot:AddItem(spec, "28251", "Feet", "Boots of the Glade-Keeper",      "PreRaid", "0", "Drop", "Cache of the Legion", "The Mechanar")
LoonBestInSlot:AddItem(spec, "27525", "Feet", "Jeweled Boots of Sanctification", "PreRaid", "0", "Drop", "Warbringer O'mrogg", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "35317", "Neck", "Vindicator's Pendant of Reprieve","BIS", "3", "PvP", "15300 Honor, 10 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity",     "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim",         "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence",      "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul",                 "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman",             "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28731", "Neck", "Shining Chain of the Afterworld", "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion",              "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara Netherstorm")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord",        "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope",       "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope",   "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor",        "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer",   "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived",      "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving",    "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band",       "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt", "1>2",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light",          "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope",            "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band",                 "PreRaid", "0", "Reputation", "Thrallmar Revered", "Quartermaster Urgronn")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence",          "PreRaid", "0", "Reputation", "Honor Hold Revered", "Logistics Officer Ulrike")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "PreRaid", "0", "Quest", "Battle of the Crimson Watch", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos",                  "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void",   "PreRaid", "0", "Drop", "Yor ", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring",           "PreRaid", "0", "Quest", "Hitting the Motherlode", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29322", "Ring", "Keeper's Ring of Piety",         "PreRaid", "0", "Quest", "The Opening of the Dark Portal", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband",                "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")

LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops",               "BIS", "2>3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr",       "BIS", "1>3", "Dungeon Token", "G'eras", "41 Badge of Justice")
LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande",          "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32486", "Trinket", "Ashtongue Talisman of Equilibrium", "Alt", "3", "Reputation", "Ashtongue Deathsworn - Exalted", "Okuno")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic",              "Alt", "1>2", "Quest", "Gava'xi", "Nagrand")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook",       "Alt", "1", "Reputation", "Lower City Revered")
LoonBestInSlot:AddItem(spec, "28823", "Trinket", "Eye of Gruul",                "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler",   "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor",         "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "33743", "MH", "Vengeful Gladiator's Salvation",   "Alt", "3", "PvP", "3150 Arena Points")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement",              "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter",              "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice",                  "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous",            "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity",                 "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon",              "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min",   "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light",              "PreRaid", "0", "Reputation", "The Sha'tar Exalted")
LoonBestInSlot:AddItem(spec, "28257", "MH", "Hammer of the Penitent",           "PreRaid", "0", "Drop", "Mechano-Lord Capacitus", "The Mechanar")
LoonBestInSlot:AddItem(spec, "28216", "MH", "Dathrohan's Ceremonial Hammer",    "PreRaid", "0", "Drop", "Captain Skarloc", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "27538", "MH", "Lightsworn Hammer",                "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "31304", "MH", "The Essence Focuser",              "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "30908", "2H", "Apostle of Argus",                 "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32344", "2H", "Staff of Immaculate Recovery",     "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29981", "2H", "Ethereum Life-Staff",              "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30732", "2H", "Exodar Life-Staff",                "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28782", "2H", "Crystalheart Pulse-Staff",         "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28604", "2H", "Nightstaff of the Everliving",     "Alt", "1", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "27791", "2H", "Serpentcrest Life-Staff",          "PreRaid", "0", "Drop", "Mekgineer Steamrigger", "The Steamvault")
LoonBestInSlot:AddItem(spec, "29133", "2H", "Seer's Cane",                      "PreRaid", "0", "Reputation", "The Scryers — Revered", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "28033", "2H", "Epoch-Mender",                     "PreRaid", "0", "Drop", "Temporus", "The Black Morass")

LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification",          "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32350", "OH", "Touch of Inspiration",             "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven",                  "Alt", "1>3", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb",                 "Alt", "1>3", "Reputation", "Cenarion Expedition (Exalted)", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King",         "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire",         "Alt", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28525", "OH", "Signet of Unshakable Faith",       "Alt", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing",       "PreRaid", "0", "Drop", "Omor the Unscarred ", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "27714", "OH", "Swamplight Lantern",               "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "28213", "OH", "Lordaeron Medical Guide",          "PreRaid", "0", "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "31493", "OH", "Netherwing Spiritualist's Charm",  "PreRaid", "0", "Quest", "Ally of the Netherwing", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28387", "OH", "Lamp of Peaceful Repose",          "PreRaid", "0", "Drop", "Dalliah the Doomsayer", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "27886", "Idol", "Idol of the Emerald Queen",      "BIS", "1>3", "Drop", "Ambassador Hellmaw", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess",      "Alt", "2>3", "Quest", "Vanquish the Raven God", "Swift Flight Questline")
LoonBestInSlot:AddItem(spec, "25643", "Idol", "Harold's Rejuvenating Broach",   "PreRaid", "0", "Quest", "The Ultimate Bloodsport", "Nagrand")