local spec = LoonBestInSlot:RegisterSpec("Druid", "Balance")
LoonBestInSlot:AddItem(spec, "31040", "Head", "Thunderheart Headguard",         "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30233", "Head", "Nordrassil Headpiece",           "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer",     "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32480", "Head", "Magnified Moon Specs",           "Alt", "2", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",    "Alt", "1>2",  "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29093", "Head", "Antlers of Malorne",             "Alt", "1>2",  "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood",               "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28744", "Head", "Uni-Mind Headdress",             "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "23828", "Head", "Gnomish Power Goggles",          "Alt", "1",  "Profession", "Gnomish Engineer (375)")
LoonBestInSlot:AddItem(spec, "28804", "Head", "Collar of Cho'gall",             "Alt", "1",  "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "31110", "Head", "Druidic Helmet of Second Sight", "PreRaid", "0", "Quest", "Teron Gorefiend, I am...")
LoonBestInSlot:AddItem(spec, "28169", "Head", "Mag'hari Ritualist's Horns",     "PreRaid", "0", "Quest", "Hero of the Mag'har")
LoonBestInSlot:AddItem(spec, "32089", "Head", "Mana-Binders Cowl",              "PreRaid", "0", "Dungeon Token", "G'eras", "50 Badge of Justice")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl",                "PreRaid", "0", "Drop", "Pathaleon the Calculator", "Mechanar")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion",               "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "31049", "Shoulders", "Thunderheart Shoulderpads",           "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher","BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads",         "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle",                   "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought",          "Alt", "3", "Profession", "Tailoring(375)")
LoonBestInSlot:AddItem(spec, "30235", "Shoulders", "Nordrassil Wrath-Mantle",           "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30024", "Shoulders", "Mantle of the Elven Kings",         "Alt", "2", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30079", "Shoulders", "Illidari Shoulderpads",             "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",  "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29095", "Shoulders", "Pauldrons of Malorne",              "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders",             "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", "Spaulders of Oblivion",             "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart",       "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "27994", "Shoulders", "Mantle of Three Terrors",           "PreRaid", "0", "Drop", "Chrono Lord Deja", "The Black Morass")
LoonBestInSlot:AddItem(spec, "27738", "Shoulders", "Incanter's Pauldrons",              "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "31797", "Shoulders", "Elekk Hide Spaulders",              "PreRaid", "0", "Quest", "The Fallen Exarch", "Terokkar Forest")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",            "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council",      "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt", "1>3",  "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant",        "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi",       "Alt", "1>3",  "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran",            "Alt", "1>2",  "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "31140", "Back", "Cloak of Entropy",                   "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities",    "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badges of Justice ")
LoonBestInSlot:AddItem(spec, "24252", "Back", "Cloak of the Black Void",            "PreRaid", "0", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "25777", "Back", "Ogre Slayer's Cover",                "PreRaid", "0", "Quest", "Cho'war the Pillager", "Nagrand")

LoonBestInSlot:AddItem(spec, "31043", "Chest", "Thunderheart Vest",                     "BIS", "3", "Drop", "undefined", "undefined")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher","BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin",                       "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30231", "Chest", "Nordrassil Chestpiece",                 "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch",            "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21848", "Chest", "Spellfire Robe",                        "Alt", "1>3", "Profession", "Spellfire Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30056", "Chest", "Robe of Hateful Echoes",                "Alt", "2", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender",     "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29091", "Chest", "Chestpiece of Malorne",                 "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk",                      "PreRaid", "0", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order",             "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe",             "PreRaid", "0", "Quest", "Everything Will Be Alright", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd",                "PreRaid", "0", "Drop", "World Drop")
LoonBestInSlot:AddItem(spec, "28342", "Chest", "Warp Infused Drape",                    "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")
LoonBestInSlot:AddItem(spec, "29129", "Chest", "Anchorite's Robes",                     "PreRaid", "0", "Reputation", "The Aldor (Honored)", "Quartermaster Endarin")
LoonBestInSlot:AddItem(spec, "28229", "Chest", "Incanter's Robe",                       "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought",   "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings",       "BIS", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "32351", "Bracers", "Elunite Empowered Bracers",   "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation",        "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands",        "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers",            "Alt", "1>3", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32655", "Bracers", "Crystalweave Bracers",        "Alt", "2", "Quest", "Apexis Crystal Infusion", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok",            "Alt", "1>2", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds",    "Alt", "1>2",  "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28453", "Bracers", "Bracers of the White Stag",   "Alt", "1",  "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom",    "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "29240", "Bracers", "Bands of Negation",           "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "21186", "Bracers", "Rockfury Bracers",            "PreRaid", "0", "Reputation", "Cenarion Circle Revered", "Vargus")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps",             "PreRaid", "0", "Quest", "The Soul Devices", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29255", "Bracers", "Bands of Rarefied Magic",     "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls (Heroic)")

LoonBestInSlot:AddItem(spec, "31035", "Gloves", "Thunderheart Handguards",      "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth",  "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "30232", "Gloves", "Nordrassil Gauntlets",         "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29987", "Gloves", "Gauntlets of the Sun King",    "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "21847", "Gloves", "Spellfire Gloves",             "Alt", "1>3", "Profession", "Spellfire Tailoring (365)")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves",           "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought", "Alt", "1>3", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps",       "Alt", "1>2",  "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29092", "Gloves", "Gloves of Malorne",            "Alt", "1>2",  "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29758", "Gloves", "Gloves of the Fallen Defender", "Alt", "1>2",  "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "27493", "Gloves", "Gloves of the Deadwatcher",    "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27537", "Gloves", "Gloves of Oblivion",           "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "24450", "Gloves", "Manaspark Gloves",             "PreRaid", "0", "Drop", "Hungarfen", "The Underbog")
LoonBestInSlot:AddItem(spec, "31149", "Gloves", "Gloves of Pandemonium",        "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves",           "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", "Tempest's Touch",              "PreRaid", "0", "Quest", "Return to Andormu", "Caverns of Time")
LoonBestInSlot:AddItem(spec, "24452", "Gloves", "Starlight Gauntlets",          "PreRaid", "0", "Drop", "Hungarfen", "The Underbog")

LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose",              "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30914", "Belt", "Belt of the Crescent Moon",      "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity",          "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting",               "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors",      "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21846", "Belt", "Spellfire Belt",                 "Alt", "1>3", "Profession", "Spellfire Tailoring (355)")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination",            "Alt", "1>2", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration",     "Alt", "1>2",  "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28654", "Belt", "Malefic Girdle",                 "Alt", "1",  "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt",                  "PreRaid", "0", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity",              "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "27843", "Belt", "Glyph-Lined Sash",               "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift",                   "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "24395", "Belt", "Mindfire Waistband",             "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31046", "Legs", "Thunderheart Pants",             "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "Alt", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation",        "Alt", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants",              "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "30234", "Legs", "Nordrassil Wrath-Kilt",          "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender","Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer",    "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers",            "Alt", "1>2",  "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist",      "Alt", "1>2", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "29141", "Legs", "Tempest Leggings",               "PreRaid", "0", "Reputation", "The Mag'har Revered", "Provisioner Nasela")
LoonBestInSlot:AddItem(spec, "29142", "Legs", "Kurenai Kilt",                   "PreRaid", "0", "Reputation", "Kurenai Revered", "Trader Narasu")
LoonBestInSlot:AddItem(spec, "29343", "Legs", "Haramad's Leggings of the Third Coin", "PreRaid", "0", "Quest", "Undercutting the Competition", "Mana-Tombs")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers",    "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "28212", "Legs", "Aran's Sorcerous Slacks",        "PreRaid", "0", "Drop", "Lieutenant Drake", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "27492", "Legs", "Moonchild Leggings",             "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration",   "PreRaid", "0", "Drop", "Temporus", "The Black Morass")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller",      "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32352", "Feet", "Naturewarden's Treads",          "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes",               "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting",              "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian",   "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling",           "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers",                  "Alt", "1>2", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27821", "Feet", "Extravagant Boots of Malice",    "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots",              "PreRaid", "0", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers",              "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29808", "Feet", "Shimmering Azure Boots",         "PreRaid", "0", "Quest", "Securing the Celestial Ridge", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30519", "Feet", "Boots of the Nexus Warden",      "PreRaid", "0", "Quest", "The Flesh Lies...", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29258", "Feet", "Boots of Ethereal Manipulation", "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica (Heroic)")
LoonBestInSlot:AddItem(spec, "27848", "Feet", "Embroidered Spellpyre Boots",    "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "27914", "Feet", "Moonstrider Boots",              "PreRaid", "0", "Drop", "Darkweaver Syth", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "29242", "Feet", "Boots of Blasphemy",             "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")

LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                     "BIS", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman",            "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "35319", "Neck", "Vindicator's Pendant of Subjugation","BIS", "3", "PvP", "15300 Honor, 10 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace",   "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "33920", "Neck", "Vindicator's Pendant of Conquest",   "Alt", "3", "PvP", "15300 Honor, 10 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury",        "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls",          "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "24116", "Neck", "Eye of the Night",                   "Alt", "1",  "Profession", "Jewelcrafting (360)")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential",     "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27758", "Neck", "Hydra-fang Necklace",                "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace",           "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29333", "Neck", "Torc of the Sethekk Prophet",        "PreRaid", "0", "Quest", "Brother Against Brother", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "24462", "Neck", "Luminous Pearls of Insight",         "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge",      "BIS", "3", "Drop", "undefined", "Black Temple")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage",       "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms",        "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils",          "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage",  "Alt", "1>3", "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury",           "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence",             "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift",                  "Alt", "1>2", "Reputation", "Cenarion Expedition Exalted", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring",         "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist",           "PreRaid", "0", "Dungeons", "50 Spirit Shard", "Spirit Sage Gartok and Spirit Sage Zran")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa",        "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "29367", "Ring", "Ring of Cryptic Dreams",         "PreRaid", "0", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet",                  "PreRaid", "0", "Reputation", "The Scryers Exalted", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "31075", "Ring", "Evoker's Mark of the Redemption", "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30366", "Ring", "Manastorm Band",                 "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31290", "Ring", "Band of Dominion",               "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "28394", "Ring", "Ryngo's Band of Ingenuity",      "PreRaid", "0", "Drop", "Wrath-Scryer Soccothrates", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan",                "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32486", "Trinket", "Ashtongue Talisman of Equilibrium",   "BIS", "3", "Drop", "Ashtongue Deathsworn (Exalted)", "Okuno")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe",              "Alt", "3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents",        "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent",         "Alt", "1>3", "Dungeon Token", "41 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye",                    "Alt", "1>3", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem",                   "Alt", "1>2", "Reputation", "The Scryers Revered", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon",                  "Alt", "1>2",  "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28223", "Trinket", "Arcanist's Stone",                    "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "26055", "Trinket", "Oculus of the Hidden Eye",            "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "30340", "Trinket", "Starkiller's Bauble",                 "PreRaid", "0", "Quest", "The Horrors of Pollution", "Netherstorm")
LoonBestInSlot:AddItem(spec, "12930", "Trinket", "Briarwood Reed",                      "PreRaid", "0", "Drop", "Jed Runewatcher", "Upper Blackrock Spire")
LoonBestInSlot:AddItem(spec, "25936", "Trinket", "Terokkar Tablet of Vim",              "PreRaid", "0", "Quest", "Torgos!", "Terokkar Forest")
LoonBestInSlot:AddItem(spec, "25620", "Trinket", "Ancient Crystal Talisman",            "PreRaid", "0", "Quest", "A Spirit Ally?", "Zangarmarsh")
LoonBestInSlot:AddItem(spec, "25619", "Trinket", "Glowing Crystal Insignia",            "PreRaid", "0", "Quest", "Overlord Gorefist", "Zangarmarsh")

LoonBestInSlot:AddItem(spec, "33763", "MH", "Vengeful Gladiator's Spellblade",  "BIS", "3", "PvP", "3150 Arena Points", "Shattrath City")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury",             "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement",              "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest",             "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade",              "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade",             "PreRaid", "0", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets",       "PreRaid", "0", "Reputation", "Lower City Exalted", "Nakodu")
LoonBestInSlot:AddItem(spec, "27543", "MH", "Starlight Dagger",                 "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "28931", "MH", "High Warlord's Spellblade",        "PreRaid", "0", "PvP", "4782 Honor + 20 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "27937", "MH", "Sky Breaker",                      "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27741", "MH", "Bleeding Hollow Warhammer",        "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27868", "MH", "Runesong Dagger",                  "PreRaid", "0", "Drop", "Warbringer O'mrogg", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer","BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "34540", "2H", "Vengeful Gladiator's Battle Staff",    "Alt", "3", "PvP", "3750 Arena Points")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key",                        "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28633", "2H", "Staff of Infinite Mysteries",          "Alt", "1>3", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "35514", "2H", "Frostscythe of Lord Ahune",            "Alt", "1>2", "Drop", "Ahune", "The Slave Pens(Fire Event)")
LoonBestInSlot:AddItem(spec, "29355", "2H", "Terokk's Shadowstaff",                 "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls (Heroic)")
LoonBestInSlot:AddItem(spec, "27842", "2H", "Grand Scepter of the Nexus-Kings",     "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "29130", "2H", "Auchenai Staff",                       "PreRaid", "0", "Reputation", "The Aldor Revered", "Quartermaster Endarin")
LoonBestInSlot:AddItem(spec, "28341", "2H", "Warpstaff of Arcanum",                 "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")
LoonBestInSlot:AddItem(spec, "31308", "2H", "The Bringer of Death",                 "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "28188", "2H", "Bloodfire Greatstaff",                 "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")

LoonBestInSlot:AddItem(spec, "30872", "2H", "Chronicle of Dark Secrets",        "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32361", "2H", "Blind-Seers Icon",                 "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone",                      "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29271", "OH", "Talisman of Kalecgos",             "Alt", "1>3", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities",  "Alt", "1>3", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane",            "Alt", "1>2",  "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack",               "PreRaid", "0", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance",        "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28187", "OH", "Star-Heart Lamp",                  "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28260", "OH", "Manual of the Nethermancer",       "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "29330", "OH", "The Saga of Terokk",               "PreRaid", "0", "Quest", "Terokk's Legacy", "Terokkar Forest")

LoonBestInSlot:AddItem(spec, "27518", "Idol", "Ivory Idol of the Moongoddess", "BIS", "1>3", "Drop", "Grand Warlock Nethekurse", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess",     "BIS", "2>3", "Quest", "Vanquish the Raven God", "Swift Flight Questline")
LoonBestInSlot:AddItem(spec, "23197", "Idol", "Idol of the Moon",              "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "32387", "Idol", "Idol of the Raven Goddess",     "PreRaid", "0", "Quest", "Druid Epic Flight Form Quests")