local spec = LoonBestInSlot:RegisterSpec("Hunter", "")

LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",      "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31003", "Head", "Gronnstalker's Helmet",          "BIS Surv", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "BIS Surv", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm",          "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30141", "Head", "Rift Stalker Helm",              "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30244", "Head", "Helm of the Vanquished Hero",    "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32087", "Head", "Mask of the Deceiver",           "Alt", "1>2", "Dungeon Token", "50 Badges of Justice", "G'eras, Shattrath")
LoonBestInSlot:AddItem(spec, "28275", "Head", "Beast Lord Helm",                "Alt", "1>2", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "29759", "Head", "Helm of the Fallen Hero",        "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29081", "Head", "Demon Stalker Greathelm",        "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "31109", "Head", "Stealther's Helmet of Second Sight", "PreRaid", "0", "Quest", " Teron Gorefiend, I am...")
LoonBestInSlot:AddItem(spec, "31106", "Head", "Stalker's Helmet of Second Sight", "PreRaid", "0", "Quest", "Teron Gorefiend, I am...")
LoonBestInSlot:AddItem(spec, "31281", "Head", "Mask of Veiled Death",           "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27414", "Head", "Mok'Nathal Beast-Mask",          "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "31006", "Shoulders", "Gronnstalker's Spaulders",           "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30892", "Shoulders", "Beast-tamer's Shoulders",           "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32264", "Shoulders", "Shoulders of the Hidden Predator",  "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders",             "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32575", "Shoulders", "Shoulders of Lightning Reflexes",   "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30143", "Shoulders", "Rift Stalker Mantle",               "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30250", "Shoulders", "Pauldrons of the Vanquished Hero",  "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "27801", "Shoulders", "Beast Lord Mantle",                 "Alt", "1>2", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",      "Alt", "2", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30085", "Shoulders", "Mantle of the Tireless Tracker",    "Alt", "2", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets",       "PreRaid", "0", "Quest", "Fel Embers", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",          "PreRaid", "0",  "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde",               "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills")

LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",         "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape",   "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap",                 "Alt", "1>3", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",      "Alt Hit", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker",       "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak",         "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud",          "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter",           "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "31004", "Chest", "Gronnstalker's Chestguard",             "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30139", "Chest", "Rift Stalker Hauberk",                  "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30238", "Chest", "Chestguard of the Vanquished Hero",     "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30054", "Chest", "Ranger-General's Chestguard",           "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30055", "Chest", "Shoulderpads of the Stranger",          "Alt", "2", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28228", "Chest", "Beast Lord Cuirass",                    "Alt", "1>2", "Drop", "Warp Splinter", "The Botanica")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest",                     "Alt", "1>2", "Profession", "Elemental Leatherworking")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate",          "Alt", "1>2", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor",                    "PreRaid", "0", "Quest", "Varedis Must Be Stopped", "Larissa Sunstrike")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands",             "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "Alt", "3", "Drop", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers",         "Alt", "3", "Drop", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending",         "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30026", "Bracers", "Bands of the Celestial Archer", "Alt", "2>3", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands",      "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers",        "Alt", "1", "Drop", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards",       "Alt", "1", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "25697", "Bracers", "Felstalker Bracers",          "PreRaid", "0", "Profession", "Leatherworking (360)")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers",    "PreRaid", "0", "Profession", "Dragonscale Leatherworking")

LoonBestInSlot:AddItem(spec, "31001", "Gloves", "Gronnstalker's Gloves",            "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30140", "Gloves", "Rift Stalker Gauntlets",           "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30241", "Gloves", "Gloves of the Vanquished Hero",    "Alt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt Surv", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "27474", "Gloves", "Beast Lord Handguards",            "Alt", "1>2", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")
LoonBestInSlot:AddItem(spec, "28827", "Gloves", "Gauntlets of the Dragonslayer",    "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves",               "PreRaid", "0", "Profession", "Leatherworking (340)")

LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt", "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32346", "Belt", "Boneweave Girdle",           "BIS Hit", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow",        "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30046", "Belt", "Belt of the Black Eagle",    "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths", "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",      "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery",        "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28656", "Belt", "Girdle of the Prowler",      "Alt", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt",          "PreRaid", "0", "Profession", "Elemental Leatherworking")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash",              "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt",      "PreRaid", "0", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "25695", "Belt", "Felstalker Belt",            "PreRaid", "0", "Profession", "Leatherworking (350)")

LoonBestInSlot:AddItem(spec, "31005", "Legs", "Gronnstalker's Leggings",            "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings",              "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons",          "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent",       "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30142", "Legs", "Rift Stalker Leggings",              "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30247", "Legs", "Leggings of the Vanquished Hero",    "Alt", "2", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29985", "Legs", "Void Reaver Greaves",                "Alt", "2", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30739", "Legs", "Scaled Greaves of the Marksman",     "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves",                  "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "30538", "Legs", "Midnight Legguards",                 "Alt", "1>2", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27874", "Legs", "Beast Lord Leggings",                "Alt", "1", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings",               "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots",       "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "Alt Hit", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "30880", "Feet", "Quickstrider Moccasins",     "Alt Hit", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots",           "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots",         "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30060", "Feet", "Boots of Effortless Striking", "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",       "Alt", "1>3", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots",         "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28669", "Feet", "Rapscallion Boots",          "Alt", "1", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "29248", "Feet", "Shadowstep Striders",        "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots",          "PreRaid", "0", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "31288", "Feet", "The Master's Treads",        "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots",    "PreRaid", "0", "Quest", "A Fate Worse Than Death", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades",      "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "BIS Surv", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem",  "BIS Surv", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares",   "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30059", "Neck", "Choker of Animalistic Fury",     "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",          "Alt", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",           "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28674", "Neck", "Saberclaw Talisman",             "Alt", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28343", "Neck", "Jagged Bark Pendant",            "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing",         "PreRaid", "0", "Quest", "Gurok the Usurper", "Gordawg, Nagrand")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring",      "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion", "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",         "BIS Surv", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant",   "BIS Surv", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General", "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality",          "Alt Hit", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",   "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",       "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality", "PreRaid", "0", "Drop", "Yor", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet",           "PreRaid", "0", "Quest", "Deathblow to the Legion", "Ishanah, Shattrath City")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption", "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Thane Yoregar / Overlord Or'barokh, Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "27925", "Ring", "Ravenclaw Band",             "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")
LoonBestInSlot:AddItem(spec, "30973", "Ring", "Band of Anguish",            "PreRaid", "0", "Quest", "News of Victory", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",         "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "32487", "Trinket", "Ashtongue Talisman of Swiftness", "Alt", "3", "Reputation", "Ashtongue Deathsworn (Exalted)", "Okuno")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",              "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",                "Alt", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",                "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",          "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller",     "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28041", "Trinket", "Bladefist's Breadth",             "PreRaid", "0", "Quest", "Overlord/Cruel's Intentions", "Hellfire Peninsula")

LoonBestInSlot:AddItem(spec, "30901", "MH", "Boundless Agony",              "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane",                   "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix",         "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "27846", "MH", "Claw of the Watcher",          "Alt", "1>2", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28524", "MH", "Emerald Ripper",               "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28584", "MH", "Big Bad Wolf's Paw",           "Alt", "1", "Drop", "The Big Bad Wolf", "Karazhan")
LoonBestInSlot:AddItem(spec, "30277", "MH", "Ripfang Paw",                  "PreRaid", "0", "Quest", "Declawing Doomclaw", "Netherstorm")
LoonBestInSlot:AddItem(spec, "28263", "MH", "Stellaris",                    "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")

LoonBestInSlot:AddItem(spec, "30881", "OH", "Blade of Infamy",              "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30865", "OH", "Tracker's Blade",              "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "28572", "OH", "Blade of the Unrequited",      "Alt", "1>3", "Drop", "Julianne", "Karazhan")
LoonBestInSlot:AddItem(spec, "29121", "OH", "Guile of Khoraazi",            "Alt", "1>2", "Reputation", "The Consortium (Exalted)", "Nagrand")
LoonBestInSlot:AddItem(spec, "28315", "OH", "Stormreaver Warblades",        "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "29372", "OH", "Void-Talon",                   "PreRaid", "0", "Vendor", "Dealer Jadyan", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32248", "2H", "Halberd of Desolation",        "BIS", "3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28436", "2H", "Bloodmoon",                    "Alt", "2>3", "Profession", "Master Axesmith (Blacksmithing)")
LoonBestInSlot:AddItem(spec, "28587", "2H", "Legacy",                       "Alt", "1>3", "Drop", "The Crone", "Karazhan")
LoonBestInSlot:AddItem(spec, "28435", "2H", "Mooncleaver",                  "Alt", "1", "Profession", "Master Axesmith (Blacksmithing)")
LoonBestInSlot:AddItem(spec, "27903", "2H", "Sonic Spear",                  "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade",                "PreRaid", "0", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "29329", "2H", "Terokk's Quill",               "PreRaid", "0", "Quest", "Terokk's Legacy", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "30906", "Ranged", "Bristleblitz Striker",     "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32336", "Ranged", "Black Bow of the Betrayer", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30105", "Ranged", "Serpent Spine Longbow",    "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol",    "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle",   "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28581", "Ranged", "Wolfslayer Sniper Rifle",  "Alt", "1>2", "Drop", "The Big Bad Wolf", "Karazhan")
LoonBestInSlot:AddItem(spec, "28504", "Ranged", "Steelhawk Crossbow",       "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "29351", "Ranged", "Wrathtide Longbow",        "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault (Heroic)")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket",         "PreRaid", "0", "Reputation", "Honor Hold (Exalted)", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow",           "PreRaid", "0", "Reputation", "Thrallmar (Exalted)", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "31323", "Ranged", "Don Santos' Famous Hunting Rifle", "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "31303", "Ranged", "Valanos' Longbow",         "PreRaid", "0", "Drop", "BOE World Drop")