local spec = LoonBestInSlot:RegisterSpec("Paladin", "Holy")

LoonBestInSlot:AddItem(spec, "30988", "Head", "Lightbringer Greathelm",         "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror","BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32354", "Head", "Crown of Empowered Fate",        "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30136", "Head", "Crystalforge Greathelm",         "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32472", "Head", "Justicebringer 2000 Specs",      "Alt", "2", "Profession", "Engineering(350)")
LoonBestInSlot:AddItem(spec, "30728", "Head", "Fathom-Helm of the Deeps",       "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29061", "Head", "Justicar Diadem",                "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",    "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28803", "Head", "Cowl of Nature's Breath",        "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28756", "Head", "Headdress of the High Potentate", "Alt", "1", "Drop", "Dust Covered Chest", "Karazhan")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood",                 "PreRaid", "0", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "32084", "Head", "Helmet of the Steadfast Champion", "PreRaid", "0", "Dungeon Token", "50 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28413", "Head", "Hallowed Crown",                 "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28348", "Head", "Moonglade Cowl",                 "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")
LoonBestInSlot:AddItem(spec, "25820", "Head", "Metallic Headband of Simm'onz",  "PreRaid", "0", "Quest", "Forge Camp: Annihilated", "Nagrand")

LoonBestInSlot:AddItem(spec, "30996", "Shoulders", "Lightbringer Pauldrons",            "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror","BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30878", "Shoulders", "Glimmering Steel Mantle",           "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30138", "Shoulders", "Crystalforge Pauldrons",            "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30097", "Shoulders", "Coral-Barbed Shoulderpads",         "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29064", "Shoulders", "Justicar Pauldrons",                "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion",  "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28631", "Shoulders", "Dragon-Quake Shoulderguards",       "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "28666", "Shoulders", "Pauldrons of the Justice-Seeker",   "Alt", "1", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28647", "Shoulders", "Forest Wind Shoulderpads",          "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders",        "PreRaid", "0", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons",                "PreRaid", "0", "Drop", "Grandmaster Vorpil", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27433", "Shoulders", "Pauldrons of Sufferance",           "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills ")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart",       "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",            "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand",          "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak",              "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32337", "Back", "Shroud of Forgiveness",              "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak",                   "Alt", "1>2", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted", "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28582", "Back", "Red Riding Hood's Cloak",            "Alt", "1", "Drop", "The Big Bad Wolf", "Karazhan")
LoonBestInSlot:AddItem(spec, "29354", "Back", "Light-Touched Stole of Altruism",    "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape",                  "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29375", "Back", "Althop's Cloak",                     "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "25805", "Back", "Mantle of Vivification",             "PreRaid", "0", "Quest", "Turning the Tide", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "25810", "Back", "Vicar's Cloak",                      "PreRaid", "0", "Quest", "The Will of the Warchief", "Hellfire Peninsula")

LoonBestInSlot:AddItem(spec, "30992", "Chest", "Lightbringer Chestpiece",           "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30904", "Chest", "Savior's Grasp",                    "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30134", "Chest", "Crystalforge Chestpiece",           "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29062", "Chest", "Justicar Chestpiece",               "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe",             "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28662", "Chest", "Breastplate of the Lightbinder",    "Alt", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "28735", "Chest", "Earthblood Chestguard",             "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk",                  "PreRaid", "0", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28230", "Chest", "Hallowed Garments",                 "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28202", "Chest", "Moonglade Robe",                    "PreRaid", "0", "Drop", "Nethermancer Sepethrea and Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "30298", "Chest", "Void Slayer's Tunic",               "PreRaid", "0", "Quest", "Dimensius the All-Devouring", "Netherstorm")

LoonBestInSlot:AddItem(spec, "30862", "Bracers", "Blessed Adamantite Bracers",  "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30869", "Bracers", "Howling Wind Bracers",        "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32571", "Bracers", "Dawnsteel Bracers",           "Alt", "3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "30047", "Bracers", "Blackfathom Warbands",        "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers",            "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "23539", "Bracers", "Blessed Bracers",             "Alt", "1>2", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker",  "Alt", "1", "Reputation", "Keepers of Time – Exalted")
LoonBestInSlot:AddItem(spec, "28512", "Bracers", "Bracers of Justice",          "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28503", "Bracers", "Whirlwind Bracers",           "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28511", "Bracers", "Bands of Indwelling",         "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29249", "Bracers", "Bands of the Benevolent",     "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls (Heroic)")
LoonBestInSlot:AddItem(spec, "28029", "Bracers", "Goldenvine Wraps",            "PreRaid", "0", "Quest", "Lost in Action", "Zangarmarsh")

LoonBestInSlot:AddItem(spec, "30112", "Gloves", "Glorious Gauntlets of Crestfall",  "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30983", "Gloves", "Lightbringer Gloves",              "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror", "Alt", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth",      "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "29976", "Gloves", "Worldstorm Gauntlets",             "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30135", "Gloves", "Crystalforge Gloves",              "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28505", "Gloves", "Gauntlets of Renewed Hope",        "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28520", "Gloves", "Gloves of Centering",              "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender",          "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29065", "Gloves", "Justicar Gloves",                  "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion",    "Alt", "1", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch",       "PreRaid", "0", "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "27457", "Gloves", "Life Bearer's Gauntlets",          "PreRaid", "0", "Drop", "Reinforced Fel Iron Chest", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "28304", "Gloves", "Prismatic Mittens of Mending",     "PreRaid", "0", "Drop", "Commander Sarannis", "The Botanica")
LoonBestInSlot:AddItem(spec, "29327", "Gloves", "Cryo-mitts", "PreRaid", "0",       "Quest", "Someone Else's Hard Work Pays Off", "Mana-Tombs")

LoonBestInSlot:AddItem(spec, "30897", "Belt", "Girdle of Hope",                 "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30030", "Belt", "Girdle of Fallen Stars",         "Alt", "2>3", "Drop", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29965", "Belt", "Girdle of the Righteous Path",   "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt",          "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28733", "Belt", "Girdle of Truth",                "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28655", "Belt", "Cord of Nature's Sustenance",    "Alt", "1", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt",                  "PreRaid", "0", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification",         "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "30932", "Belt", "Akama's Sash",                   "PreRaid", "0", "Quest", "Akama's Promise", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "30994", "Legs", "Lightbringer Leggings",          "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity",           "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32271", "Legs", "Kilt of Immortal Nature",        "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30893", "Legs", "Sun-touched Chain Leggings",     "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29991", "Legs", "Sunhawk Leggings",               "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30137", "Legs", "Crystalforge Leggings",          "Alt", "2", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt", "2", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30727", "Legs", "Gilded Trousers of Benediction", "Alt", "1", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28751", "Legs", "Heart-Flame Leggings",           "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28748", "Legs", "Legplates of the Innocent",      "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings",             "Alt", "1", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28742", "Legs", "Pantaloons of Repentance",       "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants",                "PreRaid", "0", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt",                  "PreRaid", "0", "Drop", "Warlord Kalithresh ", "The Steamvault (Heroic)")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt",        "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "30299", "Legs", "Starcaller's Plated Legguards",  "PreRaid", "0", "Quest", "Dimensius the All-Devouring", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30256", "Legs", "Pants of the Naaru",             "PreRaid", "0", "Quest", "Levixus the Soul Caller", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "32243", "Feet", "Pearl Inlaid Boots",             "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30027", "Feet", "Boots of Courage Unending",      "Alt", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light",      "Alt", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots",            "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots",                "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders",            "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28569", "Feet", "Boots of Valiance",              "Alt", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity",           "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "29251", "Feet", "Boots of the Pious",             "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar (Heroic)")
LoonBestInSlot:AddItem(spec, "28221", "Feet", "Boots of the Watchful Heart",    "PreRaid", "0", "Drop", "Captain Skarloc", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "27549", "Feet", "Wavefury Boots",                 "PreRaid", "0", "Drop", "Rokmar the Crackler", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "25792", "Feet", "Curate's Boots",                 "PreRaid", "0", "Quest", "Fel Embers", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity",     "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim",         "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence",      "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman",             "Alt", "1>3", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord",        "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "30377", "Neck", "Karja's Medallion",              "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara Netherstorm")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope",       "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor",        "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32238", "Ring", "Ring of Calming Waves",          "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer",   "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived",      "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth",        "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band",       "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30736", "Ring", "Ring of Flowing Light",          "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving",    "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29290", "Ring", "Violet Signet of the Grand Restorer", "Alt", "1", "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence",          "PreRaid", "0", "Reputation", "Honor Hold Revered", "Logistics Officer Ulrike")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band",                 "PreRaid", "0", "Reputation", "Thrallmar Revered", "Quartermaster Urgronn")
LoonBestInSlot:AddItem(spec, "27780", "Ring", "Ring of Fabled Hope",            "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband",                "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "31383", "Ring", "Spiritualist's Mark of the Sha'tar", "PreRaid", "0", "Quest", "Battle of the Crimson Watch", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring",           "PreRaid", "0", "Quest", "Hitting the Motherlode", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande",          "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops",               "BIS", "2>3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr",       "BIS", "1>3", "Dungeon Token", "G'eras", "41 Badge of Justice")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice",         "Alt", "1>3", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook",       "Alt", "1>3", "Reputation", "Lower City Revered")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle", "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic",              "PreRaid", "0", "Quest", "Gava'xi", "Nagrand")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor",         "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement",              "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter",              "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice",                  "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous",            "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity",                 "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon",              "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min",   "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light",              "PreRaid", "0", "Reputation", "The Sha'tar Exalted")
LoonBestInSlot:AddItem(spec, "25759", "MH", "Mogor's Anointing Club",           "PreRaid", "0", "Quest", "The Ring of Blood: The Final Challenge", "Nagrand")

LoonBestInSlot:AddItem(spec, "32255", "OH", "Felstone Bulwark",                 "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30882", "OH", "Bastion of Light",                 "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30911", "OH", "Scepter of Purification",          "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King",         "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29458", "OH", "Aegis of the Vindicator",          "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven",                  "Alt", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "29267", "OH", "Light-Bearer's Faith Shield",      "Alt", "1>2", "Dungeon Token", "33 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire",         "Alt", "1", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "29170", "OH", "Windcaller's Orb",                 "PreRaid", "0", "Reputation", "Cenarion Expedition (Exalted)", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "27772", "OH", "Stormshield of Renewal",           "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing",       "PreRaid", "0", "Drop", "Omor the Unscarred ", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "31493", "OH", "Netherwing Spiritualist's Charm",  "PreRaid", "0", "Quest", "Ally of the Netherwing", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "28592", "Libram", "Libram of Souls Redeemed",     "BIS", "1>3", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28296", "Libram", "Libram of the Lightbringer",   "Alt", "1>3", "Drop", "Commander Sarannis", "The Botanica")
LoonBestInSlot:AddItem(spec, "25644", "Libram", "Blessed Book of Nagrand",      "PreRaid", "0", "Quest", "The Ultimate Bloodsport", "Nagrand")