local spec = LoonBestInSlot:RegisterSpec("Paladin", "Ret")
LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",          "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32376", "Head", "Forest Prowler's Helm",              "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "32373", "Head", "Helm of the Illidari Shatterer",     "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30989", "Head", "Lightbringer War-Helm",              "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror",    "Alt", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32461", "Head", "Furious Gizmatic Goggles",           "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "30131", "Head", "Crystalforge War-Helm",              "Alt", "2", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion",    "Alt", "2", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29983", "Head", "Fel-Steel Warhelm",                  "Alt", "2", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",        "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29073", "Head", "Justicar Crown",                     "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw",                   "Alt", "1>2", "Quest", "The Warlord's Hideout", "Watcher Jhang, Zangarmarsh")
LoonBestInSlot:AddItem(spec, "31105", "Head", "Overlord's Helmet of Second Sight",  "PreRaid", "0", "Quest", "Teron Gorefiend, I am...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm",                   "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "27408", "Head", "Hope Bearer Helm",                   "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts")

LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",      "BIS", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders",             "Alt", "3", "Profession", "Leatherworking (375)", "")
LoonBestInSlot:AddItem(spec, "30997", "Shoulders", "Lightbringer Shoulderbraces",       "Alt", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "Alt", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "30133", "Shoulders", "Crystalforge Shoulderbraces",       "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion",  "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29075", "Shoulders", "Justicar Shoulderplates",           "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30740", "Shoulders", "Ripfiend Shoulderplates",           "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27771", "Shoulders", "Doomplate Shoulderguards",          "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog Heroic")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",          "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde",               "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "28865", "Shoulders", "High Warlord's Scaled Shoulders",   "PreRaid", "0", "PvP", "3156 Honor Points", "10 Arathi Basin Mark")
LoonBestInSlot:AddItem(spec, "28713", "Shoulders", "Grand Marshal's Scaled Shoulders",  "PreRaid", "0", "PvP", "3156 Honor Points", "10 Arathi Basin Mark")

LoonBestInSlot:AddItem(spec, "30098", "Back", "Razor-Scale Battlecloak",    "BIS", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "33122", "Back", "Cloak of Darkness",          "BIS", "1>3", "Profession", "Leatherworking (360)")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud",      "Alt Hit", "1>3", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap",             "Alt", "1>3", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter",       "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28249", "Back", "Capacitus' Cloak of Calibration", "PreRaid", "0", "Drop", "Cache of the Legion", "The Mechanar")

LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard",               "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30990", "Chest", "Lightbringer Breastplate",          "Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror", "Alt", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30129", "Chest", "Crystalforge Breastplate",          "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest",           "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30102", "Chest", "Krakken-Heart Breastplate",         "Alt", "2", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29071", "Chest", "Justicar Breastplate",              "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic",                 "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate",      "PreRaid", "0", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest",                 "PreRaid", "0", "Profession", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28403", "Chest", "Doomplate Chestguard",              "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "24396", "Chest", "Vest of Vengeance",                 "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace")
LoonBestInSlot:AddItem(spec, "31548", "Chest", "Blackened Chestplate",              "PreRaid", "0", "Quest", "Showdown", "Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes",  "BIS", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32568", "Bracers", "Swiftsteel Bracers",              "Alt", "3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "30057", "Bracers", "Bracers of Eradication",          "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28795", "Bracers", "Bladespire Warbands",             "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "23537", "Bracers", "Black Felsteel Bracers",          "Alt", "1>2", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "28646", "Bracers", "General's Scaled Bracers",        "PreRaid", "0", "PvP", "5897 Honor Points", "20 Warsong Gulch Marks")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers",        "PreRaid", "0", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "27918", "Bracers", "Bands of Syth",                   "PreRaid", "0", "Drop", "Darkweaver Syth", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",   "BIS", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation",           "BIS", "3", "Drop", "Essence of Anger", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",            "Alt", "1>3", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets",    "PreRaid", "0", "Quest", "The Flesh Lies...", "Agent Araxes, Netherstorm")
LoonBestInSlot:AddItem(spec, "18823", "Gloves", "Aged Core Leather Gloves",     "PreRaid", "0", "Drop", "Golemagg the Incinerator, Magmadar, or Garr", "Molten Core")
LoonBestInSlot:AddItem(spec, "29509", "Gloves", "Windstrike Gloves",            "PreRaid", "0", "Profession", "Leatherworking")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths",     "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28779", "Belt", "Girdle of the Endless Pit",      "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",          "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer",      "Alt Hit", "1>3", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery",            "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27755", "Belt", "Girdle of Gallantry",            "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog Heroic")
LoonBestInSlot:AddItem(spec, "27760", "Belt", "Dunewind Sash",                  "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt",          "PreRaid", "0", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "27985", "Belt", "Deathforge Girdle",              "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings",              "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30993", "Legs", "Lightbringer Greaves",               "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29950", "Legs", "Greaves of the Bloodwarder",         "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings",                 "Alt", "1>3", "Quest", "Special Delivery to Shattrath City", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent",       "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30132", "Legs", "Crystalforge Greaves",               "Alt", "2", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt", "2", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings",            "PreRaid", "0", "Quest", "Showdown - Baron Sablemane/Showdown", "Rexxar, Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots",           "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32345", "Feet", "Dreadboots of the Legion",       "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30081", "Feet", "Warboots of Obliteration",       "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28608", "Feet", "Ironstriders of Urgency",        "Alt", "1>3", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "29951", "Feet", "Star-Strider Boots",             "Alt", "2", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots",               "Alt", "2", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",           "Alt Hit", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots",             "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots",              "PreRaid", "0", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "28176", "Feet", "Sha'tari Wrought Greaves",       "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust",            "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28318", "Feet", "Obsidian Clodstompers",          "PreRaid", "0", "Drop", "High Botanist Freywinn", "The Botanica")

LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous",        "BIS", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares",   "BIS Hit", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",          "Alt Hit", "1>3", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",           "Alt", "1>3", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28745", "Neck", "Mithril Chain of Heroism",       "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29119", "Neck", "Haramad's Bargain",              "PreRaid", "0", "Reputation", "The Consortium (Exalted)", "Paulsta'ats / Karaaz")
LoonBestInSlot:AddItem(spec, "31275", "Neck", "Necklace of Trophies",           "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker",               "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",          "BIS", "1>3", "Reputation", "Nakodu", "Lower City Exalted")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation",            "BIS", "3", "Drop", "Trash rop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General",     "BIS Hit", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring",   "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30061", "Ring", "Ancestral Ring of Conquest",     "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",       "Alt Hit", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity",            "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28730", "Ring", "Mithril Band of the Unscarred",  "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt", "1",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",           "Alt", "1", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29177", "Ring", "A'dal's Command",                "PreRaid", "0", "Reputation", "The Sha'tar Exalted", "Almaador, Shattrath City")
LoonBestInSlot:AddItem(spec, "31920", "Ring", "Shaffar's Band of Brutality",    "PreRaid", "0", "Drop", "Yor", "Mana-Tombs Heroic")
LoonBestInSlot:AddItem(spec, "30365", "Ring", "Overseer's Signet",              "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara", "Anchorite Karja, Netherstorm (Aldor)")
LoonBestInSlot:AddItem(spec, "31380", "Ring", "Acrobat's Mark of the Sha'tar",  "PreRaid", "0", "Quest", "Battle of the Crimson Watch", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",          "BIS", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",            "BIS", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",      "Alt", "1>3", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",      "Alt", "3", "Quest", "Darkmoon Blessings Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",     "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew",       "Alt", "1>3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",            "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "Alt", "1>2", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",      "Alt", "1>2", "Quest", "Darkmoon Blessings Deck", "Darkmoon Fair")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial",        "Alt", "1", "Drop", "Julianne", "Karazhan")
LoonBestInSlot:AddItem(spec, "29776", "Trinket", "Core of Ar'kelos",            "PreRaid", "0", "Quest", "Ar'kelos the Guardian")

LoonBestInSlot:AddItem(spec, "32332", "2H", "Torch of the Damned",              "BIS", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30902", "2H", "Cataclysm's Edge",                 "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "33688", "2H", "Vengeful Gladiator's Greatsword",  "Alt", "3", "PvP", "3750 Arena Points")
LoonBestInSlot:AddItem(spec, "28430", "2H", "Lionheart Executioner",            "Alt", "2>3", "Profession", "Master Swordsmith (Blacksmithing)")
LoonBestInSlot:AddItem(spec, "29993", "2H", "Twinblade of the Phoenix",         "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30090", "2H", "World Breaker",                    "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28442", "2H", "Stormherald",                      "Alt", "2>3", "Profession", "Blacksmithing (375)")
LoonBestInSlot:AddItem(spec, "28773", "2H", "Gorehowl",                         "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30722", "2H", "Ethereum Nexus-Reaver",            "Alt", "1", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28441", "2H", "Deep Thunder",                     "Alt", "1", "Profession", "Master Hammersmith (Blacksmithing)")
LoonBestInSlot:AddItem(spec, "24550", "2H", "Gladiator's Greatsword",           "Alt", "1", "PvP", "2750 Arena Points")
LoonBestInSlot:AddItem(spec, "29356", "2H", "Quantum Blade",                    "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "31322", "2H", "The Hammer of Destiny",            "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "23541", "2H", "Khorium Champion",                 "PreRaid", "0", "Profession", "Blacksmithing")
LoonBestInSlot:AddItem(spec, "27986", "2H", "Crow Wing Reaper",                 "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "27484", "Libram", "Libram of Avengement",         "BIS", "1>3", "Drop", "The Maker", "The Blood Furnace Heroic")
LoonBestInSlot:AddItem(spec, "22401", "Libram", "Libram of Hope",               "Alt", "1>2", "Drop", "Isalien", "Dire Maul East")
LoonBestInSlot:AddItem(spec, "23203", "Libram", "Libram of Fervor",             "Alt", "1>2", "Drop", "BOE World Drop")