local spec = LoonBestInSlot:RegisterSpec("Priest", "Shadow")
LoonBestInSlot:AddItem(spec, "31064", "Head", "Hood of Absolution",             "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31097", "Head", "Helm of the Forgotten Conqueror","Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "Alt", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32494", "Head", "Destruction Holo-gogs",          "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "29986", "Head", "Cowl of the Grand Engineer",     "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30161", "Head", "Hood of the Avatar",             "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30243", "Head", "Helm of the Vanquished Defender", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood",               "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29058", "Head", "Soul-Collar of the Incarnate",   "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29761", "Head", "Helm of the Fallen Defender",    "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion",               "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28169", "Head", "Mag'hari Ritualist's Horns",     "PreRaid", "0", "Quest", "There Is No Hope", "Nagrand")
LoonBestInSlot:AddItem(spec, "31104", "Head", "Evoker's Helmet of Second Sight", "PreRaid", "0", "Quest", " Teron Gorefiend, I am...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28193", "Head", "Mana-Etched Crown",              "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28183", "Head", "Hydromancer's Headwrap",         "PreRaid", "0", "Quest", "The Warlord's Hideout", "The Steamvault")

LoonBestInSlot:AddItem(spec, "31070", "Shoulders", "Shoulderpads of Absolution",        "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31101", "Shoulders", "Pauldrons of the Forgotten Conqueror", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought",          "Alt", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle",                   "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32338", "Shoulders", "Blood-cursed Shoulderpads",         "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "21869", "Shoulders", "Frozen Shadoweave Shoulders",       "Alt", "1>3", "Profession", "Shadoweave Tailoring (355)")
LoonBestInSlot:AddItem(spec, "30163", "Shoulders", "Wings of the Avatar",               "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30249", "Shoulders", "Pauldrons of the Vanquished Defender", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29060", "Shoulders", "Soul-Mantle of the Incarnate",      "Alt", "1", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29764", "Shoulders", "Pauldrons of the Fallen Defender",  "Alt", "1", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "27778", "Shoulders", "Spaulders of Oblivion",             "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders",             "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart",       "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32590", "Back", "Nethervoid Cloak",                   "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",            "Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council",      "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "24252", "Back", "Cloak of the Black Void",            "Alt", "1", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant",        "Alt", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28570", "Back", "Shadow-Cloak of Dalaran",            "Alt", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "29813", "Back", "Cloak of Woven Energy",              "PreRaid", "0", "Quest", "Hitting the Motherlode", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31140", "Back", "Cloak of Entropy",                   "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "31065", "Chest", "Shroud of Absolution",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31089", "Chest", "Chestguard of the Forgotten Conqueror","BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30913", "Chest", "Robes of Rhonin",                   "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch",        "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "21871", "Chest", "Frozen Shadoweave Robe",            "Alt", "1>3", "Profession", "Shadoweave Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30159", "Chest", "Shroud of the Avatar",               "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30237", "Chest", "Chestguard of the Vanquished Defender", "Alt", "2", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29056", "Chest", "Shroud of the Incarnate",           "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29753", "Chest", "Chestguard of the Fallen Defender", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "31297", "Chest", "Robe of the Crimson Order",         "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29341", "Chest", "Auchenai Anchorite's Robe",         "PreRaid", "0", "Quest", "Everything Will Be Alright", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "28232", "Chest", "Robe of Oblivion",                  "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28342", "Chest", "Warp Infused Drape",                "PreRaid", "0", "Drop", "Warp Splinter", "The Botanica")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought",   "BIS", "3", "Drop", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation",        "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32270", "Bracers", "Focused Mana Bindings",       "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands",        "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok",            "Alt", "1>2", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "28515", "Bracers", "Bands of Nefarious Deeds",    "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28477", "Bracers", "Harbinger Bands",             "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "27462", "Bracers", "Crimson Bracers of Gloom",    "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "29240", "Bracers", "Bands of Negation",           "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28174", "Bracers", "Shattrath Wraps",             "PreRaid", "0", "Quest", "The Soul Devices", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "31061", "Gloves", "Handguards of Absolution",         "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31092", "Gloves", "Gloves of the Forgotten Conqueror","BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought",     "Alt", "1>3", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps",           "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30725", "Gloves", "Anger-Spark Gloves",               "Alt", "1", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30160", "Gloves", "Handguards of the Avatar",         "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30240", "Gloves", "Gloves of the Vanquished Defender", "Alt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29317", "Gloves", "Tempest's Touch",                  "PreRaid", "0", "Quest", "Return to Andormu", "Caverns of Time")
LoonBestInSlot:AddItem(spec, "27537", "Gloves", "Gloves of Oblivion",               "PreRaid", "0", "Drop", "Warchief Kargath Bladefist", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity",          "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30888", "Belt", "Anetheron's Noose",              "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting",               "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors",      "Alt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination",            "Alt", "1>2", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration",     "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "27843", "Belt", "Glyph-Lined Sash",               "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "29241", "Belt", "Belt of Depravity",              "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz (Heroic)")
LoonBestInSlot:AddItem(spec, "24395", "Belt", "Mindfire Waistband",             "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace")
LoonBestInSlot:AddItem(spec, "31461", "Belt", "A'dal's Gift",                   "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements",     "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32367", "Legs", "Leggings of Devastation",            "Alt", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31067", "Legs", "Leggings of Absolution",             "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31098", "Legs", "Leggings of the Forgotten Conqueror", "Alt", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "29972", "Legs", "Trousers of the Astromancer",        "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30162", "Legs", "Leggings of the Avatar",             "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30246", "Legs", "Leggings of the Vanquished Defender", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants",                  "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle",     "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "28594", "Legs", "Trial-Fire Trousers",                "Alt", "1", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30531", "Legs", "Breeches of the Occultist",          "PreRaid", "0", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "30532", "Legs", "Kirin Tor Master's Trousers",        "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "28185", "Legs", "Khadgar's Kilt of Abjuration",       "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "27948", "Legs", "Trousers of Oblivion",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller",      "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "21870", "Feet", "Frozen Shadoweave Boots",        "BIS", "1>3", "Profession", "Shadoweave Tailoring (365)")
LoonBestInSlot:AddItem(spec, "30894", "Feet", "Blue Suede Shoes",               "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30050", "Feet", "Boots of the Shifting Nightmare", "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian",   "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28585", "Feet", "Ruby Slippers",                  "Alt", "1", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling",           "Alt", "1", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers",              "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "35319", "Neck", "Vindicator's Pendant of Subjugation", "BIS", "3", "PvP", "15300 Honor Points, 10 Eye of the Storm Marks")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace",   "BIS", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30666", "Neck", "Ritssyn's Lost Pendant",             "Alt", "1>3", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury",        "Alt", "1", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "18814", "Neck", "Choker of the Fire Lord",            "PreRaid", "0", "Drop", "Ragnaros", "Molten Core")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace",           "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "31693", "Neck", "Natasha's Arcane Filament",          "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29368", "Neck", "Manasurge Pendant",                  "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge",      "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor",        "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms",        "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage",       "Alt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils",          "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29922", "Ring", "Band of Al'ar",                  "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28793", "Ring", "Band of Crimson Fury",           "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence",             "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift",                  "PreRaid", "0", "Reputation", "Cenarion Expedition Exalted", "Fedryen Swiftspear")
LoonBestInSlot:AddItem(spec, "28555", "Ring", "Seal of the Exorcist",           "PreRaid", "0", "Dungeons", "50 Spirit Shard", "Spirit Sage Gartok and Spirit Sage Zran")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet",                  "PreRaid", "0", "Reputation", "The Scryers Exalted", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa",        "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "19147", "Ring", "Ring of Spell Power",            "PreRaid", "0", "Drop", "4 bosses", "Molten Core")
LoonBestInSlot:AddItem(spec, "31290", "Ring", "Band of Dominion",               "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "31075", "Ring", "Evoker's Mark of the Redemption", "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30366", "Ring", "Manastorm Band",                 "PreRaid", "0", "Quest", "Shutting Down Manaforge Ara", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29793", "Ring", "Signet of the Violet Tower",     "PreRaid", "0", "Quest", "Down With Daellis	Netherstorm")

LoonBestInSlot:AddItem(spec, "32483", "Trinket", "The Skull of Gul'dan",            "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",          "BIS", "3", "Quest", "Darkmoon Blessings Deck", "Darkmoon Fair") -- beta
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent",     "BIS", "1>3", "Dungeon Token", "41 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28789", "Trinket", "Eye of Magtheridon",              "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye",                "Alt", "1>3", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem",               "PreRaid", "0", "Reputation", "The Scryers Revered", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "28223", "Trinket", "Arcanist's Stone",                "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "26055", "Trinket", "Oculus of the Hidden Eye",        "PreRaid", "0", "Drop", "Shirrak the Dead Watcher", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "27922", "Trinket", "Mark of Defiance",                "PreRaid", "0", "PvP", "30 Marks Honor Hold")
LoonBestInSlot:AddItem(spec, "27924", "Trinket", "Mark of Defiance",                "PreRaid", "0", "PvP", "30 Mark of Thrallmar")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel",   "BIS", "3", "PvP", "3150 Arena Points")
LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury",         "BIS", "3", "Drop", "	High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement",          "Alt", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest",         "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade",          "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets",   "PreRaid", "0", "Reputation", "Lower City Exalted", "Nakodu")
LoonBestInSlot:AddItem(spec, "27543", "MH", "Starlight Dagger",             "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens (Heroic)")

LoonBestInSlot:AddItem(spec, "29272", "OH", "Orb of the Soul-Eater",        "BIS", "1>3", "Dungeon Token", "25 Badge of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets",    "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32361", "OH", "Blind-Seers Icon",             "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack",           "PreRaid", "0", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "19309", "OH", "Tome of Shadow Force",         "PreRaid", "0", "PvP", "4760 Honor Points, 25 Alterac Valley Marks")
LoonBestInSlot:AddItem(spec, "19315", "OH", "Therazane's Touch",            "PreRaid", "0", "PvP", "4760 Honor Points, 25 Alterac Valley Marks")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance",    "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "29982", "Wand", "Wand of the Forgotten Star",     "BIS", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32343", "Wand", "Wand of Prismatic Focus",        "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "29350", "Wand", "The Black Stalk",                "Alt", "1>2", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "32872", "Wand", "Illidari Rod of Discipline",     "Alt", "1", "Quest", "Subdue the Subduer", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28673", "Wand", "Tirisfal Wand of Ascendancy",    "Alt", "1", "Drop", "Shade of Aran", "Karazhan")