local spec = LoonBestInSlot:RegisterSpec("Rogue", "")

LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",      "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31027", "Head", "Slayer's Helm",                  "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31096", "Head", "Helm of the Forgotten Vanquisher", "Alt", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30146", "Head", "Deathmantle Helm",               "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32478", "Head", "Deathblow X11 Goggles",          "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "29044", "Head", "Netherblade Facemask",           "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",    "Alt", "1>2", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28732", "Head", "Cowl of Defiance",               "Alt", "1", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28796", "Head", "Malefic Mask of the Shadows",    "Alt", "1", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm",               "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw",               "PreRaid", "0", "Quest", "The Warlord's Hideout", "Watcher Jhang, Zangarmarsh")

LoonBestInSlot:AddItem(spec, "31030", "Shoulders", "Slayer's Shoulderpads",             "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31102", "Shoulders", "Pauldrons of the Forgotten Vanquisher", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders",             "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32377", "Shoulders", "Mantle of Darkness",                "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30149", "Shoulders", "Deathmantle Shoulderpads",          "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",      "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29047", "Shoulders", "Netherblade Shoulderpads",          "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion",  "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",          "Alt", "1", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets",       "PreRaid", "0", "Quest", "Fel Embers", "Magus Zabraxis, Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29148", "Shoulders", "Blackened Leather Spaulders",       "PreRaid", "0", "Reputation", "Kurenai (Revered)", "Nagrand")
LoonBestInSlot:AddItem(spec, "29147", "Shoulders", "Talbuk Hide Spaulders",             "PreRaid", "0", "Reputation", "The Mag'har (Revered)", "Nagrand")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",  "Alt", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap",             "Alt", "1>2", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28777", "Back", "Cloak of the Pit Stalker",   "Alt", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29382", "Back", "Blood Knight War Cloak",     "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28032", "Back", "Delicate Green Poncho",      "PreRaid", "0", "Quest", "Bring Me The Egg!", "Nagrand")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud",      "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")

LoonBestInSlot:AddItem(spec, "31028", "Chest", "Slayer's Chestguard",               "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31090", "Chest", "Chestguard of the Forgotten Vanquisher", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard",               "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic",               "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30101", "Chest", "Bloodsea Brigand's Vest",           "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30144", "Chest", "Deathmantle Chestguard",            "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic",                 "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29045", "Chest", "Netherblade Chestpiece",            "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28264", "Chest", "Wastewalker Tunic",                 "PreRaid", "0", "Drop", "Keli'dan the Breaker", "The Blood Furnace (Heroic)")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest",                 "PreRaid", "0", "Profession", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30933", "Chest", "Hauberk of Karabor",                "PreRaid", "0", "Quest", "Varedis Must Be Stopped", "The Aldor/Scryers")

LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands",             "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32580", "Bracers", "Swiftstrike Bracers",         "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs",                "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending",         "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32647", "Bracers", "Shard-bound Bracers",         "Alt", "2", "Reputation", "Ogri'la (Exalted)", "Jho'nass, Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29246", "Bracers", "Nightfall Wristguards",       "Alt", "1>2", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards",   "Alt", "1>2", "Quest", "The Soul Devices", "Spy To'gun, Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers",        "PreRaid", "0", "Drop", "Elemental Leatherworking (375)")

LoonBestInSlot:AddItem(spec, "31026", "Gloves", "Slayer's Handguards",              "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31093", "Gloves", "Gloves of the Forgotten Vanquisher", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation",               "Alt", "3", "Drop", "Essence of Anger", "Black Temple")
LoonBestInSlot:AddItem(spec, "30145", "Gloves", "Deathmantle Handguards",           "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",       "Alt", "2", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29048", "Gloves", "Netherblade Gloves",               "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion",    "Alt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",                "Alt", "1>2", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "28506", "Gloves", "Gloves of Dexterous Manipulation", "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "25685", "Gloves", "Fel Leather Gloves",               "PreRaid", "0", "Profession", "Leatherworking (340)")
LoonBestInSlot:AddItem(spec, "30003", "Gloves", "Gloves of the Nether-Stalker",     "PreRaid", "0", "Quest", "Dealing with the Overmaster", "Netherstorm")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths",         "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32265", "Belt", "Shadow-walker's Cord",               "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt",         "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow",                "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer",          "Alt", "1>2", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",              "Alt", "1", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28750", "Belt", "Girdle of Treachery",                "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt",                  "PreRaid", "0", "Profession", "Elemental Leatherworking")
LoonBestInSlot:AddItem(spec, "30372", "Belt", "Socrethar's Girdle",                 "PreRaid", "0", "Quest", "Turning Point", "Voren'thal the Seer, Shattrath City")
LoonBestInSlot:AddItem(spec, "31464", "Belt", "Naaru Belt of Precision",            "PreRaid", "0", "Quest", "How to Break Into the Arcatraz", "A'dal, Shattrath City")

LoonBestInSlot:AddItem(spec, "31029", "Legs", "Slayer's Legguards",                 "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31099", "Legs", "Leggings of the Forgotten Vanquisher", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons",          "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30148", "Legs", "Deathmantle Legguards",              "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves",                  "Alt", "1>3", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "29995", "Legs", "Leggings of Murderous Intent",       "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29046", "Legs", "Netherblade Breeches",               "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29766", "Legs", "Leggings of the Fallen Champion",    "Alt", "1>2", "Token", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "27837", "Legs", "Wastewalker Leggings",               "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "25687", "Legs", "Fel Leather Leggings",               "PreRaid", "0", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings",            "PreRaid", "0", "Quest", "Showdown - Baron Sablemane/Showdown", "Rexxar, Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots",           "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",           "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness",        "Alt", "2", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots",              "PreRaid", "0", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "30939", "Feet", "Felboar Hide Shoes",             "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Borak, Son of Oronok, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares",       "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades",          "Alt", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",              "Alt", "1>3", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "24114", "Neck", "Braided Eternium Chain",             "Alt", "1>3", "Profession", "Jewelcrafting (360)")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                     "Alt", "2", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem",      "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",               "Alt", "1", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "25562", "Neck", "Earthen Mark of Razing",             "PreRaid", "0", "Quest", "Gurok the Usurper", "Gordawg, Nagrand")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring",                  "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion",           "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent",               "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality",                      "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General",             "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",               "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",                   "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity",                    "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin",   "Alt", "1",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",                     "Alt", "1", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28791", "Ring", "Ring of the Recalcitrant",               "Alt", "1", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",                  "PreRaid", "0", "Reputation", "Nakodu", "Lower City Exalted")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption",        "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Thane Yoregar / Overlord Or'barokh, Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "30860", "Ring", "Kaylaan's Signet",                       "PreRaid", "0", "Quest", "Deathblow to the Legion", "Ishanah, Shattrath City")
LoonBestInSlot:AddItem(spec, "30973", "Ring", "Band of Anguish",                        "PreRaid", "0", "Quest", "News of Victory", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "30450", "Trinket", "Warp-Spring Coil",                "BIS", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",              "BIS", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",         "Alt", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "32492", "Trinket", "Ashtongue Talisman of Lethality", "Alt", "3", "Drop", "Ashtongue Deathsworn", "Black Temple")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",                "Alt", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",                "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial",            "Alt", "1", "Drop", "Julianne", "Karazhan")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",          "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller",     "PreRaid", "0", "Drop", "Temporus", "The Black Morass")

LoonBestInSlot:AddItem(spec, "32837", "MH", "Warglaive of Azzinoth",        "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30881", "MH", "Blade of Infamy",              "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32471", "MH", "Shard of Azzinoth",            "BIS Dagger", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "33762", "MH", "Vengeful Gladiator's Slicer",  "Alt", "3", "PvP", "2625 Arena Points")
LoonBestInSlot:AddItem(spec, "33762", "MH", "Vengeful Gladiator's Slicer",  "Alt", "3", "PvP", "2625 Arena Points")
LoonBestInSlot:AddItem(spec, "32052", "MH", "Merciless Gladiator's Slicer", "Alt", "3", "PvP", "1300 Arena Points")
LoonBestInSlot:AddItem(spec, "33754", "MH", "Vengeful Gladiator's Shanker", "Alt Dagger", "3", "PvP", "2625 Points")
LoonBestInSlot:AddItem(spec, "30082", "MH", "Talon of Azshara",             "Alt", "2>3", "Drop", "Morogrim Tidewalker", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike",                 "Alt", "2>3", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "30103", "MH", "Fang of Vashj",                "Alt Dagger", "2", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix",         "Alt", "2", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King",          "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32052", "MH", "Merciless Gladiator's Slicer", "Alt", "2", "PvP", "1300 Arena Points")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw",                    "Alt", "1", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "31332", "MH", "Blinkstrike",                  "Alt", "1", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "28768", "MH", "Malchazeen",                   "Alt Dagger", "1", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30733", "MH", "Hope Ender",                   "Alt", "1", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29124", "MH", "Vindicator's Brand",           "PreRaid", "0", "Reputation", "Exalted with The Aldor")
LoonBestInSlot:AddItem(spec, "31331", "MH", "The Night Blade",              "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "28312", "MH", "Gladiator's Shanker",          "PreRaid", "0", "PvP", "14228 Honor Points, 20 Eye of the Storm Marks")

LoonBestInSlot:AddItem(spec, "32838", "OH", "Warglaive of Azzinoth",        "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32369", "OH", "Blade of Savagery",            "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "33756", "OH", "Vengeful Gladiator's Shiv",    "BIS Dagger", "3", "PvP", "1125 Points", "Arena")
LoonBestInSlot:AddItem(spec, "33734", "OH", "Vengeful Gladiator's Quickblade", "Alt", "3", "PvP", "1125 Points", "Arena")
LoonBestInSlot:AddItem(spec, "32027", "OH", "Merciless Gladiator's Quickblade", "Alt", "3", "PvP", "550 Points", "Arena")
LoonBestInSlot:AddItem(spec, "30865", "OH", "Tracker's Blade",              "Alt Dagger", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32027", "OH", "Merciless Gladiator's Quickblade", "Alt", "2", "PvP", "1125 Points", "Arena")
LoonBestInSlot:AddItem(spec, "32046", "OH", "Merciless Gladiator's Shiv",   "Alt Dagger", "2", "PvP", "1125 Points", "Arena")
LoonBestInSlot:AddItem(spec, "28189", "OH", "Latro's Shifting Sword",       "Alt", "1>2", "Drop", "The Black Morass", "Aeonus")
LoonBestInSlot:AddItem(spec, "29275", "OH", "Searing Sunblade",             "Alt Dagger", "1", "Dungeon Token", "50 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28307", "OH", "Gladiator's Quickblade",       "PreRaid", "0", "PvP", "1125 Arena Points")
LoonBestInSlot:AddItem(spec, "28310", "OH", "Gladiator's Shiv",             "PreRaid", "0", "PvP", "1125 Arena Points")

LoonBestInSlot:AddItem(spec, "29949", "Ranged", "Arcanite Steam-Pistol",    "BIS", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32326", "Ranged", "Twisted Blades of Zarak",  "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "28772", "Ranged", "Sunfury Bow of the Phoenix", "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30724", "Ranged", "Barrel-Blade Longrifle",   "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29151", "Ranged", "Veteran's Musket",         "Alt", "1>2", "Reputation", "Honor Hold", "Exalted")
LoonBestInSlot:AddItem(spec, "29152", "Ranged", "Marksman's Bow",           "Alt", "1>2", "Reputation", "Thrallmar", "Exalted")
LoonBestInSlot:AddItem(spec, "30279", "Ranged", "Mama's Insurance",         "PreRaid", "0", "Quest", "Declawing Doomclaw", "Netherstorm")
LoonBestInSlot:AddItem(spec, "30227", "Ranged", "Mark V's Throwing Star",   "PreRaid", "0", "Quest", "Mark V is Alive!", "Netherstorm")