local spec = LoonBestInSlot:RegisterSpec("Shaman", "Resto")

LoonBestInSlot:AddItem(spec, "31012", "Head", "Skyshatter Helmet",              "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32241", "Head", "Helm of Soothing Currents",      "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30166", "Head", "Cataclysm Headguard",            "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32475", "Head", "Living Replicator Specs",        "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",    "Alt", "1>3", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29028", "Head", "Cyclone Headdress",              "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30728", "Head", "Fathom-Helm of the Deeps",       "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "24264", "Head", "Whitemend Hood",                 "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29508", "Head", "Living Dragonscale Helm",        "Alt", "1>2", "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "27759", "Head", "Headdress of the Tides",         "PreRaid", "0", "Drop", "Ghaz'an", "The Underbog (Heroic)")

LoonBestInSlot:AddItem(spec, "31022", "Shoulders", "Skyshatter Shoulderpads",               "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector",  "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32579", "Shoulders", "Living Earth Shoulders",                "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30168", "Shoulders", "Cataclysm Shoulderguards",              "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion",  "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30097", "Shoulders", "Coral-Barbed Shoulderpads",             "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29031", "Shoulders", "Cyclone Shoulderpads",                  "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion",      "Alt", "1>3", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28631", "Shoulders", "Dragon-Quake Shoulderguards",           "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "21874", "Shoulders", "Primal Mooncloth Shoulders",            "PreRaid", "0", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "27775", "Shoulders", "Hallowed Pauldrons",                    "PreRaid", "0", "Drop", "Grandmaster Vorpil", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "27826", "Shoulders", "Mantle of the Sea Wolf",                "PreRaid", "0", "Drop", "Tavarok ", "Mana-Tombs (Heroic)")

LoonBestInSlot:AddItem(spec, "32524", "Back", "Shroud of the Highborne",                "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "34012", "Back", "Shroud of the Final Stand",              "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29989", "Back", "Sunshower Light Cloak",                  "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28765", "Back", "Stainless Cloak of the Pure Hearted",    "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "31329", "Back", "Lifegiving Cloak",                       "Alt", "1>2", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "24254", "Back", "White Remedy Cape",                      "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "27448", "Back", "Cloak of the Everliving",                "PreRaid", "0", "Drop", "Watchkeeper Gargolmar", "Hellfire Ramparts (Heroic)")

LoonBestInSlot:AddItem(spec, "31016", "Chest", "Skyshatter Chestguard",                 "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30887", "Chest", "Golden Links of Restoration",           "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30164", "Chest", "Cataclysm Chestguard",                  "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29921", "Chest", "Fire Crest Breastplate",                "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk",                      "Alt", "1>3", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "21875", "Chest", "Primal Mooncloth Robe",                 "Alt", "1>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "29029", "Chest", "Cyclone Hauberk",                       "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion",     "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "23527", "Chest", "Earthpeace Breastplate",                "PreRaid", "0", "Profession", "Blacksmithing")

LoonBestInSlot:AddItem(spec, "32577", "Bracers", "Living Earth Bindings",       "BIS", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32584", "Bracers", "Swiftheal Wraps",             "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "32582", "Bracers", "Bracers of Renewed Life",     "BIS", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30869", "Bracers", "Howling Wind Bracers",        "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30047", "Bracers", "Blackfathom Warbands",        "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32516", "Bracers", "Wraps of Purification",       "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers",            "Alt", "1>3", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28503", "Bracers", "Whirlwind Bracers",           "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "29183", "Bracers", "Bindings of the Timewalker",  "Alt", "1>2", "Reputation", "Keepers of Time – Exalted")
LoonBestInSlot:AddItem(spec, "28194", "Bracers", "Primal Surge Bracers",        "PreRaid", "0", "Drop", "Aeonus", "The Black Morass")

LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth",      "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32275", "Gloves", "Spiritwalker Gauntlets",           "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "31007", "Gloves", "Skyshatter Gloves",                "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "Alt", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29976", "Gloves", "Worldstorm Gauntlets",             "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30165", "Gloves", "Cataclysm Gloves",                 "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28520", "Gloves", "Gloves of Centering",              "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28521", "Gloves", "Mitts of the Treemender",          "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29032", "Gloves", "Cyclone Gloves",                   "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion",    "Alt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "27806", "Gloves", "Fathomheart Gauntlets",            "PreRaid", "0", "Drop", "Warlord Kalithresh", "The Steamvault")
LoonBestInSlot:AddItem(spec, "28304", "Gloves", "Prismatic Mittens of Mending",     "PreRaid", "0", "Drop", "Commander Sarannis", "The Botanica")
LoonBestInSlot:AddItem(spec, "29506", "Gloves", "Gloves of the Living Touch",       "PreRaid", "0", "Profession", "Leatherworking (365)")

LoonBestInSlot:AddItem(spec, "32258", "Belt", "Naturalist's Preserving Cinch",  "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32339", "Belt", "Belt of Primal Majesty",         "BIS", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "30895", "Belt", "Angelista's Sash",               "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30030", "Belt", "Girdle of Fallen Stars",         "Alt", "2>3", "Alt", "Trash Drop", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt",                  "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "21873", "Belt", "Primal Mooncloth Belt",          "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "28567", "Belt", "Belt of Gale Force",             "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "29250", "Belt", "Cord of Sanctification",         "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "31019", "Legs", "Skyshatter Leggings",                "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30912", "Legs", "Leggings of Eternity",               "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32271", "Legs", "Kilt of Immortal Nature",            "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30893", "Legs", "Sun-touched Chain Leggings",         "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29991", "Legs", "Sunhawk Leggings",                   "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30167", "Legs", "Cataclysm Legguards",                "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28751", "Legs", "Heart-Flame Leggings",               "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "28591", "Legs", "Earthsoul Leggings",                 "Alt", "1>2", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "24261", "Legs", "Whitemend Pants",                    "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30543", "Legs", "Pontifex Kilt",                      "PreRaid", "0", "Drop", "Warlord Kalithresh ", "The Steamvault (Heroic)")
LoonBestInSlot:AddItem(spec, "31343", "Legs", "Kamaei's Cerulean Skirt",            "PreRaid", "0", "Drop", "BoE World Drop")

LoonBestInSlot:AddItem(spec, "30873", "Feet", "Stillwater Boots",               "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32609", "Feet", "Boots of the Divine Light",      "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30092", "Feet", "Orca-Hide Boots",                "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30737", "Feet", "Gold-Leaf Wildboots",            "Alt", "1>3", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "30066", "Feet", "Tempest-Strider Boots",          "Alt", "2", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28752", "Feet", "Forestlord Striders",            "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27411", "Feet", "Slippers of Serenity",           "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts")
LoonBestInSlot:AddItem(spec, "27549", "Feet", "Wavefury Boots",                 "PreRaid", "0", "Drop", "Rokmar the Crackler", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27525", "Feet", "Jeweled Boots of Sanctification","PreRaid", "0", "Drop", "Warbringer O'mrogg", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "32370", "Neck", "Nadina's Pendant of Purity",     "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30018", "Neck", "Lord Sanguinar's Claim",         "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28609", "Neck", "Emberspur Talisman",             "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "30726", "Neck", "Archaic Charm of Presence",      "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28822", "Neck", "Teeth of Gruul",                 "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "31691", "Neck", "Natasha's Guardian Cord",        "Alt", "1>2", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "28233", "Neck", "Necklace of Resplendent Hope",   "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "29374", "Neck", "Necklace of Eternal Hope",       "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")

LoonBestInSlot:AddItem(spec, "32528", "Ring", "Blessed Band of Karabor",        "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29309", "Ring", "Band of the Eternal Restorer",   "Alt", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32238", "Ring", "Ring of Calming Waves",          "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29920", "Ring", "Phoenix-Ring of Rebirth",        "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30110", "Ring", "Coral Band of the Revived",      "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28763", "Ring", "Jade Ring of the Everliving",    "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "32385", "Ring", "Magtheridon's Head",             "Alt", "1>3", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "28790", "Ring", "Naaru Lightwarden's Band",       "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29169", "Ring", "Ring of Convalescence",          "PreRaid", "0", "Reputation", "Honor Hold Revered", "Logistics Officer Ulrike")
LoonBestInSlot:AddItem(spec, "29168", "Ring", "Ancestral Band",                 "PreRaid", "0", "Reputation", "Thrallmar Revered", "Quartermaster Urgronn")
LoonBestInSlot:AddItem(spec, "28259", "Ring", "Cosmic Lifeband",                "PreRaid", "0", "Drop", "Nethermancer Sepethrea", "The Mechanar")
LoonBestInSlot:AddItem(spec, "31923", "Ring", "Band of the Crystalline Void",   "PreRaid", "0", "Drop", "Yor", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "29814", "Ring", "Celestial Jewel Ring",           "PreRaid", "0", "Quest", "Hitting the Motherlode", "Netherstorm")
LoonBestInSlot:AddItem(spec, "29373", "Ring", "Band of Halos",                  "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")

LoonBestInSlot:AddItem(spec, "32496", "Trinket", "Memento of Tyrande",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29376", "Trinket", "Essence of the Martyr",           "BIS", "1>3", "Dungeon Token", "G'eras", "41 Badge of Justice")
LoonBestInSlot:AddItem(spec, "38288", "Trinket", "Direbrew Hops",                   "BIS", "2>3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "28190", "Trinket", "Scarab of the Infinite Cycle",    "Alt", "1>3", "Drop", "Aeonus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28590", "Trinket", "Ribbon of Sacrifice",             "Alt", "1>3", "Drop", "Opera Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "30841", "Trinket", "Lower City Prayerbook",           "PreRaid", "0", "Reputation", "Lower City Revered")
LoonBestInSlot:AddItem(spec, "24390", "Trinket", "Auslese's Light Channeler",       "PreRaid", "0", "Drop", "Broggok", "The Blood Furnace")
LoonBestInSlot:AddItem(spec, "25634", "Trinket", "Oshu'gun Relic",                  "PreRaid", "0", "Quest", "Gava'xi", "Nagrand")

LoonBestInSlot:AddItem(spec, "32500", "MH", "Crystal Spire of Karabor",         "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30918", "MH", "Hammer of Atonement",              "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity",                 "Alt", "1>3", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "30108", "MH", "Lightfathom Scepter",              "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28771", "MH", "Light's Justice",                  "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28522", "MH", "Shard of the Virtuous",            "Alt", "1>3", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "32451", "MH", "Gladiator's Salvation",            "PreRaid", "0", "PvP", "3150 Arena Points", "PvP Vendor")
LoonBestInSlot:AddItem(spec, "23556", "MH", "Hand of Eternity",                 "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29353", "MH", "Shockwave Truncheon",              "PreRaid", "0", "Drop", "Murmur", "Shadow Labyrinth (Heroic)")
LoonBestInSlot:AddItem(spec, "31342", "MH", "The Ancient Scepter of Sue-Min",   "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "29175", "MH", "Gavel of Pure Light",              "PreRaid", "0", "Reputation", "The Sha'tar Exalted")

LoonBestInSlot:AddItem(spec, "30882", "OH", "Bastion of Light",                 "BIS", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32255", "OH", "Felstone Bulwark",                 "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "29458", "OH", "Aegis of the Vindicator",          "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29923", "OH", "Talisman of the Sun King",         "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28728", "OH", "Aran's Soothing Sapphire",         "Alt", "1>2", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "28754", "OH", "Triptych Shield of the Ancients",  "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29274", "OH", "Tears of Heaven",                  "PreRaid", "0", "Dungeon Token", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "27477", "OH", "Faol's Signet of Cleansing",       "PreRaid", "0", "Drop", "Omor the Unscarred ", "Hellfire Ramparts (Heroic)")
LoonBestInSlot:AddItem(spec, "27772", "OH", "Stormshield of Renewal",           "PreRaid", "0", "Drop", "The Black Stalker", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "31292", "OH", "Crystal Pulse Shield",             "PreRaid", "0", "Drop", "BoE World Drop")

LoonBestInSlot:AddItem(spec, "28523", "Totem", "Totem of Healing Rains",        "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "27544", "Totem", "Totem of Spontaneous Regrowth", "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "25645", "Totem", "Totem of the Plains",           "PreRaid", "0", "Quest", "The Ultimate Bloodsport", "Nagrand")