local spec = LoonBestInSlot:RegisterSpec("Shaman", "Enhance")

LoonBestInSlot:AddItem(spec, "32235", "Head", "Cursed Vision of Sargeras",      "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31015", "Head", "Skyshatter Cover",               "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "Alt", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30190", "Head", "Cataclysm Helm",                 "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32474", "Head", "Surestrike Goggles v2.0",        "Alt", "2>3", "Profession", "Engineering (350)")
LoonBestInSlot:AddItem(spec, "29040", "Head", "Cyclone Helm",                   "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",    "Alt", "1", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28732", "Head", "Cowl of Defiance",               "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28224", "Head", "Wastewalker Helm",               "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "28182", "Head", "Helm of the Claw",               "PreRaid", "0", "Quest", "The Warlord's Hideout", "Watcher Jhang, Zangarmarsh")
LoonBestInSlot:AddItem(spec, "31109", "Head", "Stealther's Helmet of Second Sight", "PreRaid", "0", "Quest", "Teron Gorefiend, I am...", "Ancient Shadowmoon Spirit, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32581", "Shoulders", "Swiftstrike Shoulders",         "BIS", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32575", "Shoulders", "Shoulders of Lightning Reflexes", "Alt", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32377", "Shoulders", "Mantle of Darkness",            "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30055", "Shoulders", "Shoulderpads of the Stranger",  "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29043", "Shoulders", "Cyclone Shoulderplates",        "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion", "Alt", "1>2", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28755", "Shoulders", "Bladed Shoulderpads of the Merciless", "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "27797", "Shoulders", "Wastewalker Shoulderpads",      "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27434", "Shoulders", "Mantle of Perenolde",           "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills")
LoonBestInSlot:AddItem(spec, "25790", "Shoulders", "Expedition Scout's Epaulets",   "PreRaid", "0", "Quest", "Fel Embers", "Magus Zabraxis, Hellfire Peninsula")

LoonBestInSlot:AddItem(spec, "32323", "Back", "Shadowmoon Destroyer's Drape", "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "29994", "Back", "Thalassian Wildercloak",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "24259", "Back", "Vengeance Wrap",             "Alt", "1>3", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "28672", "Back", "Drape of the Dark Reavers",  "Alt", "1>3", "Drop", "Shade of Aran", "Karazhan")
LoonBestInSlot:AddItem(spec, "27878", "Back", "Auchenai Death Shroud",      "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "27892", "Back", "Cloak of the Inciter",       "PreRaid", "0", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")

LoonBestInSlot:AddItem(spec, "30905", "Chest", "Midnight Chestguard",           "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32252", "Chest", "Nether Shadow Tunic",           "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30185", "Chest", "Cataclysm Chestplate",          "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30730", "Chest", "Terrorweave Tunic",             "Alt", "1>3", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "29038", "Chest", "Cyclone Breastplate",           "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion", "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "25997", "Chest", "Gladiator's Linked Armor",      "Alt", "1", "PvP", "1875 Arena Points")
LoonBestInSlot:AddItem(spec, "29525", "Chest", "Primalstrike Vest",             "PreRaid", "0", "Profession", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29515", "Chest", "Ebon Netherscale Breastplate",  "PreRaid", "0", "Profession", "Dragonscale Leatherworking")

LoonBestInSlot:AddItem(spec, "30863", "Bracers", "Deadly Cuffs",                "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32574", "Bracers", "Bindings of Lightning Reflexes", "BIS", "3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "32324", "Bracers", "Insidious Bands",             "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "30091", "Bracers", "True-Aim Stalker Bands",      "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29966", "Bracers", "Vambraces of Ending",         "Alt", "2>3", "Drop", "High Astromancer Solarian", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28514", "Bracers", "Bracers of Maliciousness",    "Alt", "1>3", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "29527", "Bracers", "Primalstrike Bracers",        "PreRaid", "0", "Drop", "Elemental Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29517", "Bracers", "Ebon Netherscale Bracers",    "PreRaid", "0", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "28171", "Bracers", "Spymistress's Wristguards",   "PreRaid", "0", "Quest", "The Soul Devices", "Spy To'gun, Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "30399", "Bracers", "Nightstalker's Wristguards",  "PreRaid", "0", "Quest", "Down with Daelis", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32234", "Gloves", "Fists of Mukoa",                   "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32347", "Gloves", "Grips of Damnation",               "BIS", "3", "Drop", "Reliquary of the Lost", "Black Temple")
LoonBestInSlot:AddItem(spec, "29947", "Gloves", "Gloves of the Searing Grip",       "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt", "2", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30189", "Gloves", "Cataclysm Gauntlets",              "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28776", "Gloves", "Liar's Tongue Gloves",             "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30644", "Gloves", "Grips of Deftness",                "Alt", "1>2", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "30341", "Gloves", "Flesh Handler's Gauntlets",        "PreRaid", "0", "Quest", "The Flesh Lies...", "Agent Araxes, Netherstorm")
LoonBestInSlot:AddItem(spec, "29503", "Gloves", "Cobrascale Gloves",                "PreRaid", "0", "Profession", "Leatherworking (365)")
LoonBestInSlot:AddItem(spec, "28396", "Gloves", "Gloves of the Unbound",            "PreRaid", "0", "Drop", "Wrath-Scryer Soccothrates and Zereketh the Unbound", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "30106", "Belt", "Belt of One-Hundred Deaths",     "BIS", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "32346", "Belt", "Boneweave Girdle",               "Alt", "3", "Drop", "Reliquary of the Lost", "Black Temple")
LoonBestInSlot:AddItem(spec, "32265", "Belt", "Shadow-walker's Cord",           "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30879", "Belt", "Don Alejandro's Money Belt",     "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30919", "Belt", "Valestalker Girdle",             "Alt", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30040", "Belt", "Belt of Deep Shadow",            "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28828", "Belt", "Gronn-Stitched Girdle",          "Alt", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29526", "Belt", "Primalstrike Belt",              "Alt", "1>3", "Profession", "Elemental Leatherworking")
LoonBestInSlot:AddItem(spec, "29516", "Belt", "Ebon Netherscale Belt",          "PreRaid", "0", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "29247", "Belt", "Girdle of the Deathdealer",      "PreRaid", "0", "Drop", "Aeonus", "The Black Morass (Heroic)")
LoonBestInSlot:AddItem(spec, "27911", "Belt", "Epoch's Whispering Cinch",       "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "30900", "Legs", "Bow-stitched Leggings",              "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30898", "Legs", "Shady Dealer's Pantaloons",          "Alt", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30192", "Legs", "Cataclysm Legplates",                "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28741", "Legs", "Skulker's Greaves",                  "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "30257", "Legs", "Shattrath Leggings",                 "Alt", "1", "Quest", "Special Delivery to Shattrath City", "Netherstorm")
LoonBestInSlot:AddItem(spec, "31544", "Legs", "Clefthoof Hide Leggings",            "Alt", "1", "Quest", "Showdown - Baron Sablemane/Showdown", "Rexxar, Blade's Edge Mountains")

LoonBestInSlot:AddItem(spec, "32366", "Feet", "Shadowmaster's Boots",       "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32510", "Feet", "Softstep Boots of Tracking", "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "30880", "Feet", "Quickstrider Moccasins",     "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30039", "Feet", "Boots of Utter Darkness",    "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "30104", "Feet", "Cobra-Lash Boots",           "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28545", "Feet", "Edgewalker Longboots",       "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28746", "Feet", "Fiend Slayer Boots",         "Alt", "1", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "25686", "Feet", "Fel Leather Boots",          "Alt", "1", "Profession", "Leatherworking (350)")
LoonBestInSlot:AddItem(spec, "27867", "Feet", "Boots of the Unjust",        "PreRaid", "0", "Drop", "Avatar of the Martyred", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "30401", "Feet", "Farahlite Studded Boots",    "PreRaid", "0", "Quest", "A Fate Worse Than Death", "Netherstorm")

LoonBestInSlot:AddItem(spec, "32260", "Neck", "Choker of Endless Nightmares",   "BIS", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32591", "Neck", "Choker of Serrated Blades",      "BIS", "3", "Drop", "Trash Drop", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30017", "Neck", "Telonicus's Pendant of Mayhem",  "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30022", "Neck", "Pendant of the Perilous",        "Alt", "2>3", "Drop", "Trash Drop", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29381", "Neck", "Choker of Vile Intent",          "Alt", "1>2", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28509", "Neck", "Worgen Claw Necklace",           "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "31695", "Neck", "Natasha's Choker",               "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "27546", "Neck", "Traitor's Noose",                "PreRaid", "0", "Drop", "Mennu the Betrayer", "The Slave Pens (Heroic)")

LoonBestInSlot:AddItem(spec, "32497", "Ring", "Stormrage Signet Ring",              "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29301", "Ring", "Band of the Eternal Champion",       "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "29997", "Ring", "Band of the Ranger-General",         "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32526", "Ring", "Band of Devastation",                "Alt", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "32335", "Ring", "Unstoppable Aggressor's Ring",       "Alt", "3", "Drop", "Gurtogg Bloodboil", "Black Temple")
LoonBestInSlot:AddItem(spec, "32266", "Ring", "Ring of Deceitful Intent",           "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "30052", "Ring", "Ring of Lethality",                  "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28757", "Ring", "Ring of a Thousand Marks",           "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28649", "Ring", "Garona's Signet Ring",               "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "30738", "Ring", "Ring of Reciprocity",                "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29283", "Ring", "Violet Signet of the Master Assassin", "Alt", "1>2",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "30834", "Ring", "Shapeshifter's Signet",              "PreRaid", "0", "Reputation", "Nakodu", "Lower City Exalted")
LoonBestInSlot:AddItem(spec, "29379", "Ring", "Ring of Arathi Warlords",            "PreRaid", "0", "Dungeon Token", "25 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "28323", "Ring", "Ring of Umbral Doom",                "PreRaid", "0", "Drop", "Thorngrin the Tender", "The Botanica")
LoonBestInSlot:AddItem(spec, "31077", "Ring", "Slayer's Mark of the Redemption",    "PreRaid", "0", "Quest", "Dissension Amongst the Ranks...", "Thane Yoregar / Overlord Or'barokh, Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "32505", "Trinket", "Madness of the Betrayer",     "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "38287", "Trinket", "Empty Mug of Direbrew",       "BIS", "1>3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "28830", "Trinket", "Dragonspine Trophy",          "BIS", "1>3", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29383", "Trinket", "Bloodlust Brooch",            "BIS", "1>3", "Dungeon Token", "41 Badge of Justice", "G'eras, Shattrath City")
LoonBestInSlot:AddItem(spec, "31856", "Trinket", "Darkmoon Card: Crusade",      "Alt", "3", "Quest", "Darkmoon Blessings Deck", "Darkmoon Faire")
LoonBestInSlot:AddItem(spec, "28579", "Trinket", "Romulo's Poison Vial",        "Alt", "1>2", "Drop", "Julianne", "Karazhan")
LoonBestInSlot:AddItem(spec, "30627", "Trinket", "Tsunami Talisman",            "Alt", "2", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28034", "Trinket", "Hourglass of the Unraveller", "PreRaid", "0", "Drop", "Temporus", "The Black Morass")
LoonBestInSlot:AddItem(spec, "28288", "Trinket", "Abacus of Violent Odds",      "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")

LoonBestInSlot:AddItem(spec, "33669", "MH", "Vengeful Gladiator's Cleaver", "BIS(All)", "3", "PvP", "2625 Arena Points")
LoonBestInSlot:AddItem(spec, "32262", "MH", "Syphon of the Nathrezim",  "BIS(All)", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32946", "MH", "Claw of Molten Fury",      "Alt(MH)", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31965", "MH", "Merciless Gladiator's Cleaver", "Alt(All)", "3", "PvP", "1300 Arena Points")
LoonBestInSlot:AddItem(spec, "32236", "MH", "Rising Tide",              "Alt(All)", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32944", "MH", "Talon of the Phoenix",     "Alt(MH)", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29996", "MH", "Rod of the Sun King",      "Alt(All)", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28433", "MH", "Wicked Edge of the Planes", "Alt(MH)", "2>3", "Profession", "Master Axesmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "29924", "MH", "Netherbane",               "Alt(All)", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28439", "MH", "Dragonstrike",             "Alt(MH)", "2>3", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "28767", "MH", "The Decapitator",          "Alt(MH)", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28657", "MH", "Fool's Bane",              "Alt(MH)", "1>2", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "28308", "MH", "Gladiator's Cleaver",      "Alt(All)", "1>2", "PvP", "2625 Arena Points")
LoonBestInSlot:AddItem(spec, "28438", "MH", "Dragonmaw",                "PreRaid", "0", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "28437", "MH", "Drakefist Hammer",         "PreRaid", "0", "Profession", "Master Hammersmith (Blacksmith)")
LoonBestInSlot:AddItem(spec, "28392", "MH", "Reflex Blades",            "PreRaid", "0", "Drop", "Dalliah the Doomsayer", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "27872", "MH", "The Harvester of Souls",   "PreRaid", "0", "Drop", "Exarch Maladaar", "Auchenai Crypts (Heroic)")
LoonBestInSlot:AddItem(spec, "31139", "MH", "Fist of Reckoning",        "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "27815", "Totem", "Totem of the Astral Winds", "BIS", "1>3", "Drop", "Pandemonius", "Mana-Tombs (Heroic)")