local spec = LoonBestInSlot:RegisterSpec("Shaman", "Elemental")

LoonBestInSlot:AddItem(spec, "31014", "Head", "Skyshatter Headguard",           "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31095", "Head", "Helm of the Forgotten Protector", "BIS", "3", "Token", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32525", "Head", "Cowl of the Illidari High Lord", "Alt", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "30242", "Head", "Helm of the Vanquished Champion", "Alt", "2>3", "Token", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30171", "Head", "Cataclysm Headpiece",            "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29035", "Head", "Cyclone Faceguard",              "Alt", "1>3", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "29760", "Head", "Helm of the Fallen Champion",    "Alt", "1>3", "Token", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "32476", "Head", "Gadgetstorm Goggles",            "Alt", "2>3", "Profession", "Engineering (375)")
LoonBestInSlot:AddItem(spec, "28415", "Head", "Hood of Oblivion",               "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")
LoonBestInSlot:AddItem(spec, "28278", "Head", "Incanter's Cowl",                "PreRaid", "0", "Drop", "Pathaleon the Calculator", "The Mechanar")
LoonBestInSlot:AddItem(spec, "24266", "Head", "Spellstrike Hood",               "PreRaid", "0", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "31330", "Head", "Lightning Crown",                "PreRaid", "0", "Drop", "BoE World Drop")
LoonBestInSlot:AddItem(spec, "31107", "Head", "Shamanistic Helmet of Second Sight", "PreRaid", "0", "Quest", "Teron Gorefiend, I am...", "Shadowmoon Valley")

LoonBestInSlot:AddItem(spec, "31023", "Shoulders", "Skyshatter Mantle",                 "BIS", "3", "Drop", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "31103", "Shoulders", "Pauldrons of the Forgotten Protector", "BIS", "3", "Token", "Mother Shahraz", "Black Temple")
LoonBestInSlot:AddItem(spec, "32587", "Shoulders", "Mantle of Nimble Thought",          "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30884", "Shoulders", "Hatefury Mantle",                   "Alt", "3", "Drop", "Anetheron", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30248", "Shoulders", "Pauldrons of the Vanquished Champion", "Alt", "2>3", "Token", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30173", "Shoulders", "Cataclysm Shoulderpad",             "Alt", "2>3", "Drop", "Void Reaver", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29037", "Shoulders", "Cyclone Shoulderguards",            "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29763", "Shoulders", "Pauldrons of the Fallen Champion",  "Alt", "1>3", "Token", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "30925", "Shoulders", "Spaulders of the Torn-heart",       "PreRaid", "0", "Quest", "The Cipher of Damnation - The Third Fragment Recovered", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "32078", "Shoulders", "Pauldrons of Wild Magic",           "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "27796", "Shoulders", "Mana-Etched Spaulders",             "PreRaid", "0", "Quest", "Quagmirran", "The Slave Pens ")

LoonBestInSlot:AddItem(spec, "32331", "Back", "Cloak of the Illidari Council",      "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "28797", "Back", "Brute Cloak of the Ogre-Magi",       "Alt", "1>3", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "29992", "Back", "Royal Cloak of the Sunstriders",     "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "28766", "Back", "Ruby Drape of the Mysticant",        "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "30735", "Back", "Ancient Spellcloak of the Highborne", "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "29369", "Back", "Shawl of Shifting Probabilities",    "PreRaid", "0", "Heroics", "G'eras", "25 Badge of Justice")
LoonBestInSlot:AddItem(spec, "27981", "Back", "Sethekk Oracle Cloak",               "PreRaid", "0", "Drop", "Talon King Ikiss", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "31017", "Chest", "Skyshatter Breastplate",                "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "31091", "Chest", "Chestguard of the Forgotten Protector", "BIS", "3", "Token", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "32592", "Chest", "Chestguard of Relentless Storms",       "Alt", "3", "Drop", "Trash Mobs", "Hyjal Summit / Black Temple")
LoonBestInSlot:AddItem(spec, "30169", "Chest", "Cataclysm Chestpiece",                  "Alt", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30236", "Chest", "Chestguard of the Vanquished Champion", "Alt", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30107", "Chest", "Vestments of the Sea-Witch",            "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29519", "Chest", "Netherstrike Breastplate",              "Alt", "1>2", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "29522", "Chest", "Windhawk Hauberk",                      "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "29033", "Chest", "Cyclone Chestguard",                    "Alt", "1>2", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "29754", "Chest", "Chestguard of the Fallen Champion",     "Alt", "1>2", "Token", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "31340", "Chest", "Will of Edward the Odd",                "Alt", "1>2", "Drop", "World Drop")
LoonBestInSlot:AddItem(spec, "28191", "Chest", "Mana-Etched Vestments",                 "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")

LoonBestInSlot:AddItem(spec, "32586", "Bracers", "Bracers of Nimble Thought",   "BIS", "3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30870", "Bracers", "Cuffs of Devastation",        "Alt", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "29918", "Bracers", "Mindstorm Wristbands",        "Alt", "2>3", "Drop", "Al'ar", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "29521", "Bracers", "Netherstrike Bracers",        "Alt", "1>3", "Profession", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "29523", "Bracers", "Windhawk Bracers",            "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "24250", "Bracers", "Bracers of Havok",            "Alt", "1>2", "Profession", "Tailoring (350)")
LoonBestInSlot:AddItem(spec, "28638", "Bracers", "General's Mail Bracers",      "PreRaid", "0", "PvP", "9199 honor & 20x  Warsong Gulch Mark")

LoonBestInSlot:AddItem(spec, "31008", "Gloves", "Skyshatter Gauntlets",             "BIS", "3", "Drop", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31094", "Gloves", "Gloves of the Forgotten Protector", "BIS", "3", "Token", "Azgalor", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "32328", "Gloves", "Botanist's Gloves of Growth",      "Alt", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "32275", "Gloves", "Spiritwalker Gauntlets",           "Alt", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "28780", "Gloves", "Soul-Eater's Handwraps",           "Alt", "1>3", "Drop", "Magtheridon", "Magtheridon's Lair")
LoonBestInSlot:AddItem(spec, "30170", "Gloves", "Cataclysm Handgrips",              "Alt", "2>3", "Drop", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30239", "Gloves", "Gloves of the Vanquished Champion", "Alt", "2>3", "Token", "Leotheras the Blind", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "28507", "Gloves", "Handwraps of Flowing Thought",     "Alt", "1>2", "Drop", "Attumen the Huntsman", "Karazhan")
LoonBestInSlot:AddItem(spec, "29034", "Gloves", "Cyclone Handguards",               "Alt", "1>2", "Drop", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "29757", "Gloves", "Gloves of the Fallen Champion",    "Alt", "1>2", "Token", "The Curator", "Karazhan")
LoonBestInSlot:AddItem(spec, "27465", "Gloves", "Mana-Etched Gloves",               "PreRaid", "0", "Drop", "Omor the Unscarred", "Hellfire Ramparts")
LoonBestInSlot:AddItem(spec, "27793", "Gloves", "Earth Mantle Handwraps",           "PreRaid", "0", "Drop", "Mekgineer Steamrigger", "The Steamvault")
LoonBestInSlot:AddItem(spec, "31149", "Gloves", "Gloves of Pandemonium",            "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "32276", "Belt", "Flashfire Girdle",           "BIS", "3", "Drop", "Shade of Akama", "Black Temple")
LoonBestInSlot:AddItem(spec, "32256", "Belt", "Waistwrap of Infinity",      "Alt", "3", "Drop", "Supremus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30038", "Belt", "Belt of Blasting",           "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30064", "Belt", "Cord of Screaming Terrors",  "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29520", "Belt", "Netherstrike Belt",          "Alt", "1>3", "Drop", "Dragonscale Leatherworking")
LoonBestInSlot:AddItem(spec, "24256", "Belt", "Girdle of Ruination",        "Alt", "1>2", "Profession", "Tailoring (365)")
LoonBestInSlot:AddItem(spec, "29524", "Belt", "Windhawk Belt",              "Alt", "1>2", "Profession", "Tribal Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28799", "Belt", "Belt of Divine Inspiration", "Alt", "1>2", "Drop", "High King Maulgar", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "31283", "Belt", "Sash of Sealed Fate",        "PreRaid", "0", "Drop", "BOE World Drop")

LoonBestInSlot:AddItem(spec, "30916", "Legs", "Leggings of Channeled Elements", "BIS", "3", "Drop", "Kaz'rogal", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "31020", "Legs", "Skyshatter Legguards",           "BIS", "3", "Drop", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "31100", "Legs", "Leggings of the Forgotten Protector", "BIS", "3", "Token", "The Illidari Council", "Black Temple")
LoonBestInSlot:AddItem(spec, "30172", "Legs", "Cataclysm Leggings",             "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30245", "Legs", "Leggings of the Vanquished Champion", "Alt", "2>3", "Token", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "24262", "Legs", "Spellstrike Pants",              "Alt", "1>2", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30734", "Legs", "Leggings of the Seventh Circle", "Alt", "1>2", "Drop", "Doom Lord Kazzak", "Hellfire Peninsula")
LoonBestInSlot:AddItem(spec, "30541", "Legs", "Stormsong Kilt",                 "PreRaid", "0", "DressUpModel", "The Black Stalker ", "The Underbog (Heroic)")
LoonBestInSlot:AddItem(spec, "29142", "Legs", "Kurenai Kilt",                   "PreRaid", "0", "Reputation", "Kurenai Revered", "Trader Narasu")
LoonBestInSlot:AddItem(spec, "29141", "Legs", "Tempest Leggings",               "PreRaid", "0", "Reputation", "The Mag'har Revered", "Provisioner Nasela")

LoonBestInSlot:AddItem(spec, "32239", "Feet", "Slippers of the Seacaller",      "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "32352", "Feet", "Naturewarden's Treads",          "BIS", "3", "Drop", "Reliquary of the Lost", "Black Temple")
LoonBestInSlot:AddItem(spec, "32242", "Feet", "Boots of Oceanic Fury",          "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30067", "Feet", "Velvet Boots of the Guardian",   "Alt", "2>3", "Drop", "The Lurker Below", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30037", "Feet", "Boots of Blasting",              "Alt", "2>3", "Profession", "Tailoring (375)")
LoonBestInSlot:AddItem(spec, "30043", "Feet", "Hurricane Boots",                "Alt", "2>3", "Profession", "Leatherworking (375)")
LoonBestInSlot:AddItem(spec, "28517", "Feet", "Boots of Foretelling",           "Alt", "1>2", "Drop", "Maiden of Virtue", "Karazhan")
LoonBestInSlot:AddItem(spec, "28406", "Feet", "Sigil-Laced Boots",              "Alt", "1>2", "Drop", "Tavarok", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "28810", "Feet", "Windshear Boots",                "Alt", "1>2", "Drop", "Gruul the Dragonkiller", "Gruul's Lair")
LoonBestInSlot:AddItem(spec, "28179", "Feet", "Shattrath Jumpers",              "PreRaid", "0", "Quest", "Into the Heart of the Labyrinth", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "28640", "Feet", "General's Mail Sabatons",        "PreRaid", "0", "PvP", "13923 honor & 40x  Eye of the Storm Mark")

LoonBestInSlot:AddItem(spec, "32405", "Neck", "Verdant Sphere",                 "BIS", "2>3", "Token", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "30015", "Neck", "The Sun King's Talisman",        "BIS", "2>3", "Drop", "Kael'thas Sunstrider", "Tempest Keep")
LoonBestInSlot:AddItem(spec, "32349", "Neck", "Translucent Spellthread Necklace", "Alt", "3", "Drop", "Reliquary of the Lost", "Black Temple")
LoonBestInSlot:AddItem(spec, "28762", "Neck", "Adornment of Stolen Souls",      "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "28530", "Neck", "Brooch of Unquenchable Fury",    "Alt", "1>2", "Drop", "Moroes", "Karazhan")
LoonBestInSlot:AddItem(spec, "28134", "Neck", "Brooch of Heightened Potential", "Alt", "1>2", "Drop", "Blackheart the Inciter", "Shadow Labyrinth")
LoonBestInSlot:AddItem(spec, "31692", "Neck", "Natasha's Ember Necklace",       "PreRaid", "0", "Quest", "The Hound-Master", "Blade's Edge Mountains")
LoonBestInSlot:AddItem(spec, "29333", "Neck", "Torc of the Sethekk Prophet",    "PreRaid", "0", "Quest", "Brother Against Brother", "Sethekk Halls")

LoonBestInSlot:AddItem(spec, "32527", "Ring", "Ring of Ancient Knowledge",  "BIS", "3", "Drop", "Trash Drop", "Black Temple")
LoonBestInSlot:AddItem(spec, "29305", "Ring", "Band of the Eternal Sage",   "BIS", "3", "Reputation", "Soridormi", "The Scale of the Sands (Exalted)")
LoonBestInSlot:AddItem(spec, "32247", "Ring", "Ring of Captured Storms",    "Alt", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "30109", "Ring", "Ring of Endless Coils",      "Alt", "2>3", "Drop", "Lady Vashj", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "30667", "Ring", "Ring of Unrelenting Storms", "Alt", "1>3", "Drop", "Trash Drop", "Karazhan")
LoonBestInSlot:AddItem(spec, "29126", "Ring", "Seer's Signet",              "Alt", "1>2", "Reputation", "The Scryers Exalted", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "28753", "Ring", "Ring of Recurrence",         "Alt", "1>2", "Drop", "Chess Event", "Karazhan")
LoonBestInSlot:AddItem(spec, "29287", "Ring", "Violet Signet of the Archmage", "Alt", "1>2",  "Reputation", "Violet Eye (Exalted)", "Karazhan")
LoonBestInSlot:AddItem(spec, "28227", "Ring", "Sparking Arcanite Ring",     "PreRaid", "0", "Drop", "Epoch Hunter", "Old Hillsbrad Foothills (Heroic)")
LoonBestInSlot:AddItem(spec, "29367", "Ring", "Ring of Cryptic Dreams",     "PreRaid", "0", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "29352", "Ring", "Cobalt Band of Tyrigosa",    "PreRaid", "0", "Drop", "Nexus-Prince Shaffar", "Mana-Tombs (Heroic)")
LoonBestInSlot:AddItem(spec, "31290", "Ring", "Band of Dominion",           "PreRaid", "0", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29172", "Ring", "Ashyen's Gift",              "PreRaid", "0", "Reputation", "Cenarion Expedition Exalted", "Fedryen Swiftspear")

LoonBestInSlot:AddItem(spec, "28785", "Trinket", "The Lightning Capacitor",     "BIS", "1>3", "Drop", "Terestian Illhoof", "Karazhan")
LoonBestInSlot:AddItem(spec, "29370", "Trinket", "Icon of the Silver Crescent", "BIS", "1>3", "Dungeon Token", "41 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "38290", "Trinket", "Dark Iron Smoking Pipe",      "BIS", "3", "Drop", "Coren Direbrew", "Brewfest")
LoonBestInSlot:AddItem(spec, "30626", "Trinket", "Sextant of Unstable Currents", "Alt", "2>3", "Drop", "Fathom-Lord Karathress", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "27683", "Trinket", "Quagmirran's Eye",            "PreRaid", "0", "Drop", "Quagmirran", "The Slave Pens (Heroic)")
LoonBestInSlot:AddItem(spec, "29179", "Trinket", "Xi'ri's Gift",                "PreRaid", "0", "Reputation", "Almaador", "The Sha'tar Revered, Shattrath City")
LoonBestInSlot:AddItem(spec, "29132", "Trinket", "Scryer's Bloodgem",           "PreRaid", "0", "Reputation", "The Scryers Revered", "Quartermaster Enuril")
LoonBestInSlot:AddItem(spec, "28418", "Trinket", "Shiffar's Nexus-Horn",        "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "32374", "2H", "Zhar'doom, Greatstaff of the Devourer", "BIS", "3", "Drop", "Illidan Stormrage", "Black Temple")
LoonBestInSlot:AddItem(spec, "29988", "2H", "The Nexus Key",                        "Alt", "2", "Drop", "Kael'thas Sunstrider", "Tempest Keep")

LoonBestInSlot:AddItem(spec, "32237", "MH", "The Maelstrom's Fury",         "BIS", "3", "Drop", "High Warlord Naj'entus", "Black Temple")
LoonBestInSlot:AddItem(spec, "33687", "MH", "Vengeful Gladiator's Gavel",   "Alt", "3", "PvP", "3150 Arena Points")
LoonBestInSlot:AddItem(spec, "34009", "MH", "Hammer of Judgement",          "Alt", "3", "Drop", "Trash Drop", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30723", "MH", "Talon of the Tempest",         "Alt", "1>2", "Drop", "Doomwalker", "Shadowmoon Valley")
LoonBestInSlot:AddItem(spec, "28770", "MH", "Nathrezim Mindblade",          "Alt", "1>2", "Drop", "Prince Malchezaar", "Karazhan")
LoonBestInSlot:AddItem(spec, "32450", "MH", "Gladiator's Gavel",            "Alt", "1", "PvP", "3150 Arena Points")
LoonBestInSlot:AddItem(spec, "23554", "MH", "Eternium Runed Blade",         "PreRaid", "0", "Profession", "Blacksmithing (365)")
LoonBestInSlot:AddItem(spec, "30832", "MH", "Gavel of Unearthed Secrets",   "PreRaid", "0", "Reputation", "Lower City Exalted", "Nakodu")
LoonBestInSlot:AddItem(spec, "27868", "MH", "Runesong Dagger",              "PreRaid", "0", "Drop", "Warbringer O'mrogg", "The Shattered Halls")

LoonBestInSlot:AddItem(spec, "30909", "OH", "Antonidas's Aegis of Rapt Concentration", "BIS", "3", "Drop", "Archimonde", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30872", "OH", "Chronicle of Dark Secrets",            "BIS", "3", "Drop", "Rage Winterchill", "Hyjal Summit")
LoonBestInSlot:AddItem(spec, "30049", "OH", "Fathomstone",                          "Alt", "2>3", "Drop", "Hydross the Unstable", "Serpentshrine Cavern")
LoonBestInSlot:AddItem(spec, "29273", "OH", "Khadgar's Knapsack",                   "Alt", "1>2", "Dungeon Token", "25 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "29268", "OH", "Mazthoril Honor Shield",               "Alt", "1>2", "Dungeon Token", "33 Badges of Justice", "G'eras")
LoonBestInSlot:AddItem(spec, "28734", "OH", "Jewel of Infinite Possibilities",      "Alt", "1>2", "Drop", "Netherspite", "Karazhan")
LoonBestInSlot:AddItem(spec, "28603", "OH", "Talisman of Nightbane",                "Alt", "1>2", "Drop", "Nightbane", "Karazhan")
LoonBestInSlot:AddItem(spec, "28412", "OH", "Lamp of Peaceful Radiance",            "PreRaid", "0", "Drop", "Harbinger Skyriss", "The Arcatraz")

LoonBestInSlot:AddItem(spec, "32330", "Totem", "Totem of Ancestral Guidance",   "BIS", "3", "Drop", "Teron Gorefiend", "Black Temple")
LoonBestInSlot:AddItem(spec, "28248", "Totem", "Totem of the Void",             "Alt", "1>2", "Drop", "Cache of the Legion", "The Mechanar")
LoonBestInSlot:AddItem(spec, "23199", "Totem", "Totem of the Storm",            "Alt", "1>2", "Drop", "BOE World Drop")
LoonBestInSlot:AddItem(spec, "29389", "Totem", "Totem of the Pulsing Earth",    "Alt", "1>2", "Dungeon Token", "15 Badges of Justice", "G'eras")